/**
 * 导出所有单词数据为 JSON 格式
 * 用于生产环境批量导入
 */

// 所有单词数据
const allWords: Array<{
  word: string;
  phonetic: string;
  meaning: string;
  category: string;
}> = [];

// ========== A 字母开头 ==========
const wordsA = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃', category: '托福词汇' },
  { word: 'abide', phonetic: '/əˈbaɪd/', meaning: 'v. 遵守；忍受', category: 'GRE词汇' },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力；才能', category: '托福词汇' },
  { word: 'abnormal', phonetic: '/æbˈnɔːml/', meaning: 'adj. 反常的；异常的', category: '托福词汇' },
  { word: 'aboard', phonetic: '/əˈbɔːd/', meaning: 'adv./prep. 在船/飞机上', category: '托福词汇' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: 'v. 废除；废止', category: '托福词汇' },
  { word: 'abound', phonetic: '/əˈbaʊnd/', meaning: 'v. 大量存在', category: 'GRE词汇' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', meaning: 'adv. 在国外；到国外', category: '托福词汇' },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', meaning: 'adj. 突然的；唐突的', category: '托福词汇' },
  { word: 'absence', phonetic: '/ˈæbsəns/', meaning: 'n. 缺席；不在', category: '托福词汇' },
  { word: 'absent', phonetic: '/ˈæbsənt/', meaning: 'adj. 缺席的；不在的', category: '托福词汇' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', meaning: 'adj. 绝对的；完全的', category: '托福词汇' },
  { word: 'absorb', phonetic: '/əbˈzɔːb/', meaning: 'v. 吸收；理解', category: '托福词汇' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的 n. 摘要', category: '托福词汇' },
  { word: 'absurd', phonetic: '/əbˈsɜːd/', meaning: 'adj. 荒谬的', category: 'GRE词汇' },
  { word: 'abundance', phonetic: '/əˈbʌndəns/', meaning: 'n. 丰富', category: '托福词汇' },
  { word: 'abundant', phonetic: '/əˈbʌndənt/', meaning: 'adj. 丰富的；充裕的', category: '托福词汇' },
  { word: 'abuse', phonetic: '/əˈbjuːs/', meaning: 'n./v. 滥用；虐待', category: '托福词汇' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: 'adj. 学术的；学业的', category: '托福词汇' },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速；促进', category: '托福词汇' },
  { word: 'accent', phonetic: '/ˈæksent/', meaning: 'n. 口音；重音', category: '托福词汇' },
  { word: 'accept', phonetic: '/əkˈsept/', meaning: 'v. 接受；认可', category: '托福词汇' },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道；机会 v. 进入', category: '托福词汇' },
  { word: 'accessible', phonetic: '/əkˈsesəbl/', meaning: 'adj. 可接近的', category: '托福词汇' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', meaning: 'n. 事故；意外', category: '托福词汇' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；适应', category: '托福词汇' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴；伴随', category: '托福词汇' },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: 'v. 完成；实现', category: '托福词汇' },
  { word: 'accord', phonetic: '/əˈkɔːd/', meaning: 'v. 符合；给予 n. 协议', category: '托福词汇' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户；描述 v. 解释', category: '托福词汇' },
  { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: 'v. 积累；积聚', category: '托福词汇' },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 准确的；精确的', category: '托福词汇' },
  { word: 'accuse', phonetic: '/əˈkjuːz/', meaning: 'v. 指控；谴责', category: '托福词汇' },
  { word: 'accustomed', phonetic: '/əˈkʌstəmd/', meaning: 'adj. 习惯的', category: '托福词汇' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现；达到', category: '托福词汇' },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: 'v. 承认；确认', category: '托福词汇' },
  { word: 'acquaint', phonetic: '/əˈkweɪnt/', meaning: 'v. 使了解', category: 'GRE词汇' },
  { word: 'acquaintance', phonetic: '/əˈkweɪntəns/', meaning: 'n. 熟人；了解', category: '托福词汇' },
  { word: 'acquire', phonetic: '/əˈkwaɪə/', meaning: 'v. 获得；学到', category: '托福词汇' },
  { word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', meaning: 'n. 获得；收购', category: '托福词汇' },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编', category: '托福词汇' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的；适当的', category: '托福词汇' },
  { word: 'adhere', phonetic: '/ədˈhɪə/', meaning: 'v. 坚持；粘附', category: 'GRE词汇' },
  { word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', meaning: 'adj. 邻近的', category: '托福词汇' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整；适应', category: '托福词汇' },
  { word: 'administer', phonetic: '/ədˈmɪnɪstə/', meaning: 'v. 管理；执行', category: '托福词汇' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: 'n. 管理；行政', category: '托福词汇' },
  { word: 'admire', phonetic: '/ədˈmaɪə/', meaning: 'v. 钦佩；欣赏', category: '托福词汇' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认；准许进入', category: '托福词汇' },
  { word: 'adolescent', phonetic: '/ˌædəˈlesnt/', meaning: 'n. 青少年 adj. 青春期的', category: '托福词汇' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: 'v. 采用；收养', category: '托福词汇' },
  { word: 'adore', phonetic: '/əˈdɔː/', meaning: 'v. 崇拜；热爱', category: 'GRE词汇' },
  { word: 'adult', phonetic: '/ˈædʌlt/', meaning: 'n. 成年人 adj. 成年的', category: '托福词汇' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: 'v. 前进；推进 n. 进步', category: '托福词汇' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: 'n. 优势；好处', category: '托福词汇' },
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: 'n. 冒险；奇遇', category: '托福词汇' },
  { word: 'adverse', phonetic: '/ˈædvɜːs/', meaning: 'adj. 不利的；相反的', category: 'GRE词汇' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', meaning: 'v. 做广告；宣传', category: '托福词汇' },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: 'v. 提倡 n. 提倡者', category: '托福词汇' },
  { word: 'aesthetic', phonetic: '/iːsˈθetɪk/', meaning: 'adj. 美学的', category: 'GRE词汇' },
  { word: 'affair', phonetic: '/əˈfeə/', meaning: 'n. 事务；事件', category: '托福词汇' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响；感动', category: '托福词汇' },
  { word: 'affection', phonetic: '/əˈfekʃn/', meaning: 'n. 喜爱；感情', category: '托福词汇' },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', meaning: 'v. 使附属 n. 附属机构', category: '托福词汇' },
  { word: 'affirm', phonetic: '/əˈfɜːm/', meaning: 'v. 肯定；确认', category: 'GRE词汇' },
  { word: 'affluent', phonetic: '/ˈæfluənt/', meaning: 'adj. 富裕的', category: 'GRE词汇' },
  { word: 'afford', phonetic: '/əˈfɔːd/', meaning: 'v. 负担得起；提供', category: '托福词汇' },
  { word: 'aggravate', phonetic: '/ˈæɡrəveɪt/', meaning: 'v. 加重；恶化', category: 'GRE词汇' },
  { word: 'aggregate', phonetic: '/ˈæɡrɪɡət/', meaning: 'n. 总计 v. 聚集', category: 'GRE词汇' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', meaning: 'adj. 侵略的；有进取心的', category: '托福词汇' },
  { word: 'agitate', phonetic: '/ˈædʒɪteɪt/', meaning: 'v. 搅动；煽动', category: 'GRE词汇' },
  { word: 'agony', phonetic: '/ˈæɡəni/', meaning: 'n. 极大痛苦', category: 'GRE词汇' },
  { word: 'agreeable', phonetic: '/əˈɡriːəbl/', meaning: 'adj. 令人愉快的', category: 'GRE词汇' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃə/', meaning: 'n. 农业', category: '托福词汇' },
  { word: 'aircraft', phonetic: '/ˈeəkrɑːft/', meaning: 'n. 飞行器；飞机', category: '托福词汇' },
  { word: 'alarm', phonetic: '/əˈlɑːm/', meaning: 'n. 警报 v. 使惊恐', category: '托福词汇' },
  { word: 'alien', phonetic: '/ˈeɪliən/', meaning: 'adj. 外国的 n. 外国人', category: '托福词汇' },
  { word: 'allegiance', phonetic: '/əˈliːdʒəns/', meaning: 'n. 忠诚', category: 'GRE词汇' },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: 'v. 减轻；缓解', category: 'GRE词汇' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: 'v. 分配；拨给', category: '托福词汇' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: 'n. 津贴；允许', category: '托福词汇' },
  { word: 'alter', phonetic: '/ˈɔːltə/', meaning: 'v. 改变', category: '托福词汇' },
  { word: 'alternate', phonetic: '/ɔːlˈtɜːnət/', meaning: 'v. 交替 adj. 交替的', category: '托福词汇' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːnətɪv/', meaning: 'n. 替代品 adj. 替代的', category: '托福词汇' },
  { word: 'amateur', phonetic: '/ˈæmətə/', meaning: 'n. 业余爱好者', category: '托福词汇' },
  { word: 'amaze', phonetic: '/əˈmeɪz/', meaning: 'v. 使惊奇', category: '托福词汇' },
  { word: 'ambassador', phonetic: '/æmˈbæsədə/', meaning: 'n. 大使', category: '托福词汇' },
  { word: 'ambiguity', phonetic: '/ˌæmbɪˈɡjuːəti/', meaning: 'n. 模糊；歧义', category: 'GRE词汇' },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: 'adj. 模糊的；有歧义的', category: '托福词汇' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心；野心', category: '托福词汇' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', meaning: 'adj. 有雄心的', category: '托福词汇' },
  { word: 'amend', phonetic: '/əˈmend/', meaning: 'v. 修正；改进', category: 'GRE词汇' },
  { word: 'amiable', phonetic: '/ˈeɪmiəbl/', meaning: 'adj. 和蔼可亲的', category: 'GRE词汇' },
  { word: 'amid', phonetic: '/əˈmɪd/', meaning: 'prep. 在...之中', category: '托福词汇' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning: 'n. 数量 v. 总计', category: '托福词汇' },
  { word: 'ample', phonetic: '/ˈæmpl/', meaning: 'adj. 充足的', category: 'GRE词汇' },
  { word: 'amplify', phonetic: '/ˈæmplɪfaɪ/', meaning: 'v. 放大；增强', category: 'GRE词汇' },
  { word: 'amuse', phonetic: '/əˈmjuːz/', meaning: 'v. 使娱乐；使发笑', category: '托福词汇' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析', category: '托福词汇' },
  { word: 'analysis', phonetic: '/əˈnæləsɪs/', meaning: 'n. 分析', category: '托福词汇' },
  { word: 'ancestor', phonetic: '/ˈænsestə/', meaning: 'n. 祖先', category: '托福词汇' },
  { word: 'anchor', phonetic: '/ˈæŋkə/', meaning: 'n. 锚 v. 抛锚', category: '托福词汇' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', meaning: 'adj. 古代的', category: '托福词汇' },
  { word: 'anecdote', phonetic: '/ˈænɪkdəʊt/', meaning: 'n. 轶事', category: 'GRE词汇' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', meaning: 'n. 角度', category: '托福词汇' },
  { word: 'anguish', phonetic: '/ˈæŋɡwɪʃ/', meaning: 'n. 痛苦', category: 'GRE词汇' },
  { word: 'animate', phonetic: '/ˈænɪmeɪt/', meaning: 'v. 使有生气 adj. 有生命的', category: 'GRE词汇' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布', category: '托福词汇' },
  { word: 'annoy', phonetic: '/əˈnɔɪ/', meaning: 'v. 使恼怒', category: '托福词汇' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 年度的 n. 年刊', category: '托福词汇' },
  { word: 'anonymous', phonetic: '/əˈnɒnɪməs/', meaning: 'adj. 匿名的', category: '托福词汇' },
  { word: 'antagonist', phonetic: '/ænˈtæɡənɪst/', meaning: 'n. 对抗者；反派', category: 'GRE词汇' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: 'v. 预期；期望', category: '托福词汇' },
  { word: 'antique', phonetic: '/ænˈtiːk/', meaning: 'adj. 古老的 n. 古董', category: '托福词汇' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', meaning: 'n. 焦虑', category: '托福词汇' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', meaning: 'adj. 焦虑的；渴望的', category: '托福词汇' },
  { word: 'apartment', phonetic: '/əˈpɑːtmənt/', meaning: 'n. 公寓', category: '托福词汇' },
  { word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', meaning: 'v. 道歉', category: '托福词汇' },
  { word: 'appall', phonetic: '/əˈpɔːl/', meaning: 'v. 使惊骇', category: 'GRE词汇' },
  { word: 'apparent', phonetic: '/əˈpærənt/', meaning: 'adj. 明显的；表面上的', category: '托福词汇' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: 'n./v. 呼吁；吸引', category: '托福词汇' },
  { word: 'appearance', phonetic: '/əˈpɪərəns/', meaning: 'n. 外表；出现', category: '托福词汇' },
  { word: 'appease', phonetic: '/əˈpiːz/', meaning: 'v. 平息；安抚', category: 'GRE词汇' },
  { word: 'appendix', phonetic: '/əˈpendɪks/', meaning: 'n. 附录；阑尾', category: '托福词汇' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', meaning: 'n. 胃口；欲望', category: '托福词汇' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', meaning: 'v. 鼓掌；称赞', category: '托福词汇' },
  { word: 'applicable', phonetic: '/əˈplɪkəbl/', meaning: 'adj. 适用的', category: '托福词汇' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: 'n. 申请人', category: '托福词汇' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', meaning: 'n. 申请；应用', category: '托福词汇' },
  { word: 'apply', phonetic: '/əˈplaɪ/', meaning: 'v. 申请；应用', category: '托福词汇' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: 'v. 任命；指定', category: '托福词汇' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: 'v. 欣赏；感激', category: '托福词汇' },
  { word: 'apprehend', phonetic: '/ˌæprɪˈhend/', meaning: 'v. 逮捕；理解', category: 'GRE词汇' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: 'v. 接近 n. 方法', category: '托福词汇' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: 'adj. 适当的 v. 挪用', category: '托福词汇' },
  { word: 'approval', phonetic: '/əˈpruːvl/', meaning: 'n. 批准；赞同', category: '托福词汇' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准；赞同', category: '托福词汇' },
  { word: 'approximate', phonetic: '/əˈprɒksɪmət/', meaning: 'adj. 大约的 v. 接近', category: '托福词汇' },
  { word: 'apt', phonetic: '/æpt/', meaning: 'adj. 恰当的；易于...的', category: 'GRE词汇' },
  { word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', meaning: 'adj. 任意的；武断的', category: '托福词汇' },
  { word: 'arch', phonetic: '/ɑːtʃ/', meaning: 'n. 拱门 v. 弯曲', category: '托福词汇' },
  { word: 'architecture', phonetic: '/ˈɑːkɪtektʃə/', meaning: 'n. 建筑学', category: '托福词汇' },
  { word: 'arena', phonetic: '/əˈriːnə/', meaning: 'n. 竞技场；舞台', category: '托福词汇' },
  { word: 'argue', phonetic: '/ˈɑːɡjuː/', meaning: 'v. 争论；论证', category: '托福词汇' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现；产生', category: '托福词汇' },
  { word: 'aristocrat', phonetic: '/ˈærɪstəkræt/', meaning: 'n. 贵族', category: 'GRE词汇' },
  { word: 'arithmetic', phonetic: '/əˈrɪθmətɪk/', meaning: 'n. 算术', category: '托福词汇' },
  { word: 'armour', phonetic: '/ˈɑːmə/', meaning: 'n. 盔甲', category: '托福词汇' },
  { word: 'arouse', phonetic: '/əˈraʊz/', meaning: 'v. 引起；唤起', category: '托福词汇' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排；整理', category: '托福词汇' },
  { word: 'array', phonetic: '/əˈreɪ/', meaning: 'n. 一系列 v. 排列', category: '托福词汇' },
  { word: 'arrest', phonetic: '/əˈrest/', meaning: 'v./n. 逮捕', category: '托福词汇' },
  { word: 'arrogant', phonetic: '/ˈærəɡənt/', meaning: 'adj. 傲慢的', category: 'GRE词汇' },
  { word: 'articulate', phonetic: '/ɑːˈtɪkjələt/', meaning: 'adj. 清晰的 v. 清晰表达', category: 'GRE词汇' },
  { word: 'artificial', phonetic: '/ˌɑːtɪˈfɪʃl/', meaning: 'adj. 人造的', category: '托福词汇' },
  { word: 'artistic', phonetic: '/ɑːˈtɪstɪk/', meaning: 'adj. 艺术的', category: '托福词汇' },
  { word: 'ascend', phonetic: '/əˈsend/', meaning: 'v. 上升；攀登', category: 'GRE词汇' },
  { word: 'ascertain', phonetic: '/ˌæsəˈteɪn/', meaning: 'v. 查明', category: 'GRE词汇' },
  { word: 'ashamed', phonetic: '/əˈʃeɪmd/', meaning: 'adj. 惭愧的', category: '托福词汇' },
  { word: 'aspect', phonetic: '/ˈæspekt/', meaning: 'n. 方面；外观', category: '托福词汇' },
  { word: 'aspiration', phonetic: '/ˌæspəˈreɪʃn/', meaning: 'n. 渴望；抱负', category: '托福词汇' },
  { word: 'aspire', phonetic: '/əˈspaɪə/', meaning: 'v. 渴望', category: 'GRE词汇' },
  { word: 'assassinate', phonetic: '/əˈsæsɪneɪt/', meaning: 'v. 暗杀', category: 'GRE词汇' },
  { word: 'assault', phonetic: '/əˈsɔːlt/', meaning: 'n./v. 攻击', category: '托福词汇' },
  { word: 'assemble', phonetic: '/əˈsembl/', meaning: 'v. 集合；组装', category: '托福词汇' },
  { word: 'assembly', phonetic: '/əˈsembli/', meaning: 'n. 集会；装配', category: '托福词汇' },
  { word: 'assert', phonetic: '/əˈsɜːt/', meaning: 'v. 断言；主张', category: 'GRE词汇' },
  { word: 'assess', phonetic: '/əˈses/', meaning: 'v. 评估', category: '托福词汇' },
  { word: 'asset', phonetic: '/ˈæset/', meaning: 'n. 资产；优点', category: '托福词汇' },
  { word: 'assign', phonetic: '/əˈsaɪn/', meaning: 'v. 分配；指派', category: '托福词汇' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', meaning: 'n. 任务；作业', category: '托福词汇' },
  { word: 'assimilate', phonetic: '/əˈsɪmɪleɪt/', meaning: 'v. 同化；吸收', category: 'GRE词汇' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 帮助', category: '托福词汇' },
  { word: 'associate', phonetic: '/əˈsəʊʃieɪt/', meaning: 'v. 联想 n. 同事', category: '托福词汇' },
  { word: 'association', phonetic: '/əˌsəʊʃiˈeɪʃn/', meaning: 'n. 协会；关联', category: '托福词汇' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: 'v. 假定；承担', category: '托福词汇' },
  { word: 'assurance', phonetic: '/əˈʃʊərəns/', meaning: 'n. 保证；自信', category: '托福词汇' },
  { word: 'assure', phonetic: '/əˈʃʊə/', meaning: 'v. 保证；使确信', category: '托福词汇' },
  { word: 'astonish', phonetic: '/əˈstɒnɪʃ/', meaning: 'v. 使惊讶', category: '托福词汇' },
  { word: 'astronaut', phonetic: '/ˈæstrənɔːt/', meaning: 'n. 宇航员', category: '托福词汇' },
  { word: 'astronomy', phonetic: '/əˈstrɒnəmi/', meaning: 'n. 天文学', category: '托福词汇' },
  { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: 'n. 运动员', category: '托福词汇' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪə/', meaning: 'n. 大气；气氛', category: '托福词汇' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附上；依恋', category: '托福词汇' },
  { word: 'attack', phonetic: '/əˈtæk/', meaning: 'v./n. 攻击', category: '托福词汇' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: 'v. 获得；达到', category: '托福词汇' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'n./v. 尝试', category: '托福词汇' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: 'v. 出席；照顾', category: '托福词汇' },
  { word: 'attendant', phonetic: '/əˈtendənt/', meaning: 'n. 服务员 adj. 伴随的', category: '托福词汇' },
  { word: 'attention', phonetic: '/əˈtenʃn/', meaning: 'n. 注意', category: '托福词汇' },
  { word: 'attentive', phonetic: '/əˈtentɪv/', meaning: 'adj. 注意的；体贴的', category: '托福词汇' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: 'n. 态度', category: '托福词汇' },
  { word: 'attorney', phonetic: '/əˈtɜːni/', meaning: 'n. 律师', category: '托福词汇' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引', category: '托福词汇' },
  { word: 'attraction', phonetic: '/əˈtrækʃn/', meaning: 'n. 吸引力', category: '托福词汇' },
  { word: 'attractive', phonetic: '/əˈtræktɪv/', meaning: 'adj. 有吸引力的', category: '托福词汇' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', meaning: 'v. 归因 n. 属性', category: '托福词汇' },
  { word: 'auction', phonetic: '/ˈɔːkʃn/', meaning: 'n./v. 拍卖', category: 'GRE词汇' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: 'n. 观众；听众', category: '托福词汇' },
  { word: 'audit', phonetic: '/ˈɔːdɪt/', meaning: 'n./v. 审计', category: '托福词汇' },
  { word: 'augment', phonetic: '/ɔːɡˈment/', meaning: 'v. 增加', category: 'GRE词汇' },
  { word: 'authentic', phonetic: '/ɔːˈθentɪk/', meaning: 'adj. 真实的', category: '托福词汇' },
  { word: 'authority', phonetic: '/ɔːˈθɒrəti/', meaning: 'n. 权威；当局', category: '托福词汇' },
  { word: 'authorize', phonetic: '/ˈɔːθəraɪz/', meaning: 'v. 授权', category: '托福词汇' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', meaning: 'adj. 自动的', category: '托福词汇' },
  { word: 'autonomy', phonetic: '/ɔːˈtɒnəmi/', meaning: 'n. 自治', category: 'GRE词汇' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的', category: '托福词汇' },
  { word: 'avalanche', phonetic: '/ˈævəlɑːnʃ/', meaning: 'n. 雪崩', category: 'GRE词汇' },
  { word: 'avenge', phonetic: '/əˈvendʒ/', meaning: 'v. 报复', category: 'GRE词汇' },
  { word: 'avenue', phonetic: '/ˈævənjuː/', meaning: 'n. 大街；途径', category: '托福词汇' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'n. 平均 adj. 平均的', category: '托福词汇' },
  { word: 'avert', phonetic: '/əˈvɜːt/', meaning: 'v. 避免；转移', category: 'GRE词汇' },
  { word: 'aviation', phonetic: '/ˌeɪviˈeɪʃn/', meaning: 'n. 航空', category: '托福词汇' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免', category: '托福词汇' },
  { word: 'await', phonetic: '/əˈweɪt/', meaning: 'v. 等待', category: '托福词汇' },
  { word: 'awake', phonetic: '/əˈweɪk/', meaning: 'adj. 醒着的 v. 唤醒', category: '托福词汇' },
  { word: 'award', phonetic: '/əˈwɔːd/', meaning: 'n. 奖品 v. 授予', category: '托福词汇' },
  { word: 'aware', phonetic: '/əˈweə/', meaning: 'adj. 意识到的', category: '托福词汇' },
  { word: 'awe', phonetic: '/ɔː/', meaning: 'n. 敬畏', category: 'GRE词汇' },
  { word: 'awkward', phonetic: '/ˈɔːkwəd/', meaning: 'adj. 尴尬的；笨拙的', category: '托福词汇' },
];
allWords.push(...wordsA);

// 导出为 JSON
console.log(JSON.stringify(allWords, null, 2));
