// 扩展单词数据 - E和F字母
import { getSupabaseClient } from '../src/storage/database/supabase-client';

const supabase = getSupabaseClient();

const WORDS_TABLE = 'words';

// 更多单词数据
const moreWords = [
  // E
  { word: 'earnest', phonetic: '/ˈɜːnɪst/', meaning: 'adj. 认真的；诚挚的', category: '托福词汇' },
  { word: 'earring', phonetic: '/ˈɪərɪŋ/', meaning: 'n. 耳环', category: '日常词汇' },
  { word: 'earthquake', phonetic: '/ˈɜːθkweɪk/', meaning: 'n. 地震', category: '科技词汇' },
  { word: 'ease', phonetic: '/iːz/', meaning: 'n. 舒适；v. 缓解', category: '托福词汇' },
  { word: 'easily', phonetic: '/ˈiːzəli/', meaning: 'adv. 容易地', category: '托福词汇' },
  { word: 'eastward', phonetic: '/ˈiːstwəd/', meaning: 'adj. 向东的；adv. 向东', category: '托福词汇' },
  { word: 'easygoing', phonetic: '/ˌiːziˈɡəʊɪŋ/', meaning: 'adj. 随和的', category: '托福词汇' },
  { word: 'eccentric', phonetic: '/ɪkˈsentrɪk/', meaning: 'adj. 古怪的；n. 怪人', category: 'GRE词汇' },
  { word: 'eccentricity', phonetic: '/ˌeksenˈtrɪsəti/', meaning: 'n. 古怪；怪癖', category: 'GRE词汇' },
  { word: 'ecclesiastical', phonetic: '/ɪˌkliːziˈæstɪkl/', meaning: 'adj. 教会的；神职的', category: 'GRE词汇' },
  { word: 'eclipse', phonetic: '/ɪˈklɪps/', meaning: 'n. 日食；v. 使黯然失色', category: '托福词汇' },
  { word: 'ecological', phonetic: '/ˌiːkəˈlɒdʒɪkl/', meaning: 'adj. 生态的', category: '科技词汇' },
  { word: 'ecology', phonetic: '/iˈkɒlədʒi/', meaning: 'n. 生态学', category: '科技词汇' },
  { word: 'economic', phonetic: '/ˌiːkəˈnɒmɪk/', meaning: 'adj. 经济的', category: '托福词汇' },
  { word: 'economics', phonetic: '/ˌiːkəˈnɒmɪks/', meaning: 'n. 经济学', category: '商务词汇' },
  { word: 'economical', phonetic: '/ˌiːkəˈnɒmɪkl/', meaning: 'adj. 节约的；经济的', category: '托福词汇' },
  { word: 'economist', phonetic: '/ɪˈkɒnəmɪst/', meaning: 'n. 经济学家', category: '商务词汇' },
  { word: 'economize', phonetic: '/ɪˈkɒnəmaɪz/', meaning: 'v. 节约；节省', category: 'GRE词汇' },
  { word: 'economy', phonetic: '/ɪˈkɒnəmi/', meaning: 'n. 经济；节约', category: '托福词汇' },
  { word: 'ecosystem', phonetic: '/ˈiːkəʊsɪstəm/', meaning: 'n. 生态系统', category: '科技词汇' },
  { word: 'ecstasy', phonetic: '/ˈekstəsi/', meaning: 'n. 狂喜；出神', category: 'GRE词汇' },
  { word: 'ecstatic', phonetic: '/ekˈstætɪk/', meaning: 'adj. 狂喜的', category: 'GRE词汇' },
  { word: 'edge', phonetic: '/edʒ/', meaning: 'n. 边缘；v. 缓缓移动', category: '托福词汇' },
  { word: 'edible', phonetic: '/ˈedəbl/', meaning: 'adj. 可食用的', category: '托福词汇' },
  { word: 'edifice', phonetic: '/ˈedɪfɪs/', meaning: 'n. 大建筑物；宏伟大厦', category: 'GRE词汇' },
  { word: 'edify', phonetic: '/ˈedɪfaɪ/', meaning: 'v. 教化；启迪', category: 'GRE词汇' },
  { word: 'edit', phonetic: '/ˈedɪt/', meaning: 'v. 编辑', category: '托福词汇' },
  { word: 'edition', phonetic: '/ɪˈdɪʃn/', meaning: 'n. 版本', category: '托福词汇' },
  { word: 'editor', phonetic: '/ˈedɪtər/', meaning: 'n. 编辑', category: '托福词汇' },
  { word: 'editorial', phonetic: '/ˌedɪˈtɔːriəl/', meaning: 'n. 社论；adj. 编辑的', category: '托福词汇' },
  { word: 'educate', phonetic: '/ˈedʒukeɪt/', meaning: 'v. 教育', category: '托福词汇' },
  { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning: 'n. 教育', category: '托福词汇' },
  { word: 'educational', phonetic: '/ˌedʒuˈkeɪʃənl/', meaning: 'adj. 教育的', category: '托福词汇' },
  { word: 'educator', phonetic: '/ˈedʒukeɪtər/', meaning: 'n. 教育家', category: '托福词汇' },
  { word: 'eerie', phonetic: '/ˈɪəri/', meaning: 'adj. 可怕的；怪异的', category: 'GRE词汇' },
  { word: 'effect', phonetic: '/ɪˈfekt/', meaning: 'n. 效果；v. 引起', category: '托福词汇' },
  { word: 'effective', phonetic: '/ɪˈfektɪv/', meaning: 'adj. 有效的', category: '托福词汇' },
  { word: 'effectiveness', phonetic: '/ɪˈfektɪvnəs/', meaning: 'n. 效力；有效性', category: '托福词汇' },
  { word: 'effeminate', phonetic: '/ɪˈfemɪnət/', meaning: 'adj. 女人气的；柔弱的', category: 'GRE词汇' },
  { word: 'effervescence', phonetic: '/ˌefəˈvesns/', meaning: 'n. 沸腾；兴奋', category: 'GRE词汇' },
  { word: 'effervescent', phonetic: '/ˌefəˈvesnt/', meaning: 'adj. 沸腾的；兴高采烈的', category: 'GRE词汇' },
  { word: 'effete', phonetic: '/ɪˈfiːt/', meaning: 'adj. 衰老的；衰弱的', category: 'GRE词汇' },
  { word: 'efficacious', phonetic: '/ˌefɪˈkeɪʃəs/', meaning: 'adj. 有效的；灵验的', category: 'GRE词汇' },
  { word: 'efficacy', phonetic: '/ˈefɪkəsi/', meaning: 'n. 功效；效力', category: 'GRE词汇' },
  { word: 'efficiency', phonetic: '/ɪˈfɪʃnsi/', meaning: 'n. 效率', category: '托福词汇' },
  { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: 'adj. 高效的', category: '托福词汇' },
  { word: 'effigy', phonetic: '/ˈefɪdʒi/', meaning: 'n. 雕像；肖像', category: 'GRE词汇' },
  { word: 'effort', phonetic: '/ˈefət/', meaning: 'n. 努力', category: '托福词汇' },
  { word: 'effortless', phonetic: '/ˈefətləs/', meaning: 'adj. 不费力的', category: '托福词汇' },
  { word: 'effrontery', phonetic: '/ɪˈfrʌntəri/', meaning: 'n. 厚颜无耻', category: 'GRE词汇' },
  { word: 'effulgent', phonetic: '/ɪˈfʌldʒənt/', meaning: 'adj. 光辉的；灿烂的', category: 'GRE词汇' },
  { word: 'egalitarian', phonetic: '/ɪˌɡælɪˈteəriən/', meaning: 'adj. 平等主义的', category: 'GRE词汇' },
  { word: 'egocentric', phonetic: '/ˌiːɡəʊˈsentrɪk/', meaning: 'adj. 以自我为中心的', category: 'GRE词汇' },
  { word: 'egoism', phonetic: '/ˈiːɡəʊɪzəm/', meaning: 'n. 利己主义', category: 'GRE词汇' },
  { word: 'egoist', phonetic: '/ˈiːɡəʊɪst/', meaning: 'n. 利己主义者', category: 'GRE词汇' },
  { word: 'egotism', phonetic: '/ˈiːɡətɪzəm/', meaning: 'n. 自负；自大', category: 'GRE词汇' },
  { word: 'egotistical', phonetic: '/ˌiːɡəˈtɪstɪkl/', meaning: 'adj. 自负的', category: 'GRE词汇' },
  { word: 'egregious', phonetic: '/ɪˈɡriːdʒəs/', meaning: 'adj. 极坏的；惊人的', category: 'GRE词汇' },
  { word: 'egress', phonetic: '/ˈiːɡres/', meaning: 'n. 出口；v. 外出', category: 'GRE词汇' },
  { word: 'ejaculate', phonetic: '/ɪˈdʒækjuleɪt/', meaning: 'v. 突然喊出', category: 'GRE词汇' },
  { word: 'elaborate', phonetic: '/ɪˈlæbərət/', meaning: 'adj. 精心制作的；v. 详细阐述', category: '托福词汇' },
  { word: 'elapse', phonetic: '/ɪˈlæps/', meaning: 'v. 流逝；过去', category: 'GRE词汇' },
  { word: 'elastic', phonetic: '/ɪˈlæstɪk/', meaning: 'adj. 有弹性的', category: '托福词汇' },
  { word: 'elasticity', phonetic: '/ˌiːlæˈstɪsəti/', meaning: 'n. 弹性；灵活性', category: 'GRE词汇' },
  { word: 'elate', phonetic: '/ɪˈleɪt/', meaning: 'v. 使兴奋；使得意', category: 'GRE词汇' },
  { word: 'elated', phonetic: '/ɪˈleɪtɪd/', meaning: 'adj. 兴高采烈的', category: 'GRE词汇' },
  { word: 'elbow', phonetic: '/ˈelbəʊ/', meaning: 'n. 肘；v. 用肘推', category: '托福词汇' },
  { word: 'elder', phonetic: '/ˈeldər/', meaning: 'n. 长者；adj. 年长的', category: '托福词汇' },
  { word: 'elderly', phonetic: '/ˈeldəli/', meaning: 'adj. 年长的', category: '托福词汇' },
  { word: 'elect', phonetic: '/ɪˈlekt/', meaning: 'v. 选举；adj. 当选的', category: '托福词汇' },
  { word: 'election', phonetic: '/ɪˈlekʃn/', meaning: 'n. 选举', category: '托福词汇' },
  { word: 'elective', phonetic: '/ɪˈlektɪv/', meaning: 'adj. 选修的；n. 选修课', category: '托福词汇' },
  { word: 'electric', phonetic: '/ɪˈlektrɪk/', meaning: 'adj. 电的', category: '科技词汇' },
  { word: 'electrical', phonetic: '/ɪˈlektrɪkl/', meaning: 'adj. 电的；电气科学的', category: '科技词汇' },
  { word: 'electrician', phonetic: '/ɪˌlekˈtrɪʃn/', meaning: 'n. 电工', category: '科技词汇' },
  { word: 'electricity', phonetic: '/ɪˌlekˈtrɪsəti/', meaning: 'n. 电', category: '科技词汇' },
  { word: 'electrify', phonetic: '/ɪˈlektrɪfaɪ/', meaning: 'v. 使通电；使震惊', category: '托福词汇' },
  { word: 'electron', phonetic: '/ɪˈlektrɒn/', meaning: 'n. 电子', category: '科技词汇' },
  { word: 'electronic', phonetic: '/ɪˌlekˈtrɒnɪk/', meaning: 'adj. 电子的', category: '科技词汇' },
  { word: 'electronics', phonetic: '/ɪˌlekˈtrɒnɪks/', meaning: 'n. 电子学', category: '科技词汇' },
  { word: 'elegance', phonetic: '/ˈelɪɡəns/', meaning: 'n. 优雅', category: '托福词汇' },
  { word: 'elegant', phonetic: '/ˈelɪɡənt/', meaning: 'adj. 优雅的', category: '托福词汇' },
  { word: 'elegy', phonetic: '/ˈelədʒi/', meaning: 'n. 挽歌；哀歌', category: 'GRE词汇' },
  { word: 'element', phonetic: '/ˈelɪmənt/', meaning: 'n. 元素；要素', category: '托福词汇' },
  { word: 'elementary', phonetic: '/ˌelɪˈmentri/', meaning: 'adj. 基本的；初级的', category: '托福词汇' },
  { word: 'elephant', phonetic: '/ˈelɪfənt/', meaning: 'n. 大象', category: '日常词汇' },
  { word: 'elevate', phonetic: '/ˈelɪveɪt/', meaning: 'v. 提升；举起', category: '托福词汇' },
  { word: 'elevated', phonetic: '/ˈelɪveɪtɪd/', meaning: 'adj. 提高的；高尚的', category: 'GRE词汇' },
  { word: 'elevation', phonetic: '/ˌelɪˈveɪʃn/', meaning: 'n. 提高；海拔', category: '托福词汇' },
  { word: 'elevator', phonetic: '/ˈelɪveɪtər/', meaning: 'n. 电梯', category: '托福词汇' },
  { word: 'eleventh', phonetic: '/ɪˈlevnθ/', meaning: 'adj. 第十一的', category: '日常词汇' },
  { word: 'elicit', phonetic: '/ɪˈlɪsɪt/', meaning: 'v. 引出；引起', category: 'GRE词汇' },
  { word: 'eligible', phonetic: '/ˈelɪdʒəbl/', meaning: 'adj. 有资格的', category: '托福词汇' },
  { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning: 'v. 消除；淘汰', category: '托福词汇' },
  { word: 'elimination', phonetic: '/ɪˌlɪmɪˈneɪʃn/', meaning: 'n. 消除；淘汰', category: '托福词汇' },
  { word: 'elite', phonetic: '/eɪˈliːt/', meaning: 'n. 精英', category: '托福词汇' },
  { word: 'elixir', phonetic: '/ɪˈlɪksər/', meaning: 'n. 万灵药；仙丹', category: 'GRE词汇' },
  { word: 'elongate', phonetic: '/ˈiːlɒŋɡeɪt/', meaning: 'v. 延长；伸长', category: 'GRE词汇' },
  { word: 'elope', phonetic: '/ɪˈləʊp/', meaning: 'v. 私奔', category: 'GRE词汇' },
  { word: 'eloquence', phonetic: '/ˈeləkwəns/', meaning: 'n. 雄辩；口才', category: 'GRE词汇' },
  { word: 'eloquent', phonetic: '/ˈeləkwənt/', meaning: 'adj. 雄辩的；有说服力的', category: 'GRE词汇' },
  { word: 'elucidate', phonetic: '/ɪˈluːsɪdeɪt/', meaning: 'v. 阐明；解释', category: 'GRE词汇' },
  { word: 'elusive', phonetic: '/ɪˈluːsɪv/', meaning: 'adj. 难以捉摸的', category: 'GRE词汇' },
  { word: 'emaciated', phonetic: '/ɪˈmeɪʃieɪtɪd/', meaning: 'adj. 消瘦的；衰弱的', category: '医学词汇' },
  { word: 'emanate', phonetic: '/ˈeməneɪt/', meaning: 'v. 发出；散发', category: 'GRE词汇' },
  { word: 'emancipate', phonetic: '/ɪˈmænsɪpeɪt/', meaning: 'v. 解放；释放', category: 'GRE词汇' },
  { word: 'emancipation', phonetic: '/ɪˌmænsɪˈpeɪʃn/', meaning: 'n. 解放', category: 'GRE词汇' },
  { word: 'embargo', phonetic: '/ɪmˈbɑːɡəʊ/', meaning: 'n. 禁运；v. 禁止', category: '商务词汇' },
  { word: 'embark', phonetic: '/ɪmˈbɑːk/', meaning: 'v. 上船；开始', category: '托福词汇' },
  { word: 'embarrass', phonetic: '/ɪmˈbærəs/', meaning: 'v. 使尴尬', category: '托福词汇' },
  { word: 'embarrassing', phonetic: '/ɪmˈbærəsɪŋ/', meaning: 'adj. 令人尴尬的', category: '托福词汇' },
  { word: 'embarrassment', phonetic: '/ɪmˈbærəsmənt/', meaning: 'n. 尴尬', category: '托福词汇' },
  { word: 'embattled', phonetic: '/ɪmˈbætld/', meaning: 'adj. 处于困境的；严阵以待的', category: 'GRE词汇' },
  { word: 'embellish', phonetic: '/ɪmˈbelɪʃ/', meaning: 'v. 装饰；润色', category: 'GRE词汇' },
  { word: 'ember', phonetic: '/ˈembər/', meaning: 'n. 余烬', category: 'GRE词汇' },
  { word: 'embezzle', phonetic: '/ɪmˈbezl/', meaning: 'v. 挪用；贪污', category: '法律词汇' },
  { word: 'emblem', phonetic: '/ˈembləm/', meaning: 'n. 徽章；象征', category: '托福词汇' },
  { word: 'emblematic', phonetic: '/ˌembləˈmætɪk/', meaning: 'adj. 象征性的', category: 'GRE词汇' },
  { word: 'embody', phonetic: '/ɪmˈbɒdi/', meaning: 'v. 体现；包含', category: '托福词汇' },
  { word: 'embolden', phonetic: '/ɪmˈbəʊldən/', meaning: 'v. 使大胆；鼓励', category: 'GRE词汇' },
  { word: 'embrace', phonetic: '/ɪmˈbreɪs/', meaning: 'v. 拥抱；接受', category: '托福词汇' },
  { word: 'embroidery', phonetic: '/ɪmˈbrɔɪdəri/', meaning: 'n. 刺绣', category: 'GRE词汇' },
  { word: 'embroil', phonetic: '/ɪmˈbrɔɪl/', meaning: 'v. 使卷入；使混乱', category: 'GRE词汇' },
  { word: 'embryo', phonetic: '/ˈembriəʊ/', meaning: 'n. 胚胎', category: '医学词汇' },
  { word: 'embryonic', phonetic: '/ˌembriˈɒnɪk/', meaning: 'adj. 胚胎的；萌芽的', category: '医学词汇' },
  { word: 'emend', phonetic: '/ɪˈmend/', meaning: 'v. 修订；校正', category: 'GRE词汇' },
  { word: 'emerald', phonetic: '/ˈemərəld/', meaning: 'n. 祖母绿；翡翠', category: 'GRE词汇' },
  { word: 'emerge', phonetic: '/ɪˈmɜːdʒ/', meaning: 'v. 出现；浮现', category: '托福词汇' },
  { word: 'emergence', phonetic: '/ɪˈmɜːdʒəns/', meaning: 'n. 出现', category: '托福词汇' },
  { word: 'emergency', phonetic: '/ɪˈmɜːdʒənsi/', meaning: 'n. 紧急情况', category: '托福词汇' },
  { word: 'emergent', phonetic: '/ɪˈmɜːdʒənt/', meaning: 'adj. 新兴的；出现的', category: 'GRE词汇' },
  { word: 'emigrant', phonetic: '/ˈemɪɡrənt/', meaning: 'n. 移民；adj. 移居的', category: 'GRE词汇' },
  { word: 'emigrate', phonetic: '/ˈemɪɡreɪt/', meaning: 'v. 移居外国', category: '托福词汇' },
  { word: 'emigration', phonetic: '/ˌemɪˈɡreɪʃn/', meaning: 'n. 移居外国', category: 'GRE词汇' },
  { word: 'eminent', phonetic: '/ˈemɪnənt/', meaning: 'adj. 杰出的', category: 'GRE词汇' },
  { word: 'emission', phonetic: '/ɪˈmɪʃn/', meaning: 'n. 排放；散发', category: '科技词汇' },
  { word: 'emit', phonetic: '/ɪˈmɪt/', meaning: 'v. 发出；发射', category: '托福词汇' },
  { word: 'emotion', phonetic: '/ɪˈməʊʃn/', meaning: 'n. 情绪', category: '托福词汇' },
  { word: 'emotional', phonetic: '/ɪˈməʊʃənl/', meaning: 'adj. 情绪的；易激动的', category: '托福词汇' },
  { word: 'emotionalism', phonetic: '/ɪˈməʊʃənəlɪzəm/', meaning: 'n. 感情主义', category: 'GRE词汇' },
  { word: 'emotionally', phonetic: '/ɪˈməʊʃənəli/', meaning: 'adv. 在情绪上', category: '托福词汇' },
  { word: 'emotive', phonetic: '/ɪˈməʊtɪv/', meaning: 'adj. 激起感情的', category: 'GRE词汇' },
  { word: 'empathy', phonetic: '/ˈempəθi/', meaning: 'n. 同情；共鸣', category: 'GRE词汇' },
  { word: 'emperor', phonetic: '/ˈempərər/', meaning: 'n. 皇帝', category: '托福词汇' },
  { word: 'emphasis', phonetic: '/ˈemfəsɪs/', meaning: 'n. 强调', category: '托福词汇' },
  { word: 'emphasize', phonetic: '/ˈemfəsaɪz/', meaning: 'v. 强调', category: '托福词汇' },
  { word: 'emphatic', phonetic: '/ɪmˈfætɪk/', meaning: 'adj. 强调的；断然的', category: 'GRE词汇' },
  { word: 'empirical', phonetic: '/ɪmˈpɪrɪkl/', meaning: 'adj. 经验的；实证的', category: 'GRE词汇' },
  { word: 'empiricism', phonetic: '/ɪmˈpɪrɪsɪzəm/', meaning: 'n. 经验主义', category: 'GRE词汇' },
  { word: 'employ', phonetic: '/ɪmˈplɔɪ/', meaning: 'v. 雇用；使用', category: '托福词汇' },
  { word: 'employee', phonetic: '/ɪmˈplɔɪiː/', meaning: 'n. 雇员', category: '托福词汇' },
  { word: 'employer', phonetic: '/ɪmˈplɔɪər/', meaning: 'n. 雇主', category: '托福词汇' },
  { word: 'employment', phonetic: '/ɪmˈplɔɪmənt/', meaning: 'n. 雇用；就业', category: '托福词汇' },
  { word: 'empower', phonetic: '/ɪmˈpaʊər/', meaning: 'v. 授权；使能够', category: '商务词汇' },
  { word: 'emptiness', phonetic: '/ˈemptinəs/', meaning: 'n. 空虚', category: '托福词汇' },
  { word: 'empty', phonetic: '/ˈempti/', meaning: 'adj. 空的；v. 倒空', category: '托福词汇' },
  { word: 'emulate', phonetic: '/ˈemjuleɪt/', meaning: 'v. 模仿；超越', category: 'GRE词汇' },
  { word: 'emulation', phonetic: '/ˌemjuˈleɪʃn/', meaning: 'n. 模仿；竞争', category: 'GRE词汇' },
  { word: 'emulsify', phonetic: '/ɪˈmʌlsɪfaɪ/', meaning: 'v. 使乳化', category: '科技词汇' },
  { word: 'emulsion', phonetic: '/ɪˈmʌlʃn/', meaning: 'n. 乳状液', category: '科技词汇' },
  { word: 'enable', phonetic: '/ɪˈneɪbl/', meaning: 'v. 使能够', category: '托福词汇' },
  { word: 'enact', phonetic: '/ɪˈnækt/', meaning: 'v. 制定；颁布', category: '法律词汇' },
  { word: 'enactment', phonetic: '/ɪˈnæktmənt/', meaning: 'n. 制定；法律', category: '法律词汇' },
  { word: 'enamel', phonetic: '/ɪˈnæml/', meaning: 'n. 搪瓷；珐琅', category: 'GRE词汇' },
  { word: 'enchant', phonetic: '/ɪnˈtʃɑːnt/', meaning: 'v. 使着迷', category: 'GRE词汇' },
  { word: 'enchantment', phonetic: '/ɪnˈtʃɑːntmənt/', meaning: 'n. 魅力；着迷', category: 'GRE词汇' },
  { word: 'encircle', phonetic: '/ɪnˈsɜːkl/', meaning: 'v. 包围；环绕', category: 'GRE词汇' },
  { word: 'enclose', phonetic: '/ɪnˈkləʊz/', meaning: 'v. 围住；附上', category: '托福词汇' },
  { word: 'enclosure', phonetic: '/ɪnˈkləʊʒər/', meaning: 'n. 围栏；附件', category: '托福词汇' },
  { word: 'encompass', phonetic: '/ɪnˈkʌmpəs/', meaning: 'v. 包含；围绕', category: 'GRE词汇' },
  { word: 'encounter', phonetic: '/ɪnˈkaʊntər/', meaning: 'v. 遇到；n. 遭遇', category: '托福词汇' },
  { word: 'encourage', phonetic: '/ɪnˈkʌrɪdʒ/', meaning: 'v. 鼓励', category: '托福词汇' },
  { word: 'encouragement', phonetic: '/ɪnˈkʌrɪdʒmənt/', meaning: 'n. 鼓励', category: '托福词汇' },
  { word: 'encroach', phonetic: '/ɪnˈkrəʊtʃ/', meaning: 'v. 侵犯；蚕食', category: 'GRE词汇' },
  { word: 'encrust', phonetic: '/ɪnˈkrʌst/', meaning: 'v. 包壳；形成硬壳', category: 'GRE词汇' },
  { word: 'encumber', phonetic: '/ɪnˈkʌmbər/', meaning: 'v. 阻碍；拖累', category: 'GRE词汇' },
  { word: 'encyclopedia', phonetic: '/ɪnˌsaɪkləˈpiːdiə/', meaning: 'n. 百科全书', category: '托福词汇' },
  { word: 'encyclopedic', phonetic: '/ɪnˌsaɪkləˈpiːdɪk/', meaning: 'adj. 百科全书的；知识渊博的', category: 'GRE词汇' },
  { word: 'endanger', phonetic: '/ɪnˈdeɪndʒər/', meaning: 'v. 危及；危害', category: '托福词汇' },
  { word: 'endear', phonetic: '/ɪnˈdɪər/', meaning: 'v. 使受喜爱', category: 'GRE词汇' },
  { word: 'endearment', phonetic: '/ɪnˈdɪəmənt/', meaning: 'n. 爱慕表示', category: 'GRE词汇' },
  { word: 'endeavor', phonetic: '/ɪnˈdevər/', meaning: 'v. 努力；n. 努力', category: 'GRE词汇' },
  { word: 'endemic', phonetic: '/enˈdemɪk/', meaning: 'adj. 地方性的；特有的', category: 'GRE词汇' },
  { word: 'ending', phonetic: '/ˈendɪŋ/', meaning: 'n. 结局；结尾', category: '托福词汇' },
  { word: 'endless', phonetic: '/ˈendləs/', meaning: 'adj. 无尽的', category: '托福词汇' },
  { word: 'endocrine', phonetic: '/ˈendəʊkrɪn/', meaning: 'adj. 内分泌的；n. 内分泌腺', category: '医学词汇' },
  { word: 'endow', phonetic: '/ɪnˈdaʊ/', meaning: 'v. 赋予；捐赠', category: 'GRE词汇' },
  { word: 'endowment', phonetic: '/ɪnˈdaʊmənt/', meaning: 'n. 天赋；捐赠', category: 'GRE词汇' },
  { word: 'endurance', phonetic: '/ɪnˈdjʊərəns/', meaning: 'n. 耐力', category: '托福词汇' },
  { word: 'endure', phonetic: '/ɪnˈdjʊər/', meaning: 'v. 忍受；持续', category: '托福词汇' },
  { word: 'enduring', phonetic: '/ɪnˈdjʊərɪŋ/', meaning: 'adj. 持久的', category: '托福词汇' },
  { word: 'enemy', phonetic: '/ˈenəmi/', meaning: 'n. 敌人', category: '托福词汇' },
  { word: 'energetic', phonetic: '/ˌenəˈdʒetɪk/', meaning: 'adj. 精力充沛的', category: '托福词汇' },
  { word: 'energize', phonetic: '/ˈenədʒaɪz/', meaning: 'v. 使充满活力', category: '托福词汇' },
  { word: 'energy', phonetic: '/ˈenədʒi/', meaning: 'n. 能量；精力', category: '托福词汇' },
  { word: 'enervate', phonetic: '/ˈenəveɪt/', meaning: 'v. 使衰弱', category: 'GRE词汇' },
  { word: 'enforced', phonetic: '/ɪnˈfɔːst/', meaning: 'adj. 强制的', category: '托福词汇' },
  { word: 'enforce', phonetic: '/ɪnˈfɔːs/', meaning: 'v. 实施；强制执行', category: '托福词汇' },
  { word: 'enforcement', phonetic: '/ɪnˈfɔːsmənt/', meaning: 'n. 实施；执行', category: '法律词汇' },
  { word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', meaning: 'v. 参与；订婚', category: '托福词汇' },
  { word: 'engagement', phonetic: '/ɪnˈɡeɪdʒmənt/', meaning: 'n. 订婚；约会', category: '托福词汇' },
  { word: 'engaging', phonetic: '/ɪnˈɡeɪdʒɪŋ/', meaning: 'adj. 迷人的', category: 'GRE词汇' },
  { word: 'engine', phonetic: '/ˈendʒɪn/', meaning: 'n. 发动机', category: '科技词汇' },
  { word: 'engineer', phonetic: '/ˌendʒɪˈnɪər/', meaning: 'n. 工程师；v. 设计', category: '托福词汇' },
  { word: 'engineering', phonetic: '/ˌendʒɪˈnɪərɪŋ/', meaning: 'n. 工程学', category: '科技词汇' },
  { word: 'engrave', phonetic: '/ɪnˈɡreɪv/', meaning: 'v. 雕刻', category: 'GRE词汇' },
  { word: 'engross', phonetic: '/ɪnˈɡrəʊs/', meaning: 'v. 使全神贯注', category: 'GRE词汇' },
  { word: 'engulf', phonetic: '/ɪnˈɡʌlf/', meaning: 'v. 吞没；淹没', category: 'GRE词汇' },
  { word: 'enhance', phonetic: '/ɪnˈhɑːns/', meaning: 'v. 增强；提高', category: '托福词汇' },
  { word: 'enhancement', phonetic: '/ɪnˈhɑːnsmənt/', meaning: 'n. 增强；改进', category: '托福词汇' },
  { word: 'enigma', phonetic: '/ɪˈnɪɡmə/', meaning: 'n. 谜；难以理解的人或事', category: 'GRE词汇' },
  { word: 'enigmatic', phonetic: '/ˌenɪɡˈmætɪk/', meaning: 'adj. 神秘的；难以理解的', category: 'GRE词汇' },
  { word: 'enjoin', phonetic: '/ɪnˈdʒɔɪn/', meaning: 'v. 命令；禁止', category: '法律词汇' },
  { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning: 'v. 享受', category: '托福词汇' },
  { word: 'enjoyable', phonetic: '/ɪnˈdʒɔɪəbl/', meaning: 'adj. 令人愉快的', category: '托福词汇' },
  { word: 'enjoyment', phonetic: '/ɪnˈdʒɔɪmənt/', meaning: 'n. 享受；乐趣', category: '托福词汇' },
  { word: 'enlarge', phonetic: '/ɪnˈlɑːdʒ/', meaning: 'v. 扩大', category: '托福词汇' },
  { word: 'enlighten', phonetic: '/ɪnˈlaɪtn/', meaning: 'v. 启发；教导', category: 'GRE词汇' },
  { word: 'enlightened', phonetic: '/ɪnˈlaɪtnd/', meaning: 'adj. 开明的；有见识的', category: 'GRE词汇' },
  { word: 'enlightenment', phonetic: '/ɪnˈlaɪtnmənt/', meaning: 'n. 启蒙；教化', category: 'GRE词汇' },
  { word: 'enlist', phonetic: '/ɪnˈlɪst/', meaning: 'v. 征募；入伍', category: 'GRE词汇' },
  { word: 'enliven', phonetic: '/ɪnˈlaɪvn/', meaning: 'v. 使活跃；使有生气', category: 'GRE词汇' },
  { word: 'enmity', phonetic: '/ˈenməti/', meaning: 'n. 敌意；仇恨', category: 'GRE词汇' },
  { word: 'enormous', phonetic: '/ɪˈnɔːməs/', meaning: 'adj. 巨大的', category: '托福词汇' },
  { word: 'enormity', phonetic: '/ɪˈnɔːməti/', meaning: 'n. 巨大；暴行', category: 'GRE词汇' },
  { word: 'enough', phonetic: '/ɪˈnʌf/', meaning: 'adj. 足够的；adv. 足够', category: '托福词汇' },
  { word: 'enquire', phonetic: '/ɪnˈkwaɪər/', meaning: 'v. 询问', category: '托福词汇' },
  { word: 'enquiry', phonetic: '/ɪnˈkwaɪəri/', meaning: 'n. 询问', category: '托福词汇' },
  { word: 'enrage', phonetic: '/ɪnˈreɪdʒ/', meaning: 'v. 激怒', category: 'GRE词汇' },
  { word: 'enrich', phonetic: '/ɪnˈrɪtʃ/', meaning: 'v. 使丰富；使富裕', category: '托福词汇' },
  { word: 'enrichment', phonetic: '/ɪnˈrɪtʃmənt/', meaning: 'n. 丰富', category: '托福词汇' },
  { word: 'enroll', phonetic: '/ɪnˈrəʊl/', meaning: 'v. 登记；注册', category: '托福词汇' },
  { word: 'enrollment', phonetic: '/ɪnˈrəʊlmənt/', meaning: 'n. 登记；入学', category: '托福词汇' },
  { word: 'ensconce', phonetic: '/ɪnˈskɒns/', meaning: 'v. 安置；隐藏', category: 'GRE词汇' },
  { word: 'ensemble', phonetic: '/ɒnˈsɒmbl/', meaning: 'n. 全体；整体', category: 'GRE词汇' },
  { word: 'ensue', phonetic: '/ɪnˈsjuː/', meaning: 'v. 接着发生', category: 'GRE词汇' },
  { word: 'ensure', phonetic: '/ɪnˈʃʊər/', meaning: 'v. 确保', category: '托福词汇' },
  { word: 'entail', phonetic: '/ɪnˈteɪl/', meaning: 'v. 必需；带来', category: 'GRE词汇' },
  { word: 'entangle', phonetic: '/ɪnˈtæŋɡl/', meaning: 'v. 使纠缠；卷入', category: 'GRE词汇' },
  { word: 'enter', phonetic: '/ˈentər/', meaning: 'v. 进入', category: '托福词汇' },
  { word: 'enterprise', phonetic: '/ˈentəpraɪz/', meaning: 'n. 企业；事业', category: '商务词汇' },
  { word: 'enterprising', phonetic: '/ˈentəpraɪzɪŋ/', meaning: 'adj. 有进取心的', category: '商务词汇' },
  { word: 'entertain', phonetic: '/ˌentəˈteɪn/', meaning: 'v. 娱乐；招待', category: '托福词汇' },
  { word: 'entertaining', phonetic: '/ˌentəˈteɪnɪŋ/', meaning: 'adj. 有趣的', category: '托福词汇' },
  { word: 'entertainment', phonetic: '/ˌentəˈteɪnmənt/', meaning: 'n. 娱乐', category: '托福词汇' },
  { word: 'enthral', phonetic: '/ɪnˈθrɔːl/', meaning: 'v. 迷住；奴役', category: 'GRE词汇' },
  { word: 'enthrall', phonetic: '/ɪnˈθrɔːl/', meaning: 'v. 迷住', category: 'GRE词汇' },
  { word: 'enthusiasm', phonetic: '/ɪnˈθjuːziæzəm/', meaning: 'n. 热情', category: '托福词汇' },
  { word: 'enthusiast', phonetic: '/ɪnˈθjuːziæst/', meaning: 'n. 热心者', category: '托福词汇' },
  { word: 'enthusiastic', phonetic: '/ɪnˌθjuːziˈæstɪk/', meaning: 'adj. 热情的', category: '托福词汇' },
  { word: 'entice', phonetic: '/ɪnˈtaɪs/', meaning: 'v. 诱惑；怂恿', category: 'GRE词汇' },
  { word: 'enticement', phonetic: '/ɪnˈtaɪsmənt/', meaning: 'n. 诱惑', category: 'GRE词汇' },
  { word: 'enticing', phonetic: '/ɪnˈtaɪsɪŋ/', meaning: 'adj. 诱人的', category: 'GRE词汇' },
  { word: 'entire', phonetic: '/ɪnˈtaɪər/', meaning: 'adj. 全部的', category: '托福词汇' },
  { word: 'entirely', phonetic: '/ɪnˈtaɪəli/', meaning: 'adv. 完全地', category: '托福词汇' },
  { word: 'entity', phonetic: '/ˈentəti/', meaning: 'n. 实体', category: '托福词汇' },
  { word: 'entomb', phonetic: '/ɪnˈtuːm/', meaning: 'v. 埋葬', category: 'GRE词汇' },
  { word: 'entrance', phonetic: '/ˈentrəns/', meaning: 'n. 入口；v. 使入迷', category: '托福词汇' },
  { word: 'entrant', phonetic: '/ˈentrənt/', meaning: 'n. 新加入者', category: '商务词汇' },
  { word: 'entreat', phonetic: '/ɪnˈtriːt/', meaning: 'v. 恳求', category: 'GRE词汇' },
  { word: 'entreaty', phonetic: '/ɪnˈtriːti/', meaning: 'n. 恳求', category: 'GRE词汇' },
  { word: 'entree', phonetic: '/ˈɒntreɪ/', meaning: 'n. 入场许可；主菜', category: 'GRE词汇' },
  { word: 'entrench', phonetic: '/ɪnˈtrentʃ/', meaning: 'v. 确立；挖掘', category: 'GRE词汇' },
  { word: 'entrepreneur', phonetic: '/ˌɒntrəprəˈnɜːr/', meaning: 'n. 企业家', category: '商务词汇' },
  { word: 'entrepreneurial', phonetic: '/ˌɒntrəprəˈnɜːriəl/', meaning: 'adj. 企业家的', category: '商务词汇' },
  { word: 'entrust', phonetic: '/ɪnˈtrʌst/', meaning: 'v. 委托', category: '托福词汇' },
  { word: 'entry', phonetic: '/ˈentri/', meaning: 'n. 进入；条目', category: '托福词汇' },
  { word: 'entwine', phonetic: '/ɪnˈtwaɪn/', meaning: 'v. 缠绕', category: 'GRE词汇' },
  { word: 'enumerate', phonetic: '/ɪˈnjuːməreɪt/', meaning: 'v. 列举；枚举', category: 'GRE词汇' },
  { word: 'enunciate', phonetic: '/ɪˈnʌnsieɪt/', meaning: 'v. 阐明；发音', category: 'GRE词汇' },
  { word: 'envelop', phonetic: '/ɪnˈveləp/', meaning: 'v. 包围；笼罩', category: 'GRE词汇' },
  { word: 'envelope', phonetic: '/ˈenvələʊp/', meaning: 'n. 信封', category: '托福词汇' },
  { word: 'enviable', phonetic: '/ˈenviəbl/', meaning: 'adj. 令人羡慕的', category: 'GRE词汇' },
  { word: 'envious', phonetic: '/ˈenviəs/', meaning: 'adj. 嫉妒的', category: '托福词汇' },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: 'n. 环境', category: '托福词汇' },
  { word: 'environmental', phonetic: '/ɪnˌvaɪrənˈmentl/', meaning: 'adj. 环境的', category: '托福词汇' },
  { word: 'environmentalist', phonetic: '/ɪnˌvaɪrənˈmentəlɪst/', meaning: 'n. 环保主义者', category: '托福词汇' },
  { word: 'envisage', phonetic: '/ɪnˈvɪzɪdʒ/', meaning: 'v. 设想；正视', category: 'GRE词汇' },
  { word: 'envision', phonetic: '/ɪnˈvɪʒn/', meaning: 'v. 设想；展望', category: '托福词汇' },
  { word: 'envoy', phonetic: '/ˈenvɔɪ/', meaning: 'n. 使者；代表', category: 'GRE词汇' },
  { word: 'envy', phonetic: '/ˈenvi/', meaning: 'n. 嫉妒；v. 嫉妒', category: '托福词汇' },
  { word: 'enzyme', phonetic: '/ˈenzaɪm/', meaning: 'n. 酶', category: '医学词汇' },
  { word: 'eon', phonetic: '/ˈiːən/', meaning: 'n. 极长的时期', category: 'GRE词汇' },
  { word: 'epic', phonetic: '/ˈepɪk/', meaning: 'n. 史诗；adj. 史诗般的', category: 'GRE词汇' },
  { word: 'epicenter', phonetic: '/ˈepɪsentər/', meaning: 'n. 震中；中心', category: '科技词汇' },
  { word: 'epicure', phonetic: '/ˈepɪkjʊər/', meaning: 'n. 美食家', category: 'GRE词汇' },
  { word: 'epidemic', phonetic: '/ˌepɪˈdemɪk/', meaning: 'n. 流行病；adj. 流行的', category: '医学词汇' },
  { word: 'epidemiology', phonetic: '/ˌepɪˌdiːmiˈɒlədʒi/', meaning: 'n. 流行病学', category: '医学词汇' },
  { word: 'epigram', phonetic: '/ˈepɪɡræm/', meaning: 'n. 警句；讽刺短诗', category: 'GRE词汇' },
  { word: 'epilogue', phonetic: '/ˈepɪlɒɡ/', meaning: 'n. 结语；后记', category: 'GRE词汇' },
  { word: 'epiphany', phonetic: '/ɪˈpɪfəni/', meaning: 'n. 顿悟；显现', category: 'GRE词汇' },
  { word: 'episode', phonetic: '/ˈepɪsəʊd/', meaning: 'n. 插曲；一集', category: '托福词汇' },
  { word: 'episodic', phonetic: '/ˌepɪˈsɒdɪk/', meaning: 'adj. 插曲式的；零星的', category: 'GRE词汇' },
  { word: 'epistle', phonetic: '/ɪˈpɪsl/', meaning: 'n. 书信', category: 'GRE词汇' },
  { word: 'epitaph', phonetic: '/ˈepɪtɑːf/', meaning: 'n. 墓志铭', category: 'GRE词汇' },
  { word: 'epithet', phonetic: '/ˈepɪθet/', meaning: 'n. 绰号；形容词', category: 'GRE词汇' },
  { word: 'epitome', phonetic: '/ɪˈpɪtəmi/', meaning: 'n. 典型；缩影', category: 'GRE词汇' },
  { word: 'epitomize', phonetic: '/ɪˈpɪtəmaɪz/', meaning: 'v. 成为…的典型', category: 'GRE词汇' },
  { word: 'epoch', phonetic: '/ˈiːpɒk/', meaning: 'n. 纪元；时代', category: 'GRE词汇' },
  { word: 'equal', phonetic: '/ˈiːkwəl/', meaning: 'adj. 相等的；v. 等于', category: '托福词汇' },
  { word: 'equalitarian', phonetic: '/ɪˌkwɒlɪˈteəriən/', meaning: 'n. 平均主义者', category: 'GRE词汇' },
  { word: 'equality', phonetic: '/ɪˈkwɒləti/', meaning: 'n. 平等', category: '托福词汇' },
  { word: 'equalize', phonetic: '/ˈiːkwəlaɪz/', meaning: 'v. 使平等', category: '托福词汇' },
  { word: 'equanimity', phonetic: '/ˌiːkwəˈnɪməti/', meaning: 'n. 平静；镇定', category: 'GRE词汇' },
  { word: 'equate', phonetic: '/ɪˈkweɪt/', meaning: 'v. 使相等；等同', category: '托福词汇' },
  { word: 'equation', phonetic: '/ɪˈkweɪʒn/', meaning: 'n. 方程式', category: '科技词汇' },
  { word: 'equator', phonetic: '/ɪˈkweɪtər/', meaning: 'n. 赤道', category: '科技词汇' },
  { word: 'equilibrium', phonetic: '/ˌiːkwɪˈlɪbriəm/', meaning: 'n. 平衡', category: 'GRE词汇' },
  { word: 'equine', phonetic: '/ˈiːkwaɪn/', meaning: 'adj. 马的', category: 'GRE词汇' },
  { word: 'equinox', phonetic: '/ˈiːkwɪnɒks/', meaning: 'n. 春分；秋分', category: '科技词汇' },
  { word: 'equip', phonetic: '/ɪˈkwɪp/', meaning: 'v. 装备', category: '托福词汇' },
  { word: 'equipment', phonetic: '/ɪˈkwɪpmənt/', meaning: 'n. 设备', category: '托福词汇' },
  { word: 'equitable', phonetic: '/ˈekwɪtəbl/', meaning: 'adj. 公平的', category: 'GRE词汇' },
  { word: 'equity', phonetic: '/ˈekwəti/', meaning: 'n. 公平；资产净值', category: '商务词汇' },
  { word: 'equivalence', phonetic: '/ɪˈkwɪvələns/', meaning: 'n. 相等；等价', category: '科技词汇' },
  { word: 'equivalent', phonetic: '/ɪˈkwɪvələnt/', meaning: 'adj. 相等的；n. 等价物', category: '托福词汇' },
  { word: 'equivocal', phonetic: '/ɪˈkwɪvəkl/', meaning: 'adj. 模棱两可的', category: 'GRE词汇' },
  { word: 'equivocate', phonetic: '/ɪˈkwɪvəkeɪt/', meaning: 'v. 含糊其辞', category: 'GRE词汇' },
  { word: 'era', phonetic: '/ˈɪərə/', meaning: 'n. 时代', category: '托福词汇' },
  { word: 'eradicate', phonetic: '/ɪˈrædɪkeɪt/', meaning: 'v. 根除；消灭', category: 'GRE词汇' },
  { word: 'erase', phonetic: '/ɪˈreɪz/', meaning: 'v. 擦除', category: '托福词汇' },
  { word: 'eraser', phonetic: '/ɪˈreɪzər/', meaning: 'n. 橡皮擦', category: '日常词汇' },
  { word: 'erasure', phonetic: '/ɪˈreɪʒər/', meaning: 'n. 擦除；消除', category: 'GRE词汇' },
  { word: 'erect', phonetic: '/ɪˈrekt/', meaning: 'v. 建造；adj. 直立的', category: '托福词汇' },
  { word: 'erection', phonetic: '/ɪˈrekʃn/', meaning: 'n. 建立；竖立', category: '托福词汇' },
  { word: 'erode', phonetic: '/ɪˈrəʊd/', meaning: 'v. 侵蚀；腐蚀', category: '托福词汇' },
  { word: 'erosion', phonetic: '/ɪˈrəʊʒn/', meaning: 'n. 侵蚀；腐蚀', category: '托福词汇' },
  { word: 'erotic', phonetic: '/ɪˈrɒtɪk/', meaning: 'adj. 色情的', category: 'GRE词汇' },
  { word: 'err', phonetic: '/ɜːr/', meaning: 'v. 犯错', category: 'GRE词汇' },
  { word: 'errand', phonetic: '/ˈerənd/', meaning: 'n. 差事', category: '托福词汇' },
  { word: 'errant', phonetic: '/ˈerənt/', meaning: 'adj. 错误的；漫游的', category: 'GRE词汇' },
  { word: 'erratic', phonetic: '/ɪˈrætɪk/', meaning: 'adj. 反复无常的', category: 'GRE词汇' },
  { word: 'erroneous', phonetic: '/ɪˈrəʊniəs/', meaning: 'adj. 错误的', category: 'GRE词汇' },
  { word: 'error', phonetic: '/ˈerər/', meaning: 'n. 错误', category: '托福词汇' },
  { word: 'ersatz', phonetic: '/ˈerzæts/', meaning: 'adj. 代替的；人造的', category: 'GRE词汇' },
  { word: 'erudite', phonetic: '/ˈeruːdaɪt/', meaning: 'adj. 博学的', category: 'GRE词汇' },
  { word: 'erudition', phonetic: '/ˌeruˈdɪʃn/', meaning: 'n. 博学', category: 'GRE词汇' },
  { word: 'erupt', phonetic: '/ɪˈrʌpt/', meaning: 'v. 爆发', category: '托福词汇' },
  { word: 'eruption', phonetic: '/ɪˈrʌpʃn/', meaning: 'n. 爆发', category: '托福词汇' },
  { word: 'escalate', phonetic: '/ˈeskəleɪt/', meaning: 'v. 升级；扩大', category: '托福词汇' },
  { word: 'escalation', phonetic: '/ˌeskəˈleɪʃn/', meaning: 'n. 升级', category: '托福词汇' },
  { word: 'escalator', phonetic: '/ˈeskəleɪtər/', meaning: 'n. 自动扶梯', category: '托福词汇' },
  { word: 'escapade', phonetic: '/ˈeskəpeɪd/', meaning: 'n. 冒险行为；恶作剧', category: 'GRE词汇' },
  { word: 'escape', phonetic: '/ɪˈskeɪp/', meaning: 'v. 逃跑；n. 逃脱', category: '托福词汇' },
  { word: 'escapism', phonetic: '/ɪˈskeɪpɪzəm/', meaning: 'n. 逃避现实', category: 'GRE词汇' },
  { word: 'escort', phonetic: '/ɪˈskɔːt/', meaning: 'n. 护送者；v. 护送', category: '托福词汇' },
  { word: 'esoteric', phonetic: '/ˌesəˈterɪk/', meaning: 'adj. 深奥的；秘传的', category: 'GRE词汇' },
  { word: 'espionage', phonetic: '/ˈespiənɑːʒ/', meaning: 'n. 间谍活动', category: 'GRE词汇' },
  { word: 'espouse', phonetic: '/ɪˈspaʊz/', meaning: 'v. 支持；嫁娶', category: 'GRE词汇' },
  { word: 'espy', phonetic: '/ɪˈspaɪ/', meaning: 'v. 窥见；发现', category: 'GRE词汇' },
  { word: 'essay', phonetic: '/ˈeseɪ/', meaning: 'n. 散文；v. 尝试', category: '托福词汇' },
  { word: 'essence', phonetic: '/ˈesns/', meaning: 'n. 本质；精华', category: '托福词汇' },
  { word: 'essential', phonetic: '/ɪˈsenʃl/', meaning: 'adj. 必要的；本质的', category: '托福词汇' },
  { word: 'essentially', phonetic: '/ɪˈsenʃəli/', meaning: 'adv. 本质上', category: '托福词汇' },
  { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: 'v. 建立', category: '托福词汇' },
  { word: 'establishment', phonetic: '/ɪˈstæblɪʃmənt/', meaning: 'n. 建立；机构', category: '托福词汇' },
  { word: 'estate', phonetic: '/ɪˈsteɪt/', meaning: 'n. 房地产；财产', category: '商务词汇' },
  { word: 'esteem', phonetic: '/ɪˈstiːm/', meaning: 'v. 尊重；n. 尊敬', category: 'GRE词汇' },
  { word: 'esthetic', phonetic: '/iːsˈθetɪk/', meaning: 'adj. 美学的', category: 'GRE词汇' },
  { word: 'estimable', phonetic: '/ˈestɪməbl/', meaning: 'adj. 值得尊敬的；可估计的', category: 'GRE词汇' },
  { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: 'v. 估计；n. 估计', category: '托福词汇' },
  { word: 'estimation', phonetic: '/ˌestɪˈmeɪʃn/', meaning: 'n. 估计；评价', category: '托福词汇' },
  { word: 'estrange', phonetic: '/ɪˈstreɪndʒ/', meaning: 'v. 使疏远', category: 'GRE词汇' },
  { word: 'estrangement', phonetic: '/ɪˈstreɪndʒmənt/', meaning: 'n. 疏远', category: 'GRE词汇' },
  { word: 'estuary', phonetic: '/ˈestʃuəri/', meaning: 'n. 河口', category: 'GRE词汇' },
  { word: 'eternal', phonetic: '/ɪˈtɜːnl/', meaning: 'adj. 永恒的', category: '托福词汇' },
  { word: 'eternity', phonetic: '/ɪˈtɜːnəti/', meaning: 'n. 永恒', category: '托福词汇' },
  { word: 'ether', phonetic: '/ˈiːθər/', meaning: 'n. 以太；乙醚', category: '科技词汇' },
  { word: 'ethereal', phonetic: '/ɪˈθɪəriəl/', meaning: 'adj. 轻飘的；天上的', category: 'GRE词汇' },
  { word: 'ethical', phonetic: '/ˈeθɪkl/', meaning: 'adj. 道德的', category: '托福词汇' },
  { word: 'ethics', phonetic: '/ˈeθɪks/', meaning: 'n. 伦理学；道德准则', category: '托福词汇' },
  { word: 'ethnic', phonetic: '/ˈeθnɪk/', meaning: 'adj. 种族的', category: '托福词汇' },
  { word: 'ethnography', phonetic: '/eθˈnɒɡrəfi/', meaning: 'n. 民族志', category: 'GRE词汇' },
  { word: 'ethnology', phonetic: '/eθˈnɒlədʒi/', meaning: 'n. 民族学', category: 'GRE词汇' },
  { word: 'ethos', phonetic: '/ˈiːθɒs/', meaning: 'n. 气质；精神', category: 'GRE词汇' },
  { word: 'etiquette', phonetic: '/ˈetɪket/', meaning: 'n. 礼仪', category: '托福词汇' },
  { word: 'etymology', phonetic: '/ˌetɪˈmɒlədʒi/', meaning: 'n. 词源学', category: 'GRE词汇' },
  { word: 'eulogize', phonetic: '/ˈjuːlədʒaɪz/', meaning: 'v. 称赞；颂扬', category: 'GRE词汇' },
  { word: 'eulogy', phonetic: '/ˈjuːlədʒi/', meaning: 'n. 颂词；悼词', category: 'GRE词汇' },
  { word: 'euphemism', phonetic: '/ˈjuːfəmɪzəm/', meaning: 'n. 委婉语', category: 'GRE词汇' },
  { word: 'euphonious', phonetic: '/juːˈfəʊniəs/', meaning: 'adj. 悦耳的', category: 'GRE词汇' },
  { word: 'euphony', phonetic: '/ˈjuːfəni/', meaning: 'n. 悦耳的声音', category: 'GRE词汇' },
  { word: 'euphoria', phonetic: '/juːˈfɔːriə/', meaning: 'n. 极度兴奋', category: 'GRE词汇' },
  { word: 'euphoric', phonetic: '/juːˈfɒrɪk/', meaning: 'adj. 极度兴奋的', category: 'GRE词汇' },
  { word: 'evacuate', phonetic: '/ɪˈvækjueɪt/', meaning: 'v. 撤离；疏散', category: '托福词汇' },
  { word: 'evade', phonetic: '/ɪˈveɪd/', meaning: 'v. 逃避；规避', category: 'GRE词汇' },
  { word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: 'v. 评估', category: '托福词汇' },
  { word: 'evaluation', phonetic: '/ɪˌvæljuˈeɪʃn/', meaning: 'n. 评估', category: '托福词汇' },
  { word: 'evanescent', phonetic: '/ˌevəˈnesnt/', meaning: 'adj. 短暂的；易逝的', category: 'GRE词汇' },
  { word: 'evangelical', phonetic: '/ˌiːvænˈdʒelɪkl/', meaning: 'adj. 福音派的', category: 'GRE词汇' },
  { word: 'evaporate', phonetic: '/ɪˈvæpəreɪt/', meaning: 'v. 蒸发', category: '托福词汇' },
  { word: 'evasion', phonetic: '/ɪˈveɪʒn/', meaning: 'n. 逃避；借口', category: 'GRE词汇' },
  { word: 'evasive', phonetic: '/ɪˈveɪsɪv/', meaning: 'adj. 逃避的；推托的', category: 'GRE词汇' },
  { word: 'eve', phonetic: '/iːv/', meaning: 'n. 前夜', category: '托福词汇' },
  { word: 'even', phonetic: '/ˈiːvn/', meaning: 'adj. 平的；adv. 甚至', category: '托福词汇' },
  { word: 'evenhanded', phonetic: '/ˌiːvnˈhændɪd/', meaning: 'adj. 公平的；不偏不倚的', category: 'GRE词汇' },
  { word: 'evening', phonetic: '/ˈiːvnɪŋ/', meaning: 'n. 晚上', category: '托福词汇' },
  { word: 'event', phonetic: '/ɪˈvent/', meaning: 'n. 事件', category: '托福词汇' },
  { word: 'eventful', phonetic: '/ɪˈventfl/', meaning: 'adj. 多事的', category: '托福词汇' },
  { word: 'eventual', phonetic: '/ɪˈventʃuəl/', meaning: 'adj. 最终的', category: '托福词汇' },
  { word: 'eventually', phonetic: '/ɪˈventʃuəli/', meaning: 'adv. 最终', category: '托福词汇' },
  { word: 'everlasting', phonetic: '/ˌevəˈlɑːstɪŋ/', meaning: 'adj. 永恒的', category: 'GRE词汇' },
  { word: 'everyday', phonetic: '/ˈevrideɪ/', meaning: 'adj. 日常的', category: '托福词汇' },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: 'n. 证据', category: '托福词汇' },
  { word: 'evident', phonetic: '/ˈevɪdənt/', meaning: 'adj. 明显的', category: '托福词汇' },
  { word: 'evidential', phonetic: '/ˌevɪˈdenʃl/', meaning: 'adj. 证据的', category: '法律词汇' },
  { word: 'evidently', phonetic: '/ˈevɪdəntli/', meaning: 'adv. 明显地', category: '托福词汇' },
  { word: 'evil', phonetic: '/ˈiːvl/', meaning: 'adj. 邪恶的；n. 邪恶', category: '托福词汇' },
  { word: 'eviscerate', phonetic: '/ɪˈvɪsəreɪt/', meaning: 'v. 取出内脏；剔除', category: 'GRE词汇' },
  { word: 'evoke', phonetic: '/ɪˈvəʊk/', meaning: 'v. 唤起；引起', category: 'GRE词汇' },
  { word: 'evolution', phonetic: '/ˌiːvəˈluːʃn/', meaning: 'n. 进化', category: '托福词汇' },
  { word: 'evolutionary', phonetic: '/ˌiːvəˈluːʃənri/', meaning: 'adj. 进化的', category: '托福词汇' },
  { word: 'evolve', phonetic: '/ɪˈvɒlv/', meaning: 'v. 进化；发展', category: '托福词汇' },
  { word: 'exact', phonetic: '/ɪɡˈzækt/', meaning: 'adj. 确切的；v. 强求', category: '托福词汇' },
  { word: 'exacting', phonetic: '/ɪɡˈzæktɪŋ/', meaning: 'adj. 严格的；苛求的', category: 'GRE词汇' },
  { word: 'exaction', phonetic: '/ɪɡˈzækʃn/', meaning: 'n. 强求；勒索', category: 'GRE词汇' },
  { word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', meaning: 'v. 夸大', category: '托福词汇' },
  { word: 'exaggeration', phonetic: '/ɪɡˌzædʒəˈreɪʃn/', meaning: 'n. 夸大', category: '托福词汇' },
  { word: 'exalt', phonetic: '/ɪɡˈzɔːlt/', meaning: 'v. 提升；赞扬', category: 'GRE词汇' },
  { word: 'exalted', phonetic: '/ɪɡˈzɔːltɪd/', meaning: 'adj. 高贵的；兴奋的', category: 'GRE词汇' },
  { word: 'exam', phonetic: '/ɪɡˈzæm/', meaning: 'n. 考试', category: '托福词汇' },
  { word: 'examination', phonetic: '/ɪɡˌzæmɪˈneɪʃn/', meaning: 'n. 考试；检查', category: '托福词汇' },
  { word: 'examine', phonetic: '/ɪɡˈzæmɪn/', meaning: 'v. 检查；考试', category: '托福词汇' },
  { word: 'example', phonetic: '/ɪɡˈzɑːmpl/', meaning: 'n. 例子', category: '托福词汇' },
  { word: 'exasperate', phonetic: '/ɪɡˈzɑːspəreɪt/', meaning: 'v. 使恼怒', category: 'GRE词汇' },
  { word: 'exasperation', phonetic: '/ɪɡˌzɑːspəˈreɪʃn/', meaning: 'n. 恼怒', category: 'GRE词汇' },
  { word: 'excavate', phonetic: '/ˈekskəveɪt/', meaning: 'v. 挖掘', category: 'GRE词汇' },
  { word: 'excavation', phonetic: '/ˌekskəˈveɪʃn/', meaning: 'n. 挖掘', category: 'GRE词汇' },
  { word: 'exceed', phonetic: '/ɪkˈsiːd/', meaning: 'v. 超过', category: '托福词汇' },
  { word: 'exceedingly', phonetic: '/ɪkˈsiːdɪŋli/', meaning: 'adv. 非常', category: '托福词汇' },
  { word: 'excel', phonetic: '/ɪkˈsel/', meaning: 'v. 胜过；杰出', category: '托福词汇' },
  { word: 'excellence', phonetic: '/ˈeksələns/', meaning: 'n. 卓越', category: '托福词汇' },
  { word: 'excellent', phonetic: '/ˈeksələnt/', meaning: 'adj. 卓越的', category: '托福词汇' },
  { word: 'excel', phonetic: '/ɪkˈsel/', meaning: 'v. 胜过；擅长', category: '托福词汇' },
  { word: 'except', phonetic: '/ɪkˈsept/', meaning: 'prep. 除了；v. 除外', category: '托福词汇' },
  { word: 'exception', phonetic: '/ɪkˈsepʃn/', meaning: 'n. 例外', category: '托福词汇' },
  { word: 'exceptional', phonetic: '/ɪkˈsepʃənl/', meaning: 'adj. 例外的；杰出的', category: '托福词汇' },
  { word: 'excerpt', phonetic: '/ˈeksɜːpt/', meaning: 'n. 摘录', category: '托福词汇' },
  { word: 'excess', phonetic: '/ɪkˈses/', meaning: 'n. 过量；adj. 过量的', category: '托福词汇' },
  { word: 'excessive', phonetic: '/ɪkˈsesɪv/', meaning: 'adj. 过度的', category: '托福词汇' },
  { word: 'exchange', phonetic: '/ɪksˈtʃeɪndʒ/', meaning: 'v. 交换；n. 交换', category: '托福词汇' },
  { word: 'excisable', phonetic: '/ekˈsaɪzəbl/', meaning: 'adj. 可切除的', category: '医学词汇' },
  { word: 'excite', phonetic: '/ɪkˈsaɪt/', meaning: 'v. 使兴奋', category: '托福词汇' },
  { word: 'excitement', phonetic: '/ɪkˈsaɪtmənt/', meaning: 'n. 兴奋', category: '托福词汇' },
  { word: 'exciting', phonetic: '/ɪkˈsaɪtɪŋ/', meaning: 'adj. 令人兴奋的', category: '托福词汇' },
  { word: 'exclaim', phonetic: '/ɪkˈskleɪm/', meaning: 'v. 惊叫', category: '托福词汇' },
  { word: 'exclamation', phonetic: '/ˌekskləˈmeɪʃn/', meaning: 'n. 惊叫', category: '托福词汇' },
  { word: 'exclude', phonetic: '/ɪkˈskluːd/', meaning: 'v. 排除', category: '托福词汇' },
  { word: 'exclusion', phonetic: '/ɪkˈskluːʒn/', meaning: 'n. 排除', category: '托福词汇' },
  { word: 'exclusive', phonetic: '/ɪkˈskluːsɪv/', meaning: 'adj. 独有的；排外的', category: '托福词汇' },
  { word: 'exclusively', phonetic: '/ɪkˈskluːsɪvli/', meaning: 'adv. 专门地', category: '托福词汇' },
  { word: 'excommunicate', phonetic: '/ˌekskəˈmjuːnɪkeɪt/', meaning: 'v. 逐出教会', category: 'GRE词汇' },
  { word: 'excoriate', phonetic: '/ɪkˈskɔːrieɪt/', meaning: 'v. 严厉批评；剥皮', category: 'GRE词汇' },
  { word: 'excrete', phonetic: '/ɪkˈskriːt/', meaning: 'v. 排泄', category: '医学词汇' },
  { word: 'excretion', phonetic: '/ɪkˈskriːʃn/', meaning: 'n. 排泄物', category: '医学词汇' },
  { word: 'excursion', phonetic: '/ɪkˈskɜːʃn/', meaning: 'n. 远足；短途旅行', category: '托福词汇' },
  { word: 'excusable', phonetic: '/ɪkˈskjuːzəbl/', meaning: 'adj. 可原谅的', category: '托福词汇' },
  { word: 'excuse', phonetic: '/ɪkˈskjuːz/', meaning: 'n. 借口；v. 原谅', category: '托福词汇' },
  { word: 'execrate', phonetic: '/ˈeksɪkreɪt/', meaning: 'v. 咒骂；憎恶', category: 'GRE词汇' },
  { word: 'execrable', phonetic: '/ˈeksɪkrəbl/', meaning: 'adj. 可恶的；糟糕的', category: 'GRE词汇' },
  { word: 'execute', phonetic: '/ˈeksɪkjuːt/', meaning: 'v. 执行；处死', category: '托福词汇' },
  { word: 'execution', phonetic: '/ˌeksɪˈkjuːʃn/', meaning: 'n. 执行；处决', category: '托福词汇' },
  { word: 'executive', phonetic: '/ɪɡˈzekjətɪv/', meaning: 'n. 行政人员；adj. 行政的', category: '商务词汇' },
  { word: 'executor', phonetic: '/ɪɡˈzekjətər/', meaning: 'n. 执行者', category: '法律词汇' },
  { word: 'exegesis', phonetic: '/ˌeksɪˈdʒiːsɪs/', meaning: 'n. 注释；解释', category: 'GRE词汇' },
  { word: 'exemplary', phonetic: '/ɪɡˈzempləri/', meaning: 'adj. 典范的；惩戒性的', category: 'GRE词汇' },
  { word: 'exemplify', phonetic: '/ɪɡˈzemplɪfaɪ/', meaning: 'v. 举例说明', category: 'GRE词汇' },
  { word: 'exempt', phonetic: '/ɪɡˈzempt/', meaning: 'adj. 豁免的；v. 豁免', category: '托福词汇' },
  { word: 'exemption', phonetic: '/ɪɡˈzempʃn/', meaning: 'n. 豁免', category: '商务词汇' },
  { word: 'exercise', phonetic: '/ˈeksəsaɪz/', meaning: 'n. 运动；v. 锻炼', category: '托福词汇' },
  { word: 'exert', phonetic: '/ɪɡˈzɜːt/', meaning: 'v. 运用；施加', category: '托福词汇' },
  { word: 'exertion', phonetic: '/ɪɡˈzɜːʃn/', meaning: 'n. 努力；运用', category: 'GRE词汇' },
  { word: 'exhale', phonetic: '/eksˈheɪl/', meaning: 'v. 呼气', category: '医学词汇' },
  { word: 'exhaust', phonetic: '/ɪɡˈzɔːst/', meaning: 'v. 使筋疲力尽；n. 废气', category: '托福词汇' },
  { word: 'exhaustion', phonetic: '/ɪɡˈzɔːstʃən/', meaning: 'n. 筋疲力尽', category: '托福词汇' },
  { word: 'exhaustive', phonetic: '/ɪɡˈzɔːstɪv/', meaning: 'adj. 彻底的；详尽的', category: 'GRE词汇' },
  { word: 'exhibit', phonetic: '/ɪɡˈzɪbɪt/', meaning: 'v. 展示；n. 展品', category: '托福词汇' },
  { word: 'exhibition', phonetic: '/ˌeksɪˈbɪʃn/', meaning: 'n. 展览', category: '托福词汇' },
  { word: 'exhilarate', phonetic: '/ɪɡˈzɪləreɪt/', meaning: 'v. 使高兴', category: 'GRE词汇' },
  { word: 'exhilarating', phonetic: '/ɪɡˈzɪləreɪtɪŋ/', meaning: 'adj. 令人振奋的', category: 'GRE词汇' },
  { word: 'exhort', phonetic: '/ɪɡˈzɔːt/', meaning: 'v. 劝告；激励', category: 'GRE词汇' },
  { word: 'exhume', phonetic: '/eksˈhjuːm/', meaning: 'v. 发掘；挖出', category: 'GRE词汇' },
  { word: 'exigency', phonetic: '/ˈeksɪdʒənsi/', meaning: 'n. 紧急情况', category: 'GRE词汇' },
  { word: 'exigent', phonetic: '/ˈeksɪdʒənt/', meaning: 'adj. 紧急的；苛求的', category: 'GRE词汇' },
  { word: 'exile', phonetic: '/ˈeksaɪl/', meaning: 'n. 流放；v. 流放', category: '托福词汇' },
  { word: 'exist', phonetic: '/ɪɡˈzɪst/', meaning: 'v. 存在', category: '托福词汇' },
  { word: 'existence', phonetic: '/ɪɡˈzɪstəns/', meaning: 'n. 存在', category: '托福词汇' },
  { word: 'existent', phonetic: '/ɪɡˈzɪstənt/', meaning: 'adj. 存在的', category: '托福词汇' },
  { word: 'existential', phonetic: '/ˌeɡzɪˈstenʃl/', meaning: 'adj. 存在主义的', category: 'GRE词汇' },
  { word: 'exit', phonetic: '/ˈeksɪt/', meaning: 'n. 出口；v. 退出', category: '托福词汇' },
  { word: 'exodus', phonetic: '/ˈeksədəs/', meaning: 'n. 大批离开', category: 'GRE词汇' },
  { word: 'ex officio', phonetic: '/eks əˈfɪʃiəʊ/', meaning: 'adj. 依职权的', category: 'GRE词汇' },
  { word: 'exonerate', phonetic: '/ɪɡˈzɒnəreɪt/', meaning: 'v. 免除责任；证明无罪', category: 'GRE词汇' },
  { word: 'exorbitant', phonetic: '/ɪɡˈzɔːbɪtənt/', meaning: 'adj. 过高的；过分的', category: 'GRE词汇' },
  { word: 'exorcise', phonetic: '/ˈeksɔːsaɪz/', meaning: 'v. 驱邪', category: 'GRE词汇' },
  { word: 'exotic', phonetic: '/ɪɡˈzɒtɪk/', meaning: 'adj. 异国情调的', category: '托福词汇' },
  { word: 'expand', phonetic: '/ɪkˈspænd/', meaning: 'v. 扩大', category: '托福词汇' },
  { word: 'expanse', phonetic: '/ɪkˈspæns/', meaning: 'n. 广阔区域', category: 'GRE词汇' },
  { word: 'expansion', phonetic: '/ɪkˈspænʃn/', meaning: 'n. 扩大', category: '托福词汇' },
  { word: 'expansive', phonetic: '/ɪkˈspænsɪv/', meaning: 'adj. 广阔的；健谈的', category: 'GRE词汇' },
  { word: 'expatriate', phonetic: '/eksˈpætriət/', meaning: 'v. 驱逐；n. 侨民', category: 'GRE词汇' },
  { word: 'expect', phonetic: '/ɪkˈspekt/', meaning: 'v. 期望', category: '托福词汇' },
  { word: 'expectancy', phonetic: '/ɪkˈspektənsi/', meaning: 'n. 期望', category: '托福词汇' },
  { word: 'expectant', phonetic: '/ɪkˈspektənt/', meaning: 'adj. 期待的', category: '托福词汇' },
  { word: 'expectation', phonetic: '/ˌekspekˈteɪʃn/', meaning: 'n. 期望', category: '托福词汇' },
  { word: 'expedient', phonetic: '/ɪkˈspiːdiənt/', meaning: 'adj. 权宜的；n. 权宜之计', category: 'GRE词汇' },
  { word: 'expedite', phonetic: '/ˈekspədaɪt/', meaning: 'v. 加速；促进', category: 'GRE词汇' },
  { word: 'expedition', phonetic: '/ˌekspəˈdɪʃn/', meaning: 'n. 远征；探险', category: '托福词汇' },
  { word: 'expeditious', phonetic: '/ˌekspəˈdɪʃəs/', meaning: 'adj. 迅速的', category: 'GRE词汇' },
  { word: 'expel', phonetic: '/ɪkˈspel/', meaning: 'v. 驱逐；开除', category: '托福词汇' },
  { word: 'expend', phonetic: '/ɪkˈspend/', meaning: 'v. 花费', category: 'GRE词汇' },
  { word: 'expendable', phonetic: '/ɪkˈspendəbl/', meaning: 'adj. 可消耗的', category: 'GRE词汇' },
  { word: 'expenditure', phonetic: '/ɪkˈspendɪtʃər/', meaning: 'n. 支出；花费', category: '商务词汇' },
  { word: 'expense', phonetic: '/ɪkˈspens/', meaning: 'n. 费用；代价', category: '托福词汇' },
  { word: 'expensive', phonetic: '/ɪkˈspensɪv/', meaning: 'adj. 昂贵的', category: '托福词汇' },
  { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: 'n. 经验；v. 经历', category: '托福词汇' },
  { word: 'experienced', phonetic: '/ɪkˈspɪəriənst/', meaning: 'adj. 有经验的', category: '托福词汇' },
  { word: 'experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: 'n. 实验；v. 实验', category: '托福词汇' },
  { word: 'experimental', phonetic: '/ɪkˌsperɪˈmentl/', meaning: 'adj. 实验的', category: '托福词汇' },
  { word: 'expert', phonetic: '/ˈekspɜːt/', meaning: 'n. 专家；adj. 熟练的', category: '托福词汇' },
  { word: 'expertise', phonetic: '/ˌekspɜːˈtiːz/', meaning: 'n. 专业知识', category: '托福词汇' },
  { word: 'expiate', phonetic: '/ˈekspieɪt/', meaning: 'v. 补偿；赎罪', category: 'GRE词汇' },
  { word: 'expiration', phonetic: '/ˌekspəˈreɪʃn/', meaning: 'n. 期满；呼气', category: '商务词汇' },
  { word: 'expire', phonetic: '/ɪkˈspaɪər/', meaning: 'v. 期满；死亡', category: '托福词汇' },
  { word: 'explanatory', phonetic: '/ɪkˈsplænətri/', meaning: 'adj. 解释的', category: '托福词汇' },
  { word: 'explicit', phonetic: '/ɪkˈsplɪsɪt/', meaning: 'adj. 明确的', category: '托福词汇' },
  { word: 'explode', phonetic: '/ɪkˈspləʊd/', meaning: 'v. 爆炸；激增', category: '托福词汇' },
  { word: 'exploit', phonetic: '/ɪkˈsplɔɪt/', meaning: 'v. 利用；n. 功绩', category: '托福词汇' },
  { word: 'exploitation', phonetic: '/ˌeksplɔɪˈteɪʃn/', meaning: 'n. 利用；剥削', category: '托福词汇' },
  { word: 'exploration', phonetic: '/ˌekspləˈreɪʃn/', meaning: 'n. 探索', category: '托福词汇' },
  { word: 'explore', phonetic: '/ɪkˈsplɔːr/', meaning: 'v. 探索', category: '托福词汇' },
  { word: 'explosion', phonetic: '/ɪkˈspləʊʒn/', meaning: 'n. 爆炸', category: '托福词汇' },
  { word: 'explosive', phonetic: '/ɪkˈspləʊsɪv/', meaning: 'adj. 爆炸的；n. 炸药', category: '托福词汇' },
  { word: 'exponent', phonetic: '/ɪkˈspəʊnənt/', meaning: 'n. 指数；倡导者', category: '科技词汇' },
  { word: 'exponential', phonetic: '/ˌekspəˈnenʃl/', meaning: 'adj. 指数的', category: '科技词汇' },
  { word: 'export', phonetic: '/ɪkˈspɔːt/', meaning: 'v. 出口；n. 出口商品', category: '托福词汇' },
  { word: 'expose', phonetic: '/ɪkˈspəʊz/', meaning: 'v. 暴露；揭露', category: '托福词汇' },
  { word: 'exposition', phonetic: '/ˌekspəˈzɪʃn/', meaning: 'n. 说明；博览会', category: 'GRE词汇' },
  { word: 'exposure', phonetic: '/ɪkˈspəʊʒər/', meaning: 'n. 暴露；曝光', category: '托福词汇' },
  { word: 'express', phonetic: '/ɪkˈspres/', meaning: 'v. 表达；adj. 快速的', category: '托福词汇' },
  { word: 'expression', phonetic: '/ɪkˈspreʃn/', meaning: 'n. 表达；表情', category: '托福词汇' },
  { word: 'expressive', phonetic: '/ɪkˈspresɪv/', meaning: 'adj. 有表现力的', category: '托福词汇' },
  { word: 'expropriate', phonetic: '/eksˈprəʊprieɪt/', meaning: 'v. 没收；征用', category: '法律词汇' },
  { word: 'expulsion', phonetic: '/ɪkˈspʌlʃn/', meaning: 'n. 驱逐；开除', category: 'GRE词汇' },
  { word: 'exquisite', phonetic: '/ɪkˈskwɪzɪt/', meaning: 'adj. 精致的；剧烈的', category: 'GRE词汇' },
  { word: 'extant', phonetic: '/ekˈstænt/', meaning: 'adj. 现存的', category: 'GRE词汇' },
  { word: 'extemporaneous', phonetic: '/ɪkˌstempəˈreɪniəs/', meaning: 'adj. 即兴的', category: 'GRE词汇' },
  { word: 'extemporize', phonetic: '/ɪkˈstempəraɪz/', meaning: 'v. 即兴创作', category: 'GRE词汇' },
  { word: 'extend', phonetic: '/ɪkˈstend/', meaning: 'v. 延伸；扩大', category: '托福词汇' },
  { word: 'extension', phonetic: '/ɪkˈstenʃn/', meaning: 'n. 延伸；扩展', category: '托福词汇' },
  { word: 'extensive', phonetic: '/ɪkˈstensɪv/', meaning: 'adj. 广泛的', category: '托福词汇' },
  { word: 'extent', phonetic: '/ɪkˈstent/', meaning: 'n. 程度；范围', category: '托福词汇' },
  { word: 'extenuate', phonetic: '/ɪkˈstenjueɪt/', meaning: 'v. 减轻；低估', category: 'GRE词汇' },
  { word: 'exterior', phonetic: '/ɪkˈstɪəriər/', meaning: 'adj. 外部的；n. 外部', category: '托福词汇' },
  { word: 'exterminate', phonetic: '/ɪkˈstɜːmɪneɪt/', meaning: 'v. 消灭', category: 'GRE词汇' },
  { word: 'external', phonetic: '/ɪkˈstɜːnl/', meaning: 'adj. 外部的', category: '托福词汇' },
  { word: 'extinct', phonetic: '/ɪkˈstɪŋkt/', meaning: 'adj. 灭绝的', category: '托福词汇' },
  { word: 'extinction', phonetic: '/ɪkˈstɪŋkʃn/', meaning: 'n. 灭绝', category: '托福词汇' },
  { word: 'extinguish', phonetic: '/ɪkˈstɪŋɡwɪʃ/', meaning: 'v. 熄灭；消灭', category: '托福词汇' },
  { word: 'extirpate', phonetic: '/ˈekstəpeɪt/', meaning: 'v. 根除', category: 'GRE词汇' },
  { word: 'extol', phonetic: '/ɪkˈstəʊl/', meaning: 'v. 赞美', category: 'GRE词汇' },
  { word: 'extra', phonetic: '/ˈekstrə/', meaning: 'adj. 额外的；n. 额外之物', category: '托福词汇' },
  { word: 'extract', phonetic: '/ɪkˈstrækt/', meaning: 'v. 提取；n. 提取物', category: '托福词汇' },
  { word: 'extracurricular', phonetic: '/ˌekstrəkəˈrɪkjələr/', meaning: 'adj. 课外的', category: '托福词汇' },
  { word: 'extraneous', phonetic: '/ɪkˈstreɪniəs/', meaning: 'adj. 外来的；无关的', category: 'GRE词汇' },
  { word: 'extraordinary', phonetic: '/ɪkˈstrɔːdnri/', meaning: 'adj. 非凡的', category: '托福词汇' },
  { word: 'extrapolate', phonetic: '/ɪkˈstræpəleɪt/', meaning: 'v. 推断', category: 'GRE词汇' },
  { word: 'extravagant', phonetic: '/ɪkˈstrævəɡənt/', meaning: 'adj. 奢侈的；过度的', category: '托福词汇' },
  { word: 'extravaganza', phonetic: '/ɪkˌstrævəˈɡænzə/', meaning: 'n. 盛大表演', category: 'GRE词汇' },
  { word: 'extreme', phonetic: '/ɪkˈstriːm/', meaning: 'adj. 极端的；n. 极端', category: '托福词汇' },
  { word: 'extremist', phonetic: '/ɪkˈstriːmɪst/', meaning: 'n. 极端主义者', category: '托福词汇' },
  { word: 'extricate', phonetic: '/ˈekstrɪkeɪt/', meaning: 'v. 解脱；救出', category: 'GRE词汇' },
  { word: 'extrinsic', phonetic: '/ɪkˈstrɪnsɪk/', meaning: 'adj. 外在的', category: 'GRE词汇' },
  { word: 'extrovert', phonetic: '/ˈekstrəvɜːt/', meaning: 'n. 外向的人', category: '托福词汇' },
  { word: 'extrude', phonetic: '/ɪkˈstruːd/', meaning: 'v. 挤出；逐出', category: '科技词汇' },
  { word: 'exuberance', phonetic: '/ɪɡˈzjuːbərəns/', meaning: 'n. 丰富；热情洋溢', category: 'GRE词汇' },
  { word: 'exuberant', phonetic: '/ɪɡˈzjuːbərənt/', meaning: 'adj. 热情洋溢的', category: 'GRE词汇' },
  { word: 'exude', phonetic: '/ɪɡˈzjuːd/', meaning: 'v. 流露；散发', category: 'GRE词汇' },
  { word: 'exult', phonetic: '/ɪɡˈzʌlt/', meaning: 'v. 欢欣鼓舞', category: 'GRE词汇' },
  { word: 'exultant', phonetic: '/ɪɡˈzʌltənt/', meaning: 'adj. 欢欣鼓舞的', category: 'GRE词汇' },
];

// 获取分类ID映射
async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

// 获取已存在的单词
async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await supabase
    .from(WORDS_TABLE)
    .select('word');
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

// 插入单词
async function insertWords(words: typeof moreWords, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: w.example_sentence || `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  // 批量插入
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

// 获取当前单词总数
async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入更多单词数据 ===');
  console.log(`预定义单词数量: ${moreWords.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(moreWords, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
