import { getSupabaseClient } from '../src/storage/database/supabase-client';

const client = getSupabaseClient();

// 真实单词数据 - 雅思核心词汇
const ieltsWords = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃', example: 'Never abandon your dreams.' },
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: 'n. 能力；才能', example: 'She has the ability to succeed.' },
  { word: 'abnormal', phonetic: '/æbˈnɔːml/', meaning: 'adj. 反常的；异常的', example: 'The weather has been abnormal this year.' },
  { word: 'aboard', phonetic: '/əˈbɔːd/', meaning: 'adv./prep. 在船/飞机上', example: 'Welcome aboard!' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: 'v. 废除；废止', example: 'Slavery was abolished in 1865.' },
  { word: 'abortion', phonetic: '/əˈbɔːʃn/', meaning: 'n. 流产；堕胎', example: 'Abortion is a controversial topic.' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', meaning: 'adv. 在国外；到国外', example: 'He went abroad to study.' },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', meaning: 'adj. 突然的；唐突的', example: 'There was an abrupt change in the weather.' },
  { word: 'absence', phonetic: '/ˈæbsəns/', meaning: 'n. 缺席；不在', example: 'His absence was noticed by everyone.' },
  { word: 'absent', phonetic: '/ˈæbsənt/', meaning: 'adj. 缺席的；不在的', example: 'He was absent from school yesterday.' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', meaning: 'adj. 绝对的；完全的', example: 'I have absolute confidence in you.' },
  { word: 'absorb', phonetic: '/əbˈzɔːb/', meaning: 'v. 吸收；理解', example: 'Plants absorb carbon dioxide.' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的 n. 摘要', example: 'The concept is too abstract to understand.' },
  { word: 'abundant', phonetic: '/əˈbʌndənt/', meaning: 'adj. 丰富的；充裕的', example: 'The country has abundant natural resources.' },
  { word: 'abuse', phonetic: '/əˈbjuːs/', meaning: 'n./v. 滥用；虐待', example: 'Drug abuse is a serious problem.' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: 'adj. 学术的；学业的', example: 'She has excellent academic performance.' },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速；促进', example: 'The government plans to accelerate growth.' },
  { word: 'accent', phonetic: '/ˈæksent/', meaning: 'n. 口音；重音', example: 'She speaks with a British accent.' },
  { word: 'accept', phonetic: '/əkˈsept/', meaning: 'v. 接受；认可', example: 'Please accept my apology.' },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道；机会 v. 进入', example: 'Students have access to the library.' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', meaning: 'n. 事故；意外', example: 'He was injured in a car accident.' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；适应', example: 'The hotel can accommodate 500 guests.' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴；伴随', example: 'She asked me to accompany her.' },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: 'v. 完成；实现', example: 'We accomplished our goal.' },
  { word: 'accord', phonetic: '/əˈkɔːd/', meaning: 'v. 符合；给予 n. 协议', example: 'His actions accord with his words.' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户；描述 v. 解释', example: 'Open a bank account.' },
  { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: 'v. 积累；积聚', example: 'He accumulated great wealth.' },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 准确的；精确的', example: 'The data must be accurate.' },
  { word: 'accuse', phonetic: '/əˈkjuːz/', meaning: 'v. 指控；谴责', example: 'He was accused of theft.' },
  { word: 'accustomed', phonetic: '/əˈkʌstəmd/', meaning: 'adj. 习惯的', example: 'I am accustomed to getting up early.' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现；达到', example: 'She achieved her goal.' },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: 'v. 承认；确认', example: 'He acknowledged his mistake.' },
  { word: 'acquire', phonetic: '/əˈkwaɪə/', meaning: 'v. 获得；学到', example: 'She acquired new skills.' },
  { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编', example: 'He adapted to the new environment.' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的；适当的', example: 'We have adequate resources.' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整；适应', example: 'Adjust the settings as needed.' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: 'n. 管理；行政', example: 'The administration needs improvement.' },
  { word: 'admire', phonetic: '/ədˈmaɪə/', meaning: 'v. 钦佩；欣赏', example: 'I admire her courage.' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认；准许进入', example: 'He admitted his guilt.' },
  { word: 'adolescent', phonetic: '/ˌædəˈlesnt/', meaning: 'n. 青少年 adj. 青春期的', example: 'Adolescents face many challenges.' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: 'v. 采用；收养', example: 'They adopted a child.' },
  { word: 'adult', phonetic: '/ˈædʌlt/', meaning: 'n. 成年人 adj. 成年的', example: 'Adults should be responsible.' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: 'v. 前进；推进 n. 进步', example: 'Technology continues to advance.' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: 'n. 优势；好处', example: 'This gives us an advantage.' },
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: 'n. 冒险；奇遇', example: 'Life is full of adventures.' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', meaning: 'v. 做广告；宣传', example: 'Companies advertise their products.' },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: 'v. 提倡 n. 提倡者', example: 'He advocates for human rights.' },
  { word: 'affair', phonetic: '/əˈfeə/', meaning: 'n. 事务；事件', example: 'It is a private affair.' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响；感动', example: 'The decision will affect everyone.' },
  { word: 'afford', phonetic: '/əˈfɔːd/', meaning: 'v. 负担得起；提供', example: 'I cannot afford a new car.' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃə/', meaning: 'n. 农业', example: 'Agriculture is important to the economy.' },
  { word: 'aircraft', phonetic: '/ˈeəkrɑːft/', meaning: 'n. 飞行器；飞机', example: 'The aircraft landed safely.' },
  { word: 'alarm', phonetic: '/əˈlɑːm/', meaning: 'n. 警报；惊慌 v. 警告', example: 'The alarm went off at 6 am.' },
  { word: 'alcohol', phonetic: '/ˈælkəhɒl/', meaning: 'n. 酒精；酒', example: 'Alcohol can damage your health.' },
  { word: 'alert', phonetic: '/əˈlɜːt/', meaning: 'adj. 警觉的 n. 警报', example: 'Stay alert while driving.' },
  { word: 'alien', phonetic: '/ˈeɪliən/', meaning: 'n. 外星人；外国人 adj. 外国的', example: 'The concept was alien to me.' },
  { word: 'allege', phonetic: '/əˈledʒ/', meaning: 'v. 宣称；断言', example: 'He allegedly stole the money.' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: 'v. 分配；拨给', example: 'Funds were allocated for education.' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: 'n. 津贴；允许', example: 'She receives a monthly allowance.' },
  { word: 'alter', phonetic: '/ˈɔːltə/', meaning: 'v. 改变；修改', example: 'The plan was altered.' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːnətɪv/', meaning: 'n. 替代品 adj. 可选择的', example: 'We need an alternative solution.' },
  { word: 'altitude', phonetic: '/ˈæltɪtjuːd/', meaning: 'n. 高度；海拔', example: 'The altitude affects breathing.' },
  { word: 'amateur', phonetic: '/ˈæmətə/', meaning: 'n. 业余爱好者 adj. 业余的', example: 'He is an amateur photographer.' },
  { word: 'amaze', phonetic: '/əˈmeɪz/', meaning: 'v. 使惊奇', example: 'Her performance amazed everyone.' },
  { word: 'ambassador', phonetic: '/æmˈbæsədə/', meaning: 'n. 大使；代表', example: 'The ambassador met with the president.' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心；野心', example: 'Her ambition is to become a doctor.' },
  { word: 'ambulance', phonetic: '/ˈæmbjələns/', meaning: 'n. 救护车', example: 'Call an ambulance immediately.' },
  { word: 'amend', phonetic: '/əˈmend/', meaning: 'v. 修改；改进', example: 'The law was amended.' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning: 'n. 数量 v. 总计', example: 'A large amount of money was spent.' },
  { word: 'ample', phonetic: '/ˈæmpl/', meaning: 'adj. 足够的；宽敞的', example: 'There is ample evidence.' },
  { word: 'amuse', phonetic: '/əˈmjuːz/', meaning: 'v. 使娱乐；使发笑', example: 'The story amused the children.' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析', example: 'We need to analyse the data.' },
  { word: 'ancestor', phonetic: '/ˈænsestə/', meaning: 'n. 祖先', example: 'His ancestors came from Ireland.' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', meaning: 'adj. 古老的；古代的', example: 'Ancient civilizations were advanced.' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', meaning: 'n. 角度；观点', example: 'Look at it from a different angle.' },
  { word: 'anniversary', phonetic: '/ˌænɪˈvɜːsəri/', meaning: 'n. 周年纪念', example: 'Today is our wedding anniversary.' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布；宣告', example: 'They announced their engagement.' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 每年的 n. 年刊', example: 'The annual report was published.' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: 'v. 预期；期望', example: 'We anticipate good results.' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', meaning: 'n. 焦虑；担忧', example: 'She felt anxiety before the exam.' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', meaning: 'adj. 焦虑的；渴望的', example: 'He was anxious about the results.' },
  { word: 'apartment', phonetic: '/əˈpɑːtmənt/', meaning: 'n. 公寓', example: 'They live in a small apartment.' },
  { word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', meaning: 'v. 道歉', example: 'You should apologize to her.' },
  { word: 'apparent', phonetic: '/əˈpærənt/', meaning: 'adj. 明显的；表面的', example: 'The reason was apparent.' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: 'v. 呼吁；吸引 n. 吸引力', example: 'The idea appeals to me.' },
  { word: 'appearance', phonetic: '/əˈpɪərəns/', meaning: 'n. 外表；出现', example: 'Don\'t judge by appearance.' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', meaning: 'n. 胃口；欲望', example: 'I have a good appetite.' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', meaning: 'v. 鼓掌；称赞', example: 'The audience applauded loudly.' },
  { word: 'applicable', phonetic: '/əˈplɪkəbl/', meaning: 'adj. 可应用的；适当的', example: 'The rules are applicable here.' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: 'n. 申请人', example: 'There were many applicants.' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', meaning: 'n. 申请；应用', example: 'Submit your application.' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: 'v. 任命；约定', example: 'She was appointed as manager.' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: 'v. 感激；欣赏', example: 'I appreciate your help.' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: 'v. 接近 n. 方法', example: 'We need a new approach.' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: 'adj. 适当的', example: 'Wear appropriate clothing.' },
  { word: 'approval', phonetic: '/əˈpruːvl/', meaning: 'n. 批准；赞同', example: 'The plan got approval.' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准；赞成', example: 'I approve of your decision.' },
  { word: 'approximate', phonetic: '/əˈprɒksɪmət/', meaning: 'adj. 大约的 v. 接近', example: 'The approximate cost is $100.' },
  { word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', meaning: 'adj. 任意的；武断的', example: 'The decision seemed arbitrary.' },
  { word: 'architect', phonetic: '/ˈɑːkɪtekt/', meaning: 'n. 建筑师', example: 'The architect designed the building.' },
  { word: 'architecture', phonetic: '/ˈɑːkɪtektʃə/', meaning: 'n. 建筑学；建筑风格', example: 'The architecture is impressive.' },
  { word: 'argue', phonetic: '/ˈɑːɡjuː/', meaning: 'v. 争论；论证', example: 'Don\'t argue with me.' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现；产生', example: 'Problems may arise.' },
  { word: 'arithmetic', phonetic: '/əˈrɪθmətɪk/', meaning: 'n. 算术', example: 'He is good at arithmetic.' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排；整理', example: 'I will arrange a meeting.' },
  { word: 'arrest', phonetic: '/əˈrest/', meaning: 'v. 逮捕 n. 逮捕', example: 'He was arrested for theft.' },
  { word: 'artificial', phonetic: '/ˌɑːtɪˈfɪʃl/', meaning: 'adj. 人造的；虚假的', example: 'Artificial intelligence is growing.' },
  { word: 'aspect', phonetic: '/ˈæspekt/', meaning: 'n. 方面；外观', example: 'Consider every aspect.' },
  { word: 'assemble', phonetic: '/əˈsembl/', meaning: 'v. 集合；组装', example: 'They assembled in the hall.' },
  { word: 'assess', phonetic: '/əˈses/', meaning: 'v. 评估；评定', example: 'We need to assess the situation.' },
  { word: 'assign', phonetic: '/əˈsaɪn/', meaning: 'v. 分配；指派', example: 'She was assigned a new project.' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 协助；帮助', example: 'Can you assist me?' },
  { word: 'associate', phonetic: '/əˈsəʊʃieɪt/', meaning: 'v. 联想；交往 n. 同事', example: 'I associate summer with vacation.' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: 'v. 假定；承担', example: 'Let\'s assume it\'s true.' },
  { word: 'assure', phonetic: '/əˈʃʊə/', meaning: 'v. 保证；使确信', example: 'I assure you it\'s safe.' },
  { word: 'astonish', phonetic: '/əˈstɒnɪʃ/', meaning: 'v. 使惊讶', example: 'The news astonished me.' },
  { word: 'astronaut', phonetic: '/ˈæstrənɔːt/', meaning: 'n. 宇航员', example: 'He wants to be an astronaut.' },
  { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: 'n. 运动员', example: 'She is a professional athlete.' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪə/', meaning: 'n. 气氛；大气层', example: 'The atmosphere was friendly.' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附上；贴上', example: 'Attach your resume.' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: 'v. 获得；达到', example: 'She attained her goal.' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'n./v. 尝试；企图', example: 'He made an attempt.' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: 'v. 出席；照顾', example: 'Please attend the meeting.' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: 'n. 态度', example: 'Her attitude is positive.' },
  { word: 'attorney', phonetic: '/əˈtɜːni/', meaning: 'n. 律师', example: 'Contact your attorney.' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引', example: 'The music attracted a crowd.' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', meaning: 'v. 归因于 n. 特性', example: 'Success is attributed to hard work.' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: 'n. 观众；听众', example: 'The audience clapped.' },
  { word: 'authority', phonetic: '/ɔːˈθɒrəti/', meaning: 'n. 权威；当局', example: 'Contact the local authority.' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', meaning: 'adj. 自动的', example: 'The system is automatic.' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的；可获得的', example: 'The product is available now.' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'n. 平均数 adj. 平均的', example: 'The average score was 85.' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免', example: 'Avoid making mistakes.' },
  { word: 'award', phonetic: '/əˈwɔːd/', meaning: 'n. 奖品 v. 授予', example: 'She won an award.' },
  { word: 'aware', phonetic: '/əˈweə/', meaning: 'adj. 意识到的', example: 'Are you aware of the rules?' },
  { word: 'awful', phonetic: '/ˈɔːfl/', meaning: 'adj. 可怕的；糟糕的', example: 'The weather was awful.' },
  { word: 'awkward', phonetic: '/ˈɔːkwəd/', meaning: 'adj. 尴尬的；笨拙的', example: 'It was an awkward situation.' },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', meaning: 'n. 背景', example: 'Tell me your background.' },
  { word: 'bacteria', phonetic: '/bækˈtɪəriə/', meaning: 'n. 细菌', example: 'Bacteria can cause illness.' },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: 'n. 平衡 v. 平衡', example: 'Keep a good balance.' },
  { word: 'barrier', phonetic: '/ˈbæriə/', meaning: 'n. 障碍；屏障', example: 'Language is a barrier.' },
  { word: 'basis', phonetic: '/ˈbeɪsɪs/', meaning: 'n. 基础；根据', example: 'On what basis did you decide?' },
  { word: 'behavior', phonetic: '/bɪˈheɪvjə/', meaning: 'n. 行为；举止', example: 'His behavior was inappropriate.' },
  { word: 'belief', phonetic: '/bɪˈliːf/', meaning: 'n. 信仰；信念', example: 'I have a strong belief in justice.' },
  { word: 'belong', phonetic: '/bɪˈlɒŋ/', meaning: 'v. 属于', example: 'This book belongs to me.' },
  { word: 'beneath', phonetic: '/bɪˈniːθ/', meaning: 'prep. 在...下面', example: 'The truth lies beneath.' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: 'n. 好处 v. 有益于', example: 'Exercise has many benefits.' },
  { word: 'besides', phonetic: '/bɪˈsaɪdz/', meaning: 'adv. 此外 prep. 除...之外', example: 'Besides, it\'s too late.' },
  { word: 'bias', phonetic: '/ˈbaɪəs/', meaning: 'n. 偏见 v. 使有偏见', example: 'The report has a bias.' },
  { word: 'billion', phonetic: '/ˈbɪljən/', meaning: 'n. 十亿', example: 'There are billions of stars.' },
  { word: 'biography', phonetic: '/baɪˈɒɡrəfi/', meaning: 'n. 传记', example: 'I read his biography.' },
  { word: 'biology', phonetic: '/baɪˈɒlədʒi/', meaning: 'n. 生物学', example: 'She studies biology.' },
  { word: 'bitter', phonetic: '/ˈbɪtə/', meaning: 'adj. 苦的；痛苦的', example: 'The medicine tastes bitter.' },
  { word: 'blame', phonetic: '/bleɪm/', meaning: 'v. 责备 n. 过失', example: 'Don\'t blame others.' },
  { word: 'blank', phonetic: '/blæŋk/', meaning: 'adj. 空白的 n. 空白', example: 'Leave it blank.' },
  { word: 'blend', phonetic: '/blend/', meaning: 'v. 混合 n. 混合物', example: 'Blend all the ingredients.' },
  { word: 'bond', phonetic: '/bɒnd/', meaning: 'n. 债券；纽带 v. 结合', example: 'The bond between them is strong.' },
  { word: 'bonus', phonetic: '/ˈbəʊnəs/', meaning: 'n. 奖金；红利', example: 'He received a bonus.' },
  { word: 'boom', phonetic: '/buːm/', meaning: 'n. 繁荣 v. 激增', example: 'The economy is booming.' },
  { word: 'boost', phonetic: '/buːst/', meaning: 'v. 促进；提高 n. 提高', example: 'This will boost sales.' },
  { word: 'border', phonetic: '/ˈbɔːdə/', meaning: 'n. 边界；边境', example: 'They crossed the border.' },
  { word: 'bore', phonetic: '/bɔː/', meaning: 'v. 使厌烦 n. 令人厌烦的人', example: 'The lecture bored me.' },
  { word: 'bother', phonetic: '/ˈbɒðə/', meaning: 'v. 打扰；烦恼', example: 'Don\'t bother me.' },
  { word: 'bounce', phonetic: '/baʊns/', meaning: 'v. 弹跳 n. 弹跳', example: 'The ball bounced away.' },
  { word: 'boundary', phonetic: '/ˈbaʊndri/', meaning: 'n. 边界；界限', example: 'Set clear boundaries.' },
  { word: 'brand', phonetic: '/brænd/', meaning: 'n. 品牌 v. 打烙印', example: 'This is a famous brand.' },
  { word: 'breakthrough', phonetic: '/ˈbreɪkθruː/', meaning: 'n. 突破', example: 'This is a major breakthrough.' },
  { word: 'breathe', phonetic: '/briːð/', meaning: 'v. 呼吸', example: 'Breathe deeply.' },
  { word: 'breed', phonetic: '/briːd/', meaning: 'v. 繁殖；饲养 n. 品种', example: 'Dogs breed quickly.' },
  { word: 'brief', phonetic: '/briːf/', meaning: 'adj. 简短的 n. 摘要', example: 'Please be brief.' },
  { word: 'brilliant', phonetic: '/ˈbrɪliənt/', meaning: 'adj. 杰出的；闪耀的', example: 'She is a brilliant student.' },
  { word: 'broad', phonetic: '/brɔːd/', meaning: 'adj. 宽的；广泛的', example: 'He has broad shoulders.' },
  { word: 'broadcast', phonetic: '/ˈbrɔːdkɑːst/', meaning: 'v. 广播 n. 广播', example: 'The show is broadcast live.' },
  { word: 'budget', phonetic: '/ˈbʌdʒɪt/', meaning: 'n. 预算', example: 'We need to stick to the budget.' },
  { word: 'bureau', phonetic: '/ˈbjʊərəʊ/', meaning: 'n. 局；处', example: 'Contact the travel bureau.' },
  { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: 'n. 运动；战役', example: 'The campaign was successful.' },
  { word: 'cancel', phonetic: '/ˈkænsl/', meaning: 'v. 取消', example: 'The flight was cancelled.' },
  { word: 'candidate', phonetic: '/ˈkændɪdət/', meaning: 'n. 候选人', example: 'He is a strong candidate.' },
  { word: 'capable', phonetic: '/ˈkeɪpəbl/', meaning: 'adj. 有能力的', example: 'She is capable of doing it.' },
  { word: 'capacity', phonetic: '/kəˈpæsəti/', meaning: 'n. 容量；能力', example: 'The hall has a capacity of 500.' },
  { word: 'capture', phonetic: '/ˈkæptʃə/', meaning: 'v. 捕获；夺取', example: 'The police captured the thief.' },
  { word: 'carbon', phonetic: '/ˈkɑːbən/', meaning: 'n. 碳', example: 'Carbon dioxide is a greenhouse gas.' },
  { word: 'career', phonetic: '/kəˈrɪə/', meaning: 'n. 职业；生涯', example: 'She has a successful career.' },
  { word: 'cargo', phonetic: '/ˈkɑːɡəʊ/', meaning: 'n. 货物', example: 'The ship carries cargo.' },
  { word: 'carpenter', phonetic: '/ˈkɑːpəntə/', meaning: 'n. 木匠', example: 'He works as a carpenter.' },
  { word: 'carrier', phonetic: '/ˈkæriə/', meaning: 'n. 运输公司；携带者', example: 'The airline is a major carrier.' },
  { word: 'cash', phonetic: '/kæʃ/', meaning: 'n. 现金 v. 兑现', example: 'I don\'t have any cash.' },
  { word: 'casual', phonetic: '/ˈkæʒuəl/', meaning: 'adj. 随意的；非正式的', example: 'It was a casual meeting.' },
  { word: 'category', phonetic: '/ˈkætəɡəri/', meaning: 'n. 类别；种类', example: 'This falls into a different category.' },
  { word: 'cease', phonetic: '/siːs/', meaning: 'v. 停止', example: 'The fighting has ceased.' },
  { word: 'celebrate', phonetic: '/ˈselɪbreɪt/', meaning: 'v. 庆祝', example: 'We celebrated his birthday.' },
  { word: 'ceremony', phonetic: '/ˈserəməni/', meaning: 'n. 典礼；仪式', example: 'The ceremony was beautiful.' },
  { word: 'certificate', phonetic: '/səˈtɪfɪkət/', meaning: 'n. 证书', example: 'She received a certificate.' },
  { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: 'n. 挑战 v. 挑战', example: 'This is a big challenge.' },
  { word: 'chamber', phonetic: '/ˈtʃeɪmbə/', meaning: 'n. 室；房间', example: 'The heart has four chambers.' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: 'n. 冠军', example: 'She is a world champion.' },
  { word: 'channel', phonetic: '/ˈtʃænl/', meaning: 'n. 频道；渠道', example: 'Watch the news channel.' },
  { word: 'chapter', phonetic: '/ˈtʃæptə/', meaning: 'n. 章节', example: 'Read the first chapter.' },
  { word: 'character', phonetic: '/ˈkærəktə/', meaning: 'n. 性格；角色；字符', example: 'She has a strong character.' },
  { word: 'characteristic', phonetic: '/ˌkærəktəˈrɪstɪk/', meaning: 'n. 特征 adj. 典型的', example: 'What are the characteristics?' },
  { word: 'charge', phonetic: '/tʃɑːdʒ/', meaning: 'v. 收费；指控 n. 费用', example: 'There is no charge.' },
  { word: 'charity', phonetic: '/ˈtʃærəti/', meaning: 'n. 慈善', example: 'He donated to charity.' },
  { word: 'chart', phonetic: '/tʃɑːt/', meaning: 'n. 图表 v. 绘制', example: 'The chart shows the data.' },
  { word: 'chase', phonetic: '/tʃeɪs/', meaning: 'v. 追逐 n. 追逐', example: 'The cat chased the mouse.' },
  { word: 'cheap', phonetic: '/tʃiːp/', meaning: 'adj. 便宜的', example: 'It\'s very cheap.' },
  { word: 'cheat', phonetic: '/tʃiːt/', meaning: 'v. 欺骗 n. 欺骗', example: 'Don\'t cheat on the exam.' },
  { word: 'chemical', phonetic: '/ˈkemɪkl/', meaning: 'adj. 化学的 n. 化学品', example: 'Chemical reactions occur.' },
  { word: 'chemistry', phonetic: '/ˈkemɪstri/', meaning: 'n. 化学', example: 'I study chemistry.' },
  { word: 'chief', phonetic: '/tʃiːf/', meaning: 'n. 首领 adj. 主要的', example: 'He is the chief editor.' },
  { word: 'childhood', phonetic: '/ˈtʃaɪldhʊd/', meaning: 'n. 童年', example: 'He had a happy childhood.' },
  { word: 'chip', phonetic: '/tʃɪp/', meaning: 'n. 芯片；碎片', example: 'Computer chips are essential.' },
  { word: 'choice', phonetic: '/tʃɔɪs/', meaning: 'n. 选择', example: 'You have a choice.' },
  { word: 'choose', phonetic: '/tʃuːz/', meaning: 'v. 选择', example: 'Choose wisely.' },
  { word: 'church', phonetic: '/tʃɜːtʃ/', meaning: 'n. 教堂', example: 'They go to church on Sundays.' },
  { word: 'cigarette', phonetic: '/ˌsɪɡəˈret/', meaning: 'n. 香烟', example: 'Smoking cigarettes is harmful.' },
  { word: 'circle', phonetic: '/ˈsɜːkl/', meaning: 'n. 圆圈 v. 圈出', example: 'Draw a circle.' },
  { word: 'circumstance', phonetic: '/ˈsɜːkəmstəns/', meaning: 'n. 情况；环境', example: 'Under the circumstances, yes.' },
  { word: 'cite', phonetic: '/saɪt/', meaning: 'v. 引用', example: 'Please cite your sources.' },
  { word: 'citizen', phonetic: '/ˈsɪtɪzn/', meaning: 'n. 公民', example: 'Every citizen has rights.' },
  { word: 'civil', phonetic: '/ˈsɪvl/', meaning: 'adj. 公民的；文明的', example: 'Civil rights are important.' },
  { word: 'civilization', phonetic: '/ˌsɪvəlaɪˈzeɪʃn/', meaning: 'n. 文明', example: 'Ancient civilizations were advanced.' },
  { word: 'claim', phonetic: '/kleɪm/', meaning: 'v. 声称；要求 n. 要求', example: 'He claims to be innocent.' },
  { word: 'clarify', phonetic: '/ˈklærəfaɪ/', meaning: 'v. 澄清', example: 'Please clarify your point.' },
  { word: 'classic', phonetic: '/ˈklæsɪk/', meaning: 'adj. 经典的 n. 经典作品', example: 'This is a classic example.' },
  { word: 'classification', phonetic: '/ˌklæsɪfɪˈkeɪʃn/', meaning: 'n. 分类', example: 'The classification is useful.' },
  { word: 'classify', phonetic: '/ˈklæsɪfaɪ/', meaning: 'v. 分类', example: 'Classify these items.' },
  { word: 'client', phonetic: '/ˈklaɪənt/', meaning: 'n. 客户', example: 'We have many clients.' },
  { word: 'climate', phonetic: '/ˈklaɪmət/', meaning: 'n. 气候', example: 'The climate is changing.' },
  { word: 'cling', phonetic: '/klɪŋ/', meaning: 'v. 紧握；粘着', example: 'He clung to the hope.' },
  { word: 'clinic', phonetic: '/ˈklɪnɪk/', meaning: 'n. 诊所', example: 'Go to the clinic.' },
  { word: 'clinical', phonetic: '/ˈklɪnɪkl/', meaning: 'adj. 临床的', example: 'Clinical trials are ongoing.' },
  { word: 'clue', phonetic: '/kluː/', meaning: 'n. 线索', example: 'Do you have any clues?' },
  { word: 'cluster', phonetic: '/ˈklʌstə/', meaning: 'n. 群；簇', example: 'A cluster of stars.' },
  { word: 'coach', phonetic: '/kəʊtʃ/', meaning: 'n. 教练 v. 训练', example: 'He is a good coach.' },
  { word: 'coal', phonetic: '/kəʊl/', meaning: 'n. 煤', example: 'Coal is a fossil fuel.' },
  { word: 'coalition', phonetic: '/ˌkəʊəˈlɪʃn/', meaning: 'n. 联盟', example: 'A coalition was formed.' },
  { word: 'coarse', phonetic: '/kɔːs/', meaning: 'adj. 粗糙的；粗俗的', example: 'The fabric is coarse.' },
  { word: 'code', phonetic: '/kəʊd/', meaning: 'n. 代码；准则', example: 'Follow the dress code.' },
  { word: 'cognitive', phonetic: '/ˈkɒɡnətɪv/', meaning: 'adj. 认知的', example: 'Cognitive abilities develop.' },
  { word: 'coherent', phonetic: '/kəʊˈhɪərənt/', meaning: 'adj. 连贯的', example: 'The argument is coherent.' },
  { word: 'coincide', phonetic: '/ˌkəʊɪnˈsaɪd/', meaning: 'v. 同时发生；一致', example: 'The events coincided.' },
  { word: 'collaborate', phonetic: '/kəˈlæbəreɪt/', meaning: 'v. 合作', example: 'Let\'s collaborate on this.' },
  { word: 'collapse', phonetic: '/kəˈlæps/', meaning: 'v. 倒塌；崩溃', example: 'The building collapsed.' },
  { word: 'colleague', phonetic: '/ˈkɒliːɡ/', meaning: 'n. 同事', example: 'My colleagues are helpful.' },
  { word: 'collect', phonetic: '/kəˈlekt/', meaning: 'v. 收集', example: 'Collect the papers.' },
  { word: 'collective', phonetic: '/kəˈlektɪv/', meaning: 'adj. 集体的', example: 'A collective effort is needed.' },
  { word: 'collision', phonetic: '/kəˈlɪʒn/', meaning: 'n. 碰撞', example: 'There was a collision.' },
  { word: 'colony', phonetic: '/ˈkɒləni/', meaning: 'n. 殖民地', example: 'The country was a colony.' },
  { word: 'combine', phonetic: '/kəmˈbaɪn/', meaning: 'v. 结合', example: 'Combine the ingredients.' },
  { word: 'come', phonetic: '/kʌm/', meaning: 'v. 来', example: 'Come here please.' },
  { word: 'comedy', phonetic: '/ˈkɒmədi/', meaning: 'n. 喜剧', example: 'It\'s a great comedy.' },
  { word: 'comfort', phonetic: '/ˈkʌmfət/', meaning: 'n. 舒适 v. 安慰', example: 'She needs some comfort.' },
  { word: 'comfortable', phonetic: '/ˈkʌmfətəbl/', meaning: 'adj. 舒适的', example: 'This chair is comfortable.' },
  { word: 'comic', phonetic: '/ˈkɒmɪk/', meaning: 'adj. 滑稽的 n. 漫画', example: 'It was a comic scene.' },
  { word: 'command', phonetic: '/kəˈmɑːnd/', meaning: 'v. 命令 n. 命令', example: 'Follow my command.' },
  { word: 'comment', phonetic: '/ˈkɒment/', meaning: 'n. 评论 v. 评论', example: 'Leave a comment below.' },
  { word: 'commerce', phonetic: '/ˈkɒmɜːs/', meaning: 'n. 商业', example: 'International commerce is growing.' },
  { word: 'commercial', phonetic: '/kəˈmɜːʃl/', meaning: 'adj. 商业的', example: 'Commercial activities increased.' },
  { word: 'commission', phonetic: '/kəˈmɪʃn/', meaning: 'n. 委员会；佣金', example: 'She gets a commission.' },
  { word: 'commit', phonetic: '/kəˈmɪt/', meaning: 'v. 承诺；犯罪', example: 'He committed to the project.' },
  { word: 'commitment', phonetic: '/kəˈmɪtmənt/', meaning: 'n. 承诺', example: 'Make a commitment.' },
  { word: 'committee', phonetic: '/kəˈmɪti/', meaning: 'n. 委员会', example: 'The committee met today.' },
  { word: 'commodity', phonetic: '/kəˈmɒdəti/', meaning: 'n. 商品', example: 'Oil is a commodity.' },
  { word: 'common', phonetic: '/ˈkɒmən/', meaning: 'adj. 常见的；共同的', example: 'It\'s a common mistake.' },
  { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: 'v. 交流', example: 'We need to communicate.' },
  { word: 'communication', phonetic: '/kəˌmjuːnɪˈkeɪʃn/', meaning: 'n. 交流；通信', example: 'Communication is key.' },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: 'n. 社区', example: 'The community is supportive.' },
  { word: 'companion', phonetic: '/kəmˈpæniən/', meaning: 'n. 同伴', example: 'He is my travel companion.' },
  { word: 'company', phonetic: '/ˈkʌmpəni/', meaning: 'n. 公司；陪伴', example: 'She works for a big company.' },
  { word: 'comparable', phonetic: '/ˈkɒmpərəbl/', meaning: 'adj. 可比较的', example: 'The two are comparable.' },
  { word: 'comparative', phonetic: '/kəmˈpærətɪv/', meaning: 'adj. 比较的', example: 'Comparative analysis was done.' },
  { word: 'compare', phonetic: '/kəmˈpeə/', meaning: 'v. 比较', example: 'Compare the two options.' },
  { word: 'comparison', phonetic: '/kəmˈpærɪsn/', meaning: 'n. 比较', example: 'Make a comparison.' },
  { word: 'compel', phonetic: '/kəmˈpel/', meaning: 'v. 强迫', example: 'He was compelled to confess.' },
  { word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', meaning: 'v. 补偿', example: 'They compensated for the loss.' },
  { word: 'compensation', phonetic: '/ˌkɒmpenˈseɪʃn/', meaning: 'n. 补偿；报酬', example: 'He received compensation.' },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争', example: 'Many companies compete.' },
  { word: 'competence', phonetic: '/ˈkɒmpɪtəns/', meaning: 'n. 能力', example: 'Her competence is impressive.' },
  { word: 'competent', phonetic: '/ˈkɒmpɪtənt/', meaning: 'adj. 有能力的', example: 'She is a competent worker.' },
  { word: 'competition', phonetic: '/ˌkɒmpəˈtɪʃn/', meaning: 'n. 竞争；比赛', example: 'The competition was fierce.' },
  { word: 'competitive', phonetic: '/kəmˈpetətɪv/', meaning: 'adj. 竞争的', example: 'The market is competitive.' },
  { word: 'competitor', phonetic: '/kəmˈpetɪtə/', meaning: 'n. 竞争者', example: 'They are our competitors.' },
  { word: 'complain', phonetic: '/kəmˈpleɪn/', meaning: 'v. 抱怨', example: 'Don\'t complain too much.' },
  { word: 'complaint', phonetic: '/kəmˈpleɪnt/', meaning: 'n. 投诉；抱怨', example: 'We received a complaint.' },
  { word: 'complete', phonetic: '/kəmˈpliːt/', meaning: 'adj. 完整的 v. 完成', example: 'The work is complete.' },
  { word: 'complex', phonetic: '/ˈkɒmpleks/', meaning: 'adj. 复杂的 n. 复合体', example: 'This is a complex issue.' },
  { word: 'complexity', phonetic: '/kəmˈpleksəti/', meaning: 'n. 复杂性', example: 'The complexity is high.' },
  { word: 'complicated', phonetic: '/ˈkɒmplɪkeɪtɪd/', meaning: 'adj. 复杂的', example: 'The situation is complicated.' },
  { word: 'component', phonetic: '/kəmˈpəʊnənt/', meaning: 'n. 成分；组件', example: 'Each component matters.' },
  { word: 'compose', phonetic: '/kəmˈpəʊz/', meaning: 'v. 组成；作曲', example: 'Water is composed of H and O.' },
  { word: 'composer', phonetic: '/kəmˈpəʊzə/', meaning: 'n. 作曲家', example: 'He is a famous composer.' },
  { word: 'composition', phonetic: '/ˌkɒmpəˈzɪʃn/', meaning: 'n. 构成；作文', example: 'The composition is good.' },
  { word: 'compound', phonetic: '/ˈkɒmpaʊnd/', meaning: 'n. 化合物 v. 加重', example: 'This is a chemical compound.' },
  { word: 'comprehension', phonetic: '/ˌkɒmprɪˈhenʃn/', meaning: 'n. 理解', example: 'Test your comprehension.' },
  { word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', meaning: 'adj. 全面的', example: 'A comprehensive review was done.' },
  { word: 'comprise', phonetic: '/kəmˈpraɪz/', meaning: 'v. 包含；由...组成', example: 'The team comprises experts.' },
  { word: 'compromise', phonetic: '/ˈkɒmprəmaɪz/', meaning: 'n. 妥协 v. 妥协', example: 'Reach a compromise.' },
  { word: 'compulsory', phonetic: '/kəmˈpʌlsəri/', meaning: 'adj. 强制的', example: 'Education is compulsory.' },
  { word: 'compute', phonetic: '/kəmˈpjuːt/', meaning: 'v. 计算', example: 'Computers compute fast.' },
  { word: 'computer', phonetic: '/kəmˈpjuːtə/', meaning: 'n. 计算机', example: 'I use a computer for work.' },
  { word: 'conceal', phonetic: '/kənˈsiːl/', meaning: 'v. 隐藏', example: 'He tried to conceal the truth.' },
  { word: 'concede', phonetic: '/kənˈsiːd/', meaning: 'v. 承认；让步', example: 'He conceded defeat.' },
  { word: 'concentrate', phonetic: '/ˈkɒnsntreɪt/', meaning: 'v. 集中', example: 'Concentrate on your work.' },
  { word: 'concept', phonetic: '/ˈkɒnsept/', meaning: 'n. 概念', example: 'This concept is important.' },
  { word: 'concern', phonetic: '/kənˈsɜːn/', meaning: 'n. 关心 v. 涉及', example: 'There is concern about safety.' },
  { word: 'concerning', phonetic: '/kənˈsɜːnɪŋ/', meaning: 'prep. 关于', example: 'Information concerning the case.' },
  { word: 'conclude', phonetic: '/kənˈkluːd/', meaning: 'v. 得出结论；结束', example: 'We can conclude that...' },
  { word: 'conclusion', phonetic: '/kənˈkluːʒn/', meaning: 'n. 结论', example: 'What is your conclusion?' },
  { word: 'concrete', phonetic: '/ˈkɒŋkriːt/', meaning: 'adj. 具体的 n. 混凝土', example: 'Give me concrete evidence.' },
  { word: 'condemn', phonetic: '/kənˈdem/', meaning: 'v. 谴责', example: 'The attack was condemned.' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: 'n. 条件；状况', example: 'The car is in good condition.' },
  { word: 'conduct', phonetic: '/kənˈdʌkt/', meaning: 'v. 进行 n. 行为', example: 'Conduct the experiment.' },
  { word: 'conference', phonetic: '/ˈkɒnfərəns/', meaning: 'n. 会议', example: 'Attend the conference.' },
  { word: 'confess', phonetic: '/kənˈfes/', meaning: 'v. 承认；忏悔', example: 'He confessed his crime.' },
  { word: 'confidence', phonetic: '/ˈkɒnfɪdəns/', meaning: 'n. 信心', example: 'Have confidence in yourself.' },
  { word: 'confident', phonetic: '/ˈkɒnfɪdənt/', meaning: 'adj. 自信的', example: 'Be confident in your abilities.' },
  { word: 'confidential', phonetic: '/ˌkɒnfɪˈdenʃl/', meaning: 'adj. 机密的', example: 'This is confidential.' },
  { word: 'confine', phonetic: '/kənˈfaɪn/', meaning: 'v. 限制', example: 'Confine your comments to the topic.' },
  { word: 'confirm', phonetic: '/kənˈfɜːm/', meaning: 'v. 确认', example: 'Please confirm your attendance.' },
  { word: 'conflict', phonetic: '/ˈkɒnflɪkt/', meaning: 'n. 冲突', example: 'There was a conflict.' },
  { word: 'conform', phonetic: '/kənˈfɔːm/', meaning: 'v. 遵守；符合', example: 'Conform to the rules.' },
  { word: 'confront', phonetic: '/kənˈfrʌnt/', meaning: 'v. 面对；对抗', example: 'Confront the problem.' },
  { word: 'confuse', phonetic: '/kənˈfjuːz/', meaning: 'v. 使困惑', example: 'The question confused me.' },
  { word: 'confusion', phonetic: '/kənˈfjuːʒn/', meaning: 'n. 困惑；混乱', example: 'There was some confusion.' },
  { word: 'congratulate', phonetic: '/kənˈɡrætʃuleɪt/', meaning: 'v. 祝贺', example: 'I congratulate you.' },
  { word: 'congress', phonetic: '/ˈkɒŋɡres/', meaning: 'n. 国会', example: 'Congress passed the law.' },
  { word: 'conjunction', phonetic: '/kənˈdʒʌŋkʃn/', meaning: 'n. 连词；结合', example: 'Use the right conjunction.' },
  { word: 'connect', phonetic: '/kəˈnekt/', meaning: 'v. 连接', example: 'Connect the dots.' },
  { word: 'connection', phonetic: '/kəˈnekʃn/', meaning: 'n. 连接；关系', example: 'There is no connection.' },
  { word: 'conquer', phonetic: '/ˈkɒŋkə/', meaning: 'v. 征服', example: 'They conquered the enemy.' },
  { word: 'conscience', phonetic: '/ˈkɒnʃəns/', meaning: 'n. 良心', example: 'Listen to your conscience.' },
  { word: 'conscious', phonetic: '/ˈkɒnʃəs/', meaning: 'adj. 有意识的', example: 'Be conscious of your actions.' },
  { word: 'consciousness', phonetic: '/ˈkɒnʃəsnəs/', meaning: 'n. 意识', example: 'He lost consciousness.' },
  { word: 'consensus', phonetic: '/kənˈsensəs/', meaning: 'n. 共识', example: 'We reached a consensus.' },
  { word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', meaning: 'n. 结果；后果', example: 'Face the consequences.' },
  { word: 'consequent', phonetic: '/ˈkɒnsɪkwənt/', meaning: 'adj. 随之发生的', example: 'The consequent changes were minor.' },
  { word: 'conservation', phonetic: '/ˌkɒnsəˈveɪʃn/', meaning: 'n. 保护；保存', example: 'Wildlife conservation matters.' },
  { word: 'conservative', phonetic: '/kənˈsɜːvətɪv/', meaning: 'adj. 保守的', example: 'He has conservative views.' },
  { word: 'consider', phonetic: '/kənˈsɪdə/', meaning: 'v. 考虑', example: 'Consider all options.' },
  { word: 'considerable', phonetic: '/kənˈsɪdərəbl/', meaning: 'adj. 相当大的', example: 'There was considerable progress.' },
  { word: 'considerate', phonetic: '/kənˈsɪdərət/', meaning: 'adj. 体贴的', example: 'He is very considerate.' },
  { word: 'consideration', phonetic: '/kənˌsɪdəˈreɪʃn/', meaning: 'n. 考虑', example: 'Take this into consideration.' },
  { word: 'consist', phonetic: '/kənˈsɪst/', meaning: 'v. 由...组成', example: 'The team consists of experts.' },
  { word: 'consistent', phonetic: '/kənˈsɪstənt/', meaning: 'adj. 一致的', example: 'Be consistent in your efforts.' },
  { word: 'constant', phonetic: '/ˈkɒnstənt/', meaning: 'adj. 恒定的；不断的', example: 'There was constant rain.' },
  { word: 'constitute', phonetic: '/ˈkɒnstɪtjuːt/', meaning: 'v. 构成', example: 'Women constitute the majority.' },
  { word: 'constitution', phonetic: '/ˌkɒnstɪˈtjuːʃn/', meaning: 'n. 宪法；体质', example: 'The constitution guarantees rights.' },
  { word: 'construct', phonetic: '/kənˈstrʌkt/', meaning: 'v. 建造', example: 'Construct a new building.' },
  { word: 'construction', phonetic: '/kənˈstrʌkʃn/', meaning: 'n. 建设；结构', example: 'Construction is ongoing.' },
  { word: 'consult', phonetic: '/kənˈsʌlt/', meaning: 'v. 咨询', example: 'Consult a doctor.' },
  { word: 'consultant', phonetic: '/kənˈsʌltənt/', meaning: 'n. 顾问', example: 'He is a business consultant.' },
  { word: 'consume', phonetic: '/kənˈsjuːm/', meaning: 'v. 消费；消耗', example: 'We consume a lot of energy.' },
  { word: 'consumer', phonetic: '/kənˈsjuːmə/', meaning: 'n. 消费者', example: 'Consumer rights are important.' },
  { word: 'consumption', phonetic: '/kənˈsʌmpʃn/', meaning: 'n. 消费', example: 'Oil consumption is high.' },
  { word: 'contact', phonetic: '/ˈkɒntækt/', meaning: 'n. 联系 v. 联系', example: 'Contact us for help.' },
  { word: 'contain', phonetic: '/kənˈteɪn/', meaning: 'v. 包含', example: 'This book contains useful info.' },
  { word: 'container', phonetic: '/kənˈteɪnə/', meaning: 'n. 容器', example: 'Put it in a container.' },
  { word: 'contemporary', phonetic: '/kənˈtempərəri/', meaning: 'adj. 当代的', example: 'Contemporary art is diverse.' },
  { word: 'content', phonetic: '/ˈkɒntent/', meaning: 'n. 内容 adj. 满足的', example: 'Check the content.' },
  { word: 'contest', phonetic: '/ˈkɒntest/', meaning: 'n. 比赛 v. 争议', example: 'She won the contest.' },
  { word: 'context', phonetic: '/ˈkɒntekst/', meaning: 'n. 背景；上下文', example: 'Consider the context.' },
  { word: 'continent', phonetic: '/ˈkɒntɪnənt/', meaning: 'n. 大陆', example: 'Asia is a large continent.' },
  { word: 'continual', phonetic: '/kənˈtɪnjuəl/', meaning: 'adj. 频繁的', example: 'There were continual interruptions.' },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: 'v. 继续', example: 'Continue your work.' },
  { word: 'continuous', phonetic: '/kənˈtɪnjuəs/', meaning: 'adj. 连续的', example: 'Continuous improvement is needed.' },
  { word: 'contract', phonetic: '/ˈkɒntrækt/', meaning: 'n. 合同 v. 收缩', example: 'Sign the contract.' },
  { word: 'contradict', phonetic: '/ˌkɒntrəˈdɪkt/', meaning: 'v. 反驳；矛盾', example: 'Don\'t contradict me.' },
  { word: 'contrary', phonetic: '/ˈkɒntrəri/', meaning: 'adj. 相反的 n. 相反', example: 'On the contrary, I agree.' },
  { word: 'contrast', phonetic: '/ˈkɒntrɑːst/', meaning: 'n. 对比 v. 对比', example: 'Compare and contrast.' },
  { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: 'v. 贡献', example: 'Contribute to the project.' },
  { word: 'contribution', phonetic: '/ˌkɒntrɪˈbjuːʃn/', meaning: 'n. 贡献', example: 'Thank you for your contribution.' },
  { word: 'control', phonetic: '/kənˈtrəʊl/', meaning: 'v./n. 控制', example: 'Take control of the situation.' },
  { word: 'controversial', phonetic: '/ˌkɒntrəˈvɜːʃl/', meaning: 'adj. 有争议的', example: 'This is a controversial topic.' },
  { word: 'controversy', phonetic: '/ˈkɒntrəvɜːsi/', meaning: 'n. 争议', example: 'There is much controversy.' },
  { word: 'convenient', phonetic: '/kənˈviːniənt/', meaning: 'adj. 方便的', example: 'This is very convenient.' },
  { word: 'convention', phonetic: '/kənˈvenʃn/', meaning: 'n. 惯例；大会', example: 'Social conventions vary.' },
  { word: 'conventional', phonetic: '/kənˈvenʃənl/', meaning: 'adj. 传统的', example: 'Use conventional methods.' },
  { word: 'conversation', phonetic: '/ˌkɒnvəˈseɪʃn/', meaning: 'n. 对话', example: 'Have a conversation with him.' },
  { word: 'convert', phonetic: '/kənˈvɜːt/', meaning: 'v. 转变', example: 'Convert the file format.' },
  { word: 'convey', phonetic: '/kənˈveɪ/', meaning: 'v. 传达', example: 'Convey my best wishes.' },
  { word: 'convince', phonetic: '/kənˈvɪns/', meaning: 'v. 说服', example: 'I convinced him to come.' },
  { word: 'cooperate', phonetic: '/kəʊˈɒpəreɪt/', meaning: 'v. 合作', example: 'We must cooperate.' },
  { word: 'cooperation', phonetic: '/kəʊˌɒpəˈreɪʃn/', meaning: 'n. 合作', example: 'Thank you for your cooperation.' },
  { word: 'coordinate', phonetic: '/kəʊˈɔːdɪnət/', meaning: 'v. 协调 n. 坐标', example: 'Coordinate the activities.' },
  { word: 'cope', phonetic: '/kəʊp/', meaning: 'v. 应付', example: 'How do you cope with stress?' },
  { word: 'core', phonetic: '/kɔː/', meaning: 'n. 核心 adj. 核心的', example: 'This is the core issue.' },
  { word: 'corporate', phonetic: '/ˈkɔːpərət/', meaning: 'adj. 公司的', example: 'Corporate culture matters.' },
  { word: 'corporation', phonetic: '/ˌkɔːpəˈreɪʃn/', meaning: 'n. 公司', example: 'He works for a corporation.' },
  { word: 'corps', phonetic: '/kɔː/', meaning: 'n. 军团；团队', example: 'The peace corps helps people.' },
  { word: 'correct', phonetic: '/kəˈrekt/', meaning: 'adj. 正确的 v. 纠正', example: 'Your answer is correct.' },
  { word: 'correspond', phonetic: '/ˌkɒrɪˈspɒnd/', meaning: 'v. 符合；通信', example: 'The results correspond.' },
  { word: 'correspondent', phonetic: '/ˌkɒrɪˈspɒndənt/', meaning: 'n. 通讯记者', example: 'He is a war correspondent.' },
  { word: 'corresponding', phonetic: '/ˌkɒrɪˈspɒndɪŋ/', meaning: 'adj. 相应的', example: 'Take corresponding actions.' },
  { word: 'corridor', phonetic: '/ˈkɒrɪdɔː/', meaning: 'n. 走廊', example: 'Walk down the corridor.' },
  { word: 'cost', phonetic: '/kɒst/', meaning: 'n. 成本 v. 花费', example: 'What is the cost?' },
  { word: 'costly', phonetic: '/ˈkɒstli/', meaning: 'adj. 昂贵的', example: 'It was a costly mistake.' },
  { word: 'council', phonetic: '/ˈkaʊnsl/', meaning: 'n. 委员会', example: 'The council met yesterday.' },
  { word: 'counsel', phonetic: '/ˈkaʊnsl/', meaning: 'n. 建议；律师 v. 建议', example: 'Seek legal counsel.' },
  { word: 'count', phonetic: '/kaʊnt/', meaning: 'v. 数 n. 计数', example: 'Count the votes.' },
  { word: 'counter', phonetic: '/ˈkaʊntə/', meaning: 'n. 柜台 v. 反驳', example: 'Go to the counter.' },
  { word: 'country', phonetic: '/ˈkʌntri/', meaning: 'n. 国家', example: 'I love my country.' },
  { word: 'countryside', phonetic: '/ˈkʌntrisaɪd/', meaning: 'n. 乡村', example: 'I live in the countryside.' },
  { word: 'county', phonetic: '/ˈkaʊnti/', meaning: 'n. 郡；县', example: 'The county has many towns.' },
  { word: 'couple', phonetic: '/ˈkʌpl/', meaning: 'n. 夫妇；一对', example: 'They are a nice couple.' },
  { word: 'courage', phonetic: '/ˈkʌrɪdʒ/', meaning: 'n. 勇气', example: 'Have courage.' },
  { word: 'course', phonetic: '/kɔːs/', meaning: 'n. 课程；过程', example: 'Take this course.' },
  { word: 'court', phonetic: '/kɔːt/', meaning: 'n. 法院；球场', example: 'Go to court.' },
  { word: 'cousin', phonetic: '/ˈkʌzn/', meaning: 'n. 堂兄弟；表兄弟', example: 'He is my cousin.' },
  { word: 'cover', phonetic: '/ˈkʌvə/', meaning: 'v. 覆盖 n. 封面', example: 'Cover the table.' },
  { word: 'coward', phonetic: '/ˈkaʊəd/', meaning: 'n. 懦夫', example: 'Don\'t be a coward.' },
  { word: 'crack', phonetic: '/kræk/', meaning: 'v. 裂开 n. 裂缝', example: 'The glass cracked.' },
  { word: 'craft', phonetic: '/krɑːft/', meaning: 'n. 工艺；技艺', example: 'He learned the craft.' },
  { word: 'crash', phonetic: '/kræʃ/', meaning: 'v. 碰撞 n. 崩溃', example: 'The car crashed.' },
  { word: 'crawl', phonetic: '/krɔːl/', meaning: 'v. 爬行', example: 'The baby crawls.' },
  { word: 'crazy', phonetic: '/ˈkreɪzi/', meaning: 'adj. 疯狂的', example: 'That\'s a crazy idea.' },
  { word: 'cream', phonetic: '/kriːm/', meaning: 'n. 奶油', example: 'Add some cream.' },
  { word: 'create', phonetic: '/kriˈeɪt/', meaning: 'v. 创造', example: 'Create something new.' },
  { word: 'creation', phonetic: '/kriˈeɪʃn/', meaning: 'n. 创造；作品', example: 'This is a great creation.' },
  { word: 'creative', phonetic: '/kriˈeɪtɪv/', meaning: 'adj. 创造性的', example: 'Be creative in your work.' },
  { word: 'creature', phonetic: '/ˈkriːtʃə/', meaning: 'n. 生物', example: 'All creatures are important.' },
  { word: 'credit', phonetic: '/ˈkredɪt/', meaning: 'n. 信用；学分', example: 'Give him credit for his work.' },
  { word: 'crew', phonetic: '/kruː/', meaning: 'n. 全体人员', example: 'The crew worked hard.' },
  { word: 'crime', phonetic: '/kraɪm/', meaning: 'n. 犯罪', example: 'Crime is increasing.' },
  { word: 'criminal', phonetic: '/ˈkrɪmɪnl/', meaning: 'n. 罪犯 adj. 刑事的', example: 'He is a criminal.' },
  { word: 'crisis', phonetic: '/ˈkraɪsɪs/', meaning: 'n. 危机', example: 'We face a crisis.' },
  { word: 'criterion', phonetic: '/kraɪˈtɪəriən/', meaning: 'n. 标准', example: 'What is the criterion?' },
  { word: 'critic', phonetic: '/ˈkrɪtɪk/', meaning: 'n. 批评家', example: 'The critic wrote a review.' },
  { word: 'critical', phonetic: '/ˈkrɪtɪkl/', meaning: 'adj. 批判的；关键的', example: 'This is a critical moment.' },
  { word: 'criticism', phonetic: '/ˈkrɪtɪsɪzəm/', meaning: 'n. 批评', example: 'Accept constructive criticism.' },
  { word: 'criticize', phonetic: '/ˈkrɪtɪsaɪz/', meaning: 'v. 批评', example: 'Don\'t criticize others.' },
  { word: 'crop', phonetic: '/krɒp/', meaning: 'n. 庄稼', example: 'The crop was harvested.' },
  { word: 'crowd', phonetic: '/kraʊd/', meaning: 'n. 人群 v. 拥挤', example: 'There was a large crowd.' },
  { word: 'crucial', phonetic: '/ˈkruːʃl/', meaning: 'adj. 至关重要的', example: 'This is crucial.' },
  { word: 'cruel', phonetic: '/ˈkruːəl/', meaning: 'adj. 残忍的', example: 'That was cruel.' },
  { word: 'cruise', phonetic: '/kruːz/', meaning: 'n. 巡航 v. 巡航', example: 'We went on a cruise.' },
  { word: 'crush', phonetic: '/krʌʃ/', meaning: 'v. 压碎 n. 迷恋', example: 'Don\'t crush the flowers.' },
  { word: 'crust', phonetic: '/krʌst/', meaning: 'n. 外壳；面包皮', example: 'The earth\'s crust is thick.' },
  { word: 'crystal', phonetic: '/ˈkrɪstl/', meaning: 'n. 水晶 adj. 清澈的', example: 'The water was crystal clear.' },
  { word: 'cube', phonetic: '/kjuːb/', meaning: 'n. 立方体', example: 'A cube has six sides.' },
  { word: 'cue', phonetic: '/kjuː/', meaning: 'n. 提示 v. 提示', example: 'Take your cue from me.' },
  { word: 'cultivate', phonetic: '/ˈkʌltɪveɪt/', meaning: 'v. 培养；耕作', example: 'Cultivate good habits.' },
  { word: 'culture', phonetic: '/ˈkʌltʃə/', meaning: 'n. 文化', example: 'Learn about different cultures.' },
  { word: 'curiosity', phonetic: '/ˌkjʊəriˈɒsəti/', meaning: 'n. 好奇心', example: 'Curiosity leads to discovery.' },
  { word: 'curious', phonetic: '/ˈkjʊəriəs/', meaning: 'adj. 好奇的', example: 'I am curious about that.' },
  { word: 'currency', phonetic: '/ˈkʌrənsi/', meaning: 'n. 货币', example: 'What is the local currency?' },
  { word: 'current', phonetic: '/ˈkʌrənt/', meaning: 'adj. 当前的 n. 水流', example: 'What is the current situation?' },
  { word: 'curriculum', phonetic: '/kəˈrɪkjələm/', meaning: 'n. 课程', example: 'The curriculum is updated.' },
  { word: 'curse', phonetic: '/kɜːs/', meaning: 'n./v. 诅咒', example: 'Don\'t curse.' },
  { word: 'curtain', phonetic: '/ˈkɜːtn/', meaning: 'n. 窗帘', example: 'Close the curtain.' },
  { word: 'curve', phonetic: '/kɜːv/', meaning: 'n. 曲线 v. 弯曲', example: 'The road has a curve.' },
  { word: 'cushion', phonetic: '/ˈkʊʃn/', meaning: 'n. 垫子', example: 'Sit on the cushion.' },
  { word: 'custom', phonetic: '/ˈkʌstəm/', meaning: 'n. 习俗', example: 'It\'s a local custom.' },
  { word: 'customer', phonetic: '/ˈkʌstəmə/', meaning: 'n. 顾客', example: 'The customer is always right.' },
  { word: 'cycle', phonetic: '/ˈsaɪkl/', meaning: 'n. 循环；周期', example: 'The water cycle is important.' },
];

// 托福核心词汇
const toeflWords = [
  { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃', example: 'Never abandon hope.' },
  { word: 'abide', phonetic: '/əˈbaɪd/', meaning: 'v. 遵守；忍受', example: 'Abide by the rules.' },
  { word: 'abnormal', phonetic: '/æbˈnɔːml/', meaning: 'adj. 异常的', example: 'The weather is abnormal.' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: 'v. 废除', example: 'Slavery was abolished.' },
  { word: 'abound', phonetic: '/əˈbaʊnd/', meaning: 'v. 大量存在', example: 'Fish abound in this lake.' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', meaning: 'adv. 在国外', example: 'Study abroad.' },
  { word: 'abrupt', phonetic: '/əˈbrʌpt/', meaning: 'adj. 突然的', example: 'An abrupt change occurred.' },
  { word: 'absence', phonetic: '/ˈæbsəns/', meaning: 'n. 缺席', example: 'His absence was noted.' },
  { word: 'absorb', phonetic: '/əbˈzɔːb/', meaning: 'v. 吸收', example: 'Paper absorbs water.' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: 'adj. 抽象的', example: 'Abstract concepts are hard.' },
  { word: 'absurd', phonetic: '/əbˈsɜːd/', meaning: 'adj. 荒谬的', example: 'The idea was absurd.' },
  { word: 'abundance', phonetic: '/əˈbʌndəns/', meaning: 'n. 丰富', example: 'There is an abundance of food.' },
  { word: 'abuse', phonetic: '/əˈbjuːs/', meaning: 'n./v. 滥用', example: 'Drug abuse is dangerous.' },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: 'v. 加速', example: 'Accelerate the process.' },
  { word: 'acceptable', phonetic: '/əkˈseptəbl/', meaning: 'adj. 可接受的', example: 'The offer is acceptable.' },
  { word: 'access', phonetic: '/ˈækses/', meaning: 'n. 通道 v. 接近', example: 'Gain access to the system.' },
  { word: 'accessible', phonetic: '/əkˈsesəbl/', meaning: 'adj. 可接近的', example: 'The library is accessible.' },
  { word: 'accessory', phonetic: '/əkˈsesəri/', meaning: 'n. 附件；从犯', example: 'Buy some accessories.' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', meaning: 'n. 事故', example: 'A car accident happened.' },
  { word: 'acclaim', phonetic: '/əˈkleɪm/', meaning: 'v. 称赞 n. 赞誉', example: 'The book was acclaimed.' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；适应', example: 'Accommodate the guests.' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', meaning: 'v. 陪伴', example: 'Accompany me to the door.' },
  { word: 'accomplice', phonetic: '/əˈkʌmplɪs/', meaning: 'n. 同谋', example: 'He was an accomplice.' },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', meaning: 'v. 完成', example: 'Accomplish the task.' },
  { word: 'accord', phonetic: '/əˈkɔːd/', meaning: 'v. 符合 n. 协议', example: 'They reached an accord.' },
  { word: 'account', phonetic: '/əˈkaʊnt/', meaning: 'n. 账户 v. 解释', example: 'Open an account.' },
  { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: 'v. 积累', example: 'Accumulate wealth.' },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: 'adj. 准确的', example: 'Be accurate in your work.' },
  { word: 'accuse', phonetic: '/əˈkjuːz/', meaning: 'v. 指控', example: 'He was accused of theft.' },
  { word: 'accustomed', phonetic: '/əˈkʌstəmd/', meaning: 'adj. 习惯的', example: 'Be accustomed to hard work.' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现', example: 'Achieve your goals.' },
  { word: 'acid', phonetic: '/ˈæsɪd/', meaning: 'n. 酸 adj. 酸的', example: 'Acid rain is harmful.' },
  { word: 'acknowledge', phonetic: '/əkˈnɒlɪdʒ/', meaning: 'v. 承认', example: 'Acknowledge your mistake.' },
  { word: 'acoustic', phonetic: '/əˈkuːstɪk/', meaning: 'adj. 声学的', example: 'Acoustic guitar sounds nice.' },
  { word: 'acquaint', phonetic: '/əˈkweɪnt/', meaning: 'v. 使了解', example: 'Acquaint yourself with the rules.' },
  { word: 'acquire', phonetic: '/əˈkwaɪə/', meaning: 'v. 获得', example: 'Acquire new skills.' },
  { word: 'acquisition', phonetic: '/ˌækwɪˈzɪʃn/', meaning: 'n. 获得', example: 'The acquisition was successful.' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: 'adj. 足够的', example: 'We have adequate supplies.' },
  { word: 'adhere', phonetic: '/ədˈhɪə/', meaning: 'v. 坚持；粘附', example: 'Adhere to the plan.' },
  { word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', meaning: 'adj. 邻近的', example: 'The two buildings are adjacent.' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: 'v. 调整', example: 'Adjust the settings.' },
  { word: 'administer', phonetic: '/ədˈmɪnɪstə/', meaning: 'v. 管理', example: 'Administer the medicine.' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: 'n. 管理', example: 'The administration is efficient.' },
  { word: 'admire', phonetic: '/ədˈmaɪə/', meaning: 'v. 钦佩', example: 'I admire your courage.' },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: 'v. 承认', example: 'Admit your mistake.' },
  { word: 'adolescent', phonetic: '/ˌædəˈlesnt/', meaning: 'n. 青少年', example: 'Adolescents need guidance.' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', meaning: 'v. 采用；收养', example: 'Adopt a new approach.' },
  { word: 'adore', phonetic: '/əˈdɔː/', meaning: 'v. 崇拜', example: 'She adores her children.' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', meaning: 'v. 前进 n. 进步', example: 'Technology advances rapidly.' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', meaning: 'n. 优势', example: 'Take advantage of the opportunity.' },
  { word: 'adventure', phonetic: '/ədˈventʃə/', meaning: 'n. 冒险', example: 'Life is an adventure.' },
  { word: 'adverse', phonetic: '/ˈædvɜːs/', meaning: 'adj. 不利的', example: 'Adverse conditions exist.' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', meaning: 'v. 做广告', example: 'Advertise the product.' },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: 'v. 提倡', example: 'Advocate for change.' },
  { word: 'aesthetic', phonetic: '/iːsˈθetɪk/', meaning: 'adj. 美学的', example: 'The aesthetic design is beautiful.' },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: 'v. 影响', example: 'The news affected him.' },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', meaning: 'v. 使隶属', example: 'The company is affiliated.' },
  { word: 'affirm', phonetic: '/əˈfɜːm/', meaning: 'v. 肯定', example: 'Affirm your commitment.' },
  { word: 'afflict', phonetic: '/əˈflɪkt/', meaning: 'v. 折磨', example: 'He was afflicted by illness.' },
  { word: 'afford', phonetic: '/əˈfɔːd/', meaning: 'v. 负担得起', example: 'I can\'t afford it.' },
  { word: 'aggravate', phonetic: '/ˈæɡrəveɪt/', meaning: 'v. 加重', example: 'Don\'t aggravate the situation.' },
  { word: 'aggregate', phonetic: '/ˈæɡrɪɡət/', meaning: 'v. 集合 n. 总计', example: 'The aggregate was high.' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', meaning: 'adj. 好斗的', example: 'Be more aggressive.' },
  { word: 'agitate', phonetic: '/ˈædʒɪteɪt/', meaning: 'v. 煽动；焦虑', example: 'The crowd was agitated.' },
  { word: 'alienate', phonetic: '/ˈeɪliəneɪt/', meaning: 'v. 疏远', example: 'Don\'t alienate your friends.' },
  { word: 'allegiance', phonetic: '/əˈliːdʒəns/', meaning: 'n. 忠诚', example: 'Pledge your allegiance.' },
  { word: 'allegedly', phonetic: '/əˈledʒɪdli/', meaning: 'adv. 据称', example: 'He is allegedly guilty.' },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: 'v. 减轻', example: 'Alleviate the pain.' },
  { word: 'allocate', phonetic: '/ˈæləkeɪt/', meaning: 'v. 分配', example: 'Allocate resources wisely.' },
  { word: 'allot', phonetic: '/əˈlɒt/', meaning: 'v. 分配', example: 'Allot time for study.' },
  { word: 'allowance', phonetic: '/əˈlaʊəns/', meaning: 'n. 津贴', example: 'He gets an allowance.' },
  { word: 'allude', phonetic: '/əˈluːd/', meaning: 'v. 暗指', example: 'He alluded to the problem.' },
  { word: 'alter', phonetic: '/ˈɔːltə/', meaning: 'v. 改变', example: 'Alter the design.' },
  { word: 'alternate', phonetic: '/ɔːlˈtɜːnət/', meaning: 'v. 交替 adj. 交替的', example: 'Days alternate with nights.' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːnətɪv/', meaning: 'n. 替代方案', example: 'Find an alternative.' },
  { word: 'amass', phonetic: '/əˈmæs/', meaning: 'v. 积累', example: 'He amassed a fortune.' },
  { word: 'amaze', phonetic: '/əˈmeɪz/', meaning: 'v. 使惊奇', example: 'I was amazed by the view.' },
  { word: 'ambiguity', phonetic: '/ˌæmbɪˈɡjuːəti/', meaning: 'n. 模糊', example: 'Avoid ambiguity.' },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: 'adj. 模糊的', example: 'The statement was ambiguous.' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', meaning: 'n. 雄心', example: 'Have great ambition.' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', meaning: 'adj. 有雄心的', example: 'She is ambitious.' },
  { word: 'amend', phonetic: '/əˈmend/', meaning: 'v. 修改', example: 'Amend the contract.' },
  { word: 'amiable', phonetic: '/ˈeɪmiəbl/', meaning: 'adj. 和蔼的', example: 'She is amiable.' },
  { word: 'amicable', phonetic: '/ˈæmɪkəbl/', meaning: 'adj. 友好的', example: 'Reach an amicable agreement.' },
  { word: 'amplify', phonetic: '/ˈæmplɪfaɪ/', meaning: 'v. 放大', example: 'Amplify the sound.' },
  { word: 'amuse', phonetic: '/əˈmjuːz/', meaning: 'v. 使娱乐', example: 'The story amused me.' },
  { word: 'analogy', phonetic: '/əˈnælədʒi/', meaning: 'n. 类比', example: 'Draw an analogy.' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', meaning: 'v. 分析', example: 'Analyse the data.' },
  { word: 'analysis', phonetic: '/əˈnæləsɪs/', meaning: 'n. 分析', example: 'Do a careful analysis.' },
  { word: 'ancestor', phonetic: '/ˈænsestə/', meaning: 'n. 祖先', example: 'Honor your ancestors.' },
  { word: 'anchor', phonetic: '/ˈæŋkə/', meaning: 'n. 锚 v. 抛锚', example: 'The ship dropped anchor.' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', meaning: 'adj. 古老的', example: 'Ancient history is fascinating.' },
  { word: 'anecdote', phonetic: '/ˈænɪkdəʊt/', meaning: 'n. 轶事', example: 'Tell us an anecdote.' },
  { word: 'anguish', phonetic: '/ˈæŋɡwɪʃ/', meaning: 'n. 痛苦', example: 'He suffered anguish.' },
  { word: 'animated', phonetic: '/ˈænɪmeɪtɪd/', meaning: 'adj. 有生气的', example: 'An animated discussion.' },
  { word: 'announce', phonetic: '/əˈnaʊns/', meaning: 'v. 宣布', example: 'Announce the winner.' },
  { word: 'annoy', phonetic: '/əˈnɔɪ/', meaning: 'v. 使烦恼', example: 'Don\'t annoy me.' },
  { word: 'annual', phonetic: '/ˈænjuəl/', meaning: 'adj. 每年的', example: 'The annual meeting is tomorrow.' },
  { word: 'anonymous', phonetic: '/əˈnɒnɪməs/', meaning: 'adj. 匿名的', example: 'An anonymous caller.' },
  { word: 'antagonist', phonetic: '/ænˈtæɡənɪst/', meaning: 'n. 对手', example: 'The antagonist was defeated.' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: 'v. 预期', example: 'Anticipate problems.' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', meaning: 'adj. 焦虑的', example: 'Don\'t be anxious.' },
  { word: 'apathetic', phonetic: '/ˌæpəˈθetɪk/', meaning: 'adj. 冷漠的', example: 'Don\'t be apathetic.' },
  { word: 'appalling', phonetic: '/əˈpɔːlɪŋ/', meaning: 'adj. 令人震惊的', example: 'The conditions were appalling.' },
  { word: 'apparent', phonetic: '/əˈpærənt/', meaning: 'adj. 明显的', example: 'The reason was apparent.' },
  { word: 'appeal', phonetic: '/əˈpiːl/', meaning: 'v. 吸引 n. 吸引力', example: 'The idea appeals to me.' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', meaning: 'n. 胃口', example: 'I have a good appetite.' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', meaning: 'v. 鼓掌', example: 'The audience applauded.' },
  { word: 'applicable', phonetic: '/əˈplɪkəbl/', meaning: 'adj. 适用的', example: 'The rules are applicable.' },
  { word: 'applicant', phonetic: '/ˈæplɪkənt/', meaning: 'n. 申请人', example: 'The applicant was hired.' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', meaning: 'n. 申请', example: 'Submit your application.' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', meaning: 'v. 任命', example: 'Appoint a new manager.' },
  { word: 'appreciable', phonetic: '/əˈpriːʃəbl/', meaning: 'adj. 可观的', example: 'An appreciable increase.' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', meaning: 'v. 欣赏；感激', example: 'I appreciate your help.' },
  { word: 'apprehend', phonetic: '/ˌæprɪˈhend/', meaning: 'v. 逮捕；理解', example: 'The suspect was apprehended.' },
  { word: 'apprentice', phonetic: '/əˈprentɪs/', meaning: 'n. 学徒', example: 'He was an apprentice.' },
  { word: 'approach', phonetic: '/əˈprəʊtʃ/', meaning: 'v. 接近 n. 方法', example: 'Approach the problem differently.' },
  { word: 'appropriate', phonetic: '/əˈprəʊpriət/', meaning: 'adj. 适当的', example: 'Wear appropriate clothes.' },
  { word: 'approve', phonetic: '/əˈpruːv/', meaning: 'v. 批准', example: 'I approve your plan.' },
  { word: 'approximate', phonetic: '/əˈprɒksɪmət/', meaning: 'adj. 大约的', example: 'The approximate cost is $100.' },
  { word: 'apt', phonetic: '/æpt/', meaning: 'adj. 恰当的；易于...的', example: 'An apt description.' },
  { word: 'aptitude', phonetic: '/ˈæptɪtjuːd/', meaning: 'n. 天赋', example: 'He has an aptitude for music.' },
  { word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', meaning: 'adj. 任意的', example: 'The decision was arbitrary.' },
  { word: 'arbitrate', phonetic: '/ˈɑːbɪtreɪt/', meaning: 'v. 仲裁', example: 'Arbitrate the dispute.' },
  { word: 'arc', phonetic: '/ɑːk/', meaning: 'n. 弧', example: 'A rainbow forms an arc.' },
  { word: 'arch', phonetic: '/ɑːtʃ/', meaning: 'n. 拱门', example: 'Walk through the arch.' },
  { word: 'archaeology', phonetic: '/ˌɑːkiˈɒlədʒi/', meaning: 'n. 考古学', example: 'He studies archaeology.' },
  { word: 'architect', phonetic: '/ˈɑːkɪtekt/', meaning: 'n. 建筑师', example: 'The architect designed it.' },
  { word: 'architecture', phonetic: '/ˈɑːkɪtektʃə/', meaning: 'n. 建筑学', example: 'Study architecture.' },
  { word: 'arduous', phonetic: '/ˈɑːdjuəs/', meaning: 'adj. 艰巨的', example: 'An arduous task.' },
  { word: 'argue', phonetic: '/ˈɑːɡjuː/', meaning: 'v. 争论', example: 'Don\'t argue with me.' },
  { word: 'arise', phonetic: '/əˈraɪz/', meaning: 'v. 出现', example: 'Problems may arise.' },
  { word: 'aristocrat', phonetic: '/ˈærɪstəkræt/', meaning: 'n. 贵族', example: 'He is an aristocrat.' },
  { word: 'arithmetic', phonetic: '/əˈrɪθmətɪk/', meaning: 'n. 算术', example: 'Learn arithmetic.' },
  { word: 'armour', phonetic: '/ˈɑːmə/', meaning: 'n. 盔甲', example: 'Wear armour for protection.' },
  { word: 'aroma', phonetic: '/əˈrəʊmə/', meaning: 'n. 香气', example: 'The aroma of coffee.' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: 'v. 安排', example: 'Arrange a meeting.' },
  { word: 'array', phonetic: '/əˈreɪ/', meaning: 'n. 排列', example: 'An array of options.' },
  { word: 'arrest', phonetic: '/əˈrest/', meaning: 'v. 逮捕', example: 'He was arrested.' },
  { word: 'arrogance', phonetic: '/ˈærəɡəns/', meaning: 'n. 傲慢', example: 'His arrogance is annoying.' },
  { word: 'arrogant', phonetic: '/ˈærəɡənt/', meaning: 'adj. 傲慢的', example: 'Don\'t be arrogant.' },
  { word: 'articulate', phonetic: '/ɑːˈtɪkjələt/', meaning: 'adj. 清晰的 v. 表达', example: 'Be articulate in speech.' },
  { word: 'artificial', phonetic: '/ˌɑːtɪˈfɪʃl/', meaning: 'adj. 人造的', example: 'Artificial intelligence.' },
  { word: 'artillery', phonetic: '/ɑːˈtɪləri/', meaning: 'n. 大炮', example: 'The artillery fired.' },
  { word: 'ascend', phonetic: '/əˈsend/', meaning: 'v. 上升', example: 'Ascend the stairs.' },
  { word: 'ascertain', phonetic: '/ˌæsəˈteɪn/', meaning: 'v. 确定', example: 'Ascertain the truth.' },
  { word: 'ashamed', phonetic: '/əˈʃeɪmd/', meaning: 'adj. 羞愧的', example: 'Don\'t be ashamed.' },
  { word: 'ashore', phonetic: '/əˈʃɔː/', meaning: 'adv. 向岸边', example: 'Swim ashore.' },
  { word: 'aspiration', phonetic: '/ˌæspəˈreɪʃn/', meaning: 'n. 渴望', example: 'Follow your aspirations.' },
  { word: 'aspire', phonetic: '/əˈspaɪə/', meaning: 'v. 渴望', example: 'Aspire to greatness.' },
  { word: 'assassin', phonetic: '/əˈsæsɪn/', meaning: 'n. 刺客', example: 'The assassin escaped.' },
  { word: 'assassinate', phonetic: '/əˈsæsɪneɪt/', meaning: 'v. 暗杀', example: 'The leader was assassinated.' },
  { word: 'assault', phonetic: '/əˈsɔːlt/', meaning: 'n./v. 攻击', example: 'The assault was brutal.' },
  { word: 'assemble', phonetic: '/əˈsembl/', meaning: 'v. 集合', example: 'Assemble in the hall.' },
  { word: 'assembly', phonetic: '/əˈsembli/', meaning: 'n. 集会', example: 'Attend the assembly.' },
  { word: 'assert', phonetic: '/əˈsɜːt/', meaning: 'v. 断言', example: 'Assert your rights.' },
  { word: 'assess', phonetic: '/əˈses/', meaning: 'v. 评估', example: 'Assess the situation.' },
  { word: 'assessment', phonetic: '/əˈsesmənt/', meaning: 'n. 评估', example: 'Complete the assessment.' },
  { word: 'assign', phonetic: '/əˈsaɪn/', meaning: 'v. 分配', example: 'Assign tasks to the team.' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', meaning: 'n. 任务', example: 'Finish your assignment.' },
  { word: 'assimilate', phonetic: '/əˈsɪməleɪt/', meaning: 'v. 同化；吸收', example: 'Assimilate new ideas.' },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: 'v. 协助', example: 'Assist me please.' },
  { word: 'associate', phonetic: '/əˈsəʊʃieɪt/', meaning: 'v. 联想', example: 'Associate words with images.' },
  { word: 'association', phonetic: '/əˌsəʊsiˈeɪʃn/', meaning: 'n. 协会', example: 'Join the association.' },
  { word: 'assorted', phonetic: '/əˈsɔːtɪd/', meaning: 'adj. 各式各样的', example: 'Assorted chocolates.' },
  { word: 'assume', phonetic: '/əˈsjuːm/', meaning: 'v. 假定', example: 'Assume it\'s true.' },
  { word: 'assure', phonetic: '/əˈʃʊə/', meaning: 'v. 保证', example: 'I assure you.' },
  { word: 'astonish', phonetic: '/əˈstɒnɪʃ/', meaning: 'v. 使惊讶', example: 'I was astonished.' },
  { word: 'astronomy', phonetic: '/əˈstrɒnəmi/', meaning: 'n. 天文学', example: 'Study astronomy.' },
  { word: 'athlete', phonetic: '/ˈæθliːt/', meaning: 'n. 运动员', example: 'He is an athlete.' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪə/', meaning: 'n. 气氛', example: 'The atmosphere was tense.' },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: 'v. 附上', example: 'Attach the file.' },
  { word: 'attachment', phonetic: '/əˈtætʃmənt/', meaning: 'n. 附件', example: 'Send the attachment.' },
  { word: 'attain', phonetic: '/əˈteɪn/', meaning: 'v. 获得', example: 'Attain your goals.' },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: 'v./n. 尝试', example: 'Make an attempt.' },
  { word: 'attend', phonetic: '/əˈtend/', meaning: 'v. 出席', example: 'Attend the meeting.' },
  { word: 'attendant', phonetic: '/əˈtendənt/', meaning: 'n. 服务员', example: 'The flight attendant helped.' },
  { word: 'attention', phonetic: '/əˈtenʃn/', meaning: 'n. 注意', example: 'Pay attention.' },
  { word: 'attitude', phonetic: '/ˈætɪtjuːd/', meaning: 'n. 态度', example: 'Have a positive attitude.' },
  { word: 'attorney', phonetic: '/əˈtɜːni/', meaning: 'n. 律师', example: 'Contact an attorney.' },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: 'v. 吸引', example: 'Attract customers.' },
  { word: 'attraction', phonetic: '/əˈtrækʃn/', meaning: 'n. 吸引力', example: 'The main attraction.' },
  { word: 'attractive', phonetic: '/əˈtræktɪv/', meaning: 'adj. 有吸引力的', example: 'She is attractive.' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', meaning: 'v. 归因于 n. 特性', example: 'Attribute success to hard work.' },
  { word: 'auction', phonetic: '/ˈɔːkʃn/', meaning: 'n. 拍卖', example: 'Attend the auction.' },
  { word: 'audible', phonetic: '/ˈɔːdəbl/', meaning: 'adj. 听得见的', example: 'The sound was audible.' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', meaning: 'n. 观众', example: 'The audience cheered.' },
  { word: 'audit', phonetic: '/ˈɔːdɪt/', meaning: 'n. 审计 v. 审计', example: 'Conduct an audit.' },
  { word: 'auditorium', phonetic: '/ˌɔːdɪˈtɔːriəm/', meaning: 'n. 礼堂', example: 'Meet in the auditorium.' },
  { word: 'augment', phonetic: '/ɔːɡˈment/', meaning: 'v. 增加', example: 'Augment your income.' },
  { word: 'authentic', phonetic: '/ɔːˈθentɪk/', meaning: 'adj. 正宗的', example: 'This is authentic.' },
  { word: 'authoritarian', phonetic: '/ɔːˌθɒrɪˈteəriən/', meaning: 'adj. 独裁的', example: 'An authoritarian regime.' },
  { word: 'authority', phonetic: '/ɔːˈθɒrəti/', meaning: 'n. 权威', example: 'Respect authority.' },
  { word: 'authorize', phonetic: '/ˈɔːθəraɪz/', meaning: 'v. 授权', example: 'Authorize the payment.' },
  { word: 'autobiography', phonetic: '/ˌɔːtəbaɪˈɒɡrəfi/', meaning: 'n. 自传', example: 'Read his autobiography.' },
  { word: 'automate', phonetic: '/ˈɔːtəmeɪt/', meaning: 'v. 自动化', example: 'Automate the process.' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', meaning: 'adj. 自动的', example: 'It\'s automatic.' },
  { word: 'automobile', phonetic: '/ˈɔːtəməbiːl/', meaning: 'n. 汽车', example: 'Buy an automobile.' },
  { word: 'autonomous', phonetic: '/ɔːˈtɒnəməs/', meaning: 'adj. 自治的', example: 'An autonomous region.' },
  { word: 'autonomy', phonetic: '/ɔːˈtɒnəmi/', meaning: 'n. 自治', example: 'Respect their autonomy.' },
  { word: 'available', phonetic: '/əˈveɪləbl/', meaning: 'adj. 可用的', example: 'Is this available?' },
  { word: 'avalanche', phonetic: '/ˈævəlɑːnʃ/', meaning: 'n. 雪崩', example: 'An avalanche occurred.' },
  { word: 'avenge', phonetic: '/əˈvendʒ/', meaning: 'v. 报仇', example: 'Avenge his death.' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: 'n. 平均 adj. 平均的', example: 'Above average.' },
  { word: 'avert', phonetic: '/əˈvɜːt/', meaning: 'v. 避免', example: 'Avert a disaster.' },
  { word: 'aviation', phonetic: '/ˌeɪviˈeɪʃn/', meaning: 'n. 航空', example: 'The aviation industry.' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: 'v. 避免', example: 'Avoid mistakes.' },
  { word: 'await', phonetic: '/əˈweɪt/', meaning: 'v. 等待', example: 'Await further instructions.' },
  { word: 'awake', phonetic: '/əˈweɪk/', meaning: 'adj. 醒着的 v. 唤醒', example: 'Stay awake.' },
  { word: 'award', phonetic: '/əˈwɔːd/', meaning: 'n. 奖品 v. 授予', example: 'Receive an award.' },
  { word: 'aware', phonetic: '/əˈweə/', meaning: 'adj. 意识到的', example: 'Be aware of the risks.' },
  { word: 'awe', phonetic: '/ɔː/', meaning: 'n. 敬畏', example: 'Look with awe.' },
  { word: 'awful', phonetic: '/ˈɔːfl/', meaning: 'adj. 可怕的', example: 'The weather was awful.' },
  { word: 'awkward', phonetic: '/ˈɔːkwəd/', meaning: 'adj. 尴尬的', example: 'An awkward situation.' },
];

// 将单词数据合并并导入
async function importRealWords() {
  try {
    console.log('开始导入真实单词数据...');

    // 清空现有单词数据
    const { error: deleteError } = await client
      .from('words')
      .delete()
      .neq('id', 0);

    if (deleteError) {
      console.error('清空单词失败:', deleteError);
      return;
    }

    // 获取词库分类
    const { data: categories } = await client
      .from('vocabulary_categories')
      .select('*');

    if (!categories) {
      console.error('未找到词库分类');
      return;
    }

    const categoryMap = new Map(categories.map(c => [c.name, c.id]));

    // 插入雅思词汇
    const ieltsData = ieltsWords.map(w => ({
      word: w.word,
      phonetic: w.phonetic,
      meaning: w.meaning,
      example_sentence: w.example,
      category_id: categoryMap.get('雅思词汇'),
    }));

    const { error: ieltsError } = await client
      .from('words')
      .insert(ieltsData);

    if (ieltsError) {
      console.error('插入雅思词汇失败:', ieltsError);
    } else {
      console.log(`已插入 ${ieltsData.length} 个雅思词汇`);
    }

    // 插入托福词汇
    const toeflData = toeflWords.map(w => ({
      word: w.word,
      phonetic: w.phonetic,
      meaning: w.meaning,
      example_sentence: w.example,
      category_id: categoryMap.get('托福词汇'),
    }));

    const { error: toeflError } = await client
      .from('words')
      .insert(toeflData);

    if (toeflError) {
      console.error('插入托福词汇失败:', toeflError);
    } else {
      console.log(`已插入 ${toeflData.length} 个托福词汇`);
    }

    // 统计总数
    const { count } = await client
      .from('words')
      .select('*', { count: 'exact', head: true });

    console.log(`\n导入完成！总单词数: ${count}`);

  } catch (error) {
    console.error('导入失败:', error);
  }
}

importRealWords();
