// M字母开头的单词 - Part 1/4
import { getSupabaseClient } from '../src/storage/database/supabase-client';
import { fetchAllFromSupabase } from '../src/lib/supabase-fetch-all';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsM = [
  { word: 'mace', phonetic: '/meɪs/', meaning: 'n. 权杖；胡椒', category: 'GRE词汇' },
  { word: 'machete', phonetic: '/məˈtʃeti/', meaning: 'n. 大砍刀', category: 'GRE词汇' },
  { word: 'machine', phonetic: '/məˈʃiːn/', meaning: 'n. 机器', category: '托福词汇' },
  { word: 'machinery', phonetic: '/məˈʃiːnəri/', meaning: 'n. 机械', category: '托福词汇' },
  { word: 'machinist', phonetic: '/məˈʃiːnɪst/', meaning: 'n. 机械师', category: '托福词汇' },
  { word: 'mad', phonetic: '/mæd/', meaning: 'adj. 疯狂的；生气的', category: '托福词汇' },
  { word: 'madam', phonetic: '/ˈmædəm/', meaning: 'n. 夫人', category: '托福词汇' },
  { word: 'madhouse', phonetic: '/ˈmædhaʊs/', meaning: 'n. 疯人院', category: 'GRE词汇' },
  { word: 'madman', phonetic: '/ˈmædmən/', meaning: 'n. 疯子', category: '托福词汇' },
  { word: 'madness', phonetic: '/ˈmædnəs/', meaning: 'n. 疯狂', category: '托福词汇' },
  { word: 'madrigal', phonetic: '/ˈmædrɪɡl/', meaning: 'n. 情歌', category: 'GRE词汇' },
  { word: 'maelstrom', phonetic: '/ˈmeɪlstrɒm/', meaning: 'n. 大漩涡', category: 'GRE词汇' },
  { word: 'maestro', phonetic: '/ˈmaɪstrəʊ/', meaning: 'n. 大师', category: 'GRE词汇' },
  { word: 'magazine', phonetic: '/ˌmæɡəˈziːn/', meaning: 'n. 杂志', category: '托福词汇' },
  { word: 'maggot', phonetic: '/ˈmæɡət/', meaning: 'n. 蛆', category: 'GRE词汇' },
  { word: 'magic', phonetic: '/ˈmædʒɪk/', meaning: 'n. 魔法；adj. 魔法的', category: '托福词汇' },
  { word: 'magical', phonetic: '/ˈmædʒɪkl/', meaning: 'adj. 魔法的', category: '托福词汇' },
  { word: 'magician', phonetic: '/məˈdʒɪʃn/', meaning: 'n. 魔术师', category: '托福词汇' },
  { word: 'magistrate', phonetic: '/ˈmædʒɪstreɪt/', meaning: 'n. 地方法官', category: '法律词汇' },
  { word: 'magnet', phonetic: '/ˈmæɡnɪt/', meaning: 'n. 磁铁', category: '托福词汇' },
  { word: 'magnetic', phonetic: '/mæɡˈnetɪk/', meaning: 'adj. 有磁性的', category: '托福词汇' },
  { word: 'magnetism', phonetic: '/ˈmæɡnɪtɪzəm/', meaning: 'n. 磁力', category: '科技词汇' },
  { word: 'magnetize', phonetic: '/ˈmæɡnɪtaɪz/', meaning: 'v. 磁化', category: '科技词汇' },
  { word: 'magnificent', phonetic: '/mæɡˈnɪfɪsnt/', meaning: 'adj. 壮丽的', category: '托福词汇' },
  { word: 'magnificence', phonetic: '/mæɡˈnɪfɪsns/', meaning: 'n. 壮丽', category: 'GRE词汇' },
  { word: 'magnifier', phonetic: '/ˈmæɡnɪfaɪər/', meaning: 'n. 放大镜', category: '托福词汇' },
  { word: 'magnify', phonetic: '/ˈmæɡnɪfaɪ/', meaning: 'v. 放大', category: '托福词汇' },
  { word: 'magnitude', phonetic: '/ˈmæɡnɪtjuːd/', meaning: 'n. 大小；重要性', category: '托福词汇' },
  { word: 'magnolia', phonetic: '/mæɡˈnəʊliə/', meaning: 'n. 木兰', category: 'GRE词汇' },
  { word: 'mahogany', phonetic: '/məˈhɒɡəni/', meaning: 'n. 红木', category: 'GRE词汇' },
  { word: 'maid', phonetic: '/meɪd/', meaning: 'n. 女仆', category: '托福词汇' },
  { word: 'maiden', phonetic: '/ˈmeɪdn/', meaning: 'n. 少女；adj. 初次的', category: 'GRE词汇' },
  { word: 'mail', phonetic: '/meɪl/', meaning: 'n. 邮件；v. 邮寄', category: '托福词汇' },
  { word: 'mailbox', phonetic: '/ˈmeɪlbɒks/', meaning: 'n. 邮箱', category: '托福词汇' },
  { word: 'maim', phonetic: '/meɪm/', meaning: 'v. 使残废', category: 'GRE词汇' },
  { word: 'main', phonetic: '/meɪn/', meaning: 'adj. 主要的', category: '托福词汇' },
  { word: 'mainland', phonetic: '/ˈmeɪnlənd/', meaning: 'n. 大陆', category: '托福词汇' },
  { word: 'mainly', phonetic: '/ˈmeɪnli/', meaning: 'adv. 主要地', category: '托福词汇' },
  { word: 'mainstream', phonetic: '/ˈmeɪnstriːm/', meaning: 'n. 主流；adj. 主流的', category: '托福词汇' },
  { word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: 'v. 维持', category: '托福词汇' },
  { word: 'maintenance', phonetic: '/ˈmeɪntənəns/', meaning: 'n. 维护', category: '托福词汇' },
  { word: 'maison', phonetic: '/ˈmeɪzən/', meaning: 'n. 房屋', category: 'GRE词汇' },
  { word: 'maize', phonetic: '/meɪz/', meaning: 'n. 玉米', category: '托福词汇' },
  { word: 'majestic', phonetic: '/məˈdʒestɪk/', meaning: 'adj. 雄伟的', category: 'GRE词汇' },
  { word: 'majesty', phonetic: '/ˈmædʒəsti/', meaning: 'n. 威严；陛下', category: 'GRE词汇' },
  { word: 'major', phonetic: '/ˈmeɪdʒər/', meaning: 'adj. 主要的；n. 专业', category: '托福词汇' },
  { word: 'majority', phonetic: '/məˈdʒɒrəti/', meaning: 'n. 多数', category: '托福词汇' },
  { word: 'make', phonetic: '/meɪk/', meaning: 'v. 制造；n. 制造', category: '托福词汇' },
  { word: 'maker', phonetic: '/ˈmeɪkər/', meaning: 'n. 制造者', category: '托福词汇' },
  { word: 'makeup', phonetic: '/ˈmeɪkʌp/', meaning: 'n. 化妆品；组成', category: '托福词汇' },
  { word: 'maladjusted', phonetic: '/ˌmæləˈdʒʌstɪd/', meaning: 'adj. 失调的', category: 'GRE词汇' },
  { word: 'maladministration', phonetic: '/ˌmælədˌmɪnɪˈstreɪʃn/', meaning: 'n. 管理不善', category: 'GRE词汇' },
  { word: 'malady', phonetic: '/ˈmælədi/', meaning: 'n. 疾病', category: 'GRE词汇' },
  { word: 'malaise', phonetic: '/məˈleɪz/', meaning: 'n. 不适', category: 'GRE词汇' },
  { word: 'malaria', phonetic: '/məˈleəriə/', meaning: 'n. 疟疾', category: '医学词汇' },
  { word: 'malcontent', phonetic: '/ˈmælkəntent/', meaning: 'n. 不满者', category: 'GRE词汇' },
  { word: 'male', phonetic: '/meɪl/', meaning: 'adj. 男性的；n. 男性', category: '托福词汇' },
  { word: 'malefactor', phonetic: '/ˈmælɪfæktər/', meaning: 'n. 罪犯', category: 'GRE词汇' },
  { word: 'malevolent', phonetic: '/məˈlevələnt/', meaning: 'adj. 恶意的', category: 'GRE词汇' },
  { word: 'malice', phonetic: '/ˈmælɪs/', meaning: 'n. 恶意', category: 'GRE词汇' },
  { word: 'malicious', phonetic: '/məˈlɪʃəs/', meaning: 'adj. 恶意的', category: '法律词汇' },
  { word: 'malign', phonetic: '/məˈlaɪn/', meaning: 'v. 诽谤；adj. 恶性的', category: 'GRE词汇' },
  { word: 'malignant', phonetic: '/məˈlɪɡnənt/', meaning: 'adj. 恶性的', category: '医学词汇' },
  { word: 'malleable', phonetic: '/ˈmæliəbl/', meaning: 'adj. 可锻的；易受影响的', category: 'GRE词汇' },
  { word: 'mallet', phonetic: '/ˈmælɪt/', meaning: 'n. 木槌', category: 'GRE词汇' },
  { word: 'malnutrition', phonetic: '/ˌmælnjuːˈtrɪʃn/', meaning: 'n. 营养不良', category: '医学词汇' },
  { word: 'malodorous', phonetic: '/ˌmælˈəʊdərəs/', meaning: 'adj. 有恶臭的', category: 'GRE词汇' },
  { word: 'malt', phonetic: '/mɔːlt/', meaning: 'n. 麦芽', category: 'GRE词汇' },
  { word: 'maltreat', phonetic: '/ˌmælˈtriːt/', meaning: 'v. 虐待', category: '法律词汇' },
  { word: 'mama', phonetic: '/məˈmɑː/', meaning: 'n. 妈妈', category: '托福词汇' },
  { word: 'mammoth', phonetic: '/ˈmæməθ/', meaning: 'n. 猛犸象；adj. 巨大的', category: 'GRE词汇' },
  { word: 'man', phonetic: '/mæn/', meaning: 'n. 男人', category: '托福词汇' },
  { word: 'manage', phonetic: '/ˈmænɪdʒ/', meaning: 'v. 管理', category: '托福词汇' },
  { word: 'management', phonetic: '/ˈmænɪdʒmənt/', meaning: 'n. 管理', category: '托福词汇' },
  { word: 'manager', phonetic: '/ˈmænɪdʒər/', meaning: 'n. 经理', category: '托福词汇' },
  { word: 'managerial', phonetic: '/ˌmænɪˈdʒɪəriəl/', meaning: 'adj. 管理的', category: '商务词汇' },
  { word: 'manatee', phonetic: '/ˈmænətiː/', meaning: 'n. 海牛', category: 'GRE词汇' },
  { word: 'mandarin', phonetic: '/ˈmændərɪn/', meaning: 'n. 官话；柑橘', category: '托福词汇' },
  { word: 'mandate', phonetic: '/ˈmændeɪt/', meaning: 'n. 命令；v. 授权', category: 'GRE词汇' },
  { word: 'mandatory', phonetic: '/ˈmændətəri/', meaning: 'adj. 强制的', category: '法律词汇' },
  { word: 'mandolin', phonetic: '/ˈmændəlɪn/', meaning: 'n. 曼陀林琴', category: 'GRE词汇' },
  { word: 'mane', phonetic: '/meɪn/', meaning: 'n. 鬃毛', category: 'GRE词汇' },
  { word: 'maneuver', phonetic: '/məˈnuːvər/', meaning: 'n. 演习；v. 操纵', category: 'GRE词汇' },
  { word: 'manger', phonetic: '/ˈmeɪndʒər/', meaning: 'n. 马槽', category: 'GRE词汇' },
  { word: 'mangle', phonetic: '/ˈmæŋɡl/', meaning: 'v. 撕裂；n. 轧布机', category: 'GRE词汇' },
  { word: 'mango', phonetic: '/ˈmæŋɡəʊ/', meaning: 'n. 芒果', category: '托福词汇' },
  { word: 'mania', phonetic: '/ˈmeɪniə/', meaning: 'n. 狂热', category: 'GRE词汇' },
  { word: 'maniac', phonetic: '/ˈmeɪniæk/', meaning: 'n. 疯子', category: 'GRE词汇' },
  { word: 'manic', phonetic: '/ˈmænɪk/', meaning: 'adj. 狂躁的', category: 'GRE词汇' },
  { word: 'manicure', phonetic: '/ˈmænɪkjʊər/', meaning: 'n. 修指甲', category: '托福词汇' },
  { word: 'manifest', phonetic: '/ˈmænɪfest/', meaning: 'adj. 明显的；v. 表明', category: 'GRE词汇' },
  { word: 'manifestation', phonetic: '/ˌmænɪfeˈsteɪʃn/', meaning: 'n. 表现', category: 'GRE词汇' },
  { word: 'manifesto', phonetic: '/ˌmænɪˈfestəʊ/', meaning: 'n. 宣言', category: 'GRE词汇' },
  { word: 'manifold', phonetic: '/ˈmænɪfəʊld/', meaning: 'adj. 多样的', category: 'GRE词汇' },
  { word: 'manipulate', phonetic: '/məˈnɪpjuleɪt/', meaning: 'v. 操纵', category: '托福词汇' },
  { word: 'manipulation', phonetic: '/məˌnɪpjuˈleɪʃn/', meaning: 'n. 操纵', category: '托福词汇' },
  { word: 'mankind', phonetic: '/mænˈkaɪnd/', meaning: 'n. 人类', category: '托福词汇' },
  { word: 'manly', phonetic: '/ˈmænli/', meaning: 'adj. 有男子气概的', category: '托福词汇' },
  { word: 'manna', phonetic: '/ˈmænə/', meaning: 'n. 吗哪；天赐之物', category: 'GRE词汇' },
  { word: 'manner', phonetic: '/ˈmænər/', meaning: 'n. 方式；礼貌', category: '托福词汇' },
  { word: 'mannerism', phonetic: '/ˈmænərɪzəm/', meaning: 'n. 独特的风格', category: 'GRE词汇' },
  { word: 'manners', phonetic: '/ˈmænərz/', meaning: 'n. 礼貌', category: '托福词汇' },
  { word: 'manor', phonetic: '/ˈmænər/', meaning: 'n. 庄园', category: 'GRE词汇' },
  { word: 'mansion', phonetic: '/ˈmænʃn/', meaning: 'n. 大厦', category: '托福词汇' },
  { word: 'manslaughter', phonetic: '/ˈmænˌslɔːtər/', meaning: 'n. 过失杀人', category: '法律词汇' },
  { word: 'mantel', phonetic: '/ˈmæntl/', meaning: 'n. 壁炉架', category: 'GRE词汇' },
  { word: 'mantle', phonetic: '/ˈmæntl/', meaning: 'n. 披风；地幔', category: 'GRE词汇' },
  { word: 'manual', phonetic: '/ˈmænjuəl/', meaning: 'adj. 手动的；n. 手册', category: '托福词汇' },
  { word: 'manufacture', phonetic: '/ˌmænjuˈfæktʃər/', meaning: 'v. 制造；n. 制造', category: '托福词汇' },
  { word: 'manufacturer', phonetic: '/ˌmænjuˈfæktʃərər/', meaning: 'n. 制造商', category: '托福词汇' },
  { word: 'manure', phonetic: '/məˈnjʊər/', meaning: 'n. 肥料；v. 施肥', category: 'GRE词汇' },
  { word: 'manuscript', phonetic: '/ˈmænjuskrɪpt/', meaning: 'n. 手稿', category: 'GRE词汇' },
  { word: 'many', phonetic: '/ˈmeni/', meaning: 'adj. 许多的', category: '托福词汇' },
  { word: 'map', phonetic: '/mæp/', meaning: 'n. 地图；v. 绘制地图', category: '托福词汇' },
  { word: 'maple', phonetic: '/ˈmeɪpl/', meaning: 'n. 枫树', category: 'GRE词汇' },
  { word: 'mar', phonetic: '/mɑːr/', meaning: 'v. 损坏', category: 'GRE词汇' },
  { word: 'marathon', phonetic: '/ˈmærəθən/', meaning: 'n. 马拉松', category: '托福词汇' },
  { word: 'marble', phonetic: '/ˈmɑːbl/', meaning: 'n. 大理石', category: '托福词汇' },
  { word: 'marc', phonetic: '/mɑːk/', meaning: 'n. 葡萄渣', category: 'GRE词汇' },
  { word: 'march', phonetic: '/mɑːtʃ/', meaning: 'v. 行军；n. 三月', category: '托福词汇' },
  { word: 'mare', phonetic: '/meər/', meaning: 'n. 母马', category: 'GRE词汇' },
  { word: 'margin', phonetic: '/ˈmɑːdʒɪn/', meaning: 'n. 边缘；利润', category: '托福词汇' },
  { word: 'marginal', phonetic: '/ˈmɑːdʒɪnl/', meaning: 'adj. 边缘的；微小的', category: '托福词汇' },
  { word: 'marginally', phonetic: '/ˈmɑːdʒɪnəli/', meaning: 'adv. 轻微地', category: '托福词汇' },
  { word: 'marigold', phonetic: '/ˈmærɪɡəʊld/', meaning: 'n. 万寿菊', category: 'GRE词汇' },
  { word: 'marijuana', phonetic: '/ˌmærɪˈwɑːnə/', meaning: 'n. 大麻', category: '法律词汇' },
  { word: 'marine', phonetic: '/məˈriːn/', meaning: 'adj. 海洋的；n. 海军陆战队', category: '托福词汇' },
  { word: 'mariner', phonetic: '/ˈmærɪnər/', meaning: 'n. 水手', category: 'GRE词汇' },
  { word: 'marital', phonetic: '/ˈmærɪtl/', meaning: 'adj. 婚姻的', category: '托福词汇' },
  { word: 'maritime', phonetic: '/ˈmærɪtaɪm/', meaning: 'adj. 海事的', category: 'GRE词汇' },
  { word: 'marital', phonetic: '/ˈmærɪtl/', meaning: 'adj. 婚姻的', category: '法律词汇' },
  { word: 'mark', phonetic: '/mɑːk/', meaning: 'n. 标记；v. 标记', category: '托福词汇' },
  { word: 'market', phonetic: '/ˈmɑːkɪt/', meaning: 'n. 市场；v. 销售', category: '托福词汇' },
  { word: 'marketable', phonetic: '/ˈmɑːkɪtəbl/', meaning: 'adj. 可销售的', category: '商务词汇' },
  { word: 'marketer', phonetic: '/ˈmɑːkɪtər/', meaning: 'n. 营销人员', category: '商务词汇' },
  { word: 'marketing', phonetic: '/ˈmɑːkɪtɪŋ/', meaning: 'n. 营销', category: '商务词汇' },
  { word: 'marketplace', phonetic: '/ˈmɑːkɪtpleɪs/', meaning: 'n. 市场', category: '商务词汇' },
  { word: 'marking', phonetic: '/ˈmɑːkɪŋ/', meaning: 'n. 标记', category: '托福词汇' },
  { word: 'marksman', phonetic: '/ˈmɑːksmən/', meaning: 'n. 神枪手', category: 'GRE词汇' },
  { word: 'marriage', phonetic: '/ˈmærɪdʒ/', meaning: 'n. 婚姻', category: '托福词汇' },
  { word: 'married', phonetic: '/ˈmærid/', meaning: 'adj. 已婚的', category: '托福词汇' },
  { word: 'marrow', phonetic: '/ˈmærəʊ/', meaning: 'n. 骨髓', category: '医学词汇' },
  { word: 'marry', phonetic: '/ˈmæri/', meaning: 'v. 结婚', category: '托福词汇' },
  { word: 'mars', phonetic: '/mɑːz/', meaning: 'n. 火星', category: '托福词汇' },
  { word: 'marsh', phonetic: '/mɑːʃ/', meaning: 'n. 沼泽', category: '托福词汇' },
  { word: 'marshal', phonetic: '/ˈmɑːʃl/', meaning: 'n. 元帅；v. 整理', category: 'GRE词汇' },
  { word: 'marshy', phonetic: '/ˈmɑːʃi/', meaning: 'adj. 沼泽的', category: 'GRE词汇' },
  { word: 'marsupial', phonetic: '/mɑːˈsuːpiəl/', meaning: 'n. 有袋动物', category: 'GRE词汇' },
  { word: 'martial', phonetic: '/ˈmɑːʃl/', meaning: 'adj. 军事的', category: 'GRE词汇' },
  { word: 'martian', phonetic: '/ˈmɑːʃn/', meaning: 'adj. 火星的；n. 火星人', category: '托福词汇' },
  { word: 'martyr', phonetic: '/ˈmɑːtər/', meaning: 'n. 烈士', category: 'GRE词汇' },
  { word: 'marvel', phonetic: '/ˈmɑːvl/', meaning: 'n. 奇迹；v. 惊叹', category: 'GRE词汇' },
  { word: 'marvelous', phonetic: '/ˈmɑːvələs/', meaning: 'adj. 了不起的', category: '托福词汇' },
  { word: 'marxism', phonetic: '/ˈmɑːksɪzəm/', meaning: 'n. 马克思主义', category: 'GRE词汇' },
  { word: 'masculine', phonetic: '/ˈmæskjəlɪn/', meaning: 'adj. 男性的', category: '托福词汇' },
  { word: 'masquerade', phonetic: '/ˌmæskəˈreɪd/', meaning: 'n. 化装舞会；v. 伪装', category: 'GRE词汇' },
  { word: 'mass', phonetic: '/mæs/', meaning: 'n. 质量；大量', category: '托福词汇' },
  { word: 'massacre', phonetic: '/ˈmæsəkər/', meaning: 'n. 大屠杀；v. 屠杀', category: 'GRE词汇' },
  { word: 'massage', phonetic: '/məˈsɑːʒ/', meaning: 'n. 按摩；v. 按摩', category: '托福词汇' },
  { word: 'massive', phonetic: '/ˈmæsɪv/', meaning: 'adj. 巨大的', category: '托福词汇' },
  { word: 'mast', phonetic: '/mɑːst/', meaning: 'n. 桅杆', category: 'GRE词汇' },
  { word: 'master', phonetic: '/ˈmɑːstər/', meaning: 'n. 主人；大师', category: '托福词汇' },
  { word: 'masterpiece', phonetic: '/ˈmɑːstəpiːs/', meaning: 'n. 杰作', category: '托福词汇' },
  { word: 'mastery', phonetic: '/ˈmɑːstəri/', meaning: 'n. 精通', category: '托福词汇' },
  { word: 'masticate', phonetic: '/ˈmæstɪkeɪt/', meaning: 'v. 咀嚼', category: 'GRE词汇' },
  { word: 'mastodon', phonetic: '/ˈmæstədɒn/', meaning: 'n. 乳齿象', category: 'GRE词汇' },
  { word: 'mat', phonetic: '/mæt/', meaning: 'n. 垫子', category: '托福词汇' },
  { word: 'match', phonetic: '/mætʃ/', meaning: 'n. 比赛；火柴；v. 匹配', category: '托福词汇' },
  { word: 'matchless', phonetic: '/ˈmætʃləs/', meaning: 'adj. 无敌的', category: 'GRE词汇' },
  { word: 'mate', phonetic: '/meɪt/', meaning: 'n. 伙伴；配偶', category: '托福词汇' },
  { word: 'material', phonetic: '/məˈtɪəriəl/', meaning: 'n. 材料；adj. 物质的', category: '托福词汇' },
  { word: 'materialism', phonetic: '/məˈtɪəriəlɪzəm/', meaning: 'n. 唯物主义', category: 'GRE词汇' },
  { word: 'materialize', phonetic: '/məˈtɪəriəlaɪz/', meaning: 'v. 实现', category: 'GRE词汇' },
  { word: 'maternal', phonetic: '/məˈtɜːnl/', meaning: 'adj. 母亲的', category: '托福词汇' },
  { word: 'maternity', phonetic: '/məˈtɜːnəti/', meaning: 'n. 母性；adj. 孕妇的', category: '托福词汇' },
  { word: 'mathematical', phonetic: '/ˌmæθəˈmætɪkl/', meaning: 'adj. 数学的', category: '托福词汇' },
  { word: 'mathematician', phonetic: '/ˌmæθəməˈtɪʃn/', meaning: 'n. 数学家', category: '托福词汇' },
  { word: 'mathematics', phonetic: '/ˌmæθəˈmætɪks/', meaning: 'n. 数学', category: '托福词汇' },
  { word: 'matrix', phonetic: '/ˈmeɪtrɪks/', meaning: 'n. 矩阵', category: '科技词汇' },
  { word: 'matron', phonetic: '/ˈmeɪtrən/', meaning: 'n. 女总管', category: 'GRE词汇' },
  { word: 'matter', phonetic: '/ˈmætər/', meaning: 'n. 物质；事情', category: '托福词汇' },
  { word: 'mattress', phonetic: '/ˈmætrəs/', meaning: 'n. 床垫', category: '托福词汇' },
  { word: 'mature', phonetic: '/məˈtʃʊər/', meaning: 'adj. 成熟的；v. 成熟', category: '托福词汇' },
  { word: 'maturity', phonetic: '/məˈtʃʊərəti/', meaning: 'n. 成熟', category: '托福词汇' },
  { word: 'maudlin', phonetic: '/ˈmɔːdlɪn/', meaning: 'adj. 感伤的', category: 'GRE词汇' },
  { word: 'maul', phonetic: '/mɔːl/', meaning: 'v. 袭击；重伤', category: 'GRE词汇' },
  { word: 'mausoleum', phonetic: '/ˌmɔːsəˈliːəm/', meaning: 'n. 陵墓', category: 'GRE词汇' },
  { word: 'mauve', phonetic: '/məʊv/', meaning: 'n. 淡紫色；adj. 淡紫色的', category: 'GRE词汇' },
  { word: 'maverick', phonetic: '/ˈmævərɪk/', meaning: 'n. 特立独行的人', category: 'GRE词汇' },
  { word: 'maw', phonetic: '/mɔː/', meaning: 'n. 咽喉；胃', category: 'GRE词汇' },
  { word: 'maxim', phonetic: '/ˈmæksɪm/', meaning: 'n. 格言', category: 'GRE词汇' },
  { word: 'maximal', phonetic: '/ˈmæksɪml/', meaning: 'adj. 最大的', category: '托福词汇' },
  { word: 'maximize', phonetic: '/ˈmæksɪmaɪz/', meaning: 'v. 最大化', category: '商务词汇' },
  { word: 'maximum', phonetic: '/ˈmæksɪməm/', meaning: 'n. 最大值；adj. 最大的', category: '托福词汇' },
  { word: 'maybe', phonetic: '/ˈmeɪbi/', meaning: 'adv. 也许', category: '托福词汇' },
  { word: 'mayhem', phonetic: '/ˈmeɪhem/', meaning: 'n. 大混乱', category: 'GRE词汇' },
  { word: 'mayor', phonetic: '/meər/', meaning: 'n. 市长', category: '托福词汇' },
  { word: 'mayoral', phonetic: '/ˈmeərəl/', meaning: 'adj. 市长的', category: 'GRE词汇' },
  { word: 'maze', phonetic: '/meɪz/', meaning: 'n. 迷宫', category: '托福词汇' },
  { word: 'meager', phonetic: '/ˈmiːɡər/', meaning: 'adj. 贫乏的', category: 'GRE词汇' },
  { word: 'meal', phonetic: '/miːl/', meaning: 'n. 膳食', category: '托福词汇' },
  { word: 'mean', phonetic: '/miːn/', meaning: 'v. 意思是；adj. 刻薄的；n. 平均值', category: '托福词汇' },
  { word: 'meaning', phonetic: '/ˈmiːnɪŋ/', meaning: 'n. 意义', category: '托福词汇' },
  { word: 'meaningful', phonetic: '/ˈmiːnɪŋfl/', meaning: 'adj. 有意义的', category: '托福词汇' },
  { word: 'means', phonetic: '/miːnz/', meaning: 'n. 方法；财产', category: '托福词汇' },
  { word: 'meantime', phonetic: '/ˈmiːntaɪm/', meaning: 'n. 其间', category: '托福词汇' },
  { word: 'meanwhile', phonetic: '/ˈmiːnwaɪl/', meaning: 'adv. 同时', category: '托福词汇' },
  { word: 'measles', phonetic: '/ˈmiːzlz/', meaning: 'n. 麻疹', category: '医学词汇' },
  { word: 'measure', phonetic: '/ˈmeʒər/', meaning: 'n. 措施；v. 测量', category: '托福词汇' },
  { word: 'measured', phonetic: '/ˈmeʒərd/', meaning: 'adj. 有分寸的', category: 'GRE词汇' },
  { word: 'measurement', phonetic: '/ˈmeʒəmənt/', meaning: 'n. 测量', category: '托福词汇' },
  { word: 'meat', phonetic: '/miːt/', meaning: 'n. 肉', category: '托福词汇' },
  { word: 'meaty', phonetic: '/ˈmiːti/', meaning: 'adj. 多肉的', category: 'GRE词汇' },
  { word: 'mechanic', phonetic: '/məˈkænɪk/', meaning: 'n. 技工', category: '托福词汇' },
  { word: 'mechanical', phonetic: '/məˈkænɪkl/', meaning: 'adj. 机械的', category: '托福词汇' },
  { word: 'mechanics', phonetic: '/məˈkænɪks/', meaning: 'n. 力学', category: '科技词汇' },
  { word: 'mechanism', phonetic: '/ˈmekənɪzəm/', meaning: 'n. 机制', category: '托福词汇' },
  { word: 'mechanize', phonetic: '/ˈmekənaɪz/', meaning: 'v. 机械化', category: '科技词汇' },
  { word: 'medal', phonetic: '/ˈmedl/', meaning: 'n. 勋章', category: '托福词汇' },
  { word: 'meddle', phonetic: '/ˈmedl/', meaning: 'v. 干涉', category: 'GRE词汇' },
  { word: 'media', phonetic: '/ˈmiːdiə/', meaning: 'n. 媒体', category: '托福词汇' },
  { word: 'medial', phonetic: '/ˈmiːdiəl/', meaning: 'adj. 中间的', category: 'GRE词汇' },
  { word: 'median', phonetic: '/ˈmiːdiən/', meaning: 'adj. 中间的；n. 中位数', category: 'GRE词汇' },
  { word: 'mediate', phonetic: '/ˈmiːdieɪt/', meaning: 'v. 调解', category: '托福词汇' },
  { word: 'mediation', phonetic: '/ˌmiːdiˈeɪʃn/', meaning: 'n. 调解', category: '法律词汇' },
  { word: 'mediator', phonetic: '/ˈmiːdieɪtər/', meaning: 'n. 调解人', category: '法律词汇' },
  { word: 'medic', phonetic: '/ˈmedɪk/', meaning: 'n. 医生', category: '医学词汇' },
  { word: 'medical', phonetic: '/ˈmedɪkl/', meaning: 'adj. 医学的', category: '托福词汇' },
  { word: 'medication', phonetic: '/ˌmedɪˈkeɪʃn/', meaning: 'n. 药物', category: '医学词汇' },
  { word: 'medicine', phonetic: '/ˈmedsn/', meaning: 'n. 医学；药', category: '托福词汇' },
  { word: 'medicinal', phonetic: '/meˈdɪsɪnl/', meaning: 'adj. 药用的', category: '医学词汇' },
  { word: 'medieval', phonetic: '/ˌmediˈiːvl/', meaning: 'adj. 中世纪的', category: '托福词汇' },
  { word: 'mediocre', phonetic: '/ˌmiːdiˈəʊkər/', meaning: 'adj. 平庸的', category: 'GRE词汇' },
  { word: 'mediocrity', phonetic: '/ˌmiːdiˈɒkrəti/', meaning: 'n. 平庸', category: 'GRE词汇' },
  { word: 'meditate', phonetic: '/ˈmedɪteɪt/', meaning: 'v. 冥想；沉思', category: '托福词汇' },
  { word: 'meditation', phonetic: '/ˌmedɪˈteɪʃn/', meaning: 'n. 冥想', category: '托福词汇' },
  { word: 'meditative', phonetic: '/ˈmedɪtətɪv/', meaning: 'adj. 沉思的', category: 'GRE词汇' },
  { word: 'mediterranean', phonetic: '/ˌmedɪtəˈreɪniən/', meaning: 'adj. 地中海的', category: '托福词汇' },
  { word: 'medium', phonetic: '/ˈmiːdiəm/', meaning: 'n. 媒介；adj. 中等的', category: '托福词汇' },
  { word: 'meek', phonetic: '/miːk/', meaning: 'adj. 温顺的', category: 'GRE词汇' },
  { word: 'meet', phonetic: '/miːt/', meaning: 'v. 遇见；n. 会议', category: '托福词汇' },
  { word: 'meeting', phonetic: '/ˈmiːtɪŋ/', meaning: 'n. 会议', category: '托福词汇' },
  { word: 'megaphone', phonetic: '/ˈmeɡəfəʊn/', meaning: 'n. 扩音器', category: 'GRE词汇' },
  { word: 'melee', phonetic: '/ˈmeleɪ/', meaning: 'n. 混战', category: 'GRE词汇' },
  { word: 'melancholy', phonetic: '/ˈmelənkəli/', meaning: 'n. 忧郁；adj. 忧郁的', category: 'GRE词汇' },
  { word: 'melatonin', phonetic: '/ˌmeləˈtəʊnɪn/', meaning: 'n. 褪黑素', category: '医学词汇' },
  { word: 'meld', phonetic: '/meld/', meaning: 'v. 融合', category: 'GRE词汇' },
  { word: 'melee', phonetic: '/meˈleɪ/', meaning: 'n. 混战', category: 'GRE词汇' },
  { word: 'mellifluous', phonetic: '/meˈlɪfluəs/', meaning: 'adj. 悦耳的', category: 'GRE词汇' },
  { word: 'melon', phonetic: '/ˈmelən/', meaning: 'n. 瓜', category: '托福词汇' },
  { word: 'melt', phonetic: '/melt/', meaning: 'v. 融化', category: '托福词汇' },
  { word: 'meltdown', phonetic: '/ˈmeltdaʊn/', meaning: 'n. 熔毁；崩溃', category: 'GRE词汇' },
  { word: 'member', phonetic: '/ˈmembər/', meaning: 'n. 成员', category: '托福词汇' },
  { word: 'membership', phonetic: '/ˈmembəʃɪp/', meaning: 'n. 会员资格', category: '托福词汇' },
  { word: 'membrane', phonetic: '/ˈmembreɪn/', meaning: 'n. 膜', category: '医学词汇' },
  { word: 'memento', phonetic: '/meˈmentəʊ/', meaning: 'n. 纪念品', category: 'GRE词汇' },
  { word: 'memo', phonetic: '/ˈmeməʊ/', meaning: 'n. 备忘录', category: '商务词汇' },
  { word: 'memoir', phonetic: '/ˈmemwɑːr/', meaning: 'n. 回忆录', category: 'GRE词汇' },
  { word: 'memorable', phonetic: '/ˈmemərəbl/', meaning: 'adj. 难忘的', category: '托福词汇' },
  { word: 'memorial', phonetic: '/məˈmɔːriəl/', meaning: 'n. 纪念碑；adj. 纪念的', category: '托福词汇' },
  { word: 'memorandum', phonetic: '/ˌmeməˈrændəm/', meaning: 'n. 备忘录', category: '商务词汇' },
  { word: 'memorize', phonetic: '/ˈmeməraɪz/', meaning: 'v. 记住', category: '托福词汇' },
  { word: 'memory', phonetic: '/ˈmeməri/', meaning: 'n. 记忆', category: '托福词汇' },
  { word: 'memphis', phonetic: '/ˈmemfɪs/', meaning: 'n. 孟菲斯', category: '托福词汇' },
  { word: 'men', phonetic: '/men/', meaning: 'n. man的复数', category: '托福词汇' },
  { word: 'menace', phonetic: '/ˈmenəs/', meaning: 'n. 威胁；v. 威胁', category: 'GRE词汇' },
  { word: 'menagerie', phonetic: '/məˈnædʒəri/', meaning: 'n. 动物园', category: 'GRE词汇' },
  { word: 'mend', phonetic: '/mend/', meaning: 'v. 修理', category: '托福词汇' },
  { word: 'mendacious', phonetic: '/menˈdeɪʃəs/', meaning: 'adj. 虚假的', category: 'GRE词汇' },
  { word: 'mendacity', phonetic: '/menˈdæsəti/', meaning: 'n. 虚假', category: 'GRE词汇' },
  { word: 'menial', phonetic: '/ˈmiːniəl/', meaning: 'adj. 卑微的', category: 'GRE词汇' },
  { word: 'meningitis', phonetic: '/ˌmenɪnˈdʒaɪtɪs/', meaning: 'n. 脑膜炎', category: '医学词汇' },
  { word: 'menopause', phonetic: '/ˈmenəpɔːz/', meaning: 'n. 更年期', category: '医学词汇' },
  { word: 'menses', phonetic: '/ˈmensiːz/', meaning: 'n. 月经', category: '医学词汇' },
  { word: 'menstrual', phonetic: '/ˈmenstruəl/', meaning: 'adj. 月经的', category: '医学词汇' },
  { word: 'menstruate', phonetic: '/ˈmenstrueɪt/', meaning: 'v. 来月经', category: '医学词汇' },
  { word: 'mental', phonetic: '/ˈmentl/', meaning: 'adj. 心理的', category: '托福词汇' },
  { word: 'mentality', phonetic: '/menˈtæləti/', meaning: 'n. 心态', category: '托福词汇' },
  { word: 'mentally', phonetic: '/ˈmentəli/', meaning: 'adv. 心理上地', category: '托福词汇' },
  { word: 'mentation', phonetic: '/menˈteɪʃn/', meaning: 'n. 心理活动', category: 'GRE词汇' },
  { word: 'mentor', phonetic: '/ˈmentɔːr/', meaning: 'n. 导师；v. 指导', category: '托福词汇' },
  { word: 'menu', phonetic: '/ˈmenjuː/', meaning: 'n. 菜单', category: '托福词汇' },
  { word: 'mephitic', phonetic: '/meˈfɪtɪk/', meaning: 'adj. 恶臭的', category: 'GRE词汇' },
  { word: 'mercantile', phonetic: '/ˈmɜːkəntaɪl/', meaning: 'adj. 商业的', category: 'GRE词汇' },
  { word: 'mercenary', phonetic: '/ˈmɜːsənəri/', meaning: 'adj. 唯利是图的；n. 雇佣兵', category: 'GRE词汇' },
  { word: 'merchandise', phonetic: '/ˈmɜːtʃəndaɪs/', meaning: 'n. 商品；v. 经商', category: '商务词汇' },
  { word: 'merchant', phonetic: '/ˈmɜːtʃənt/', meaning: 'n. 商人', category: '托福词汇' },
  { word: 'merciful', phonetic: '/ˈmɜːsɪfl/', meaning: 'adj. 仁慈的', category: '托福词汇' },
  { word: 'merciless', phonetic: '/ˈmɜːsɪləs/', meaning: 'adj. 无情的', category: 'GRE词汇' },
  { word: 'mercury', phonetic: '/ˈmɜːkjəri/', meaning: 'n. 水银；水星', category: '托福词汇' },
  { word: 'mercy', phonetic: '/ˈmɜːsi/', meaning: 'n. 仁慈', category: '托福词汇' },
  { word: 'mere', phonetic: '/mɪər/', meaning: 'adj. 仅仅的', category: '托福词汇' },
  { word: 'merely', phonetic: '/ˈmɪəli/', meaning: 'adv. 仅仅', category: '托福词汇' },
  { word: 'merge', phonetic: '/mɜːdʒ/', meaning: 'v. 合并', category: '托福词汇' },
  { word: 'merger', phonetic: '/ˈmɜːdʒər/', meaning: 'n. 合并', category: '商务词汇' },
  { word: 'meridian', phonetic: '/məˈrɪdiən/', meaning: 'n. 子午线；adj. 顶峰的', category: 'GRE词汇' },
  { word: 'merit', phonetic: '/ˈmerɪt/', meaning: 'n. 优点；v. 值得', category: '托福词汇' },
  { word: 'meritorious', phonetic: '/ˌmerɪˈtɔːriəs/', meaning: 'adj. 值得称赞的', category: 'GRE词汇' },
  { word: 'mermaid', phonetic: '/ˈmɜːmeɪd/', meaning: 'n. 美人鱼', category: '托福词汇' },
  { word: 'merriest', phonetic: '/ˈmeriɪst/', meaning: 'adj. 最快乐的', category: '托福词汇' },
  { word: 'merriment', phonetic: '/ˈmerimənt/', meaning: 'n. 欢乐', category: 'GRE词汇' },
  { word: 'merrily', phonetic: '/ˈmerɪli/', meaning: 'adv. 愉快地', category: '托福词汇' },
  { word: 'merrymaking', phonetic: '/ˈmerimeɪkɪŋ/', meaning: 'n. 欢庆', category: 'GRE词汇' },
  { word: 'merry', phonetic: '/ˈmeri/', meaning: 'adj. 快乐的', category: '托福词汇' },
  { word: 'mesh', phonetic: '/meʃ/', meaning: 'n. 网眼；v. 啮合', category: 'GRE词汇' },
  { word: 'mesmerize', phonetic: '/ˈmezməraɪz/', meaning: 'v. 迷住', category: 'GRE词汇' },
  { word: 'mess', phonetic: '/mes/', meaning: 'n. 混乱；v. 弄乱', category: '托福词汇' },
  { word: 'message', phonetic: '/ˈmesɪdʒ/', meaning: 'n. 消息', category: '托福词汇' },
  { word: 'messenger', phonetic: '/ˈmesɪndʒər/', meaning: 'n. 信使', category: '托福词汇' },
  { word: 'messy', phonetic: '/ˈmesi/', meaning: 'adj. 凌乱的', category: '托福词汇' },
  { word: 'metabolic', phonetic: '/ˌmetəˈbɒlɪk/', meaning: 'adj. 代谢的', category: '医学词汇' },
  { word: 'metabolism', phonetic: '/məˈtæbəlɪzəm/', meaning: 'n. 新陈代谢', category: '医学词汇' },
  { word: 'metabolize', phonetic: '/məˈtæbəlaɪz/', meaning: 'v. 代谢', category: '医学词汇' },
  { word: 'metal', phonetic: '/ˈmetl/', meaning: 'n. 金属', category: '托福词汇' },
  { word: 'metallic', phonetic: '/məˈtælɪk/', meaning: 'adj. 金属的', category: '托福词汇' },
  { word: 'metallurgy', phonetic: '/ˈmetlɜːdʒi/', meaning: 'n. 冶金学', category: '科技词汇' },
  { word: 'metamorphosis', phonetic: '/ˌmetəˈmɔːfəsɪs/', meaning: 'n. 变形', category: 'GRE词汇' },
  { word: 'metaphor', phonetic: '/ˈmetəfər/', meaning: 'n. 隐喻', category: 'GRE词汇' },
  { word: 'metaphorical', phonetic: '/ˌmetəˈfɒrɪkl/', meaning: 'adj. 隐喻的', category: 'GRE词汇' },
  { word: 'metaphysics', phonetic: '/ˌmetəˈfɪzɪks/', meaning: 'n. 形而上学', category: 'GRE词汇' },
  { word: 'mete', phonetic: '/miːt/', meaning: 'v. 分配', category: 'GRE词汇' },
  { word: 'meteor', phonetic: '/ˈmiːtiər/', meaning: 'n. 流星', category: '托福词汇' },
  { word: 'meteoric', phonetic: '/ˌmiːtiˈɒrɪk/', meaning: 'adj. 迅速的', category: 'GRE词汇' },
  { word: 'meteorite', phonetic: '/ˈmiːtiəraɪt/', meaning: 'n. 陨石', category: '托福词汇' },
  { word: 'meteorology', phonetic: '/ˌmiːtiəˈrɒlədʒi/', meaning: 'n. 气象学', category: '科技词汇' },
  { word: 'meter', phonetic: '/ˈmiːtər/', meaning: 'n. 米；仪表', category: '托福词汇' },
  { word: 'method', phonetic: '/ˈmeθəd/', meaning: 'n. 方法', category: '托福词汇' },
  { word: 'methodical', phonetic: '/məˈθɒdɪkl/', meaning: 'adj. 有条理的', category: 'GRE词汇' },
  { word: 'methodology', phonetic: '/ˌmeθəˈdɒlədʒi/', meaning: 'n. 方法论', category: 'GRE词汇' },
  { word: 'meticulous', phonetic: '/məˈtɪkjələs/', meaning: 'adj. 一丝不苟的', category: 'GRE词汇' },
  { word: 'metric', phonetic: '/ˈmetrɪk/', meaning: 'adj. 公制的；n. 度量', category: '托福词汇' },
  { word: 'metropolis', phonetic: '/məˈtrɒpəlɪs/', meaning: 'n. 大都市', category: 'GRE词汇' },
  { word: 'metropolitan', phonetic: '/ˌmetrəˈpɒlɪtən/', meaning: 'adj. 大都市的', category: '托福词汇' },
  { word: 'mettle', phonetic: '/ˈmetl/', meaning: 'n. 勇气', category: 'GRE词汇' },
  { word: 'mew', phonetic: '/mjuː/', meaning: 'v. 咪咪叫', category: 'GRE词汇' },
  { word: 'mewl', phonetic: '/mjuːl/', meaning: 'v. 低声哭泣', category: 'GRE词汇' },
  { word: 'mexican', phonetic: '/ˈmeksɪkən/', meaning: 'adj. 墨西哥的；n. 墨西哥人', category: '托福词汇' },
  { word: 'mexico', phonetic: '/ˈmeksɪkəʊ/', meaning: 'n. 墨西哥', category: '托福词汇' },
  { word: 'mezzanine', phonetic: '/ˈmezəniːn/', meaning: 'n. 夹层', category: 'GRE词汇' },
  { word: 'midair', phonetic: '/ˌmɪdˈeər/', meaning: 'n. 半空中', category: '托福词汇' },
  { word: 'midday', phonetic: '/ˌmɪdˈdeɪ/', meaning: 'n. 中午', category: '托福词汇' },
  { word: 'middle', phonetic: '/ˈmɪdl/', meaning: 'n. 中间；adj. 中间的', category: '托福词汇' },
  { word: 'middleman', phonetic: '/ˈmɪdlmæn/', meaning: 'n. 中间人', category: '商务词汇' },
  { word: 'middling', phonetic: '/ˈmɪdlɪŋ/', meaning: 'adj. 中等的', category: 'GRE词汇' },
  { word: 'midfield', phonetic: '/ˈmɪdfiːld/', meaning: 'n. 中场', category: '托福词汇' },
  { word: 'midlife', phonetic: '/ˈmɪdlaɪf/', meaning: 'n. 中年', category: '托福词汇' },
  { word: 'midnight', phonetic: '/ˈmɪdnaɪt/', meaning: 'n. 午夜', category: '托福词汇' },
  { word: 'midriff', phonetic: '/ˈmɪdrɪf/', meaning: 'n. 横膈膜', category: 'GRE词汇' },
  { word: 'midst', phonetic: '/mɪdst/', meaning: 'n. 中间', category: '托福词汇' },
  { word: 'midway', phonetic: '/ˌmɪdˈweɪ/', meaning: 'adv. 中途地', category: '托福词汇' },
  { word: 'midweek', phonetic: '/ˌmɪdˈwiːk/', meaning: 'n. 一周的中间', category: '托福词汇' },
  { word: 'midwife', phonetic: '/ˈmɪdwaɪf/', meaning: 'n. 助产士', category: '医学词汇' },
  { word: 'might', phonetic: '/maɪt/', meaning: 'aux. 可能；n. 力量', category: '托福词汇' },
  { word: 'mighty', phonetic: '/ˈmaɪti/', meaning: 'adj. 强大的', category: '托福词汇' },
  { word: 'migration', phonetic: '/maɪˈɡreɪʃn/', meaning: 'n. 迁移', category: '托福词汇' },
  { word: 'migratory', phonetic: '/ˈmaɪɡrətri/', meaning: 'adj. 迁徙的', category: 'GRE词汇' },
  { word: 'mild', phonetic: '/maɪld/', meaning: 'adj. 温和的', category: '托福词汇' },
  { word: 'mildew', phonetic: '/ˈmɪldjuː/', meaning: 'n. 霉', category: 'GRE词汇' },
  { word: 'mildly', phonetic: '/ˈmaɪldli/', meaning: 'adv. 温和地', category: '托福词汇' },
  { word: 'mile', phonetic: '/maɪl/', meaning: 'n. 英里', category: '托福词汇' },
  { word: 'mileage', phonetic: '/ˈmaɪlɪdʒ/', meaning: 'n. 英里数', category: '托福词汇' },
  { word: 'milestone', phonetic: '/ˈmaɪlstəʊn/', meaning: 'n. 里程碑', category: '托福词汇' },
  { word: 'militant', phonetic: '/ˈmɪlɪtənt/', meaning: 'adj. 好战的；n. 好战分子', category: 'GRE词汇' },
  { word: 'militarism', phonetic: '/ˈmɪlɪtərɪzəm/', meaning: 'n. 军国主义', category: 'GRE词汇' },
  { word: 'militarist', phonetic: '/ˈmɪlɪtərɪst/', meaning: 'n. 军国主义者', category: 'GRE词汇' },
  { word: 'military', phonetic: '/ˈmɪlɪtəri/', meaning: 'adj. 军事的', category: '托福词汇' },
  { word: 'militia', phonetic: '/məˈlɪʃə/', meaning: 'n. 民兵', category: 'GRE词汇' },
  { word: 'militiaman', phonetic: '/məˈlɪʃəmən/', meaning: 'n. 民兵', category: 'GRE词汇' },
  { word: 'milk', phonetic: '/mɪlk/', meaning: 'n. 牛奶；v. 挤奶', category: '托福词汇' },
  { word: 'milky', phonetic: '/ˈmɪlki/', meaning: 'adj. 乳状的', category: '托福词汇' },
  { word: 'mill', phonetic: '/mɪl/', meaning: 'n. 磨坊；工厂', category: '托福词汇' },
  { word: 'millennium', phonetic: '/mɪˈleniəm/', meaning: 'n. 千年', category: 'GRE词汇' },
  { word: 'miller', phonetic: '/ˈmɪlər/', meaning: 'n. 磨坊主', category: 'GRE词汇' },
  { word: 'millet', phonetic: '/ˈmɪlɪt/', meaning: 'n. 小米', category: 'GRE词汇' },
  { word: 'milligram', phonetic: '/ˈmɪlɪɡræm/', meaning: 'n. 毫克', category: '科技词汇' },
  { word: 'milliliter', phonetic: '/ˈmɪlɪliːtər/', meaning: 'n. 毫升', category: '科技词汇' },
  { word: 'millimeter', phonetic: '/ˈmɪlɪmiːtər/', meaning: 'n. 毫米', category: '科技词汇' },
  { word: 'million', phonetic: '/ˈmɪljən/', meaning: 'n. 百万', category: '托福词汇' },
  { word: 'millionaire', phonetic: '/ˌmɪljəˈneər/', meaning: 'n. 百万富翁', category: '托福词汇' },
  { word: 'mime', phonetic: '/maɪm/', meaning: 'n. 哑剧；v. 演哑剧', category: 'GRE词汇' },
  { word: 'mimic', phonetic: '/ˈmɪmɪk/', meaning: 'v. 模仿；n. 模仿者', category: 'GRE词汇' },
  { word: 'mimicry', phonetic: '/ˈmɪmɪkri/', meaning: 'n. 模仿', category: 'GRE词汇' },
  { word: 'mince', phonetic: '/mɪns/', meaning: 'v. 切碎；n. 肉末', category: 'GRE词汇' },
  { word: 'mind', phonetic: '/maɪnd/', meaning: 'n. 思想；v. 介意', category: '托福词汇' },
  { word: 'mindful', phonetic: '/ˈmaɪndfl/', meaning: 'adj. 留心的', category: '托福词汇' },
  { word: 'mindless', phonetic: '/ˈmaɪndləs/', meaning: 'adj. 不用脑的', category: 'GRE词汇' },
  { word: 'mine', phonetic: '/maɪn/', meaning: 'pron. 我的；n. 矿；v. 开采', category: '托福词汇' },
  { word: 'miner', phonetic: '/ˈmaɪnər/', meaning: 'n. 矿工', category: '托福词汇' },
  { word: 'mineral', phonetic: '/ˈmɪnərəl/', meaning: 'n. 矿物', category: '托福词汇' },
  { word: 'mineralogy', phonetic: '/ˌmɪnəˈrælədʒi/', meaning: 'n. 矿物学', category: '科技词汇' },
  { word: 'mingle', phonetic: '/ˈmɪŋɡl/', meaning: 'v. 混合', category: 'GRE词汇' },
  { word: 'miniature', phonetic: '/ˈmɪnətʃər/', meaning: 'adj. 微型的；n. 缩图', category: 'GRE词汇' },
  { word: 'miniaturization', phonetic: '/ˌmɪnətʃəraɪˈzeɪʃn/', meaning: 'n. 小型化', category: '科技词汇' },
  { word: 'minimize', phonetic: '/ˈmɪnɪmaɪz/', meaning: 'v. 最小化', category: '托福词汇' },
  { word: 'minimum', phonetic: '/ˈmɪnɪməm/', meaning: 'n. 最小值；adj. 最小的', category: '托福词汇' },
  { word: 'minion', phonetic: '/ˈmɪnjən/', meaning: 'n. 奴才', category: 'GRE词汇' },
  { word: 'minister', phonetic: '/ˈmɪnɪstər/', meaning: 'n. 部长；牧师', category: '托福词汇' },
  { word: 'ministry', phonetic: '/ˈmɪnɪstri/', meaning: 'n. 部', category: '托福词汇' },
  { word: 'mink', phonetic: '/mɪŋk/', meaning: 'n. 貂', category: 'GRE词汇' },
  { word: 'minor', phonetic: '/ˈmaɪnər/', meaning: 'adj. 较小的；n. 未成年人', category: '托福词汇' },
  { word: 'minority', phonetic: '/maɪˈnɒrəti/', meaning: 'n. 少数；少数民族', category: '托福词汇' },
  { word: 'minstrel', phonetic: '/ˈmɪnstrəl/', meaning: 'n. 吟游诗人', category: 'GRE词汇' },
  { word: 'mint', phonetic: '/mɪnt/', meaning: 'n. 薄荷；造币厂；v. 铸造', category: '托福词汇' },
  { word: 'minus', phonetic: '/ˈmaɪnəs/', meaning: 'prep. 减去；adj. 负的', category: '托福词汇' },
  { word: 'minute', phonetic: '/ˈmɪnɪt/', meaning: 'n. 分钟；adj. 微小的', category: '托福词汇' },
  { word: 'minutely', phonetic: '/ˈmɪnjuːtli/', meaning: 'adv. 详细地', category: 'GRE词汇' },
  { word: 'minutia', phonetic: '/maɪˈnjuːʃə/', meaning: 'n. 细节', category: 'GRE词汇' },
  { word: 'miracle', phonetic: '/ˈmɪrəkl/', meaning: 'n. 奇迹', category: '托福词汇' },
  { word: 'miraculous', phonetic: '/mɪˈrækjələs/', meaning: 'adj. 奇迹的', category: 'GRE词汇' },
  { word: 'mirage', phonetic: '/mɪˈrɑːʒ/', meaning: 'n. 海市蜃楼', category: 'GRE词汇' },
  { word: 'mire', phonetic: '/maɪər/', meaning: 'n. 泥潭；v. 陷入', category: 'GRE词汇' },
  { word: 'mirror', phonetic: '/ˈmɪrər/', meaning: 'n. 镜子；v. 反映', category: '托福词汇' },
  { word: 'mirth', phonetic: '/mɜːθ/', meaning: 'n. 欢乐', category: 'GRE词汇' },
  { word: 'mirthful', phonetic: '/ˈmɜːθfl/', meaning: 'adj. 欢乐的', category: 'GRE词汇' },
  { word: 'misadventure', phonetic: '/ˌmɪsədˈventʃər/', meaning: 'n. 不幸事故', category: 'GRE词汇' },
  { word: 'misalliance', phonetic: '/ˌmɪsəˈlaɪəns/', meaning: 'n. 不当的联合', category: 'GRE词汇' },
  { word: 'misapprehend', phonetic: '/ˌmɪsæprɪˈhend/', meaning: 'v. 误解', category: 'GRE词汇' },
  { word: 'misbehave', phonetic: '/ˌmɪsbɪˈheɪv/', meaning: 'v. 行为不端', category: '托福词汇' },
  { word: 'misbehavior', phonetic: '/ˌmɪsbɪˈheɪvjər/', meaning: 'n. 不当行为', category: '托福词汇' },
  { word: 'miscalculate', phonetic: '/mɪsˈkælkjuleɪt/', meaning: 'v. 误算', category: 'GRE词汇' },
  { word: 'miscast', phonetic: '/ˌmɪsˈkɑːst/', meaning: 'v. 选角不当', category: 'GRE词汇' },
  { word: 'miscellaneous', phonetic: '/ˌmɪsəˈleɪniəs/', meaning: 'adj. 杂项的', category: 'GRE词汇' },
  { word: 'mischief', phonetic: '/ˈmɪstʃɪf/', meaning: 'n. 恶作剧', category: '托福词汇' },
  { word: 'mischievous', phonetic: '/ˈmɪstʃɪvəs/', meaning: 'adj. 恶作剧的', category: 'GRE词汇' },
  { word: 'misconception', phonetic: '/ˌmɪskənˈsepʃn/', meaning: 'n. 误解', category: '托福词汇' },
  { word: 'misconduct', phonetic: '/mɪsˈkɒndʌkt/', meaning: 'n. 不当行为', category: '法律词汇' },
  { word: 'misconstruction', phonetic: '/ˌmɪskənˈstrʌkʃn/', meaning: 'n. 曲解', category: 'GRE词汇' },
  { word: 'miscreate', phonetic: '/mɪsˈkriːeɪt/', meaning: 'v. 错误创造', category: 'GRE词汇' },
  { word: 'miscreant', phonetic: '/ˈmɪskriənt/', meaning: 'n. 恶棍', category: 'GRE词汇' },
  { word: 'misdemeanor', phonetic: '/ˌmɪsdɪˈmiːnər/', meaning: 'n. 轻罪', category: '法律词汇' },
  { word: 'misdirect', phonetic: '/ˌmɪsdɪˈrekt/', meaning: 'v. 误导', category: 'GRE词汇' },
  { word: 'misdoing', phonetic: '/mɪsˈduːɪŋ/', meaning: 'n. 坏事', category: 'GRE词汇' },
  { word: 'miser', phonetic: '/ˈmaɪzər/', meaning: 'n. 吝啬鬼', category: 'GRE词汇' },
  { word: 'miserable', phonetic: '/ˈmɪzrəbl/', meaning: 'adj. 悲惨的', category: '托福词汇' },
  { word: 'miserly', phonetic: '/ˈmaɪzəli/', meaning: 'adj. 吝啬的', category: 'GRE词汇' },
  { word: 'misery', phonetic: '/ˈmɪzəri/', meaning: 'n. 悲惨', category: '托福词汇' },
  { word: 'misfaith', phonetic: '/mɪsˈfeɪθ/', meaning: 'n. 不信任', category: 'GRE词汇' },
  { word: 'misfortune', phonetic: '/mɪsˈfɔːtʃuːn/', meaning: 'n. 不幸', category: '托福词汇' },
  { word: 'misgiving', phonetic: '/mɪsˈɡɪvɪŋ/', meaning: 'n. 疑虑', category: 'GRE词汇' },
  { word: 'misguide', phonetic: '/mɪsˈɡaɪd/', meaning: 'v. 误导', category: 'GRE词汇' },
  { word: 'misguide', phonetic: '/mɪsˈɡaɪd/', meaning: 'v. 误导', category: 'GRE词汇' },
  { word: 'misguided', phonetic: '/mɪsˈɡaɪdɪd/', meaning: 'adj. 被误导的', category: 'GRE词汇' },
  { word: 'mishandle', phonetic: '/mɪsˈhændl/', meaning: 'v. 处理不当', category: 'GRE词汇' },
  { word: 'mishap', phonetic: '/ˈmɪshæp/', meaning: 'n. 小事故', category: 'GRE词汇' },
  { word: 'misinform', phonetic: '/ˌmɪsɪnˈfɔːm/', meaning: 'v. 误传', category: 'GRE词汇' },
  { word: 'misinterpret', phonetic: '/ˌmɪsɪnˈtɜːprɪt/', meaning: 'v. 曲解', category: 'GRE词汇' },
  { word: 'misjudge', phonetic: '/mɪsˈdʒʌdʒ/', meaning: 'v. 判断错误', category: 'GRE词汇' },
  { word: 'mislay', phonetic: '/mɪsˈleɪ/', meaning: 'v. 放错地方', category: 'GRE词汇' },
  { word: 'mislead', phonetic: '/mɪsˈliːd/', meaning: 'v. 误导', category: '托福词汇' },
  { word: 'misleading', phonetic: '/mɪsˈliːdɪŋ/', meaning: 'adj. 误导的', category: '托福词汇' },
  { word: 'mislike', phonetic: '/mɪsˈlaɪk/', meaning: 'v. 厌恶', category: 'GRE词汇' },
  { word: 'misplace', phonetic: '/mɪsˈpleɪs/', meaning: 'v. 放错位置', category: '托福词汇' },
  { word: 'misprint', phonetic: '/mɪsˈprɪnt/', meaning: 'v. 印错；n. 印刷错误', category: 'GRE词汇' },
  { word: 'mispronounce', phonetic: '/ˌmɪsprəˈnaʊns/', meaning: 'v. 发音错误', category: 'GRE词汇' },
  { word: 'misread', phonetic: '/mɪsˈriːd/', meaning: 'v. 读错', category: 'GRE词汇' },
  { word: 'misrepresent', phonetic: '/ˌmɪsreprɪˈzent/', meaning: 'v. 歪曲', category: 'GRE词汇' },
  { word: 'miss', phonetic: '/mɪs/', meaning: 'v. 想念；错过；n. 小姐', category: '托福词汇' },
  { word: 'missile', phonetic: '/ˈmɪsaɪl/', meaning: 'n. 导弹', category: '托福词汇' },
  { word: 'missing', phonetic: '/ˈmɪsɪŋ/', meaning: 'adj. 缺少的', category: '托福词汇' },
  { word: 'mission', phonetic: '/ˈmɪʃn/', meaning: 'n. 使命', category: '托福词汇' },
  { word: 'missionary', phonetic: '/ˈmɪʃənri/', meaning: 'n. 传教士', category: 'GRE词汇' },
  { word: 'misspell', phonetic: '/mɪsˈspel/', meaning: 'v. 拼错', category: '托福词汇' },
  { word: 'misstatement', phonetic: '/mɪsˈsteɪtmənt/', meaning: 'n. 虚假陈述', category: 'GRE词汇' },
  { word: 'mist', phonetic: '/mɪst/', meaning: 'n. 薄雾', category: '托福词汇' },
  { word: 'mistake', phonetic: '/mɪˈsteɪk/', meaning: 'n. 错误；v. 弄错', category: '托福词汇' },
  { word: 'mistaken', phonetic: '/mɪˈsteɪkən/', meaning: 'adj. 错误的', category: '托福词汇' },
  { word: 'mister', phonetic: '/ˈmɪstər/', meaning: 'n. 先生', category: '托福词汇' },
  { word: 'mistime', phonetic: '/mɪsˈtaɪm/', meaning: 'v. 时机不当', category: 'GRE词汇' },
  { word: 'mistress', phonetic: '/ˈmɪstrəs/', meaning: 'n. 女主人；情妇', category: '托福词汇' },
  { word: 'misty', phonetic: '/ˈmɪsti/', meaning: 'adj. 有雾的', category: '托福词汇' },
  { word: 'misunderstand', phonetic: '/ˌmɪsʌndərˈstænd/', meaning: 'v. 误解', category: '托福词汇' },
  { word: 'misunderstanding', phonetic: '/ˌmɪsʌndərˈstændɪŋ/', meaning: 'n. 误解', category: '托福词汇' },
  { word: 'misuse', phonetic: '/mɪsˈjuːz/', meaning: 'v. 滥用；n. 滥用', category: '托福词汇' },
  { word: 'mite', phonetic: '/maɪt/', meaning: 'n. 螨；一点点', category: 'GRE词汇' },
  { word: 'mitigate', phonetic: '/ˈmɪtɪɡeɪt/', meaning: 'v. 减轻', category: 'GRE词汇' },
  { word: 'mitigation', phonetic: '/ˌmɪtɪˈɡeɪʃn/', meaning: 'n. 减轻', category: '法律词汇' },
  { word: 'mitigator', phonetic: '/ˈmɪtɪɡeɪtər/', meaning: 'n. 缓和者', category: 'GRE词汇' },
  { word: 'mitochondria', phonetic: '/ˌmaɪtəʊˈkɒndriə/', meaning: 'n. 线粒体', category: '医学词汇' },
  { word: 'mitt', phonetic: '/mɪt/', meaning: 'n. 连指手套', category: 'GRE词汇' },
  { word: 'mitten', phonetic: '/ˈmɪtn/', meaning: 'n. 连指手套', category: '托福词汇' },
  { word: 'mix', phonetic: '/mɪks/', meaning: 'v. 混合；n. 混合物', category: '托福词汇' },
  { word: 'mixed', phonetic: '/mɪkst/', meaning: 'adj. 混合的', category: '托福词汇' },
  { word: 'mixture', phonetic: '/ˈmɪkstʃər/', meaning: 'n. 混合物', category: '托福词汇' },
  { word: 'moan', phonetic: '/məʊn/', meaning: 'v. 呻吟；n. 呻吟声', category: '托福词汇' },
  { word: 'moat', phonetic: '/məʊt/', meaning: 'n. 护城河', category: 'GRE词汇' },
  { word: 'mob', phonetic: '/mɒb/', meaning: 'n. 暴民；v. 围攻', category: '托福词汇' },
  { word: 'mobile', phonetic: '/ˈməʊbaɪl/', meaning: 'adj. 移动的；n. 手机', category: '托福词汇' },
  { word: 'mobility', phonetic: '/məʊˈbɪləti/', meaning: 'n. 流动性', category: '托福词汇' },
  { word: 'mobilization', phonetic: '/ˌməʊbɪlaɪˈzeɪʃn/', meaning: 'n. 动员', category: 'GRE词汇' },
  { word: 'mobilize', phonetic: '/ˈməʊbɪlaɪz/', meaning: 'v. 动员', category: 'GRE词汇' },
  { word: 'mock', phonetic: '/mɒk/', meaning: 'v. 嘲笑；adj. 假的', category: '托福词汇' },
  { word: 'mockery', phonetic: '/ˈmɒkəri/', meaning: 'n. 嘲弄', category: 'GRE词汇' },
  { word: 'mode', phonetic: '/məʊd/', meaning: 'n. 方式；模式', category: '托福词汇' },
  { word: 'model', phonetic: '/ˈmɒdl/', meaning: 'n. 模型；v. 模仿', category: '托福词汇' },
  { word: 'moderate', phonetic: '/ˈmɒdərət/', meaning: 'adj. 适度的；v. 缓和', category: '托福词汇' },
  { word: 'moderation', phonetic: '/ˌmɒdəˈreɪʃn/', meaning: 'n. 适度', category: '托福词汇' },
  { word: 'moderator', phonetic: '/ˈmɒdəreɪtər/', meaning: 'n. 调解人', category: 'GRE词汇' },
  { word: 'modern', phonetic: '/ˈmɒdn/', meaning: 'adj. 现代的', category: '托福词汇' },
  { word: 'modernization', phonetic: '/ˌmɒdnəˈzeɪʃn/', meaning: 'n. 现代化', category: '托福词汇' },
  { word: 'modernize', phonetic: '/ˈmɒdnəz/', meaning: 'v. 现代化', category: '托福词汇' },
  { word: 'modest', phonetic: '/ˈmɒdɪst/', meaning: 'adj. 谦虚的；适度的', category: '托福词汇' },
  { word: 'modesty', phonetic: '/ˈmɒdɪsti/', meaning: 'n. 谦虚', category: '托福词汇' },
  { word: 'modification', phonetic: '/ˌmɒdɪfɪˈkeɪʃn/', meaning: 'n. 修改', category: '托福词汇' },
  { word: 'modify', phonetic: '/ˈmɒdɪfaɪ/', meaning: 'v. 修改', category: '托福词汇' },
  { word: 'modish', phonetic: '/ˈməʊdɪʃ/', meaning: 'adj. 时髦的', category: 'GRE词汇' },
  { word: 'module', phonetic: '/ˈmɒdjuːl/', meaning: 'n. 模块', category: '托福词汇' },
  { word: 'moist', phonetic: '/mɔɪst/', meaning: 'adj. 潮湿的', category: '托福词汇' },
  { word: 'moisten', phonetic: '/ˈmɔɪsn/', meaning: 'v. 弄湿', category: 'GRE词汇' },
  { word: 'moisture', phonetic: '/ˈmɔɪstʃər/', meaning: 'n. 湿气', category: '托福词汇' },
  { word: 'molar', phonetic: '/ˈməʊlər/', meaning: 'n. 臼齿；adj. 臼齿的', category: '医学词汇' },
  { word: 'mold', phonetic: '/məʊld/', meaning: 'n. 模子；霉菌；v. 塑造', category: '托福词汇' },
  { word: 'molder', phonetic: '/ˈməʊldər/', meaning: 'v. 腐烂', category: 'GRE词汇' },
  { word: 'mole', phonetic: '/məʊl/', meaning: 'n. 痣；鼹鼠；摩尔', category: '托福词汇' },
  { word: 'molecular', phonetic: '/məˈlekjələr/', meaning: 'adj. 分子的', category: '科技词汇' },
  { word: 'molecule', phonetic: '/ˈmɒlɪkjuːl/', meaning: 'n. 分子', category: '托福词汇' },
  { word: 'molehill', phonetic: '/ˈməʊlhɪl/', meaning: 'n. 鼹鼠丘', category: 'GRE词汇' },
  { word: 'mollify', phonetic: '/ˈmɒlɪfaɪ/', meaning: 'v. 平息', category: 'GRE词汇' },
  { word: 'mollusk', phonetic: '/ˈmɒləsk/', meaning: 'n. 软体动物', category: 'GRE词汇' },
  { word: 'molten', phonetic: '/ˈməʊltən/', meaning: 'adj. 熔融的', category: 'GRE词汇' },
  { word: 'moment', phonetic: '/ˈməʊmənt/', meaning: 'n. 片刻', category: '托福词汇' },
  { word: 'momentary', phonetic: '/ˈməʊməntri/', meaning: 'adj. 瞬间的', category: 'GRE词汇' },
  { word: 'momentous', phonetic: '/məˈmentəs/', meaning: 'adj. 重大的', category: 'GRE词汇' },
  { word: 'momentum', phonetic: '/məˈmentəm/', meaning: 'n. 动量；动力', category: '托福词汇' },
  { word: 'monarch', phonetic: '/ˈmɒnək/', meaning: 'n. 君主', category: 'GRE词汇' },
  { word: 'monarchy', phonetic: '/ˈmɒnəki/', meaning: 'n. 君主制', category: 'GRE词汇' },
  { word: 'monastery', phonetic: '/ˈmɒnəstri/', meaning: 'n. 修道院', category: 'GRE词汇' },
  { word: 'monastic', phonetic: '/məˈnæstɪk/', meaning: 'adj. 修道院的', category: 'GRE词汇' },
  { word: 'monday', phonetic: '/ˈmʌndeɪ/', meaning: 'n. 星期一', category: '托福词汇' },
  { word: 'monetary', phonetic: '/ˈmʌnɪtri/', meaning: 'adj. 货币的', category: '商务词汇' },
  { word: 'money', phonetic: '/ˈmʌni/', meaning: 'n. 钱', category: '托福词汇' },
  { word: 'moneylender', phonetic: '/ˈmʌnilendər/', meaning: 'n. 放贷人', category: '商务词汇' },
  { word: 'moneymaker', phonetic: '/ˈmʌnimeɪkər/', meaning: 'n. 摇钱树', category: '商务词汇' },
  { word: 'mongrel', phonetic: '/ˈmʌŋɡrəl/', meaning: 'n. 杂种狗', category: 'GRE词汇' },
  { word: 'moniker', phonetic: '/ˈmɒnɪkər/', meaning: 'n. 绰号', category: 'GRE词汇' },
  { word: 'monitor', phonetic: '/ˈmɒnɪtər/', meaning: 'n. 显示器；v. 监控', category: '托福词汇' },
  { word: 'monk', phonetic: '/mʌŋk/', meaning: 'n. 僧侣', category: '托福词汇' },
  { word: 'monkey', phonetic: '/ˈmʌŋki/', meaning: 'n. 猴子', category: '托福词汇' },
  { word: 'mono', phonetic: '/ˈmɒnəʊ/', meaning: 'adj. 单声道的', category: '科技词汇' },
  { word: 'monochrome', phonetic: '/ˈmɒnəkrəʊm/', meaning: 'adj. 单色的', category: 'GRE词汇' },
  { word: 'monocle', phonetic: '/ˈmɒnəkl/', meaning: 'n. 单片眼镜', category: 'GRE词汇' },
  { word: 'monogamy', phonetic: '/məˈnɒɡəmi/', meaning: 'n. 一夫一妻制', category: 'GRE词汇' },
  { word: 'monogram', phonetic: '/ˈmɒnəɡræm/', meaning: 'n. 字母组合', category: 'GRE词汇' },
  { word: 'monograph', phonetic: '/ˈmɒnəɡrɑːf/', meaning: 'n. 专著', category: 'GRE词汇' },
  { word: 'monologue', phonetic: '/ˈmɒnəlɒɡ/', meaning: 'n. 独白', category: 'GRE词汇' },
  { word: 'monolith', phonetic: '/ˈmɒnəlɪθ/', meaning: 'n. 独石', category: 'GRE词汇' },
  { word: 'monolithic', phonetic: '/ˌmɒnəˈlɪθɪk/', meaning: 'adj. 整体的', category: 'GRE词汇' },
  { word: 'monomania', phonetic: '/ˌmɒnəˈmeɪniə/', meaning: 'n. 偏执狂', category: 'GRE词汇' },
  { word: 'monopoly', phonetic: '/məˈnɒpəli/', meaning: 'n. 垄断', category: '商务词汇' },
  { word: 'monopolize', phonetic: '/məˈnɒpəlaɪz/', meaning: 'v. 垄断', category: '商务词汇' },
  { word: 'monotonous', phonetic: '/məˈnɒtənəs/', meaning: 'adj. 单调的', category: 'GRE词汇' },
  { word: 'monotony', phonetic: '/məˈnɒtəni/', meaning: 'n. 单调', category: 'GRE词汇' },
  { word: 'monster', phonetic: '/ˈmɒnstər/', meaning: 'n. 怪物', category: '托福词汇' },
  { word: 'monstrous', phonetic: '/ˈmɒnstrəs/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'montage', phonetic: '/mɒnˈtɑːʒ/', meaning: 'n. 蒙太奇', category: 'GRE词汇' },
  { word: 'month', phonetic: '/mʌnθ/', meaning: 'n. 月', category: '托福词汇' },
  { word: 'monthly', phonetic: '/ˈmʌnθli/', meaning: 'adj. 每月的；n. 月刊', category: '托福词汇' },
  { word: 'monument', phonetic: '/ˈmɒnjumənt/', meaning: 'n. 纪念碑', category: '托福词汇' },
  { word: 'monumental', phonetic: '/ˌmɒnjuˈmentl/', meaning: 'adj. 纪念碑的；巨大的', category: 'GRE词汇' },
  { word: 'monumentally', phonetic: '/ˌmɒnjuˈmentəli/', meaning: 'adv. 巨大地', category: 'GRE词汇' },
  { word: 'moo', phonetic: '/muː/', meaning: 'v. 哞哞叫', category: 'GRE词汇' },
  { word: 'mood', phonetic: '/muːd/', meaning: 'n. 心情', category: '托福词汇' },
  { word: 'moody', phonetic: '/ˈmuːdi/', meaning: 'adj. 喜怒无常的', category: '托福词汇' },
  { word: 'moon', phonetic: '/muːn/', meaning: 'n. 月亮', category: '托福词汇' },
  { word: 'moonlight', phonetic: '/ˈmuːnlaɪt/', meaning: 'n. 月光；v. 兼职', category: '托福词汇' },
  { word: 'moonlit', phonetic: '/ˈmuːnlɪt/', meaning: 'adj. 月光照耀的', category: 'GRE词汇' },
  { word: 'moor', phonetic: '/mɔːr/', meaning: 'n. 荒原；v. 停泊', category: 'GRE词汇' },
  { word: 'moorish', phonetic: '/ˈmʊərɪʃ/', meaning: 'adj. 摩尔式的', category: 'GRE词汇' },
  { word: 'moose', phonetic: '/muːs/', meaning: 'n. 驼鹿', category: 'GRE词汇' },
  { word: 'moot', phonetic: '/muːt/', meaning: 'adj. 无实际意义的；v. 讨论', category: 'GRE词汇' },
  { word: 'mop', phonetic: '/mɒp/', meaning: 'n. 拖把；v. 擦', category: '托福词汇' },
  { word: 'mope', phonetic: '/məʊp/', meaning: 'v. 闷闷不乐', category: 'GRE词汇' },
  { word: 'moral', phonetic: '/ˈmɒrəl/', meaning: 'adj. 道德的；n. 寓意', category: '托福词汇' },
  { word: 'morale', phonetic: '/məˈrɑːl/', meaning: 'n. 士气', category: '托福词汇' },
  { word: 'moralist', phonetic: '/ˈmɒrəlɪst/', meaning: 'n. 道德家', category: 'GRE词汇' },
  { word: 'morality', phonetic: '/məˈræləti/', meaning: 'n. 道德', category: '托福词汇' },
  { word: 'moralize', phonetic: '/ˈmɒrəlaɪz/', meaning: 'v. 说教', category: 'GRE词汇' },
  { word: 'morass', phonetic: '/məˈræs/', meaning: 'n. 沼泽；困境', category: 'GRE词汇' },
  { word: 'moratorium', phonetic: '/ˌmɒrəˈtɔːriəm/', meaning: 'n. 暂停', category: 'GRE词汇' },
  { word: 'morbid', phonetic: '/ˈmɔːbɪd/', meaning: 'adj. 病态的', category: 'GRE词汇' },
  { word: 'morbidity', phonetic: '/mɔːˈbɪdəti/', meaning: 'n. 病态', category: '医学词汇' },
  { word: 'morbidly', phonetic: '/ˈmɔːbɪdli/', meaning: 'adv. 病态地', category: 'GRE词汇' },
  { word: 'more', phonetic: '/mɔːr/', meaning: 'adj. 更多的；adv. 更多', category: '托福词汇' },
  { word: 'moreover', phonetic: '/mɔːrˈəʊvər/', meaning: 'adv. 此外', category: '托福词汇' },
  { word: 'morganatic', phonetic: '/ˌmɔːɡəˈnætɪk/', meaning: 'adj. 贵贱通婚的', category: 'GRE词汇' },
  { word: 'morgue', phonetic: '/mɔːɡ/', meaning: 'n. 停尸房', category: 'GRE词汇' },
  { word: 'moribund', phonetic: '/ˈmɒrɪbʌnd/', meaning: 'adj. 垂死的', category: 'GRE词汇' },
  { word: 'morning', phonetic: '/ˈmɔːnɪŋ/', meaning: 'n. 早晨', category: '托福词汇' },
  { word: 'moron', phonetic: '/ˈmɔːrɒn/', meaning: 'n. 笨蛋', category: 'GRE词汇' },
  { word: 'moronic', phonetic: '/məˈrɒnɪk/', meaning: 'adj. 愚蠢的', category: 'GRE词汇' },
  { word: 'morose', phonetic: '/məˈrəʊs/', meaning: 'adj. 郁闷的', category: 'GRE词汇' },
  { word: 'morph', phonetic: '/mɔːf/', meaning: 'v. 变形', category: 'GRE词汇' },
  { word: 'morphine', phonetic: '/ˈmɔːfiːn/', meaning: 'n. 吗啡', category: '医学词汇' },
  { word: 'morphology', phonetic: '/mɔːˈfɒlədʒi/', meaning: 'n. 形态学', category: 'GRE词汇' },
  { word: 'morrow', phonetic: '/ˈmɒrəʊ/', meaning: 'n. 次日', category: 'GRE词汇' },
  { word: 'morsel', phonetic: '/ˈmɔːsl/', meaning: 'n. 小块食物', category: 'GRE词汇' },
  { word: 'mortal', phonetic: '/ˈmɔːtl/', meaning: 'adj. 会死的；n. 凡人', category: '托福词汇' },
  { word: 'mortality', phonetic: '/mɔːˈtæləti/', meaning: 'n. 死亡率', category: '医学词汇' },
  { word: 'mortally', phonetic: '/ˈmɔːtəli/', meaning: 'adv. 致命地', category: 'GRE词汇' },
  { word: 'mortar', phonetic: '/ˈmɔːtər/', meaning: 'n. 砂浆；迫击炮', category: 'GRE词汇' },
  { word: 'mortgage', phonetic: '/ˈmɔːɡɪdʒ/', meaning: 'n. 抵押；v. 抵押', category: '商务词汇' },
  { word: 'mortify', phonetic: '/ˈmɔːtɪfaɪ/', meaning: 'v. 使羞愧', category: 'GRE词汇' },
  { word: 'mortuary', phonetic: '/ˈmɔːtʃuəri/', meaning: 'n. 停尸房', category: 'GRE词汇' },
  { word: 'mosaic', phonetic: '/məʊˈzeɪɪk/', meaning: 'n. 马赛克', category: 'GRE词汇' },
  { word: 'mosque', phonetic: '/mɒsk/', meaning: 'n. 清真寺', category: '托福词汇' },
  { word: 'mosquito', phonetic: '/məˈskiːtəʊ/', meaning: 'n. 蚊子', category: '托福词汇' },
  { word: 'moss', phonetic: '/mɒs/', meaning: 'n. 苔藓', category: '托福词汇' },
  { word: 'mossy', phonetic: '/ˈmɒsi/', meaning: 'adj. 长满苔藓的', category: 'GRE词汇' },
  { word: 'most', phonetic: '/məʊst/', meaning: 'adj. 最多的；adv. 最', category: '托福词汇' },
  { word: 'mostly', phonetic: '/ˈməʊstli/', meaning: 'adv. 主要地', category: '托福词汇' },
  { word: 'mot', phonetic: '/məʊ/', meaning: 'n. 妙语', category: 'GRE词汇' },
  { word: 'motel', phonetic: '/məʊˈtel/', meaning: 'n. 汽车旅馆', category: '托福词汇' },
  { word: 'moth', phonetic: '/mɒθ/', meaning: 'n. 蛾', category: '托福词汇' },
  { word: 'mother', phonetic: '/ˈmʌðər/', meaning: 'n. 母亲', category: '托福词汇' },
  { word: 'motherland', phonetic: '/ˈmʌðəlænd/', meaning: 'n. 祖国', category: '托福词汇' },
  { word: 'motif', phonetic: '/məʊˈtiːf/', meaning: 'n. 主题', category: 'GRE词汇' },
  { word: 'motion', phonetic: '/ˈməʊʃn/', meaning: 'n. 运动；v. 示意', category: '托福词汇' },
  { word: 'motionless', phonetic: '/ˈməʊʃənləs/', meaning: 'adj. 静止的', category: 'GRE词汇' },
  { word: 'motivate', phonetic: '/ˈməʊtɪveɪt/', meaning: 'v. 激励', category: '托福词汇' },
  { word: 'motivation', phonetic: '/ˌməʊtɪˈveɪʃn/', meaning: 'n. 动力', category: '托福词汇' },
  { word: 'motive', phonetic: '/ˈməʊtɪv/', meaning: 'n. 动机', category: '托福词汇' },
  { word: 'motley', phonetic: '/ˈmɒtli/', meaning: 'adj. 混杂的', category: 'GRE词汇' },
  { word: 'motor', phonetic: '/ˈməʊtər/', meaning: 'n. 发动机', category: '托福词汇' },
  { word: 'motorcycle', phonetic: '/ˈməʊtəsaɪkl/', meaning: 'n. 摩托车', category: '托福词汇' },
  { word: 'motorist', phonetic: '/ˈməʊtərɪst/', meaning: 'n. 驾车者', category: '托福词汇' },
  { word: 'motorway', phonetic: '/ˈməʊtəweɪ/', meaning: 'n. 高速公路', category: '托福词汇' },
  { word: 'mottled', phonetic: '/ˈmɒtld/', meaning: 'adj. 斑驳的', category: 'GRE词汇' },
  { word: 'motto', phonetic: '/ˈmɒtəʊ/', meaning: 'n. 座右铭', category: '托福词汇' },
  { word: 'mould', phonetic: '/məʊld/', meaning: 'n. 模子；v. 塑造', category: '托福词汇' },
  { word: 'moult', phonetic: '/məʊlt/', meaning: 'v. 蜕皮', category: 'GRE词汇' },
  { word: 'mound', phonetic: '/maʊnd/', meaning: 'n. 土堆', category: 'GRE词汇' },
  { word: 'mount', phonetic: '/maʊnt/', meaning: 'v. 登上；n. 山', category: '托福词汇' },
  { word: 'mountain', phonetic: '/ˈmaʊntən/', meaning: 'n. 山', category: '托福词汇' },
  { word: 'mountaineer', phonetic: '/ˌmaʊntəˈnɪər/', meaning: 'n. 登山者', category: 'GRE词汇' },
  { word: 'mountainous', phonetic: '/ˈmaʊntənəs/', meaning: 'adj. 多山的', category: '托福词汇' },
  { word: 'mounting', phonetic: '/ˈmaʊntɪŋ/', meaning: 'adj. 增加的', category: 'GRE词汇' },
  { word: 'mourn', phonetic: '/mɔːn/', meaning: 'v. 哀悼', category: '托福词汇' },
  { word: 'mourner', phonetic: '/ˈmɔːnər/', meaning: 'n. 哀悼者', category: 'GRE词汇' },
  { word: 'mournful', phonetic: '/ˈmɔːnfl/', meaning: 'adj. 悲伤的', category: 'GRE词汇' },
  { word: 'mourning', phonetic: '/ˈmɔːnɪŋ/', meaning: 'n. 哀悼', category: '托福词汇' },
  { word: 'mouse', phonetic: '/maʊs/', meaning: 'n. 老鼠', category: '托福词汇' },
  { word: 'mouser', phonetic: '/ˈmaʊzər/', meaning: 'n. 捕鼠猫', category: 'GRE词汇' },
  { word: 'mousetrap', phonetic: '/ˈmaʊstræp/', meaning: 'n. 捕鼠器', category: 'GRE词汇' },
  { word: 'moustache', phonetic: '/məˈstɑːʃ/', meaning: 'n. 胡子', category: '托福词汇' },
  { word: 'mout', phonetic: '/muː/', meaning: 'v. 哞哞叫', category: 'GRE词汇' },
  { word: 'mouth', phonetic: '/maʊθ/', meaning: 'n. 嘴', category: '托福词汇' },
  { word: 'mouthful', phonetic: '/ˈmaʊθfl/', meaning: 'n. 一口', category: '托福词汇' },
  { word: 'mouthpiece', phonetic: '/ˈmaʊθpiːs/', meaning: 'n. 喉舌', category: 'GRE词汇' },
  { word: 'movable', phonetic: '/ˈmuːvəbl/', meaning: 'adj. 可移动的', category: '托福词汇' },
  { word: 'move', phonetic: '/muːv/', meaning: 'v. 移动；n. 移动', category: '托福词汇' },
  { word: 'movement', phonetic: '/ˈmuːvmənt/', meaning: 'n. 运动', category: '托福词汇' },
  { word: 'mover', phonetic: '/ˈmuːvər/', meaning: 'n. 搬家公司', category: '托福词汇' },
  { word: 'movie', phonetic: '/ˈmuːvi/', meaning: 'n. 电影', category: '托福词汇' },
  { word: 'moving', phonetic: '/ˈmuːvɪŋ/', meaning: 'adj. 动人的；移动的', category: '托福词汇' },
  { word: 'mow', phonetic: '/məʊ/', meaning: 'v. 割草', category: 'GRE词汇' },
  { word: 'much', phonetic: '/mʌtʃ/', meaning: 'adj. 许多的；adv. 非常', category: '托福词汇' },
  { word: 'muck', phonetic: '/mʌk/', meaning: 'n. 粪肥；v. 弄脏', category: 'GRE词汇' },
  { word: 'mucker', phonetic: '/ˈmʌkər/', meaning: 'n. 挖泥工', category: 'GRE词汇' },
  { word: 'muckrake', phonetic: '/ˈmʌkreɪk/', meaning: 'v. 揭发丑闻', category: 'GRE词汇' },
  { word: 'mucky', phonetic: '/ˈmʌki/', meaning: 'adj. 肮脏的', category: 'GRE词汇' },
  { word: 'mucous', phonetic: '/ˈmjuːkəs/', meaning: 'adj. 黏液的', category: '医学词汇' },
  { word: 'mucus', phonetic: '/ˈmjuːkəs/', meaning: 'n. 黏液', category: '医学词汇' },
  { word: 'mud', phonetic: '/mʌd/', meaning: 'n. 泥', category: '托福词汇' },
  { word: 'muddle', phonetic: '/ˈmʌdl/', meaning: 'v. 混淆；n. 混乱', category: 'GRE词汇' },
  { word: 'muddy', phonetic: '/ˈmʌdi/', meaning: 'adj. 泥泞的', category: '托福词汇' },
  { word: 'muff', phonetic: '/mʌf/', meaning: 'n. 暖手筒；v. 搞砸', category: 'GRE词汇' },
  { word: 'muffin', phonetic: '/ˈmʌfɪn/', meaning: 'n. 松饼', category: '托福词汇' },
  { word: 'muffle', phonetic: '/ˈmʌfl/', meaning: 'v. 裹住；n. 围巾', category: 'GRE词汇' },
  { word: 'muffler', phonetic: '/ˈmʌflər/', meaning: 'n. 消声器', category: 'GRE词汇' },
  { word: 'mufti', phonetic: '/ˈmʌfti/', meaning: 'n. 便服', category: 'GRE词汇' },
  { word: 'mug', phonetic: '/mʌɡ/', meaning: 'n. 杯子；v. 抢劫', category: '托福词汇' },
  { word: 'muggy', phonetic: '/ˈmʌɡi/', meaning: 'adj. 闷热的', category: 'GRE词汇' },
  { word: 'mulatto', phonetic: '/mjuˈlætəʊ/', meaning: 'n. 混血儿', category: 'GRE词汇' },
  { word: 'mulch', phonetic: '/mʌltʃ/', meaning: 'n. 覆盖物；v. 覆盖', category: 'GRE词汇' },
  { word: 'mulct', phonetic: '/mʌlkt/', meaning: 'v. 罚款；n. 罚金', category: 'GRE词汇' },
  { word: 'mule', phonetic: '/mjuːl/', meaning: 'n. 骡子', category: '托福词汇' },
  { word: 'mulish', phonetic: '/ˈmjuːlɪʃ/', meaning: 'adj. 固执的', category: 'GRE词汇' },
  { word: 'multicultural', phonetic: '/ˌmʌltiˈkʌltʃərəl/', meaning: 'adj. 多元文化的', category: '托福词汇' },
  { word: 'multilateral', phonetic: '/ˌmʌltiˈlætərəl/', meaning: 'adj. 多边的', category: 'GRE词汇' },
  { word: 'multilingual', phonetic: '/ˌmʌltiˈlɪŋɡwəl/', meaning: 'adj. 多语言的', category: 'GRE词汇' },
  { word: 'multimeter', phonetic: '/ˈmʌltɪmiːtər/', meaning: 'n. 万用表', category: '科技词汇' },
  { word: 'multinational', phonetic: '/ˌmʌltiˈnæʃənl/', meaning: 'adj. 跨国的', category: '商务词汇' },
  { word: 'multiple', phonetic: '/ˈmʌltɪpl/', meaning: 'adj. 多重的', category: '托福词汇' },
  { word: 'multiplication', phonetic: '/ˌmʌltɪplɪˈkeɪʃn/', meaning: 'n. 乘法', category: '托福词汇' },
  { word: 'multiply', phonetic: '/ˈmʌltɪplaɪ/', meaning: 'v. 乘；繁殖', category: '托福词汇' },
  { word: 'multiplicity', phonetic: '/ˌmʌltɪˈplɪsəti/', meaning: 'n. 多样性', category: 'GRE词汇' },
  { word: 'multitude', phonetic: '/ˈmʌltɪtjuːd/', meaning: 'n. 大量', category: 'GRE词汇' },
  { word: 'mum', phonetic: '/mʌm/', meaning: 'n. 妈妈；adj. 沉默的', category: '托福词汇' },
  { word: 'mumble', phonetic: '/ˈmʌmbl/', meaning: 'v. 喃喃自语', category: 'GRE词汇' },
  { word: 'mummer', phonetic: '/ˈmʌmər/', meaning: 'n. 哑剧演员', category: 'GRE词汇' },
  { word: 'mummify', phonetic: '/ˈmʌmɪfaɪ/', meaning: 'v. 制成木乃伊', category: 'GRE词汇' },
  { word: 'mummy', phonetic: '/ˈmʌmi/', meaning: 'n. 木乃伊；妈妈', category: '托福词汇' },
  { word: 'munch', phonetic: '/mʌntʃ/', meaning: 'v. 大嚼', category: 'GRE词汇' },
  { word: 'mundane', phonetic: '/mʌnˈdeɪn/', meaning: 'adj. 世俗的', category: 'GRE词汇' },
  { word: 'municipal', phonetic: '/mjuːˈnɪsɪpl/', meaning: 'adj. 市政的', category: '托福词汇' },
  { word: 'municipality', phonetic: '/mjuːˌnɪsɪˈpæləti/', meaning: 'n. 市政当局', category: 'GRE词汇' },
  { word: 'munificence', phonetic: '/mjuːˈnɪfɪsns/', meaning: 'n. 慷慨', category: 'GRE词汇' },
  { word: 'munificent', phonetic: '/mjuːˈnɪfɪsnt/', meaning: 'adj. 慷慨的', category: 'GRE词汇' },
  { word: 'munitions', phonetic: '/mjuːˈnɪʃnz/', meaning: 'n. 军火', category: 'GRE词汇' },
  { word: 'mural', phonetic: '/ˈmjʊərəl/', meaning: 'n. 壁画', category: 'GRE词汇' },
  { word: 'murder', phonetic: '/ˈmɜːdər/', meaning: 'n. 谋杀；v. 谋杀', category: '托福词汇' },
  { word: 'murderer', phonetic: '/ˈmɜːdərər/', meaning: 'n. 凶手', category: '托福词汇' },
  { word: 'murderous', phonetic: '/ˈmɜːdərəs/', meaning: 'adj. 杀人的', category: 'GRE词汇' },
  { word: 'murk', phonetic: '/mɜːk/', meaning: 'n. 黑暗', category: 'GRE词汇' },
  { word: 'murky', phonetic: '/ˈmɜːki/', meaning: 'adj. 黑暗的', category: 'GRE词汇' },
  { word: 'murmur', phonetic: '/ˈmɜːmər/', meaning: 'v. 低语；n. 低语声', category: 'GRE词汇' },
  { word: 'murphy', phonetic: '/ˈmɜːfi/', meaning: 'n. 马铃薯', category: 'GRE词汇' },
  { word: 'muscle', phonetic: '/ˈmʌsl/', meaning: 'n. 肌肉', category: '托福词汇' },
  { word: 'muscular', phonetic: '/ˈmʌskjələr/', meaning: 'adj. 肌肉发达的', category: '托福词汇' },
  { word: 'muse', phonetic: '/mjuːz/', meaning: 'v. 沉思；n. 缪斯', category: 'GRE词汇' },
  { word: 'museum', phonetic: '/mjuˈziːəm/', meaning: 'n. 博物馆', category: '托福词汇' },
  { word: 'mush', phonetic: '/mʌʃ/', meaning: 'n. 软糊；v. 压碎', category: 'GRE词汇' },
  { word: 'mushroom', phonetic: '/ˈmʌʃrʊm/', meaning: 'n. 蘑菇', category: '托福词汇' },
  { word: 'mushy', phonetic: '/ˈmʌʃi/', meaning: 'adj. 糊状的', category: 'GRE词汇' },
  { word: 'music', phonetic: '/ˈmjuːzɪk/', meaning: 'n. 音乐', category: '托福词汇' },
  { word: 'musical', phonetic: '/ˈmjuːzɪkl/', meaning: 'adj. 音乐的；n. 音乐剧', category: '托福词汇' },
  { word: 'musician', phonetic: '/mjuˈzɪʃn/', meaning: 'n. 音乐家', category: '托福词汇' },
  { word: 'musk', phonetic: '/mʌsk/', meaning: 'n. 麝香', category: 'GRE词汇' },
  { word: 'musket', phonetic: '/ˈmʌskɪt/', meaning: 'n. 火枪', category: 'GRE词汇' },
  { word: 'muskrat', phonetic: '/ˈmʌskræt/', meaning: 'n. 麝鼠', category: 'GRE词汇' },
  { word: 'musky', phonetic: '/ˈmʌski/', meaning: 'adj. 麝香的', category: 'GRE词汇' },
  { word: 'muslin', phonetic: '/ˈmʌzlɪn/', meaning: 'n. 平纹细布', category: 'GRE词汇' },
  { word: 'muss', phonetic: '/mʌs/', meaning: 'v. 弄乱', category: 'GRE词汇' },
  { word: 'mussel', phonetic: '/ˈmʌsl/', meaning: 'n. 贻贝', category: 'GRE词汇' },
  { word: 'must', phonetic: '/mʌst/', meaning: 'aux. 必须；n. 必须做的事', category: '托福词汇' },
  { word: 'mustache', phonetic: '/məˈstɑːʃ/', meaning: 'n. 髭', category: '托福词汇' },
  { word: 'mustard', phonetic: '/ˈmʌstəd/', meaning: 'n. 芥末', category: '托福词汇' },
  { word: 'muster', phonetic: '/ˈmʌstər/', meaning: 'v. 集合；n. 集合', category: 'GRE词汇' },
  { word: 'musty', phonetic: '/ˈmʌsti/', meaning: 'adj. 发霉的', category: 'GRE词汇' },
  { word: 'mutable', phonetic: '/ˈmjuːtəbl/', meaning: 'adj. 易变的', category: 'GRE词汇' },
  { word: 'mutant', phonetic: '/ˈmjuːtənt/', meaning: 'n. 突变体', category: '科技词汇' },
  { word: 'mutate', phonetic: '/mjuːˈteɪt/', meaning: 'v. 变异', category: '科技词汇' },
  { word: 'mutation', phonetic: '/mjuːˈteɪʃn/', meaning: 'n. 突变', category: '科技词汇' },
  { word: 'mute', phonetic: '/mjuːt/', meaning: 'adj. 哑的；v. 静音', category: '托福词汇' },
  { word: 'mutilate', phonetic: '/ˈmjuːtɪleɪt/', meaning: 'v. 使残缺', category: 'GRE词汇' },
  { word: 'mutilation', phonetic: '/ˌmjuːtɪˈleɪʃn/', meaning: 'n. 残缺', category: 'GRE词汇' },
  { word: 'mutiny', phonetic: '/ˈmjuːtəni/', meaning: 'n. 叛变；v. 叛变', category: 'GRE词汇' },
  { word: 'mutt', phonetic: '/mʌt/', meaning: 'n. 杂种狗', category: 'GRE词汇' },
  { word: 'mutter', phonetic: '/ˈmʌtər/', meaning: 'v. 嘟囔', category: 'GRE词汇' },
  { word: 'mutton', phonetic: '/ˈmʌtn/', meaning: 'n. 羊肉', category: '托福词汇' },
  { word: 'mutual', phonetic: '/ˈmjuːtʃuəl/', meaning: 'adj. 相互的', category: '托福词汇' },
  { word: 'mutually', phonetic: '/ˈmjuːtʃuəli/', meaning: 'adv. 相互地', category: '托福词汇' },
  { word: 'muzzle', phonetic: '/ˈmʌzl/', meaning: 'n. 枪口；v. 戴口罩', category: 'GRE词汇' },
  { word: 'my', phonetic: '/maɪ/', meaning: 'pron. 我的', category: '托福词汇' },
  { word: 'myriad', phonetic: '/ˈmɪriəd/', meaning: 'adj. 无数的；n. 无数', category: 'GRE词汇' },
  { word: 'myrrh', phonetic: '/mɜːr/', meaning: 'n. 没药', category: 'GRE词汇' },
  { word: 'myself', phonetic: '/maɪˈself/', meaning: 'pron. 我自己', category: '托福词汇' },
  { word: 'mysterious', phonetic: '/mɪˈstɪəriəs/', meaning: 'adj. 神秘的', category: '托福词汇' },
  { word: 'mystery', phonetic: '/ˈmɪstri/', meaning: 'n. 神秘', category: '托福词汇' },
  { word: 'mystic', phonetic: '/ˈmɪstɪk/', meaning: 'n. 神秘主义者；adj. 神秘的', category: 'GRE词汇' },
  { word: 'mystical', phonetic: '/ˈmɪstɪkl/', meaning: 'adj. 神秘的', category: 'GRE词汇' },
  { word: 'mystify', phonetic: '/ˈmɪstɪfaɪ/', meaning: 'v. 使困惑', category: 'GRE词汇' },
  { word: 'mystique', phonetic: '/mɪˈstiːk/', meaning: 'n. 神秘感', category: 'GRE词汇' },
  { word: 'myth', phonetic: '/mɪθ/', meaning: 'n. 神话', category: '托福词汇' },
  { word: 'mythical', phonetic: '/ˈmɪθɪkl/', meaning: 'adj. 神话的', category: 'GRE词汇' },
  { word: 'mythology', phonetic: '/mɪˈθɒlədʒi/', meaning: 'n. 神话学', category: 'GRE词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await fetchAllFromSupabase(
    supabase.from(WORDS_TABLE).select('word')
  );
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsM, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 M 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsM.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsM, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
