// G-H字母开头的单词
import { getSupabaseClient } from '../src/storage/database/supabase-client';
import { fetchAllFromSupabase } from '../src/lib/supabase-fetch-all';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsGHI = [
  // G字母开头
  { word: 'gadget', phonetic: '/ˈɡædʒɪt/', meaning: 'n. 小器具；小玩意', category: '托福词汇' },
  { word: 'gaffe', phonetic: '/ɡæf/', meaning: 'n. 失礼；失态', category: 'GRE词汇' },
  { word: 'gain', phonetic: '/ɡeɪn/', meaning: 'v. 获得；n. 收益', category: '托福词汇' },
  { word: 'gainful', phonetic: '/ˈɡeɪnfl/', meaning: 'adj. 有利的；赚钱的', category: 'GRE词汇' },
  { word: 'gala', phonetic: '/ˈɡɑːlə/', meaning: 'n. 盛会；庆典', category: 'GRE词汇' },
  { word: 'galaxy', phonetic: '/ˈɡæləksi/', meaning: 'n. 银河；星系', category: '托福词汇' },
  { word: 'gale', phonetic: '/ɡeɪl/', meaning: 'n. 大风', category: '托福词汇' },
  { word: 'gallop', phonetic: '/ˈɡæləp/', meaning: 'v. 飞跑；n. 飞跑', category: 'GRE词汇' },
  { word: 'gall', phonetic: '/ɡɔːl/', meaning: 'n. 胆汁；怨恨；v. 使烦恼', category: 'GRE词汇' },
  { word: 'gallows', phonetic: '/ˈɡæləʊz/', meaning: 'n. 绞刑架', category: 'GRE词汇' },
  { word: 'gallant', phonetic: '/ˈɡælənt/', meaning: 'adj. 英勇的；殷勤的', category: 'GRE词汇' },
  { word: 'galvanize', phonetic: '/ˈɡælvənaɪz/', meaning: 'v. 刺激；电镀', category: 'GRE词汇' },
  { word: 'gamble', phonetic: '/ˈɡæmbl/', meaning: 'v. 赌博；n. 赌博', category: '托福词汇' },
  { word: 'gambler', phonetic: '/ˈɡæmblər/', meaning: 'n. 赌徒', category: '托福词汇' },
  { word: 'game', phonetic: '/ɡeɪm/', meaning: 'n. 游戏；比赛', category: '托福词汇' },
  { word: 'gamut', phonetic: '/ˈɡæmət/', meaning: 'n. 全范围；全音阶', category: 'GRE词汇' },
  { word: 'gang', phonetic: '/ɡæŋ/', meaning: 'n. 帮派；v. 结伙', category: '托福词汇' },
  { word: 'gangster', phonetic: '/ˈɡæŋstər/', meaning: 'n. 歹徒', category: '托福词汇' },
  { word: 'gap', phonetic: '/ɡæp/', meaning: 'n. 缺口；差距', category: '托福词汇' },
  { word: 'gape', phonetic: '/ɡeɪp/', meaning: 'v. 张口结舌；目瞪口呆', category: 'GRE词汇' },
  { word: 'garage', phonetic: '/ˈɡærɑːʒ/', meaning: 'n. 车库', category: '托福词汇' },
  { word: 'garble', phonetic: '/ˈɡɑːbl/', meaning: 'v. 曲解；混淆', category: 'GRE词汇' },
  { word: 'garden', phonetic: '/ˈɡɑːdn/', meaning: 'n. 花园', category: '托福词汇' },
  { word: 'gardener', phonetic: '/ˈɡɑːdnər/', meaning: 'n. 园丁', category: '托福词汇' },
  { word: 'garish', phonetic: '/ˈɡeərɪʃ/', meaning: 'adj. 俗艳的；过分装饰的', category: 'GRE词汇' },
  { word: 'garland', phonetic: '/ˈɡɑːlənd/', meaning: 'n. 花环', category: 'GRE词汇' },
  { word: 'garment', phonetic: '/ˈɡɑːmənt/', meaning: 'n. 服装', category: '托福词汇' },
  { word: 'garnish', phonetic: '/ˈɡɑːnɪʃ/', meaning: 'v. 装饰；n. 装饰品', category: 'GRE词汇' },
  { word: 'garrison', phonetic: '/ˈɡærɪsn/', meaning: 'n. 驻军；v. 驻守', category: 'GRE词汇' },
  { word: 'garrote', phonetic: '/ɡəˈrɒt/', meaning: 'n. 绞刑具；v. 绞死', category: 'GRE词汇' },
  { word: 'garrulous', phonetic: '/ˈɡærələs/', meaning: 'adj. 话多的', category: 'GRE词汇' },
  { word: 'gash', phonetic: '/ɡæʃ/', meaning: 'n. 深切口；v. 划开', category: 'GRE词汇' },
  { word: 'gasoline', phonetic: '/ˈɡæsəliːn/', meaning: 'n. 汽油', category: '托福词汇' },
  { word: 'gasp', phonetic: '/ɡɑːsp/', meaning: 'v. 喘气；n. 喘气', category: '托福词汇' },
  { word: 'gastric', phonetic: '/ˈɡæstrɪk/', meaning: 'adj. 胃的', category: '医学词汇' },
  { word: 'gastritis', phonetic: '/ɡæˈstraɪtɪs/', meaning: 'n. 胃炎', category: '医学词汇' },
  { word: 'gastronomy', phonetic: '/ɡæˈstrɒnəmi/', meaning: 'n. 美食学', category: 'GRE词汇' },
  { word: 'gate', phonetic: '/ɡeɪt/', meaning: 'n. 大门', category: '托福词汇' },
  { word: 'gatekeeper', phonetic: '/ˈɡeɪtkiːpər/', meaning: 'n. 看门人', category: '托福词汇' },
  { word: 'gather', phonetic: '/ˈɡæðər/', meaning: 'v. 收集；聚集', category: '托福词汇' },
  { word: 'gathering', phonetic: '/ˈɡæðərɪŋ/', meaning: 'n. 聚会；收集', category: '托福词汇' },
  { word: 'gauge', phonetic: '/ɡeɪdʒ/', meaning: 'n. 测量仪器；v. 测量', category: '托福词汇' },
  { word: 'gaunt', phonetic: '/ɡɔːnt/', meaning: 'adj. 憔悴的', category: 'GRE词汇' },
  { word: 'gauntlet', phonetic: '/ˈɡɔːntlɪt/', meaning: 'n. 长手套；挑战', category: 'GRE词汇' },
  { word: 'gauze', phonetic: '/ɡɔːz/', meaning: 'n. 纱布', category: '医学词汇' },
  { word: 'gavel', phonetic: '/ˈɡævl/', meaning: 'n. 法槌', category: '法律词汇' },
  { word: 'gawky', phonetic: '/ˈɡɔːki/', meaning: 'adj. 笨拙的', category: 'GRE词汇' },
  { word: 'gay', phonetic: '/ɡeɪ/', meaning: 'adj. 快乐的；同性恋的', category: '托福词汇' },
  { word: 'gaze', phonetic: '/ɡeɪz/', meaning: 'v. 凝视；n. 凝视', category: '托福词汇' },
  { word: 'gazette', phonetic: '/ɡəˈzet/', meaning: 'n. 公报；报纸', category: 'GRE词汇' },
  { word: 'gear', phonetic: '/ɡɪər/', meaning: 'n. 齿轮；装备', category: '托福词汇' },
  { word: 'geek', phonetic: '/ɡiːk/', meaning: 'n. 极客；怪人', category: '托福词汇' },
  { word: 'gem', phonetic: '/dʒem/', meaning: 'n. 宝石', category: '托福词汇' },
  { word: 'gender', phonetic: '/ˈdʒendər/', meaning: 'n. 性别', category: '托福词汇' },
  { word: 'gene', phonetic: '/dʒiːn/', meaning: 'n. 基因', category: '科技词汇' },
  { word: 'genealogy', phonetic: '/ˌdʒiːniˈælədʒi/', meaning: 'n. 家谱学', category: 'GRE词汇' },
  { word: 'generality', phonetic: '/ˌdʒenəˈræləti/', meaning: 'n. 概论；一般性', category: 'GRE词汇' },
  { word: 'generalization', phonetic: '/ˌdʒenrəlaɪˈzeɪʃn/', meaning: 'n. 概括', category: '托福词汇' },
  { word: 'generalize', phonetic: '/ˈdʒenrəlaɪz/', meaning: 'v. 概括；推广', category: '托福词汇' },
  { word: 'generally', phonetic: '/ˈdʒenrəli/', meaning: 'adv. 通常；一般地', category: '托福词汇' },
  { word: 'generate', phonetic: '/ˈdʒenəreɪt/', meaning: 'v. 产生；生成', category: '托福词汇' },
  { word: 'generation', phonetic: '/ˌdʒenəˈreɪʃn/', meaning: 'n. 一代；产生', category: '托福词汇' },
  { word: 'generative', phonetic: '/ˈdʒenərətɪv/', meaning: 'adj. 生成的；有生产力的', category: '科技词汇' },
  { word: 'generator', phonetic: '/ˈdʒenəreɪtər/', meaning: 'n. 发电机', category: '科技词汇' },
  { word: 'generic', phonetic: '/dʒəˈnerɪk/', meaning: 'adj. 一般的；通用的', category: '托福词汇' },
  { word: 'generous', phonetic: '/ˈdʒenərəs/', meaning: 'adj. 慷慨的', category: '托福词汇' },
  { word: 'generosity', phonetic: '/ˌdʒenəˈrɒsəti/', meaning: 'n. 慷慨', category: '托福词汇' },
  { word: 'genesis', phonetic: '/ˈdʒenəsɪs/', meaning: 'n. 起源', category: 'GRE词汇' },
  { word: 'genetic', phonetic: '/dʒəˈnetɪk/', meaning: 'adj. 遗传的', category: '科技词汇' },
  { word: 'geneticist', phonetic: '/dʒəˈnetɪsɪst/', meaning: 'n. 遗传学家', category: '科技词汇' },
  { word: 'genetics', phonetic: '/dʒəˈnetɪks/', meaning: 'n. 遗传学', category: '科技词汇' },
  { word: 'genial', phonetic: '/ˈdʒiːniəl/', meaning: 'adj. 亲切的；温暖的', category: 'GRE词汇' },
  { word: 'genius', phonetic: '/ˈdʒiːniəs/', meaning: 'n. 天才', category: '托福词汇' },
  { word: 'genre', phonetic: '/ˈʒɒnrə/', meaning: 'n. 类型；流派', category: '托福词汇' },
  { word: 'gentile', phonetic: '/ˈdʒentaɪl/', meaning: 'n. 非犹太人；adj. 非犹太人的', category: 'GRE词汇' },
  { word: 'gentle', phonetic: '/ˈdʒentl/', meaning: 'adj. 温和的', category: '托福词汇' },
  { word: 'gentleman', phonetic: '/ˈdʒentlmən/', meaning: 'n. 绅士', category: '托福词汇' },
  { word: 'gently', phonetic: '/ˈdʒentli/', meaning: 'adv. 温和地', category: '托福词汇' },
  { word: 'gentry', phonetic: '/ˈdʒentri/', meaning: 'n. 绅士阶层', category: 'GRE词汇' },
  { word: 'genuflect', phonetic: '/ˈdʒenjʊflekt/', meaning: 'v. 屈膝；跪拜', category: 'GRE词汇' },
  { word: 'genuine', phonetic: '/ˈdʒenjuɪn/', meaning: 'adj. 真正的', category: '托福词汇' },
  { word: 'genus', phonetic: '/ˈdʒiːnəs/', meaning: 'n. 属；种类', category: '科技词汇' },
  { word: 'geographer', phonetic: '/dʒiˈɒɡrəfər/', meaning: 'n. 地理学家', category: '托福词汇' },
  { word: 'geography', phonetic: '/dʒiˈɒɡrəfi/', meaning: 'n. 地理学', category: '托福词汇' },
  { word: 'geological', phonetic: '/ˌdʒiːəˈlɒdʒɪkl/', meaning: 'adj. 地质的', category: '科技词汇' },
  { word: 'geologist', phonetic: '/dʒiˈɒlədʒɪst/', meaning: 'n. 地质学家', category: '科技词汇' },
  { word: 'geology', phonetic: '/dʒiˈɒlədʒi/', meaning: 'n. 地质学', category: '科技词汇' },
  { word: 'geometry', phonetic: '/dʒiˈɒmətri/', meaning: 'n. 几何学', category: '科技词汇' },
  { word: 'geopolitics', phonetic: '/ˌdʒiːəʊˈpɒlətɪks/', meaning: 'n. 地缘政治学', category: 'GRE词汇' },
  { word: 'germinate', phonetic: '/ˈdʒɜːmɪneɪt/', meaning: 'v. 发芽；萌芽', category: 'GRE词汇' },
  { word: 'germ', phonetic: '/dʒɜːm/', meaning: 'n. 细菌；胚芽', category: '托福词汇' },
  { word: 'germane', phonetic: '/dʒɜːˈmeɪn/', meaning: 'adj. 相关的；贴切的', category: 'GRE词汇' },
  { word: 'geriatric', phonetic: '/ˌdʒeriˈætrɪk/', meaning: 'adj. 老年的；老年医学的', category: '医学词汇' },
  { word: 'germinal', phonetic: '/ˈdʒɜːmɪnl/', meaning: 'adj. 萌芽的；原始的', category: 'GRE词汇' },
  { word: 'germinate', phonetic: '/ˈdʒɜːmɪneɪt/', meaning: 'v. 发芽；发展', category: '科技词汇' },
  { word: 'gestation', phonetic: '/dʒeˈsteɪʃn/', meaning: 'n. 怀孕；酝酿', category: '医学词汇' },
  { word: 'gesture', phonetic: '/ˈdʒestʃər/', meaning: 'n. 手势；v. 做手势', category: '托福词汇' },
  { word: 'get', phonetic: '/ɡet/', meaning: 'v. 获得；变成', category: '托福词汇' },
  { word: 'getaway', phonetic: '/ˈɡetəweɪ/', meaning: 'n. 逃走；度假地', category: '托福词汇' },
  { word: 'geyser', phonetic: '/ˈɡaɪzər/', meaning: 'n. 间歇泉', category: 'GRE词汇' },
  { word: 'ghastly', phonetic: '/ˈɡɑːstli/', meaning: 'adj. 可怕的；恐怖的', category: 'GRE词汇' },
  { word: 'ghost', phonetic: '/ɡəʊst/', meaning: 'n. 鬼魂', category: '托福词汇' },
  { word: 'ghostly', phonetic: '/ˈɡəʊstli/', meaning: 'adj. 幽灵般的', category: 'GRE词汇' },
  { word: 'giant', phonetic: '/ˈdʒaɪənt/', meaning: 'n. 巨人；adj. 巨大的', category: '托福词汇' },
  { word: 'gibberish', phonetic: '/ˈdʒɪbərɪʃ/', meaning: 'n. 胡言乱语', category: 'GRE词汇' },
  { word: 'gibe', phonetic: '/dʒaɪb/', meaning: 'v. 嘲笑；n. 嘲笑', category: 'GRE词汇' },
  { word: 'gift', phonetic: '/ɡɪft/', meaning: 'n. 礼物；天赋', category: '托福词汇' },
  { word: 'gifted', phonetic: '/ˈɡɪftɪd/', meaning: 'adj. 有天赋的', category: '托福词汇' },
  { word: 'gigantic', phonetic: '/dʒaɪˈɡæntɪk/', meaning: 'adj. 巨大的', category: '托福词汇' },
  { word: 'giggle', phonetic: '/ˈɡɪɡl/', meaning: 'v. 咯咯笑；n. 咯咯笑', category: '托福词汇' },
  { word: 'gild', phonetic: '/ɡɪld/', meaning: 'v. 镀金；装饰', category: 'GRE词汇' },
  { word: 'gilded', phonetic: '/ˈɡɪldɪd/', meaning: 'adj. 镀金的；富有的', category: 'GRE词汇' },
  { word: 'gill', phonetic: '/ɡɪl/', meaning: 'n. 鳃', category: '托福词汇' },
  { word: 'gilting', phonetic: '/ˈɡɪltɪŋ/', meaning: 'n. 镀金', category: 'GRE词汇' },
  { word: 'ginger', phonetic: '/ˈdʒɪndʒər/', meaning: 'n. 生姜；adj. 姜黄色的', category: '托福词汇' },
  { word: 'gingerly', phonetic: '/ˈdʒɪndʒəli/', meaning: 'adv. 小心翼翼地', category: 'GRE词汇' },
  { word: 'girder', phonetic: '/ˈɡɜːdər/', meaning: 'n. 大梁', category: '科技词汇' },
  { word: 'girdle', phonetic: '/ˈɡɜːdl/', meaning: 'n. 腰带；v. 围绕', category: 'GRE词汇' },
  { word: 'girl', phonetic: '/ɡɜːl/', meaning: 'n. 女孩', category: '托福词汇' },
  { word: 'girth', phonetic: '/ɡɜːθ/', meaning: 'n. 围长；v. 围绕', category: 'GRE词汇' },
  { word: 'gist', phonetic: '/dʒɪst/', meaning: 'n. 要点；主旨', category: 'GRE词汇' },
  { word: 'give', phonetic: '/ɡɪv/', meaning: 'v. 给予', category: '托福词汇' },
  { word: 'giveaway', phonetic: '/ˈɡɪvəweɪ/', meaning: 'n. 赠品；泄密', category: '托福词汇' },
  { word: 'given', phonetic: '/ˈɡɪvn/', meaning: 'adj. 特定的；prep. 考虑到', category: '托福词汇' },
  { word: 'glacial', phonetic: '/ˈɡleɪʃl/', meaning: 'adj. 冰川的；极冷的', category: '托福词汇' },
  { word: 'glacier', phonetic: '/ˈɡlæsiər/', meaning: 'n. 冰川', category: '托福词汇' },
  { word: 'glad', phonetic: '/ɡlæd/', meaning: 'adj. 高兴的', category: '托福词汇' },
  { word: 'gladden', phonetic: '/ˈɡlædn/', meaning: 'v. 使高兴', category: 'GRE词汇' },
  { word: 'glamour', phonetic: '/ˈɡlæmər/', meaning: 'n. 魅力', category: '托福词汇' },
  { word: 'glamorous', phonetic: '/ˈɡlæmərəs/', meaning: 'adj. 有魅力的', category: '托福词汇' },
  { word: 'glance', phonetic: '/ɡlɑːns/', meaning: 'v. 一瞥；n. 一瞥', category: '托福词汇' },
  { word: 'gland', phonetic: '/ɡlænd/', meaning: 'n. 腺体', category: '医学词汇' },
  { word: 'glare', phonetic: '/ɡleər/', meaning: 'v. 怒视；n. 强光', category: '托福词汇' },
  { word: 'glass', phonetic: '/ɡlɑːs/', meaning: 'n. 玻璃；杯子', category: '托福词汇' },
  { word: 'glassy', phonetic: '/ˈɡlɑːsi/', meaning: 'adj. 像玻璃的；呆滞的', category: 'GRE词汇' },
  { word: 'glaze', phonetic: '/ɡleɪz/', meaning: 'v. 上釉；n. 釉', category: 'GRE词汇' },
  { word: 'glazing', phonetic: '/ˈɡleɪzɪŋ/', meaning: 'n. 上釉；玻璃', category: 'GRE词汇' },
  { word: 'gleam', phonetic: '/ɡliːm/', meaning: 'n. 微光；v. 闪烁', category: 'GRE词汇' },
  { word: 'glean', phonetic: '/ɡliːn/', meaning: 'v. 拾穗；收集', category: 'GRE词汇' },
  { word: 'glee', phonetic: '/ɡliː/', meaning: 'n. 欢乐', category: 'GRE词汇' },
  { word: 'glib', phonetic: '/ɡlɪb/', meaning: 'adj. 油嘴滑舌的', category: 'GRE词汇' },
  { word: 'glide', phonetic: '/ɡlaɪd/', meaning: 'v. 滑行；n. 滑行', category: '托福词汇' },
  { word: 'glider', phonetic: '/ˈɡlaɪdər/', meaning: 'n. 滑翔机', category: '科技词汇' },
  { word: 'gliding', phonetic: '/ˈɡlaɪdɪŋ/', meaning: 'n. 滑翔；adj. 滑行的', category: '托福词汇' },
  { word: 'glimmer', phonetic: '/ˈɡlɪmər/', meaning: 'v. 发微光；n. 微光', category: 'GRE词汇' },
  { word: 'glimpse', phonetic: '/ɡlɪmps/', meaning: 'n. 一瞥；v. 瞥见', category: '托福词汇' },
  { word: 'glint', phonetic: '/ɡlɪnt/', meaning: 'n. 闪烁；v. 闪烁', category: 'GRE词汇' },
  { word: 'glisten', phonetic: '/ˈɡlɪsn/', meaning: 'v. 闪耀', category: 'GRE词汇' },
  { word: 'glitter', phonetic: '/ˈɡlɪtər/', meaning: 'v. 闪烁；n. 光辉', category: '托福词汇' },
  { word: 'glitzy', phonetic: '/ˈɡlɪtsi/', meaning: 'adj. 浮华的', category: 'GRE词汇' },
  { word: 'gloat', phonetic: '/ɡləʊt/', meaning: 'v. 幸灾乐祸', category: 'GRE词汇' },
  { word: 'global', phonetic: '/ˈɡləʊbl/', meaning: 'adj. 全球的', category: '托福词汇' },
  { word: 'globalization', phonetic: '/ˌɡləʊbəlaɪˈzeɪʃn/', meaning: 'n. 全球化', category: '托福词汇' },
  { word: 'globalize', phonetic: '/ˈɡləʊbəlaɪz/', meaning: 'v. 使全球化', category: '托福词汇' },
  { word: 'globe', phonetic: '/ɡləʊb/', meaning: 'n. 地球；地球仪', category: '托福词汇' },
  { word: 'globular', phonetic: '/ˈɡlɒbjələr/', meaning: 'adj. 球状的', category: '科技词汇' },
  { word: 'gloom', phonetic: '/ɡluːm/', meaning: 'n. 阴暗；忧郁', category: '托福词汇' },
  { word: 'gloomy', phonetic: '/ˈɡluːmi/', meaning: 'adj. 阴暗的；沮丧的', category: '托福词汇' },
  { word: 'glorify', phonetic: '/ˈɡlɔːrɪfaɪ/', meaning: 'v. 赞美；美化', category: 'GRE词汇' },
  { word: 'glorious', phonetic: '/ˈɡlɔːriəs/', meaning: 'adj. 光荣的；壮丽的', category: '托福词汇' },
  { word: 'glory', phonetic: '/ˈɡlɔːri/', meaning: 'n. 光荣；荣誉', category: '托福词汇' },
  { word: 'gloss', phonetic: '/ɡlɒs/', meaning: 'n. 光泽；注释；v. 掩盖', category: 'GRE词汇' },
  { word: 'glossary', phonetic: '/ˈɡlɒsəri/', meaning: 'n. 词汇表', category: '托福词汇' },
  { word: 'glossy', phonetic: '/ˈɡlɒsi/', meaning: 'adj. 光滑的；有光泽的', category: '托福词汇' },
  { word: 'glow', phonetic: '/ɡləʊ/', meaning: 'v. 发光；n. 光辉', category: '托福词汇' },
  { word: 'glowing', phonetic: '/ˈɡləʊɪŋ/', meaning: 'adj. 发光的；热情洋溢的', category: '托福词汇' },
  { word: 'glucose', phonetic: '/ˈɡluːkəʊs/', meaning: 'n. 葡萄糖', category: '医学词汇' },
  { word: 'glue', phonetic: '/ɡluː/', meaning: 'n. 胶水；v. 粘贴', category: '托福词汇' },
  { word: 'glum', phonetic: '/ɡlʌm/', meaning: 'adj. 阴郁的', category: 'GRE词汇' },
  { word: 'glut', phonetic: '/ɡlʌt/', meaning: 'v. 使过剩；n. 过剩', category: 'GRE词汇' },
  { word: 'glutton', phonetic: '/ˈɡlʌtn/', meaning: 'n. 贪吃的人', category: 'GRE词汇' },
  { word: 'gluttonous', phonetic: '/ˈɡlʌtənəs/', meaning: 'adj. 贪吃的', category: 'GRE词汇' },
  { word: 'gnaw', phonetic: '/nɔː/', meaning: 'v. 咬；折磨', category: 'GRE词汇' },
  { word: 'gnome', phonetic: '/nəʊm/', meaning: 'n. 地精；格言', category: 'GRE词汇' },
  { word: 'goal', phonetic: '/ɡəʊl/', meaning: 'n. 目标；进球', category: '托福词汇' },
  { word: 'goalkeeper', phonetic: '/ˈɡəʊlkiːpər/', meaning: 'n. 守门员', category: '托福词汇' },
  { word: 'gob', phonetic: '/ɡɒb/', meaning: 'n. 一团；大量', category: 'GRE词汇' },
  { word: 'gobble', phonetic: '/ˈɡɒbl/', meaning: 'v. 狼吞虎咽', category: 'GRE词汇' },
  { word: 'goblet', phonetic: '/ˈɡɒblət/', meaning: 'n. 高脚杯', category: 'GRE词汇' },
  { word: 'god', phonetic: '/ɡɒd/', meaning: 'n. 神', category: '托福词汇' },
  { word: 'godlike', phonetic: '/ˈɡɒdlaɪk/', meaning: 'adj. 神一般的', category: 'GRE词汇' },
  { word: 'godsend', phonetic: '/ˈɡɒdsend/', meaning: 'n. 天赐之物', category: 'GRE词汇' },
  { word: 'goggles', phonetic: '/ˈɡɒɡlz/', meaning: 'n. 护目镜', category: '托福词汇' },
  { word: 'gold', phonetic: '/ɡəʊld/', meaning: 'n. 黄金；adj. 金色的', category: '托福词汇' },
  { word: 'golden', phonetic: '/ˈɡəʊldən/', meaning: 'adj. 金色的；珍贵的', category: '托福词汇' },
  { word: 'goldsmith', phonetic: '/ˈɡəʊldsmɪθ/', meaning: 'n. 金匠', category: 'GRE词汇' },
  { word: 'golf', phonetic: '/ɡɒlf/', meaning: 'n. 高尔夫球', category: '托福词汇' },
  { word: 'golfer', phonetic: '/ˈɡɒlfər/', meaning: 'n. 高尔夫球手', category: '托福词汇' },
  { word: 'gondola', phonetic: '/ˈɡɒndələ/', meaning: 'n. 贡多拉；缆车', category: 'GRE词汇' },
  { word: 'gone', phonetic: '/ɡɒn/', meaning: 'adj. 离去的；过去的', category: '托福词汇' },
  { word: 'gong', phonetic: '/ɡɒŋ/', meaning: 'n. 锣', category: 'GRE词汇' },
  { word: 'good', phonetic: '/ɡʊd/', meaning: 'adj. 好的；n. 好处', category: '托福词汇' },
  { word: 'goodness', phonetic: '/ˈɡʊdnəs/', meaning: 'n. 善良；美德', category: '托福词汇' },
  { word: 'goodwill', phonetic: '/ˌɡʊdˈwɪl/', meaning: 'n. 善意；信誉', category: '商务词汇' },
  { word: 'gooey', phonetic: '/ˈɡuːi/', meaning: 'adj. 胶粘的；感伤的', category: 'GRE词汇' },
  { word: 'goof', phonetic: '/ɡuːf/', meaning: 'n. 傻瓜；v. 混日子', category: 'GRE词汇' },
  { word: 'goofy', phonetic: '/ˈɡuːfi/', meaning: 'adj. 愚蠢的', category: 'GRE词汇' },
  { word: 'goon', phonetic: '/ɡuːn/', meaning: 'n. 暴徒；傻瓜', category: 'GRE词汇' },
  { word: 'goo', phonetic: '/ɡuː/', meaning: 'n. 粘性物', category: 'GRE词汇' },
  { word: 'goose', phonetic: '/ɡuːs/', meaning: 'n. 鹅', category: '托福词汇' },
  { word: 'gore', phonetic: '/ɡɔːr/', meaning: 'n. 血块；v. 用角顶伤', category: 'GRE词汇' },
  { word: 'gorge', phonetic: '/ɡɔːdʒ/', meaning: 'n. 峡谷；v. 狼吞虎咽', category: 'GRE词汇' },
  { word: 'gorgeous', phonetic: '/ˈɡɔːdʒəs/', meaning: 'adj. 华丽的；极好的', category: '托福词汇' },
  { word: 'gorilla', phonetic: '/ɡəˈrɪlə/', meaning: 'n. 大猩猩', category: '托福词汇' },
  { word: 'gospel', phonetic: '/ˈɡɒspl/', meaning: 'n. 福音；真理', category: 'GRE词汇' },
  { word: 'gossip', phonetic: '/ˈɡɒsɪp/', meaning: 'n. 闲话；v. 说闲话', category: '托福词汇' },
  { word: 'got', phonetic: '/ɡɒt/', meaning: 'v. get的过去式', category: '托福词汇' },
  { word: 'gouge', phonetic: '/ɡaʊdʒ/', meaning: 'v. 凿；n. 凿子', category: 'GRE词汇' },
  { word: 'gourd', phonetic: '/ɡʊəd/', meaning: 'n. 葫芦', category: 'GRE词汇' },
  { word: 'govern', phonetic: '/ˈɡʌvn/', meaning: 'v. 统治；管理', category: '托福词汇' },
  { word: 'governance', phonetic: '/ˈɡʌvənəns/', meaning: 'n. 治理；管理', category: '商务词汇' },
  { word: 'government', phonetic: '/ˈɡʌvənmənt/', meaning: 'n. 政府', category: '托福词汇' },
  { word: 'governor', phonetic: '/ˈɡʌvənər/', meaning: 'n. 州长；主管', category: '托福词汇' },
  { word: 'gown', phonetic: '/ɡaʊn/', meaning: 'n. 长袍；礼服', category: '托福词汇' },
  { word: 'grab', phonetic: '/ɡræb/', meaning: 'v. 抓取；n. 抓取', category: '托福词汇' },
  { word: 'grace', phonetic: '/ɡreɪs/', meaning: 'n. 优雅；恩典', category: '托福词汇' },
  { word: 'graceful', phonetic: '/ˈɡreɪsfl/', meaning: 'adj. 优雅的', category: '托福词汇' },
  { word: 'gracious', phonetic: '/ˈɡreɪʃəs/', meaning: 'adj. 亲切的；优雅的', category: '托福词汇' },
  { word: 'gradation', phonetic: '/ɡrəˈdeɪʃn/', meaning: 'n. 等级；渐变', category: 'GRE词汇' },
  { word: 'grade', phonetic: '/ɡreɪd/', meaning: 'n. 等级；v. 分级', category: '托福词汇' },
  { word: 'gradient', phonetic: '/ˈɡreɪdiənt/', meaning: 'n. 梯度；斜率', category: '科技词汇' },
  { word: 'gradual', phonetic: '/ˈɡrædʒuəl/', meaning: 'adj. 逐渐的', category: '托福词汇' },
  { word: 'gradually', phonetic: '/ˈɡrædʒuəli/', meaning: 'adv. 逐渐地', category: '托福词汇' },
  { word: 'graduate', phonetic: '/ˈɡrædʒuət/', meaning: 'n. 毕业生；v. 毕业', category: '托福词汇' },
  { word: 'graffiti', phonetic: '/ɡrəˈfiːti/', meaning: 'n. 涂鸦', category: '托福词汇' },
  { word: 'graft', phonetic: '/ɡrɑːft/', meaning: 'n. 嫁接；贪污；v. 嫁接', category: 'GRE词汇' },
  { word: 'grain', phonetic: '/ɡreɪn/', meaning: 'n. 谷物；颗粒', category: '托福词汇' },
  { word: 'grainy', phonetic: '/ˈɡreɪni/', meaning: 'adj. 有颗粒的', category: 'GRE词汇' },
  { word: 'gram', phonetic: '/ɡræm/', meaning: 'n. 克', category: '托福词汇' },
  { word: 'grammar', phonetic: '/ˈɡræmər/', meaning: 'n. 语法', category: '托福词汇' },
  { word: 'grammarian', phonetic: '/ɡrəˈmeəriən/', meaning: 'n. 语法学家', category: 'GRE词汇' },
  { word: 'grammatical', phonetic: '/ɡrəˈmætɪkl/', meaning: 'adj. 语法的', category: '托福词汇' },
  { word: 'granary', phonetic: '/ˈɡrænəri/', meaning: 'n. 粮仓', category: 'GRE词汇' },
  { word: 'grand', phonetic: '/ɡrænd/', meaning: 'adj. 宏伟的；重大的', category: '托福词汇' },
  { word: 'grandchild', phonetic: '/ˈɡræntʃaɪld/', meaning: 'n. 孙子/孙女', category: '托福词汇' },
  { word: 'grandeur', phonetic: '/ˈɡrændʒər/', meaning: 'n. 宏伟；壮丽', category: 'GRE词汇' },
  { word: 'grandfather', phonetic: '/ˈɡrænfɑːðər/', meaning: 'n. 祖父', category: '托福词汇' },
  { word: 'grandiose', phonetic: '/ˈɡrændiəʊs/', meaning: 'adj. 宏伟的；浮夸的', category: 'GRE词汇' },
  { word: 'grandmother', phonetic: '/ˈɡrænmʌðər/', meaning: 'n. 祖母', category: '托福词汇' },
  { word: 'grandparent', phonetic: '/ˈɡrænpeərənt/', meaning: 'n. 祖父母', category: '托福词汇' },
  { word: 'grant', phonetic: '/ɡrɑːnt/', meaning: 'v. 授予；n. 补助金', category: '托福词汇' },
  { word: 'granular', phonetic: '/ˈɡrænjələr/', meaning: 'adj. 颗粒状的', category: '科技词汇' },
  { word: 'granulate', phonetic: '/ˈɡrænjuleɪt/', meaning: 'v. 使成颗粒', category: '科技词汇' },
  { word: 'grape', phonetic: '/ɡreɪp/', meaning: 'n. 葡萄', category: '托福词汇' },
  { word: 'grapevine', phonetic: '/ˈɡreɪpvaɪn/', meaning: 'n. 葡萄藤；小道消息', category: 'GRE词汇' },
  { word: 'graph', phonetic: '/ɡrɑːf/', meaning: 'n. 图表', category: '托福词汇' },
  { word: 'graphic', phonetic: '/ˈɡræfɪk/', meaning: 'adj. 图表的；生动的', category: '托福词汇' },
  { word: 'graphical', phonetic: '/ˈɡræfɪkl/', meaning: 'adj. 图形的', category: '科技词汇' },
  { word: 'graphite', phonetic: '/ˈɡræfaɪt/', meaning: 'n. 石墨', category: '科技词汇' },
  { word: 'grapple', phonetic: '/ˈɡræpl/', meaning: 'v. 扭打；努力克服', category: 'GRE词汇' },
  { word: 'grasp', phonetic: '/ɡrɑːsp/', meaning: 'v. 抓住；理解', category: '托福词汇' },
  { word: 'grass', phonetic: '/ɡrɑːs/', meaning: 'n. 草', category: '托福词汇' },
  { word: 'grasshopper', phonetic: '/ˈɡrɑːshɒpər/', meaning: 'n. 蚱蜢', category: '托福词汇' },
  { word: 'grassy', phonetic: '/ˈɡrɑːsi/', meaning: 'adj. 长满草的', category: '托福词汇' },
  { word: 'grate', phonetic: '/ɡreɪt/', meaning: 'n. 炉栅；v. 磨碎', category: 'GRE词汇' },
  { word: 'grateful', phonetic: '/ˈɡreɪtfl/', meaning: 'adj. 感激的', category: '托福词汇' },
  { word: 'gratification', phonetic: '/ˌɡrætɪfɪˈkeɪʃn/', meaning: 'n. 满足', category: 'GRE词汇' },
  { word: 'gratify', phonetic: '/ˈɡrætɪfaɪ/', meaning: 'v. 使满足', category: 'GRE词汇' },
  { word: 'grating', phonetic: '/ˈɡreɪtɪŋ/', meaning: 'adj. 刺耳的；n. 栅栏', category: 'GRE词汇' },
  { word: 'gratitude', phonetic: '/ˈɡrætɪtjuːd/', meaning: 'n. 感激', category: '托福词汇' },
  { word: 'gratuitous', phonetic: '/ɡrəˈtjuːɪtəs/', meaning: 'adj. 无故的；免费的', category: 'GRE词汇' },
  { word: 'gratuity', phonetic: '/ɡrəˈtjuːɪti/', meaning: 'n. 小费', category: '托福词汇' },
  { word: 'grave', phonetic: '/ɡreɪv/', meaning: 'n. 坟墓；adj. 严肃的', category: '托福词汇' },
  { word: 'gravel', phonetic: '/ˈɡrævl/', meaning: 'n. 砾石', category: '托福词汇' },
  { word: 'gravitation', phonetic: '/ˌɡrævɪˈteɪʃn/', meaning: 'n. 引力', category: '科技词汇' },
  { word: 'gravity', phonetic: '/ˈɡrævəti/', meaning: 'n. 重力；严重性', category: '托福词汇' },
  { word: 'gravitate', phonetic: '/ˈɡrævɪteɪt/', meaning: 'v. 受引力作用；被吸引', category: 'GRE词汇' },
  { word: 'gravy', phonetic: '/ˈɡreɪvi/', meaning: 'n. 肉汁', category: '托福词汇' },
  { word: 'gray', phonetic: '/ɡreɪ/', meaning: 'adj. 灰色的；n. 灰色', category: '托福词汇' },
  { word: 'graze', phonetic: '/ɡreɪz/', meaning: 'v. 放牧；擦伤', category: '托福词汇' },
  { word: 'grease', phonetic: '/ɡriːs/', meaning: 'n. 油脂；v. 涂油', category: '托福词汇' },
  { word: 'greasy', phonetic: '/ˈɡriːsi/', meaning: 'adj. 油腻的', category: '托福词汇' },
  { word: 'great', phonetic: '/ɡreɪt/', meaning: 'adj. 伟大的；巨大的', category: '托福词汇' },
  { word: 'greatly', phonetic: '/ˈɡreɪtli/', meaning: 'adv. 非常；大大地', category: '托福词汇' },
  { word: 'greed', phonetic: '/ɡriːd/', meaning: 'n. 贪婪', category: '托福词汇' },
  { word: 'greedy', phonetic: '/ˈɡriːdi/', meaning: 'adj. 贪婪的', category: '托福词汇' },
  { word: 'green', phonetic: '/ɡriːn/', meaning: 'adj. 绿色的；n. 绿色', category: '托福词汇' },
  { word: 'greenery', phonetic: '/ˈɡriːnəri/', meaning: 'n. 绿色植物', category: '托福词汇' },
  { word: 'greenhouse', phonetic: '/ˈɡriːnhaʊs/', meaning: 'n. 温室', category: '托福词汇' },
  { word: 'greenish', phonetic: '/ˈɡriːnɪʃ/', meaning: 'adj. 带绿色的', category: '托福词汇' },
  { word: 'greet', phonetic: '/ɡriːt/', meaning: 'v. 问候；迎接', category: '托福词汇' },
  { word: 'greeting', phonetic: '/ˈɡriːtɪŋ/', meaning: 'n. 问候', category: '托福词汇' },
  { word: 'gremlin', phonetic: '/ˈɡremlɪn/', meaning: 'n. 小捣蛋鬼', category: 'GRE词汇' },
  { word: 'grenade', phonetic: '/ɡrəˈneɪd/', meaning: 'n. 手榴弹', category: 'GRE词汇' },
  { word: 'grey', phonetic: '/ɡreɪ/', meaning: 'adj. 灰色的', category: '托福词汇' },
  { word: 'grid', phonetic: '/ɡrɪd/', meaning: 'n. 网格', category: '托福词汇' },
  { word: 'gridlock', phonetic: '/ˈɡrɪdlɒk/', meaning: 'n. 僵局；交通瘫痪', category: 'GRE词汇' },
  { word: 'grief', phonetic: '/ɡriːf/', meaning: 'n. 悲伤', category: '托福词汇' },
  { word: 'grievance', phonetic: '/ˈɡriːvəns/', meaning: 'n. 委屈；不满', category: 'GRE词汇' },
  { word: 'grieve', phonetic: '/ɡriːv/', meaning: 'v. 悲伤', category: '托福词汇' },
  { word: 'grievous', phonetic: '/ˈɡriːvəs/', meaning: 'adj. 严重的；令人痛苦的', category: 'GRE词汇' },
  { word: 'grill', phonetic: '/ɡrɪl/', meaning: 'n. 烤架；v. 烤', category: '托福词汇' },
  { word: 'grim', phonetic: '/ɡrɪm/', meaning: 'adj. 严厉的；可怕的', category: 'GRE词汇' },
  { word: 'grimace', phonetic: '/ɡrɪˈmeɪs/', meaning: 'n. 鬼脸；v. 做鬼脸', category: 'GRE词汇' },
  { word: 'grime', phonetic: '/ɡraɪm/', meaning: 'n. 污垢', category: 'GRE词汇' },
  { word: 'grimy', phonetic: '/ˈɡraɪmi/', meaning: 'adj. 肮脏的', category: 'GRE词汇' },
  { word: 'grin', phonetic: '/ɡrɪn/', meaning: 'v. 露齿笑；n. 露齿笑', category: '托福词汇' },
  { word: 'grind', phonetic: '/ɡraɪnd/', meaning: 'v. 研磨；n. 苦差事', category: '托福词汇' },
  { word: 'grinder', phonetic: '/ˈɡraɪndər/', meaning: 'n. 研磨机', category: '托福词汇' },
  { word: 'grip', phonetic: '/ɡrɪp/', meaning: 'v. 抓紧；n. 紧握', category: '托福词汇' },
  { word: 'gripe', phonetic: '/ɡraɪp/', meaning: 'v. 抱怨', category: 'GRE词汇' },
  { word: 'gripping', phonetic: '/ˈɡrɪpɪŋ/', meaning: 'adj. 扣人心弦的', category: 'GRE词汇' },
  { word: 'grisly', phonetic: '/ˈɡrɪzli/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'grist', phonetic: '/ɡrɪst/', meaning: 'n. 谷物；有用之物', category: 'GRE词汇' },
  { word: 'grit', phonetic: '/ɡrɪt/', meaning: 'n. 沙砾；毅力', category: 'GRE词汇' },
  { word: 'gritty', phonetic: '/ˈɡrɪti/', meaning: 'adj. 有沙砾的；坚毅的', category: 'GRE词汇' },
  { word: 'groan', phonetic: '/ɡrəʊn/', meaning: 'v. 呻吟；n. 呻吟', category: '托福词汇' },
  { word: 'groom', phonetic: '/ɡruːm/', meaning: 'n. 新郎；v. 打扮；培养', category: '托福词汇' },
  { word: 'groove', phonetic: '/ɡruːv/', meaning: 'n. 槽；常规', category: 'GRE词汇' },
  { word: 'grope', phonetic: '/ɡrəʊp/', meaning: 'v. 摸索', category: 'GRE词汇' },
  { word: 'gross', phonetic: '/ɡrəʊs/', meaning: 'adj. 总的；粗俗的', category: '托福词汇' },
  { word: 'grotesque', phonetic: '/ɡrəʊˈtesk/', meaning: 'adj. 怪诞的；丑陋的', category: 'GRE词汇' },
  { word: 'grouch', phonetic: '/ɡraʊtʃ/', meaning: 'n. 脾气坏的人；v. 发牢骚', category: 'GRE词汇' },
  { word: 'ground', phonetic: '/ɡraʊnd/', meaning: 'n. 地面；基础', category: '托福词汇' },
  { word: 'groundbreaking', phonetic: '/ˈɡraʊndbreɪkɪŋ/', meaning: 'adj. 开创性的', category: '托福词汇' },
  { word: 'groundless', phonetic: '/ˈɡraʊndləs/', meaning: 'adj. 无根据的', category: '托福词汇' },
  { word: 'group', phonetic: '/ɡruːp/', meaning: 'n. 群体；v. 分组', category: '托福词汇' },
  { word: 'grouping', phonetic: '/ˈɡruːpɪŋ/', meaning: 'n. 分组', category: '托福词汇' },
  { word: 'grouse', phonetic: '/ɡraʊs/', meaning: 'n. 松鸡；v. 抱怨', category: 'GRE词汇' },
  { word: 'grove', phonetic: '/ɡrəʊv/', meaning: 'n. 小树林', category: 'GRE词汇' },
  { word: 'grovel', phonetic: '/ˈɡrɒvl/', meaning: 'v. 卑躬屈膝', category: 'GRE词汇' },
  { word: 'grow', phonetic: '/ɡrəʊ/', meaning: 'v. 生长；变得', category: '托福词汇' },
  { word: 'growl', phonetic: '/ɡraʊl/', meaning: 'v. 咆哮；n. 咆哮', category: '托福词汇' },
  { word: 'grown', phonetic: '/ɡrəʊn/', meaning: 'adj. 成年的', category: '托福词汇' },
  { word: 'growth', phonetic: '/ɡrəʊθ/', meaning: 'n. 生长；增长', category: '托福词汇' },
  { word: 'growl', phonetic: '/ɡraʊl/', meaning: 'v. 低吼', category: '托福词汇' },
  { word: 'grub', phonetic: '/ɡrʌb/', meaning: 'n. 幼虫；v. 挖掘', category: 'GRE词汇' },
  { word: 'grudge', phonetic: '/ɡrʌdʒ/', meaning: 'n. 怨恨；v. 勉强给', category: 'GRE词汇' },
  { word: 'grudging', phonetic: '/ˈɡrʌdʒɪŋ/', meaning: 'adj. 勉强的', category: 'GRE词汇' },
  { word: 'grueling', phonetic: '/ˈɡruːəlɪŋ/', meaning: 'adj. 累人的', category: 'GRE词汇' },
  { word: 'gruesome', phonetic: '/ˈɡruːsəm/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'grumble', phonetic: '/ˈɡrʌmbl/', meaning: 'v. 抱怨；n. 抱怨', category: '托福词汇' },
  { word: 'grumpy', phonetic: '/ˈɡrʌmpi/', meaning: 'adj. 脾气暴躁的', category: '托福词汇' },
  { word: 'grunt', phonetic: '/ɡrʌnt/', meaning: 'v. 咕哝；n. 咕哝声', category: 'GRE词汇' },
  { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: 'n. 保证；v. 保证', category: '托福词汇' },
  { word: 'guard', phonetic: '/ɡɑːd/', meaning: 'n. 守卫；v. 保卫', category: '托福词汇' },
  { word: 'guardian', phonetic: '/ˈɡɑːdiən/', meaning: 'n. 监护人；守护者', category: '托福词汇' },
  { word: 'guerrilla', phonetic: '/ɡəˈrɪlə/', meaning: 'n. 游击队员', category: 'GRE词汇' },
  { word: 'guess', phonetic: '/ɡes/', meaning: 'v. 猜测；n. 猜测', category: '托福词汇' },
  { word: 'guest', phonetic: '/ɡest/', meaning: 'n. 客人', category: '托福词汇' },
  { word: 'guidance', phonetic: '/ˈɡaɪdns/', meaning: 'n. 指导', category: '托福词汇' },
  { word: 'guide', phonetic: '/ɡaɪd/', meaning: 'n. 指南；v. 引导', category: '托福词汇' },
  { word: 'guideline', phonetic: '/ˈɡaɪdlaɪn/', meaning: 'n. 指导方针', category: '托福词汇' },
  { word: 'guild', phonetic: '/ɡɪld/', meaning: 'n. 行会；协会', category: 'GRE词汇' },
  { word: 'guile', phonetic: '/ɡaɪl/', meaning: 'n. 狡诈', category: 'GRE词汇' },
  { word: 'guileless', phonetic: '/ˈɡaɪlləs/', meaning: 'adj. 诚实的', category: 'GRE词汇' },
  { word: 'guilty', phonetic: '/ˈɡɪlti/', meaning: 'adj. 有罪的；内疚的', category: '托福词汇' },
  { word: 'guilt', phonetic: '/ɡɪlt/', meaning: 'n. 内疚；罪行', category: '托福词汇' },
  { word: 'guise', phonetic: '/ɡaɪz/', meaning: 'n. 伪装；外观', category: 'GRE词汇' },
  { word: 'guitar', phonetic: '/ɡɪˈtɑːr/', meaning: 'n. 吉他', category: '托福词汇' },
  { word: 'gulf', phonetic: '/ɡʌlf/', meaning: 'n. 海湾；鸿沟', category: '托福词汇' },
  { word: 'gull', phonetic: '/ɡʌl/', meaning: 'n. 海鸥；v. 欺骗', category: 'GRE词汇' },
  { word: 'gullible', phonetic: '/ˈɡʌləbl/', meaning: 'adj. 易受骗的', category: 'GRE词汇' },
  { word: 'gulp', phonetic: '/ɡʌlp/', meaning: 'v. 狼吞虎咽；n. 一大口', category: 'GRE词汇' },
  { word: 'gum', phonetic: '/ɡʌm/', meaning: 'n. 牙龈；口香糖', category: '托福词汇' },
  { word: 'gummy', phonetic: '/ˈɡʌmi/', meaning: 'adj. 粘的', category: 'GRE词汇' },
  { word: 'gun', phonetic: '/ɡʌn/', meaning: 'n. 枪', category: '托福词汇' },
  { word: 'gunfire', phonetic: '/ˈɡʌnfaɪər/', meaning: 'n. 炮火', category: 'GRE词汇' },
  { word: 'gunman', phonetic: '/ˈɡʌnmən/', meaning: 'n. 持枪者', category: 'GRE词汇' },
  { word: 'gunpowder', phonetic: '/ˈɡʌnpaʊdər/', meaning: 'n. 火药', category: 'GRE词汇' },
  { word: 'gurgle', phonetic: '/ˈɡɜːɡl/', meaning: 'v. 咕噜作响；n. 咕噜声', category: 'GRE词汇' },
  { word: 'guru', phonetic: '/ˈɡʊruː/', meaning: 'n. 大师；权威', category: '托福词汇' },
  { word: 'gush', phonetic: '/ɡʌʃ/', meaning: 'v. 涌出；滔滔不绝', category: 'GRE词汇' },
  { word: 'gushing', phonetic: '/ˈɡʌʃɪŋ/', meaning: 'adj. 涌出的；过分热情的', category: 'GRE词汇' },
  { word: 'gust', phonetic: '/ɡʌst/', meaning: 'n. 阵风；v. 阵风吹', category: '托福词汇' },
  { word: 'gusto', phonetic: '/ˈɡʌstəʊ/', meaning: 'n. 热情', category: 'GRE词汇' },
  { word: 'gusty', phonetic: '/ˈɡʌsti/', meaning: 'adj. 阵风的', category: '托福词汇' },
  { word: 'gut', phonetic: '/ɡʌt/', meaning: 'n. 肠子；勇气', category: '托福词汇' },
  { word: 'gutter', phonetic: '/ˈɡʌtər/', meaning: 'n. 排水沟', category: '托福词汇' },
  { word: 'gutless', phonetic: '/ˈɡʌtləs/', meaning: 'adj. 无胆量的', category: 'GRE词汇' },
  { word: 'guts', phonetic: '/ɡʌts/', meaning: 'n. 勇气；内脏', category: '托福词汇' },
  { word: 'gutsy', phonetic: '/ˈɡʌtsi/', meaning: 'adj. 勇敢的', category: 'GRE词汇' },
  { word: 'guzzle', phonetic: '/ˈɡʌzl/', meaning: 'v. 大吃大喝', category: 'GRE词汇' },
  { word: 'gym', phonetic: '/dʒɪm/', meaning: 'n. 体育馆；健身房', category: '托福词汇' },
  { word: 'gymnasium', phonetic: '/dʒɪmˈneɪziəm/', meaning: 'n. 体育馆', category: '托福词汇' },
  { word: 'gymnast', phonetic: '/ˈdʒɪmnæst/', meaning: 'n. 体操运动员', category: '托福词汇' },
  { word: 'gymnastics', phonetic: '/dʒɪmˈnæstɪks/', meaning: 'n. 体操', category: '托福词汇' },
  { word: 'gynecology', phonetic: '/ˌɡaɪnɪˈkɒlədʒi/', meaning: 'n. 妇科学', category: '医学词汇' },
  { word: 'gyrate', phonetic: '/ˈdʒaɪreɪt/', meaning: 'v. 旋转', category: 'GRE词汇' },
  { word: 'gyroscope', phonetic: '/ˈdʒaɪrəskəʊp/', meaning: 'n. 陀螺仪', category: '科技词汇' },

  // H字母开头
  { word: 'habitat', phonetic: '/ˈhæbɪtæt/', meaning: 'n. 栖息地', category: '托福词汇' },
  { word: 'habit', phonetic: '/ˈhæbɪt/', meaning: 'n. 习惯', category: '托福词汇' },
  { word: 'habitable', phonetic: '/ˈhæbɪtəbl/', meaning: 'adj. 可居住的', category: '托福词汇' },
  { word: 'habitation', phonetic: '/ˌhæbɪˈteɪʃn/', meaning: 'n. 居住；住所', category: 'GRE词汇' },
  { word: 'habitual', phonetic: '/həˈbɪtʃuəl/', meaning: 'adj. 习惯的', category: '托福词汇' },
  { word: 'hack', phonetic: '/hæk/', meaning: 'v. 砍；n. 出租车', category: '托福词汇' },
  { word: 'hacker', phonetic: '/ˈhækər/', meaning: 'n. 黑客', category: '科技词汇' },
  { word: 'hackneyed', phonetic: '/ˈhæknid/', meaning: 'adj. 陈腐的', category: 'GRE词汇' },
  { word: 'haggard', phonetic: '/ˈhæɡəd/', meaning: 'adj. 憔悴的', category: 'GRE词汇' },
  { word: 'haggle', phonetic: '/ˈhæɡl/', meaning: 'v. 讨价还价', category: 'GRE词汇' },
  { word: 'hail', phonetic: '/heɪl/', meaning: 'n. 冰雹；v. 欢呼', category: '托福词汇' },
  { word: 'hair', phonetic: '/heər/', meaning: 'n. 头发', category: '托福词汇' },
  { word: 'haircut', phonetic: '/ˈheəkʌt/', meaning: 'n. 理发', category: '托福词汇' },
  { word: 'hairdo', phonetic: '/ˈheəduː/', meaning: 'n. 发型', category: '托福词汇' },
  { word: 'hairy', phonetic: '/ˈheəri/', meaning: 'adj. 多毛的', category: '托福词汇' },
  { word: 'half', phonetic: '/hɑːf/', meaning: 'n. 一半；adj. 一半的', category: '托福词汇' },
  { word: 'halfhearted', phonetic: '/ˌhɑːfˈhɑːtɪd/', meaning: 'adj. 不认真的', category: 'GRE词汇' },
  { word: 'halfway', phonetic: '/ˌhɑːfˈweɪ/', meaning: 'adv. 半途', category: '托福词汇' },
  { word: 'hall', phonetic: '/hɔːl/', meaning: 'n. 大厅', category: '托福词汇' },
  { word: 'hallow', phonetic: '/ˈhæləʊ/', meaning: 'v. 使神圣', category: 'GRE词汇' },
  { word: 'hallucinate', phonetic: '/həˈluːsɪneɪt/', meaning: 'v. 产生幻觉', category: '医学词汇' },
  { word: 'hallucination', phonetic: '/həˌluːsɪˈneɪʃn/', meaning: 'n. 幻觉', category: '医学词汇' },
  { word: 'hallway', phonetic: '/ˈhɔːlweɪ/', meaning: 'n. 门厅', category: '托福词汇' },
  { word: 'halt', phonetic: '/hɔːlt/', meaning: 'v. 停止；n. 停止', category: '托福词汇' },
  { word: 'halting', phonetic: '/ˈhɔːltɪŋ/', meaning: 'adj. 踌躇的；不流畅的', category: 'GRE词汇' },
  { word: 'halve', phonetic: '/hɑːv/', meaning: 'v. 减半', category: '托福词汇' },
  { word: 'ham', phonetic: '/hæm/', meaning: 'n. 火腿', category: '托福词汇' },
  { word: 'hammer', phonetic: '/ˈhæmər/', meaning: 'n. 锤子；v. 锤击', category: '托福词汇' },
  { word: 'hamper', phonetic: '/ˈhæmpər/', meaning: 'v. 妨碍；n. 阻碍', category: 'GRE词汇' },
  { word: 'hamstring', phonetic: '/ˈhæmstrɪŋ/', meaning: 'n. 腿筋；v. 使瘫痪', category: 'GRE词汇' },
  { word: 'hand', phonetic: '/hænd/', meaning: 'n. 手；v. 传递', category: '托福词汇' },
  { word: 'handbag', phonetic: '/ˈhændbæɡ/', meaning: 'n. 手提包', category: '托福词汇' },
  { word: 'handbook', phonetic: '/ˈhændbʊk/', meaning: 'n. 手册', category: '托福词汇' },
  { word: 'handcuff', phonetic: '/ˈhændkʌf/', meaning: 'n. 手铐；v. 上手铐', category: '法律词汇' },
  { word: 'handful', phonetic: '/ˈhændfl/', meaning: 'n. 一把；少数', category: '托福词汇' },
  { word: 'handicap', phonetic: '/ˈhændikæp/', meaning: 'n. 障碍；v. 妨碍', category: '托福词汇' },
  { word: 'handicraft', phonetic: '/ˈhændikrɑːft/', meaning: 'n. 手工艺品', category: '托福词汇' },
  { word: 'handily', phonetic: '/ˈhændɪli/', meaning: 'adv. 方便地；轻易地', category: 'GRE词汇' },
  { word: 'handicapped', phonetic: '/ˈhændikæpt/', meaning: 'adj. 残疾的', category: '托福词汇' },
  { word: 'handle', phonetic: '/ˈhændl/', meaning: 'n. 把手；v. 处理', category: '托福词汇' },
  { word: 'handmade', phonetic: '/ˌhændˈmeɪd/', meaning: 'adj. 手工的', category: '托福词汇' },
  { word: 'handout', phonetic: '/ˈhændaʊt/', meaning: 'n. 救济品；讲义', category: '托福词汇' },
  { word: 'handover', phonetic: '/ˈhændəʊvər/', meaning: 'n. 移交', category: '商务词汇' },
  { word: 'handsome', phonetic: '/ˈhænsəm/', meaning: 'adj. 英俊的；可观的', category: '托福词汇' },
  { word: 'handwriting', phonetic: '/ˈhændraɪtɪŋ/', meaning: 'n. 笔迹', category: '托福词汇' },
  { word: 'handy', phonetic: '/ˈhændi/', meaning: 'adj. 方便的；手边的', category: '托福词汇' },
  { word: 'hang', phonetic: '/hæŋ/', meaning: 'v. 悬挂；绞死', category: '托福词汇' },
  { word: 'hanger', phonetic: '/ˈhæŋər/', meaning: 'n. 衣架', category: '托福词汇' },
  { word: 'haphazard', phonetic: '/hæpˈhæzəd/', meaning: 'adj. 随意的；杂乱的', category: 'GRE词汇' },
  { word: 'hapless', phonetic: '/ˈhæpləs/', meaning: 'adj. 不幸的', category: 'GRE词汇' },
  { word: 'happen', phonetic: '/ˈhæpən/', meaning: 'v. 发生', category: '托福词汇' },
  { word: 'happening', phonetic: '/ˈhæpənɪŋ/', meaning: 'n. 事件', category: '托福词汇' },
  { word: 'happily', phonetic: '/ˈhæpɪli/', meaning: 'adv. 幸福地', category: '托福词汇' },
  { word: 'happiness', phonetic: '/ˈhæpinəs/', meaning: 'n. 幸福', category: '托福词汇' },
  { word: 'happy', phonetic: '/ˈhæpi/', meaning: 'adj. 幸福的', category: '托福词汇' },
  { word: 'harangue', phonetic: '/həˈræŋ/', meaning: 'n. 长篇演说；v. 高谈阔论', category: 'GRE词汇' },
  { word: 'harass', phonetic: '/ˈhærəs/', meaning: 'v. 骚扰', category: '法律词汇' },
  { word: 'harassment', phonetic: '/ˈhærəsmənt/', meaning: 'n. 骚扰', category: '法律词汇' },
  { word: 'harbor', phonetic: '/ˈhɑːbər/', meaning: 'n. 港口；v. 窝藏', category: '托福词汇' },
  { word: 'hard', phonetic: '/hɑːd/', meaning: 'adj. 坚硬的；adv. 努力地', category: '托福词汇' },
  { word: 'harden', phonetic: '/ˈhɑːdn/', meaning: 'v. 变硬', category: '托福词汇' },
  { word: 'hardheaded', phonetic: '/ˌhɑːdˈhedɪd/', meaning: 'adj. 冷静的；精明的', category: 'GRE词汇' },
  { word: 'hardly', phonetic: '/ˈhɑːdli/', meaning: 'adv. 几乎不', category: '托福词汇' },
  { word: 'hardship', phonetic: '/ˈhɑːdʃɪp/', meaning: 'n. 困苦', category: '托福词汇' },
  { word: 'hardware', phonetic: '/ˈhɑːdweər/', meaning: 'n. 硬件', category: '科技词汇' },
  { word: 'hardy', phonetic: '/ˈhɑːdi/', meaning: 'adj. 强壮的；耐寒的', category: 'GRE词汇' },
  { word: 'hare', phonetic: '/heər/', meaning: 'n. 野兔', category: '托福词汇' },
  { word: 'harm', phonetic: '/hɑːm/', meaning: 'n. 伤害；v. 伤害', category: '托福词汇' },
  { word: 'harmful', phonetic: '/ˈhɑːmfl/', meaning: 'adj. 有害的', category: '托福词汇' },
  { word: 'harmless', phonetic: '/ˈhɑːmləs/', meaning: 'adj. 无害的', category: '托福词汇' },
  { word: 'harmonious', phonetic: '/hɑːˈməʊniəs/', meaning: 'adj. 和谐的', category: '托福词汇' },
  { word: 'harmonize', phonetic: '/ˈhɑːmənaɪz/', meaning: 'v. 使和谐', category: '托福词汇' },
  { word: 'harmony', phonetic: '/ˈhɑːməni/', meaning: 'n. 和谐', category: '托福词汇' },
  { word: 'harness', phonetic: '/ˈhɑːnɪs/', meaning: 'n. 马具；v. 利用', category: '托福词汇' },
  { word: 'harp', phonetic: '/hɑːp/', meaning: 'n. 竖琴；v. 反复诉说', category: 'GRE词汇' },
  { word: 'harsh', phonetic: '/hɑːʃ/', meaning: 'adj. 严厉的；粗糙的', category: '托福词汇' },
  { word: 'harvest', phonetic: '/ˈhɑːvɪst/', meaning: 'n. 收获；v. 收割', category: '托福词汇' },
  { word: 'has', phonetic: '/hæz/', meaning: 'v. have的第三人称单数', category: '托福词汇' },
  { word: 'haste', phonetic: '/heɪst/', meaning: 'n. 急忙', category: 'GRE词汇' },
  { word: 'hasten', phonetic: '/ˈheɪsn/', meaning: 'v. 加速；催促', category: 'GRE词汇' },
  { word: 'hasty', phonetic: '/ˈheɪsti/', meaning: 'adj. 匆忙的；草率的', category: 'GRE词汇' },
  { word: 'hat', phonetic: '/hæt/', meaning: 'n. 帽子', category: '托福词汇' },
  { word: 'hatch', phonetic: '/hætʃ/', meaning: 'v. 孵化；n. 舱口', category: '托福词汇' },
  { word: 'hatchet', phonetic: '/ˈhætʃɪt/', meaning: 'n. 短柄斧', category: 'GRE词汇' },
  { word: 'hate', phonetic: '/heɪt/', meaning: 'v. 憎恨；n. 憎恨', category: '托福词汇' },
  { word: 'hateful', phonetic: '/ˈheɪtfl/', meaning: 'adj. 可恨的', category: '托福词汇' },
  { word: 'hatred', phonetic: '/ˈheɪtrɪd/', meaning: 'n. 仇恨', category: '托福词汇' },
  { word: 'haughty', phonetic: '/ˈhɔːti/', meaning: 'adj. 傲慢的', category: 'GRE词汇' },
  { word: 'haul', phonetic: '/hɔːl/', meaning: 'v. 拖运；n. 拖运', category: '托福词汇' },
  { word: 'haunt', phonetic: '/hɔːnt/', meaning: 'v. 常去；困扰', category: 'GRE词汇' },
  { word: 'haunting', phonetic: '/ˈhɔːntɪŋ/', meaning: 'adj. 紫绕心头的', category: 'GRE词汇' },
  { word: 'have', phonetic: '/hæv/', meaning: 'v. 有', category: '托福词汇' },
  { word: 'haven', phonetic: '/ˈheɪvn/', meaning: 'n. 避难所', category: 'GRE词汇' },
  { word: 'havoc', phonetic: '/ˈhævək/', meaning: 'n. 大破坏', category: 'GRE词汇' },
  { word: 'hawk', phonetic: '/hɔːk/', meaning: 'n. 鹰；v. 叫卖', category: '托福词汇' },
  { word: 'hawker', phonetic: '/ˈhɔːkər/', meaning: 'n. 叫卖者', category: 'GRE词汇' },
  { word: 'hay', phonetic: '/heɪ/', meaning: 'n. 干草', category: '托福词汇' },
  { word: 'hazard', phonetic: '/ˈhæzəd/', meaning: 'n. 危险；v. 冒险', category: '托福词汇' },
  { word: 'hazardous', phonetic: '/ˈhæzədəs/', meaning: 'adj. 危险的', category: '托福词汇' },
  { word: 'haze', phonetic: '/heɪz/', meaning: 'n. 薄雾；v. 变模糊', category: '托福词汇' },
  { word: 'hazy', phonetic: '/ˈheɪzi/', meaning: 'adj. 朦胧的；模糊的', category: '托福词汇' },
  { word: 'he', phonetic: '/hiː/', meaning: 'pron. 他', category: '托福词汇' },
  { word: 'head', phonetic: '/hed/', meaning: 'n. 头；v. 率领', category: '托福词汇' },
  { word: 'headache', phonetic: '/ˈhedeɪk/', meaning: 'n. 头痛', category: '托福词汇' },
  { word: 'heading', phonetic: '/ˈhedɪŋ/', meaning: 'n. 标题', category: '托福词汇' },
  { word: 'headlong', phonetic: '/ˈhedlɒŋ/', meaning: 'adv. 头朝前；匆忙地', category: 'GRE词汇' },
  { word: 'headmaster', phonetic: '/hedˈmɑːstər/', meaning: 'n. 校长', category: '托福词汇' },
  { word: 'headphone', phonetic: '/ˈhedfəʊn/', meaning: 'n. 耳机', category: '托福词汇' },
  { word: 'headquarters', phonetic: '/ˌhedˈkwɔːtərz/', meaning: 'n. 总部', category: '托福词汇' },
  { word: 'headstrong', phonetic: '/ˈhedstrɒŋ/', meaning: 'adj. 固执的', category: 'GRE词汇' },
  { word: 'heal', phonetic: '/hiːl/', meaning: 'v. 治愈', category: '托福词汇' },
  { word: 'healer', phonetic: '/ˈhiːlər/', meaning: 'n. 医治者', category: '医学词汇' },
  { word: 'health', phonetic: '/helθ/', meaning: 'n. 健康', category: '托福词汇' },
  { word: 'healthcare', phonetic: '/ˈhelθkeər/', meaning: 'n. 医疗保健', category: '医学词汇' },
  { word: 'healthy', phonetic: '/ˈhelθi/', meaning: 'adj. 健康的', category: '托福词汇' },
  { word: 'heap', phonetic: '/hiːp/', meaning: 'n. 堆；v. 堆积', category: '托福词汇' },
  { word: 'hear', phonetic: '/hɪər/', meaning: 'v. 听见', category: '托福词汇' },
  { word: 'hearing', phonetic: '/ˈhɪərɪŋ/', meaning: 'n. 听力；听证会', category: '托福词汇' },
  { word: 'hearsay', phonetic: '/ˈhɪəseɪ/', meaning: 'n. 传闻', category: '法律词汇' },
  { word: 'hearse', phonetic: '/hɜːs/', meaning: 'n. 灵车', category: 'GRE词汇' },
  { word: 'heart', phonetic: '/hɑːt/', meaning: 'n. 心脏；中心', category: '托福词汇' },
  { word: 'heartache', phonetic: '/ˈhɑːteɪk/', meaning: 'n. 心痛', category: 'GRE词汇' },
  { word: 'heartbeat', phonetic: '/ˈhɑːtbiːt/', meaning: 'n. 心跳', category: '医学词汇' },
  { word: 'heartbreak', phonetic: '/ˈhɑːtbreɪk/', meaning: 'n. 心碎', category: 'GRE词汇' },
  { word: 'heartbreaking', phonetic: '/ˈhɑːtbreɪkɪŋ/', meaning: 'adj. 令人心碎的', category: 'GRE词汇' },
  { word: 'heartfelt', phonetic: '/ˈhɑːtfelt/', meaning: 'adj. 衷心的', category: 'GRE词汇' },
  { word: 'hearth', phonetic: '/hɑːθ/', meaning: 'n. 壁炉；家庭', category: 'GRE词汇' },
  { word: 'heartily', phonetic: '/ˈhɑːtɪli/', meaning: 'adv. 衷心地', category: '托福词汇' },
  { word: 'heartless', phonetic: '/ˈhɑːtləs/', meaning: 'adj. 无情的', category: 'GRE词汇' },
  { word: 'heartrending', phonetic: '/ˈhɑːtrendɪŋ/', meaning: 'adj. 令人心碎的', category: 'GRE词汇' },
  { word: 'hearty', phonetic: '/ˈhɑːti/', meaning: 'adj. 衷心的；丰盛的', category: 'GRE词汇' },
  { word: 'heat', phonetic: '/hiːt/', meaning: 'n. 热；v. 加热', category: '托福词汇' },
  { word: 'heater', phonetic: '/ˈhiːtər/', meaning: 'n. 加热器', category: '托福词汇' },
  { word: 'heath', phonetic: '/hiːθ/', meaning: 'n. 荒野', category: 'GRE词汇' },
  { word: 'heave', phonetic: '/hiːv/', meaning: 'v. 举起；n. 举起', category: 'GRE词汇' },
  { word: 'heaven', phonetic: '/ˈhevn/', meaning: 'n. 天堂', category: '托福词汇' },
  { word: 'heavenly', phonetic: '/ˈhevnli/', meaning: 'adj. 天堂的；极好的', category: '托福词汇' },
  { word: 'heavy', phonetic: '/ˈhevi/', meaning: 'adj. 重的；大量的', category: '托福词汇' },
  { word: 'hectic', phonetic: '/ˈhektɪk/', meaning: 'adj. 忙乱的', category: 'GRE词汇' },
  { word: 'hedge', phonetic: '/hedʒ/', meaning: 'n. 树篱；v. 规避', category: '托福词汇' },
  { word: 'hedgehog', phonetic: '/ˈhedʒhɒɡ/', meaning: 'n. 刺猬', category: 'GRE词汇' },
  { word: 'heed', phonetic: '/hiːd/', meaning: 'v. 注意；n. 注意', category: 'GRE词汇' },
  { word: 'heel', phonetic: '/hiːl/', meaning: 'n. 脚后跟', category: '托福词汇' },
  { word: 'height', phonetic: '/haɪt/', meaning: 'n. 高度', category: '托福词汇' },
  { word: 'heighten', phonetic: '/ˈhaɪtn/', meaning: 'v. 提高；加剧', category: '托福词汇' },
  { word: 'heir', phonetic: '/eər/', meaning: 'n. 继承人', category: '托福词汇' },
  { word: 'heirloom', phonetic: '/ˈeəluːm/', meaning: 'n. 传家宝', category: 'GRE词汇' },
  { word: 'heinous', phonetic: '/ˈheɪnəs/', meaning: 'adj. 可憎的', category: 'GRE词汇' },
  { word: 'held', phonetic: '/held/', meaning: 'v. hold的过去式', category: '托福词汇' },
  { word: 'helicopter', phonetic: '/ˈhelɪkɒptər/', meaning: 'n. 直升机', category: '托福词汇' },
  { word: 'helmet', phonetic: '/ˈhelmɪt/', meaning: 'n. 头盔', category: '托福词汇' },
  { word: 'help', phonetic: '/help/', meaning: 'v. 帮助；n. 帮助', category: '托福词汇' },
  { word: 'helpful', phonetic: '/ˈhelpfl/', meaning: 'adj. 有帮助的', category: '托福词汇' },
  { word: 'helpless', phonetic: '/ˈhelpləs/', meaning: 'adj. 无助的', category: '托福词汇' },
  { word: 'hemisphere', phonetic: '/ˈhemɪsfɪər/', meaning: 'n. 半球', category: '托福词汇' },
  { word: 'hemorrhage', phonetic: '/ˈhemərɪdʒ/', meaning: 'n. 出血；v. 大出血', category: '医学词汇' },
  { word: 'hen', phonetic: '/hen/', meaning: 'n. 母鸡', category: '托福词汇' },
  { word: 'hence', phonetic: '/hens/', meaning: 'adv. 因此', category: '托福词汇' },
  { word: 'henceforth', phonetic: '/ˌhensˈfɔːθ/', meaning: 'adv. 此后', category: 'GRE词汇' },
  { word: 'her', phonetic: '/hɜːr/', meaning: 'pron. 她；她的', category: '托福词汇' },
  { word: 'herald', phonetic: '/ˈherəld/', meaning: 'n. 先驱；v. 预示', category: 'GRE词汇' },
  { word: 'herb', phonetic: '/hɜːb/', meaning: 'n. 草药', category: '托福词汇' },
  { word: 'herbal', phonetic: '/ˈhɜːbl/', meaning: 'adj. 草药的', category: '托福词汇' },
  { word: 'herd', phonetic: '/hɜːd/', meaning: 'n. 兽群；v. 放牧', category: '托福词汇' },
  { word: 'here', phonetic: '/hɪər/', meaning: 'adv. 这里', category: '托福词汇' },
  { word: 'hereafter', phonetic: '/ˌhɪərˈɑːftər/', meaning: 'adv. 此后', category: 'GRE词汇' },
  { word: 'hereby', phonetic: '/hɪəˈbaɪ/', meaning: 'adv. 特此', category: '法律词汇' },
  { word: 'hereditary', phonetic: '/həˈredɪtəri/', meaning: 'adj. 遗传的', category: '医学词汇' },
  { word: 'heredity', phonetic: '/həˈredəti/', meaning: 'n. 遗传', category: '医学词汇' },
  { word: 'herein', phonetic: '/hɪərˈɪn/', meaning: 'adv. 在此处', category: '法律词汇' },
  { word: 'heretic', phonetic: '/ˈherətɪk/', meaning: 'n. 异端者', category: 'GRE词汇' },
  { word: 'heretical', phonetic: '/həˈretɪkl/', meaning: 'adj. 异端的', category: 'GRE词汇' },
  { word: 'heritage', phonetic: '/ˈherɪtɪdʒ/', meaning: 'n. 遗产；传统', category: '托福词汇' },
  { word: 'hermit', phonetic: '/ˈhɜːmɪt/', meaning: 'n. 隐士', category: 'GRE词汇' },
  { word: 'hero', phonetic: '/ˈhɪərəʊ/', meaning: 'n. 英雄', category: '托福词汇' },
  { word: 'heroic', phonetic: '/həˈrəʊɪk/', meaning: 'adj. 英雄的', category: '托福词汇' },
  { word: 'heroine', phonetic: '/ˈherəʊɪn/', meaning: 'n. 女英雄', category: '托福词汇' },
  { word: 'heron', phonetic: '/ˈherən/', meaning: 'n. 苍鹭', category: 'GRE词汇' },
  { word: 'hesitant', phonetic: '/ˈhezɪtənt/', meaning: 'adj. 犹豫的', category: '托福词汇' },
  { word: 'hesitate', phonetic: '/ˈhezɪteɪt/', meaning: 'v. 犹豫', category: '托福词汇' },
  { word: 'hesitation', phonetic: '/ˌhezɪˈteɪʃn/', meaning: 'n. 犹豫', category: '托福词汇' },
  { word: 'heterodox', phonetic: '/ˈhetərədɒks/', meaning: 'adj. 异端的', category: 'GRE词汇' },
  { word: 'heterogeneous', phonetic: '/ˌhetərəˈdʒiːniəs/', meaning: 'adj. 异质的；多样的', category: 'GRE词汇' },
  { word: 'hew', phonetic: '/hjuː/', meaning: 'v. 砍', category: 'GRE词汇' },
  { word: 'hexagon', phonetic: '/ˈheksəɡən/', meaning: 'n. 六边形', category: '科技词汇' },
  { word: 'hey', phonetic: '/heɪ/', meaning: 'int. 嘿', category: '托福词汇' },
  { word: 'hiatus', phonetic: '/haɪˈeɪtəs/', meaning: 'n. 间断；空隙', category: 'GRE词汇' },
  { word: 'hibernate', phonetic: '/ˈhaɪbəneɪt/', meaning: 'v. 冬眠', category: 'GRE词汇' },
  { word: 'hibernation', phonetic: '/ˌhaɪbəˈneɪʃn/', meaning: 'n. 冬眠', category: 'GRE词汇' },
  { word: 'hidden', phonetic: '/ˈhɪdn/', meaning: 'adj. 隐藏的', category: '托福词汇' },
  { word: 'hide', phonetic: '/haɪd/', meaning: 'v. 隐藏；n. 兽皮', category: '托福词汇' },
  { word: 'hideous', phonetic: '/ˈhɪdiəs/', meaning: 'adj. 丑陋的', category: 'GRE词汇' },
  { word: 'hiding', phonetic: '/ˈhaɪdɪŋ/', meaning: 'n. 躲藏', category: '托福词汇' },
  { word: 'hierarchy', phonetic: '/ˈhaɪərɑːki/', meaning: 'n. 等级制度', category: '托福词汇' },
  { word: 'hieroglyphic', phonetic: '/ˌhaɪərəˈɡlɪfɪk/', meaning: 'n. 象形文字', category: 'GRE词汇' },
  { word: 'high', phonetic: '/haɪ/', meaning: 'adj. 高的；adv. 高', category: '托福词汇' },
  { word: 'highland', phonetic: '/ˈhaɪlənd/', meaning: 'n. 高地', category: '托福词汇' },
  { word: 'highlight', phonetic: '/ˈhaɪlaɪt/', meaning: 'v. 突出；n. 亮点', category: '托福词汇' },
  { word: 'highly', phonetic: '/ˈhaɪli/', meaning: 'adv. 高度地', category: '托福词汇' },
  { word: 'highway', phonetic: '/ˈhaɪweɪ/', meaning: 'n. 公路', category: '托福词汇' },
  { word: 'hijack', phonetic: '/ˈhaɪdʒæk/', meaning: 'v. 劫持', category: '托福词汇' },
  { word: 'hike', phonetic: '/haɪk/', meaning: 'v. 远足；n. 远足', category: '托福词汇' },
  { word: 'hiker', phonetic: '/ˈhaɪkər/', meaning: 'n. 远足者', category: '托福词汇' },
  { word: 'hilarious', phonetic: '/hɪˈleəriəs/', meaning: 'adj. 欢闹的；滑稽的', category: '托福词汇' },
  { word: 'hilarity', phonetic: '/hɪˈlærəti/', meaning: 'n. 欢闹', category: 'GRE词汇' },
  { word: 'hill', phonetic: '/hɪl/', meaning: 'n. 小山', category: '托福词汇' },
  { word: 'hilly', phonetic: '/ˈhɪli/', meaning: 'adj. 多山的', category: '托福词汇' },
  { word: 'hinder', phonetic: '/ˈhɪndər/', meaning: 'v. 阻碍', category: '托福词汇' },
  { word: 'hindrance', phonetic: '/ˈhɪndrəns/', meaning: 'n. 阻碍', category: '托福词汇' },
  { word: 'hinge', phonetic: '/hɪndʒ/', meaning: 'n. 铰链；v. 依附', category: '托福词汇' },
  { word: 'hint', phonetic: '/hɪnt/', meaning: 'n. 暗示；v. 暗示', category: '托福词汇' },
  { word: 'hip', phonetic: '/hɪp/', meaning: 'n. 臀部', category: '托福词汇' },
  { word: 'hippopotamus', phonetic: '/ˌhɪpəˈpɒtəməs/', meaning: 'n. 河马', category: '托福词汇' },
  { word: 'hire', phonetic: '/haɪər/', meaning: 'v. 雇用；n. 租金', category: '托福词汇' },
  { word: 'hiring', phonetic: '/ˈhaɪərɪŋ/', meaning: 'n. 雇用', category: '商务词汇' },
  { word: 'historian', phonetic: '/hɪˈstɔːriən/', meaning: 'n. 历史学家', category: '托福词汇' },
  { word: 'historic', phonetic: '/hɪˈstɒrɪk/', meaning: 'adj. 历史上著名的', category: '托福词汇' },
  { word: 'historical', phonetic: '/hɪˈstɒrɪkl/', meaning: 'adj. 历史的', category: '托福词汇' },
  { word: 'history', phonetic: '/ˈhɪstri/', meaning: 'n. 历史', category: '托福词汇' },
  { word: 'hit', phonetic: '/hɪt/', meaning: 'v. 打击；n. 打击', category: '托福词汇' },
  { word: 'hitch', phonetic: '/hɪtʃ/', meaning: 'v. 搭便车；n. 故障', category: 'GRE词汇' },
  { word: 'hither', phonetic: '/ˈhɪðər/', meaning: 'adv. 向这里', category: 'GRE词汇' },
  { word: 'hive', phonetic: '/haɪv/', meaning: 'n. 蜂房', category: '托福词汇' },
  { word: 'hoard', phonetic: '/hɔːd/', meaning: 'v. 囤积；n. 囤积物', category: 'GRE词汇' },
  { word: 'hoarse', phonetic: '/hɔːs/', meaning: 'adj. 嘶哑的', category: 'GRE词汇' },
  { word: 'hoax', phonetic: '/həʊks/', meaning: 'n. 恶作剧；v. 欺骗', category: 'GRE词汇' },
  { word: 'hobby', phonetic: '/ˈhɒbi/', meaning: 'n. 爱好', category: '托福词汇' },
  { word: 'hockey', phonetic: '/ˈhɒki/', meaning: 'n. 曲棍球', category: '托福词汇' },
  { word: 'hoe', phonetic: '/həʊ/', meaning: 'n. 锄头；v. 锄地', category: 'GRE词汇' },
  { word: 'hog', phonetic: '/hɒɡ/', meaning: 'n. 猪；v. 独占', category: 'GRE词汇' },
  { word: 'hoist', phonetic: '/hɔɪst/', meaning: 'v. 升起；n. 起重机', category: '托福词汇' },
  { word: 'hold', phonetic: '/həʊld/', meaning: 'v. 拿住；n. 抓住', category: '托福词汇' },
  { word: 'holder', phonetic: '/ˈhəʊldər/', meaning: 'n. 持有者', category: '托福词汇' },
  { word: 'holding', phonetic: '/ˈhəʊldɪŋ/', meaning: 'n. 持有物', category: '商务词汇' },
  { word: 'hole', phonetic: '/həʊl/', meaning: 'n. 洞', category: '托福词汇' },
  { word: 'holiday', phonetic: '/ˈhɒlədeɪ/', meaning: 'n. 假日', category: '托福词汇' },
  { word: 'hollow', phonetic: '/ˈhɒləʊ/', meaning: 'adj. 空的；v. 挖空', category: '托福词汇' },
  { word: 'holly', phonetic: '/ˈhɒli/', meaning: 'n. 冬青', category: 'GRE词汇' },
  { word: 'holocaust', phonetic: '/ˈhɒləkɔːst/', meaning: 'n. 大屠杀', category: 'GRE词汇' },
  { word: 'hologram', phonetic: '/ˈhɒləɡræm/', meaning: 'n. 全息图', category: '科技词汇' },
  { word: 'holy', phonetic: '/ˈhəʊli/', meaning: 'adj. 神圣的', category: '托福词汇' },
  { word: 'homage', phonetic: '/ˈhɒmɪdʒ/', meaning: 'n. 敬意', category: 'GRE词汇' },
  { word: 'home', phonetic: '/həʊm/', meaning: 'n. 家；adv. 在家', category: '托福词汇' },
  { word: 'homecoming', phonetic: '/ˈhəʊmkʌmɪŋ/', meaning: 'n. 归国；返校节', category: '托福词汇' },
  { word: 'homeless', phonetic: '/ˈhəʊmləs/', meaning: 'adj. 无家可归的', category: '托福词汇' },
  { word: 'homely', phonetic: '/ˈhəʊmli/', meaning: 'adj. 朴素的；平凡的', category: 'GRE词汇' },
  { word: 'homemade', phonetic: '/ˌhəʊmˈmeɪd/', meaning: 'adj. 自制的', category: '托福词汇' },
  { word: 'homesick', phonetic: '/ˈhəʊmsɪk/', meaning: 'adj. 想家的', category: '托福词汇' },
  { word: 'homespun', phonetic: '/ˈhəʊmspʌn/', meaning: 'adj. 朴素的；手工的', category: 'GRE词汇' },
  { word: 'hometown', phonetic: '/ˈhəʊmtaʊn/', meaning: 'n. 故乡', category: '托福词汇' },
  { word: 'homeward', phonetic: '/ˈhəʊmwəd/', meaning: 'adv. 向家地', category: '托福词汇' },
  { word: 'homework', phonetic: '/ˈhəʊmwɜːk/', meaning: 'n. 家庭作业', category: '托福词汇' },
  { word: 'homicide', phonetic: '/ˈhɒmɪsaɪd/', meaning: 'n. 杀人', category: '法律词汇' },
  { word: 'homogeneous', phonetic: '/ˌhɒməˈdʒiːniəs/', meaning: 'adj. 同质的', category: 'GRE词汇' },
  { word: 'honest', phonetic: '/ˈɒnɪst/', meaning: 'adj. 诚实的', category: '托福词汇' },
  { word: 'honesty', phonetic: '/ˈɒnəsti/', meaning: 'n. 诚实', category: '托福词汇' },
  { word: 'honey', phonetic: '/ˈhʌni/', meaning: 'n. 蜂蜜', category: '托福词汇' },
  { word: 'honeymoon', phonetic: '/ˈhʌnimuːn/', meaning: 'n. 蜜月', category: '托福词汇' },
  { word: 'honor', phonetic: '/ˈɒnər/', meaning: 'n. 荣誉；v. 尊敬', category: '托福词汇' },
  { word: 'honorable', phonetic: '/ˈɒnərəbl/', meaning: 'adj. 光荣的', category: '托福词汇' },
  { word: 'hood', phonetic: '/hʊd/', meaning: 'n. 头巾；引擎盖', category: '托福词汇' },
  { word: 'hoof', phonetic: '/huːf/', meaning: 'n. 蹄', category: 'GRE词汇' },
  { word: 'hook', phonetic: '/hʊk/', meaning: 'n. 钩子；v. 钩住', category: '托福词汇' },
  { word: 'hooked', phonetic: '/hʊkt/', meaning: 'adj. 钩状的；着迷的', category: '托福词汇' },
  { word: 'hooligan', phonetic: '/ˈhuːlɪɡən/', meaning: 'n. 流氓', category: 'GRE词汇' },
  { word: 'hoop', phonetic: '/huːp/', meaning: 'n. 箍；铁环', category: 'GRE词汇' },
  { word: 'hoot', phonetic: '/huːt/', meaning: 'n. 叫声；v. 叫喊', category: 'GRE词汇' },
  { word: 'hop', phonetic: '/hɒp/', meaning: 'v. 跳跃；n. 跳跃', category: '托福词汇' },
  { word: 'hope', phonetic: '/həʊp/', meaning: 'n. 希望；v. 希望', category: '托福词汇' },
  { word: 'hopeful', phonetic: '/ˈhəʊpfl/', meaning: 'adj. 有希望的', category: '托福词汇' },
  { word: 'hopeless', phonetic: '/ˈhəʊpləs/', meaning: 'adj. 绝望的', category: '托福词汇' },
  { word: 'horizon', phonetic: '/həˈraɪzn/', meaning: 'n. 地平线；眼界', category: '托福词汇' },
  { word: 'horizontal', phonetic: '/ˌhɒrɪˈzɒntl/', meaning: 'adj. 水平的', category: '托福词汇' },
  { word: 'hormone', phonetic: '/ˈhɔːməʊn/', meaning: 'n. 激素', category: '医学词汇' },
  { word: 'horn', phonetic: '/hɔːn/', meaning: 'n. 角；喇叭', category: '托福词汇' },
  { word: 'horny', phonetic: '/ˈhɔːni/', meaning: 'adj. 角质的', category: 'GRE词汇' },
  { word: 'horrible', phonetic: '/ˈhɒrəbl/', meaning: 'adj. 可怕的', category: '托福词汇' },
  { word: 'horrid', phonetic: '/ˈhɒrɪd/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'horrific', phonetic: '/həˈrɪfɪk/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'horrify', phonetic: '/ˈhɒrɪfaɪ/', meaning: 'v. 使恐惧', category: 'GRE词汇' },
  { word: 'horror', phonetic: '/ˈhɒrər/', meaning: 'n. 恐惧', category: '托福词汇' },
  { word: 'horse', phonetic: '/hɔːs/', meaning: 'n. 马', category: '托福词汇' },
  { word: 'horseback', phonetic: '/ˈhɔːsbæk/', meaning: 'n. 马背', category: '托福词汇' },
  { word: 'horsepower', phonetic: '/ˈhɔːspaʊər/', meaning: 'n. 马力', category: '科技词汇' },
  { word: 'horseradish', phonetic: '/ˈhɔːsrædɪʃ/', meaning: 'n. 辣根', category: 'GRE词汇' },
  { word: 'hose', phonetic: '/həʊz/', meaning: 'n. 软管；长筒袜', category: '托福词汇' },
  { word: 'hospitable', phonetic: '/hɒˈspɪtəbl/', meaning: 'adj. 好客的', category: 'GRE词汇' },
  { word: 'hospital', phonetic: '/ˈhɒspɪtl/', meaning: 'n. 医院', category: '托福词汇' },
  { word: 'hospitality', phonetic: '/ˌhɒspɪˈtæləti/', meaning: 'n. 好客', category: '托福词汇' },
  { word: 'hospitalize', phonetic: '/ˈhɒspɪtəlaɪz/', meaning: 'v. 送入医院', category: '医学词汇' },
  { word: 'host', phonetic: '/həʊst/', meaning: 'n. 主人；v. 主办', category: '托福词汇' },
  { word: 'hostage', phonetic: '/ˈhɒstɪdʒ/', meaning: 'n. 人质', category: '托福词汇' },
  { word: 'hostel', phonetic: '/ˈhɒstl/', meaning: 'n. 旅社', category: '托福词汇' },
  { word: 'hostile', phonetic: '/ˈhɒstaɪl/', meaning: 'adj. 敌对的', category: '托福词汇' },
  { word: 'hostility', phonetic: '/hɒˈstɪləti/', meaning: 'n. 敌意', category: '托福词汇' },
  { word: 'hot', phonetic: '/hɒt/', meaning: 'adj. 热的', category: '托福词汇' },
  { word: 'hotdog', phonetic: '/ˈhɒtdɒɡ/', meaning: 'n. 热狗', category: '托福词汇' },
  { word: 'hotel', phonetic: '/həʊˈtel/', meaning: 'n. 旅馆', category: '托福词汇' },
  { word: 'hotly', phonetic: '/ˈhɒtli/', meaning: 'adv. 热烈地；愤怒地', category: 'GRE词汇' },
  { word: 'hound', phonetic: '/haʊnd/', meaning: 'n. 猎犬；v. 追捕', category: 'GRE词汇' },
  { word: 'hour', phonetic: '/ˈaʊər/', meaning: 'n. 小时', category: '托福词汇' },
  { word: 'house', phonetic: '/haʊs/', meaning: 'n. 房屋；v. 给...提供住房', category: '托福词汇' },
  { word: 'household', phonetic: '/ˈhaʊshəʊld/', meaning: 'n. 家庭；adj. 家庭的', category: '托福词汇' },
  { word: 'housewife', phonetic: '/ˈhaʊswaɪf/', meaning: 'n. 家庭主妇', category: '托福词汇' },
  { word: 'housework', phonetic: '/ˈhaʊswɜːk/', meaning: 'n. 家务', category: '托福词汇' },
  { word: 'hover', phonetic: '/ˈhɒvər/', meaning: 'v. 盘旋；徘徊', category: '托福词汇' },
  { word: 'however', phonetic: '/haʊˈevər/', meaning: 'adv. 然而', category: '托福词汇' },
  { word: 'howl', phonetic: '/haʊl/', meaning: 'v. 嚎叫；n. 嚎叫', category: '托福词汇' },
  { word: 'hub', phonetic: '/hʌb/', meaning: 'n. 中心；轮毂', category: '托福词汇' },
  { word: 'hubby', phonetic: '/ˈhʌbi/', meaning: 'n. 丈夫', category: '日常词汇' },
  { word: 'hubris', phonetic: '/ˈhjuːbrɪs/', meaning: 'n. 傲慢', category: 'GRE词汇' },
  { word: 'huddle', phonetic: '/ˈhʌdl/', meaning: 'v. 挤在一起；n. 挤在一起', category: 'GRE词汇' },
  { word: 'hue', phonetic: '/hjuː/', meaning: 'n. 色调', category: 'GRE词汇' },
  { word: 'huff', phonetic: '/hʌf/', meaning: 'n. 愤怒；v. 激怒', category: 'GRE词汇' },
  { word: 'hug', phonetic: '/hʌɡ/', meaning: 'v. 拥抱；n. 拥抱', category: '托福词汇' },
  { word: 'huge', phonetic: '/hjuːdʒ/', meaning: 'adj. 巨大的', category: '托福词汇' },
  { word: 'hull', phonetic: '/hʌl/', meaning: 'n. 船体；外壳', category: 'GRE词汇' },
  { word: 'hum', phonetic: '/hʌm/', meaning: 'v. 哼唱；n. 嗡嗡声', category: '托福词汇' },
  { word: 'human', phonetic: '/ˈhjuːmən/', meaning: 'n. 人类；adj. 人类的', category: '托福词汇' },
  { word: 'humane', phonetic: '/hjuːˈmeɪn/', meaning: 'adj. 人道的', category: '托福词汇' },
  { word: 'humanitarian', phonetic: '/hjuːˌmænɪˈteəriən/', meaning: 'adj. 人道主义的；n. 人道主义者', category: '托福词汇' },
  { word: 'humanity', phonetic: '/hjuːˈmænəti/', meaning: 'n. 人类；人性', category: '托福词汇' },
  { word: 'humble', phonetic: '/ˈhʌmbl/', meaning: 'adj. 谦虚的', category: '托福词汇' },
  { word: 'humid', phonetic: '/ˈhjuːmɪd/', meaning: 'adj. 潮湿的', category: '托福词汇' },
  { word: 'humidity', phonetic: '/hjuːˈmɪdəti/', meaning: 'n. 湿度', category: '托福词汇' },
  { word: 'humidify', phonetic: '/hjuːˈmɪdɪfaɪ/', meaning: 'v. 加湿', category: '科技词汇' },
  { word: 'humiliate', phonetic: '/hjuːˈmɪlieɪt/', meaning: 'v. 使丢脸', category: 'GRE词汇' },
  { word: 'humiliation', phonetic: '/hjuːˌmɪliˈeɪʃn/', meaning: 'n. 羞辱', category: 'GRE词汇' },
  { word: 'humility', phonetic: '/hjuːˈmɪləti/', meaning: 'n. 谦卑', category: 'GRE词汇' },
  { word: 'hummingbird', phonetic: '/ˈhʌmɪŋbɜːd/', meaning: 'n. 蜂鸟', category: '托福词汇' },
  { word: 'humor', phonetic: '/ˈhjuːmər/', meaning: 'n. 幽默', category: '托福词汇' },
  { word: 'humorous', phonetic: '/ˈhjuːmərəs/', meaning: 'adj. 幽默的', category: '托福词汇' },
  { word: 'hump', phonetic: '/hʌmp/', meaning: 'n. 驼峰；v. 隆起', category: 'GRE词汇' },
  { word: 'humdrum', phonetic: '/ˈhʌmdrʌm/', meaning: 'adj. 单调的', category: 'GRE词汇' },
  { word: 'hunch', phonetic: '/hʌntʃ/', meaning: 'n. 直觉；v. 弯腰', category: 'GRE词汇' },
  { word: 'hundred', phonetic: '/ˈhʌndrəd/', meaning: 'num. 百', category: '托福词汇' },
  { word: 'hunger', phonetic: '/ˈhʌŋɡər/', meaning: 'n. 饥饿', category: '托福词汇' },
  { word: 'hungry', phonetic: '/ˈhʌŋɡri/', meaning: 'adj. 饥饿的', category: '托福词汇' },
  { word: 'hunt', phonetic: '/hʌnt/', meaning: 'v. 打猎；n. 打猎', category: '托福词汇' },
  { word: 'hunter', phonetic: '/ˈhʌntər/', meaning: 'n. 猎人', category: '托福词汇' },
  { word: 'hunting', phonetic: '/ˈhʌntɪŋ/', meaning: 'n. 打猎', category: '托福词汇' },
  { word: 'hurdle', phonetic: '/ˈhɜːdl/', meaning: 'n. 障碍；v. 跳过', category: '托福词汇' },
  { word: 'hurl', phonetic: '/hɜːl/', meaning: 'v. 猛投', category: 'GRE词汇' },
  { word: 'hurray', phonetic: '/hʊˈreɪ/', meaning: 'int. 欢呼', category: '日常词汇' },
  { word: 'hurricane', phonetic: '/ˈhʌrɪkən/', meaning: 'n. 飓风', category: '托福词汇' },
  { word: 'hurried', phonetic: '/ˈhʌrid/', meaning: 'adj. 匆忙的', category: '托福词汇' },
  { word: 'hurry', phonetic: '/ˈhʌri/', meaning: 'v. 匆忙；n. 匆忙', category: '托福词汇' },
  { word: 'hurt', phonetic: '/hɜːt/', meaning: 'v. 伤害；n. 伤害', category: '托福词汇' },
  { word: 'hurtle', phonetic: '/ˈhɜːtl/', meaning: 'v. 猛冲', category: 'GRE词汇' },
  { word: 'husband', phonetic: '/ˈhʌzbənd/', meaning: 'n. 丈夫', category: '托福词汇' },
  { word: 'hush', phonetic: '/hʌʃ/', meaning: 'v. 使安静；n. 安静', category: 'GRE词汇' },
  { word: 'husk', phonetic: '/hʌsk/', meaning: 'n. 外壳', category: 'GRE词汇' },
  { word: 'husky', phonetic: '/ˈhʌski/', meaning: 'adj. 嘶哑的；强壮的', category: 'GRE词汇' },
  { word: 'hustle', phonetic: '/ˈhʌsl/', meaning: 'v. 推搡；n. 忙碌', category: 'GRE词汇' },
  { word: 'hut', phonetic: '/hʌt/', meaning: 'n. 小屋', category: '托福词汇' },
  { word: 'hutch', phonetic: '/hʌtʃ/', meaning: 'n. 笼子', category: 'GRE词汇' },
  { word: 'hybrid', phonetic: '/ˈhaɪbrɪd/', meaning: 'n. 混合物；adj. 混合的', category: '托福词汇' },
  { word: 'hydraulic', phonetic: '/haɪˈdrɔːlɪk/', meaning: 'adj. 液压的', category: '科技词汇' },
  { word: 'hydrocarbon', phonetic: '/ˌhaɪdrəʊˈkɑːbən/', meaning: 'n. 碳氢化合物', category: '科技词汇' },
  { word: 'hydroelectric', phonetic: '/ˌhaɪdrəʊɪˈlektrɪk/', meaning: 'adj. 水力发电的', category: '科技词汇' },
  { word: 'hydrogen', phonetic: '/ˈhaɪdrədʒən/', meaning: 'n. 氢', category: '科技词汇' },
  { word: 'hygiene', phonetic: '/ˈhaɪdʒiːn/', meaning: 'n. 卫生', category: '医学词汇' },
  { word: 'hygienic', phonetic: '/haɪˈdʒiːnɪk/', meaning: 'adj. 卫生的', category: '医学词汇' },
  { word: 'hymn', phonetic: '/hɪm/', meaning: 'n. 赞美诗', category: 'GRE词汇' },
  { word: 'hyperactive', phonetic: '/ˌhaɪpərˈæktɪv/', meaning: 'adj. 多动的', category: '医学词汇' },
  { word: 'hyperbole', phonetic: '/haɪˈpɜːbəli/', meaning: 'n. 夸张法', category: 'GRE词汇' },
  { word: 'hypercritical', phonetic: '/ˌhaɪpəˈkrɪtɪkl/', meaning: 'adj. 吹毛求疵的', category: 'GRE词汇' },
  { word: 'hypersensitive', phonetic: '/ˌhaɪpəˈsensətɪv/', meaning: 'adj. 过敏的', category: 'GRE词汇' },
  { word: 'hypertension', phonetic: '/ˌhaɪpəˈtenʃn/', meaning: 'n. 高血压', category: '医学词汇' },
  { word: 'hypnosis', phonetic: '/hɪpˈnəʊsɪs/', meaning: 'n. 催眠', category: '医学词汇' },
  { word: 'hypnotic', phonetic: '/hɪpˈnɒtɪk/', meaning: 'adj. 催眠的', category: 'GRE词汇' },
  { word: 'hypnotize', phonetic: '/ˈhɪpnətaɪz/', meaning: 'v. 催眠', category: 'GRE词汇' },
  { word: 'hypocrisy', phonetic: '/hɪˈpɒkrəsi/', meaning: 'n. 伪善', category: 'GRE词汇' },
  { word: 'hypocrite', phonetic: '/ˈhɪpəkrɪt/', meaning: 'n. 伪君子', category: 'GRE词汇' },
  { word: 'hypodermic', phonetic: '/ˌhaɪpəˈdɜːmɪk/', meaning: 'adj. 皮下的', category: '医学词汇' },
  { word: 'hypotenuse', phonetic: '/haɪˈpɒtənjuːz/', meaning: 'n. 斜边', category: '科技词汇' },
  { word: 'hypothesis', phonetic: '/haɪˈpɒθəsɪs/', meaning: 'n. 假设', category: '托福词汇' },
  { word: 'hypothetical', phonetic: '/ˌhaɪpəˈθetɪkl/', meaning: 'adj. 假设的', category: '托福词汇' },
  { word: 'hysteria', phonetic: '/hɪˈstɪəriə/', meaning: 'n. 歇斯底里', category: '医学词汇' },
  { word: 'hysterical', phonetic: '/hɪˈsterɪkl/', meaning: 'adj. 歇斯底里的', category: 'GRE词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await fetchAllFromSupabase(
    supabase.from(WORDS_TABLE).select('word')
  );
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsGHI, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 G-H 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsGHI.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsGHI, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
