// N-R字母开头的单词 - Part 1/4
import { getSupabaseClient } from '../src/storage/database/supabase-client';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsNR = [
  // N字母开头
  { word: 'nab', phonetic: '/næb/', meaning: 'v. 抓住', category: 'GRE词汇' },
  { word: 'nadir', phonetic: '/ˈneɪdɪər/', meaning: 'n. 最低点', category: 'GRE词汇' },
  { word: 'nag', phonetic: '/næɡ/', meaning: 'v. 唠叨；n. 唠叨', category: 'GRE词汇' },
  { word: 'nail', phonetic: '/neɪl/', meaning: 'n. 指甲；v. 钉住', category: '托福词汇' },
  { word: 'naive', phonetic: '/naɪˈiːv/', meaning: 'adj. 天真的', category: '托福词汇' },
  { word: 'naivety', phonetic: '/naɪˈiːvəti/', meaning: 'n. 天真', category: 'GRE词汇' },
  { word: 'naked', phonetic: '/ˈneɪkɪd/', meaning: 'adj. 裸体的', category: '托福词汇' },
  { word: 'name', phonetic: '/neɪm/', meaning: 'n. 名字；v. 命名', category: '托福词汇' },
  { word: 'nameless', phonetic: '/ˈneɪmləs/', meaning: 'adj. 无名的', category: 'GRE词汇' },
  { word: 'namely', phonetic: '/ˈneɪmli/', meaning: 'adv. 即', category: '托福词汇' },
  { word: 'namesake', phonetic: '/ˈneɪmseɪk/', meaning: 'n. 同名者', category: 'GRE词汇' },
  { word: 'nanny', phonetic: '/ˈnæni/', meaning: 'n. 保姆', category: '托福词汇' },
  { word: 'nap', phonetic: '/næp/', meaning: 'n. 小睡；v. 小睡', category: '托福词汇' },
  { word: 'napkin', phonetic: '/ˈnæpkɪn/', meaning: 'n. 餐巾', category: '托福词汇' },
  { word: 'narcissism', phonetic: '/ˈnɑːsɪsɪzəm/', meaning: 'n. 自恋', category: 'GRE词汇' },
  { word: 'narcissist', phonetic: '/ˈnɑːsɪsɪst/', meaning: 'n. 自恋者', category: 'GRE词汇' },
  { word: 'narcotic', phonetic: '/nɑːˈkɒtɪk/', meaning: 'n. 麻醉剂；adj. 麻醉的', category: '医学词汇' },
  { word: 'narrate', phonetic: '/nəˈreɪt/', meaning: 'v. 叙述', category: '托福词汇' },
  { word: 'narration', phonetic: '/nəˈreɪʃn/', meaning: 'n. 叙述', category: '托福词汇' },
  { word: 'narrative', phonetic: '/ˈnærətɪv/', meaning: 'n. 叙述；adj. 叙述的', category: '托福词汇' },
  { word: 'narrator', phonetic: '/nəˈreɪtər/', meaning: 'n. 叙述者', category: '托福词汇' },
  { word: 'narrow', phonetic: '/ˈnærəʊ/', meaning: 'adj. 狭窄的；v. 变窄', category: '托福词汇' },
  { word: 'narrowly', phonetic: '/ˈnærəʊli/', meaning: 'adv. 勉强地', category: '托福词汇' },
  { word: 'nasal', phonetic: '/ˈneɪzl/', meaning: 'adj. 鼻的', category: '医学词汇' },
  { word: 'nasty', phonetic: '/ˈnɑːsti/', meaning: 'adj. 令人讨厌的', category: '托福词汇' },
  { word: 'nation', phonetic: '/ˈneɪʃn/', meaning: 'n. 国家', category: '托福词汇' },
  { word: 'national', phonetic: '/ˈnæʃnəl/', meaning: 'adj. 国家的', category: '托福词汇' },
  { word: 'nationalism', phonetic: '/ˈnæʃnəlɪzəm/', meaning: 'n. 民族主义', category: 'GRE词汇' },
  { word: 'nationalist', phonetic: '/ˈnæʃnəlɪst/', meaning: 'n. 民族主义者', category: 'GRE词汇' },
  { word: 'nationality', phonetic: '/ˌnæʃəˈnæləti/', meaning: 'n. 国籍', category: '托福词汇' },
  { word: 'nationalize', phonetic: '/ˈnæʃnəlaɪz/', meaning: 'v. 国有化', category: 'GRE词汇' },
  { word: 'native', phonetic: '/ˈneɪtɪv/', meaning: 'adj. 本土的；n. 本地人', category: '托福词汇' },
  { word: 'nativity', phonetic: '/nəˈtɪvəti/', meaning: 'n. 出生', category: 'GRE词汇' },
  { word: 'natural', phonetic: '/ˈnætʃrəl/', meaning: 'adj. 自然的', category: '托福词汇' },
  { word: 'naturalism', phonetic: '/ˈnætʃrəlɪzəm/', meaning: 'n. 自然主义', category: 'GRE词汇' },
  { word: 'naturalist', phonetic: '/ˈnætʃrəlɪst/', meaning: 'n. 自然主义者', category: 'GRE词汇' },
  { word: 'naturalize', phonetic: '/ˈnætʃrəlaɪz/', meaning: 'v. 使入籍', category: 'GRE词汇' },
  { word: 'naturally', phonetic: '/ˈnætʃrəli/', meaning: 'adv. 自然地', category: '托福词汇' },
  { word: 'nature', phonetic: '/ˈneɪtʃər/', meaning: 'n. 自然；本性', category: '托福词汇' },
  { word: 'naught', phonetic: '/nɔːt/', meaning: 'n. 无', category: 'GRE词汇' },
  { word: 'naughty', phonetic: '/ˈnɔːti/', meaning: 'adj. 顽皮的', category: '托福词汇' },
  { word: 'nausea', phonetic: '/ˈnɔːziə/', meaning: 'n. 恶心', category: '医学词汇' },
  { word: 'nauseate', phonetic: '/ˈnɔːzieɪt/', meaning: 'v. 使恶心', category: 'GRE词汇' },
  { word: 'nauseous', phonetic: '/ˈnɔːziəs/', meaning: 'adj. 令人作呕的', category: 'GRE词汇' },
  { word: 'nautical', phonetic: '/ˈnɔːtɪkl/', meaning: 'adj. 航海的', category: 'GRE词汇' },
  { word: 'naval', phonetic: '/ˈneɪvl/', meaning: 'adj. 海军的', category: '托福词汇' },
  { word: 'navigate', phonetic: '/ˈnævɪɡeɪt/', meaning: 'v. 导航', category: '托福词汇' },
  { word: 'navigation', phonetic: '/ˌnævɪˈɡeɪʃn/', meaning: 'n. 导航', category: '托福词汇' },
  { word: 'navigator', phonetic: '/ˈnævɪɡeɪtər/', meaning: 'n. 导航员', category: '托福词汇' },
  { word: 'navy', phonetic: '/ˈneɪvi/', meaning: 'n. 海军', category: '托福词汇' },
  { word: 'nay', phonetic: '/neɪ/', meaning: 'adv. 不；n. 反对票', category: 'GRE词汇' },
  { word: 'near', phonetic: '/nɪər/', meaning: 'adj. 近的；adv. 近', category: '托福词汇' },
  { word: 'nearby', phonetic: '/ˈnɪəbaɪ/', meaning: 'adj. 附近的；adv. 在附近', category: '托福词汇' },
  { word: 'nearly', phonetic: '/ˈnɪəli/', meaning: 'adv. 几乎', category: '托福词汇' },
  { word: 'nearness', phonetic: '/ˈnɪənəs/', meaning: 'n. 接近', category: 'GRE词汇' },
  { word: 'neat', phonetic: '/niːt/', meaning: 'adj. 整洁的', category: '托福词汇' },
  { word: 'neatly', phonetic: '/ˈniːtli/', meaning: 'adv. 整洁地', category: '托福词汇' },
  { word: 'nebula', phonetic: '/ˈnebjələ/', meaning: 'n. 星云', category: 'GRE词汇' },
  { word: 'nebular', phonetic: '/ˈnebjələr/', meaning: 'adj. 星云的', category: 'GRE词汇' },
  { word: 'nebulous', phonetic: '/ˈnebjələs/', meaning: 'adj. 模糊的', category: 'GRE词汇' },
  { word: 'necessary', phonetic: '/ˈnesəsəri/', meaning: 'adj. 必要的；n. 必需品', category: '托福词汇' },
  { word: 'necessitate', phonetic: '/nəˈsesɪteɪt/', meaning: 'v. 使成为必要', category: 'GRE词汇' },
  { word: 'necessity', phonetic: '/nəˈsesəti/', meaning: 'n. 必要性', category: '托福词汇' },
  { word: 'neck', phonetic: '/nek/', meaning: 'n. 脖子', category: '托福词汇' },
  { word: 'necklace', phonetic: '/ˈnekləs/', meaning: 'n. 项链', category: '托福词汇' },
  { word: 'necktie', phonetic: '/ˈnektaɪ/', meaning: 'n. 领带', category: '托福词汇' },
  { word: 'necromancer', phonetic: '/ˈnekrəʊmænsər/', meaning: 'n. 巫师', category: 'GRE词汇' },
  { word: 'necropolis', phonetic: '/neˈkrɒpəlɪs/', meaning: 'n. 大墓地', category: 'GRE词汇' },
  { word: 'necrosis', phonetic: '/neˈkrəʊsɪs/', meaning: 'n. 坏死', category: '医学词汇' },
  { word: 'nectar', phonetic: '/ˈnektər/', meaning: 'n. 花蜜', category: 'GRE词汇' },
  { word: 'need', phonetic: '/niːd/', meaning: 'v. 需要；n. 需要', category: '托福词汇' },
  { word: 'needful', phonetic: '/ˈniːdfl/', meaning: 'adj. 需要的', category: 'GRE词汇' },
  { word: 'needle', phonetic: '/ˈniːdl/', meaning: 'n. 针', category: '托福词汇' },
  { word: 'needless', phonetic: '/ˈniːdləs/', meaning: 'adj. 不必要的', category: '托福词汇' },
  { word: 'needy', phonetic: '/ˈniːdi/', meaning: 'adj. 贫困的', category: '托福词汇' },
  { word: 'negate', phonetic: '/nɪˈɡeɪt/', meaning: 'v. 否定', category: 'GRE词汇' },
  { word: 'negation', phonetic: '/nɪˈɡeɪʃn/', meaning: 'n. 否定', category: 'GRE词汇' },
  { word: 'negative', phonetic: '/ˈneɡətɪv/', meaning: 'adj. 消极的；n. 否定', category: '托福词汇' },
  { word: 'neglect', phonetic: '/nɪˈɡlekt/', meaning: 'v. 忽视；n. 忽视', category: '托福词汇' },
  { word: 'negligence', phonetic: '/ˈneɡlɪdʒəns/', meaning: 'n. 疏忽', category: '法律词汇' },
  { word: 'negligent', phonetic: '/ˈneɡlɪdʒənt/', meaning: 'adj. 疏忽的', category: 'GRE词汇' },
  { word: 'negligible', phonetic: '/ˈneɡlɪdʒəbl/', meaning: 'adj. 可忽略的', category: 'GRE词汇' },
  { word: 'negotiable', phonetic: '/nɪˈɡəʊʃiəbl/', meaning: 'adj. 可协商的', category: '商务词汇' },
  { word: 'negotiate', phonetic: '/nɪˈɡəʊʃieɪt/', meaning: 'v. 谈判', category: '托福词汇' },
  { word: 'negotiation', phonetic: '/nɪˌɡəʊʃiˈeɪʃn/', meaning: 'n. 谈判', category: '托福词汇' },
  { word: 'negotiator', phonetic: '/nɪˈɡəʊʃieɪtər/', meaning: 'n. 谈判者', category: '托福词汇' },
  { word: 'negress', phonetic: '/ˈniːɡrəs/', meaning: 'n. 黑人女性', category: 'GRE词汇' },
  { word: 'negro', phonetic: '/ˈniːɡrəʊ/', meaning: 'n. 黑人', category: '托福词汇' },
  { word: 'neigh', phonetic: '/neɪ/', meaning: 'v. 马嘶；n. 马嘶声', category: 'GRE词汇' },
  { word: 'neighbor', phonetic: '/ˈneɪbər/', meaning: 'n. 邻居', category: '托福词汇' },
  { word: 'neighborhood', phonetic: '/ˈneɪbərhʊd/', meaning: 'n. 社区', category: '托福词汇' },
  { word: 'neighboring', phonetic: '/ˈneɪbərɪŋ/', meaning: 'adj. 邻近的', category: '托福词汇' },
  { word: 'neither', phonetic: '/ˈnaɪðər/', meaning: 'adj. 两者都不的；conj. 也不', category: '托福词汇' },
  { word: 'nemesis', phonetic: '/ˈneməsɪs/', meaning: 'n. 报应', category: 'GRE词汇' },
  { word: 'neon', phonetic: '/ˈniːɒn/', meaning: 'n. 氖', category: '科技词汇' },
  { word: 'neophyte', phonetic: '/ˈniːəfaɪt/', meaning: 'n. 新手', category: 'GRE词汇' },
  { word: 'nephew', phonetic: '/ˈnefjuː/', meaning: 'n. 侄子', category: '托福词汇' },
  { word: 'nepotism', phonetic: '/ˈnepətɪzəm/', meaning: 'n. 裙带关系', category: 'GRE词汇' },
  { word: 'nerve', phonetic: '/nɜːv/', meaning: 'n. 神经；勇气', category: '托福词汇' },
  { word: 'nerveless', phonetic: '/ˈnɜːvləs/', meaning: 'adj. 无力的', category: 'GRE词汇' },
  { word: 'nervous', phonetic: '/ˈnɜːvəs/', meaning: 'adj. 紧张的', category: '托福词汇' },
  { word: 'nervousness', phonetic: '/ˈnɜːvəsnəs/', meaning: 'n. 紧张', category: '托福词汇' },
  { word: 'nest', phonetic: '/nest/', meaning: 'n. 巢；v. 筑巢', category: '托福词汇' },
  { word: 'nestle', phonetic: '/ˈnesl/', meaning: 'v. 依偎', category: 'GRE词汇' },
  { word: 'nestling', phonetic: '/ˈneslɪŋ/', meaning: 'n. 雏鸟', category: 'GRE词汇' },
  { word: 'net', phonetic: '/net/', meaning: 'n. 网；adj. 净的', category: '托福词汇' },
  { word: 'nettle', phonetic: '/ˈnetl/', meaning: 'n. 荨麻；v. 激怒', category: 'GRE词汇' },
  { word: 'network', phonetic: '/ˈnetwɜːk/', meaning: 'n. 网络', category: '托福词汇' },
  { word: 'neural', phonetic: '/ˈnjʊərəl/', meaning: 'adj. 神经的', category: '医学词汇' },
  { word: 'neurasthenia', phonetic: '/ˌnjʊərəsˈθiːniə/', meaning: 'n. 神经衰弱', category: '医学词汇' },
  { word: 'neurologist', phonetic: '/njʊəˈrɒlədʒɪst/', meaning: 'n. 神经学家', category: '医学词汇' },
  { word: 'neurology', phonetic: '/njʊˈrɒlədʒi/', meaning: 'n. 神经学', category: '医学词汇' },
  { word: 'neuron', phonetic: '/ˈnjʊərɒn/', meaning: 'n. 神经元', category: '医学词汇' },
  { word: 'neurosis', phonetic: '/njʊˈrəʊsɪs/', meaning: 'n. 神经症', category: '医学词汇' },
  { word: 'neurotic', phonetic: '/njʊˈrɒtɪk/', meaning: 'adj. 神经质的', category: 'GRE词汇' },
  { word: 'neutral', phonetic: '/ˈnjuːtrəl/', meaning: 'adj. 中立的', category: '托福词汇' },
  { word: 'neutrality', phonetic: '/njuːˈtræləti/', meaning: 'n. 中立', category: 'GRE词汇' },
  { word: 'neutralize', phonetic: '/ˈnjuːtrəlaɪz/', meaning: 'v. 中和', category: 'GRE词汇' },
  { word: 'neutron', phonetic: '/ˈnjuːtrɒn/', meaning: 'n. 中子', category: '科技词汇' },
  { word: 'never', phonetic: '/ˈnevər/', meaning: 'adv. 从不', category: '托福词汇' },
  { word: 'nevertheless', phonetic: '/ˌnevəðəˈles/', meaning: 'adv. 然而', category: '托福词汇' },
  { word: 'new', phonetic: '/njuː/', meaning: 'adj. 新的', category: '托福词汇' },
  { word: 'newborn', phonetic: '/ˈnjuːbɔːn/', meaning: 'adj. 新生的', category: '托福词汇' },
  { word: 'newcomer', phonetic: '/ˈnjuːkʌmər/', meaning: 'n. 新来者', category: '托福词汇' },
  { word: 'newfound', phonetic: '/ˈnjuːfaʊnd/', meaning: 'adj. 新发现的', category: 'GRE词汇' },
  { word: 'newly', phonetic: '/ˈnjuːli/', meaning: 'adv. 新近', category: '托福词汇' },
  { word: 'newness', phonetic: '/ˈnjuːnəs/', meaning: 'n. 新奇', category: 'GRE词汇' },
  { word: 'news', phonetic: '/njuːz/', meaning: 'n. 新闻', category: '托福词汇' },
  { word: 'newsagent', phonetic: '/ˈnjuːzeɪdʒənt/', meaning: 'n. 报刊经销商', category: 'GRE词汇' },
  { word: 'newsboy', phonetic: '/ˈnjuːzbɔɪ/', meaning: 'n. 报童', category: 'GRE词汇' },
  { word: 'newscast', phonetic: '/ˈnjuːzkɑːst/', meaning: 'n. 新闻广播', category: 'GRE词汇' },
  { word: 'newspaper', phonetic: '/ˈnjuːzpeɪpər/', meaning: 'n. 报纸', category: '托福词汇' },
  { word: 'newsreel', phonetic: '/ˈnjuːzriːl/', meaning: 'n. 新闻短片', category: 'GRE词汇' },
  { word: 'newsstand', phonetic: '/ˈnjuːzstænd/', meaning: 'n. 报摊', category: 'GRE词汇' },
  { word: 'newsworthy', phonetic: '/ˈnjuːzwɜːði/', meaning: 'adj. 有新闻价值的', category: 'GRE词汇' },
  { word: 'newsy', phonetic: '/ˈnjuːzi/', meaning: 'adj. 新闻多的', category: 'GRE词汇' },
  { word: 'newt', phonetic: '/njuːt/', meaning: 'n. 蝾螈', category: 'GRE词汇' },
  { word: 'next', phonetic: '/nekst/', meaning: 'adj. 下一个的；adv. 接下来', category: '托福词汇' },
  { word: 'nibble', phonetic: '/ˈnɪbl/', meaning: 'v. 小口咬', category: 'GRE词汇' },
  { word: 'nice', phonetic: '/naɪs/', meaning: 'adj. 好的', category: '托福词汇' },
  { word: 'nicely', phonetic: '/ˈnaɪsli/', meaning: 'adv. 很好地', category: '托福词汇' },
  { word: 'nicety', phonetic: '/ˈnaɪsəti/', meaning: 'n. 精确', category: 'GRE词汇' },
  { word: 'niche', phonetic: '/nɪʃ/', meaning: 'n. 壁龛；合适的位置', category: 'GRE词汇' },
  { word: 'nick', phonetic: '/nɪk/', meaning: 'n. 刻痕；v. 刻痕', category: 'GRE词汇' },
  { word: 'nickel', phonetic: '/ˈnɪkl/', meaning: 'n. 镍；五分镍币', category: '托福词汇' },
  { word: 'nickname', phonetic: '/ˈnɪkneɪm/', meaning: 'n. 绰号；v. 给...起绰号', category: '托福词汇' },
  { word: 'nicotine', phonetic: '/ˈnɪkətiːn/', meaning: 'n. 尼古丁', category: '医学词汇' },
  { word: 'niece', phonetic: '/niːs/', meaning: 'n. 侄女', category: '托福词汇' },
  { word: 'niggard', phonetic: '/ˈnɪɡəd/', meaning: 'n. 吝啬鬼', category: 'GRE词汇' },
  { word: 'niggardly', phonetic: '/ˈnɪɡədli/', meaning: 'adj. 吝啬的', category: 'GRE词汇' },
  { word: 'niggle', phonetic: '/ˈnɪɡl/', meaning: 'v. 挑剔', category: 'GRE词汇' },
  { word: 'niggling', phonetic: '/ˈnɪɡlɪŋ/', meaning: 'adj. 琐碎的', category: 'GRE词汇' },
  { word: 'night', phonetic: '/naɪt/', meaning: 'n. 夜晚', category: '托福词汇' },
  { word: 'nightclub', phonetic: '/ˈnaɪtklʌb/', meaning: 'n. 夜总会', category: '托福词汇' },
  { word: 'nightfall', phonetic: '/ˈnaɪtfɔːl/', meaning: 'n. 黄昏', category: 'GRE词汇' },
  { word: 'nightingale', phonetic: '/ˈnaɪtɪŋɡeɪl/', meaning: 'n. 夜莺', category: 'GRE词汇' },
  { word: 'nightly', phonetic: '/ˈnaɪtli/', meaning: 'adj. 每夜的', category: '托福词汇' },
  { word: 'nightmare', phonetic: '/ˈnaɪtmeər/', meaning: 'n. 噩梦', category: '托福词汇' },
  { word: 'nihilism', phonetic: '/ˈnaɪɪlɪzəm/', meaning: 'n. 虚无主义', category: 'GRE词汇' },
  { word: 'nil', phonetic: '/nɪl/', meaning: 'n. 无；零', category: '托福词汇' },
  { word: 'nimble', phonetic: '/ˈnɪmbl/', meaning: 'adj. 敏捷的', category: 'GRE词汇' },
  { word: 'nimbleness', phonetic: '/ˈnɪmblnəs/', meaning: 'n. 敏捷', category: 'GRE词汇' },
  { word: 'nine', phonetic: '/naɪn/', meaning: 'num. 九', category: '托福词汇' },
  { word: 'nineteen', phonetic: '/naɪnˈtiːn/', meaning: 'num. 十九', category: '托福词汇' },
  { word: 'ninety', phonetic: '/ˈnaɪnti/', meaning: 'num. 九十', category: '托福词汇' },
  { word: 'ninth', phonetic: '/naɪnθ/', meaning: 'num. 第九', category: '托福词汇' },
  { word: 'nip', phonetic: '/nɪp/', meaning: 'v. 咬；n. 咬', category: 'GRE词汇' },
  { word: 'nipple', phonetic: '/ˈnɪpl/', meaning: 'n. 乳头', category: '医学词汇' },
  { word: 'nit', phonetic: '/nɪt/', meaning: 'n. 幼虫；傻瓜', category: 'GRE词汇' },
  { word: 'nitpick', phonetic: '/ˈnɪtpɪk/', meaning: 'v. 吹毛求疵', category: 'GRE词汇' },
  { word: 'nitpicking', phonetic: '/ˈnɪtpɪkɪŋ/', meaning: 'n. 吹毛求疵', category: 'GRE词汇' },
  { word: 'nitrogen', phonetic: '/ˈnaɪtrədʒən/', meaning: 'n. 氮', category: '科技词汇' },
  { word: 'no', phonetic: '/nəʊ/', meaning: 'adv. 不；adj. 没有', category: '托福词汇' },
  { word: 'nob', phonetic: '/nɒb/', meaning: 'n. 有钱人', category: 'GRE词汇' },
  { word: 'nobility', phonetic: '/nəʊˈbɪləti/', meaning: 'n. 贵族；高贵', category: 'GRE词汇' },
  { word: 'noble', phonetic: '/ˈnəʊbl/', meaning: 'adj. 高贵的；n. 贵族', category: '托福词汇' },
  { word: 'nobleman', phonetic: '/ˈnəʊblmən/', meaning: 'n. 贵族', category: 'GRE词汇' },
  { word: 'nobly', phonetic: '/ˈnəʊbli/', meaning: 'adv. 高尚地', category: 'GRE词汇' },
  { word: 'nobody', phonetic: '/ˈnəʊbədi/', meaning: 'pron. 没有人；n. 小人物', category: '托福词汇' },
  { word: 'nocturnal', phonetic: '/nɒkˈtɜːnl/', meaning: 'adj. 夜间的', category: 'GRE词汇' },
  { word: 'nod', phonetic: '/nɒd/', meaning: 'v. 点头；n. 点头', category: '托福词汇' },
  { word: 'nodding', phonetic: '/ˈnɒdɪŋ/', meaning: 'adj. 点头的', category: 'GRE词汇' },
  { word: 'nodule', phonetic: '/ˈnɒdjuːl/', meaning: 'n. 小结节', category: '医学词汇' },
  { word: 'noel', phonetic: '/nəʊˈel/', meaning: 'n. 圣诞节', category: 'GRE词汇' },
  { word: 'noisemaker', phonetic: '/ˈnɔɪzmeɪkər/', meaning: 'n. 发出噪音的人', category: 'GRE词汇' },
  { word: 'noisiness', phonetic: '/ˈnɔɪzinəs/', meaning: 'n. 吵闹', category: 'GRE词汇' },
  { word: 'noisy', phonetic: '/ˈnɔɪzi/', meaning: 'adj. 嘈杂的', category: '托福词汇' },
  { word: 'nomad', phonetic: '/ˈnəʊmæd/', meaning: 'n. 游牧民', category: 'GRE词汇' },
  { word: 'nomadic', phonetic: '/nəʊˈmædɪk/', meaning: 'adj. 游牧的', category: 'GRE词汇' },
  { word: 'nomenclature', phonetic: '/ˈnəʊmənklətʃər/', meaning: 'n. 命名法', category: 'GRE词汇' },
  { word: 'nominal', phonetic: '/ˈnɒmɪnl/', meaning: 'adj. 名义上的', category: 'GRE词汇' },
  { word: 'nominate', phonetic: '/ˈnɒmɪneɪt/', meaning: 'v. 提名', category: '托福词汇' },
  { word: 'nomination', phonetic: '/ˌnɒmɪˈneɪʃn/', meaning: 'n. 提名', category: '托福词汇' },
  { word: 'nominee', phonetic: '/ˌnɒmɪˈniː/', meaning: 'n. 被提名者', category: '托福词汇' },
  { word: 'nomothetic', phonetic: '/ˌnɒməˈθetɪk/', meaning: 'adj. 制定法律的', category: 'GRE词汇' },
  { word: 'nonaligned', phonetic: '/ˌnɒnəˈlaɪnd/', meaning: 'adj. 不结盟的', category: 'GRE词汇' },
  { word: 'nonbeliever', phonetic: '/ˌnɒnbɪˈliːvər/', meaning: 'n. 无信仰者', category: 'GRE词汇' },
  { word: 'nonchalance', phonetic: '/ˈnɒnʃələns/', meaning: 'n. 冷漠', category: 'GRE词汇' },
  { word: 'nonchalant', phonetic: '/ˈnɒnʃələnt/', meaning: 'adj. 冷漠的', category: 'GRE词汇' },
  { word: 'noncommittal', phonetic: '/ˌnɒnkəˈmɪtl/', meaning: 'adj. 含糊的', category: 'GRE词汇' },
  { word: 'nonconformist', phonetic: '/ˌnɒnkənˈfɔːmɪst/', meaning: 'n. 非国教徒', category: 'GRE词汇' },
  { word: 'nonconformity', phonetic: '/ˌnɒnkənˈfɔːməti/', meaning: 'n. 不墨守成规', category: 'GRE词汇' },
  { word: 'nondescript', phonetic: '/ˈnɒndɪskrɪpt/', meaning: 'adj. 平凡的', category: 'GRE词汇' },
  { word: 'none', phonetic: '/nʌn/', meaning: 'pron. 没有一个', category: '托福词汇' },
  { word: 'nonentity', phonetic: '/nɒnˈentəti/', meaning: 'n. 无足轻重的人', category: 'GRE词汇' },
  { word: 'nonessential', phonetic: '/ˌnɒnɪˈsenʃl/', meaning: 'adj. 非必要的', category: 'GRE词汇' },
  { word: 'nonexistent', phonetic: '/ˌnɒnɪɡˈzɪstənt/', meaning: 'adj. 不存在的', category: '托福词汇' },
  { word: 'nonfiction', phonetic: '/ˌnɒnˈfɪkʃn/', meaning: 'n. 非虚构作品', category: '托福词汇' },
  { word: 'nonhuman', phonetic: '/ˌnɒnˈhjuːmən/', meaning: 'adj. 非人类的', category: 'GRE词汇' },
  { word: 'noninterference', phonetic: '/ˌnɒnɪntəˈfɪərəns/', meaning: 'n. 不干涉', category: 'GRE词汇' },
  { word: 'nonnative', phonetic: '/ˌnɒnˈneɪtɪv/', meaning: 'adj. 非本土的', category: 'GRE词汇' },
  { word: 'nonnegotiable', phonetic: '/ˌnɒnnɪˈɡəʊʃiəbl/', meaning: 'adj. 不可协商的', category: 'GRE词汇' },
  { word: 'nonpareil', phonetic: '/ˈnɒnpərəl/', meaning: 'adj. 无比的；n. 无敌者', category: 'GRE词汇' },
  { word: 'nonpartisan', phonetic: '/ˌnɒnˈpɑːtɪzn/', meaning: 'adj. 无党派的', category: 'GRE词汇' },
  { word: 'nonpayment', phonetic: '/ˌnɒnˈpeɪmənt/', meaning: 'n. 未付款', category: '商务词汇' },
  { word: 'nonperforming', phonetic: '/ˌnɒnpəˈfɔːmɪŋ/', meaning: 'adj. 不履行的', category: '商务词汇' },
  { word: 'nonplus', phonetic: '/nɒnˈplʌs/', meaning: 'v. 使困惑', category: 'GRE词汇' },
  { word: 'nonprofit', phonetic: '/ˌnɒnˈprɒfɪt/', meaning: 'adj. 非营利的', category: '托福词汇' },
  { word: 'nonproductive', phonetic: '/ˌnɒnprəˈdʌktɪv/', meaning: 'adj. 非生产性的', category: '商务词汇' },
  { word: 'nonprofessional', phonetic: '/ˌnɒnprəˈfeʃənl/', meaning: 'adj. 非专业的', category: 'GRE词汇' },
  { word: 'nonproliferation', phonetic: '/ˌnɒnprəˌlɪfəˈreɪʃn/', meaning: 'n. 防扩散', category: 'GRE词汇' },
  { word: 'nonracial', phonetic: '/ˌnɒnˈreɪʃl/', meaning: 'adj. 非种族的', category: 'GRE词汇' },
  { word: 'nonreader', phonetic: '/ˌnɒnˈriːdər/', meaning: 'n. 文盲', category: 'GRE词汇' },
  { word: 'nonresident', phonetic: '/ˌnɒnˈrezɪdənt/', meaning: 'adj. 非居住的', category: 'GRE词汇' },
  { word: 'nonrestrictive', phonetic: '/ˌnɒnrɪˈstrɪktɪv/', meaning: 'adj. 非限制性的', category: 'GRE词汇' },
  { word: 'nonsense', phonetic: '/ˈnɒnsns/', meaning: 'n. 胡说', category: '托福词汇' },
  { word: 'nonsensical', phonetic: '/nɒnˈsensɪkl/', meaning: 'adj. 荒谬的', category: 'GRE词汇' },
  { word: 'nonsmoker', phonetic: '/ˌnɒnˈsməʊkər/', meaning: 'n. 不吸烟者', category: '托福词汇' },
  { word: 'nonsmoking', phonetic: '/ˌnɒnˈsməʊkɪŋ/', meaning: 'adj. 禁烟的', category: '托福词汇' },
  { word: 'nonstandard', phonetic: '/ˌnɒnˈstændəd/', meaning: 'adj. 非标准的', category: 'GRE词汇' },
  { word: 'nonstick', phonetic: '/ˌnɒnˈstɪk/', meaning: 'adj. 不粘的', category: '托福词汇' },
  { word: 'nonstop', phonetic: '/ˌnɒnˈstɒp/', meaning: 'adj. 直达的', category: '托福词汇' },
  { word: 'nonsense', phonetic: '/ˈnɒnsns/', meaning: 'n. 废话', category: '托福词汇' },
  { word: 'nonsupport', phonetic: '/ˌnɒnsəˈpɔːt/', meaning: 'n. 不支持', category: 'GRE词汇' },
  { word: 'nontraditional', phonetic: '/ˌnɒntrəˈdɪʃənl/', meaning: 'adj. 非传统的', category: 'GRE词汇' },
  { word: 'nonunion', phonetic: '/ˌnɒnˈjuːniən/', meaning: 'adj. 非工会的', category: 'GRE词汇' },
  { word: 'nonverbal', phonetic: '/ˌnɒnˈvɜːbl/', meaning: 'adj. 非语言的', category: 'GRE词汇' },
  { word: 'nonviolent', phonetic: '/ˌnɒnˈvaɪələnt/', meaning: 'adj. 非暴力的', category: '托福词汇' },
  { word: 'noodle', phonetic: '/ˈnuːdl/', meaning: 'n. 面条', category: '托福词汇' },
  { word: 'nook', phonetic: '/nʊk/', meaning: 'n. 角落', category: 'GRE词汇' },
  { word: 'noon', phonetic: '/nuːn/', meaning: 'n. 中午', category: '托福词汇' },
  { word: 'noose', phonetic: '/nuːs/', meaning: 'n. 绞索', category: 'GRE词汇' },
  { word: 'nor', phonetic: '/nɔːr/', meaning: 'conj. 也不', category: '托福词汇' },
  { word: 'norm', phonetic: '/nɔːm/', meaning: 'n. 规范', category: '托福词汇' },
  { word: 'normal', phonetic: '/ˈnɔːml/', meaning: 'adj. 正常的', category: '托福词汇' },
  { word: 'normalcy', phonetic: '/ˈnɔːmlsi/', meaning: 'n. 常态', category: 'GRE词汇' },
  { word: 'normality', phonetic: '/nɔːˈmæləti/', meaning: 'n. 正常', category: 'GRE词汇' },
  { word: 'normalization', phonetic: '/ˌnɔːməlaɪˈzeɪʃn/', meaning: 'n. 正常化', category: 'GRE词汇' },
  { word: 'normalize', phonetic: '/ˈnɔːməlaɪz/', meaning: 'v. 正常化', category: '托福词汇' },
  { word: 'normally', phonetic: '/ˈnɔːməli/', meaning: 'adv. 通常', category: '托福词汇' },
  { word: 'normative', phonetic: '/ˈnɔːmətɪv/', meaning: 'adj. 规范的', category: 'GRE词汇' },
  { word: 'north', phonetic: '/nɔːθ/', meaning: 'n. 北方；adj. 北方的', category: '托福词汇' },
  { word: 'northeast', phonetic: '/ˌnɔːθˈiːst/', meaning: 'n. 东北', category: '托福词汇' },
  { word: 'northern', phonetic: '/ˈnɔːðən/', meaning: 'adj. 北方的', category: '托福词汇' },
  { word: 'northward', phonetic: '/ˈnɔːθwəd/', meaning: 'adv. 向北', category: '托福词汇' },
  { word: 'northwest', phonetic: '/ˌnɔːθˈwest/', meaning: 'n. 西北', category: '托福词汇' },
  { word: 'nose', phonetic: '/nəʊz/', meaning: 'n. 鼻子', category: '托福词汇' },
  { word: 'nosebleed', phonetic: '/ˈnəʊzbliːd/', meaning: 'n. 流鼻血', category: '医学词汇' },
  { word: 'nosegay', phonetic: '/ˈnəʊzɡeɪ/', meaning: 'n. 花束', category: 'GRE词汇' },
  { word: 'nosh', phonetic: '/nɒʃ/', meaning: 'v. 吃零食', category: 'GRE词汇' },
  { word: 'nostalgia', phonetic: '/nɒˈstældʒə/', meaning: 'n. 怀旧', category: 'GRE词汇' },
  { word: 'nostalgic', phonetic: '/nɒˈstældʒɪk/', meaning: 'adj. 怀旧的', category: 'GRE词汇' },
  { word: 'nostril', phonetic: '/ˈnɒstrəl/', meaning: 'n. 鼻孔', category: '托福词汇' },
  { word: 'nostrum', phonetic: '/ˈnɒstrəm/', meaning: 'n. 万灵药', category: 'GRE词汇' },
  { word: 'nosy', phonetic: '/ˈnəʊzi/', meaning: 'adj. 爱管闲事的', category: 'GRE词汇' },
  { word: 'not', phonetic: '/nɒt/', meaning: 'adv. 不', category: '托福词汇' },
  { word: 'notable', phonetic: '/ˈnəʊtəbl/', meaning: 'adj. 值得注意的；n. 名人', category: 'GRE词汇' },
  { word: 'notably', phonetic: '/ˈnəʊtəbli/', meaning: 'adv. 显著地', category: '托福词汇' },
  { word: 'notary', phonetic: '/ˈnəʊtəri/', meaning: 'n. 公证人', category: '法律词汇' },
  { word: 'notation', phonetic: '/nəʊˈteɪʃn/', meaning: 'n. 记号', category: '托福词汇' },
  { word: 'notch', phonetic: '/nɒtʃ/', meaning: 'n. 刻痕；v. 刻痕', category: 'GRE词汇' },
  { word: 'note', phonetic: '/nəʊt/', meaning: 'n. 笔记；v. 记录', category: '托福词汇' },
  { word: 'notebook', phonetic: '/ˈnəʊtbʊk/', meaning: 'n. 笔记本', category: '托福词汇' },
  { word: 'noted', phonetic: '/ˈnəʊtɪd/', meaning: 'adj. 著名的', category: '托福词汇' },
  { word: 'notepaper', phonetic: '/ˈnəʊtpeɪpər/', meaning: 'n. 信纸', category: 'GRE词汇' },
  { word: 'noteworthy', phonetic: '/ˈnəʊtwɜːði/', meaning: 'adj. 值得注意的', category: 'GRE词汇' },
  { word: 'nothing', phonetic: '/ˈnʌθɪŋ/', meaning: 'pron. 没有什么；n. 无', category: '托福词汇' },
  { word: 'notice', phonetic: '/ˈnəʊtɪs/', meaning: 'n. 通知；v. 注意到', category: '托福词汇' },
  { word: 'noticeable', phonetic: '/ˈnəʊtɪsəbl/', meaning: 'adj. 显著的', category: '托福词汇' },
  { word: 'notification', phonetic: '/ˌnəʊtɪfɪˈkeɪʃn/', meaning: 'n. 通知', category: '托福词汇' },
  { word: 'notify', phonetic: '/ˈnəʊtɪfaɪ/', meaning: 'v. 通知', category: '托福词汇' },
  { word: 'notion', phonetic: '/ˈnəʊʃn/', meaning: 'n. 概念', category: '托福词汇' },
  { word: 'notional', phonetic: '/ˈnəʊʃənl/', meaning: 'adj. 概念的', category: 'GRE词汇' },
  { word: 'notoriety', phonetic: '/ˌnəʊtəˈraɪəti/', meaning: 'n. 恶名', category: 'GRE词汇' },
  { word: 'notorious', phonetic: '/nəʊˈtɔːriəs/', meaning: 'adj. 臭名昭著的', category: 'GRE词汇' },
  { word: 'notwithstanding', phonetic: '/ˌnɒtwɪθˈstændɪŋ/', meaning: 'prep. 尽管', category: 'GRE词汇' },
  { word: 'noun', phonetic: '/naʊn/', meaning: 'n. 名词', category: '托福词汇' },
  { word: 'nourish', phonetic: '/ˈnʌrɪʃ/', meaning: 'v. 滋养', category: 'GRE词汇' },
  { word: 'nourishment', phonetic: '/ˈnʌrɪʃmənt/', meaning: 'n. 营养', category: 'GRE词汇' },
  { word: 'nov', phonetic: '/nəʊˈvembər/', meaning: 'n. 十一月', category: '托福词汇' },
  { word: 'novel', phonetic: '/ˈnɒvl/', meaning: 'n. 小说；adj. 新奇的', category: '托福词汇' },
  { word: 'novelette', phonetic: '/ˌnɒvlˈet/', meaning: 'n. 中篇小说', category: 'GRE词汇' },
  { word: 'novelist', phonetic: '/ˈnɒvəlɪst/', meaning: 'n. 小说家', category: '托福词汇' },
  { word: 'novella', phonetic: '/nəʊˈvelə/', meaning: 'n. 中篇小说', category: 'GRE词汇' },
  { word: 'novelty', phonetic: '/ˈnɒvlti/', meaning: 'n. 新奇', category: 'GRE词汇' },
  { word: 'novice', phonetic: '/ˈnɒvɪs/', meaning: 'n. 新手', category: 'GRE词汇' },
  { word: 'now', phonetic: '/naʊ/', meaning: 'adv. 现在', category: '托福词汇' },
  { word: 'nowadays', phonetic: '/ˈnaʊədeɪz/', meaning: 'adv. 现今', category: '托福词汇' },
  { word: 'nowhere', phonetic: '/ˈnəʊweər/', meaning: 'adv. 无处', category: '托福词汇' },
  { word: 'noxious', phonetic: '/ˈnɒkʃəs/', meaning: 'adj. 有害的', category: 'GRE词汇' },
  { word: 'nuance', phonetic: '/ˈnjuːɑːns/', meaning: 'n. 细微差别', category: 'GRE词汇' },
  { word: 'nub', phonetic: '/nʌb/', meaning: 'n. 要点', category: 'GRE词汇' },
  { word: 'nubile', phonetic: '/ˈnjuːbaɪl/', meaning: 'adj. 适婚的', category: 'GRE词汇' },
  { word: 'nuclear', phonetic: '/ˈnjuːkliər/', meaning: 'adj. 核的', category: '托福词汇' },
  { word: 'nucleus', phonetic: '/ˈnjuːkliəs/', meaning: 'n. 原子核', category: '科技词汇' },
  { word: 'nude', phonetic: '/njuːd/', meaning: 'adj. 裸体的', category: '托福词汇' },
  { word: 'nudge', phonetic: '/nʌdʒ/', meaning: 'v. 轻推；n. 轻推', category: 'GRE词汇' },
  { word: 'nudity', phonetic: '/ˈnjuːdəti/', meaning: 'n. 裸体', category: 'GRE词汇' },
  { word: 'nugatory', phonetic: '/ˈnjuːɡətri/', meaning: 'adj. 无价值的', category: 'GRE词汇' },
  { word: 'nuisance', phonetic: '/ˈnjuːsns/', meaning: 'n. 麻烦事', category: '托福词汇' },
  { word: 'null', phonetic: '/nʌl/', meaning: 'adj. 无效的', category: 'GRE词汇' },
  { word: 'nullify', phonetic: '/ˈnʌlɪfaɪ/', meaning: 'v. 使无效', category: 'GRE词汇' },
  { word: 'nullity', phonetic: '/ˈnʌləti/', meaning: 'n. 无效', category: '法律词汇' },
  { word: 'numb', phonetic: '/nʌm/', meaning: 'adj. 麻木的；v. 使麻木', category: 'GRE词汇' },
  { word: 'number', phonetic: '/ˈnʌmbər/', meaning: 'n. 数字；v. 编号', category: '托福词汇' },
  { word: 'numberless', phonetic: '/ˈnʌmbələs/', meaning: 'adj. 无数的', category: 'GRE词汇' },
  { word: 'numeral', phonetic: '/ˈnjuːmərəl/', meaning: 'n. 数字；adj. 数字的', category: '托福词汇' },
  { word: 'numeracy', phonetic: '/ˈnjuːmərəsi/', meaning: 'n. 识数', category: 'GRE词汇' },
  { word: 'numerable', phonetic: '/ˈnjuːmərəbl/', meaning: 'adj. 可数的', category: 'GRE词汇' },
  { word: 'numerical', phonetic: '/njuːˈmerɪkl/', meaning: 'adj. 数字的', category: '托福词汇' },
  { word: 'numerous', phonetic: '/ˈnjuːmərəs/', meaning: 'adj. 许多的', category: '托福词汇' },
  { word: 'numinous', phonetic: '/ˈnjuːmɪnəs/', meaning: 'adj. 神圣的', category: 'GRE词汇' },
  { word: 'numismatics', phonetic: '/ˌnjuːmɪzˈmætɪks/', meaning: 'n. 钱币学', category: 'GRE词汇' },
  { word: 'nun', phonetic: '/nʌn/', meaning: 'n. 修女', category: '托福词汇' },
  { word: 'nunnery', phonetic: '/ˈnʌnəri/', meaning: 'n. 女修道院', category: 'GRE词汇' },
  { word: 'nurse', phonetic: '/nɜːs/', meaning: 'n. 护士；v. 护理', category: '托福词汇' },
  { word: 'nursery', phonetic: '/ˈnɜːsəri/', meaning: 'n. 托儿所', category: '托福词汇' },
  { word: 'nursing', phonetic: '/ˈnɜːsɪŋ/', meaning: 'n. 护理', category: '托福词汇' },
  { word: 'nurture', phonetic: '/ˈnɜːtʃər/', meaning: 'v. 养育；n. 养育', category: 'GRE词汇' },
  { word: 'nut', phonetic: '/nʌt/', meaning: 'n. 坚果', category: '托福词汇' },
  { word: 'nutrient', phonetic: '/ˈnjuːtriənt/', meaning: 'n. 营养物；adj. 营养的', category: '医学词汇' },
  { word: 'nutriment', phonetic: '/ˈnjuːtrɪmənt/', meaning: 'n. 营养品', category: 'GRE词汇' },
  { word: 'nutrition', phonetic: '/njuːˈtrɪʃn/', meaning: 'n. 营养', category: '托福词汇' },
  { word: 'nutritional', phonetic: '/njuːˈtrɪʃənl/', meaning: 'adj. 营养的', category: '托福词汇' },
  { word: 'nutritious', phonetic: '/njuːˈtrɪʃəs/', meaning: 'adj. 有营养的', category: 'GRE词汇' },
  { word: 'nutritive', phonetic: '/ˈnjuːtrɪtɪv/', meaning: 'adj. 有营养的', category: 'GRE词汇' },
  { word: 'nutshell', phonetic: '/ˈnʌtʃel/', meaning: 'n. 坚果壳', category: 'GRE词汇' },
  { word: 'nuzzle', phonetic: '/ˈnʌzl/', meaning: 'v. 用鼻子摩擦', category: 'GRE词汇' },
  { word: 'nymph', phonetic: '/nɪmf/', meaning: 'n. 仙女', category: 'GRE词汇' },

  // O字母开头
  { word: 'oak', phonetic: '/əʊk/', meaning: 'n. 橡树', category: '托福词汇' },
  { word: 'oaken', phonetic: '/ˈəʊkən/', meaning: 'adj. 橡木制的', category: 'GRE词汇' },
  { word: 'oar', phonetic: '/ɔːr/', meaning: 'n. 桨；v. 划', category: 'GRE词汇' },
  { word: 'oasis', phonetic: '/əʊˈeɪsɪs/', meaning: 'n. 绿洲', category: 'GRE词汇' },
  { word: 'oath', phonetic: '/əʊθ/', meaning: 'n. 誓言', category: '托福词汇' },
  { word: 'oatmeal', phonetic: '/ˈəʊtmiːl/', meaning: 'n. 燕麦片', category: '托福词汇' },
  { word: 'oats', phonetic: '/əʊts/', meaning: 'n. 燕麦', category: '托福词汇' },
  { word: 'obdurate', phonetic: '/ˈɒbdjərət/', meaning: 'adj. 固执的', category: 'GRE词汇' },
  { word: 'obedience', phonetic: '/əˈbiːdiəns/', meaning: 'n. 服从', category: '托福词汇' },
  { word: 'obedient', phonetic: '/əˈbiːdiənt/', meaning: 'adj. 顺从的', category: '托福词汇' },
  { word: 'obese', phonetic: '/əʊˈbiːs/', meaning: 'adj. 肥胖的', category: '医学词汇' },
  { word: 'obesity', phonetic: '/əʊˈbiːsəti/', meaning: 'n. 肥胖', category: '医学词汇' },
  { word: 'obey', phonetic: '/əʊˈbeɪ/', meaning: 'v. 服从', category: '托福词汇' },
  { word: 'obfuscate', phonetic: '/ɒbˈfʌskeɪt/', meaning: 'v. 使困惑', category: 'GRE词汇' },
  { word: 'obituary', phonetic: '/əʊˈbɪtʃuəri/', meaning: 'n. 讣告', category: 'GRE词汇' },
  { word: 'object', phonetic: '/ˈɒbdʒɪkt/', meaning: 'n. 物体；v. 反对', category: '托福词汇' },
  { word: 'objection', phonetic: '/əbˈdʒekʃn/', meaning: 'n. 反对', category: '托福词汇' },
  { word: 'objectionable', phonetic: '/əbˈdʒekʃənəbl/', meaning: 'adj. 令人反感的', category: 'GRE词汇' },
  { word: 'objective', phonetic: '/əbˈdʒektɪv/', meaning: 'adj. 客观的；n. 目标', category: '托福词汇' },
  { word: 'objectivity', phonetic: '/ˌɒbdʒekˈtɪvəti/', meaning: 'n. 客观性', category: 'GRE词汇' },
  { word: 'obligate', phonetic: '/ˈɒblɪɡeɪt/', meaning: 'v. 强迫', category: 'GRE词汇' },
  { word: 'obligation', phonetic: '/ˌɒblɪˈɡeɪʃn/', meaning: 'n. 义务', category: '托福词汇' },
  { word: 'obligatory', phonetic: '/əˈblɪɡətri/', meaning: 'adj. 强制的', category: 'GRE词汇' },
  { word: 'oblige', phonetic: '/əˈblaɪdʒ/', meaning: 'v. 强迫；施恩', category: '托福词汇' },
  { word: 'obliging', phonetic: '/əˈblaɪdʒɪŋ/', meaning: 'adj. 热心助人的', category: 'GRE词汇' },
  { word: 'oblique', phonetic: '/əˈbliːk/', meaning: 'adj. 斜的', category: 'GRE词汇' },
  { word: 'obliterate', phonetic: '/əˈblɪtəreɪt/', meaning: 'v. 消除', category: 'GRE词汇' },
  { word: 'oblivion', phonetic: '/əˈblɪviən/', meaning: 'n. 遗忘', category: 'GRE词汇' },
  { word: 'oblivious', phonetic: '/əˈblɪviəs/', meaning: 'adj. 不注意的', category: 'GRE词汇' },
  { word: 'oblong', phonetic: '/ˈɒblɒŋ/', meaning: 'adj. 长方形的', category: 'GRE词汇' },
  { word: 'obnoxious', phonetic: '/əbˈnɒkʃəs/', meaning: 'adj. 可憎的', category: 'GRE词汇' },
  { word: 'obscenity', phonetic: '/əbˈsenəti/', meaning: 'n. 淫秽', category: 'GRE词汇' },
  { word: 'obscure', phonetic: '/əbˈskjʊər/', meaning: 'adj. 模糊的；v. 遮掩', category: 'GRE词汇' },
  { word: 'obscurity', phonetic: '/əbˈskjʊərəti/', meaning: 'n. 模糊', category: 'GRE词汇' },
  { word: 'observable', phonetic: '/əbˈzɜːvəbl/', meaning: 'adj. 可观察的', category: 'GRE词汇' },
  { word: 'observance', phonetic: '/əbˈzɜːvəns/', meaning: 'n. 遵守', category: 'GRE词汇' },
  { word: 'observant', phonetic: '/əbˈzɜːvənt/', meaning: 'adj. 观察敏锐的', category: 'GRE词汇' },
  { word: 'observation', phonetic: '/ˌɒbzəˈveɪʃn/', meaning: 'n. 观察', category: '托福词汇' },
  { word: 'observatory', phonetic: '/əbˈzɜːvətri/', meaning: 'n. 天文台', category: 'GRE词汇' },
  { word: 'observe', phonetic: '/əbˈzɜːv/', meaning: 'v. 观察', category: '托福词汇' },
  { word: 'observer', phonetic: '/əbˈzɜːvər/', meaning: 'n. 观察者', category: '托福词汇' },
  { word: 'obsess', phonetic: '/əbˈses/', meaning: 'v. 迷住', category: 'GRE词汇' },
  { word: 'obsession', phonetic: '/əbˈseʃn/', meaning: 'n. 痴迷', category: '托福词汇' },
  { word: 'obsessive', phonetic: '/əbˈsesɪv/', meaning: 'adj. 痴迷的', category: 'GRE词汇' },
  { word: 'obsidian', phonetic: '/ɒbˈsɪdiən/', meaning: 'n. 黑曜石', category: 'GRE词汇' },
  { word: 'obsolescent', phonetic: '/ˌɒbsəˈlesnt/', meaning: 'adj. 逐渐过时的', category: 'GRE词汇' },
  { word: 'obsolete', phonetic: '/ˈɒbsəliːt/', meaning: 'adj. 过时的', category: 'GRE词汇' },
  { word: 'obstacle', phonetic: '/ˈɒbstəkl/', meaning: 'n. 障碍', category: '托福词汇' },
  { word: 'obstetric', phonetic: '/əbˈstetrɪk/', meaning: 'adj. 产科的', category: '医学词汇' },
  { word: 'obstetrics', phonetic: '/əbˈstetrɪks/', meaning: 'n. 产科', category: '医学词汇' },
  { word: 'obstinate', phonetic: '/ˈɒbstɪnət/', meaning: 'adj. 固执的', category: 'GRE词汇' },
  { word: 'obstinacy', phonetic: '/ˈɒbstɪnəsi/', meaning: 'n. 固执', category: 'GRE词汇' },
  { word: 'obstruct', phonetic: '/əbˈstrʌkt/', meaning: 'v. 阻碍', category: 'GRE词汇' },
  { word: 'obstruction', phonetic: '/əbˈstrʌkʃn/', meaning: 'n. 阻碍', category: 'GRE词汇' },
  { word: 'obtain', phonetic: '/əbˈteɪn/', meaning: 'v. 获得', category: '托福词汇' },
  { word: 'obtainable', phonetic: '/əbˈteɪnəbl/', meaning: 'adj. 可获得的', category: 'GRE词汇' },
  { word: 'obtrude', phonetic: '/əbˈtruːd/', meaning: 'v. 强加', category: 'GRE词汇' },
  { word: 'obtrusive', phonetic: '/əbˈtruːsɪv/', meaning: 'adj. 强加的', category: 'GRE词汇' },
  { word: 'obtuse', phonetic: '/əbˈtjuːs/', meaning: 'adj. 迟钝的', category: 'GRE词汇' },
  { word: 'obverse', phonetic: '/ˈɒbvɜːs/', meaning: 'n. 正面；adj. 正面的', category: 'GRE词汇' },
  { word: 'obviate', phonetic: '/ˈɒbvieɪt/', meaning: 'v. 消除', category: 'GRE词汇' },
  { word: 'obvious', phonetic: '/ˈɒbviəs/', meaning: 'adj. 明显的', category: '托福词汇' },
  { word: 'obviously', phonetic: '/ˈɒbviəsli/', meaning: 'adv. 明显地', category: '托福词汇' },
  { word: 'occasion', phonetic: '/əˈkeɪʒn/', meaning: 'n. 场合；v. 引起', category: '托福词汇' },
  { word: 'occasional', phonetic: '/əˈkeɪʒənl/', meaning: 'adj. 偶尔的', category: '托福词汇' },
  { word: 'occasionally', phonetic: '/əˈkeɪʒənəli/', meaning: 'adv. 偶尔', category: '托福词汇' },
  { word: 'occult', phonetic: '/əˈkʌlt/', meaning: 'adj. 神秘的；n. 神秘学', category: 'GRE词汇' },
  { word: 'occupancy', phonetic: '/ˈɒkjəpənsi/', meaning: 'n. 占用', category: '托福词汇' },
  { word: 'occupant', phonetic: '/ˈɒkjəpənt/', meaning: 'n. 占有者', category: '托福词汇' },
  { word: 'occupation', phonetic: '/ˌɒkjəˈpeɪʃn/', meaning: 'n. 职业；占领', category: '托福词汇' },
  { word: 'occupational', phonetic: '/ˌɒkjəˈpeɪʃənl/', meaning: 'adj. 职业的', category: '托福词汇' },
  { word: 'occupy', phonetic: '/ˈɒkjupaɪ/', meaning: 'v. 占据', category: '托福词汇' },
  { word: 'occur', phonetic: '/əˈkɜːr/', meaning: 'v. 发生', category: '托福词汇' },
  { word: 'occurrence', phonetic: '/əˈkʌrəns/', meaning: 'n. 发生', category: '托福词汇' },
  { word: 'ocean', phonetic: '/ˈəʊʃn/', meaning: 'n. 海洋', category: '托福词汇' },
  { word: 'oceanic', phonetic: '/ˌəʊʃiˈænɪk/', meaning: 'adj. 海洋的', category: 'GRE词汇' },
  { word: 'ocelot', phonetic: '/ˈɒsəlɒt/', meaning: 'n. 豹猫', category: 'GRE词汇' },
  { word: 'ochre', phonetic: '/ˈəʊkər/', meaning: 'n. 赭石', category: 'GRE词汇' },
  { word: 'octagon', phonetic: '/ˈɒktəɡən/', meaning: 'n. 八边形', category: 'GRE词汇' },
  { word: 'octave', phonetic: '/ˈɒktɪv/', meaning: 'n. 八度音阶', category: 'GRE词汇' },
  { word: 'october', phonetic: '/ɒkˈtəʊbər/', meaning: 'n. 十月', category: '托福词汇' },
  { word: 'octopus', phonetic: '/ˈɒktəpəs/', meaning: 'n. 章鱼', category: '托福词汇' },
  { word: 'ocular', phonetic: '/ˈɒkjələr/', meaning: 'adj. 眼的', category: '医学词汇' },
  { word: 'oddball', phonetic: '/ˈɒdbɔːl/', meaning: 'n. 古怪的人', category: 'GRE词汇' },
  { word: 'odds', phonetic: '/ɒdz/', meaning: 'n. 几率', category: '托福词汇' },
  { word: 'odious', phonetic: '/ˈəʊdiəs/', meaning: 'adj. 可憎的', category: 'GRE词汇' },
  { word: 'odor', phonetic: '/ˈəʊdər/', meaning: 'n. 气味', category: '托福词汇' },
  { word: 'odorous', phonetic: '/ˈəʊdərəs/', meaning: 'adj. 有气味的', category: 'GRE词汇' },
  { word: 'odyssey', phonetic: '/ˈɒdɪsi/', meaning: 'n. 长途冒险', category: 'GRE词汇' },
  { word: 'offal', phonetic: '/ˈɒfl/', meaning: 'n. 内脏', category: 'GRE词汇' },
  { word: 'offbeat', phonetic: '/ˈɒfbiːt/', meaning: 'adj. 不寻常的', category: 'GRE词汇' },
  { word: 'offence', phonetic: '/əˈfens/', meaning: 'n. 冒犯', category: '托福词汇' },
  { word: 'offend', phonetic: '/əˈfend/', meaning: 'v. 冒犯', category: '托福词汇' },
  { word: 'offender', phonetic: '/əˈfendər/', meaning: 'n. 冒犯者', category: '法律词汇' },
  { word: 'offense', phonetic: '/əˈfens/', meaning: 'n. 冒犯；犯罪', category: '托福词汇' },
  { word: 'offensive', phonetic: '/əˈfensɪv/', meaning: 'adj. 冒犯的', category: '托福词汇' },
  { word: 'offer', phonetic: '/ˈɒfər/', meaning: 'v. 提供；n. 提议', category: '托福词汇' },
  { word: 'offering', phonetic: '/ˈɒfərɪŋ/', meaning: 'n. 提供；祭品', category: '托福词汇' },
  { word: 'offhand', phonetic: '/ˌɒfˈhænd/', meaning: 'adj. 随意的；adv. 随意地', category: 'GRE词汇' },
  { word: 'office', phonetic: '/ˈɒfɪs/', meaning: 'n. 办公室', category: '托福词汇' },
  { word: 'officer', phonetic: '/ˈɒfɪsər/', meaning: 'n. 军官；警官', category: '托福词汇' },
  { word: 'official', phonetic: '/əˈfɪʃl/', meaning: 'adj. 官方的；n. 官员', category: '托福词汇' },
  { word: 'officially', phonetic: '/əˈfɪʃəli/', meaning: 'adv. 官方地', category: '托福词汇' },
  { word: 'officiate', phonetic: '/əˈfɪʃieɪt/', meaning: 'v. 主持', category: 'GRE词汇' },
  { word: 'officious', phonetic: '/əˈfɪʃəs/', meaning: 'adj. 爱管闲事的', category: 'GRE词汇' },
  { word: 'offset', phonetic: '/ˈɒfset/', meaning: 'v. 抵消；n. 抵消', category: '托福词汇' },
  { word: 'offshoot', phonetic: '/ˈɒfʃuːt/', meaning: 'n. 分支', category: 'GRE词汇' },
  { word: 'offshore', phonetic: '/ˌɒfˈʃɔːr/', meaning: 'adj. 离岸的', category: '托福词汇' },
  { word: 'offside', phonetic: '/ˌɒfˈsaɪd/', meaning: 'adj. 越位的', category: 'GRE词汇' },
  { word: 'offspring', phonetic: '/ˈɒfsprɪŋ/', meaning: 'n. 后代', category: '托福词汇' },
  { word: 'offstage', phonetic: '/ˌɒfˈsteɪdʒ/', meaning: 'adv. 在后台', category: 'GRE词汇' },
  { word: 'oft', phonetic: '/ɒft/', meaning: 'adv. 经常', category: 'GRE词汇' },
  { word: 'often', phonetic: '/ˈɒfn/', meaning: 'adv. 经常', category: '托福词汇' },
  { word: 'ogle', phonetic: '/ˈəʊɡl/', meaning: 'v. 媚眼；n. 媚眼', category: 'GRE词汇' },
  { word: 'ogre', phonetic: '/ˈəʊɡər/', meaning: 'n. 食人魔', category: 'GRE词汇' },
  { word: 'oil', phonetic: '/ɔɪl/', meaning: 'n. 油；v. 加油', category: '托福词汇' },
  { word: 'oily', phonetic: '/ˈɔɪli/', meaning: 'adj. 油的', category: '托福词汇' },
  { word: 'ointment', phonetic: '/ˈɔɪntmənt/', meaning: 'n. 软膏', category: '医学词汇' },
  { word: 'okay', phonetic: '/əʊˈkeɪ/', meaning: 'adj. 好的；adv. 好', category: '托福词汇' },
  { word: 'old', phonetic: '/əʊld/', meaning: 'adj. 老的', category: '托福词汇' },
  { word: 'olden', phonetic: '/ˈəʊldən/', meaning: 'adj. 古老的', category: 'GRE词汇' },
  { word: 'old-fashioned', phonetic: '/ˌəʊldˈfæʃnd/', meaning: 'adj. 过时的', category: '托福词汇' },
  { word: 'oldie', phonetic: '/ˈəʊldi/', meaning: 'n. 老人；旧物', category: 'GRE词汇' },
  { word: 'oldness', phonetic: '/ˈəʊldnəs/', meaning: 'n. 老', category: 'GRE词汇' },
  { word: 'oleander', phonetic: '/ˌəʊliˈændər/', meaning: 'n. 夹竹桃', category: 'GRE词汇' },
  { word: 'olfactory', phonetic: '/ɒlˈfæktəri/', meaning: 'adj. 嗅觉的', category: 'GRE词汇' },
  { word: 'oligarchy', phonetic: '/ˈɒlɪɡɑːki/', meaning: 'n. 寡头政治', category: 'GRE词汇' },
  { word: 'olive', phonetic: '/ˈɒlɪv/', meaning: 'n. 橄榄', category: '托福词汇' },
  { word: 'olympic', phonetic: '/əˈlɪmpɪk/', meaning: 'adj. 奥林匹克的', category: '托福词汇' },
  { word: 'omega', phonetic: '/əʊˈmeɪɡə/', meaning: 'n. 希腊字母欧米伽', category: 'GRE词汇' },
  { word: 'omen', phonetic: '/ˈəʊmən/', meaning: 'n. 征兆', category: 'GRE词汇' },
  { word: 'ominous', phonetic: '/ˈɒmɪnəs/', meaning: 'adj. 不祥的', category: 'GRE词汇' },
  { word: 'omission', phonetic: '/əˈmɪʃn/', meaning: 'n. 省略', category: 'GRE词汇' },
  { word: 'omit', phonetic: '/əˈmɪt/', meaning: 'v. 省略', category: '托福词汇' },
  { word: 'omnipotent', phonetic: '/ɒmˈnɪpətənt/', meaning: 'adj. 全能的', category: 'GRE词汇' },
  { word: 'omnipresent', phonetic: '/ˌɒmnɪˈpreznt/', meaning: 'adj. 无处不在的', category: 'GRE词汇' },
  { word: 'omniscient', phonetic: '/ɒmˈnɪsiənt/', meaning: 'adj. 全知的', category: 'GRE词汇' },
  { word: 'omnivorous', phonetic: '/ɒmˈnɪvərəs/', meaning: 'adj. 杂食的', category: 'GRE词汇' },
  { word: 'on', phonetic: '/ɒn/', meaning: 'prep. 在...上；adv. 继续', category: '托福词汇' },
  { word: 'once', phonetic: '/wʌns/', meaning: 'adv. 曾经；conj. 一旦', category: '托福词汇' },
  { word: 'oncoming', phonetic: '/ˈɒnkʌmɪŋ/', meaning: 'adj. 即将到来的', category: 'GRE词汇' },
  { word: 'one', phonetic: '/wʌn/', meaning: 'num. 一', category: '托福词汇' },
  { word: 'oneness', phonetic: '/ˈwʌnnəs/', meaning: 'n. 统一', category: 'GRE词汇' },
  { word: 'onerous', phonetic: '/ˈəʊnərəs/', meaning: 'adj. 繁重的', category: 'GRE词汇' },
  { word: 'oneself', phonetic: '/wʌnˈself/', meaning: 'pron. 自己', category: '托福词汇' },
  { word: 'ongoing', phonetic: '/ˈɒnɡəʊɪŋ/', meaning: 'adj. 进行中的', category: '托福词汇' },
  { word: 'onion', phonetic: '/ˈʌnjən/', meaning: 'n. 洋葱', category: '托福词汇' },
  { word: 'onlooker', phonetic: '/ˈɒnlʊkər/', meaning: 'n. 旁观者', category: 'GRE词汇' },
  { word: 'only', phonetic: '/ˈəʊnli/', meaning: 'adj. 唯一的；adv. 只有', category: '托福词汇' },
  { word: 'onset', phonetic: '/ˈɒnset/', meaning: 'n. 开始', category: 'GRE词汇' },
  { word: 'onshore', phonetic: '/ˈɒnʃɔːr/', meaning: 'adv. 向岸', category: 'GRE词汇' },
  { word: 'onslaught', phonetic: '/ˈɒnslɔːt/', meaning: 'n. 猛攻', category: 'GRE词汇' },
  { word: 'onto', phonetic: '/ˈɒntə/', meaning: 'prep. 到...上', category: '托福词汇' },
  { word: 'onward', phonetic: '/ˈɒnwəd/', meaning: 'adv. 向前', category: '托福词汇' },
  { word: 'onyx', phonetic: '/ˈɒnɪks/', meaning: 'n. 玛瑙', category: 'GRE词汇' },
  { word: 'oodle', phonetic: '/ˈuːdl/', meaning: 'n. 许多', category: 'GRE词汇' },
  { word: 'ooze', phonetic: '/uːz/', meaning: 'v. 渗出；n. 软泥', category: 'GRE词汇' },
  { word: 'opal', phonetic: '/ˈəʊpl/', meaning: 'n. 蛋白石', category: 'GRE词汇' },
  { word: 'opaque', phonetic: '/əʊˈpeɪk/', meaning: 'adj. 不透明的', category: 'GRE词汇' },
  { word: 'open', phonetic: '/ˈəʊpən/', meaning: 'adj. 开放的；v. 打开', category: '托福词汇' },
  { word: 'open-air', phonetic: '/ˌəʊpənˈeər/', meaning: 'adj. 露天的', category: '托福词汇' },
  { word: 'opener', phonetic: '/ˈəʊpənər/', meaning: 'n. 开启工具', category: '托福词汇' },
  { word: 'openly', phonetic: '/ˈəʊpənli/', meaning: 'adv. 公开地', category: '托福词汇' },
  { word: 'openness', phonetic: '/ˈəʊpənnəs/', meaning: 'n. 开放', category: '托福词汇' },
  { word: 'opera', phonetic: '/ˈɒprə/', meaning: 'n. 歌剧', category: '托福词汇' },
  { word: 'operate', phonetic: '/ˈɒpəreɪt/', meaning: 'v. 操作', category: '托福词汇' },
  { word: 'operation', phonetic: '/ˌɒpəˈreɪʃn/', meaning: 'n. 操作；手术', category: '托福词汇' },
  { word: 'operational', phonetic: '/ˌɒpəˈreɪʃənl/', meaning: 'adj. 操作的', category: '托福词汇' },
  { word: 'operative', phonetic: '/ˈɒpərətɪv/', meaning: 'adj. 有效的', category: 'GRE词汇' },
  { word: 'operator', phonetic: '/ˈɒpəreɪtər/', meaning: 'n. 操作员', category: '托福词汇' },
  { word: 'opinion', phonetic: '/əˈpɪnjən/', meaning: 'n. 意见', category: '托福词汇' },
  { word: 'opinionated', phonetic: '/əˈpɪnjəneɪtɪd/', meaning: 'adj. 固执己见的', category: 'GRE词汇' },
  { word: 'opium', phonetic: '/ˈəʊpiəm/', meaning: 'n. 鸦片', category: '医学词汇' },
  { word: 'opossum', phonetic: '/əˈpɒsəm/', meaning: 'n. 负鼠', category: 'GRE词汇' },
  { word: 'opponent', phonetic: '/əˈpəʊnənt/', meaning: 'n. 对手', category: '托福词汇' },
  { word: 'opportune', phonetic: '/ˈɒpətjuːn/', meaning: 'adj. 适当的', category: 'GRE词汇' },
  { word: 'opportunity', phonetic: '/ˌɒpəˈtjuːnəti/', meaning: 'n. 机会', category: '托福词汇' },
  { word: 'oppose', phonetic: '/əˈpəʊz/', meaning: 'v. 反对', category: '托福词汇' },
  { word: 'opposed', phonetic: '/əˈpəʊzd/', meaning: 'adj. 反对的', category: '托福词汇' },
  { word: 'opposite', phonetic: '/ˈɒpəzɪt/', meaning: 'adj. 相反的；n. 对立面', category: '托福词汇' },
  { word: 'opposition', phonetic: '/ˌɒpəˈzɪʃn/', meaning: 'n. 反对', category: '托福词汇' },
  { word: 'oppress', phonetic: '/əˈpres/', meaning: 'v. 压迫', category: 'GRE词汇' },
  { word: 'oppression', phonetic: '/əˈpreʃn/', meaning: 'n. 压迫', category: 'GRE词汇' },
  { word: 'oppressive', phonetic: '/əˈpresɪv/', meaning: 'adj. 压迫的', category: 'GRE词汇' },
  { word: 'oppressor', phonetic: '/əˈpresər/', meaning: 'n. 压迫者', category: 'GRE词汇' },
  { word: 'opprobrious', phonetic: '/əˈprəʊbriəs/', meaning: 'adj. 辱骂的', category: 'GRE词汇' },
  { word: 'opprobrium', phonetic: '/əˈprəʊbriəm/', meaning: 'n. 责骂', category: 'GRE词汇' },
  { word: 'opt', phonetic: '/ɒpt/', meaning: 'v. 选择', category: 'GRE词汇' },
  { word: 'optical', phonetic: '/ˈɒptɪkl/', meaning: 'adj. 光学的', category: '科技词汇' },
  { word: 'optic', phonetic: '/ˈɒptɪk/', meaning: 'adj. 眼的', category: '医学词汇' },
  { word: 'optician', phonetic: '/ɒpˈtɪʃn/', meaning: 'n. 眼镜商', category: 'GRE词汇' },
  { word: 'optics', phonetic: '/ˈɒptɪks/', meaning: 'n. 光学', category: '科技词汇' },
  { word: 'optimism', phonetic: '/ˈɒptɪmɪzəm/', meaning: 'n. 乐观', category: '托福词汇' },
  { word: 'optimist', phonetic: '/ˈɒptɪmɪst/', meaning: 'n. 乐观主义者', category: '托福词汇' },
  { word: 'optimistic', phonetic: '/ˌɒptɪˈmɪstɪk/', meaning: 'adj. 乐观的', category: '托福词汇' },
  { word: 'optimize', phonetic: '/ˈɒptɪmaɪz/', meaning: 'v. 优化', category: '托福词汇' },
  { word: 'optimum', phonetic: '/ˈɒptɪməm/', meaning: 'n. 最佳条件；adj. 最佳的', category: 'GRE词汇' },
  { word: 'option', phonetic: '/ˈɒpʃn/', meaning: 'n. 选择', category: '托福词汇' },
  { word: 'optional', phonetic: '/ˈɒpʃənl/', meaning: 'adj. 可选的', category: '托福词汇' },
  { word: 'optometrist', phonetic: '/ɒpˈtɒmətrɪst/', meaning: 'n. 验光师', category: '医学词汇' },
  { word: 'opulence', phonetic: '/ˈɒpjələns/', meaning: 'n. 富裕', category: 'GRE词汇' },
  { word: 'opulent', phonetic: '/ˈɒpjələnt/', meaning: 'adj. 富裕的', category: 'GRE词汇' },
  { word: 'opus', phonetic: '/ˈəʊpəs/', meaning: 'n. 作品', category: 'GRE词汇' },
  { word: 'oracle', phonetic: '/ˈɒrəkl/', meaning: 'n. 神谕', category: 'GRE词汇' },
  { word: 'oral', phonetic: '/ˈɔːrəl/', meaning: 'adj. 口头的', category: '托福词汇' },
  { word: 'orange', phonetic: '/ˈɒrɪndʒ/', meaning: 'n. 橙子；adj. 橙色的', category: '托福词汇' },
  { word: 'orangutan', phonetic: '/əˈræŋətæn/', meaning: 'n. 猩猩', category: 'GRE词汇' },
  { word: 'orator', phonetic: '/ˈɒrətər/', meaning: 'n. 演说家', category: 'GRE词汇' },
  { word: 'oratorical', phonetic: '/ˌɒrəˈtɒrɪkl/', meaning: 'adj. 演说的', category: 'GRE词汇' },
  { word: 'oratory', phonetic: '/ˈɒrətri/', meaning: 'n. 演说术', category: 'GRE词汇' },
  { word: 'orb', phonetic: '/ɔːb/', meaning: 'n. 球体', category: 'GRE词汇' },
  { word: 'orbit', phonetic: '/ˈɔːbɪt/', meaning: 'n. 轨道；v. 绕轨道运行', category: '托福词汇' },
  { word: 'orbital', phonetic: '/ˈɔːbɪtl/', meaning: 'adj. 轨道的', category: '科技词汇' },
  { word: 'orbiter', phonetic: '/ˈɔːbɪtər/', meaning: 'n. 轨道飞行器', category: '科技词汇' },
  { word: 'ordeal', phonetic: '/ɔːˈdiːl/', meaning: 'n. 严峻考验', category: 'GRE词汇' },
  { word: 'order', phonetic: '/ˈɔːdər/', meaning: 'n. 顺序；v. 订购', category: '托福词汇' },
  { word: 'orderly', phonetic: '/ˈɔːdəli/', meaning: 'adj. 有序的；n. 护工', category: '托福词汇' },
  { word: 'ordinance', phonetic: '/ˈɔːdɪnəns/', meaning: 'n. 法令', category: '法律词汇' },
  { word: 'ordinary', phonetic: '/ˈɔːdnri/', meaning: 'adj. 普通的', category: '托福词汇' },
  { word: 'ordination', phonetic: '/ˌɔːdɪˈneɪʃn/', meaning: 'n. 授职礼', category: 'GRE词汇' },
  { word: 'ordnance', phonetic: '/ˈɔːdnəns/', meaning: 'n. 军械', category: 'GRE词汇' },
  { word: 'ore', phonetic: '/ɔːr/', meaning: 'n. 矿石', category: '托福词汇' },
  { word: 'organ', phonetic: '/ˈɔːɡən/', meaning: 'n. 器官；风琴', category: '托福词汇' },
  { word: 'organic', phonetic: '/ɔːˈɡænɪk/', meaning: 'adj. 有机的', category: '托福词汇' },
  { word: 'organically', phonetic: '/ɔːˈɡænɪkli/', meaning: 'adv. 有机地', category: '托福词汇' },
  { word: 'organism', phonetic: '/ˈɔːɡənɪzəm/', meaning: 'n. 生物', category: '托福词汇' },
  { word: 'organization', phonetic: '/ˌɔːɡənaɪˈzeɪʃn/', meaning: 'n. 组织', category: '托福词汇' },
  { word: 'organize', phonetic: '/ˈɔːɡənaɪz/', meaning: 'v. 组织', category: '托福词汇' },
  { word: 'organized', phonetic: '/ˈɔːɡənaɪzd/', meaning: 'adj. 有组织的', category: '托福词汇' },
  { word: 'organizer', phonetic: '/ˈɔːɡənaɪzər/', meaning: 'n. 组织者', category: '托福词汇' },
  { word: 'orient', phonetic: '/ˈɔːriənt/', meaning: 'n. 东方；v. 使适应', category: 'GRE词汇' },
  { word: 'oriental', phonetic: '/ˌɔːriˈentl/', meaning: 'adj. 东方的', category: '托福词汇' },
  { word: 'orientation', phonetic: '/ˌɔːriənˈteɪʃn/', meaning: 'n. 方向', category: '托福词汇' },
  { word: 'oriented', phonetic: '/ˈɔːriəntɪd/', meaning: 'adj. 导向的', category: '托福词汇' },
  { word: 'orifice', phonetic: '/ˈɒrɪfɪs/', meaning: 'n. 孔', category: 'GRE词汇' },
  { word: 'origin', phonetic: '/ˈɒrɪdʒɪn/', meaning: 'n. 起源', category: '托福词汇' },
  { word: 'original', phonetic: '/əˈrɪdʒənl/', meaning: 'adj. 原始的；n. 原作', category: '托福词汇' },
  { word: 'originality', phonetic: '/əˌrɪdʒəˈnæləti/', meaning: 'n. 原创性', category: 'GRE词汇' },
  { word: 'originally', phonetic: '/əˈrɪdʒənəli/', meaning: 'adv. 最初', category: '托福词汇' },
  { word: 'originate', phonetic: '/əˈrɪdʒɪneɪt/', meaning: 'v. 起源', category: '托福词汇' },
  { word: 'ornament', phonetic: '/ˈɔːnəmənt/', meaning: 'n. 装饰；v. 装饰', category: '托福词汇' },
  { word: 'ornamental', phonetic: '/ˌɔːnəˈmentl/', meaning: 'adj. 装饰的', category: 'GRE词汇' },
  { word: 'ornate', phonetic: '/ɔːˈneɪt/', meaning: 'adj. 华丽的', category: 'GRE词汇' },
  { word: 'orphan', phonetic: '/ˈɔːfn/', meaning: 'n. 孤儿', category: '托福词汇' },
  { word: 'orphanage', phonetic: '/ˈɔːfənɪdʒ/', meaning: 'n. 孤儿院', category: '托福词汇' },
  { word: 'orthodox', phonetic: '/ˈɔːθədɒks/', meaning: 'adj. 正统的', category: 'GRE词汇' },
  { word: 'orthodoxy', phonetic: '/ˈɔːθədɒksi/', meaning: 'n. 正统', category: 'GRE词汇' },
  { word: 'orthodontics', phonetic: '/ˌɔːθəˈdɒntɪks/', meaning: 'n. 正畸学', category: '医学词汇' },
  { word: 'orthopedic', phonetic: '/ˌɔːθəˈpiːdɪk/', meaning: 'adj. 矫形的', category: '医学词汇' },
  { word: 'oscillate', phonetic: '/ˈɒsɪleɪt/', meaning: 'v. 振荡', category: 'GRE词汇' },
  { word: 'oscillation', phonetic: '/ˌɒsɪˈleɪʃn/', meaning: 'n. 振荡', category: '科技词汇' },
  { word: 'oscillator', phonetic: '/ˈɒsɪleɪtər/', meaning: 'n. 振荡器', category: '科技词汇' },
  { word: 'osmosis', phonetic: '/ɒzˈməʊsɪs/', meaning: 'n. 渗透', category: '科技词汇' },
  { word: 'osprey', phonetic: '/ˈɒspreɪ/', meaning: 'n. 鱼鹰', category: 'GRE词汇' },
  { word: 'ostensible', phonetic: '/ɒˈstensəbl/', meaning: 'adj. 表面上的', category: 'GRE词汇' },
  { word: 'ostentation', phonetic: '/ˌɒstenˈteɪʃn/', meaning: 'n. 炫耀', category: 'GRE词汇' },
  { word: 'ostentatious', phonetic: '/ˌɒstenˈteɪʃəs/', meaning: 'adj. 炫耀的', category: 'GRE词汇' },
  { word: 'osteoarthritis', phonetic: '/ˌɒstiəʊɑːˈθraɪtɪs/', meaning: 'n. 骨关节炎', category: '医学词汇' },
  { word: 'osteoporosis', phonetic: '/ˌɒstiəʊpəˈrəʊsɪs/', meaning: 'n. 骨质疏松症', category: '医学词汇' },
  { word: 'ostracize', phonetic: '/ˈɒstrəsaɪz/', meaning: 'v. 排斥', category: 'GRE词汇' },
  { word: 'ostrich', phonetic: '/ˈɒstrɪtʃ/', meaning: 'n. 鸵鸟', category: '托福词汇' },
  { word: 'other', phonetic: '/ˈʌðər/', meaning: 'adj. 其他的；pron. 其他', category: '托福词汇' },
  { word: 'otherwise', phonetic: '/ˈʌðərwaɪz/', meaning: 'adv. 否则', category: '托福词汇' },
  { word: 'otiose', phonetic: '/ˈəʊtiəʊs/', meaning: 'adj. 无用的', category: 'GRE词汇' },
  { word: 'otter', phonetic: '/ˈɒtər/', meaning: 'n. 水獭', category: 'GRE词汇' },
  { word: 'ottoman', phonetic: '/ˈɒtəmən/', meaning: 'n. 软垫脚凳', category: 'GRE词汇' },
  { word: 'oubliette', phonetic: '/ˌuːbliˈet/', meaning: 'n. 地牢', category: 'GRE词汇' },
  { word: 'ouch', phonetic: '/aʊtʃ/', meaning: 'int. 哎哟', category: '托福词汇' },
  { word: 'ought', phonetic: '/ɔːt/', meaning: 'aux. 应该', category: '托福词汇' },
  { word: 'ounce', phonetic: '/aʊns/', meaning: 'n. 盎司', category: '托福词汇' },
  { word: 'our', phonetic: '/aʊər/', meaning: 'pron. 我们的', category: '托福词汇' },
  { word: 'ours', phonetic: '/aʊərz/', meaning: 'pron. 我们的', category: '托福词汇' },
  { word: 'ourselves', phonetic: '/aʊərˈselvz/', meaning: 'pron. 我们自己', category: '托福词汇' },
  { word: 'oust', phonetic: '/aʊst/', meaning: 'v. 驱逐', category: 'GRE词汇' },
  { word: 'out', phonetic: '/aʊt/', meaning: 'adv. 向外；adj. 外面的', category: '托福词汇' },
  { word: 'outbreak', phonetic: '/ˈaʊtbreɪk/', meaning: 'n. 爆发', category: '托福词汇' },
  { word: 'outburst', phonetic: '/ˈaʊtbɜːst/', meaning: 'n. 爆发', category: 'GRE词汇' },
  { word: 'outcast', phonetic: '/ˈaʊtkɑːst/', meaning: 'n. 被遗弃者', category: 'GRE词汇' },
  { word: 'outcome', phonetic: '/ˈaʊtkʌm/', meaning: 'n. 结果', category: '托福词汇' },
  { word: 'outcry', phonetic: '/ˈaʊtkraɪ/', meaning: 'n. 呼喊', category: 'GRE词汇' },
  { word: 'outdated', phonetic: '/aʊtˈdeɪtɪd/', meaning: 'adj. 过时的', category: '托福词汇' },
  { word: 'outdo', phonetic: '/aʊtˈduː/', meaning: 'v. 胜过', category: 'GRE词汇' },
  { word: 'outdoor', phonetic: '/ˈaʊtdɔːr/', meaning: 'adj. 户外的', category: '托福词汇' },
  { word: 'outer', phonetic: '/ˈaʊtər/', meaning: 'adj. 外面的', category: '托福词汇' },
  { word: 'outermost', phonetic: '/ˈaʊtəməʊst/', meaning: 'adj. 最外面的', category: 'GRE词汇' },
  { word: 'outfield', phonetic: '/ˈaʊtfiːld/', meaning: 'n. 外场', category: 'GRE词汇' },
  { word: 'outfit', phonetic: '/ˈaʊtfɪt/', meaning: 'n. 装备；v. 配备', category: '托福词汇' },
  { word: 'outflow', phonetic: '/ˈaʊtfləʊ/', meaning: 'n. 流出', category: 'GRE词汇' },
  { word: 'outgoing', phonetic: '/ˈaʊtɡəʊɪŋ/', meaning: 'adj. 外向的', category: '托福词汇' },
  { word: 'outgrow', phonetic: '/aʊtˈɡrəʊ/', meaning: 'v. 长大而不再适用', category: 'GRE词汇' },
  { word: 'outgrowth', phonetic: '/ˈaʊtɡrəʊθ/', meaning: 'n. 自然发展', category: 'GRE词汇' },
  { word: 'outing', phonetic: '/ˈaʊtɪŋ/', meaning: 'n. 郊游', category: '托福词汇' },
  { word: 'outlandish', phonetic: '/aʊtˈlændɪʃ/', meaning: 'adj. 古怪的', category: 'GRE词汇' },
  { word: 'outlast', phonetic: '/aʊtˈlɑːst/', meaning: 'v. 比...持久', category: 'GRE词汇' },
  { word: 'outlay', phonetic: '/ˈaʊtleɪ/', meaning: 'n. 支出', category: '商务词汇' },
  { word: 'outlet', phonetic: '/ˈaʊtlet/', meaning: 'n. 出口；插座', category: '托福词汇' },
  { word: 'outline', phonetic: '/ˈaʊtlaɪn/', meaning: 'n. 轮廓；v. 概述', category: '托福词汇' },
  { word: 'outlive', phonetic: '/aʊtˈlɪv/', meaning: 'v. 比...活得长', category: 'GRE词汇' },
  { word: 'outlook', phonetic: '/ˈaʊtlʊk/', meaning: 'n. 观点；前景', category: '托福词汇' },
  { word: 'outlying', phonetic: '/ˈaʊtlaɪɪŋ/', meaning: 'adj. 边远的', category: 'GRE词汇' },
  { word: 'outnumber', phonetic: '/aʊtˈnʌmbər/', meaning: 'v. 数量超过', category: 'GRE词汇' },
  { word: 'outpace', phonetic: '/aʊtˈpeɪs/', meaning: 'v. 超过', category: 'GRE词汇' },
  { word: 'outpatient', phonetic: '/ˈaʊtpeɪʃnt/', meaning: 'n. 门诊病人', category: '医学词汇' },
  { word: 'outplay', phonetic: '/aʊtˈpleɪ/', meaning: 'v. 胜过', category: 'GRE词汇' },
  { word: 'outpost', phonetic: '/ˈaʊtpəʊst/', meaning: 'n. 前哨', category: 'GRE词汇' },
  { word: 'output', phonetic: '/ˈaʊtpʊt/', meaning: 'n. 产量；v. 输出', category: '托福词汇' },
  { word: 'outrage', phonetic: '/ˈaʊtreɪdʒ/', meaning: 'n. 愤怒；v. 激怒', category: 'GRE词汇' },
  { word: 'outrageous', phonetic: '/aʊtˈreɪdʒəs/', meaning: 'adj. 令人震惊的', category: 'GRE词汇' },
  { word: 'outrun', phonetic: '/aʊtˈrʌn/', meaning: 'v. 跑得比...快', category: 'GRE词汇' },
  { word: 'outrival', phonetic: '/aʊtˈraɪvl/', meaning: 'v. 胜过', category: 'GRE词汇' },
  { word: 'outset', phonetic: '/ˈaʊtset/', meaning: 'n. 开始', category: 'GRE词汇' },
  { word: 'outshine', phonetic: '/aʊtˈʃaɪn/', meaning: 'v. 比...更亮', category: 'GRE词汇' },
  { word: 'outskirts', phonetic: '/ˈaʊtskɜːts/', meaning: 'n. 郊区', category: '托福词汇' },
  { word: 'outsmart', phonetic: '/aʊtˈsmɑːt/', meaning: 'v. 比...聪明', category: 'GRE词汇' },
  { word: 'outspoken', phonetic: '/aʊtˈspəʊkən/', meaning: 'adj. 坦率的', category: 'GRE词汇' },
  { word: 'outspread', phonetic: '/ˌaʊtˈspred/', meaning: 'v. 展开', category: 'GRE词汇' },
  { word: 'outstanding', phonetic: '/aʊtˈstændɪŋ/', meaning: 'adj. 杰出的；未解决的', category: '托福词汇' },
  { word: 'outstrip', phonetic: '/aʊtˈstrɪp/', meaning: 'v. 超过', category: 'GRE词汇' },
  { word: 'outward', phonetic: '/ˈaʊtwəd/', meaning: 'adj. 向外的', category: '托福词汇' },
  { word: 'outwardly', phonetic: '/ˈaʊtwədli/', meaning: 'adv. 表面上', category: 'GRE词汇' },
  { word: 'outweigh', phonetic: '/aʊtˈweɪ/', meaning: 'v. 比...重；比...重要', category: 'GRE词汇' },
  { word: 'outwit', phonetic: '/aʊtˈwɪt/', meaning: 'v. 智胜', category: 'GRE词汇' },
  { word: 'oval', phonetic: '/ˈəʊvl/', meaning: 'adj. 椭圆的；n. 椭圆', category: '托福词汇' },
  { word: 'ovary', phonetic: '/ˈəʊvəri/', meaning: 'n. 卵巢', category: '医学词汇' },
  { word: 'ovation', phonetic: '/əʊˈveɪʃn/', meaning: 'n. 热烈欢迎', category: 'GRE词汇' },
  { word: 'oven', phonetic: '/ˈʌvn/', meaning: 'n. 烤箱', category: '托福词汇' },
  { word: 'over', phonetic: '/ˈəʊvər/', meaning: 'prep. 在...上方；adv. 结束', category: '托福词汇' },
  { word: 'overact', phonetic: '/ˌəʊvərˈækt/', meaning: 'v. 表演过火', category: 'GRE词汇' },
  { word: 'overalls', phonetic: '/ˈəʊvərɔːlz/', meaning: 'n. 工装裤', category: '托福词汇' },
  { word: 'overbalance', phonetic: '/ˌəʊvərˈbæləns/', meaning: 'v. 失去平衡', category: 'GRE词汇' },
  { word: 'overbear', phonetic: '/ˌəʊvərˈbeər/', meaning: 'v. 压倒', category: 'GRE词汇' },
  { word: 'overbearing', phonetic: '/ˌəʊvərˈbeərɪŋ/', meaning: 'adj. 傲慢的', category: 'GRE词汇' },
  { word: 'overblown', phonetic: '/ˌəʊvərˈbləʊn/', meaning: 'adj. 夸张的', category: 'GRE词汇' },
  { word: 'overboard', phonetic: '/ˈəʊvəbɔːd/', meaning: 'adv. 落水', category: 'GRE词汇' },
  { word: 'overburden', phonetic: '/ˌəʊvərˈbɜːdn/', meaning: 'v. 负担过重', category: 'GRE词汇' },
  { word: 'overcast', phonetic: '/ˈəʊvəkɑːst/', meaning: 'adj. 阴天的', category: 'GRE词汇' },
  { word: 'overcharge', phonetic: '/ˌəʊvərˈtʃɑːdʒ/', meaning: 'v. 多收费', category: '商务词汇' },
  { word: 'overcome', phonetic: '/ˌəʊvərˈkʌm/', meaning: 'v. 克服', category: '托福词汇' },
  { word: 'overconfident', phonetic: '/ˌəʊvərˈkɒnfɪdənt/', meaning: 'adj. 过于自信的', category: 'GRE词汇' },
  { word: 'overcrowd', phonetic: '/ˌəʊvərˈkraʊd/', meaning: 'v. 过度拥挤', category: 'GRE词汇' },
  { word: 'overdose', phonetic: '/ˈəʊvədəʊs/', meaning: 'n. 过量；v. 服药过量', category: '医学词汇' },
  { word: 'overdraft', phonetic: '/ˈəʊvədrɑːft/', meaning: 'n. 透支', category: '商务词汇' },
  { word: 'overdraw', phonetic: '/ˌəʊvərˈdrɔː/', meaning: 'v. 透支', category: '商务词汇' },
  { word: 'overeager', phonetic: '/ˌəʊvərˈiːɡər/', meaning: 'adj. 过于热切的', category: 'GRE词汇' },
  { word: 'overeat', phonetic: '/ˌəʊvərˈiːt/', meaning: 'v. 吃得过多', category: 'GRE词汇' },
  { word: 'overemphasize', phonetic: '/ˌəʊvərˈemfəsaɪz/', meaning: 'v. 过分强调', category: 'GRE词汇' },
  { word: 'overestimate', phonetic: '/ˌəʊvərˈestɪmeɪt/', meaning: 'v. 高估', category: '托福词汇' },
  { word: 'overexpose', phonetic: '/ˌəʊvərɪkˈspəʊz/', meaning: 'v. 过度曝光', category: 'GRE词汇' },
  { word: 'overfatigue', phonetic: '/ˌəʊvərfəˈtiːɡ/', meaning: 'v. 使过度疲劳', category: 'GRE词汇' },
  { word: 'overfeed', phonetic: '/ˌəʊvərˈfiːd/', meaning: 'v. 过度喂养', category: 'GRE词汇' },
  { word: 'overflow', phonetic: '/ˌəʊvərˈfləʊ/', meaning: 'v. 溢出；n. 溢出', category: '托福词汇' },
  { word: 'overfull', phonetic: '/ˌəʊvərˈfʊl/', meaning: 'adj. 太满的', category: 'GRE词汇' },
  { word: 'overgrown', phonetic: '/ˌəʊvərˈɡrəʊn/', meaning: 'adj. 长满的', category: 'GRE词汇' },
  { word: 'overgrowth', phonetic: '/ˈəʊvərɡrəʊθ/', meaning: 'n. 过度生长', category: '医学词汇' },
  { word: 'overhang', phonetic: '/ˈəʊvərhæŋ/', meaning: 'v. 悬垂；n. 悬垂物', category: 'GRE词汇' },
  { word: 'overhaul', phonetic: '/ˌəʊvərˈhɔːl/', meaning: 'v. 大修；n. 彻底检查', category: 'GRE词汇' },
  { word: 'overhead', phonetic: '/ˌəʊvərˈhed/', meaning: 'adv. 在头顶上；adj. 经常开支的', category: '托福词汇' },
  { word: 'overhear', phonetic: '/ˌəʊvərˈhɪər/', meaning: 'v. 偷听', category: 'GRE词汇' },
  { word: 'overjoyed', phonetic: '/ˌəʊvərˈdʒɔɪd/', meaning: 'adj. 极度高兴的', category: 'GRE词汇' },
  { word: 'overlap', phonetic: '/ˈəʊvəlæp/', meaning: 'v. 重叠；n. 重叠', category: '托福词汇' },
  { word: 'overlay', phonetic: '/ˌəʊvərˈleɪ/', meaning: 'v. 覆盖；n. 覆盖物', category: 'GRE词汇' },
  { word: 'overload', phonetic: '/ˌəʊvərˈləʊd/', meaning: 'v. 超载；n. 超载', category: '托福词汇' },
  { word: 'overlook', phonetic: '/ˌəʊvərˈlʊk/', meaning: 'v. 忽视；俯瞰', category: '托福词汇' },
  { word: 'overly', phonetic: '/ˈəʊvəli/', meaning: 'adv. 过度地', category: '托福词汇' },
  { word: 'overman', phonetic: '/ˈəʊvərmən/', meaning: 'n. 监工', category: 'GRE词汇' },
  { word: 'overmaster', phonetic: '/ˌəʊvərˈmɑːstər/', meaning: 'v. 征服', category: 'GRE词汇' },
  { word: 'overmuch', phonetic: '/ˌəʊvərˈmʌtʃ/', meaning: 'adj. 过多的', category: 'GRE词汇' },
  { word: 'overnight', phonetic: '/ˌəʊvərˈnaɪt/', meaning: 'adv. 一夜之间', category: '托福词汇' },
  { word: 'overpower', phonetic: '/ˌəʊvərˈpaʊər/', meaning: 'v. 压倒', category: 'GRE词汇' },
  { word: 'overpowering', phonetic: '/ˌəʊvərˈpaʊərɪŋ/', meaning: 'adj. 压倒性的', category: 'GRE词汇' },
  { word: 'overprice', phonetic: '/ˌəʊvərˈpraɪs/', meaning: 'v. 定价过高', category: '商务词汇' },
  { word: 'overrate', phonetic: '/ˌəʊvərˈreɪt/', meaning: 'v. 高估', category: 'GRE词汇' },
  { word: 'override', phonetic: '/ˌəʊvərˈraɪd/', meaning: 'v. 推翻', category: 'GRE词汇' },
  { word: 'overrule', phonetic: '/ˌəʊvərˈruːl/', meaning: 'v. 驳回', category: '法律词汇' },
  { word: 'overrun', phonetic: '/ˌəʊvərˈrʌn/', meaning: 'v. 超过；泛滥', category: 'GRE词汇' },
  { word: 'overseas', phonetic: '/ˌəʊvərˈsiːz/', meaning: 'adj. 海外的；adv. 在海外', category: '托福词汇' },
  { word: 'oversee', phonetic: '/ˌəʊvərˈsiː/', meaning: 'v. 监督', category: '托福词汇' },
  { word: 'overseer', phonetic: '/ˈəʊvərsiːər/', meaning: 'n. 监工', category: 'GRE词汇' },
  { word: 'overshadow', phonetic: '/ˌəʊvərˈʃædəʊ/', meaning: 'v. 使黯然失色', category: 'GRE词汇' },
  { word: 'overshoot', phonetic: '/ˌəʊvərˈʃuːt/', meaning: 'v. 超过', category: 'GRE词汇' },
  { word: 'oversight', phonetic: '/ˈəʊvərsaɪt/', meaning: 'n. 疏忽；监督', category: 'GRE词汇' },
  { word: 'oversimplify', phonetic: '/ˌəʊvərˈsɪmplɪfaɪ/', meaning: 'v. 过于简化', category: 'GRE词汇' },
  { word: 'oversleep', phonetic: '/ˌəʊvərˈsliːp/', meaning: 'v. 睡过头', category: '托福词汇' },
  { word: 'overspend', phonetic: '/ˌəʊvərˈspend/', meaning: 'v. 超支', category: '商务词汇' },
  { word: 'overstate', phonetic: '/ˌəʊvərˈsteɪt/', meaning: 'v. 夸大', category: 'GRE词汇' },
  { word: 'overstatement', phonetic: '/ˈəʊvərsteɪtmənt/', meaning: 'n. 夸大', category: 'GRE词汇' },
  { word: 'overstay', phonetic: '/ˌəʊvərˈsteɪ/', meaning: 'v. 逗留过久', category: 'GRE词汇' },
  { word: 'overstep', phonetic: '/ˌəʊvərˈstep/', meaning: 'v. 超越', category: 'GRE词汇' },
  { word: 'overt', phonetic: '/əʊˈvɜːt/', meaning: 'adj. 明显的', category: 'GRE词汇' },
  { word: 'overtake', phonetic: '/ˌəʊvərˈteɪk/', meaning: 'v. 超过', category: '托福词汇' },
  { word: 'overtax', phonetic: '/ˌəʊvərˈtæks/', meaning: 'v. 使负担过重', category: 'GRE词汇' },
  { word: 'overtake', phonetic: '/ˌəʊvərˈteɪk/', meaning: 'v. 追上', category: '托福词汇' },
  { word: 'overthrow', phonetic: '/ˌəʊvərˈθrəʊ/', meaning: 'v. 推翻；n. 推翻', category: 'GRE词汇' },
  { word: 'overtime', phonetic: '/ˈəʊvətaɪm/', meaning: 'n. 加班；adv. 加班地', category: '托福词汇' },
  { word: 'overtly', phonetic: '/əʊˈvɜːtli/', meaning: 'adv. 公开地', category: 'GRE词汇' },
  { word: 'overtone', phonetic: '/ˈəʊvətəʊn/', meaning: 'n. 暗示', category: 'GRE词汇' },
  { word: 'overtop', phonetic: '/ˌəʊvərˈtɒp/', meaning: 'v. 高出', category: 'GRE词汇' },
  { word: 'overturn', phonetic: '/ˌəʊvərˈtɜːn/', meaning: 'v. 推翻', category: 'GRE词汇' },
  { word: 'overuse', phonetic: '/ˌəʊvərˈjuːz/', meaning: 'v. 过度使用；n. 过度使用', category: '托福词汇' },
  { word: 'overvalue', phonetic: '/ˌəʊvərˈvæljuː/', meaning: 'v. 高估', category: 'GRE词汇' },
  { word: 'overweight', phonetic: '/ˌəʊvərˈweɪt/', meaning: 'adj. 超重的；n. 超重', category: '托福词汇' },
  { word: 'overwhelm', phonetic: '/ˌəʊvərˈwelm/', meaning: 'v. 压倒', category: '托福词汇' },
  { word: 'overwhelming', phonetic: '/ˌəʊvərˈwelmɪŋ/', meaning: 'adj. 压倒性的', category: '托福词汇' },
  { word: 'overwork', phonetic: '/ˌəʊvərˈwɜːk/', meaning: 'v. 过度工作；n. 过度工作', category: '托福词汇' },
  { word: 'overwrought', phonetic: '/ˌəʊvərˈrɔːt/', meaning: 'adj. 紧张过度的', category: 'GRE词汇' },
  { word: 'oviduct', phonetic: '/ˈəʊvɪdʌkt/', meaning: 'n. 输卵管', category: '医学词汇' },
  { word: 'ovulate', phonetic: '/ˈɒvjʊleɪt/', meaning: 'v. 排卵', category: '医学词汇' },
  { word: 'ovulation', phonetic: '/ˌɒvjuˈleɪʃn/', meaning: 'n. 排卵', category: '医学词汇' },
  { word: 'owe', phonetic: '/əʊ/', meaning: 'v. 欠', category: '托福词汇' },
  { word: 'owl', phonetic: '/aʊl/', meaning: 'n. 猫头鹰', category: '托福词汇' },
  { word: 'own', phonetic: '/əʊn/', meaning: 'adj. 自己的；v. 拥有', category: '托福词汇' },
  { word: 'owner', phonetic: '/ˈəʊnər/', meaning: 'n. 所有者', category: '托福词汇' },
  { word: 'ownership', phonetic: '/ˈəʊnəʃɪp/', meaning: 'n. 所有权', category: '托福词汇' },
  { word: 'ox', phonetic: '/ɒks/', meaning: 'n. 公牛', category: '托福词汇' },
  { word: 'oxide', phonetic: '/ˈɒksaɪd/', meaning: 'n. 氧化物', category: '科技词汇' },
  { word: 'oxidize', phonetic: '/ˈɒksɪdaɪz/', meaning: 'v. 氧化', category: '科技词汇' },
  { word: 'oxygen', phonetic: '/ˈɒksɪdʒən/', meaning: 'n. 氧气', category: '托福词汇' },
  { word: 'oyster', phonetic: '/ˈɔɪstər/', meaning: 'n. 牡蛎', category: '托福词汇' },
  { word: 'ozone', phonetic: '/ˈəʊzəʊn/', meaning: 'n. 臭氧', category: '科技词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await supabase
    .from(WORDS_TABLE)
    .select('word');
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsNR, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 N-O 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsNR.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsNR, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
