// F-I字母开头的单词 - Part 1/6
import { getSupabaseClient } from '../src/storage/database/supabase-client';
import { fetchAllFromSupabase } from '../src/lib/supabase-fetch-all';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsFI = [
  // F字母开头
  { word: 'fabricate', phonetic: '/ˈfæbrɪkeɪt/', meaning: 'v. 编造；制造', category: '托福词汇' },
  { word: 'fabrication', phonetic: '/ˌfæbrɪˈkeɪʃn/', meaning: 'n. 编造；制造', category: '托福词汇' },
  { word: 'fabulous', phonetic: '/ˈfæbjələs/', meaning: 'adj. 极好的；传说的', category: '托福词汇' },
  { word: 'facade', phonetic: '/fəˈsɑːd/', meaning: 'n. 正面；假象', category: 'GRE词汇' },
  { word: 'facet', phonetic: '/ˈfæsɪt/', meaning: 'n. 方面；小平面', category: 'GRE词汇' },
  { word: 'facetious', phonetic: '/fəˈsiːʃəs/', meaning: 'adj. 滑稽的；爱开玩笑的', category: 'GRE词汇' },
  { word: 'facilitate', phonetic: '/fəˈsɪlɪteɪt/', meaning: 'v. 促进；使便利', category: '托福词汇' },
  { word: 'facilitation', phonetic: '/fəˌsɪlɪˈteɪʃn/', meaning: 'n. 促进；便利', category: '托福词汇' },
  { word: 'facility', phonetic: '/fəˈsɪləti/', meaning: 'n. 设施；能力', category: '托福词汇' },
  { word: 'facsimile', phonetic: '/fækˈsɪməli/', meaning: 'n. 复制品；传真', category: 'GRE词汇' },
  { word: 'faction', phonetic: '/ˈfækʃn/', meaning: 'n. 派系；小集团', category: 'GRE词汇' },
  { word: 'factious', phonetic: '/ˈfækʃəs/', meaning: 'adj. 好搞派系的', category: 'GRE词汇' },
  { word: 'factitious', phonetic: '/fækˈtɪʃəs/', meaning: 'adj. 人为的；虚假的', category: 'GRE词汇' },
  { word: 'factor', phonetic: '/ˈfæktər/', meaning: 'n. 因素；因子', category: '托福词汇' },
  { word: 'factorial', phonetic: '/fækˈtɔːriəl/', meaning: 'n. 阶乘；adj. 因子的', category: '科技词汇' },
  { word: 'factory', phonetic: '/ˈfæktri/', meaning: 'n. 工厂', category: '托福词汇' },
  { word: 'faculty', phonetic: '/ˈfæklti/', meaning: 'n. 能力；全体教员', category: '托福词汇' },
  { word: 'fad', phonetic: '/fæd/', meaning: 'n. 一时的风尚', category: '托福词汇' },
  { word: 'fade', phonetic: '/feɪd/', meaning: 'v. 褪色；逐渐消失', category: '托福词汇' },
  { word: 'fail', phonetic: '/feɪl/', meaning: 'v. 失败', category: '托福词汇' },
  { word: 'failure', phonetic: '/ˈfeɪljər/', meaning: 'n. 失败', category: '托福词汇' },
  { word: 'faint', phonetic: '/feɪnt/', meaning: 'adj. 微弱的；v. 昏倒', category: '托福词汇' },
  { word: 'fair', phonetic: '/feər/', meaning: 'adj. 公平的；n. 集市', category: '托福词汇' },
  { word: 'fairly', phonetic: '/ˈfeəli/', meaning: 'adv. 相当；公平地', category: '托福词汇' },
  { word: 'fairness', phonetic: '/ˈfeənəs/', meaning: 'n. 公平', category: '托福词汇' },
  { word: 'fairy', phonetic: '/ˈfeəri/', meaning: 'n. 仙女；精灵', category: '日常词汇' },
  { word: 'faith', phonetic: '/feɪθ/', meaning: 'n. 信仰；信任', category: '托福词汇' },
  { word: 'faithful', phonetic: '/ˈfeɪθfl/', meaning: 'adj. 忠实的', category: '托福词汇' },
  { word: 'fake', phonetic: '/feɪk/', meaning: 'adj. 假的；v. 伪造', category: '托福词汇' },
  { word: 'fallacy', phonetic: '/ˈfæləsi/', meaning: 'n. 谬误', category: 'GRE词汇' },
  { word: 'fallible', phonetic: '/ˈfæləbl/', meaning: 'adj. 易犯错的', category: 'GRE词汇' },
  { word: 'fallout', phonetic: '/ˈfɔːlaʊt/', meaning: 'n. 后果；放射性尘埃', category: 'GRE词汇' },
  { word: 'fallow', phonetic: '/ˈfæləʊ/', meaning: 'adj. 休耕的', category: 'GRE词汇' },
  { word: 'falsehood', phonetic: '/ˈfɔːlshʊd/', meaning: 'n. 谎言；虚假', category: 'GRE词汇' },
  { word: 'falter', phonetic: '/ˈfɔːltər/', meaning: 'v. 蹒跚；犹豫', category: 'GRE词汇' },
  { word: 'fame', phonetic: '/feɪm/', meaning: 'n. 名声', category: '托福词汇' },
  { word: 'familiar', phonetic: '/fəˈmɪliər/', meaning: 'adj. 熟悉的', category: '托福词汇' },
  { word: 'familiarity', phonetic: '/fəˌmɪliˈærəti/', meaning: 'n. 熟悉；亲密', category: '托福词汇' },
  { word: 'familiarize', phonetic: '/fəˈmɪliəraɪz/', meaning: 'v. 使熟悉', category: '托福词汇' },
  { word: 'family', phonetic: '/ˈfæməli/', meaning: 'n. 家庭', category: '托福词汇' },
  { word: 'famine', phonetic: '/ˈfæmɪn/', meaning: 'n. 饥荒', category: '托福词汇' },
  { word: 'famish', phonetic: '/ˈfæmɪʃ/', meaning: 'v. 使挨饿', category: 'GRE词汇' },
  { word: 'famous', phonetic: '/ˈfeɪməs/', meaning: 'adj. 著名的', category: '托福词汇' },
  { word: 'fan', phonetic: '/fæn/', meaning: 'n. 迷；风扇', category: '托福词汇' },
  { word: 'fanatic', phonetic: '/fəˈnætɪk/', meaning: 'n. 狂热者', category: 'GRE词汇' },
  { word: 'fanaticism', phonetic: '/fəˈnætɪsɪzəm/', meaning: 'n. 狂热', category: 'GRE词汇' },
  { word: 'fancy', phonetic: '/ˈfænsi/', meaning: 'n. 幻想；adj. 精致的', category: '托福词汇' },
  { word: 'fantasy', phonetic: '/ˈfæntəsi/', meaning: 'n. 幻想', category: '托福词汇' },
  { word: 'far', phonetic: '/fɑːr/', meaning: 'adv. 远；adj. 远的', category: '托福词汇' },
  { word: 'fare', phonetic: '/feər/', meaning: 'n. 车费；v. 进展', category: '托福词汇' },
  { word: 'farewell', phonetic: '/ˌfeəˈwel/', meaning: 'n. 告别', category: '托福词汇' },
  { word: 'farm', phonetic: '/fɑːm/', meaning: 'n. 农场', category: '托福词汇' },
  { word: 'far-reaching', phonetic: '/fɑːrˈriːtʃɪŋ/', meaning: 'adj. 影响深远的', category: '托福词汇' },
  { word: 'fascinate', phonetic: '/ˈfæsɪneɪt/', meaning: 'v. 使着迷', category: '托福词汇' },
  { word: 'fascinating', phonetic: '/ˈfæsɪneɪtɪŋ/', meaning: 'adj. 迷人的', category: '托福词汇' },
  { word: 'fascination', phonetic: '/ˌfæsɪˈneɪʃn/', meaning: 'n. 魅力；着迷', category: '托福词汇' },
  { word: 'fascism', phonetic: '/ˈfæʃɪzəm/', meaning: 'n. 法西斯主义', category: 'GRE词汇' },
  { word: 'fashion', phonetic: '/ˈfæʃn/', meaning: 'n. 时尚；方式', category: '托福词汇' },
  { word: 'fashionable', phonetic: '/ˈfæʃnəbl/', meaning: 'adj. 时尚的', category: '托福词汇' },
  { word: 'fast', phonetic: '/fɑːst/', meaning: 'adj. 快的；adv. 快速地', category: '托福词汇' },
  { word: 'fasten', phonetic: '/ˈfɑːsn/', meaning: 'v. 系紧；固定', category: '托福词汇' },
  { word: 'fastidious', phonetic: '/fæˈstɪdiəs/', meaning: 'adj. 挑剔的', category: 'GRE词汇' },
  { word: 'fatal', phonetic: '/ˈfeɪtl/', meaning: 'adj. 致命的', category: '托福词汇' },
  { word: 'fatalism', phonetic: '/ˈfeɪtəlɪzəm/', meaning: 'n. 宿命论', category: 'GRE词汇' },
  { word: 'fatality', phonetic: '/fəˈtæləti/', meaning: 'n. 死亡；宿命', category: 'GRE词汇' },
  { word: 'fate', phonetic: '/feɪt/', meaning: 'n. 命运', category: '托福词汇' },
  { word: 'fated', phonetic: '/ˈfeɪtɪd/', meaning: 'adj. 命中注定的', category: 'GRE词汇' },
  { word: 'fateful', phonetic: '/ˈfeɪtfl/', meaning: 'adj. 决定性的', category: 'GRE词汇' },
  { word: 'father', phonetic: '/ˈfɑːðər/', meaning: 'n. 父亲', category: '托福词汇' },
  { word: 'fathom', phonetic: '/ˈfæðəm/', meaning: 'v. 理解；n. 英寻', category: 'GRE词汇' },
  { word: 'fatigue', phonetic: '/fəˈtiːɡ/', meaning: 'n. 疲劳；v. 使疲劳', category: '托福词汇' },
  { word: 'fatuous', phonetic: '/ˈfætʃuəs/', meaning: 'adj. 愚蠢的', category: 'GRE词汇' },
  { word: 'fault', phonetic: '/fɔːlt/', meaning: 'n. 错误；缺点', category: '托福词汇' },
  { word: 'faulty', phonetic: '/ˈfɔːlti/', meaning: 'adj. 有缺陷的', category: '托福词汇' },
  { word: 'fauna', phonetic: '/ˈfɔːnə/', meaning: 'n. 动物群', category: 'GRE词汇' },
  { word: 'favor', phonetic: '/ˈfeɪvər/', meaning: 'n. 恩惠；v. 偏爱', category: '托福词汇' },
  { word: 'favorable', phonetic: '/ˈfeɪvərəbl/', meaning: 'adj. 有利的', category: '托福词汇' },
  { word: 'favorite', phonetic: '/ˈfeɪvərɪt/', meaning: 'adj. 最喜欢的；n. 最喜欢的人或物', category: '托福词汇' },
  { word: 'fawn', phonetic: '/fɔːn/', meaning: 'v. 奉承；n. 小鹿', category: 'GRE词汇' },
  { word: 'fear', phonetic: '/fɪər/', meaning: 'n. 恐惧；v. 害怕', category: '托福词汇' },
  { word: 'fearful', phonetic: '/ˈfɪəfl/', meaning: 'adj. 可怕的；害怕的', category: '托福词汇' },
  { word: 'fearless', phonetic: '/ˈfɪələs/', meaning: 'adj. 无畏的', category: '托福词汇' },
  { word: 'feasibility', phonetic: '/ˌfiːzəˈbɪləti/', meaning: 'n. 可行性', category: '商务词汇' },
  { word: 'feasible', phonetic: '/ˈfiːzəbl/', meaning: 'adj. 可行的', category: '托福词汇' },
  { word: 'feast', phonetic: '/fiːst/', meaning: 'n. 盛宴；v. 享受', category: '托福词汇' },
  { word: 'feat', phonetic: '/fiːt/', meaning: 'n. 功绩；壮举', category: 'GRE词汇' },
  { word: 'feather', phonetic: '/ˈfeðər/', meaning: 'n. 羽毛', category: '托福词汇' },
  { word: 'feature', phonetic: '/ˈfiːtʃər/', meaning: 'n. 特征；v. 以...为特色', category: '托福词汇' },
  { word: 'febrile', phonetic: '/ˈfiːbraɪl/', meaning: 'adj. 发烧的；狂热的', category: '医学词汇' },
  { word: 'February', phonetic: '/ˈfebruəri/', meaning: 'n. 二月', category: '日常词汇' },
  { word: 'fecund', phonetic: '/ˈfiːkənd/', meaning: 'adj. 多产的；肥沃的', category: 'GRE词汇' },
  { word: 'federal', phonetic: '/ˈfedərəl/', meaning: 'adj. 联邦的', category: '托福词汇' },
  { word: 'federation', phonetic: '/ˌfedəˈreɪʃn/', meaning: 'n. 联邦；联盟', category: '托福词汇' },
  { word: 'fee', phonetic: '/fiː/', meaning: 'n. 费用', category: '托福词汇' },
  { word: 'feeble', phonetic: '/ˈfiːbl/', meaning: 'adj. 虚弱的；无力的', category: 'GRE词汇' },
  { word: 'feed', phonetic: '/fiːd/', meaning: 'v. 喂养；n. 饲料', category: '托福词汇' },
  { word: 'feel', phonetic: '/fiːl/', meaning: 'v. 感觉', category: '托福词汇' },
  { word: 'feeling', phonetic: '/ˈfiːlɪŋ/', meaning: 'n. 感觉；感情', category: '托福词汇' },
  { word: 'feign', phonetic: '/feɪn/', meaning: 'v. 假装', category: 'GRE词汇' },
  { word: 'feint', phonetic: '/feɪnt/', meaning: 'n. 假动作；v. 佯攻', category: 'GRE词汇' },
  { word: 'fell', phonetic: '/fel/', meaning: 'v. 砍倒；adj. 凶猛的', category: 'GRE词汇' },
  { word: 'fellow', phonetic: '/ˈfeləʊ/', meaning: 'n. 同伴；adj. 同伴的', category: '托福词汇' },
  { word: 'fellowship', phonetic: '/ˈfeləʊʃɪp/', meaning: 'n. 友谊；奖学金', category: '托福词汇' },
  { word: 'felon', phonetic: '/ˈfelən/', meaning: 'n. 重罪犯', category: '法律词汇' },
  { word: 'felony', phonetic: '/ˈfeləni/', meaning: 'n. 重罪', category: '法律词汇' },
  { word: 'felt', phonetic: '/felt/', meaning: 'n. 毛毡', category: 'GRE词汇' },
  { word: 'female', phonetic: '/ˈfiːmeɪl/', meaning: 'adj. 女性的；n. 女性', category: '托福词汇' },
  { word: 'feminine', phonetic: '/ˈfemənɪn/', meaning: 'adj. 女性的；娇柔的', category: '托福词汇' },
  { word: 'feminism', phonetic: '/ˈfemənɪzəm/', meaning: 'n. 女权主义', category: '托福词汇' },
  { word: 'feminist', phonetic: '/ˈfemənɪst/', meaning: 'n. 女权主义者', category: '托福词汇' },
  { word: 'fence', phonetic: '/fens/', meaning: 'n. 栅栏；v. 击剑', category: '托福词汇' },
  { word: 'fend', phonetic: '/fend/', meaning: 'v. 照料；抵挡', category: 'GRE词汇' },
  { word: 'ferment', phonetic: '/fəˈment/', meaning: 'v. 发酵；n. 骚动', category: 'GRE词汇' },
  { word: 'fermentation', phonetic: '/ˌfɜːmenˈteɪʃn/', meaning: 'n. 发酵', category: '科技词汇' },
  { word: 'fern', phonetic: '/fɜːn/', meaning: 'n. 蕨类植物', category: 'GRE词汇' },
  { word: 'ferocious', phonetic: '/fəˈrəʊʃəs/', meaning: 'adj. 凶猛的', category: 'GRE词汇' },
  { word: 'ferocity', phonetic: '/fəˈrɒsəti/', meaning: 'n. 凶猛', category: 'GRE词汇' },
  { word: 'ferret', phonetic: '/ˈferɪt/', meaning: 'v. 搜寻；n. 雪貂', category: 'GRE词汇' },
  { word: 'ferry', phonetic: '/ˈferi/', meaning: 'n. 渡船；v. 渡运', category: '托福词汇' },
  { word: 'fertile', phonetic: '/ˈfɜːtaɪl/', meaning: 'adj. 肥沃的；多产的', category: '托福词汇' },
  { word: 'fertility', phonetic: '/fəˈtɪləti/', meaning: 'n. 肥沃；繁殖力', category: '托福词汇' },
  { word: 'fertilize', phonetic: '/ˈfɜːtəlaɪz/', meaning: 'v. 施肥；受精', category: '科技词汇' },
  { word: 'fertilizer', phonetic: '/ˈfɜːtəlaɪzər/', meaning: 'n. 肥料', category: '托福词汇' },
  { word: 'ferule', phonetic: '/ˈferuːl/', meaning: 'n. 戒尺', category: 'GRE词汇' },
  { word: 'fervent', phonetic: '/ˈfɜːvənt/', meaning: 'adj. 热情的；热烈的', category: 'GRE词汇' },
  { word: 'fervid', phonetic: '/ˈfɜːvɪd/', meaning: 'adj. 热情的；热烈的', category: 'GRE词汇' },
  { word: 'fervor', phonetic: '/ˈfɜːvər/', meaning: 'n. 热情；热烈', category: 'GRE词汇' },
  { word: 'fest', phonetic: '/fest/', meaning: 'n. 集会；节日', category: '日常词汇' },
  { word: 'fester', phonetic: '/ˈfestər/', meaning: 'v. 溃烂；恶化', category: 'GRE词汇' },
  { word: 'festival', phonetic: '/ˈfestɪvl/', meaning: 'n. 节日', category: '托福词汇' },
  { word: 'festive', phonetic: '/ˈfestɪv/', meaning: 'adj. 节日的；欢庆的', category: '托福词汇' },
  { word: 'festivity', phonetic: '/feˈstɪvəti/', meaning: 'n. 欢庆；庆典', category: '托福词汇' },
  { word: 'fetal', phonetic: '/ˈfiːtl/', meaning: 'adj. 胎儿的', category: '医学词汇' },
  { word: 'fetch', phonetic: '/fetʃ/', meaning: 'v. 取来', category: '托福词汇' },
  { word: 'fete', phonetic: '/feɪt/', meaning: 'n. 庆典；v. 宴请', category: 'GRE词汇' },
  { word: 'fetid', phonetic: '/ˈfetɪd/', meaning: 'adj. 恶臭的', category: 'GRE词汇' },
  { word: 'fetter', phonetic: '/ˈfetər/', meaning: 'v. 束缚；n. 脚镣', category: 'GRE词汇' },
  { word: 'fetus', phonetic: '/ˈfiːtəs/', meaning: 'n. 胎儿', category: '医学词汇' },
  { word: 'feud', phonetic: '/fjuːd/', meaning: 'n. 世仇；v. 长期争斗', category: 'GRE词汇' },
  { word: 'feudal', phonetic: '/ˈfjuːdl/', meaning: 'adj. 封建的', category: '托福词汇' },
  { word: 'fever', phonetic: '/ˈfiːvər/', meaning: 'n. 发烧；狂热', category: '托福词汇' },
  { word: 'feverish', phonetic: '/ˈfiːvərɪʃ/', meaning: 'adj. 发烧的；狂热的', category: '托福词汇' },
  { word: 'fiasco', phonetic: '/fiˈæskəʊ/', meaning: 'n. 惨败', category: 'GRE词汇' },
  { word: 'fiat', phonetic: '/ˈfiːæt/', meaning: 'n. 命令；法令', category: 'GRE词汇' },
  { word: 'fib', phonetic: '/fɪb/', meaning: 'n. 小谎；v. 撒小谎', category: 'GRE词汇' },
  { word: 'fiber', phonetic: '/ˈfaɪbər/', meaning: 'n. 纤维', category: '托福词汇' },
  { word: 'fibrous', phonetic: '/ˈfaɪbrəs/', meaning: 'adj. 纤维的', category: '科技词汇' },
  { word: 'fickle', phonetic: '/ˈfɪkl/', meaning: 'adj. 易变的；薄情的', category: 'GRE词汇' },
  { word: 'fiction', phonetic: '/ˈfɪkʃn/', meaning: 'n. 小说；虚构', category: '托福词汇' },
  { word: 'fictional', phonetic: '/ˈfɪkʃənl/', meaning: 'adj. 虚构的', category: '托福词汇' },
  { word: 'fictitious', phonetic: '/fɪkˈtɪʃəs/', meaning: 'adj. 虚构的', category: 'GRE词汇' },
  { word: 'fidelity', phonetic: '/fɪˈdeləti/', meaning: 'n. 忠诚；保真度', category: 'GRE词汇' },
  { word: 'fidget', phonetic: '/ˈfɪdʒɪt/', meaning: 'v. 坐立不安；n. 烦躁', category: 'GRE词汇' },
  { word: 'field', phonetic: '/fiːld/', meaning: 'n. 领域；田野', category: '托福词汇' },
  { word: 'fiend', phonetic: '/fiːnd/', meaning: 'n. 恶魔；魔鬼', category: 'GRE词汇' },
  { word: 'fiendish', phonetic: '/ˈfiːndɪʃ/', meaning: 'adj. 恶魔般的；极坏的', category: 'GRE词汇' },
  { word: 'fierce', phonetic: '/fɪəs/', meaning: 'adj. 凶猛的；激烈的', category: '托福词汇' },
  { word: 'fiery', phonetic: '/ˈfaɪəri/', meaning: 'adj. 火的；激烈的', category: '托福词汇' },
  { word: 'fiesta', phonetic: '/fiˈestə/', meaning: 'n. 节日；庆典', category: 'GRE词汇' },
  { word: 'fight', phonetic: '/faɪt/', meaning: 'v. 打架；n. 战斗', category: '托福词汇' },
  { word: 'figment', phonetic: '/ˈfɪɡmənt/', meaning: 'n. 虚构的事物', category: 'GRE词汇' },
  { word: 'figure', phonetic: '/ˈfɪɡjər/', meaning: 'n. 数字；人物；v. 计算', category: '托福词汇' },
  { word: 'figurative', phonetic: '/ˈfɪɡərətɪv/', meaning: 'adj. 比喻的', category: 'GRE词汇' },
  { word: 'figurehead', phonetic: '/ˈfɪɡərhed/', meaning: 'n. 傀儡首脑', category: 'GRE词汇' },
  { word: 'filament', phonetic: '/ˈfɪləmənt/', meaning: 'n. 灯丝；细丝', category: '科技词汇' },
  { word: 'file', phonetic: '/faɪl/', meaning: 'n. 文件；v. 归档', category: '托福词汇' },
  { word: 'filial', phonetic: '/ˈfɪliəl/', meaning: 'adj. 子女的', category: 'GRE词汇' },
  { word: 'filibuster', phonetic: '/ˈfɪlɪbʌstər/', meaning: 'n. 阻挠议事；v. 阻挠', category: 'GRE词汇' },
  { word: 'fill', phonetic: '/fɪl/', meaning: 'v. 填充', category: '托福词汇' },
  { word: 'filings', phonetic: '/ˈfaɪlɪŋz/', meaning: 'n. 锉屑', category: 'GRE词汇' },
  { word: 'filled', phonetic: '/fɪld/', meaning: 'adj. 充满的', category: '托福词汇' },
  { word: 'filly', phonetic: '/ˈfɪli/', meaning: 'n. 小母马', category: 'GRE词汇' },
  { word: 'film', phonetic: '/fɪlm/', meaning: 'n. 电影；胶片', category: '托福词汇' },
  { word: 'filter', phonetic: '/ˈfɪltər/', meaning: 'n. 过滤器；v. 过滤', category: '托福词汇' },
  { word: 'filth', phonetic: '/fɪlθ/', meaning: 'n. 污秽', category: 'GRE词汇' },
  { word: 'filthy', phonetic: '/ˈfɪlθi/', meaning: 'adj. 肮脏的', category: 'GRE词汇' },
  { word: 'fin', phonetic: '/fɪn/', meaning: 'n. 鳍', category: '托福词汇' },
  { word: 'finagle', phonetic: '/fɪˈneɪɡl/', meaning: 'v. 欺骗；诈取', category: 'GRE词汇' },
  { word: 'final', phonetic: '/ˈfaɪnl/', meaning: 'adj. 最后的；n. 决赛', category: '托福词汇' },
  { word: 'finale', phonetic: '/fɪˈnɑːli/', meaning: 'n. 结局；终场', category: 'GRE词汇' },
  { word: 'finality', phonetic: '/faɪˈnæləti/', meaning: 'n. 结局；定局', category: 'GRE词汇' },
  { word: 'finalize', phonetic: '/ˈfaɪnəlaɪz/', meaning: 'v. 完成；定稿', category: '商务词汇' },
  { word: 'finally', phonetic: '/ˈfaɪnəli/', meaning: 'adv. 最后', category: '托福词汇' },
  { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning: 'n. 金融；v. 资助', category: '商务词汇' },
  { word: 'financial', phonetic: '/faɪˈnænʃl/', meaning: 'adj. 金融的', category: '商务词汇' },
  { word: 'financier', phonetic: '/ˌfaɪnænˈsɪər/', meaning: 'n. 金融家', category: '商务词汇' },
  { word: 'find', phonetic: '/faɪnd/', meaning: 'v. 发现', category: '托福词汇' },
  { word: 'finding', phonetic: '/ˈfaɪndɪŋ/', meaning: 'n. 发现；裁决', category: '托福词汇' },
  { word: 'fine', phonetic: '/faɪn/', meaning: 'adj. 好的；n. 罚款', category: '托福词汇' },
  { word: 'fine-tune', phonetic: '/faɪn tjuːn/', meaning: 'v. 微调', category: '商务词汇' },
  { word: 'finger', phonetic: '/ˈfɪŋɡər/', meaning: 'n. 手指', category: '托福词汇' },
  { word: 'finicky', phonetic: '/ˈfɪnɪki/', meaning: 'adj. 挑剔的', category: 'GRE词汇' },
  { word: 'finish', phonetic: '/ˈfɪnɪʃ/', meaning: 'v. 完成；n. 结束', category: '托福词汇' },
  { word: 'finite', phonetic: '/ˈfaɪnaɪt/', meaning: 'adj. 有限的', category: '托福词汇' },
  { word: 'fir', phonetic: '/fɜːr/', meaning: 'n. 冷杉', category: 'GRE词汇' },
  { word: 'fire', phonetic: '/ˈfaɪər/', meaning: 'n. 火；v. 开除', category: '托福词汇' },
  { word: 'firebrand', phonetic: '/ˈfaɪəbrænd/', meaning: 'n. 煽动者', category: 'GRE词汇' },
  { word: 'firefly', phonetic: '/ˈfaɪəflaɪ/', meaning: 'n. 萤火虫', category: 'GRE词汇' },
  { word: 'fireplace', phonetic: '/ˈfaɪəpleɪs/', meaning: 'n. 壁炉', category: '托福词汇' },
  { word: 'firework', phonetic: '/ˈfaɪəwɜːk/', meaning: 'n. 烟花', category: '托福词汇' },
  { word: 'firm', phonetic: '/fɜːm/', meaning: 'adj. 坚定的；n. 公司', category: '托福词汇' },
  { word: 'firmament', phonetic: '/ˈfɜːməmənt/', meaning: 'n. 天空', category: 'GRE词汇' },
  { word: 'first', phonetic: '/fɜːst/', meaning: 'adj. 第一的；adv. 首先', category: '托福词汇' },
  { word: 'fiscal', phonetic: '/ˈfɪskl/', meaning: 'adj. 财政的', category: '商务词汇' },
  { word: 'fish', phonetic: '/fɪʃ/', meaning: 'n. 鱼；v. 钓鱼', category: '托福词汇' },
  { word: 'fisherman', phonetic: '/ˈfɪʃəmən/', meaning: 'n. 渔夫', category: '托福词汇' },
  { word: 'fishery', phonetic: '/ˈfɪʃəri/', meaning: 'n. 渔业', category: '托福词汇' },
  { word: 'fishy', phonetic: '/ˈfɪʃi/', meaning: 'adj. 可疑的', category: 'GRE词汇' },
  { word: 'fissile', phonetic: '/ˈfɪsaɪl/', meaning: 'adj. 可分裂的', category: '科技词汇' },
  { word: 'fission', phonetic: '/ˈfɪʃn/', meaning: 'n. 裂变', category: '科技词汇' },
  { word: 'fissure', phonetic: '/ˈfɪʃər/', meaning: 'n. 裂缝', category: 'GRE词汇' },
  { word: 'fist', phonetic: '/fɪst/', meaning: 'n. 拳头', category: '托福词汇' },
  { word: 'fit', phonetic: '/fɪt/', meaning: 'v. 适合；adj. 健康的', category: '托福词汇' },
  { word: 'fitful', phonetic: '/ˈfɪtfl/', meaning: 'adj. 断断续续的', category: 'GRE词汇' },
  { word: 'fitness', phonetic: '/ˈfɪtnəs/', meaning: 'n. 健康；适合', category: '托福词汇' },
  { word: 'fitting', phonetic: '/ˈfɪtɪŋ/', meaning: 'n. 试穿；配件；adj. 适当的', category: '托福词汇' },
  { word: 'five', phonetic: '/faɪv/', meaning: 'num. 五', category: '日常词汇' },
  { word: 'fix', phonetic: '/fɪks/', meaning: 'v. 修理；固定', category: '托福词汇' },
  { word: 'fixate', phonetic: '/fɪkˈseɪt/', meaning: 'v. 固定；注视', category: 'GRE词汇' },
  { word: 'fixation', phonetic: '/fɪkˈseɪʃn/', meaning: 'n. 固着；痴迷', category: 'GRE词汇' },
  { word: 'fixture', phonetic: '/ˈfɪkstʃər/', meaning: 'n. 固定装置', category: '托福词汇' },
  { word: 'flag', phonetic: '/flæɡ/', meaning: 'n. 旗帜；v. 变弱', category: '托福词汇' },
  { word: 'flagrant', phonetic: '/ˈfleɪɡrənt/', meaning: 'adj. 公然的；臭名昭著的', category: 'GRE词汇' },
  { word: 'flail', phonetic: '/fleɪl/', meaning: 'v. 乱打；n. 连枷', category: 'GRE词汇' },
  { word: 'flair', phonetic: '/fleər/', meaning: 'n. 天赋；鉴别力', category: 'GRE词汇' },
  { word: 'flak', phonetic: '/flæk/', meaning: 'n. 高射炮；批评', category: 'GRE词汇' },
  { word: 'flake', phonetic: '/fleɪk/', meaning: 'n. 薄片；v. 剥落', category: '托福词汇' },
  { word: 'flaky', phonetic: '/ˈfleɪki/', meaning: 'adj. 薄片的；不可靠的', category: 'GRE词汇' },
  { word: 'flamboyant', phonetic: '/flæmˈbɔɪənt/', meaning: 'adj. 浮夸的；艳丽的', category: 'GRE词汇' },
  { word: 'flame', phonetic: '/fleɪm/', meaning: 'n. 火焰；v. 燃烧', category: '托福词汇' },
  { word: 'flaming', phonetic: '/ˈfleɪmɪŋ/', meaning: 'adj. 燃烧的；激烈的', category: '托福词汇' },
  { word: 'flammable', phonetic: '/ˈflæməbl/', meaning: 'adj. 易燃的', category: '科技词汇' },
  { word: 'flank', phonetic: '/flæŋk/', meaning: 'n. 侧面；v. 侧击', category: 'GRE词汇' },
  { word: 'flannel', phonetic: '/ˈflænl/', meaning: 'n. 法兰绒', category: 'GRE词汇' },
  { word: 'flap', phonetic: '/flæp/', meaning: 'v. 拍打；n. 拍打声', category: '托福词汇' },
  { word: 'flare', phonetic: '/fleər/', meaning: 'v. 闪耀；n. 闪光', category: '托福词汇' },
  { word: 'flash', phonetic: '/flæʃ/', meaning: 'n. 闪光；v. 闪烁', category: '托福词汇' },
  { word: 'flashy', phonetic: '/ˈflæʃi/', meaning: 'adj. 浮华的', category: 'GRE词汇' },
  { word: 'flask', phonetic: '/flɑːsk/', meaning: 'n. 烧瓶；细颈瓶', category: '科技词汇' },
  { word: 'flat', phonetic: '/flæt/', meaning: 'adj. 平的；n. 公寓', category: '托福词汇' },
  { word: 'flatten', phonetic: '/ˈflætn/', meaning: 'v. 使平坦', category: '托福词汇' },
  { word: 'flatter', phonetic: '/ˈflætər/', meaning: 'v. 奉承', category: 'GRE词汇' },
  { word: 'flattery', phonetic: '/ˈflætəri/', meaning: 'n. 奉承', category: 'GRE词汇' },
  { word: 'flatulent', phonetic: '/ˈflætʃulənt/', meaning: 'adj. 浮夸的；肠胃胀气的', category: 'GRE词汇' },
  { word: 'flaunt', phonetic: '/flɔːnt/', meaning: 'v. 炫耀', category: 'GRE词汇' },
  { word: 'flavor', phonetic: '/ˈfleɪvər/', meaning: 'n. 味道；v. 调味', category: '托福词汇' },
  { word: 'flaw', phonetic: '/flɔː/', meaning: 'n. 瑕疵；v. 使有缺陷', category: '托福词汇' },
  { word: 'flawed', phonetic: '/flɔːd/', meaning: 'adj. 有缺陷的', category: '托福词汇' },
  { word: 'flawless', phonetic: '/ˈflɔːləs/', meaning: 'adj. 完美的', category: '托福词汇' },
  { word: 'flax', phonetic: '/flæks/', meaning: 'n. 亚麻', category: 'GRE词汇' },
  { word: 'flay', phonetic: '/fleɪ/', meaning: 'v. 剥皮；严斥', category: 'GRE词汇' },
  { word: 'flea', phonetic: '/fliː/', meaning: 'n. 跳蚤', category: '托福词汇' },
  { word: 'flee', phonetic: '/fliː/', meaning: 'v. 逃离', category: '托福词汇' },
  { word: 'fleece', phonetic: '/fliːs/', meaning: 'n. 羊毛；v. 诈骗', category: 'GRE词汇' },
  { word: 'fleeting', phonetic: '/ˈfliːtɪŋ/', meaning: 'adj. 短暂的', category: 'GRE词汇' },
  { word: 'flesh', phonetic: '/fleʃ/', meaning: 'n. 肉；肉体', category: '托福词汇' },
  { word: 'fleshy', phonetic: '/ˈfleʃi/', meaning: 'adj. 多肉的', category: 'GRE词汇' },
  { word: 'flex', phonetic: '/fleks/', meaning: 'v. 弯曲', category: '托福词汇' },
  { word: 'flexibility', phonetic: '/ˌfleksəˈbɪləti/', meaning: 'n. 灵活性', category: '托福词汇' },
  { word: 'flexible', phonetic: '/ˈfleksəbl/', meaning: 'adj. 灵活的；可弯曲的', category: '托福词汇' },
  { word: 'flick', phonetic: '/flɪk/', meaning: 'v. 轻弹；n. 轻打', category: '托福词汇' },
  { word: 'flicker', phonetic: '/ˈflɪkər/', meaning: 'v. 闪烁；n. 闪烁', category: '托福词汇' },
  { word: 'flier', phonetic: '/ˈflaɪər/', meaning: 'n. 传单；飞行者', category: '托福词汇' },
  { word: 'flight', phonetic: '/flaɪt/', meaning: 'n. 飞行；航班', category: '托福词汇' },
  { word: 'flimsy', phonetic: '/ˈflɪmzi/', meaning: 'adj. 脆弱的；不足信的', category: 'GRE词汇' },
  { word: 'flinch', phonetic: '/flɪntʃ/', meaning: 'v. 退缩', category: 'GRE词汇' },
  { word: 'fling', phonetic: '/flɪŋ/', meaning: 'v. 投掷；n. 投掷', category: '托福词汇' },
  { word: 'flint', phonetic: '/flɪnt/', meaning: 'n. 燧石', category: 'GRE词汇' },
  { word: 'flinty', phonetic: '/ˈflɪnti/', meaning: 'adj. 坚硬的；冷酷的', category: 'GRE词汇' },
  { word: 'flip', phonetic: '/flɪp/', meaning: 'v. 翻转；n. 轻抛', category: '托福词汇' },
  { word: 'flippant', phonetic: '/ˈflɪpənt/', meaning: 'adj. 轻率的', category: 'GRE词汇' },
  { word: 'flippancy', phonetic: '/ˈflɪpənsi/', meaning: 'n. 轻率', category: 'GRE词汇' },
  { word: 'flirt', phonetic: '/flɜːt/', meaning: 'v. 调情', category: '托福词汇' },
  { word: 'flit', phonetic: '/flɪt/', meaning: 'v. 掠过；轻快地飞', category: 'GRE词汇' },
  { word: 'float', phonetic: '/fləʊt/', meaning: 'v. 漂浮；n. 漂浮物', category: '托福词汇' },
  { word: 'flock', phonetic: '/flɒk/', meaning: 'n. 群；v. 聚集', category: '托福词汇' },
  { word: 'flog', phonetic: '/flɒɡ/', meaning: 'v. 鞭打', category: 'GRE词汇' },
  { word: 'flood', phonetic: '/flʌd/', meaning: 'n. 洪水；v. 淹没', category: '托福词汇' },
  { word: 'floor', phonetic: '/flɔːr/', meaning: 'n. 地板；楼层', category: '托福词汇' },
  { word: 'flop', phonetic: '/flɒp/', meaning: 'v. 笨重地落下；n. 失败', category: 'GRE词汇' },
  { word: 'floppy', phonetic: '/ˈflɒpi/', meaning: 'adj. 松软的', category: 'GRE词汇' },
  { word: 'flora', phonetic: '/ˈflɔːrə/', meaning: 'n. 植物群', category: 'GRE词汇' },
  { word: 'florid', phonetic: '/ˈflɒrɪd/', meaning: 'adj. 华丽的；红润的', category: 'GRE词汇' },
  { word: 'florist', phonetic: '/ˈflɒrɪst/', meaning: 'n. 花商', category: '托福词汇' },
  { word: 'floss', phonetic: '/flɒs/', meaning: 'n. 牙线；丝线', category: '托福词汇' },
  { word: 'flotilla', phonetic: '/fləˈtɪlə/', meaning: 'n. 小型船队', category: 'GRE词汇' },
  { word: 'flounder', phonetic: '/ˈflaʊndər/', meaning: 'v. 挣扎；n. 比目鱼', category: 'GRE词汇' },
  { word: 'flour', phonetic: '/ˈflaʊər/', meaning: 'n. 面粉', category: '托福词汇' },
  { word: 'flourish', phonetic: '/ˈflʌrɪʃ/', meaning: 'v. 繁荣；挥舞', category: '托福词汇' },
  { word: 'flout', phonetic: '/flaʊt/', meaning: 'v. 藐视；违反', category: 'GRE词汇' },
  { word: 'flow', phonetic: '/fləʊ/', meaning: 'v. 流动；n. 流动', category: '托福词汇' },
  { word: 'flower', phonetic: '/ˈflaʊər/', meaning: 'n. 花；v. 开花', category: '托福词汇' },
  { word: 'flowery', phonetic: '/ˈflaʊəri/', meaning: 'adj. 多花的；辞藻华丽的', category: 'GRE词汇' },
  { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', meaning: 'v. 波动', category: '托福词汇' },
  { word: 'fluctuation', phonetic: '/ˌflʌktʃuˈeɪʃn/', meaning: 'n. 波动', category: '托福词汇' },
  { word: 'fluency', phonetic: '/ˈfluːənsi/', meaning: 'n. 流利', category: '托福词汇' },
  { word: 'fluent', phonetic: '/ˈfluːənt/', meaning: 'adj. 流利的', category: '托福词汇' },
  { word: 'fluid', phonetic: '/ˈfluːɪd/', meaning: 'n. 液体；adj. 流动的', category: '托福词汇' },
  { word: 'fluorescent', phonetic: '/ˌflɔːˈresnt/', meaning: 'adj. 荧光的', category: '科技词汇' },
  { word: 'fluoridate', phonetic: '/ˈflʊərɪdeɪt/', meaning: 'v. 加氟', category: '科技词汇' },
  { word: 'flurry', phonetic: '/ˈflʌri/', meaning: 'n. 阵雨；一阵', category: 'GRE词汇' },
  { word: 'flush', phonetic: '/flʌʃ/', meaning: 'v. 冲洗；adj. 齐平的', category: '托福词汇' },
  { word: 'fluster', phonetic: '/ˈflʌstər/', meaning: 'v. 使慌张', category: 'GRE词汇' },
  { word: 'flute', phonetic: '/fluːt/', meaning: 'n. 长笛', category: '托福词汇' },
  { word: 'flutter', phonetic: '/ˈflʌtər/', meaning: 'v. 飘动；n. 颤动', category: '托福词汇' },
  { word: 'flux', phonetic: '/flʌks/', meaning: 'n. 变迁；流动', category: 'GRE词汇' },
  { word: 'fly', phonetic: '/flaɪ/', meaning: 'v. 飞；n. 苍蝇', category: '托福词汇' },
  { word: 'flyer', phonetic: '/ˈflaɪər/', meaning: 'n. 传单；飞行者', category: '托福词汇' },
  { word: 'flyby', phonetic: '/ˈflaɪbaɪ/', meaning: 'n. 飞越', category: '科技词汇' },
  { word: 'foam', phonetic: '/fəʊm/', meaning: 'n. 泡沫；v. 起泡沫', category: '托福词汇' },
  { word: 'foe', phonetic: '/fəʊ/', meaning: 'n. 敌人', category: 'GRE词汇' },
  { word: 'fog', phonetic: '/fɒɡ/', meaning: 'n. 雾', category: '托福词汇' },
  { word: 'foggy', phonetic: '/ˈfɒɡi/', meaning: 'adj. 有雾的；模糊的', category: '托福词汇' },
  { word: 'foil', phonetic: '/fɔɪl/', meaning: 'v. 挫败；n. 箔；陪衬', category: 'GRE词汇' },
  { word: 'fold', phonetic: '/fəʊld/', meaning: 'v. 折叠；n. 褶痕', category: '托福词汇' },
  { word: 'folder', phonetic: '/ˈfəʊldər/', meaning: 'n. 文件夹', category: '托福词汇' },
  { word: 'foliage', phonetic: '/ˈfəʊliɪdʒ/', meaning: 'n. 叶子', category: 'GRE词汇' },
  { word: 'folk', phonetic: '/fəʊk/', meaning: 'n. 人们；adj. 民间的', category: '托福词汇' },
  { word: 'folklore', phonetic: '/ˈfəʊklɔːr/', meaning: 'n. 民间传说', category: '托福词汇' },
  { word: 'follow', phonetic: '/ˈfɒləʊ/', meaning: 'v. 跟随', category: '托福词汇' },
  { word: 'follower', phonetic: '/ˈfɒləʊər/', meaning: 'n. 追随者', category: '托福词汇' },
  { word: 'folly', phonetic: '/ˈfɒli/', meaning: 'n. 愚蠢', category: 'GRE词汇' },
  { word: 'fond', phonetic: '/fɒnd/', meaning: 'adj. 喜欢的；溺爱的', category: '托福词汇' },
  { word: 'fondle', phonetic: '/ˈfɒndl/', meaning: 'v. 爱抚', category: 'GRE词汇' },
  { word: 'food', phonetic: '/fuːd/', meaning: 'n. 食物', category: '托福词汇' },
  { word: 'foodstuff', phonetic: '/ˈfuːdstʌf/', meaning: 'n. 食品', category: '托福词汇' },
  { word: 'fool', phonetic: '/fuːl/', meaning: 'n. 傻瓜；v. 愚弄', category: '托福词汇' },
  { word: 'foolhardy', phonetic: '/ˈfuːlhɑːdi/', meaning: 'adj. 有勇无谋的', category: 'GRE词汇' },
  { word: 'foolish', phonetic: '/ˈfuːlɪʃ/', meaning: 'adj. 愚蠢的', category: '托福词汇' },
  { word: 'foolproof', phonetic: '/ˈfuːlpruːf/', meaning: 'adj. 万无一失的', category: 'GRE词汇' },
  { word: 'foot', phonetic: '/fʊt/', meaning: 'n. 脚；英尺', category: '托福词汇' },
  { word: 'footing', phonetic: '/ˈfʊtɪŋ/', meaning: 'n. 立足点；基础', category: 'GRE词汇' },
  { word: 'footnote', phonetic: '/ˈfʊtnəʊt/', meaning: 'n. 脚注', category: '托福词汇' },
  { word: 'footprint', phonetic: '/ˈfʊtprɪnt/', meaning: 'n. 脚印；足迹', category: '托福词汇' },
  { word: 'footstep', phonetic: '/ˈfʊtstep/', meaning: 'n. 脚步', category: '托福词汇' },
  { word: 'for', phonetic: '/fɔːr/', meaning: 'prep. 为了；conj. 因为', category: '托福词汇' },
  { word: 'forage', phonetic: '/ˈfɒrɪdʒ/', meaning: 'v. 搜寻；n. 饲料', category: 'GRE词汇' },
  { word: 'forbear', phonetic: '/fɔːˈbeər/', meaning: 'v. 克制；n. 祖先', category: 'GRE词汇' },
  { word: 'forbearance', phonetic: '/fɔːˈbeərəns/', meaning: 'n. 克制；忍耐', category: 'GRE词汇' },
  { word: 'forbid', phonetic: '/fəˈbɪd/', meaning: 'v. 禁止', category: '托福词汇' },
  { word: 'forbidden', phonetic: '/fəˈbɪdn/', meaning: 'adj. 被禁止的', category: '托福词汇' },
  { word: 'force', phonetic: '/fɔːs/', meaning: 'n. 力量；v. 强迫', category: '托福词汇' },
  { word: 'forceful', phonetic: '/ˈfɔːsfl/', meaning: 'adj. 有力的', category: '托福词汇' },
  { word: 'forceful', phonetic: '/ˈfɔːsfl/', meaning: 'adj. 有说服力的', category: '托福词汇' },
  { word: 'forcible', phonetic: '/ˈfɔːsəbl/', meaning: 'adj. 强行的；有说服力的', category: 'GRE词汇' },
  { word: 'ford', phonetic: '/fɔːd/', meaning: 'n. 浅滩；v. 涉水', category: 'GRE词汇' },
  { word: 'fore', phonetic: '/fɔːr/', meaning: 'adj. 前面的；adv. 在前面', category: 'GRE词汇' },
  { word: 'forearm', phonetic: '/ˈfɔːrɑːm/', meaning: 'n. 前臂；v. 预先武装', category: 'GRE词汇' },
  { word: 'forecast', phonetic: '/ˈfɔːkɑːst/', meaning: 'v. 预测；n. 预报', category: '托福词汇' },
  { word: 'foreclose', phonetic: '/fɔːˈkləʊz/', meaning: 'v. 取消抵押赎回权', category: '商务词汇' },
  { word: 'forefather', phonetic: '/ˈfɔːfɑːðər/', meaning: 'n. 祖先', category: 'GRE词汇' },
  { word: 'forefront', phonetic: '/ˈfɔːfrʌnt/', meaning: 'n. 最前线', category: 'GRE词汇' },
  { word: 'forego', phonetic: '/fɔːˈɡəʊ/', meaning: 'v. 放弃；先行', category: 'GRE词汇' },
  { word: 'foreground', phonetic: '/ˈfɔːɡraʊnd/', meaning: 'n. 前景', category: '托福词汇' },
  { word: 'forehead', phonetic: '/ˈfɔːhed/', meaning: 'n. 额头', category: '托福词汇' },
  { word: 'foreign', phonetic: '/ˈfɒrən/', meaning: 'adj. 外国的；陌生的', category: '托福词汇' },
  { word: 'foreigner', phonetic: '/ˈfɒrənər/', meaning: 'n. 外国人', category: '托福词汇' },
  { word: 'foreknowledge', phonetic: '/fɔːˈnɒlɪdʒ/', meaning: 'n. 预知', category: 'GRE词汇' },
  { word: 'foremost', phonetic: '/ˈfɔːməʊst/', meaning: 'adj. 首要的；adv. 首先', category: 'GRE词汇' },
  { word: 'forensic', phonetic: '/fəˈrensɪk/', meaning: 'adj. 法庭的；法医的', category: '法律词汇' },
  { word: 'foresee', phonetic: '/fɔːˈsiː/', meaning: 'v. 预见', category: '托福词汇' },
  { word: 'foreseeable', phonetic: '/fɔːˈsiːəbl/', meaning: 'adj. 可预见的', category: '托福词汇' },
  { word: 'foreshadow', phonetic: '/fɔːˈʃædəʊ/', meaning: 'v. 预示', category: 'GRE词汇' },
  { word: 'foresight', phonetic: '/ˈfɔːsaɪt/', meaning: 'n. 远见', category: 'GRE词汇' },
  { word: 'forest', phonetic: '/ˈfɒrɪst/', meaning: 'n. 森林', category: '托福词汇' },
  { word: 'forestry', phonetic: '/ˈfɒrɪstri/', meaning: 'n. 林业', category: '托福词汇' },
  { word: 'foretell', phonetic: '/fɔːˈtel/', meaning: 'v. 预言', category: 'GRE词汇' },
  { word: 'forever', phonetic: '/fəˈrevər/', meaning: 'adv. 永远', category: '托福词汇' },
  { word: 'forfeit', phonetic: '/ˈfɔːfɪt/', meaning: 'v. 丧失；n. 罚金', category: 'GRE词汇' },
  { word: 'forger', phonetic: '/ˈfɔːdʒər/', meaning: 'n. 伪造者', category: '法律词汇' },
  { word: 'forgery', phonetic: '/ˈfɔːdʒəri/', meaning: 'n. 伪造；赝品', category: '法律词汇' },
  { word: 'forget', phonetic: '/fəˈɡet/', meaning: 'v. 忘记', category: '托福词汇' },
  { word: 'forgive', phonetic: '/fəˈɡɪv/', meaning: 'v. 原谅', category: '托福词汇' },
  { word: 'forgiveness', phonetic: '/fəˈɡɪvnəs/', meaning: 'n. 原谅', category: '托福词汇' },
  { word: 'fork', phonetic: '/fɔːk/', meaning: 'n. 叉子；分岔', category: '托福词汇' },
  { word: 'forlorn', phonetic: '/fəˈlɔːn/', meaning: 'adj. 孤独的；凄凉的', category: 'GRE词汇' },
  { word: 'form', phonetic: '/fɔːm/', meaning: 'n. 形式；v. 形成', category: '托福词汇' },
  { word: 'formal', phonetic: '/ˈfɔːml/', meaning: 'adj. 正式的', category: '托福词汇' },
  { word: 'formaldehyde', phonetic: '/fɔːˈmældɪhaɪd/', meaning: 'n. 甲醛', category: '科技词汇' },
  { word: 'formality', phonetic: '/fɔːˈmæləti/', meaning: 'n. 礼节；形式', category: '托福词汇' },
  { word: 'formalize', phonetic: '/ˈfɔːməlaɪz/', meaning: 'v. 使正式化', category: '商务词汇' },
  { word: 'format', phonetic: '/ˈfɔːmæt/', meaning: 'n. 格式；v. 格式化', category: '托福词汇' },
  { word: 'formation', phonetic: '/fɔːˈmeɪʃn/', meaning: 'n. 形成；队形', category: '托福词汇' },
  { word: 'former', phonetic: '/ˈfɔːmər/', meaning: 'adj. 以前的；n. 前者', category: '托福词汇' },
  { word: 'formidable', phonetic: '/fɔːˈmɪdəbl/', meaning: 'adj. 可怕的；令人敬畏的', category: 'GRE词汇' },
  { word: 'formula', phonetic: '/ˈfɔːmjələ/', meaning: 'n. 公式；配方', category: '托福词汇' },
  { word: 'formulate', phonetic: '/ˈfɔːmjuleɪt/', meaning: 'v. 制定；阐述', category: '托福词汇' },
  { word: 'formulation', phonetic: '/ˌfɔːmjuˈleɪʃn/', meaning: 'n. 制定；配方', category: '托福词汇' },
  { word: 'forsake', phonetic: '/fəˈseɪk/', meaning: 'v. 遗弃；放弃', category: 'GRE词汇' },
  { word: 'fort', phonetic: '/fɔːt/', meaning: 'n. 堡垒', category: '托福词汇' },
  { word: 'forth', phonetic: '/fɔːθ/', meaning: 'adv. 向前', category: '托福词汇' },
  { word: 'forthcoming', phonetic: '/ˌfɔːθˈkʌmɪŋ/', meaning: 'adj. 即将到来的', category: '托福词汇' },
  { word: 'forthright', phonetic: '/ˈfɔːθraɪt/', meaning: 'adj. 直率的', category: 'GRE词汇' },
  { word: 'fortify', phonetic: '/ˈfɔːtɪfaɪ/', meaning: 'v. 加强；设防', category: 'GRE词汇' },
  { word: 'fortitude', phonetic: '/ˈfɔːtɪtjuːd/', meaning: 'n. 坚韧', category: 'GRE词汇' },
  { word: 'fortnight', phonetic: '/ˈfɔːtnaɪt/', meaning: 'n. 两周', category: '托福词汇' },
  { word: 'fortress', phonetic: '/ˈfɔːtrəs/', meaning: 'n. 堡垒', category: 'GRE词汇' },
  { word: 'fortuitous', phonetic: '/fɔːˈtjuːɪtəs/', meaning: 'adj. 偶然的；幸运的', category: 'GRE词汇' },
  { word: 'fortune', phonetic: '/ˈfɔːtʃuːn/', meaning: 'n. 财富；命运', category: '托福词汇' },
  { word: 'fortunate', phonetic: '/ˈfɔːtʃənət/', meaning: 'adj. 幸运的', category: '托福词汇' },
  { word: 'forty', phonetic: '/ˈfɔːti/', meaning: 'num. 四十', category: '日常词汇' },
  { word: 'forum', phonetic: '/ˈfɔːrəm/', meaning: 'n. 论坛', category: '托福词汇' },
  { word: 'forward', phonetic: '/ˈfɔːwəd/', meaning: 'adv. 向前；adj. 向前的', category: '托福词汇' },
  { word: 'fossil', phonetic: '/ˈfɒsl/', meaning: 'n. 化石', category: '托福词汇' },
  { word: 'fossilize', phonetic: '/ˈfɒsəlaɪz/', meaning: 'v. 使石化；使僵化', category: 'GRE词汇' },
  { word: 'foster', phonetic: '/ˈfɒstər/', meaning: 'v. 培养；抚育', category: '托福词汇' },
  { word: 'foul', phonetic: '/faʊl/', meaning: 'adj. 肮脏的；v. 弄脏', category: '托福词汇' },
  { word: 'found', phonetic: '/faʊnd/', meaning: 'v. 建立；n. 铸造', category: '托福词汇' },
  { word: 'foundation', phonetic: '/faʊnˈdeɪʃn/', meaning: 'n. 基础；基金会', category: '托福词汇' },
  { word: 'founder', phonetic: '/ˈfaʊndər/', meaning: 'n. 创始人；v. 沉没', category: '托福词汇' },
  { word: 'fountain', phonetic: '/ˈfaʊntən/', meaning: 'n. 喷泉', category: '托福词汇' },
  { word: 'four', phonetic: '/fɔːr/', meaning: 'num. 四', category: '日常词汇' },
  { word: 'fourteen', phonetic: '/ˌfɔːˈtiːn/', meaning: 'num. 十四', category: '日常词汇' },
  { word: 'fourth', phonetic: '/fɔːθ/', meaning: 'adj. 第四的', category: '日常词汇' },
  { word: 'fowl', phonetic: '/faʊl/', meaning: 'n. 家禽；鸟', category: 'GRE词汇' },
  { word: 'fox', phonetic: '/fɒks/', meaning: 'n. 狐狸；v. 欺骗', category: '托福词汇' },
  { word: 'foyer', phonetic: '/ˈfɔɪeɪ/', meaning: 'n. 门厅', category: 'GRE词汇' },
  { word: 'fraction', phonetic: '/ˈfrækʃn/', meaning: 'n. 小部分；分数', category: '托福词汇' },
  { word: 'fractional', phonetic: '/ˈfrækʃənl/', meaning: 'adj. 部分的；分数的', category: '科技词汇' },
  { word: 'fracture', phonetic: '/ˈfræktʃər/', meaning: 'n. 骨折；v. 折断', category: '医学词汇' },
  { word: 'fragile', phonetic: '/ˈfrædʒaɪl/', meaning: 'adj. 易碎的；脆弱的', category: '托福词汇' },
  { word: 'fragment', phonetic: '/ˈfræɡmənt/', meaning: 'n. 碎片；v. 分裂', category: '托福词汇' },
  { word: 'fragmentary', phonetic: '/ˈfræɡməntri/', meaning: 'adj. 零碎的', category: 'GRE词汇' },
  { word: 'fragmented', phonetic: '/fræɡˈmentɪd/', meaning: 'adj. 支离破碎的', category: '托福词汇' },
  { word: 'fragrance', phonetic: '/ˈfreɪɡrəns/', meaning: 'n. 香味', category: '托福词汇' },
  { word: 'fragrant', phonetic: '/ˈfreɪɡrənt/', meaning: 'adj. 芬芳的', category: '托福词汇' },
  { word: 'frail', phonetic: '/freɪl/', meaning: 'adj. 虚弱的', category: '托福词汇' },
  { word: 'frailty', phonetic: '/ˈfreɪlti/', meaning: 'n. 脆弱；弱点', category: 'GRE词汇' },
  { word: 'frame', phonetic: '/freɪm/', meaning: 'n. 框架；v. 构筑', category: '托福词汇' },
  { word: 'framework', phonetic: '/ˈfreɪmwɜːk/', meaning: 'n. 框架', category: '托福词汇' },
  { word: 'franchise', phonetic: '/ˈfræntʃaɪz/', meaning: 'n. 特许经营权；选举权', category: '商务词汇' },
  { word: 'frank', phonetic: '/fræŋk/', meaning: 'adj. 坦率的', category: '托福词汇' },
  { word: 'frantic', phonetic: '/ˈfræntɪk/', meaning: 'adj. 疯狂的；手忙脚乱的', category: 'GRE词汇' },
  { word: 'fraternity', phonetic: '/frəˈtɜːnəti/', meaning: 'n. 兄弟会；兄弟情谊', category: 'GRE词汇' },
  { word: 'fraud', phonetic: '/frɔːd/', meaning: 'n. 欺诈；骗子', category: '法律词汇' },
  { word: 'fraudulent', phonetic: '/ˈfrɔːdʒələnt/', meaning: 'adj. 欺诈的', category: '法律词汇' },
  { word: 'fray', phonetic: '/freɪ/', meaning: 'v. 磨损；n. 争吵', category: 'GRE词汇' },
  { word: 'frazzle', phonetic: '/ˈfræzl/', meaning: 'v. 使疲惫；磨损', category: 'GRE词汇' },
  { word: 'freak', phonetic: '/friːk/', meaning: 'n. 怪人；adj. 反常的', category: '托福词汇' },
  { word: 'freakish', phonetic: '/ˈfriːkɪʃ/', meaning: 'adj. 怪异的', category: 'GRE词汇' },
  { word: 'free', phonetic: '/friː/', meaning: 'adj. 自由的；adv. 免费', category: '托福词汇' },
  { word: 'freedom', phonetic: '/ˈfriːdəm/', meaning: 'n. 自由', category: '托福词汇' },
  { word: 'freely', phonetic: '/ˈfriːli/', meaning: 'adv. 自由地', category: '托福词汇' },
  { word: 'freeze', phonetic: '/friːz/', meaning: 'v. 冻结；n. 冻结', category: '托福词汇' },
  { word: 'freight', phonetic: '/freɪt/', meaning: 'n. 货物；运费', category: '托福词汇' },
  { word: 'freightliner', phonetic: '/ˈfreɪtlaɪnər/', meaning: 'n. 货运列车', category: '商务词汇' },
  { word: 'French', phonetic: '/frentʃ/', meaning: 'adj. 法国的；n. 法语', category: '托福词汇' },
  { word: 'frenetic', phonetic: '/frəˈnetɪk/', meaning: 'adj. 狂乱的', category: 'GRE词汇' },
  { word: 'frenzy', phonetic: '/ˈfrenzi/', meaning: 'n. 狂乱', category: 'GRE词汇' },
  { word: 'frequent', phonetic: '/ˈfriːkwənt/', meaning: 'adj. 频繁的；v. 常去', category: '托福词汇' },
  { word: 'frequently', phonetic: '/ˈfriːkwəntli/', meaning: 'adv. 频繁地', category: '托福词汇' },
  { word: 'fresh', phonetic: '/freʃ/', meaning: 'adj. 新鲜的', category: '托福词汇' },
  { word: 'freshman', phonetic: '/ˈfreʃmən/', meaning: 'n. 新生；新手', category: '托福词汇' },
  { word: 'freshwater', phonetic: '/ˈfreʃwɔːtər/', meaning: 'adj. 淡水的', category: '托福词汇' },
  { word: 'fret', phonetic: '/fret/', meaning: 'v. 烦恼；n. 烦躁', category: 'GRE词汇' },
  { word: 'friction', phonetic: '/ˈfrɪkʃn/', meaning: 'n. 摩擦；冲突', category: '托福词汇' },
  { word: 'friday', phonetic: '/ˈfraɪdeɪ/', meaning: 'n. 星期五', category: '日常词汇' },
  { word: 'fridge', phonetic: '/frɪdʒ/', meaning: 'n. 冰箱', category: '日常词汇' },
  { word: 'friend', phonetic: '/frend/', meaning: 'n. 朋友', category: '托福词汇' },
  { word: 'friendliness', phonetic: '/ˈfrendlinəs/', meaning: 'n. 友好', category: '托福词汇' },
  { word: 'friendly', phonetic: '/ˈfrendli/', meaning: 'adj. 友好的', category: '托福词汇' },
  { word: 'friendship', phonetic: '/ˈfrendʃɪp/', meaning: 'n. 友谊', category: '托福词汇' },
  { word: 'fright', phonetic: '/fraɪt/', meaning: 'n. 惊吓', category: '托福词汇' },
  { word: 'frighten', phonetic: '/ˈfraɪtn/', meaning: 'v. 使惊恐', category: '托福词汇' },
  { word: 'frightened', phonetic: '/ˈfraɪtnd/', meaning: 'adj. 受惊的', category: '托福词汇' },
  { word: 'frightening', phonetic: '/ˈfraɪtnɪŋ/', meaning: 'adj. 令人恐惧的', category: '托福词汇' },
  { word: 'frightful', phonetic: '/ˈfraɪtfl/', meaning: 'adj. 可怕的', category: 'GRE词汇' },
  { word: 'frigid', phonetic: '/ˈfrɪdʒɪd/', meaning: 'adj. 寒冷的；冷淡的', category: 'GRE词汇' },
  { word: 'frill', phonetic: '/frɪl/', meaning: 'n. 褶边；装饰', category: 'GRE词汇' },
  { word: 'fringe', phonetic: '/frɪndʒ/', meaning: 'n. 边缘；刘海', category: 'GRE词汇' },
  { word: 'frivolous', phonetic: '/ˈfrɪvələs/', meaning: 'adj. 轻浮的；不严肃的', category: 'GRE词汇' },
  { word: 'frizzle', phonetic: '/ˈfrɪzl/', meaning: 'v. 煎；使卷曲', category: 'GRE词汇' },
  { word: 'fro', phonetic: '/frəʊ/', meaning: 'adv. 向后', category: 'GRE词汇' },
  { word: 'frock', phonetic: '/frɒk/', meaning: 'n. 女装；僧袍', category: 'GRE词汇' },
  { word: 'frog', phonetic: '/frɒɡ/', meaning: 'n. 青蛙', category: '托福词汇' },
  { word: 'from', phonetic: '/frɒm/', meaning: 'prep. 来自', category: '托福词汇' },
  { word: 'front', phonetic: '/frʌnt/', meaning: 'n. 前面；adj. 前面的', category: '托福词汇' },
  { word: 'frontier', phonetic: '/ˈfrʌntɪər/', meaning: 'n. 边疆；前沿', category: '托福词汇' },
  { word: 'frontline', phonetic: '/ˈfrʌntlaɪn/', meaning: 'n. 前线', category: 'GRE词汇' },
  { word: 'frost', phonetic: '/frɒst/', meaning: 'n. 霜；v. 结霜', category: '托福词汇' },
  { word: 'frosty', phonetic: '/ˈfrɒsti/', meaning: 'adj. 霜冻的；冷淡的', category: '托福词汇' },
  { word: 'froth', phonetic: '/frɒθ/', meaning: 'n. 泡沫；v. 起泡', category: 'GRE词汇' },
  { word: 'frothy', phonetic: '/ˈfrɒθi/', meaning: 'adj. 起泡的；空洞的', category: 'GRE词汇' },
  { word: 'frown', phonetic: '/fraʊn/', meaning: 'v. 皱眉；n. 皱眉', category: '托福词汇' },
  { word: 'frowzy', phonetic: '/ˈfraʊzi/', meaning: 'adj. 肮脏的；臭的', category: 'GRE词汇' },
  { word: 'froze', phonetic: '/frəʊz/', meaning: 'v. freeze的过去式', category: '托福词汇' },
  { word: 'frozen', phonetic: '/ˈfrəʊzn/', meaning: 'adj. 冻结的', category: '托福词汇' },
  { word: 'frugal', phonetic: '/ˈfruːɡl/', meaning: 'adj. 节俭的', category: 'GRE词汇' },
  { word: 'frugality', phonetic: '/fruːˈɡæləti/', meaning: 'n. 节俭', category: 'GRE词汇' },
  { word: 'fruit', phonetic: '/fruːt/', meaning: 'n. 水果；成果', category: '托福词汇' },
  { word: 'fruitful', phonetic: '/ˈfruːtfl/', meaning: 'adj. 多产的；有成效的', category: '托福词汇' },
  { word: 'fruitless', phonetic: '/ˈfruːtləs/', meaning: 'adj. 无结果的', category: '托福词汇' },
  { word: 'fruition', phonetic: '/fruːˈɪʃn/', meaning: 'n. 实现；结果', category: 'GRE词汇' },
  { word: 'frustrate', phonetic: '/frʌˈstreɪt/', meaning: 'v. 使沮丧；挫败', category: '托福词汇' },
  { word: 'frustrated', phonetic: '/frʌˈstreɪtɪd/', meaning: 'adj. 沮丧的', category: '托福词汇' },
  { word: 'frustration', phonetic: '/frʌˈstreɪʃn/', meaning: 'n. 挫败；沮丧', category: '托福词汇' },
  { word: 'frustum', phonetic: '/ˈfrʌstəm/', meaning: 'n. 截头锥体', category: '科技词汇' },
  { word: 'fry', phonetic: '/fraɪ/', meaning: 'v. 油炸；n. 油炸食品', category: '托福词汇' },
  { word: 'fryer', phonetic: '/ˈfraɪər/', meaning: 'n. 油炸锅；小鸡', category: '日常词汇' },
  { word: 'fugitive', phonetic: '/ˈfjuːdʒətɪv/', meaning: 'n. 逃亡者；adj. 逃亡的', category: 'GRE词汇' },
  { word: 'fulcrum', phonetic: '/ˈfʌlkrəm/', meaning: 'n. 支点', category: '科技词汇' },
  { word: 'fulfill', phonetic: '/fʊlˈfɪl/', meaning: 'v. 实现；履行', category: '托福词汇' },
  { word: 'fulfillment', phonetic: '/fʊlˈfɪlmənt/', meaning: 'n. 实现；满足', category: '托福词汇' },
  { word: 'full', phonetic: '/fʊl/', meaning: 'adj. 满的；adv. 完全地', category: '托福词汇' },
  { word: 'full-blown', phonetic: '/ˈfʊl bləʊn/', meaning: 'adj. 充分发展的', category: 'GRE词汇' },
  { word: 'full-fledged', phonetic: '/ˈfʊl fledʒd/', meaning: 'adj. 成熟的；完全有资格的', category: 'GRE词汇' },
  { word: 'full-scale', phonetic: '/ˈfʊl skeɪl/', meaning: 'adj. 全面的；全尺寸的', category: 'GRE词汇' },
  { word: 'full-time', phonetic: '/ˈfʊl taɪm/', meaning: 'adj. 全职的', category: '商务词汇' },
  { word: 'fumble', phonetic: '/ˈfʌmbl/', meaning: 'v. 摸索；笨拙地做', category: 'GRE词汇' },
  { word: 'fume', phonetic: '/fjuːm/', meaning: 'n. 烟气；v. 冒烟；愤怒', category: 'GRE词汇' },
  { word: 'fuming', phonetic: '/ˈfjuːmɪŋ/', meaning: 'adj. 冒烟的；愤怒的', category: 'GRE词汇' },
  { word: 'fun', phonetic: '/fʌn/', meaning: 'n. 乐趣；adj. 有趣的', category: '托福词汇' },
  { word: 'function', phonetic: '/ˈfʌŋkʃn/', meaning: 'n. 功能；v. 运行', category: '托福词汇' },
  { word: 'functional', phonetic: '/ˈfʌŋkʃənl/', meaning: 'adj. 功能的；实用的', category: '托福词汇' },
  { word: 'functionalism', phonetic: '/ˈfʌŋkʃənəlɪzəm/', meaning: 'n. 功能主义', category: 'GRE词汇' },
  { word: 'fund', phonetic: '/fʌnd/', meaning: 'n. 基金；v. 资助', category: '商务词汇' },
  { word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: 'adj. 基本的；n. 基本原理', category: '托福词汇' },
  { word: 'fundamentally', phonetic: '/ˌfʌndəˈmentəli/', meaning: 'adv. 根本地', category: '托福词汇' },
  { word: 'funding', phonetic: '/ˈfʌndɪŋ/', meaning: 'n. 资金', category: '商务词汇' },
  { word: 'funeral', phonetic: '/ˈfjuːnərəl/', meaning: 'n. 葬礼', category: '托福词汇' },
  { word: 'funnel', phonetic: '/ˈfʌnl/', meaning: 'n. 漏斗；v. 汇集', category: '托福词汇' },
  { word: 'funny', phonetic: '/ˈfʌni/', meaning: 'adj. 有趣的；奇怪的', category: '托福词汇' },
  { word: 'fur', phonetic: '/fɜːr/', meaning: 'n. 毛皮', category: '托福词汇' },
  { word: 'furious', phonetic: '/ˈfjʊəriəs/', meaning: 'adj. 狂怒的；激烈的', category: '托福词汇' },
  { word: 'furlough', phonetic: '/ˈfɜːləʊ/', meaning: 'n. 休假；v. 准假', category: '商务词汇' },
  { word: 'furnace', phonetic: '/ˈfɜːnɪs/', meaning: 'n. 熔炉', category: '托福词汇' },
  { word: 'furnish', phonetic: '/ˈfɜːnɪʃ/', meaning: 'v. 供应；布置', category: '托福词汇' },
  { word: 'furniture', phonetic: '/ˈfɜːnɪtʃər/', meaning: 'n. 家具', category: '托福词汇' },
  { word: 'furore', phonetic: '/fjʊˈrɔːri/', meaning: 'n. 轰动；狂热', category: 'GRE词汇' },
  { word: 'furor', phonetic: '/ˈfjʊərɔːr/', meaning: 'n. 狂热；轰动', category: 'GRE词汇' },
  { word: 'furry', phonetic: '/ˈfɜːri/', meaning: 'adj. 毛皮的；毛茸茸的', category: '托福词汇' },
  { word: 'furtive', phonetic: '/ˈfɜːtɪv/', meaning: 'adj. 鬼鬼祟祟的', category: 'GRE词汇' },
  { word: 'fury', phonetic: '/ˈfjʊəri/', meaning: 'n. 暴怒', category: 'GRE词汇' },
  { word: 'fuse', phonetic: '/fjuːz/', meaning: 'n. 保险丝；v. 熔合', category: '科技词汇' },
  { word: 'fusion', phonetic: '/ˈfjuːʒn/', meaning: 'n. 融合；聚变', category: '科技词汇' },
  { word: 'fuss', phonetic: '/fʌs/', meaning: 'n. 大惊小怪；v. 忙乱', category: '托福词汇' },
  { word: 'fussy', phonetic: '/ˈfʌsi/', meaning: 'adj. 爱挑剔的；大惊小怪的', category: 'GRE词汇' },
  { word: 'fustian', phonetic: '/ˈfʌstiən/', meaning: 'n. 粗斜纹布；adj. 浮夸的', category: 'GRE词汇' },
  { word: 'fusty', phonetic: '/ˈfʌsti/', meaning: 'adj. 发霉的；陈腐的', category: 'GRE词汇' },
  { word: 'futile', phonetic: '/ˈfjuːtaɪl/', meaning: 'adj. 无用的', category: 'GRE词汇' },
  { word: 'futility', phonetic: '/fjuːˈtɪləti/', meaning: 'n. 无用', category: 'GRE词汇' },
  { word: 'future', phonetic: '/ˈfjuːtʃər/', meaning: 'n. 未来；adj. 未来的', category: '托福词汇' },
  { word: 'futurist', phonetic: '/ˈfjuːtʃərɪst/', meaning: 'n. 未来主义者', category: 'GRE词汇' },
  { word: 'futuristic', phonetic: '/ˌfjuːtʃəˈrɪstɪk/', meaning: 'adj. 未来的；未来主义的', category: 'GRE词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await fetchAllFromSupabase(
    supabase.from(WORDS_TABLE).select('word')
  );
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsFI, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 F-I 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsFI.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsFI, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
