// Part 3/4 - 单词数据 Part 3
const wordsDataPart3 = [
  // D
  { word: 'dabble', phonetic: '/ˈdæbl/', meaning: 'v. 涉猎；嬉水', category: 'GRE词汇' },
  { word: 'dainty', phonetic: '/ˈdeɪnti/', meaning: 'adj. 精致的；优美的', category: 'GRE词汇' },
  { word: 'dampen', phonetic: '/ˈdæmpən/', meaning: 'v. 使潮湿；抑制', category: '托福词汇' },
  { word: 'dandy', phonetic: '/ˈdændi/', meaning: 'n. 花花公子；adj. 极好的', category: 'GRE词汇' },
  { word: 'dangle', phonetic: '/ˈdæŋɡl/', meaning: 'v. 悬挂；摇晃', category: '托福词汇' },
  { word: 'dank', phonetic: '/dæŋk/', meaning: 'adj. 阴湿的；潮湿的', category: 'GRE词汇' },
  { word: 'dapper', phonetic: '/ˈdæpər/', meaning: 'adj. 整洁的；利落的', category: 'GRE词汇' },
  { word: 'dappled', phonetic: '/ˈdæpld/', meaning: 'adj. 有斑点的', category: 'GRE词汇' },
  { word: 'dare', phonetic: '/deər/', meaning: 'v. 敢；n. 挑战', category: '托福词汇' },
  { word: 'daring', phonetic: '/ˈdeərɪŋ/', meaning: 'adj. 大胆的；勇敢的', category: '托福词汇' },
  { word: 'darken', phonetic: '/ˈdɑːkən/', meaning: 'v. 使变暗；使阴沉', category: '日常词汇' },
  { word: 'darling', phonetic: '/ˈdɑːlɪŋ/', meaning: 'n. 亲爱的；adj. 可爱的', category: '日常词汇' },
  { word: 'darn', phonetic: '/dɑːn/', meaning: 'v. 织补；n. 织补处', category: 'GRE词汇' },
  { word: 'dart', phonetic: '/dɑːt/', meaning: 'v. 飞奔；n. 镖', category: '托福词汇' },
  { word: 'dash', phonetic: '/dæʃ/', meaning: 'v. 冲；n. 破折号', category: '托福词汇' },
  { word: 'dastard', phonetic: '/ˈdæstəd/', meaning: 'n. 懦夫；卑鄙的人', category: 'GRE词汇' },
  { word: 'daunt', phonetic: '/dɔːnt/', meaning: 'v. 威吓；使气馁', category: 'GRE词汇' },
  { word: 'dauntless', phonetic: '/ˈdɔːntləs/', meaning: 'adj. 无畏的；勇敢的', category: 'GRE词汇' },
  { word: 'dawdle', phonetic: '/ˈdɔːdl/', meaning: 'v. 游荡；拖延', category: 'GRE词汇' },
  { word: 'dawn', phonetic: '/dɔːn/', meaning: 'n. 黎明；v. 开始', category: '托福词汇' },
  { word: 'daylight', phonetic: '/ˈdeɪlaɪt/', meaning: 'n. 日光；白天', category: '日常词汇' },
  { word: 'daze', phonetic: '/deɪz/', meaning: 'v. 使眩晕；n. 迷乱', category: 'GRE词汇' },
  { word: 'dazzle', phonetic: '/ˈdæzl/', meaning: 'v. 使目眩；n. 耀眼', category: '托福词汇' },
  { word: 'deactivate', phonetic: '/diːˈæktɪveɪt/', meaning: 'v. 使失效；停用', category: '科技词汇' },
  { word: 'deadlock', phonetic: '/ˈdedlɒk/', meaning: 'n. 僵局', category: '商务词汇' },
  { word: 'deadly', phonetic: '/ˈdedli/', meaning: 'adj. 致命的；adv. 非常', category: '托福词汇' },
  { word: 'deaf', phonetic: '/def/', meaning: 'adj. 聋的；不愿听的', category: '医学词汇' },
  { word: 'deafen', phonetic: '/ˈdefn/', meaning: 'v. 使聋；使听不见', category: 'GRE词汇' },
  { word: 'deal', phonetic: '/diːl/', meaning: 'n. 交易；v. 处理', category: '托福词汇' },
  { word: 'dealer', phonetic: '/ˈdiːlər/', meaning: 'n. 商人；发牌者', category: '商务词汇' },
  { word: 'dean', phonetic: '/diːn/', meaning: 'n. 院长；系主任', category: '托福词汇' },
  { word: 'dear', phonetic: '/dɪər/', meaning: 'adj. 亲爱的；昂贵的', category: '日常词汇' },
  { word: 'dearth', phonetic: '/dɜːθ/', meaning: 'n. 缺乏；短缺', category: 'GRE词汇' },
  { word: 'death', phonetic: '/deθ/', meaning: 'n. 死亡；毁灭', category: '日常词汇' },
  { word: 'debacle', phonetic: '/deɪˈbɑːkl/', meaning: 'n. 大失败；崩溃', category: 'GRE词汇' },
  { word: 'debar', phonetic: '/dɪˈbɑːr/', meaning: 'v. 禁止；排除', category: 'GRE词汇' },
  { word: 'debase', phonetic: '/dɪˈbeɪs/', meaning: 'v. 贬低；降低质量', category: 'GRE词汇' },
  { word: 'debatable', phonetic: '/dɪˈbeɪtəbl/', meaning: 'adj. 有争议的', category: '托福词汇' },
  { word: 'debate', phonetic: '/dɪˈbeɪt/', meaning: 'n. 辩论；v. 辩论', category: '托福词汇' },
  { word: 'debilitate', phonetic: '/dɪˈbɪlɪteɪt/', meaning: 'v. 使衰弱；削弱', category: 'GRE词汇' },
  { word: 'debonair', phonetic: '/ˌdebəˈneər/', meaning: 'adj. 温文尔雅的；自信的', category: 'GRE词汇' },
  { word: 'debris', phonetic: '/ˈdebriː/', meaning: 'n. 残骸；碎片', category: '托福词汇' },
  { word: 'debut', phonetic: '/ˈdeɪbjuː/', meaning: 'n. 首次亮相；v. 首次登场', category: '托福词汇' },
  { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: 'n. 十年', category: '托福词汇' },
  { word: 'decadence', phonetic: '/ˈdekədəns/', meaning: 'n. 堕落；颓废', category: 'GRE词汇' },
  { word: 'decadent', phonetic: '/ˈdekədənt/', meaning: 'adj. 颓废的；堕落的', category: 'GRE词汇' },
  { word: 'decal', phonetic: '/ˈdiːkæl/', meaning: 'n. 贴纸；印花', category: '日常词汇' },
  { word: 'decamp', phonetic: '/dɪˈkæmp/', meaning: 'v. 撤营；逃走', category: 'GRE词汇' },
  { word: 'decant', phonetic: '/dɪˈkænt/', meaning: 'v. 倾倒；移注', category: 'GRE词汇' },
  { word: 'decapitate', phonetic: '/dɪˈkæpɪteɪt/', meaning: 'v. 斩首', category: 'GRE词汇' },
  { word: 'deceive', phonetic: '/dɪˈsiːv/', meaning: 'v. 欺骗；蒙蔽', category: '托福词汇' },
  { word: 'decent', phonetic: '/ˈdiːsnt/', meaning: 'adj. 体面的；正派的', category: '托福词汇' },
  { word: 'deception', phonetic: '/dɪˈsepʃn/', meaning: 'n. 欺骗；骗局', category: '托福词汇' },
  { word: 'deceptive', phonetic: '/dɪˈseptɪv/', meaning: 'adj. 欺骗性的', category: '托福词汇' },
  { word: 'deci', phonetic: '/ˈdesi/', meaning: 'n. 分（十分之一）', category: '科技词汇' },
  { word: 'decidable', phonetic: '/dɪˈsaɪdəbl/', meaning: 'adj. 可决定的', category: '科技词汇' },
  { word: 'decimate', phonetic: '/ˈdesɪmeɪt/', meaning: 'v. 大量毁灭；大批杀死', category: 'GRE词汇' },
  { word: 'decipher', phonetic: '/dɪˈsaɪfər/', meaning: 'v. 破译；解读', category: '托福词汇' },
  { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning: 'n. 决定；决议', category: '托福词汇' },
  { word: 'decisive', phonetic: '/dɪˈsaɪsɪv/', meaning: 'adj. 决定性的；果断的', category: '托福词汇' },
  { word: 'deck', phonetic: '/dek/', meaning: 'n. 甲板；一层', category: '托福词汇' },
  { word: 'declaim', phonetic: '/dɪˈkleɪm/', meaning: 'v. 雄辩；朗诵', category: 'GRE词汇' },
  { word: 'declamation', phonetic: '/ˌdekləˈmeɪʃn/', meaning: 'n. 雄辩；朗诵', category: 'GRE词汇' },
  { word: 'declare', phonetic: '/dɪˈkleər/', meaning: 'v. 宣布；声明', category: '托福词汇' },
  { word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: 'v. 下降；拒绝', category: '托福词汇' },
  { word: 'declivity', phonetic: '/dɪˈklɪvəti/', meaning: 'n. 下坡；倾斜', category: 'GRE词汇' },
  { word: 'decoy', phonetic: '/ˈdiːkɔɪ/', meaning: 'n. 诱饵；v. 诱骗', category: 'GRE词汇' },
  { word: 'decrepit', phonetic: '/dɪˈkrepɪt/', meaning: 'adj. 衰老的；破旧的', category: 'GRE词汇' },
  { word: 'decry', phonetic: '/dɪˈkraɪ/', meaning: 'v. 责难；贬低', category: 'GRE词汇' },
  { word: 'dedicate', phonetic: '/ˈdedɪkeɪt/', meaning: 'v. 奉献；致力于', category: '托福词汇' },
  { word: 'dedication', phonetic: '/ˌdedɪˈkeɪʃn/', meaning: 'n. 奉献；献词', category: '托福词汇' },
  { word: 'deduce', phonetic: '/dɪˈdjuːs/', meaning: 'v. 推论；演绎', category: '托福词汇' },
  { word: 'deduct', phonetic: '/dɪˈdʌkt/', meaning: 'v. 扣除；减去', category: '商务词汇' },
  { word: 'deduction', phonetic: '/dɪˈdʌkʃn/', meaning: 'n. 扣除；推论', category: '托福词汇' },
  { word: 'deed', phonetic: '/diːd/', meaning: 'n. 行为；契约', category: '托福词汇' },
  { word: 'deem', phonetic: '/diːm/', meaning: 'v. 认为；视为', category: 'GRE词汇' },
  { word: 'deepen', phonetic: '/ˈdiːpən/', meaning: 'v. 加深；深化', category: '托福词汇' },
  { word: 'deface', phonetic: '/dɪˈfeɪs/', meaning: 'v. 损毁外观；涂污', category: 'GRE词汇' },
  { word: 'defame', phonetic: '/dɪˈfeɪm/', meaning: 'v. 诽谤；中伤', category: '法律词汇' },
  { word: 'default', phonetic: '/dɪˈfɔːlt/', meaning: 'n. 默认；违约', category: '商务词汇' },
  { word: 'defeat', phonetic: '/dɪˈfiːt/', meaning: 'v. 击败；n. 失败', category: '托福词汇' },
  { word: 'defect', phonetic: '/ˈdiːfekt/', meaning: 'n. 缺陷；v. 叛变', category: '托福词汇' },
  { word: 'defective', phonetic: '/dɪˈfektɪv/', meaning: 'adj. 有缺陷的', category: '托福词汇' },
  { word: 'defend', phonetic: '/dɪˈfend/', meaning: 'v. 防守；辩护', category: '托福词汇' },
  { word: 'defendant', phonetic: '/dɪˈfendənt/', meaning: 'n. 被告', category: '法律词汇' },
  { word: 'defense', phonetic: '/dɪˈfens/', meaning: 'n. 防御；辩护', category: '托福词汇' },
  { word: 'defensive', phonetic: '/dɪˈfensɪv/', meaning: 'adj. 防御的；自卫的', category: '托福词汇' },
  { word: 'defer', phonetic: '/dɪˈfɜːr/', meaning: 'v. 推迟；服从', category: 'GRE词汇' },
  { word: 'deference', phonetic: '/ˈdefərəns/', meaning: 'n. 尊重；顺从', category: 'GRE词汇' },
  { word: 'defiance', phonetic: '/dɪˈfaɪəns/', meaning: 'n. 蔑视；挑战', category: 'GRE词汇' },
  { word: 'defiant', phonetic: '/dɪˈfaɪənt/', meaning: 'adj. 挑战的；蔑视的', category: 'GRE词汇' },
  { word: 'deficiency', phonetic: '/dɪˈfɪʃnsi/', meaning: 'n. 缺乏；不足', category: '托福词汇' },
  { word: 'deficient', phonetic: '/dɪˈfɪʃnt/', meaning: 'adj. 不足的；有缺陷的', category: '托福词汇' },
  { word: 'deficit', phonetic: '/ˈdefɪsɪt/', meaning: 'n. 赤字；亏损', category: '商务词汇' },
  { word: 'defile', phonetic: '/dɪˈfaɪl/', meaning: 'v. 污损；n. 狭谷', category: 'GRE词汇' },
  { word: 'define', phonetic: '/dɪˈfaɪn/', meaning: 'v. 定义；解释', category: '托福词汇' },
  { word: 'definite', phonetic: '/ˈdefɪnət/', meaning: 'adj. 明确的；确定的', category: '托福词汇' },
  { word: 'definitive', phonetic: '/dɪˈfɪnətɪv/', meaning: 'adj. 权威的；最终的', category: 'GRE词汇' },
  { word: 'deflect', phonetic: '/dɪˈflekt/', meaning: 'v. 使偏斜；使转向', category: 'GRE词汇' },
  { word: 'deflection', phonetic: '/dɪˈflekʃn/', meaning: 'n. 偏斜；偏差', category: '科技词汇' },
  { word: 'deform', phonetic: '/dɪˈfɔːm/', meaning: 'v. 使变形；使畸形', category: '托福词汇' },
  { word: 'deformation', phonetic: '/ˌdiːfɔːˈmeɪʃn/', meaning: 'n. 变形；畸形', category: '科技词汇' },
  { word: 'defraud', phonetic: '/dɪˈfrɔːd/', meaning: 'v. 欺诈；骗取', category: '法律词汇' },
  { word: 'defray', phonetic: '/dɪˈfreɪ/', meaning: 'v. 支付；负担费用', category: 'GRE词汇' },
  { word: 'defrost', phonetic: '/ˌdiːˈfrɒst/', meaning: 'v. 除霜；解冻', category: '日常词汇' },
  { word: 'deft', phonetic: '/deft/', meaning: 'adj. 灵巧的；熟练的', category: 'GRE词汇' },
  { word: 'defunct', phonetic: '/dɪˈfʌŋkt/', meaning: 'adj. 已故的；失效的', category: 'GRE词汇' },
  { word: 'defuse', phonetic: '/ˌdiːˈfjuːz/', meaning: 'v. 拆除引信；缓和', category: '托福词汇' },
  { word: 'defy', phonetic: '/dɪˈfaɪ/', meaning: 'v. 蔑视；公然反抗', category: '托福词汇' },
  { word: 'degenerate', phonetic: '/dɪˈdʒenərət/', meaning: 'v. 退化；堕落', category: 'GRE词汇' },
  { word: 'degradation', phonetic: '/ˌdeɡrəˈdeɪʃn/', meaning: 'n. 降级；退化', category: 'GRE词汇' },
  { word: 'degrade', phonetic: '/dɪˈɡreɪd/', meaning: 'v. 降级；贬低', category: '托福词汇' },
  { word: 'degree', phonetic: '/dɪˈɡriː/', meaning: 'n. 程度；学位', category: '托福词汇' },
  { word: 'dehydrate', phonetic: '/ˌdiːˈhaɪdreɪt/', meaning: 'v. 脱水', category: '医学词汇' },
  { word: 'deify', phonetic: '/ˈdeɪfaɪ/', meaning: 'v. 神化；崇拜', category: 'GRE词汇' },
  { word: 'deign', phonetic: '/deɪn/', meaning: 'v. 屈尊；俯就', category: 'GRE词汇' },
  { word: 'deject', phonetic: '/dɪˈdʒekt/', meaning: 'v. 使沮丧', category: 'GRE词汇' },
  { word: 'dejected', phonetic: '/dɪˈdʒektɪd/', meaning: 'adj. 沮丧的；情绪低落的', category: 'GRE词汇' },
  { word: 'delay', phonetic: '/dɪˈleɪ/', meaning: 'v. 延迟；n. 延误', category: '托福词汇' },
  { word: 'delectable', phonetic: '/dɪˈlektəbl/', meaning: 'adj. 令人愉快的；美味的', category: 'GRE词汇' },
  { word: 'delegacy', phonetic: '/ˈdelɪɡəsi/', meaning: 'n. 代表权；代表团', category: 'GRE词汇' },
  { word: 'delegate', phonetic: '/ˈdelɪɡət/', meaning: 'n. 代表；v. 授权', category: '托福词汇' },
  { word: 'delete', phonetic: '/dɪˈliːt/', meaning: 'v. 删除', category: '托福词汇' },
  { word: 'deleterious', phonetic: '/ˌdeləˈtɪəriəs/', meaning: 'adj. 有害的', category: 'GRE词汇' },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', meaning: 'adj. 故意的；v. 深思', category: '托福词汇' },
  { word: 'delicacy', phonetic: '/ˈdelɪkəsi/', meaning: 'n. 精美；微妙', category: 'GRE词汇' },
  { word: 'delicate', phonetic: '/ˈdelɪkət/', meaning: 'adj. 精致的；微妙的', category: '托福词汇' },
  { word: 'delicious', phonetic: '/dɪˈlɪʃəs/', meaning: 'adj. 美味的；令人愉悦的', category: '托福词汇' },
  { word: 'delight', phonetic: '/dɪˈlaɪt/', meaning: 'n. 高兴；v. 使高兴', category: '托福词汇' },
  { word: 'delimit', phonetic: '/diːˈlɪmɪt/', meaning: 'v. 定界限；划界', category: 'GRE词汇' },
  { word: 'delineate', phonetic: '/dɪˈlɪnieɪt/', meaning: 'v. 描绘；勾勒', category: 'GRE词汇' },
  { word: 'delinquency', phonetic: '/dɪˈlɪŋkwənsi/', meaning: 'n. 失职；违法行为', category: '法律词汇' },
  { word: 'delinquent', phonetic: '/dɪˈlɪŋkwənt/', meaning: 'adj. 拖欠的；n. 违法者', category: '法律词汇' },
  { word: 'delirious', phonetic: '/dɪˈlɪriəs/', meaning: 'adj. 神志不清的；极度兴奋的', category: '医学词汇' },
  { word: 'delirium', phonetic: '/dɪˈlɪriəm/', meaning: 'n. 精神错乱；谵妄', category: '医学词汇' },
  { word: 'deliver', phonetic: '/dɪˈlɪvər/', meaning: 'v. 递送；发表', category: '托福词汇' },
  { word: 'delude', phonetic: '/dɪˈluːd/', meaning: 'v. 欺骗；迷惑', category: 'GRE词汇' },
  { word: 'deluge', phonetic: '/ˈdeljuːdʒ/', meaning: 'n. 洪水；v. 淹没', category: 'GRE词汇' },
  { word: 'delusion', phonetic: '/dɪˈluːʒn/', meaning: 'n. 妄想；错觉', category: 'GRE词汇' },
  { word: 'delusive', phonetic: '/dɪˈluːsɪv/', meaning: 'adj. 欺骗的；迷惑的', category: 'GRE词汇' },
  { word: 'delve', phonetic: '/delv/', meaning: 'v. 钻研；探究', category: 'GRE词汇' },
  { word: 'demand', phonetic: '/dɪˈmɑːnd/', meaning: 'v. 要求；n. 需求', category: '托福词汇' },
  { word: 'demarcate', phonetic: '/ˈdiːmɑːkeɪt/', meaning: 'v. 划界；区分', category: 'GRE词汇' },
  { word: 'demean', phonetic: '/dɪˈmiːn/', meaning: 'v. 贬低；降低身份', category: 'GRE词汇' },
  { word: 'demeanor', phonetic: '/dɪˈmiːnər/', meaning: 'n. 行为；风度', category: 'GRE词汇' },
  { word: 'demented', phonetic: '/dɪˈmentɪd/', meaning: 'adj. 疯狂的；精神错乱的', category: '医学词汇' },
  { word: 'demerit', phonetic: '/ˌdiːˈmerɪt/', meaning: 'n. 缺点；过失', category: 'GRE词汇' },
  { word: 'demesne', phonetic: '/dɪˈmeɪn/', meaning: 'n. 领地；地产', category: 'GRE词汇' },
  { word: 'demise', phonetic: '/dɪˈmaɪz/', meaning: 'n. 死亡；转让', category: '法律词汇' },
  { word: 'demographic', phonetic: '/ˌdeməˈɡræfɪk/', meaning: 'adj. 人口统计的', category: '商务词汇' },
  { word: 'demolish', phonetic: '/dɪˈmɒlɪʃ/', meaning: 'v. 拆除；推翻', category: '托福词汇' },
  { word: 'demolition', phonetic: '/ˌdeməˈlɪʃn/', meaning: 'n. 拆除；破坏', category: '托福词汇' },
  { word: 'demon', phonetic: '/ˈdiːmən/', meaning: 'n. 恶魔；恶棍', category: 'GRE词汇' },
  { word: 'demoniac', phonetic: '/dɪˈməʊniæk/', meaning: 'adj. 魔鬼的；凶恶的', category: 'GRE词汇' },
  { word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', meaning: 'v. 证明；示范', category: '托福词汇' },
  { word: 'demonstrative', phonetic: '/dɪˈmɒnstrətɪv/', meaning: 'adj. 感情外露的；指示的', category: 'GRE词汇' },
  { word: 'demoralize', phonetic: '/dɪˈmɒrəlaɪz/', meaning: 'v. 使士气低落；使泄气', category: 'GRE词汇' },
  { word: 'demur', phonetic: '/dɪˈmɜːr/', meaning: 'v. 反对；犹豫', category: 'GRE词汇' },
  { word: 'demure', phonetic: '/dɪˈmjʊər/', meaning: 'adj. 端庄的；娴静的', category: 'GRE词汇' },
  { word: 'den', phonetic: '/den/', meaning: 'n. 兽穴；窝', category: '日常词汇' },
  { word: 'denial', phonetic: '/dɪˈnaɪəl/', meaning: 'n. 否认；拒绝', category: '托福词汇' },
  { word: 'denigrate', phonetic: '/ˈdenɪɡreɪt/', meaning: 'v. 诋毁；贬低', category: 'GRE词汇' },
  { word: 'denizen', phonetic: '/ˈdenɪzn/', meaning: 'n. 居民；常客', category: 'GRE词汇' },
  { word: 'denominate', phonetic: '/dɪˈnɒmɪneɪt/', meaning: 'v. 命名；称…为', category: 'GRE词汇' },
  { word: 'denomination', phonetic: '/dɪˌnɒmɪˈneɪʃn/', meaning: 'n. 名称；面额', category: '商务词汇' },
  { word: 'denote', phonetic: '/dɪˈnəʊt/', meaning: 'v. 表示；意味着', category: '托福词汇' },
  { word: 'denounce', phonetic: '/dɪˈnaʊns/', meaning: 'v. 谴责；告发', category: 'GRE词汇' },
  { word: 'dense', phonetic: '/dens/', meaning: 'adj. 密集的；稠密的', category: '托福词汇' },
  { word: 'density', phonetic: '/ˈdensəti/', meaning: 'n. 密度', category: '科技词汇' },
  { word: 'dent', phonetic: '/dent/', meaning: 'n. 凹痕；v. 使凹陷', category: '托福词汇' },
  { word: 'dental', phonetic: '/ˈdentl/', meaning: 'adj. 牙齿的', category: '医学词汇' },
  { word: 'denture', phonetic: '/ˈdentʃər/', meaning: 'n. 假牙', category: '医学词汇' },
  { word: 'denude', phonetic: '/dɪˈnjuːd/', meaning: 'v. 剥光；剥夺', category: 'GRE词汇' },
  { word: 'denunciation', phonetic: '/dɪˌnʌnsiˈeɪʃn/', meaning: 'n. 谴责；告发', category: 'GRE词汇' },
  { word: 'deny', phonetic: '/dɪˈnaɪ/', meaning: 'v. 否认；拒绝', category: '托福词汇' },
  { word: 'deodorant', phonetic: '/diːˈəʊdərənt/', meaning: 'n. 除臭剂', category: '日常词汇' },
  { word: 'depart', phonetic: '/dɪˈpɑːt/', meaning: 'v. 离开；出发', category: '托福词汇' },
  { word: 'department', phonetic: '/dɪˈpɑːtmənt/', meaning: 'n. 部门；系', category: '托福词汇' },
  { word: 'departure', phonetic: '/dɪˈpɑːtʃər/', meaning: 'n. 离开；出发', category: '托福词汇' },
  { word: 'depict', phonetic: '/dɪˈpɪkt/', meaning: 'v. 描绘；描述', category: '托福词汇' },
  { word: 'deplete', phonetic: '/dɪˈpliːt/', meaning: 'v. 耗尽；使枯竭', category: 'GRE词汇' },
  { word: 'deplore', phonetic: '/dɪˈplɔːr/', meaning: 'v. 谴责；哀叹', category: 'GRE词汇' },
  { word: 'deploy', phonetic: '/dɪˈplɔɪ/', meaning: 'v. 部署；调动', category: '托福词汇' },
  { word: 'deport', phonetic: '/dɪˈpɔːt/', meaning: 'v. 驱逐出境；行为', category: '法律词汇' },
  { word: 'deportment', phonetic: '/dɪˈpɔːtmənt/', meaning: 'n. 行为；风度', category: 'GRE词汇' },
  { word: 'depose', phonetic: '/dɪˈpəʊz/', meaning: 'v. 免职；作证', category: '法律词汇' },
  { word: 'deposit', phonetic: '/dɪˈpɒzɪt/', meaning: 'n. 存款；v. 存放', category: '商务词汇' },
  { word: 'depot', phonetic: '/ˈdepəʊ/', meaning: 'n. 仓库；车站', category: '商务词汇' },
  { word: 'deprave', phonetic: '/dɪˈpreɪv/', meaning: 'v. 使堕落；使腐败', category: 'GRE词汇' },
  { word: 'depraved', phonetic: '/dɪˈpreɪvd/', meaning: 'adj. 堕落的；腐败的', category: 'GRE词汇' },
  { word: 'deprecate', phonetic: '/ˈdeprəkeɪt/', meaning: 'v. 反对；不赞成', category: 'GRE词汇' },
  { word: 'depreciate', phonetic: '/dɪˈpriːʃieɪt/', meaning: 'v. 贬值；贬低', category: '商务词汇' },
  { word: 'deprecatory', phonetic: '/ˈdeprəkətəri/', meaning: 'adj. 反对的；不赞成的', category: 'GRE词汇' },
  { word: 'depress', phonetic: '/dɪˈpres/', meaning: 'v. 使沮丧；抑制', category: '托福词汇' },
  { word: 'depression', phonetic: '/dɪˈpreʃn/', meaning: 'n. 抑郁；萧条', category: '医学词汇' },
  { word: 'deprivation', phonetic: '/ˌdeprɪˈveɪʃn/', meaning: 'n. 剥夺；匮乏', category: 'GRE词汇' },
  { word: 'deprive', phonetic: '/dɪˈpraɪv/', meaning: 'v. 剥夺；使丧失', category: '托福词汇' },
  { word: 'derange', phonetic: '/dɪˈreɪndʒ/', meaning: 'v. 扰乱；使精神错乱', category: 'GRE词汇' },
  { word: 'deranged', phonetic: '/dɪˈreɪndʒd/', meaning: 'adj. 疯狂的；精神错乱的', category: 'GRE词汇' },
  { word: 'derelict', phonetic: '/ˈderəlɪkt/', meaning: 'adj. 荒废的；n. 遗弃物', category: 'GRE词汇' },
  { word: 'deride', phonetic: '/dɪˈraɪd/', meaning: 'v. 嘲笑；嘲弄', category: 'GRE词汇' },
  { word: 'derision', phonetic: '/dɪˈrɪʒn/', meaning: 'n. 嘲笑；嘲弄', category: 'GRE词汇' },
  { word: 'derisive', phonetic: '/dɪˈraɪsɪv/', meaning: 'adj. 嘲笑的；嘲弄的', category: 'GRE词汇' },
  { word: 'derivative', phonetic: '/dɪˈrɪvətɪv/', meaning: 'adj. 衍生的；n. 衍生物', category: 'GRE词汇' },
  { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: 'v. 获得；源于', category: '托福词汇' },
  { word: 'dermatologist', phonetic: '/ˌdɜːməˈtɒlədʒɪst/', meaning: 'n. 皮肤科医生', category: '医学词汇' },
  { word: 'derogate', phonetic: '/ˈderəɡeɪt/', meaning: 'v. 贬低；减损', category: 'GRE词汇' },
  { word: 'derogatory', phonetic: '/dɪˈrɒɡətri/', meaning: 'adj. 贬低的；不敬的', category: 'GRE词汇' },
  { word: 'descend', phonetic: '/dɪˈsend/', meaning: 'v. 下降；继承', category: '托福词汇' },
  { word: 'descendant', phonetic: '/dɪˈsendənt/', meaning: 'n. 后代；后裔', category: '托福词汇' },
  { word: 'descent', phonetic: '/dɪˈsent/', meaning: 'n. 下降；血统', category: '托福词汇' },
  { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning: 'v. 描述；形容', category: '托福词汇' },
  { word: 'description', phonetic: '/dɪˈskrɪpʃn/', meaning: 'n. 描述；说明书', category: '托福词汇' },
  { word: 'desecrate', phonetic: '/ˈdesɪkreɪt/', meaning: 'v. 亵渎；玷污', category: 'GRE词汇' },
  { word: 'desegregate', phonetic: '/ˌdiːˈseɡrɪɡeɪt/', meaning: 'v. 废除种族隔离', category: 'GRE词汇' },
  { word: 'desert', phonetic: '/ˈdezət/', meaning: 'n. 沙漠；v. 抛弃', category: '托福词汇' },
  { word: 'deserve', phonetic: '/dɪˈzɜːv/', meaning: 'v. 值得；应得', category: '托福词汇' },
  { word: 'design', phonetic: '/dɪˈzaɪn/', meaning: 'n. 设计；v. 设计', category: '托福词汇' },
  { word: 'designate', phonetic: '/ˈdezɪɡneɪt/', meaning: 'v. 指定；指派', category: '托福词汇' },
  { word: 'designation', phonetic: '/ˌdezɪɡˈneɪʃn/', meaning: 'n. 指定；名称', category: '托福词汇' },
  { word: 'designedly', phonetic: '/dɪˈzaɪnɪdli/', meaning: 'adv. 故意地；蓄意地', category: 'GRE词汇' },
  { word: 'designer', phonetic: '/dɪˈzaɪnər/', meaning: 'n. 设计师', category: '托福词汇' },
  { word: 'desirable', phonetic: '/dɪˈzaɪərəbl/', meaning: 'adj. 令人向往的', category: '托福词汇' },
  { word: 'desire', phonetic: '/dɪˈzaɪər/', meaning: 'v. 渴望；n. 欲望', category: '托福词汇' },
  { word: 'desist', phonetic: '/dɪˈzɪst/', meaning: 'v. 停止；克制', category: 'GRE词汇' },
  { word: 'desolate', phonetic: '/ˈdesələt/', meaning: 'adj. 荒凉的；v. 使荒凉', category: 'GRE词汇' },
  { word: 'desolation', phonetic: '/ˌdesəˈleɪʃn/', meaning: 'n. 荒凉；孤寂', category: 'GRE词汇' },
  { word: 'despair', phonetic: '/dɪˈspeər/', meaning: 'n. 绝望；v. 绝望', category: '托福词汇' },
  { word: 'desperate', phonetic: '/ˈdespərət/', meaning: 'adj. 绝望的；拼命的', category: '托福词汇' },
  { word: 'desperation', phonetic: '/ˌdespəˈreɪʃn/', meaning: 'n. 绝望；拼命', category: '托福词汇' },
  { word: 'despicable', phonetic: '/dɪˈspɪkəbl/', meaning: 'adj. 卑鄙的；可鄙的', category: 'GRE词汇' },
  { word: 'despise', phonetic: '/dɪˈspaɪz/', meaning: 'v. 鄙视；蔑视', category: 'GRE词汇' },
  { word: 'despite', phonetic: '/dɪˈspaɪt/', meaning: 'prep. 尽管；n. 恶意', category: '托福词汇' },
  { word: 'despondent', phonetic: '/dɪˈspɒndənt/', meaning: 'adj. 沮丧的；泄气的', category: 'GRE词汇' },
  { word: 'despot', phonetic: '/ˈdespɒt/', meaning: 'n. 暴君；专制君主', category: 'GRE词汇' },
  { word: 'despotic', phonetic: '/deˈspɒtɪk/', meaning: 'adj. 专制的；暴虐的', category: 'GRE词汇' },
  { word: 'despotism', phonetic: '/ˈdespətɪzəm/', meaning: 'n. 专制；暴政', category: 'GRE词汇' },
  { word: 'dessert', phonetic: '/dɪˈzɜːt/', meaning: 'n. 甜点', category: '日常词汇' },
  { word: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', meaning: 'n. 目的地', category: '托福词汇' },
  { word: 'destine', phonetic: '/ˈdestɪn/', meaning: 'v. 注定；预定', category: 'GRE词汇' },
  { word: 'destined', phonetic: '/ˈdestɪnd/', meaning: 'adj. 注定的；预定的', category: '托福词汇' },
  { word: 'destiny', phonetic: '/ˈdestəni/', meaning: 'n. 命运；定数', category: '托福词汇' },
  { word: 'destitute', phonetic: '/ˈdestɪtjuːt/', meaning: 'adj. 贫困的；缺乏的', category: 'GRE词汇' },
  { word: 'destroy', phonetic: '/dɪˈstrɔɪ/', meaning: 'v. 破坏；毁灭', category: '托福词汇' },
  { word: 'destruction', phonetic: '/dɪˈstrʌkʃn/', meaning: 'n. 破坏；毁灭', category: '托福词汇' },
  { word: 'destructive', phonetic: '/dɪˈstrʌktɪv/', meaning: 'adj. 破坏性的', category: '托福词汇' },
  { word: 'desultory', phonetic: '/ˈdesəltri/', meaning: 'adj. 散漫的；无条理的', category: 'GRE词汇' },
  { word: 'detach', phonetic: '/dɪˈtætʃ/', meaning: 'v. 分离；派遣', category: '托福词汇' },
  { word: 'detached', phonetic: '/dɪˈtætʃt/', meaning: 'adj. 分离的；客观的', category: 'GRE词汇' },
  { word: 'detachment', phonetic: '/dɪˈtætʃmənt/', meaning: 'n. 分离；超然', category: 'GRE词汇' },
  { word: 'detail', phonetic: '/ˈdiːteɪl/', meaning: 'n. 细节；v. 详述', category: '托福词汇' },
  { word: 'detain', phonetic: '/dɪˈteɪn/', meaning: 'v. 拘留；留住', category: '法律词汇' },
  { word: 'detect', phonetic: '/dɪˈtekt/', meaning: 'v. 发现；探测', category: '托福词汇' },
  { word: 'detection', phonetic: '/dɪˈtekʃn/', meaning: 'n. 发现；探测', category: '托福词汇' },
  { word: 'detective', phonetic: '/dɪˈtektɪv/', meaning: 'n. 侦探', category: '托福词汇' },
  { word: 'detector', phonetic: '/dɪˈtektər/', meaning: 'n. 探测器', category: '科技词汇' },
  { word: 'detention', phonetic: '/dɪˈtenʃn/', meaning: 'n. 拘留；留堂', category: '法律词汇' },
  { word: 'deter', phonetic: '/dɪˈtɜːr/', meaning: 'v. 阻止；威慑', category: 'GRE词汇' },
  { word: 'detergent', phonetic: '/dɪˈtɜːdʒənt/', meaning: 'n. 清洁剂；adj. 净化的', category: '日常词汇' },
  { word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', meaning: 'v. 恶化；变坏', category: '托福词汇' },
  { word: 'determination', phonetic: '/dɪˌtɜːmɪˈneɪʃn/', meaning: 'n. 决心；测定', category: '托福词汇' },
  { word: 'determine', phonetic: '/dɪˈtɜːmɪn/', meaning: 'v. 决定；确定', category: '托福词汇' },
  { word: 'deterrent', phonetic: '/dɪˈterənt/', meaning: 'n. 威慑物；adj. 威慑的', category: 'GRE词汇' },
  { word: 'detest', phonetic: '/dɪˈtest/', meaning: 'v. 厌恶；憎恨', category: 'GRE词汇' },
  { word: 'detonate', phonetic: '/ˈdetəneɪt/', meaning: 'v. 爆炸；引爆', category: 'GRE词汇' },
  { word: 'detour', phonetic: '/ˈdiːtʊər/', meaning: 'n. 绕道；v. 绕行', category: '托福词汇' },
  { word: 'detract', phonetic: '/dɪˈtrækt/', meaning: 'v. 贬低；减损', category: 'GRE词汇' },
  { word: 'detriment', phonetic: '/ˈdetrɪmənt/', meaning: 'n. 损害；不利', category: 'GRE词汇' },
  { word: 'detrimental', phonetic: '/ˌdetrɪˈmentl/', meaning: 'adj. 有害的；不利的', category: 'GRE词汇' },
  { word: 'devastate', phonetic: '/ˈdevəsteɪt/', meaning: 'v. 摧毁；使荒废', category: '托福词汇' },
  { word: 'devastating', phonetic: '/ˈdevəsteɪtɪŋ/', meaning: 'adj. 毁灭性的', category: '托福词汇' },
  { word: 'deviate', phonetic: '/ˈdiːvieɪt/', meaning: 'v. 偏离；背离', category: 'GRE词汇' },
  { word: 'deviation', phonetic: '/ˌdiːviˈeɪʃn/', meaning: 'n. 偏差；偏离', category: '托福词汇' },
  { word: 'device', phonetic: '/dɪˈvaɪs/', meaning: 'n. 设备；策略', category: '托福词汇' },
  { word: 'devil', phonetic: '/ˈdevl/', meaning: 'n. 魔鬼；恶棍', category: '日常词汇' },
  { word: 'devilish', phonetic: '/ˈdevlɪʃ/', meaning: 'adj. 邪恶的；残忍的', category: 'GRE词汇' },
  { word: 'devious', phonetic: '/ˈdiːviəs/', meaning: 'adj. 狡猾的；迂回的', category: 'GRE词汇' },
  { word: 'devisable', phonetic: '/dɪˈvaɪzəbl/', meaning: 'adj. 可发明的；可设计的', category: 'GRE词汇' },
  { word: 'devise', phonetic: '/dɪˈvaɪz/', meaning: 'v. 设计；发明', category: '托福词汇' },
  { word: 'devoid', phonetic: '/dɪˈvɔɪd/', meaning: 'adj. 缺乏的；全无的', category: 'GRE词汇' },
  { word: 'devolve', phonetic: '/dɪˈvɒlv/', meaning: 'v. 转移；移交', category: 'GRE词汇' },
  { word: 'devote', phonetic: '/dɪˈvəʊt/', meaning: 'v. 奉献；致力于', category: '托福词汇' },
  { word: 'devoted', phonetic: '/dɪˈvəʊtɪd/', meaning: 'adj. 献身的；忠诚的', category: '托福词汇' },
  { word: 'devotion', phonetic: '/dɪˈvəʊʃn/', meaning: 'n. 奉献；忠诚', category: '托福词汇' },
  { word: 'devour', phonetic: '/dɪˈvaʊər/', meaning: 'v. 吞食；贪婪地吃', category: 'GRE词汇' },
  { word: 'devout', phonetic: '/dɪˈvaʊt/', meaning: 'adj. 虔诚的；衷心的', category: 'GRE词汇' },
  { word: 'dew', phonetic: '/djuː/', meaning: 'n. 露水', category: '日常词汇' },
  { word: 'dexterity', phonetic: '/dekˈsterəti/', meaning: 'n. 灵巧；敏捷', category: 'GRE词汇' },
  { word: 'dexterous', phonetic: '/ˈdekstrəs/', meaning: 'adj. 灵巧的；熟练的', category: 'GRE词汇' },
  { word: 'diagnose', phonetic: '/ˈdaɪəɡnəʊz/', meaning: 'v. 诊断', category: '医学词汇' },
  { word: 'diagnosis', phonetic: '/ˌdaɪəɡˈnəʊsɪs/', meaning: 'n. 诊断', category: '医学词汇' },
  { word: 'diagram', phonetic: '/ˈdaɪəɡræm/', meaning: 'n. 图表；v. 用图表示', category: '托福词汇' },
  { word: 'dialect', phonetic: '/ˈdaɪəlekt/', meaning: 'n. 方言；土语', category: '托福词汇' },
  { word: 'dialectic', phonetic: '/ˌdaɪəˈlektɪk/', meaning: 'n. 辩证法；adj. 辩证的', category: 'GRE词汇' },
  { word: 'dialogue', phonetic: '/ˈdaɪəlɒɡ/', meaning: 'n. 对话；v. 对话', category: '托福词汇' },
  { word: 'diameter', phonetic: '/daɪˈæmɪtər/', meaning: 'n. 直径', category: '科技词汇' },
  { word: 'diaphanous', phonetic: '/daɪˈæfənəs/', meaning: 'adj. 透明的；朦胧的', category: 'GRE词汇' },
  { word: 'diatribe', phonetic: '/ˈdaɪətraɪb/', meaning: 'n. 谴责；抨击', category: 'GRE词汇' },
  { word: 'dichotomy', phonetic: '/daɪˈkɒtəmi/', meaning: 'n. 二分法；对立', category: 'GRE词汇' },
  { word: 'dictate', phonetic: '/dɪkˈteɪt/', meaning: 'v. 命令；口述', category: '托福词汇' },
  { word: 'dictation', phonetic: '/dɪkˈteɪʃn/', meaning: 'n. 口述；听写', category: '托福词汇' },
  { word: 'dictator', phonetic: '/dɪkˈteɪtər/', meaning: 'n. 独裁者', category: '托福词汇' },
  { word: 'dictatorial', phonetic: '/ˌdɪktəˈtɔːriəl/', meaning: 'adj. 独裁的；专横的', category: 'GRE词汇' },
  { word: 'diction', phonetic: '/ˈdɪkʃn/', meaning: 'n. 用词；措辞', category: 'GRE词汇' },
  { word: 'dictionary', phonetic: '/ˈdɪkʃənri/', meaning: 'n. 词典', category: '托福词汇' },
  { word: 'didactic', phonetic: '/daɪˈdæktɪk/', meaning: 'adj. 说教的；教导的', category: 'GRE词汇' },
  { word: 'die', phonetic: '/daɪ/', meaning: 'v. 死；n. 骰子', category: '日常词汇' },
  { word: 'diet', phonetic: '/ˈdaɪət/', meaning: 'n. 饮食；v. 节食', category: '托福词汇' },
  { word: 'dietary', phonetic: '/ˈdaɪətəri/', meaning: 'adj. 饮食的；n. 饮食规定', category: '医学词汇' },
  { word: 'differ', phonetic: '/ˈdɪfər/', meaning: 'v. 不同；意见不合', category: '托福词汇' },
  { word: 'difference', phonetic: '/ˈdɪfrəns/', meaning: 'n. 差异；分歧', category: '托福词汇' },
  { word: 'different', phonetic: '/ˈdɪfrənt/', meaning: 'adj. 不同的', category: '托福词汇' },
  { word: 'differential', phonetic: '/ˌdɪfəˈrenʃl/', meaning: 'adj. 差异的；n. 差别', category: '科技词汇' },
  { word: 'differentiate', phonetic: '/ˌdɪfəˈrenʃieɪt/', meaning: 'v. 区分；区别', category: '托福词汇' },
  { word: 'difficult', phonetic: '/ˈdɪfɪkəlt/', meaning: 'adj. 困难的', category: '托福词汇' },
  { word: 'difficulty', phonetic: '/ˈdɪfɪkəlti/', meaning: 'n. 困难；难题', category: '托福词汇' },
  { word: 'diffidence', phonetic: '/ˈdɪfɪdəns/', meaning: 'n. 缺乏自信；羞怯', category: 'GRE词汇' },
  { word: 'diffident', phonetic: '/ˈdɪfɪdənt/', meaning: 'adj. 缺乏自信的；羞怯的', category: 'GRE词汇' },
  { word: 'diffuse', phonetic: '/dɪˈfjuːz/', meaning: 'v. 扩散；adj. 弥漫的', category: 'GRE词汇' },
  { word: 'diffusion', phonetic: '/dɪˈfjuːʒn/', meaning: 'n. 扩散；传播', category: '科技词汇' },
  { word: 'dig', phonetic: '/dɪɡ/', meaning: 'v. 挖；n. 挖掘', category: '日常词汇' },
  { word: 'digest', phonetic: '/daɪˈdʒest/', meaning: 'v. 消化；理解', category: '托福词汇' },
  { word: 'digestion', phonetic: '/daɪˈdʒestʃən/', meaning: 'n. 消化；吸收', category: '医学词汇' },
  { word: 'digit', phonetic: '/ˈdɪdʒɪt/', meaning: 'n. 数字；手指', category: '科技词汇' },
  { word: 'digital', phonetic: '/ˈdɪdʒɪtl/', meaning: 'adj. 数字的', category: '科技词汇' },
  { word: 'dignified', phonetic: '/ˈdɪɡnɪfaɪd/', meaning: 'adj. 庄严的；高贵的', category: 'GRE词汇' },
  { word: 'dignitary', phonetic: '/ˈdɪɡnɪtəri/', meaning: 'n. 显要人物；权贵', category: 'GRE词汇' },
  { word: 'dignity', phonetic: '/ˈdɪɡnəti/', meaning: 'n. 尊严；高贵', category: '托福词汇' },
  { word: 'digress', phonetic: '/daɪˈɡres/', meaning: 'v. 离题；偏离', category: 'GRE词汇' },
  { word: 'digression', phonetic: '/daɪˈɡreʃn/', meaning: 'n. 离题；偏离', category: 'GRE词汇' },
  { word: 'dilate', phonetic: '/daɪˈleɪt/', meaning: 'v. 扩大；膨胀', category: '医学词汇' },
  { word: 'dilatory', phonetic: '/ˈdɪlətəri/', meaning: 'adj. 拖延的；慢吞吞的', category: 'GRE词汇' },
  { word: 'dilemma', phonetic: '/dɪˈlemə/', meaning: 'n. 困境；进退两难', category: '托福词汇' },
  { word: 'dilettante', phonetic: '/ˌdɪləˈtænti/', meaning: 'n. 业余爱好者；半瓶醋', category: 'GRE词汇' },
  { word: 'diligence', phonetic: '/ˈdɪlɪdʒəns/', meaning: 'n. 勤奋；努力', category: '托福词汇' },
  { word: 'diligent', phonetic: '/ˈdɪlɪdʒənt/', meaning: 'adj. 勤奋的；努力的', category: '托福词汇' },
  { word: 'dill', phonetic: '/dɪl/', meaning: 'n. 莳萝（香草）', category: '日常词汇' },
  { word: 'dilute', phonetic: '/daɪˈljuːt/', meaning: 'v. 稀释；adj. 稀释的', category: '托福词汇' },
  { word: 'dim', phonetic: '/dɪm/', meaning: 'adj. 昏暗的；v. 使昏暗', category: '托福词汇' },
  { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', meaning: 'v. 减少；缩小', category: '托福词汇' },
  { word: 'diminution', phonetic: '/ˌdɪmɪˈnjuːʃn/', meaning: 'n. 减少；缩小', category: 'GRE词汇' },
  { word: 'dimple', phonetic: '/ˈdɪmpl/', meaning: 'n. 酒窝；v. 起涟漪', category: 'GRE词汇' },
  { word: 'din', phonetic: '/dɪn/', meaning: 'n. 喧闹声；v. 喧闹', category: 'GRE词汇' },
  { word: 'dine', phonetic: '/daɪn/', meaning: 'v. 进餐', category: '托福词汇' },
  { word: 'diner', phonetic: '/ˈdaɪnər/', meaning: 'n. 用餐者；小餐馆', category: '托福词汇' },
  { word: 'dinghy', phonetic: '/ˈdɪŋɡi/', meaning: 'n. 小船；橡皮艇', category: 'GRE词汇' },
  { word: 'dingy', phonetic: '/ˈdɪndʒi/', meaning: 'adj. 肮脏的；昏暗的', category: 'GRE词汇' },
  { word: 'dining', phonetic: '/ˈdaɪnɪŋ/', meaning: 'n. 进餐', category: '托福词汇' },
  { word: 'dinner', phonetic: '/ˈdɪnər/', meaning: 'n. 晚餐；正餐', category: '托福词汇' },
  { word: 'dint', phonetic: '/dɪnt/', meaning: 'n. 凹痕；v. 造成凹痕', category: 'GRE词汇' },
  { word: 'diocese', phonetic: '/ˈdaɪəsɪs/', meaning: 'n. 主教管区', category: 'GRE词汇' },
  { word: 'dioxide', phonetic: '/daɪˈɒksaɪd/', meaning: 'n. 二氧化物', category: '科技词汇' },
  { word: 'dip', phonetic: '/dɪp/', meaning: 'v. 浸；n. 浸泡', category: '日常词汇' },
  { word: 'diphthong', phonetic: '/ˈdɪfθɒŋ/', meaning: 'n. 双元音', category: 'GRE词汇' },
  { word: 'diploma', phonetic: '/dɪˈpləʊmə/', meaning: 'n. 文凭；毕业证书', category: '托福词汇' },
  { word: 'diplomacy', phonetic: '/dɪˈpləʊməsi/', meaning: 'n. 外交；手腕', category: '托福词汇' },
  { word: 'diplomat', phonetic: '/ˈdɪpləmæt/', meaning: 'n. 外交官', category: '托福词汇' },
  { word: 'diplomatic', phonetic: '/ˌdɪpləˈmætɪk/', meaning: 'adj. 外交的；老练的', category: '托福词汇' },
  { word: 'dire', phonetic: '/daɪər/', meaning: 'adj. 可怕的；悲惨的', category: 'GRE词汇' },
  { word: 'direct', phonetic: '/dəˈrekt/', meaning: 'adj. 直接的；v. 指导', category: '托福词汇' },
  { word: 'direction', phonetic: '/dəˈrekʃn/', meaning: 'n. 方向；指导', category: '托福词汇' },
  { word: 'directive', phonetic: '/dəˈrektɪv/', meaning: 'n. 指令；adj. 指导的', category: '商务词汇' },
  { word: 'director', phonetic: '/dəˈrektər/', meaning: 'n. 导演；董事', category: '托福词汇' },
  { word: 'directory', phonetic: '/dəˈrektəri/', meaning: 'n. 目录；通讯录', category: '托福词汇' },
  { word: 'dirge', phonetic: '/dɜːdʒ/', meaning: 'n. 挽歌；哀歌', category: 'GRE词汇' },
  { word: 'dirk', phonetic: '/dɜːk/', meaning: 'n. 短剑', category: 'GRE词汇' },
  { word: 'dirt', phonetic: '/dɜːt/', meaning: 'n. 污垢；泥土', category: '日常词汇' },
  { word: 'dirty', phonetic: '/ˈdɜːti/', meaning: 'adj. 肮脏的；v. 弄脏', category: '日常词汇' },
  { word: 'disable', phonetic: '/dɪsˈeɪbl/', meaning: 'v. 使残废；使无效', category: '托福词汇' },
  { word: 'disability', phonetic: '/ˌdɪsəˈbɪləti/', meaning: 'n. 残疾；无能', category: '托福词汇' },
  { word: 'disable', phonetic: '/dɪsˈeɪbl/', meaning: 'v. 使丧失能力；使无效', category: '科技词汇' },
  { word: 'disabuse', phonetic: '/ˌdɪsəˈbjuːz/', meaning: 'v. 纠正错误观念', category: 'GRE词汇' },
  { word: 'disadvantage', phonetic: '/ˌdɪsədˈvɑːntɪdʒ/', meaning: 'n. 不利条件；缺点', category: '托福词汇' },
  { word: 'disadvantaged', phonetic: '/ˌdɪsədˈvɑːntɪdʒd/', meaning: 'adj. 处于劣势的', category: '托福词汇' },
  { word: 'disaffected', phonetic: '/ˌdɪsəˈfektɪd/', meaning: 'adj. 不满的；愤愤不平的', category: 'GRE词汇' },
  { word: 'disaffection', phonetic: '/ˌdɪsəˈfekʃn/', meaning: 'n. 不满；背叛', category: 'GRE词汇' },
  { word: 'disagree', phonetic: '/ˌdɪsəˈɡriː/', meaning: 'v. 不同意；不一致', category: '托福词汇' },
  { word: 'disagreeable', phonetic: '/ˌdɪsəˈɡriːəbl/', meaning: 'adj. 不愉快的；难相处的', category: 'GRE词汇' },
  { word: 'disallow', phonetic: '/ˌdɪsəˈlaʊ/', meaning: 'v. 不允许；拒绝', category: 'GRE词汇' },
  { word: 'disappear', phonetic: '/ˌdɪsəˈpɪər/', meaning: 'v. 消失；失踪', category: '托福词汇' },
  { word: 'disappearance', phonetic: '/ˌdɪsəˈpɪərəns/', meaning: 'n. 消失；失踪', category: '托福词汇' },
  { word: 'disappoint', phonetic: '/ˌdɪsəˈpɔɪnt/', meaning: 'v. 使失望', category: '托福词汇' },
  { word: 'disappointment', phonetic: '/ˌdɪsəˈpɔɪntmənt/', meaning: 'n. 失望', category: '托福词汇' },
  { word: 'disapprobation', phonetic: '/ˌdɪsæprəˈbeɪʃn/', meaning: 'n. 不赞成；谴责', category: 'GRE词汇' },
  { word: 'disapproval', phonetic: '/ˌdɪsəˈpruːvl/', meaning: 'n. 不赞成', category: '托福词汇' },
  { word: 'disapprove', phonetic: '/ˌdɪsəˈpruːv/', meaning: 'v. 不赞成', category: '托福词汇' },
  { word: 'disarm', phonetic: '/dɪsˈɑːm/', meaning: 'v. 解除武装；消除敌意', category: 'GRE词汇' },
  { word: 'disarmament', phonetic: '/dɪsˈɑːməmənt/', meaning: 'n. 裁军', category: 'GRE词汇' },
  { word: 'disarmingly', phonetic: '/dɪsˈɑːmɪŋli/', meaning: 'adv. 令人消除戒心地', category: 'GRE词汇' },
  { word: 'disarray', phonetic: '/ˌdɪsəˈreɪ/', meaning: 'n. 混乱；v. 使混乱', category: 'GRE词汇' },
  { word: 'disaster', phonetic: '/dɪˈzɑːstər/', meaning: 'n. 灾难', category: '托福词汇' },
  { word: 'disastrous', phonetic: '/dɪˈzɑːstrəs/', meaning: 'adj. 灾难性的', category: '托福词汇' },
  { word: 'disavow', phonetic: '/ˌdɪsəˈvaʊ/', meaning: 'v. 否认；不承认', category: 'GRE词汇' },
  { word: 'disband', phonetic: '/dɪsˈbænd/', meaning: 'v. 解散；遣散', category: 'GRE词汇' },
  { word: 'disbar', phonetic: '/dɪsˈbɑːr/', meaning: 'v. 取消律师资格', category: '法律词汇' },
  { word: 'disbelief', phonetic: '/ˌdɪsbɪˈliːf/', meaning: 'n. 不相信；怀疑', category: '托福词汇' },
  { word: 'disburden', phonetic: '/dɪsˈbɜːdn/', meaning: 'v. 卸下负担', category: 'GRE词汇' },
  { word: 'disc', phonetic: '/dɪsk/', meaning: 'n. 圆盘；光盘', category: '科技词汇' },
  { word: 'discard', phonetic: '/dɪˈskɑːd/', meaning: 'v. 丢弃；抛弃', category: '托福词汇' },
  { word: 'discern', phonetic: '/dɪˈsɜːn/', meaning: 'v. 辨别；识别', category: 'GRE词汇' },
  { word: 'discernible', phonetic: '/dɪˈsɜːnəbl/', meaning: 'adj. 可辨别的', category: 'GRE词汇' },
  { word: 'discerning', phonetic: '/dɪˈsɜːnɪŋ/', meaning: 'adj. 有眼光的；敏锐的', category: 'GRE词汇' },
  { word: 'discharge', phonetic: '/dɪsˈtʃɑːdʒ/', meaning: 'v. 释放；放电', category: '托福词汇' },
  { word: 'disciple', phonetic: '/dɪˈsaɪpl/', meaning: 'n. 信徒；门徒', category: 'GRE词汇' },
  { word: 'disciplinarian', phonetic: '/ˌdɪsəplɪˈneəriən/', meaning: 'n. 执行纪律者', category: 'GRE词汇' },
  { word: 'disciplinary', phonetic: '/ˈdɪsəplɪnəri/', meaning: 'adj. 纪律的；惩戒的', category: '托福词汇' },
  { word: 'discipline', phonetic: '/ˈdɪsəplɪn/', meaning: 'n. 纪律；学科；v. 训练', category: '托福词汇' },
  { word: 'disclaim', phonetic: '/dɪsˈkleɪm/', meaning: 'v. 否认；放弃权利', category: 'GRE词汇' },
  { word: 'disclose', phonetic: '/dɪsˈkləʊz/', meaning: 'v. 揭露；透露', category: '托福词汇' },
  { word: 'disclosure', phonetic: '/dɪsˈkləʊʒər/', meaning: 'n. 揭露；披露', category: '商务词汇' },
  { word: 'disco', phonetic: '/ˈdɪskəʊ/', meaning: 'n. 迪斯科舞厅', category: '日常词汇' },
  { word: 'discombobulate', phonetic: '/ˌdɪskəmˈbɒbjuleɪt/', meaning: 'v. 使困惑；使慌乱', category: 'GRE词汇' },
  { word: 'discomfit', phonetic: '/dɪsˈkʌmfɪt/', meaning: 'v. 使尴尬；使挫败', category: 'GRE词汇' },
  { word: 'discomfort', phonetic: '/dɪsˈkʌmfət/', meaning: 'n. 不适；v. 使不适', category: '托福词汇' },
  { word: 'discomposure', phonetic: '/ˌdɪskəmˈpəʊʒər/', meaning: 'n. 不安；心乱', category: 'GRE词汇' },
  { word: 'disconcert', phonetic: '/ˌdɪskənˈsɜːt/', meaning: 'v. 使不安；使困惑', category: 'GRE词汇' },
  { word: 'disconciliate', phonetic: '/dɪskənˈsɪlieɪt/', meaning: 'v. 使不和睦', category: 'GRE词汇' },
  { word: 'disconnect', phonetic: '/ˌdɪskəˈnekt/', meaning: 'v. 断开；切断', category: '托福词汇' },
  { word: 'disconsolate', phonetic: '/dɪsˈkɒnsələt/', meaning: 'adj. 孤独的；忧郁的', category: 'GRE词汇' },
  { word: 'discontent', phonetic: '/ˌdɪskənˈtent/', meaning: 'n. 不满；v. 使不满', category: 'GRE词汇' },
  { word: 'discontinue', phonetic: '/ˌdɪskənˈtɪnjuː/', meaning: 'v. 停止；中断', category: '托福词汇' },
  { word: 'discontinuity', phonetic: '/ˌdɪskɒntɪˈnjuːəti/', meaning: 'n. 不连续性', category: '科技词汇' },
  { word: 'discord', phonetic: '/ˈdɪskɔːd/', meaning: 'n. 不和；纷争', category: 'GRE词汇' },
  { word: 'discordant', phonetic: '/dɪsˈkɔːdənt/', meaning: 'adj. 不一致的；不和谐的', category: 'GRE词汇' },
  { word: 'discount', phonetic: '/ˈdɪskaʊnt/', meaning: 'n. 折扣；v. 打折', category: '商务词汇' },
  { word: 'discountenance', phonetic: '/dɪsˈkaʊntənəns/', meaning: 'v. 不赞成；使尴尬', category: 'GRE词汇' },
  { word: 'discourse', phonetic: '/ˈdɪskɔːs/', meaning: 'n. 演讲；论述；v. 论述', category: 'GRE词汇' },
  { word: 'discourteous', phonetic: '/dɪsˈkɜːtiəs/', meaning: 'adj. 无礼的', category: 'GRE词汇' },
  { word: 'discover', phonetic: '/dɪˈskʌvər/', meaning: 'v. 发现', category: '托福词汇' },
  { word: 'discovery', phonetic: '/dɪˈskʌvəri/', meaning: 'n. 发现', category: '托福词汇' },
  { word: 'discredit', phonetic: '/dɪsˈkredɪt/', meaning: 'v. 使丢脸；n. 丧失名誉', category: 'GRE词汇' },
  { word: 'discreet', phonetic: '/dɪˈskriːt/', meaning: 'adj. 谨慎的；审慎的', category: 'GRE词汇' },
  { word: 'discrepancy', phonetic: '/dɪsˈkrepənsi/', meaning: 'n. 差异；不一致', category: '托福词汇' },
  { word: 'discrete', phonetic: '/dɪˈskriːt/', meaning: 'adj. 分离的；不连续的', category: 'GRE词汇' },
  { word: 'discretion', phonetic: '/dɪˈskreʃn/', meaning: 'n. 谨慎；自行决定权', category: '托福词汇' },
  { word: 'discriminate', phonetic: '/dɪˈskrɪmɪneɪt/', meaning: 'v. 歧视；区分', category: '托福词汇' },
  { word: 'discrimination', phonetic: '/dɪˌskrɪmɪˈneɪʃn/', meaning: 'n. 歧视；辨别力', category: '托福词汇' },
  { word: 'discriminatory', phonetic: '/dɪˈskrɪmɪnətəri/', meaning: 'adj. 歧视的', category: '法律词汇' },
  { word: 'discursive', phonetic: '/dɪˈskɜːsɪv/', meaning: 'adj. 散漫的；推论的', category: 'GRE词汇' },
  { word: 'discuss', phonetic: '/dɪˈskʌs/', meaning: 'v. 讨论', category: '托福词汇' },
  { word: 'discussion', phonetic: '/dɪˈskʌʃn/', meaning: 'n. 讨论', category: '托福词汇' },
  { word: 'disdain', phonetic: '/dɪsˈdeɪn/', meaning: 'v. 蔑视；n. 轻蔑', category: 'GRE词汇' },
  { word: 'disdainful', phonetic: '/dɪsˈdeɪnfl/', meaning: 'adj. 轻蔑的', category: 'GRE词汇' },
  { word: 'disease', phonetic: '/dɪˈziːz/', meaning: 'n. 疾病', category: '医学词汇' },
  { word: 'disembark', phonetic: '/ˌdɪsɪmˈbɑːk/', meaning: 'v. 下船；登陆', category: 'GRE词汇' },
  { word: 'disembodied', phonetic: '/ˌdɪsɪmˈbɒdid/', meaning: 'adj. 无实体的；空洞的', category: 'GRE词汇' },
  { word: 'disenchant', phonetic: '/ˌdɪsɪnˈtʃɑːnt/', meaning: 'v. 使醒悟；使不抱幻想', category: 'GRE词汇' },
  { word: 'disenfranchise', phonetic: '/ˌdɪsɪnˈfræntʃaɪz/', meaning: 'v. 剥夺公民权', category: 'GRE词汇' },
  { word: 'disengage', phonetic: '/ˌdɪsɪnˈɡeɪdʒ/', meaning: 'v. 脱离；解开', category: 'GRE词汇' },
  { word: 'disengage', phonetic: '/ˌdɪsɪnˈɡeɪdʒ/', meaning: 'v. 解开；脱离', category: '科技词汇' },
  { word: 'disentangle', phonetic: '/ˌdɪsɪnˈtæŋɡl/', meaning: 'v. 解开；理清', category: 'GRE词汇' },
  { word: 'disfigure', phonetic: '/dɪsˈfɪɡər/', meaning: 'v. 毁容；使变丑', category: 'GRE词汇' },
];

export { wordsDataPart3 };
