// L-M字母开头的单词 - Part 1/3
import { getSupabaseClient } from '../src/storage/database/supabase-client';
import { fetchAllFromSupabase } from '../src/lib/supabase-fetch-all';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsLM = [
  // L字母开头
  { word: 'label', phonetic: '/ˈleɪbl/', meaning: 'n. 标签；v. 贴标签', category: '托福词汇' },
  { word: 'labor', phonetic: '/ˈleɪbər/', meaning: 'n. 劳动；v. 努力工作', category: '托福词汇' },
  { word: 'laboratory', phonetic: '/ləˈbɒrətri/', meaning: 'n. 实验室', category: '托福词汇' },
  { word: 'laborious', phonetic: '/ləˈbɔːriəs/', meaning: 'adj. 艰苦的；费力的', category: 'GRE词汇' },
  { word: 'laborer', phonetic: '/ˈleɪbərər/', meaning: 'n. 劳工', category: '托福词汇' },
  { word: 'labyrinth', phonetic: '/ˈlæbərɪnθ/', meaning: 'n. 迷宫', category: 'GRE词汇' },
  { word: 'lace', phonetic: '/leɪs/', meaning: 'n. 蕾丝；v. 用带子系紧', category: '托福词汇' },
  { word: 'lacerate', phonetic: '/ˈlæsəreɪt/', meaning: 'v. 撕裂；伤害', category: 'GRE词汇' },
  { word: 'lack', phonetic: '/læk/', meaning: 'v. 缺乏；n. 缺乏', category: '托福词汇' },
  { word: 'lackluster', phonetic: '/ˈlæklʌstər/', meaning: 'adj. 平淡的；无光泽的', category: 'GRE词汇' },
  { word: 'laconic', phonetic: '/ləˈkɒnɪk/', meaning: 'adj. 简洁的', category: 'GRE词汇' },
  { word: 'lacquer', phonetic: '/ˈlækər/', meaning: 'n. 漆；v. 涂漆', category: 'GRE词汇' },
  { word: 'lactose', phonetic: '/ˈlæktəʊs/', meaning: 'n. 乳糖', category: '医学词汇' },
  { word: 'lad', phonetic: '/læd/', meaning: 'n. 少年', category: '托福词汇' },
  { word: 'ladder', phonetic: '/ˈlædər/', meaning: 'n. 梯子', category: '托福词汇' },
  { word: 'laden', phonetic: '/ˈleɪdn/', meaning: 'adj. 装满的', category: 'GRE词汇' },
  { word: 'ladle', phonetic: '/ˈleɪdl/', meaning: 'n. 长柄勺；v. 舀', category: 'GRE词汇' },
  { word: 'lady', phonetic: '/ˈleɪdi/', meaning: 'n. 女士', category: '托福词汇' },
  { word: 'lag', phonetic: '/læɡ/', meaning: 'v. 落后；n. 滞后', category: '托福词汇' },
  { word: 'lagoon', phonetic: '/ləˈɡuːn/', meaning: 'n. 礁湖', category: 'GRE词汇' },
  { word: 'lair', phonetic: '/leər/', meaning: 'n. 巢穴', category: 'GRE词汇' },
  { word: 'lake', phonetic: '/leɪk/', meaning: 'n. 湖', category: '托福词汇' },
  { word: 'lamb', phonetic: '/læm/', meaning: 'n. 羔羊', category: '托福词汇' },
  { word: 'lame', phonetic: '/leɪm/', meaning: 'adj. 跛的；v. 使跛', category: '托福词汇' },
  { word: 'lament', phonetic: '/ləˈment/', meaning: 'v. 哀悼；n. 挽歌', category: 'GRE词汇' },
  { word: 'lamentable', phonetic: '/ləˈmentəbl/', meaning: 'adj. 可悲的', category: 'GRE词汇' },
  { word: 'laminate', phonetic: '/ˈlæmɪneɪt/', meaning: 'v. 层压；n. 层压板', category: '科技词汇' },
  { word: 'lamp', phonetic: '/læmp/', meaning: 'n. 灯', category: '托福词汇' },
  { word: 'lampoon', phonetic: '/læmˈpuːn/', meaning: 'v. 讽刺；n. 讽刺文章', category: 'GRE词汇' },
  { word: 'lance', phonetic: '/lɑːns/', meaning: 'n. 长矛；v. 切开', category: 'GRE词汇' },
  { word: 'lancer', phonetic: '/ˈlɑːnsər/', meaning: 'n. 长矛骑兵', category: 'GRE词汇' },
  { word: 'land', phonetic: '/lænd/', meaning: 'n. 土地；v. 登陆', category: '托福词汇' },
  { word: 'landfall', phonetic: '/ˈlændfɔːl/', meaning: 'n. 着陆', category: 'GRE词汇' },
  { word: 'landlord', phonetic: '/ˈlændlɔːd/', meaning: 'n. 房东', category: '托福词汇' },
  { word: 'landmark', phonetic: '/ˈlændmɑːk/', meaning: 'n. 地标', category: '托福词汇' },
  { word: 'landmine', phonetic: '/ˈlændmaɪn/', meaning: 'n. 地雷', category: 'GRE词汇' },
  { word: 'landscape', phonetic: '/ˈlændskeɪp/', meaning: 'n. 风景', category: '托福词汇' },
  { word: 'landslide', phonetic: '/ˈlændslaɪd/', meaning: 'n. 山崩；压倒性胜利', category: '托福词汇' },
  { word: 'lane', phonetic: '/leɪn/', meaning: 'n. 小巷；车道', category: '托福词汇' },
  { word: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning: 'n. 语言', category: '托福词汇' },
  { word: 'languid', phonetic: '/ˈlæŋɡwɪd/', meaning: 'adj. 无精打采的', category: 'GRE词汇' },
  { word: 'languish', phonetic: '/ˈlæŋɡwɪʃ/', meaning: 'v. 变得衰弱；渴望', category: 'GRE词汇' },
  { word: 'languor', phonetic: '/ˈlæŋɡər/', meaning: 'n. 倦怠', category: 'GRE词汇' },
  { word: 'lanky', phonetic: '/ˈlæŋki/', meaning: 'adj. 瘦长的', category: 'GRE词汇' },
  { word: 'lantern', phonetic: '/ˈlæntən/', meaning: 'n. 灯笼', category: '托福词汇' },
  { word: 'lap', phonetic: '/læp/', meaning: 'n. 大腿；v. 舔', category: '托福词汇' },
  { word: 'lapse', phonetic: '/læps/', meaning: 'n. 失误；v. 失效', category: '托福词汇' },
  { word: 'laptop', phonetic: '/ˈlæptɒp/', meaning: 'n. 笔记本电脑', category: '托福词汇' },
  { word: 'larceny', phonetic: '/ˈlɑːsəni/', meaning: 'n. 盗窃罪', category: '法律词汇' },
  { word: 'lard', phonetic: '/lɑːd/', meaning: 'n. 猪油', category: 'GRE词汇' },
  { word: 'large', phonetic: '/lɑːdʒ/', meaning: 'adj. 大的', category: '托福词汇' },
  { word: 'largely', phonetic: '/ˈlɑːdʒli/', meaning: 'adv. 主要地', category: '托福词汇' },
  { word: 'largesse', phonetic: '/lɑːˈdʒes/', meaning: 'n. 慷慨', category: 'GRE词汇' },
  { word: 'lark', phonetic: '/lɑːk/', meaning: 'n. 云雀；玩笑', category: 'GRE词汇' },
  { word: 'larva', phonetic: '/ˈlɑːvə/', meaning: 'n. 幼虫', category: '托福词汇' },
  { word: 'larynx', phonetic: '/ˈlærɪŋks/', meaning: 'n. 喉', category: '医学词汇' },
  { word: 'laser', phonetic: '/ˈleɪzər/', meaning: 'n. 激光', category: '科技词汇' },
  { word: 'lash', phonetic: '/læʃ/', meaning: 'v. 鞭打；n. 睫毛', category: '托福词汇' },
  { word: 'lass', phonetic: '/læs/', meaning: 'n. 少女', category: 'GRE词汇' },
  { word: 'lassitude', phonetic: '/ˈlæsɪtjuːd/', meaning: 'n. 疲倦', category: 'GRE词汇' },
  { word: 'last', phonetic: '/lɑːst/', meaning: 'adj. 最后的；adv. 最后', category: '托福词汇' },
  { word: 'lasting', phonetic: '/ˈlɑːstɪŋ/', meaning: 'adj. 持久的', category: '托福词汇' },
  { word: 'latch', phonetic: '/lætʃ/', meaning: 'n. 门闩；v. 闩上', category: '托福词汇' },
  { word: 'late', phonetic: '/leɪt/', meaning: 'adj. 迟的；adv. 迟', category: '托福词汇' },
  { word: 'lately', phonetic: '/ˈleɪtli/', meaning: 'adv. 最近', category: '托福词汇' },
  { word: 'later', phonetic: '/ˈleɪtər/', meaning: 'adv. 后来', category: '托福词汇' },
  { word: 'lateral', phonetic: '/ˈlætərəl/', meaning: 'adj. 侧面的', category: '托福词汇' },
  { word: 'latest', phonetic: '/ˈleɪtɪst/', meaning: 'adj. 最新的', category: '托福词汇' },
  { word: 'latex', phonetic: '/ˈleɪteks/', meaning: 'n. 乳胶', category: '科技词汇' },
  { word: 'lath', phonetic: '/lɑːθ/', meaning: 'n. 板条', category: 'GRE词汇' },
  { word: 'lathe', phonetic: '/leɪð/', meaning: 'n. 车床', category: '科技词汇' },
  { word: 'lather', phonetic: '/ˈlɑːðər/', meaning: 'n. 肥皂泡；v. 涂肥皂', category: 'GRE词汇' },
  { word: 'latin', phonetic: '/ˈlætɪn/', meaning: 'n. 拉丁语；adj. 拉丁的', category: '托福词汇' },
  { word: 'latitude', phonetic: '/ˈlætɪtjuːd/', meaning: 'n. 纬度；自由度', category: '托福词汇' },
  { word: 'latrine', phonetic: '/ləˈtriːn/', meaning: 'n. 公共厕所', category: 'GRE词汇' },
  { word: 'latter', phonetic: '/ˈlætər/', meaning: 'adj. 后者的', category: '托福词汇' },
  { word: 'lattice', phonetic: '/ˈlætɪs/', meaning: 'n. 格子', category: 'GRE词汇' },
  { word: 'laud', phonetic: '/lɔːd/', meaning: 'v. 赞美；n. 赞美', category: 'GRE词汇' },
  { word: 'laudable', phonetic: '/ˈlɔːdəbl/', meaning: 'adj. 值得赞扬的', category: 'GRE词汇' },
  { word: 'laudatory', phonetic: '/ˈlɔːdətri/', meaning: 'adj. 赞美的', category: 'GRE词汇' },
  { word: 'laugh', phonetic: '/lɑːf/', meaning: 'v. 笑；n. 笑', category: '托福词汇' },
  { word: 'laughable', phonetic: '/ˈlɑːfəbl/', meaning: 'adj. 可笑的', category: 'GRE词汇' },
  { word: 'laughter', phonetic: '/ˈlɑːftər/', meaning: 'n. 笑声', category: '托福词汇' },
  { word: 'launch', phonetic: '/lɔːntʃ/', meaning: 'v. 发射；n. 发射', category: '托福词汇' },
  { word: 'launder', phonetic: '/ˈlɔːndər/', meaning: 'v. 洗涤；洗钱', category: '商务词汇' },
  { word: 'laundry', phonetic: '/ˈlɔːndri/', meaning: 'n. 洗衣店', category: '托福词汇' },
  { word: 'laurel', phonetic: '/ˈlɒrəl/', meaning: 'n. 月桂树；荣誉', category: 'GRE词汇' },
  { word: 'lava', phonetic: '/ˈlɑːvə/', meaning: 'n. 熔岩', category: '托福词汇' },
  { word: 'lavatory', phonetic: '/ˈlævətri/', meaning: 'n. 厕所', category: '托福词汇' },
  { word: 'lavender', phonetic: '/ˈlævəndər/', meaning: 'n. 薰衣草', category: '托福词汇' },
  { word: 'lavish', phonetic: '/ˈlævɪʃ/', meaning: 'adj. 奢华的；v. 挥霍', category: 'GRE词汇' },
  { word: 'law', phonetic: '/lɔː/', meaning: 'n. 法律', category: '托福词汇' },
  { word: 'lawful', phonetic: '/ˈlɔːfl/', meaning: 'adj. 合法的', category: '法律词汇' },
  { word: 'lawless', phonetic: '/ˈlɔːləs/', meaning: 'adj. 非法的', category: '法律词汇' },
  { word: 'lawn', phonetic: '/lɔːn/', meaning: 'n. 草坪', category: '托福词汇' },
  { word: 'lawsuit', phonetic: '/ˈlɔːsuːt/', meaning: 'n. 诉讼', category: '法律词汇' },
  { word: 'lawyer', phonetic: '/ˈlɔːjər/', meaning: 'n. 律师', category: '托福词汇' },
  { word: 'lax', phonetic: '/læks/', meaning: 'adj. 松弛的', category: 'GRE词汇' },
  { word: 'laxative', phonetic: '/ˈlæksətɪv/', meaning: 'n. 泻药；adj. 通便的', category: '医学词汇' },
  { word: 'lay', phonetic: '/leɪ/', meaning: 'v. 放置；adj. 世俗的', category: '托福词汇' },
  { word: 'layer', phonetic: '/ˈleɪər/', meaning: 'n. 层；v. 分层', category: '托福词汇' },
  { word: 'layman', phonetic: '/ˈleɪmən/', meaning: 'n. 外行', category: '托福词汇' },
  { word: 'layout', phonetic: '/ˈleɪaʊt/', meaning: 'n. 布局', category: '托福词汇' },
  { word: 'laze', phonetic: '/leɪz/', meaning: 'v. 懒散', category: 'GRE词汇' },
  { word: 'lazy', phonetic: '/ˈleɪzi/', meaning: 'adj. 懒惰的', category: '托福词汇' },
  { word: 'lea', phonetic: '/liː/', meaning: 'n. 草地', category: 'GRE词汇' },
  { word: 'leach', phonetic: '/liːtʃ/', meaning: 'v. 过滤；n. 过滤', category: '科技词汇' },
  { word: 'lead', phonetic: '/liːd/', meaning: 'v. 引导；n. 领导', category: '托福词汇' },
  { word: 'leader', phonetic: '/ˈliːdər/', meaning: 'n. 领导者', category: '托福词汇' },
  { word: 'leadership', phonetic: '/ˈliːdəʃɪp/', meaning: 'n. 领导能力', category: '托福词汇' },
  { word: 'leading', phonetic: '/ˈliːdɪŋ/', meaning: 'adj. 主要的', category: '托福词汇' },
  { word: 'leaf', phonetic: '/liːf/', meaning: 'n. 叶子', category: '托福词汇' },
  { word: 'leaflet', phonetic: '/ˈliːflət/', meaning: 'n. 传单', category: '托福词汇' },
  { word: 'leafy', phonetic: '/ˈliːfi/', meaning: 'adj. 多叶的', category: '托福词汇' },
  { word: 'league', phonetic: '/liːɡ/', meaning: 'n. 联盟', category: '托福词汇' },
  { word: 'leak', phonetic: '/liːk/', meaning: 'v. 泄漏；n. 泄漏', category: '托福词汇' },
  { word: 'leakage', phonetic: '/ˈliːkɪdʒ/', meaning: 'n. 泄漏', category: '托福词汇' },
  { word: 'lean', phonetic: '/liːn/', meaning: 'v. 倾斜；adj. 瘦的', category: '托福词汇' },
  { word: 'leap', phonetic: '/liːp/', meaning: 'v. 跳跃；n. 跳跃', category: '托福词汇' },
  { word: 'learn', phonetic: '/lɜːn/', meaning: 'v. 学习', category: '托福词汇' },
  { word: 'learned', phonetic: '/ˈlɜːnɪd/', meaning: 'adj. 博学的', category: '托福词汇' },
  { word: 'learner', phonetic: '/ˈlɜːnər/', meaning: 'n. 学习者', category: '托福词汇' },
  { word: 'learning', phonetic: '/ˈlɜːnɪŋ/', meaning: 'n. 学习；知识', category: '托福词汇' },
  { word: 'lease', phonetic: '/liːs/', meaning: 'n. 租约；v. 出租', category: '托福词汇' },
  { word: 'leash', phonetic: '/liːʃ/', meaning: 'n. 皮带；v. 束缚', category: 'GRE词汇' },
  { word: 'least', phonetic: '/liːst/', meaning: 'adj. 最小的；adv. 最少', category: '托福词汇' },
  { word: 'leather', phonetic: '/ˈleðər/', meaning: 'n. 皮革', category: '托福词汇' },
  { word: 'leathery', phonetic: '/ˈleðəri/', meaning: 'adj. 似皮革的', category: 'GRE词汇' },
  { word: 'leave', phonetic: '/liːv/', meaning: 'v. 离开；n. 休假', category: '托福词汇' },
  { word: 'lecture', phonetic: '/ˈlektʃər/', meaning: 'n. 讲座；v. 演讲', category: '托福词汇' },
  { word: 'lecturer', phonetic: '/ˈlektʃərər/', meaning: 'n. 讲师', category: '托福词汇' },
  { word: 'ledge', phonetic: '/ledʒ/', meaning: 'n. 岩架', category: 'GRE词汇' },
  { word: 'ledger', phonetic: '/ˈledʒər/', meaning: 'n. 分类账', category: '商务词汇' },
  { word: 'lee', phonetic: '/liː/', meaning: 'n. 避风处', category: 'GRE词汇' },
  { word: 'leech', phonetic: '/liːtʃ/', meaning: 'n. 水蛭；吸血鬼', category: 'GRE词汇' },
  { word: 'leek', phonetic: '/liːk/', meaning: 'n. 韭菜', category: 'GRE词汇' },
  { word: 'leer', phonetic: '/lɪər/', meaning: 'v. 斜视；n. 斜视', category: 'GRE词汇' },
  { word: 'leeward', phonetic: '/ˈliːwəd/', meaning: 'adj. 下风的；n. 下风处', category: 'GRE词汇' },
  { word: 'left', phonetic: '/left/', meaning: 'adj. 左边的；n. 左边', category: '托福词汇' },
  { word: 'leftover', phonetic: '/ˈleftəʊvər/', meaning: 'n. 剩余物；adj. 剩余的', category: '托福词汇' },
  { word: 'leg', phonetic: '/leɡ/', meaning: 'n. 腿', category: '托福词汇' },
  { word: 'legacy', phonetic: '/ˈleɡəsi/', meaning: 'n. 遗产；遗留', category: '托福词汇' },
  { word: 'legal', phonetic: '/ˈliːɡl/', meaning: 'adj. 合法的', category: '托福词汇' },
  { word: 'legalize', phonetic: '/ˈliːɡəlaɪz/', meaning: 'v. 使合法化', category: '法律词汇' },
  { word: 'legend', phonetic: '/ˈledʒənd/', meaning: 'n. 传说', category: '托福词汇' },
  { word: 'legendary', phonetic: '/ˈledʒəndri/', meaning: 'adj. 传说的', category: '托福词汇' },
  { word: 'legible', phonetic: '/ˈledʒəbl/', meaning: 'adj. 清晰可读的', category: 'GRE词汇' },
  { word: 'legion', phonetic: '/ˈliːdʒən/', meaning: 'n. 军团；大量', category: 'GRE词汇' },
  { word: 'legislate', phonetic: '/ˈledʒɪsleɪt/', meaning: 'v. 立法', category: '法律词汇' },
  { word: 'legislation', phonetic: '/ˌledʒɪsˈleɪʃn/', meaning: 'n. 立法', category: '法律词汇' },
  { word: 'legislative', phonetic: '/ˈledʒɪslətɪv/', meaning: 'adj. 立法的', category: '法律词汇' },
  { word: 'legislator', phonetic: '/ˈledʒɪsleɪtər/', meaning: 'n. 立法者', category: '法律词汇' },
  { word: 'legislature', phonetic: '/ˈledʒɪslətʃər/', meaning: 'n. 立法机关', category: '法律词汇' },
  { word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', meaning: 'adj. 合法的；v. 使合法', category: '托福词汇' },
  { word: 'legitimize', phonetic: '/lɪˈdʒɪtɪmaɪz/', meaning: 'v. 使合法化', category: 'GRE词汇' },
  { word: 'leisure', phonetic: '/ˈleʒər/', meaning: 'n. 闲暇', category: '托福词汇' },
  { word: 'lemon', phonetic: '/ˈlemən/', meaning: 'n. 柠檬', category: '托福词汇' },
  { word: 'lemonade', phonetic: '/ˌleməˈneɪd/', meaning: 'n. 柠檬水', category: '托福词汇' },
  { word: 'lend', phonetic: '/lend/', meaning: 'v. 借出', category: '托福词汇' },
  { word: 'lender', phonetic: '/ˈlendər/', meaning: 'n. 放贷人', category: '商务词汇' },
  { word: 'length', phonetic: '/leŋθ/', meaning: 'n. 长度', category: '托福词汇' },
  { word: 'lengthen', phonetic: '/ˈleŋθən/', meaning: 'v. 延长', category: '托福词汇' },
  { word: 'lengthy', phonetic: '/ˈleŋθi/', meaning: 'adj. 冗长的', category: '托福词汇' },
  { word: 'leniency', phonetic: '/ˈliːniənsi/', meaning: 'n. 宽大', category: 'GRE词汇' },
  { word: 'lenient', phonetic: '/ˈliːniənt/', meaning: 'adj. 宽大的', category: 'GRE词汇' },
  { word: 'lens', phonetic: '/lenz/', meaning: 'n. 透镜；晶状体', category: '托福词汇' },
  { word: 'lent', phonetic: '/lent/', meaning: 'n. 大斋期', category: 'GRE词汇' },
  { word: 'leopard', phonetic: '/ˈlepəd/', meaning: 'n. 豹', category: '托福词汇' },
  { word: 'leprosy', phonetic: '/ˈleprəsi/', meaning: 'n. 麻风病', category: '医学词汇' },
  { word: 'lesion', phonetic: '/ˈliːʒn/', meaning: 'n. 损伤；病变', category: '医学词汇' },
  { word: 'less', phonetic: '/les/', meaning: 'adj. 较少的；adv. 较少', category: '托福词汇' },
  { word: 'lessen', phonetic: '/ˈlesn/', meaning: 'v. 减少', category: '托福词汇' },
  { word: 'lesser', phonetic: '/ˈlesər/', meaning: 'adj. 较小的', category: '托福词汇' },
  { word: 'lesson', phonetic: '/ˈlesn/', meaning: 'n. 课程；教训', category: '托福词汇' },
  { word: 'lessor', phonetic: '/leˈsɔːr/', meaning: 'n. 出租人', category: '商务词汇' },
  { word: 'lest', phonetic: '/lest/', meaning: 'conj. 唯恐', category: 'GRE词汇' },
  { word: 'let', phonetic: '/let/', meaning: 'v. 让；出租', category: '托福词汇' },
  { word: 'lethal', phonetic: '/ˈliːθl/', meaning: 'adj. 致命的', category: '托福词汇' },
  { word: 'lethargic', phonetic: '/lɪˈθɑːdʒɪk/', meaning: 'adj. 昏睡的', category: 'GRE词汇' },
  { word: 'lethargy', phonetic: '/ˈleθədʒi/', meaning: 'n. 昏睡', category: 'GRE词汇' },
  { word: 'letter', phonetic: '/ˈletər/', meaning: 'n. 信；字母', category: '托福词汇' },
  { word: 'letterhead', phonetic: '/ˈletərhed/', meaning: 'n. 信头', category: '商务词汇' },
  { word: 'lettuce', phonetic: '/ˈletɪs/', meaning: 'n. 生菜', category: '托福词汇' },
  { word: 'leukemia', phonetic: '/luːˈkiːmiə/', meaning: 'n. 白血病', category: '医学词汇' },
  { word: 'level', phonetic: '/ˈlevl/', meaning: 'n. 水平；adj. 平的', category: '托福词汇' },
  { word: 'levy', phonetic: '/ˈlevi/', meaning: 'v. 征收；n. 征税', category: '商务词汇' },
  { word: 'lewd', phonetic: '/luːd/', meaning: 'adj. 淫荡的', category: 'GRE词汇' },
  { word: 'lexical', phonetic: '/ˈleksɪkl/', meaning: 'adj. 词汇的', category: 'GRE词汇' },
  { word: 'lexicon', phonetic: '/ˈleksɪkən/', meaning: 'n. 词典', category: 'GRE词汇' },
  { word: 'liability', phonetic: '/ˌlaɪəˈbɪləti/', meaning: 'n. 责任；债务', category: '商务词汇' },
  { word: 'liable', phonetic: '/ˈlaɪəbl/', meaning: 'adj. 有责任的；可能的', category: '托福词汇' },
  { word: 'liaison', phonetic: '/liˈeɪzɒn/', meaning: 'n. 联络', category: '商务词汇' },
  { word: 'liar', phonetic: '/ˈlaɪər/', meaning: 'n. 说谎者', category: '托福词汇' },
  { word: 'libel', phonetic: '/ˈlaɪbl/', meaning: 'n. 诽谤；v. 诽谤', category: '法律词汇' },
  { word: 'liberal', phonetic: '/ˈlɪbərəl/', meaning: 'adj. 自由的；慷慨的', category: '托福词汇' },
  { word: 'liberalism', phonetic: '/ˈlɪbərəlɪzəm/', meaning: 'n. 自由主义', category: 'GRE词汇' },
  { word: 'liberalize', phonetic: '/ˈlɪbərəlaɪz/', meaning: 'v. 使自由化', category: 'GRE词汇' },
  { word: 'liberate', phonetic: '/ˈlɪbəreɪt/', meaning: 'v. 解放', category: '托福词汇' },
  { word: 'liberation', phonetic: '/ˌlɪbəˈreɪʃn/', meaning: 'n. 解放', category: '托福词汇' },
  { word: 'liberty', phonetic: '/ˈlɪbəti/', meaning: 'n. 自由', category: '托福词汇' },
  { word: 'librarian', phonetic: '/laɪˈbreəriən/', meaning: 'n. 图书管理员', category: '托福词汇' },
  { word: 'library', phonetic: '/ˈlaɪbrəri/', meaning: 'n. 图书馆', category: '托福词汇' },
  { word: 'lice', phonetic: '/laɪs/', meaning: 'n. louse的复数形式', category: 'GRE词汇' },
  { word: 'license', phonetic: '/ˈlaɪsns/', meaning: 'n. 执照；v. 发许可证', category: '托福词汇' },
  { word: 'licentious', phonetic: '/laɪˈsenʃəs/', meaning: 'adj. 放荡的', category: 'GRE词汇' },
  { word: 'lick', phonetic: '/lɪk/', meaning: 'v. 舔；n. 舔', category: '托福词汇' },
  { word: 'lid', phonetic: '/lɪd/', meaning: 'n. 盖子', category: '托福词汇' },
  { word: 'lie', phonetic: '/laɪ/', meaning: 'v. 躺；n. 谎言', category: '托福词汇' },
  { word: 'lieu', phonetic: '/ljuː/', meaning: 'n. 场所', category: 'GRE词汇' },
  { word: 'lieutenant', phonetic: '/lefˈtenənt/', meaning: 'n. 中尉', category: 'GRE词汇' },
  { word: 'life', phonetic: '/laɪf/', meaning: 'n. 生命；生活', category: '托福词汇' },
  { word: 'lifeboat', phonetic: '/ˈlaɪfbəʊt/', meaning: 'n. 救生艇', category: '托福词汇' },
  { word: 'lifelong', phonetic: '/ˈlaɪflɒŋ/', meaning: 'adj. 终身的', category: '托福词汇' },
  { word: 'lifestyle', phonetic: '/ˈlaɪfstaɪl/', meaning: 'n. 生活方式', category: '托福词汇' },
  { word: 'lifetime', phonetic: '/ˈlaɪftaɪm/', meaning: 'n. 一生', category: '托福词汇' },
  { word: 'lift', phonetic: '/lɪft/', meaning: 'v. 举起；n. 电梯', category: '托福词汇' },
  { word: 'ligament', phonetic: '/ˈlɪɡəmənt/', meaning: 'n. 韧带', category: '医学词汇' },
  { word: 'light', phonetic: '/laɪt/', meaning: 'n. 光；adj. 轻的', category: '托福词汇' },
  { word: 'lighten', phonetic: '/ˈlaɪtn/', meaning: 'v. 减轻；发亮', category: '托福词汇' },
  { word: 'lighter', phonetic: '/ˈlaɪtər/', meaning: 'n. 打火机', category: '托福词汇' },
  { word: 'lightning', phonetic: '/ˈlaɪtnɪŋ/', meaning: 'n. 闪电', category: '托福词汇' },
  { word: 'lightweight', phonetic: '/ˈlaɪtweɪt/', meaning: 'n. 轻量级选手；adj. 轻量的', category: '托福词汇' },
  { word: 'ligneous', phonetic: '/ˈlɪɡniəs/', meaning: 'adj. 木质的', category: 'GRE词汇' },
  { word: 'likable', phonetic: '/ˈlaɪkəbl/', meaning: 'adj. 可爱的', category: '托福词汇' },
  { word: 'like', phonetic: '/laɪk/', meaning: 'v. 喜欢；prep. 像', category: '托福词汇' },
  { word: 'likelihood', phonetic: '/ˈlaɪklihʊd/', meaning: 'n. 可能性', category: '托福词汇' },
  { word: 'likely', phonetic: '/ˈlaɪkli/', meaning: 'adj. 可能的；adv. 可能', category: '托福词汇' },
  { word: 'liken', phonetic: '/ˈlaɪkən/', meaning: 'v. 比作', category: 'GRE词汇' },
  { word: 'likeness', phonetic: '/ˈlaɪknəs/', meaning: 'n. 相似', category: 'GRE词汇' },
  { word: 'likewise', phonetic: '/ˈlaɪkwaɪz/', meaning: 'adv. 同样地', category: '托福词汇' },
  { word: 'lilac', phonetic: '/ˈlaɪlək/', meaning: 'n. 丁香花', category: 'GRE词汇' },
  { word: 'lilt', phonetic: '/lɪlt/', meaning: 'n. 轻快的节奏', category: 'GRE词汇' },
  { word: 'limb', phonetic: '/lɪm/', meaning: 'n. 肢体；树枝', category: '托福词汇' },
  { word: 'limber', phonetic: '/ˈlɪmbər/', meaning: 'adj. 柔软的', category: 'GRE词汇' },
  { word: 'lime', phonetic: '/laɪm/', meaning: 'n. 酸橙；石灰', category: '托福词汇' },
  { word: 'limelight', phonetic: '/ˈlaɪmlaɪt/', meaning: 'n. 聚光灯', category: 'GRE词汇' },
  { word: 'limestone', phonetic: '/ˈlaɪmstəʊn/', meaning: 'n. 石灰石', category: '科技词汇' },
  { word: 'limit', phonetic: '/ˈlɪmɪt/', meaning: 'n. 限制；v. 限制', category: '托福词汇' },
  { word: 'limitation', phonetic: '/ˌlɪmɪˈteɪʃn/', meaning: 'n. 限制', category: '托福词汇' },
  { word: 'limited', phonetic: '/ˈlɪmɪtɪd/', meaning: 'adj. 有限的', category: '托福词汇' },
  { word: 'limousine', phonetic: '/ˈlɪməziːn/', meaning: 'n. 豪华轿车', category: '托福词汇' },
  { word: 'limp', phonetic: '/lɪmp/', meaning: 'v. 跛行；adj. 柔软的', category: '托福词汇' },
  { word: 'limpid', phonetic: '/ˈlɪmpɪd/', meaning: 'adj. 清澈的', category: 'GRE词汇' },
  { word: 'line', phonetic: '/laɪn/', meaning: 'n. 线；v. 排队', category: '托福词汇' },
  { word: 'lineage', phonetic: '/ˈlɪniɪdʒ/', meaning: 'n. 血统', category: 'GRE词汇' },
  { word: 'lineal', phonetic: '/ˈlɪniəl/', meaning: 'adj. 直系的', category: 'GRE词汇' },
  { word: 'linear', phonetic: '/ˈlɪniər/', meaning: 'adj. 线性的', category: '托福词汇' },
  { word: 'linen', phonetic: '/ˈlɪnɪn/', meaning: 'n. 亚麻布', category: '托福词汇' },
  { word: 'liner', phonetic: '/ˈlaɪnər/', meaning: 'n. 班轮', category: '托福词汇' },
  { word: 'linger', phonetic: '/ˈlɪŋɡər/', meaning: 'v. 徘徊；拖延', category: '托福词汇' },
  { word: 'lingering', phonetic: '/ˈlɪŋɡərɪŋ/', meaning: 'adj. 拖延的', category: 'GRE词汇' },
  { word: 'linguist', phonetic: '/ˈlɪŋɡwɪst/', meaning: 'n. 语言学家', category: '托福词汇' },
  { word: 'linguistic', phonetic: '/lɪŋˈɡwɪstɪk/', meaning: 'adj. 语言的', category: '托福词汇' },
  { word: 'linguistics', phonetic: '/lɪŋˈɡwɪstɪks/', meaning: 'n. 语言学', category: '托福词汇' },
  { word: 'lining', phonetic: '/ˈlaɪnɪŋ/', meaning: 'n. 衬里', category: '托福词汇' },
  { word: 'link', phonetic: '/lɪŋk/', meaning: 'n. 链接；v. 连接', category: '托福词汇' },
  { word: 'linkage', phonetic: '/ˈlɪŋkɪdʒ/', meaning: 'n. 连接', category: '托福词汇' },
  { word: 'lion', phonetic: '/ˈlaɪən/', meaning: 'n. 狮子', category: '托福词汇' },
  { word: 'lip', phonetic: '/lɪp/', meaning: 'n. 嘴唇', category: '托福词汇' },
  { word: 'lipid', phonetic: '/ˈlɪpɪd/', meaning: 'n. 脂质', category: '医学词汇' },
  { word: 'liposuction', phonetic: '/ˈlɪpəʊsʌkʃn/', meaning: 'n. 吸脂术', category: '医学词汇' },
  { word: 'liquid', phonetic: '/ˈlɪkwɪd/', meaning: 'n. 液体；adj. 液态的', category: '托福词汇' },
  { word: 'liquidate', phonetic: '/ˈlɪkwɪdeɪt/', meaning: 'v. 清算；清除', category: '商务词汇' },
  { word: 'liquidation', phonetic: '/ˌlɪkwɪˈdeɪʃn/', meaning: 'n. 清算', category: '商务词汇' },
  { word: 'liquor', phonetic: '/ˈlɪkər/', meaning: 'n. 酒', category: '托福词汇' },
  { word: 'list', phonetic: '/lɪst/', meaning: 'n. 列表；v. 列出', category: '托福词汇' },
  { word: 'listen', phonetic: '/ˈlɪsn/', meaning: 'v. 听', category: '托福词汇' },
  { word: 'listener', phonetic: '/ˈlɪsnər/', meaning: 'n. 听众', category: '托福词汇' },
  { word: 'listless', phonetic: '/ˈlɪstləs/', meaning: 'adj. 无精打采的', category: 'GRE词汇' },
  { word: 'lit', phonetic: '/lɪt/', meaning: 'adj. 点亮的', category: '托福词汇' },
  { word: 'literal', phonetic: '/ˈlɪtərəl/', meaning: 'adj. 字面的', category: '托福词汇' },
  { word: 'literally', phonetic: '/ˈlɪtərəli/', meaning: 'adv. 字面上地', category: '托福词汇' },
  { word: 'literary', phonetic: '/ˈlɪtərəri/', meaning: 'adj. 文学的', category: '托福词汇' },
  { word: 'literate', phonetic: '/ˈlɪtərət/', meaning: 'adj. 有文化的', category: '托福词汇' },
  { word: 'literature', phonetic: '/ˈlɪtrətʃər/', meaning: 'n. 文学', category: '托福词汇' },
  { word: 'lithe', phonetic: '/laɪð/', meaning: 'adj. 柔软的', category: 'GRE词汇' },
  { word: 'lithograph', phonetic: '/ˈlɪθəɡrɑːf/', meaning: 'n. 石版画', category: 'GRE词汇' },
  { word: 'litigation', phonetic: '/ˌlɪtɪˈɡeɪʃn/', meaning: 'n. 诉讼', category: '法律词汇' },
  { word: 'litigious', phonetic: '/lɪˈtɪdʒəs/', meaning: 'adj. 好诉讼的', category: '法律词汇' },
  { word: 'litre', phonetic: '/ˈliːtər/', meaning: 'n. 升', category: '托福词汇' },
  { word: 'litter', phonetic: '/ˈlɪtər/', meaning: 'n. 垃圾；v. 乱扔', category: '托福词汇' },
  { word: 'little', phonetic: '/ˈlɪtl/', meaning: 'adj. 小的；adv. 很少', category: '托福词汇' },
  { word: 'liturgy', phonetic: '/ˈlɪtədʒi/', meaning: 'n. 礼拜仪式', category: 'GRE词汇' },
  { word: 'live', phonetic: '/lɪv/', meaning: 'v. 生活；adj. 现场的', category: '托福词汇' },
  { word: 'lively', phonetic: '/ˈlaɪvli/', meaning: 'adj. 活泼的', category: '托福词汇' },
  { word: 'liven', phonetic: '/ˈlaɪvn/', meaning: 'v. 使有生气', category: 'GRE词汇' },
  { word: 'liver', phonetic: '/ˈlɪvər/', meaning: 'n. 肝脏', category: '医学词汇' },
  { word: 'livelihood', phonetic: '/ˈlaɪvlihʊd/', meaning: 'n. 生计', category: '托福词汇' },
  { word: 'lively', phonetic: '/ˈlaɪvli/', meaning: 'adj. 生动的', category: '托福词汇' },
  { word: 'livestock', phonetic: '/ˈlaɪvstɒk/', meaning: 'n. 牲畜', category: '托福词汇' },
  { word: 'livid', phonetic: '/ˈlɪvɪd/', meaning: 'adj. 青灰色的；愤怒的', category: 'GRE词汇' },
  { word: 'living', phonetic: '/ˈlɪvɪŋ/', meaning: 'n. 生活；adj. 活着的', category: '托福词汇' },
  { word: 'lizard', phonetic: '/ˈlɪzərd/', meaning: 'n. 蜥蜴', category: '托福词汇' },
  { word: 'load', phonetic: '/ləʊd/', meaning: 'n. 负载；v. 装载', category: '托福词汇' },
  { word: 'loaf', phonetic: '/ləʊf/', meaning: 'n. 面包；v. 游荡', category: '托福词汇' },
  { word: 'loath', phonetic: '/ləʊθ/', meaning: 'adj. 不情愿的', category: 'GRE词汇' },
  { word: 'loathe', phonetic: '/ləʊð/', meaning: 'v. 憎恨', category: 'GRE词汇' },
  { word: 'loathing', phonetic: '/ˈləʊðɪŋ/', meaning: 'n. 憎恨', category: 'GRE词汇' },
  { word: 'loathsome', phonetic: '/ˈləʊðsəm/', meaning: 'adj. 令人作呕的', category: 'GRE词汇' },
  { word: 'lobby', phonetic: '/ˈlɒbi/', meaning: 'n. 大厅；v. 游说', category: '托福词汇' },
  { word: 'lobster', phonetic: '/ˈlɒbstər/', meaning: 'n. 龙虾', category: '托福词汇' },
  { word: 'local', phonetic: '/ˈləʊkl/', meaning: 'adj. 当地的', category: '托福词汇' },
  { word: 'locality', phonetic: '/ləʊˈkæləti/', meaning: 'n. 地区', category: '托福词汇' },
  { word: 'localize', phonetic: '/ˈləʊkəlaɪz/', meaning: 'v. 使局部化', category: '托福词汇' },
  { word: 'locate', phonetic: '/ləʊˈkeɪt/', meaning: 'v. 定位', category: '托福词汇' },
  { word: 'location', phonetic: '/ləʊˈkeɪʃn/', meaning: 'n. 位置', category: '托福词汇' },
  { word: 'loch', phonetic: '/lɒk/', meaning: 'n. 湖', category: 'GRE词汇' },
  { word: 'lock', phonetic: '/lɒk/', meaning: 'n. 锁；v. 锁上', category: '托福词汇' },
  { word: 'locker', phonetic: '/ˈlɒkər/', meaning: 'n. 储物柜', category: '托福词汇' },
  { word: 'lockout', phonetic: '/ˈlɒkaʊt/', meaning: 'n. 封锁', category: '商务词汇' },
  { word: 'locomotive', phonetic: '/ˌləʊkəˈməʊtɪv/', meaning: 'n. 火车头', category: '托福词汇' },
  { word: 'locust', phonetic: '/ˈləʊkəst/', meaning: 'n. 蝗虫', category: 'GRE词汇' },
  { word: 'lodge', phonetic: '/lɒdʒ/', meaning: 'n. 小屋；v. 住宿', category: '托福词汇' },
  { word: 'lodging', phonetic: '/ˈlɒdʒɪŋ/', meaning: 'n. 寄宿处', category: '托福词汇' },
  { word: 'loft', phonetic: '/lɒft/', meaning: 'n. 阁楼', category: '托福词汇' },
  { word: 'lofty', phonetic: '/ˈlɒfti/', meaning: 'adj. 高耸的；崇高的', category: 'GRE词汇' },
  { word: 'log', phonetic: '/lɒɡ/', meaning: 'n. 原木；v. 记录', category: '托福词汇' },
  { word: 'logarithm', phonetic: '/ˈlɒɡərɪðəm/', meaning: 'n. 对数', category: '科技词汇' },
  { word: 'logic', phonetic: '/ˈlɒdʒɪk/', meaning: 'n. 逻辑', category: '托福词汇' },
  { word: 'logical', phonetic: '/ˈlɒdʒɪkl/', meaning: 'adj. 合乎逻辑的', category: '托福词汇' },
  { word: 'logician', phonetic: '/ləˈdʒɪʃn/', meaning: 'n. 逻辑学家', category: 'GRE词汇' },
  { word: 'logistics', phonetic: '/ləˈdʒɪstɪks/', meaning: 'n. 后勤', category: '商务词汇' },
  { word: 'logo', phonetic: '/ˈləʊɡəʊ/', meaning: 'n. 标志', category: '托福词汇' },
  { word: 'logrolling', phonetic: '/ˈlɒɡrəʊlɪŋ/', meaning: 'n. 互相吹捧', category: 'GRE词汇' },
  { word: 'loin', phonetic: '/lɔɪn/', meaning: 'n. 腰部', category: 'GRE词汇' },
  { word: 'loiter', phonetic: '/ˈlɔɪtər/', meaning: 'v. 闲逛', category: 'GRE词汇' },
  { word: 'loll', phonetic: '/lɒl/', meaning: 'v. 懒洋洋地倚靠', category: 'GRE词汇' },
  { word: 'lonely', phonetic: '/ˈləʊnli/', meaning: 'adj. 孤独的', category: '托福词汇' },
  { word: 'lonesome', phonetic: '/ˈləʊnsəm/', meaning: 'adj. 孤独的', category: 'GRE词汇' },
  { word: 'long', phonetic: '/lɒŋ/', meaning: 'adj. 长的；v. 渴望', category: '托福词汇' },
  { word: 'longevity', phonetic: '/lɒnˈdʒevəti/', meaning: 'n. 长寿', category: 'GRE词汇' },
  { word: 'longing', phonetic: '/ˈlɒŋɪŋ/', meaning: 'n. 渴望', category: '托福词汇' },
  { word: 'longitude', phonetic: '/ˈlɒŋɡɪtjuːd/', meaning: 'n. 经度', category: '托福词汇' },
  { word: 'longstanding', phonetic: '/ˌlɒŋˈstændɪŋ/', meaning: 'adj. 长期存在的', category: 'GRE词汇' },
  { word: 'longterm', phonetic: '/ˌlɒŋˈtɜːm/', meaning: 'adj. 长期的', category: '托福词汇' },
  { word: 'look', phonetic: '/lʊk/', meaning: 'v. 看；n. 外表', category: '托福词汇' },
  { word: 'lookout', phonetic: '/ˈlʊkaʊt/', meaning: 'n. 瞭望台', category: 'GRE词汇' },
  { word: 'loom', phonetic: '/luːm/', meaning: 'n. 织布机；v. 隐约出现', category: '托福词汇' },
  { word: 'loom', phonetic: '/luːm/', meaning: 'v. 迫近', category: 'GRE词汇' },
  { word: 'loon', phonetic: '/luːn/', meaning: 'n. 潜鸟；疯子', category: 'GRE词汇' },
  { word: 'loony', phonetic: '/ˈluːni/', meaning: 'adj. 疯狂的', category: 'GRE词汇' },
  { word: 'loop', phonetic: '/luːp/', meaning: 'n. 圈；v. 成圈', category: '托福词汇' },
  { word: 'loophole', phonetic: '/ˈluːphəʊl/', meaning: 'n. 漏洞', category: '托福词汇' },
  { word: 'loose', phonetic: '/luːs/', meaning: 'adj. 松的；v. 释放', category: '托福词汇' },
  { word: 'loosen', phonetic: '/ˈluːsn/', meaning: 'v. 放松', category: '托福词汇' },
  { word: 'loot', phonetic: '/luːt/', meaning: 'n. 战利品；v. 掠夺', category: 'GRE词汇' },
  { word: 'lop', phonetic: '/lɒp/', meaning: 'v. 剪断', category: 'GRE词汇' },
  { word: 'lope', phonetic: '/ləʊp/', meaning: 'v. 大步慢跑', category: 'GRE词汇' },
  { word: 'loquacious', phonetic: '/ləˈkweɪʃəs/', meaning: 'adj. 话多的', category: 'GRE词汇' },
  { word: 'lord', phonetic: '/lɔːd/', meaning: 'n. 领主', category: '托福词汇' },
  { word: 'lorry', phonetic: '/ˈlɒri/', meaning: 'n. 卡车', category: '托福词汇' },
  { word: 'lose', phonetic: '/luːz/', meaning: 'v. 失去', category: '托福词汇' },
  { word: 'loser', phonetic: '/ˈluːzər/', meaning: 'n. 失败者', category: '托福词汇' },
  { word: 'loss', phonetic: '/lɒs/', meaning: 'n. 损失', category: '托福词汇' },
  { word: 'lost', phonetic: '/lɒst/', meaning: 'adj. 迷失的', category: '托福词汇' },
  { word: 'lot', phonetic: '/lɒt/', meaning: 'n. 许多；签', category: '托福词汇' },
  { word: 'lotion', phonetic: '/ˈləʊʃn/', meaning: 'n. 洗液', category: '托福词汇' },
  { word: 'lottery', phonetic: '/ˈlɒtəri/', meaning: 'n. 彩票', category: '托福词汇' },
  { word: 'lotus', phonetic: '/ˈləʊtəs/', meaning: 'n. 莲花', category: 'GRE词汇' },
  { word: 'loud', phonetic: '/laʊd/', meaning: 'adj. 大声的', category: '托福词汇' },
  { word: 'loudspeaker', phonetic: '/ˌlaʊdˈspiːkər/', meaning: 'n. 扬声器', category: '科技词汇' },
  { word: 'lounge', phonetic: '/laʊndʒ/', meaning: 'n. 休息室；v. 懒洋洋地躺', category: '托福词汇' },
  { word: 'louse', phonetic: '/laʊs/', meaning: 'n. 虱子', category: 'GRE词汇' },
  { word: 'lousy', phonetic: '/ˈlaʊzi/', meaning: 'adj. 糟糕的', category: 'GRE词汇' },
  { word: 'lout', phonetic: '/laʊt/', meaning: 'n. 粗鲁的人', category: 'GRE词汇' },
  { word: 'louver', phonetic: '/ˈluːvər/', meaning: 'n. 百叶窗', category: 'GRE词汇' },
  { word: 'love', phonetic: '/lʌv/', meaning: 'n. 爱；v. 爱', category: '托福词汇' },
  { word: 'lovable', phonetic: '/ˈlʌvəbl/', meaning: 'adj. 可爱的', category: '托福词汇' },
  { word: 'love affair', phonetic: '/lʌv əˈfeər/', meaning: 'n. 恋情', category: '托福词汇' },
  { word: 'lovely', phonetic: '/ˈlʌvli/', meaning: 'adj. 可爱的', category: '托福词汇' },
  { word: 'lover', phonetic: '/ˈlʌvər/', meaning: 'n. 爱人', category: '托福词汇' },
  { word: 'low', phonetic: '/ləʊ/', meaning: 'adj. 低的；adv. 低', category: '托福词汇' },
  { word: 'lower', phonetic: '/ˈləʊər/', meaning: 'v. 降低；adj. 较低的', category: '托福词汇' },
  { word: 'low-key', phonetic: '/ˌləʊ ˈkiː/', meaning: 'adj. 低调的', category: 'GRE词汇' },
  { word: 'lowland', phonetic: '/ˈləʊlənd/', meaning: 'n. 低地', category: '托福词汇' },
  { word: 'loyal', phonetic: '/ˈlɔɪəl/', meaning: 'adj. 忠诚的', category: '托福词汇' },
  { word: 'loyalist', phonetic: '/ˈlɔɪəlɪst/', meaning: 'n. 忠诚者', category: 'GRE词汇' },
  { word: 'loyalty', phonetic: '/ˈlɔɪəlti/', meaning: 'n. 忠诚', category: '托福词汇' },
  { word: 'lubricant', phonetic: '/ˈluːbrɪkənt/', meaning: 'n. 润滑剂', category: '科技词汇' },
  { word: 'lubricate', phonetic: '/ˈluːbrɪkeɪt/', meaning: 'v. 润滑', category: '科技词汇' },
  { word: 'lucid', phonetic: '/ˈluːsɪd/', meaning: 'adj. 清晰的；神志清醒的', category: 'GRE词汇' },
  { word: 'luck', phonetic: '/lʌk/', meaning: 'n. 运气', category: '托福词汇' },
  { word: 'lucky', phonetic: '/ˈlʌki/', meaning: 'adj. 幸运的', category: '托福词汇' },
  { word: 'lucrative', phonetic: '/ˈluːkrətɪv/', meaning: 'adj. 有利可图的', category: 'GRE词汇' },
  { word: 'ludicrous', phonetic: '/ˈluːdɪkrəs/', meaning: 'adj. 荒谬的', category: 'GRE词汇' },
  { word: 'lull', phonetic: '/lʌl/', meaning: 'v. 使平静；n. 暂停', category: 'GRE词汇' },
  { word: 'lumber', phonetic: '/ˈlʌmbər/', meaning: 'n. 木材；v. 笨拙地移动', category: '托福词汇' },
  { word: 'lumberjack', phonetic: '/ˈlʌmbədʒæk/', meaning: 'n. 伐木工', category: 'GRE词汇' },
  { word: 'luminous', phonetic: '/ˈluːmɪnəs/', meaning: 'adj. 发光的', category: 'GRE词汇' },
  { word: 'lump', phonetic: '/lʌmp/', meaning: 'n. 块；v. 结块', category: '托福词汇' },
  { word: 'lumpy', phonetic: '/ˈlʌmpi/', meaning: 'adj. 多块的', category: 'GRE词汇' },
  { word: 'lunacy', phonetic: '/ˈluːnəsi/', meaning: 'n. 疯狂', category: 'GRE词汇' },
  { word: 'lunar', phonetic: '/ˈluːnər/', meaning: 'adj. 月球的', category: '托福词汇' },
  { word: 'lunch', phonetic: '/lʌntʃ/', meaning: 'n. 午餐', category: '托福词汇' },
  { word: 'luncheon', phonetic: '/ˈlʌntʃən/', meaning: 'n. 午宴', category: 'GRE词汇' },
  { word: 'lung', phonetic: '/lʌŋ/', meaning: 'n. 肺', category: '医学词汇' },
  { word: 'lurch', phonetic: '/lɜːtʃ/', meaning: 'v. 蹒跚；n. 突然倾斜', category: 'GRE词汇' },
  { word: 'lure', phonetic: '/lʊər/', meaning: 'v. 引诱；n. 诱惑', category: 'GRE词汇' },
  { word: 'lurid', phonetic: '/ˈlʊərɪd/', meaning: 'adj. 可怕的；刺眼的', category: 'GRE词汇' },
  { word: 'lurk', phonetic: '/lɜːk/', meaning: 'v. 潜伏', category: 'GRE词汇' },
  { word: 'luscious', phonetic: '/ˈlʌʃəs/', meaning: 'adj. 美味的；性感的', category: 'GRE词汇' },
  { word: 'lush', phonetic: '/lʌʃ/', meaning: 'adj. 茂盛的', category: 'GRE词汇' },
  { word: 'lust', phonetic: '/lʌst/', meaning: 'n. 欲望；v. 贪求', category: 'GRE词汇' },
  { word: 'luster', phonetic: '/ˈlʌstər/', meaning: 'n. 光泽', category: 'GRE词汇' },
  { word: 'lustful', phonetic: '/ˈlʌstfl/', meaning: 'adj. 贪欲的', category: 'GRE词汇' },
  { word: 'lusty', phonetic: '/ˈlʌsti/', meaning: 'adj. 精力充沛的', category: 'GRE词汇' },
  { word: 'lute', phonetic: '/ljuːt/', meaning: 'n. 琵琶', category: 'GRE词汇' },
  { word: 'luxurious', phonetic: '/lʌɡˈʒʊəriəs/', meaning: 'adj. 奢华的', category: '托福词汇' },
  { word: 'luxury', phonetic: '/ˈlʌkʃəri/', meaning: 'n. 奢侈', category: '托福词汇' },
  { word: 'lying', phonetic: '/ˈlaɪɪŋ/', meaning: 'n. 说谎；adj. 说谎的', category: '托福词汇' },
  { word: 'lymph', phonetic: '/lɪmf/', meaning: 'n. 淋巴', category: '医学词汇' },
  { word: 'lymphatic', phonetic: '/lɪmˈfætɪk/', meaning: 'adj. 淋巴的', category: '医学词汇' },
  { word: 'lynch', phonetic: '/lɪntʃ/', meaning: 'v. 私刑处死', category: 'GRE词汇' },
  { word: 'lyric', phonetic: '/ˈlɪrɪk/', meaning: 'n. 歌词；adj. 抒情的', category: '托福词汇' },
  { word: 'lyrical', phonetic: '/ˈlɪrɪkl/', meaning: 'adj. 抒情的', category: 'GRE词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await fetchAllFromSupabase(
    supabase.from(WORDS_TABLE).select('word')
  );
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsLM, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const word = w.word.toLowerCase().trim();
    if (!word || !w.meaning || existingSet.has(word)) continue;
    
    records.push({
      word,
      phonetic: w.phonetic || '',
      meaning: w.meaning.trim(),
      example_sentence: `This is an example using the word "${w.word}".`,
      category_id: categoryIds.get(w.category) || defaultCategoryId,
    });
    existingSet.add(word);
  }
  
  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const batch = records.slice(i, i + batchSize);
    const { error } = await supabase.from(WORDS_TABLE).insert(batch);
    if (!error) {
      inserted += batch.length;
      console.log(`已插入 ${inserted}/${records.length} 个单词`);
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 L 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsLM.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsLM, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
