// Part 2/4 - 单词数据 Part 2
const wordsDataPart2 = [
  // C
  { word: 'cabal', phonetic: '/kəˈbɑːl/', meaning: 'n. 阴谋集团', category: 'GRE词汇' },
  { word: 'cache', phonetic: '/kæʃ/', meaning: 'n. 贮存物；缓存', category: '科技词汇' },
  { word: 'cacophony', phonetic: '/kəˈkɒfəni/', meaning: 'n. 刺耳的声音', category: 'GRE词汇' },
  { word: 'cadaver', phonetic: '/kəˈdævər/', meaning: 'n. 尸体', category: '医学词汇' },
  { word: 'cadge', phonetic: '/kædʒ/', meaning: 'v. 乞讨；骗取', category: 'GRE词汇' },
  { word: 'cajole', phonetic: '/kəˈdʒəʊl/', meaning: 'v. 哄骗；诱导', category: 'GRE词汇' },
  { word: 'calamity', phonetic: '/kəˈlæməti/', meaning: 'n. 灾难；不幸', category: '托福词汇' },
  { word: 'calcify', phonetic: '/ˈkælsɪfaɪ/', meaning: 'v. 钙化；硬化', category: '医学词汇' },
  { word: 'caliber', phonetic: '/ˈkælɪbər/', meaning: 'n. 口径；品质', category: 'GRE词汇' },
  { word: 'callous', phonetic: '/ˈkæləs/', meaning: 'adj. 冷漠的；无情的', category: 'GRE词汇' },
  { word: 'callow', phonetic: '/ˈkæləʊ/', meaning: 'adj. 年轻无经验的', category: 'GRE词汇' },
  { word: 'calumniate', phonetic: '/kəˈlʌmnieɪt/', meaning: 'v. 诽谤；中伤', category: 'GRE词汇' },
  { word: 'camaraderie', phonetic: '/ˌkæməˈrɑːdəri/', meaning: 'n. 友情；同志情谊', category: 'GRE词汇' },
  { word: 'camouflage', phonetic: '/ˈkæməflɑːʒ/', meaning: 'n. 伪装；v. 掩饰', category: '托福词汇' },
  { word: 'canard', phonetic: '/kəˈnɑːrd/', meaning: 'n. 虚假消息；谣言', category: 'GRE词汇' },
  { word: 'candid', phonetic: '/ˈkændɪd/', meaning: 'adj. 坦率的；公正的', category: '托福词汇' },
  { word: 'candor', phonetic: '/ˈkændər/', meaning: 'n. 坦率；公正', category: 'GRE词汇' },
  { word: 'canine', phonetic: '/ˈkeɪnaɪn/', meaning: 'adj. 犬的；n. 犬齿', category: '医学词汇' },
  { word: 'canker', phonetic: '/ˈkæŋkər/', meaning: 'n. 溃疡；祸根', category: '医学词汇' },
  { word: 'canny', phonetic: '/ˈkæni/', meaning: 'adj. 精明的；谨慎的', category: 'GRE词汇' },
  { word: 'canon', phonetic: '/ˈkænən/', meaning: 'n. 正典；准则', category: 'GRE词汇' },
  { word: 'cant', phonetic: '/kænt/', meaning: 'n. 伪善之言；行话', category: 'GRE词汇' },
  { word: 'cantankerous', phonetic: '/kənˈtæŋkərəs/', meaning: 'adj. 脾气坏的；难相处的', category: 'GRE词汇' },
  { word: 'canonical', phonetic: '/kəˈnɒnɪkl/', meaning: 'adj. 正统的；经典的', category: '科技词汇' },
  { word: 'canvass', phonetic: '/ˈkænvəs/', meaning: 'v. 游说；拉票', category: 'GRE词汇' },
  { word: 'capacious', phonetic: '/kəˈpeɪʃəs/', meaning: 'adj. 容量大的', category: 'GRE词汇' },
  { word: 'capitulate', phonetic: '/kəˈpɪtʃuleɪt/', meaning: 'v. 投降；屈服', category: 'GRE词汇' },
  { word: 'caprice', phonetic: '/kəˈpriːs/', meaning: 'n. 反复无常；任性', category: 'GRE词汇' },
  { word: 'capricious', phonetic: '/kəˈprɪʃəs/', meaning: 'adj. 反复无常的', category: 'GRE词汇' },
  { word: 'caption', phonetic: '/ˈkæpʃn/', meaning: 'n. 标题；说明文字', category: '日常词汇' },
  { word: 'captious', phonetic: '/ˈkæpʃəs/', meaning: 'adj. 吹毛求疵的', category: 'GRE词汇' },
  { word: 'captivate', phonetic: '/ˈkæptɪveɪt/', meaning: 'v. 迷住；吸引', category: '托福词汇' },
  { word: 'carapace', phonetic: '/ˈkærəpeɪs/', meaning: 'n. 甲壳；外壳', category: 'GRE词汇' },
  { word: 'carat', phonetic: '/ˈkærət/', meaning: 'n. 克拉；开', category: '商务词汇' },
  { word: 'carcinogen', phonetic: '/kɑːˈsɪnədʒən/', meaning: 'n. 致癌物', category: '医学词汇' },
  { word: 'cardinal', phonetic: '/ˈkɑːdɪnl/', meaning: 'adj. 主要的；基本的', category: 'GRE词汇' },
  { word: 'careen', phonetic: '/kəˈriːn/', meaning: 'v. 猛冲；倾斜', category: 'GRE词汇' },
  { word: 'caricature', phonetic: '/ˈkærɪkətjʊər/', meaning: 'n. 漫画；夸张描写', category: 'GRE词汇' },
  { word: 'carnage', phonetic: '/ˈkɑːnɪdʒ/', meaning: 'n. 大屠杀', category: 'GRE词汇' },
  { word: 'carnal', phonetic: '/ˈkɑːnl/', meaning: 'adj. 肉体的；世俗的', category: 'GRE词汇' },
  { word: 'carnivorous', phonetic: '/kɑːˈnɪvərəs/', meaning: 'adj. 食肉的', category: '科技词汇' },
  { word: 'carouse', phonetic: '/kəˈraʊz/', meaning: 'v. 痛饮；狂欢', category: 'GRE词汇' },
  { word: 'carp', phonetic: '/kɑːp/', meaning: 'v. 吹毛求疵', category: 'GRE词汇' },
  { word: 'carping', phonetic: '/ˈkɑːpɪŋ/', meaning: 'adj. 吹毛求疵的', category: 'GRE词汇' },
  { word: 'carrion', phonetic: '/ˈkæriən/', meaning: 'n. 腐肉', category: 'GRE词汇' },
  { word: 'cartel', phonetic: '/kɑːˈtel/', meaning: 'n. 卡特尔；同业联盟', category: '商务词汇' },
  { word: 'cartography', phonetic: '/kɑːˈtɒɡrəfi/', meaning: 'n. 制图学', category: '科技词汇' },
  { word: 'cascade', phonetic: '/kæˈskeɪd/', meaning: 'n. 瀑布；级联', category: '科技词汇' },
  { word: 'caste', phonetic: '/kɑːst/', meaning: 'n. 社会等级；种姓', category: 'GRE词汇' },
  { word: 'castigate', phonetic: '/ˈkæstɪɡeɪt/', meaning: 'v. 严厉批评；惩罚', category: 'GRE词汇' },
  { word: 'casualty', phonetic: '/ˈkæʒuəlti/', meaning: 'n. 伤亡人员；受害者', category: '托福词汇' },
  { word: 'cataclysm', phonetic: '/ˈkætəklɪzəm/', meaning: 'n. 大灾难；巨变', category: 'GRE词汇' },
  { word: 'catalyst', phonetic: '/ˈkætəlɪst/', meaning: 'n. 催化剂；促进因素', category: '托福词汇' },
  { word: 'catapult', phonetic: '/ˈkætəpʌlt/', meaning: 'n. 弹弓；v. 弹射', category: '托福词汇' },
  { word: 'cataract', phonetic: '/ˈkætərækt/', meaning: 'n. 大瀑布；白内障', category: '医学词汇' },
  { word: 'catastrophe', phonetic: '/kəˈtæstrəfi/', meaning: 'n. 大灾难', category: '托福词汇' },
  { word: 'catechism', phonetic: '/ˈkætəkɪzəm/', meaning: 'n. 教义问答', category: 'GRE词汇' },
  { word: 'categorical', phonetic: '/ˌkætəˈɡɒrɪkl/', meaning: 'adj. 绝对的；明确的', category: 'GRE词汇' },
  { word: 'cater', phonetic: '/ˈkeɪtər/', meaning: 'v. 迎合；提供餐饮', category: '托福词汇' },
  { word: 'catharsis', phonetic: '/kəˈθɑːsɪs/', meaning: 'n. 净化；宣泄', category: 'GRE词汇' },
  { word: 'cathartic', phonetic: '/kəˈθɑːtɪk/', meaning: 'adj. 净化的；宣泄的', category: 'GRE词汇' },
  { word: 'caucus', phonetic: '/ˈkɔːkəs/', meaning: 'n. 核心会议', category: 'GRE词汇' },
  { word: 'caustic', phonetic: '/ˈkɔːstɪk/', meaning: 'adj. 腐蚀性的；刻薄的', category: 'GRE词汇' },
  { word: 'cauterize', phonetic: '/ˈkɔːtəraɪz/', meaning: 'v. 烧灼；使麻木', category: '医学词汇' },
  { word: 'cautionary', phonetic: '/ˈkɔːʃənri/', meaning: 'adj. 警告的；劝诫的', category: '托福词汇' },
  { word: 'cavalcade', phonetic: '/ˌkævlˈkeɪd/', meaning: 'n. 骑马队伍；游行', category: 'GRE词汇' },
  { word: 'cavalier', phonetic: '/ˌkævəˈlɪər/', meaning: 'adj. 傲慢的；漫不经心的', category: 'GRE词汇' },
  { word: 'caveat', phonetic: '/ˈkæviæt/', meaning: 'n. 警告；限制条款', category: '法律词汇' },
  { word: 'cavil', phonetic: '/ˈkævɪl/', meaning: 'v. 挑剔；吹毛求疵', category: 'GRE词汇' },
  { word: 'cavity', phonetic: '/ˈkævəti/', meaning: 'n. 洞；腔', category: '医学词汇' },
  { word: 'cede', phonetic: '/siːd/', meaning: 'v. 割让；放弃', category: 'GRE词汇' },
  { word: 'celebrity', phonetic: '/səˈlebrəti/', meaning: 'n. 名人；名声', category: '托福词汇' },
  { word: 'celerity', phonetic: '/səˈlerəti/', meaning: 'n. 敏捷；快速', category: 'GRE词汇' },
  { word: 'celestial', phonetic: '/səˈlestiəl/', meaning: 'adj. 天上的；神圣的', category: 'GRE词汇' },
  { word: 'celibate', phonetic: '/ˈselɪbət/', meaning: 'adj. 独身的；禁欲的', category: 'GRE词汇' },
  { word: 'censor', phonetic: '/ˈsensər/', meaning: 'v. 审查；n. 检查员', category: '托福词汇' },
  { word: 'censorious', phonetic: '/senˈsɔːriəs/', meaning: 'adj. 吹毛求疵的', category: 'GRE词汇' },
  { word: 'censure', phonetic: '/ˈsenʃər/', meaning: 'v. 谴责；n. 指责', category: 'GRE词汇' },
  { word: 'centrifugal', phonetic: '/senˈtrɪfjʊɡl/', meaning: 'adj. 离心的', category: '科技词汇' },
  { word: 'centurion', phonetic: '/senˈtjʊriən/', meaning: 'n. 百夫长', category: 'GRE词汇' },
  { word: 'cerebral', phonetic: '/ˈserəbrəl/', meaning: 'adj. 大脑的；理智的', category: '医学词汇' },
  { word: 'cerebellum', phonetic: '/ˌserəˈbeləm/', meaning: 'n. 小脑', category: '医学词汇' },
  { word: 'ceremonial', phonetic: '/ˌserɪˈməʊniəl/', meaning: 'adj. 仪式的；正式的', category: '托福词汇' },
  { word: 'ceremonious', phonetic: '/ˌserɪˈməʊniəs/', meaning: 'adj. 讲究礼节的', category: 'GRE词汇' },
  { word: 'certitude', phonetic: '/ˈsɜːtɪtjuːd/', meaning: 'n. 确信；确定性', category: 'GRE词汇' },
  { word: 'cessation', phonetic: '/seˈseɪʃn/', meaning: 'n. 停止；中止', category: 'GRE词汇' },
  { word: 'chafe', phonetic: '/tʃeɪf/', meaning: 'v. 恼怒；摩擦', category: 'GRE词汇' },
  { word: 'chaff', phonetic: '/tʃɑːf/', meaning: 'n. 谷壳；无用之物', category: 'GRE词汇' },
  { word: 'chagrin', phonetic: '/ˈʃæɡrɪn/', meaning: 'n. 恼怒；懊恼', category: 'GRE词汇' },
  { word: 'chalice', phonetic: '/ˈtʃælɪs/', meaning: 'n. 圣杯；酒杯', category: 'GRE词汇' },
  { word: 'champion', phonetic: '/ˈtʃæmpiən/', meaning: 'v. 支持；n. 冠军', category: '托福词汇' },
  { word: 'chaos', phonetic: '/ˈkeɪɒs/', meaning: 'n. 混乱；混沌', category: '托福词汇' },
  { word: 'chaotic', phonetic: '/keɪˈɒtɪk/', meaning: 'adj. 混乱的', category: '托福词汇' },
  { word: 'chapfallen', phonetic: '/ˈtʃæpfɔːlən/', meaning: 'adj. 垂头丧气的', category: 'GRE词汇' },
  { word: 'chapel', phonetic: '/ˈtʃæpl/', meaning: 'n. 小教堂', category: '托福词汇' },
  { word: 'charade', phonetic: '/ʃəˈrɑːd/', meaning: 'n. 假装；哑谜游戏', category: 'GRE词汇' },
  { word: 'charismatic', phonetic: '/ˌkærɪzˈmætɪk/', meaning: 'adj. 有魅力的', category: '托福词汇' },
  { word: 'charitable', phonetic: '/ˈtʃærɪtəbl/', meaning: 'adj. 慈善的；宽容的', category: '托福词汇' },
  { word: 'charlatan', phonetic: '/ˈʃɑːlətən/', meaning: 'n. 骗子；冒牌医生', category: 'GRE词汇' },
  { word: 'charred', phonetic: '/tʃɑːrd/', meaning: 'adj. 烧焦的', category: '日常词汇' },
  { word: 'chart', phonetic: '/tʃɑːt/', meaning: 'n. 图表；v. 绘制', category: '商务词汇' },
  { word: 'chary', phonetic: '/ˈtʃeəri/', meaning: 'adj. 谨慎的；小心的', category: 'GRE词汇' },
  { word: 'chase', phonetic: '/tʃeɪs/', meaning: 'v. 追逐；n. 追赶', category: '日常词汇' },
  { word: 'chasm', phonetic: '/ˈkæzəm/', meaning: 'n. 深渊；巨大分歧', category: 'GRE词汇' },
  { word: 'chassis', phonetic: '/ˈʃæsi/', meaning: 'n. 底盘；框架', category: '科技词汇' },
  { word: 'chaste', phonetic: '/tʃeɪst/', meaning: 'adj. 贞洁的；纯洁的', category: 'GRE词汇' },
  { word: 'chasten', phonetic: '/ˈtʃeɪsn/', meaning: 'v. 惩戒；磨练', category: 'GRE词汇' },
  { word: 'chastise', phonetic: '/tʃæˈstaɪz/', meaning: 'v. 严厉惩罚', category: 'GRE词汇' },
  { word: 'chastity', phonetic: '/ˈtʃæstəti/', meaning: 'n. 贞洁；纯洁', category: 'GRE词汇' },
  { word: 'chauvinist', phonetic: '/ˈʃəʊvɪnɪst/', meaning: 'n. 盲目爱国者；大男子主义者', category: 'GRE词汇' },
  { word: 'checkered', phonetic: '/ˈtʃekərd/', meaning: 'adj. 多变的；有交替经历的', category: 'GRE词汇' },
  { word: 'cherubic', phonetic: '/tʃəˈruːbɪk/', meaning: 'adj. 天使般的；天真无邪的', category: 'GRE词汇' },
  { word: 'chicanery', phonetic: '/ʃɪˈkeɪnəri/', meaning: 'n. 欺骗；诡计', category: 'GRE词汇' },
  { word: 'chide', phonetic: '/tʃaɪd/', meaning: 'v. 斥责；责骂', category: 'GRE词汇' },
  { word: 'chimerical', phonetic: '/kaɪˈmerɪkl/', meaning: 'adj. 荒诞的；不切实际的', category: 'GRE词汇' },
  { word: 'chisel', phonetic: '/ˈtʃɪzl/', meaning: 'n. 凿子；v. 凿', category: '日常词汇' },
  { word: 'chivalrous', phonetic: '/ˈʃɪvəlrəs/', meaning: 'adj. 骑士风度的；侠义的', category: 'GRE词汇' },
  { word: 'choleric', phonetic: '/ˈkɒlərɪk/', meaning: 'adj. 易怒的；暴躁的', category: 'GRE词汇' },
  { word: 'choreograph', phonetic: '/ˈkɒriəɡrɑːf/', meaning: 'v. 编舞；设计', category: '日常词汇' },
  { word: 'chronic', phonetic: '/ˈkrɒnɪk/', meaning: 'adj. 慢性的；长期的', category: '医学词汇' },
  { word: 'chronicle', phonetic: '/ˈkrɒnɪkl/', meaning: 'n. 编年史；v. 记录', category: '托福词汇' },
  { word: 'chronological', phonetic: '/ˌkrɒnəˈlɒdʒɪkl/', meaning: 'adj. 按时间顺序的', category: '托福词汇' },
  { word: 'churlish', phonetic: '/ˈtʃɜːlɪʃ/', meaning: 'adj. 粗鲁的；吝啬的', category: 'GRE词汇' },
  { word: 'cipher', phonetic: '/ˈsaɪfər/', meaning: 'n. 密码；零', category: '科技词汇' },
  { word: 'circumambulate', phonetic: '/ˌsɜːkəmˈæmbjuleɪt/', meaning: 'v. 绕行；巡视', category: 'GRE词汇' },
  { word: 'circumference', phonetic: '/səˈkʌmfərəns/', meaning: 'n. 圆周；周长', category: '科技词汇' },
  { word: 'circumlocution', phonetic: '/ˌsɜːkəmləˈkjuːʃn/', meaning: 'n. 迂回说法', category: 'GRE词汇' },
  { word: 'circumnavigate', phonetic: '/ˌsɜːkəmˈnævɪɡeɪt/', meaning: 'v. 环航；绕行', category: 'GRE词汇' },
  { word: 'circumscribe', phonetic: '/ˈsɜːkəmskraɪb/', meaning: 'v. 限制；划定范围', category: 'GRE词汇' },
  { word: 'circumspect', phonetic: '/ˈsɜːkəmspekt/', meaning: 'adj. 慎重的；周到的', category: 'GRE词汇' },
  { word: 'circumstance', phonetic: '/ˈsɜːkəmstəns/', meaning: 'n. 情况；环境', category: '托福词汇' },
  { word: 'circumvent', phonetic: '/ˌsɜːkəmˈvent/', meaning: 'v. 规避；绕过', category: 'GRE词汇' },
  { word: 'citadel', phonetic: '/ˈsɪtədəl/', meaning: 'n. 城堡；堡垒', category: 'GRE词汇' },
  { word: 'cite', phonetic: '/saɪt/', meaning: 'v. 引用；传讯', category: '托福词汇' },
  { word: 'civil', phonetic: '/ˈsɪvl/', meaning: 'adj. 公民的；文明的', category: '托福词汇' },
  { word: 'civic', phonetic: '/ˈsɪvɪk/', meaning: 'adj. 市民的；公民的', category: '托福词汇' },
  { word: 'civilian', phonetic: '/səˈvɪliən/', meaning: 'n. 平民；adj. 平民的', category: '托福词汇' },
  { word: 'clamor', phonetic: '/ˈklæmər/', meaning: 'n. 喧哗；v. 大声要求', category: 'GRE词汇' },
  { word: 'clandestine', phonetic: '/klænˈdestɪn/', meaning: 'adj. 秘密的；暗中的', category: 'GRE词汇' },
  { word: 'clarion', phonetic: '/ˈklæriən/', meaning: 'adj. 响亮清晰的', category: 'GRE词汇' },
  { word: 'clarity', phonetic: '/ˈklærəti/', meaning: 'n. 清楚；清晰', category: '托福词汇' },
  { word: 'claustrophobia', phonetic: '/ˌklɔːstrəˈfəʊbiə/', meaning: 'n. 幽闭恐惧症', category: '医学词汇' },
  { word: 'cleave', phonetic: '/kliːv/', meaning: 'v. 劈开；坚持', category: 'GRE词汇' },
  { word: 'cleft', phonetic: '/kleft/', meaning: 'n. 裂缝；裂口', category: 'GRE词汇' },
  { word: 'clemency', phonetic: '/ˈklemənsi/', meaning: 'n. 仁慈；宽厚', category: 'GRE词汇' },
  { word: 'cliché', phonetic: '/ˈkliːʃeɪ/', meaning: 'n. 陈词滥调', category: '托福词汇' },
  { word: 'clique', phonetic: '/kliːk/', meaning: 'n. 派系；小圈子', category: 'GRE词汇' },
  { word: 'cloister', phonetic: '/ˈklɔɪstər/', meaning: 'n. 修道院；v. 隐居', category: 'GRE词汇' },
  { word: 'cloture', phonetic: '/ˈkləʊtʃər/', meaning: 'n. 终结辩论', category: '法律词汇' },
  { word: 'clout', phonetic: '/klaʊt/', meaning: 'n. 影响力；v. 猛击', category: 'GRE词汇' },
  { word: 'cloying', phonetic: '/ˈklɔɪɪŋ/', meaning: 'adj. 甜得发腻的', category: 'GRE词汇' },
  { word: 'coagulate', phonetic: '/kəʊˈæɡjuleɪt/', meaning: 'v. 凝结；结块', category: '医学词汇' },
  { word: 'coalition', phonetic: '/ˌkəʊəˈlɪʃn/', meaning: 'n. 联盟；联合', category: '托福词汇' },
  { word: 'coarse', phonetic: '/kɔːs/', meaning: 'adj. 粗糙的；粗俗的', category: '托福词汇' },
  { word: 'coax', phonetic: '/kəʊks/', meaning: 'v. 哄骗；耐心诱导', category: '托福词汇' },
  { word: 'cobbler', phonetic: '/ˈkɒblər/', meaning: 'n. 鞋匠', category: 'GRE词汇' },
  { word: 'cobweb', phonetic: '/ˈkɒbweb/', meaning: 'n. 蜘蛛网', category: '日常词汇' },
  { word: 'coda', phonetic: '/ˈkəʊdə/', meaning: 'n. 尾声；结尾', category: 'GRE词汇' },
  { word: 'codicil', phonetic: '/ˈkɒdɪsɪl/', meaning: 'n. 遗嘱附录', category: '法律词汇' },
  { word: 'codify', phonetic: '/ˈkəʊdɪfaɪ/', meaning: 'v. 编纂；整理', category: '法律词汇' },
  { word: 'coerce', phonetic: '/kəʊˈɜːs/', meaning: 'v. 强迫；胁迫', category: 'GRE词汇' },
  { word: 'coeval', phonetic: '/kəʊˈiːvl/', meaning: 'adj. 同时代的', category: 'GRE词汇' },
  { word: 'cogent', phonetic: '/ˈkəʊdʒənt/', meaning: 'adj. 有说服力的', category: 'GRE词汇' },
  { word: 'cogitate', phonetic: '/ˈkɒdʒɪteɪt/', meaning: 'v. 深思；思考', category: 'GRE词汇' },
  { word: 'cognate', phonetic: '/ˈkɒɡneɪt/', meaning: 'adj. 同源的；相关的', category: 'GRE词汇' },
  { word: 'cognition', phonetic: '/kɒɡˈnɪʃn/', meaning: 'n. 认知；认识', category: '科技词汇' },
  { word: 'cognitive', phonetic: '/ˈkɒɡnətɪv/', meaning: 'adj. 认知的', category: '科技词汇' },
  { word: 'cognizant', phonetic: '/ˈkɒɡnɪzənt/', meaning: 'adj. 认识到的；意识到的', category: 'GRE词汇' },
  { word: 'cohabit', phonetic: '/kəʊˈhæbɪt/', meaning: 'v. 同居', category: 'GRE词汇' },
  { word: 'cohere', phonetic: '/kəʊˈhɪər/', meaning: 'v. 连贯；一致', category: 'GRE词汇' },
  { word: 'cohesion', phonetic: '/kəʊˈhiːʒn/', meaning: 'n. 凝聚力；结合', category: '托福词汇' },
  { word: 'cohesive', phonetic: '/kəʊˈhiːsɪv/', meaning: 'adj. 有凝聚力的', category: '托福词汇' },
  { word: 'cohort', phonetic: '/ˈkəʊhɔːt/', meaning: 'n. 一群；同伙', category: 'GRE词汇' },
  { word: 'coincide', phonetic: '/ˌkəʊɪnˈsaɪd/', meaning: 'v. 同时发生；一致', category: '托福词汇' },
  { word: 'collaborate', phonetic: '/kəˈlæbəreɪt/', meaning: 'v. 合作；协作', category: '托福词汇' },
  { word: 'collage', phonetic: '/kəˈlɑːʒ/', meaning: 'n. 拼贴画', category: '日常词汇' },
  { word: 'collapse', phonetic: '/kəˈlæps/', meaning: 'v. 倒塌；崩溃', category: '托福词汇' },
  { word: 'collateral', phonetic: '/kəˈlætərəl/', meaning: 'n. 抵押品；adj. 附带的', category: '商务词汇' },
  { word: 'colleague', phonetic: '/ˈkɒliːɡ/', meaning: 'n. 同事', category: '商务词汇' },
  { word: 'collective', phonetic: '/kəˈlektɪv/', meaning: 'adj. 集体的；共同的', category: '托福词汇' },
  { word: 'collide', phonetic: '/kəˈlaɪd/', meaning: 'v. 碰撞；冲突', category: '托福词汇' },
  { word: 'colloquial', phonetic: '/kəˈləʊkwiəl/', meaning: 'adj. 口语的；通俗的', category: 'GRE词汇' },
  { word: 'collude', phonetic: '/kəˈluːd/', meaning: 'v. 共谋；勾结', category: 'GRE词汇' },
  { word: 'colonial', phonetic: '/kəˈləʊniəl/', meaning: 'adj. 殖民的', category: '托福词汇' },
  { word: 'colossal', phonetic: '/kəˈlɒsl/', meaning: 'adj. 巨大的；庞大的', category: '托福词汇' },
  { word: 'colt', phonetic: '/kəʊlt/', meaning: 'n. 小马', category: 'GRE词汇' },
  { word: 'columnist', phonetic: '/ˈkɒləmnɪst/', meaning: 'n. 专栏作家', category: '商务词汇' },
  { word: 'comatose', phonetic: '/ˈkəʊmətəʊs/', meaning: 'adj. 昏迷的；昏睡的', category: '医学词汇' },
  { word: 'combative', phonetic: '/ˈkɒmbətɪv/', meaning: 'adj. 好斗的', category: 'GRE词汇' },
  { word: 'combine', phonetic: '/kəmˈbaɪn/', meaning: 'v. 结合；联合', category: '托福词汇' },
  { word: 'combustion', phonetic: '/kəmˈbʌstʃən/', meaning: 'n. 燃烧', category: '科技词汇' },
  { word: 'comely', phonetic: '/ˈkʌmli/', meaning: 'adj. 美丽的；合适的', category: 'GRE词汇' },
  { word: 'commemorate', phonetic: '/kəˈmeməreɪt/', meaning: 'v. 纪念', category: '托福词汇' },
  { word: 'commence', phonetic: '/kəˈmens/', meaning: 'v. 开始；着手', category: '托福词汇' },
  { word: 'commend', phonetic: '/kəˈmend/', meaning: 'v. 称赞；推荐', category: '托福词汇' },
  { word: 'commensurate', phonetic: '/kəˈmenʃərət/', meaning: 'adj. 相称的；成比例的', category: 'GRE词汇' },
  { word: 'commentary', phonetic: '/ˈkɒməntri/', meaning: 'n. 评论；解说', category: '托福词汇' },
  { word: 'commerce', phonetic: '/ˈkɒmɜːs/', meaning: 'n. 商业；贸易', category: '商务词汇' },
  { word: 'commingle', phonetic: '/kəˈmɪŋɡl/', meaning: 'v. 混合；合并', category: 'GRE词汇' },
  { word: 'commiserate', phonetic: '/kəˈmɪzəreɪt/', meaning: 'v. 同情；怜悯', category: 'GRE词汇' },
  { word: 'commission', phonetic: '/kəˈmɪʃn/', meaning: 'n. 委员会；佣金', category: '商务词汇' },
  { word: 'commitment', phonetic: '/kəˈmɪtmənt/', meaning: 'n. 承诺；投入', category: '托福词汇' },
  { word: 'commodity', phonetic: '/kəˈmɒdəti/', meaning: 'n. 商品；日用品', category: '商务词汇' },
  { word: 'commodious', phonetic: '/kəˈməʊdiəs/', meaning: 'adj. 宽敞的', category: 'GRE词汇' },
  { word: 'commonplace', phonetic: '/ˈkɒmənpleɪs/', meaning: 'adj. 普通的；平凡的', category: 'GRE词汇' },
  { word: 'commonsense', phonetic: '/ˌkɒmənˈsens/', meaning: 'adj. 常识性的', category: '托福词汇' },
  { word: 'commotion', phonetic: '/kəˈməʊʃn/', meaning: 'n. 骚动；混乱', category: 'GRE词汇' },
  { word: 'communal', phonetic: '/ˈkɒmjənl/', meaning: 'adj. 公共的；社区的', category: '托福词汇' },
  { word: 'communicable', phonetic: '/kəˈmjuːnɪkəbl/', meaning: 'adj. 可传播的；传染的', category: '医学词汇' },
  { word: 'compact', phonetic: '/kəmˈpækt/', meaning: 'adj. 紧凑的；n. 协议', category: '托福词汇' },
  { word: 'companionship', phonetic: '/kəmˈpæniənʃɪp/', meaning: 'n. 友谊；陪伴', category: '托福词汇' },
  { word: 'comparable', phonetic: '/ˈkɒmpərəbl/', meaning: 'adj. 可比较的', category: '托福词汇' },
  { word: 'compartment', phonetic: '/kəmˈpɑːtmənt/', meaning: 'n. 隔间；分隔空间', category: '托福词汇' },
  { word: 'compassion', phonetic: '/kəmˈpæʃn/', meaning: 'n. 同情；怜悯', category: '托福词汇' },
  { word: 'compassionate', phonetic: '/kəmˈpæʃənət/', meaning: 'adj. 有同情心的', category: '托福词汇' },
  { word: 'compatible', phonetic: '/kəmˈpætəbl/', meaning: 'adj. 兼容的；相容的', category: '托福词汇' },
  { word: 'compel', phonetic: '/kəmˈpel/', meaning: 'v. 强迫；迫使', category: '托福词汇' },
  { word: 'compendium', phonetic: '/kəmˈpendiəm/', meaning: 'n. 概要；汇编', category: 'GRE词汇' },
  { word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', meaning: 'v. 补偿；赔偿', category: '托福词汇' },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争；比赛', category: '托福词汇' },
  { word: 'competence', phonetic: '/ˈkɒmpɪtəns/', meaning: 'n. 能力；胜任', category: '托福词汇' },
  { word: 'competent', phonetic: '/ˈkɒmpɪtənt/', meaning: 'adj. 有能力的；胜任的', category: '托福词汇' },
  { word: 'compile', phonetic: '/kəmˈpaɪl/', meaning: 'v. 编译；汇编', category: '托福词汇' },
  { word: 'complacency', phonetic: '/kəmˈpleɪsnsi/', meaning: 'n. 自满；满足', category: 'GRE词汇' },
  { word: 'complaisant', phonetic: '/kəmˈpleɪznt/', meaning: 'adj. 殷勤的；顺从的', category: 'GRE词汇' },
  { word: 'complement', phonetic: '/ˈkɒmplɪment/', meaning: 'v. 补充；n. 补充物', category: '托福词汇' },
  { word: 'complete', phonetic: '/kəmˈpliːt/', meaning: 'adj. 完整的；v. 完成', category: '日常词汇' },
  { word: 'complexion', phonetic: '/kəmˈplekʃn/', meaning: 'n. 肤色；局面', category: 'GRE词汇' },
  { word: 'compliance', phonetic: '/kəmˈplaɪəns/', meaning: 'n. 遵守；服从', category: '商务词汇' },
  { word: 'complicate', phonetic: '/ˈkɒmplɪkeɪt/', meaning: 'v. 使复杂', category: '托福词汇' },
  { word: 'complicity', phonetic: '/kəmˈplɪsəti/', meaning: 'n. 共谋；同谋', category: 'GRE词汇' },
  { word: 'compliment', phonetic: '/ˈkɒmplɪmənt/', meaning: 'n. 称赞；v. 称赞', category: '托福词汇' },
  { word: 'comply', phonetic: '/kəmˈplaɪ/', meaning: 'v. 遵守；顺从', category: '托福词汇' },
  { word: 'component', phonetic: '/kəmˈpəʊnənt/', meaning: 'n. 成分；组件', category: '托福词汇' },
  { word: 'compose', phonetic: '/kəmˈpəʊz/', meaning: 'v. 组成；作曲', category: '托福词汇' },
  { word: 'composite', phonetic: '/ˈkɒmpəzɪt/', meaning: 'adj. 合成的；n. 合成物', category: '托福词汇' },
  { word: 'composition', phonetic: '/ˌkɒmpəˈzɪʃn/', meaning: 'n. 作文；组成', category: '托福词汇' },
  { word: 'compost', phonetic: '/ˈkɒmpɒst/', meaning: 'n. 堆肥', category: '日常词汇' },
  { word: 'composure', phonetic: '/kəmˈpəʊʒər/', meaning: 'n. 镇静；沉着', category: 'GRE词汇' },
  { word: 'compound', phonetic: '/ˈkɒmpaʊnd/', meaning: 'n. 化合物；v. 混合', category: '托福词汇' },
  { word: 'comprehend', phonetic: '/ˌkɒmprɪˈhend/', meaning: 'v. 理解；包含', category: '托福词汇' },
  { word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', meaning: 'adj. 全面的；综合的', category: '托福词汇' },
  { word: 'compress', phonetic: '/kəmˈpres/', meaning: 'v. 压缩；n. 敷布', category: '托福词汇' },
  { word: 'comprise', phonetic: '/kəmˈpraɪz/', meaning: 'v. 包含；由…组成', category: '托福词汇' },
  { word: 'compromise', phonetic: '/ˈkɒmprəmaɪz/', meaning: 'n. 妥协；v. 妥协', category: '托福词汇' },
  { word: 'compulsion', phonetic: '/kəmˈpʌlʃn/', meaning: 'n. 强迫；冲动', category: 'GRE词汇' },
  { word: 'compulsive', phonetic: '/kəmˈpʌlsɪv/', meaning: 'adj. 强迫的；禁不住的', category: 'GRE词汇' },
  { word: 'compulsory', phonetic: '/kəmˈpʌlsəri/', meaning: 'adj. 强制的；义务的', category: '托福词汇' },
  { word: 'computation', phonetic: '/ˌkɒmpjuˈteɪʃn/', meaning: 'n. 计算；估计', category: '科技词汇' },
  { word: 'compute', phonetic: '/kəmˈpjuːt/', meaning: 'v. 计算；估算', category: '科技词汇' },
  { word: 'concave', phonetic: '/kɒnˈkeɪv/', meaning: 'adj. 凹的', category: '科技词汇' },
  { word: 'concede', phonetic: '/kənˈsiːd/', meaning: 'v. 承认；让步', category: '托福词汇' },
  { word: 'conceit', phonetic: '/kənˈsiːt/', meaning: 'n. 自负；奇想', category: 'GRE词汇' },
  { word: 'conceive', phonetic: '/kənˈsiːv/', meaning: 'v. 构想；怀孕', category: '托福词汇' },
  { word: 'concentrate', phonetic: '/ˈkɒnsntreɪt/', meaning: 'v. 集中；浓缩', category: '托福词汇' },
  { word: 'conception', phonetic: '/kənˈsepʃn/', meaning: 'n. 概念；观念', category: '托福词汇' },
  { word: 'concern', phonetic: '/kənˈsɜːn/', meaning: 'n. 关心；v. 涉及', category: '托福词汇' },
  { word: 'concert', phonetic: '/ˈkɒnsət/', meaning: 'n. 音乐会；一致', category: '托福词汇' },
  { word: 'concession', phonetic: '/kənˈseʃn/', meaning: 'n. 让步；特许权', category: '商务词汇' },
  { word: 'conch', phonetic: '/kɒntʃ/', meaning: 'n. 海螺', category: 'GRE词汇' },
  { word: 'conciliate', phonetic: '/kənˈsɪlieɪt/', meaning: 'v. 调解；安抚', category: 'GRE词汇' },
  { word: 'concise', phonetic: '/kənˈsaɪs/', meaning: 'adj. 简明的', category: '托福词汇' },
  { word: 'conclave', phonetic: '/ˈkɒŋkleɪv/', meaning: 'n. 秘密会议', category: 'GRE词汇' },
  { word: 'conclude', phonetic: '/kənˈkluːd/', meaning: 'v. 结束；得出结论', category: '托福词汇' },
  { word: 'concoct', phonetic: '/kənˈkɒkt/', meaning: 'v. 编造；调制', category: 'GRE词汇' },
  { word: 'concomitant', phonetic: '/kənˈkɒmɪtənt/', meaning: 'adj. 伴随的；同时发生的', category: 'GRE词汇' },
  { word: 'concord', phonetic: '/ˈkɒŋkɔːd/', meaning: 'n. 和谐；一致', category: 'GRE词汇' },
  { word: 'concur', phonetic: '/kənˈkɜːr/', meaning: 'v. 同意；同时发生', category: 'GRE词汇' },
  { word: 'concurrent', phonetic: '/kənˈkʌrənt/', meaning: 'adj. 同时发生的', category: '托福词汇' },
  { word: 'condemn', phonetic: '/kənˈdem/', meaning: 'v. 谴责；判刑', category: '托福词汇' },
  { word: 'condense', phonetic: '/kənˈdens/', meaning: 'v. 浓缩；压缩', category: '托福词汇' },
  { word: 'condescend', phonetic: '/ˌkɒndɪˈsend/', meaning: 'v. 屈尊；俯就', category: 'GRE词汇' },
  { word: 'condiment', phonetic: '/ˈkɒndɪmənt/', meaning: 'n. 调味品', category: '日常词汇' },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: 'n. 条件；状态', category: '托福词汇' },
  { word: 'condole', phonetic: '/kənˈdəʊl/', meaning: 'v. 吊唁；慰问', category: 'GRE词汇' },
  { word: 'condone', phonetic: '/kənˈdəʊn/', meaning: 'v. 宽恕；纵容', category: 'GRE词汇' },
  { word: 'conducive', phonetic: '/kənˈdjuːsɪv/', meaning: 'adj. 有益的；有助于…的', category: 'GRE词汇' },
  { word: 'conduct', phonetic: '/kənˈdʌkt/', meaning: 'v. 进行；n. 行为', category: '托福词汇' },
  { word: 'conduit', phonetic: '/ˈkɒndjuɪt/', meaning: 'n. 管道；渠道', category: 'GRE词汇' },
  { word: 'cone', phonetic: '/kəʊn/', meaning: 'n. 圆锥体；球果', category: '科技词汇' },
  { word: 'confection', phonetic: '/kənˈfekʃn/', meaning: 'n. 甜点；精制之物', category: 'GRE词汇' },
  { word: 'confederacy', phonetic: '/kənˈfedərəsi/', meaning: 'n. 联盟；同盟', category: 'GRE词汇' },
  { word: 'confer', phonetic: '/kənˈfɜːr/', meaning: 'v. 协商；授予', category: '托福词汇' },
  { word: 'confess', phonetic: '/kənˈfes/', meaning: 'v. 承认；忏悔', category: '托福词汇' },
  { word: 'confide', phonetic: '/kənˈfaɪd/', meaning: 'v. 吐露；信任', category: 'GRE词汇' },
  { word: 'confidence', phonetic: '/ˈkɒnfɪdəns/', meaning: 'n. 信心；秘密', category: '托福词汇' },
  { word: 'confident', phonetic: '/ˈkɒnfɪdənt/', meaning: 'adj. 自信的', category: '托福词汇' },
  { word: 'confidential', phonetic: '/ˌkɒnfɪˈdenʃl/', meaning: 'adj. 机密的；秘密的', category: '商务词汇' },
  { word: 'configuration', phonetic: '/kənˌfɪɡəˈreɪʃn/', meaning: 'n. 配置；结构', category: '科技词汇' },
  { word: 'confine', phonetic: '/kənˈfaɪn/', meaning: 'v. 限制；禁闭', category: '托福词汇' },
  { word: 'confirm', phonetic: '/kənˈfɜːm/', meaning: 'v. 确认；证实', category: '托福词汇' },
  { word: 'confiscate', phonetic: '/ˈkɒnfɪskeɪt/', meaning: 'v. 没收；充公', category: '法律词汇' },
  { word: 'conflagration', phonetic: '/ˌkɒnfləˈɡreɪʃn/', meaning: 'n. 大火灾', category: 'GRE词汇' },
  { word: 'conflict', phonetic: '/ˈkɒnflɪkt/', meaning: 'n. 冲突；矛盾', category: '托福词汇' },
  { word: 'confluence', phonetic: '/ˈkɒnfluəns/', meaning: 'n. 汇合；汇流处', category: 'GRE词汇' },
  { word: 'conform', phonetic: '/kənˈfɔːm/', meaning: 'v. 遵守；符合', category: '托福词汇' },
  { word: 'conformity', phonetic: '/kənˈfɔːməti/', meaning: 'n. 遵守；一致', category: 'GRE词汇' },
  { word: 'confound', phonetic: '/kənˈfaʊnd/', meaning: 'v. 使困惑；混淆', category: 'GRE词汇' },
  { word: 'confraternity', phonetic: '/ˌkɒnfrəˈtɜːnəti/', meaning: 'n. 兄弟会；协会', category: 'GRE词汇' },
  { word: 'confront', phonetic: '/kənˈfrʌnt/', meaning: 'v. 面对；对抗', category: '托福词汇' },
  { word: 'confuse', phonetic: '/kənˈfjuːz/', meaning: 'v. 使困惑；混淆', category: '托福词汇' },
  { word: 'confutation', phonetic: '/ˌkɒnfjuˈteɪʃn/', meaning: 'n. 驳斥；推翻', category: 'GRE词汇' },
  { word: 'congeal', phonetic: '/kənˈdʒiːl/', meaning: 'v. 凝结；冻结', category: 'GRE词汇' },
  { word: 'congenial', phonetic: '/kənˈdʒiːniəl/', meaning: 'adj. 志趣相投的；适宜的', category: 'GRE词汇' },
  { word: 'congenital', phonetic: '/kənˈdʒenɪtl/', meaning: 'adj. 先天的；天生的', category: '医学词汇' },
  { word: 'congested', phonetic: '/kənˈdʒestɪd/', meaning: 'adj. 拥挤的；充血的', category: '医学词汇' },
  { word: 'conglomerate', phonetic: '/kənˈɡlɒmərət/', meaning: 'n. 企业集团；v. 聚集', category: '商务词汇' },
  { word: 'congregate', phonetic: '/ˈkɒŋɡrɪɡeɪt/', meaning: 'v. 聚集；集合', category: 'GRE词汇' },
  { word: 'congress', phonetic: '/ˈkɒŋɡres/', meaning: 'n. 国会；代表大会', category: '托福词汇' },
  { word: 'congruent', phonetic: '/ˈkɒŋɡruənt/', meaning: 'adj. 一致的；全等的', category: '科技词汇' },
  { word: 'conifer', phonetic: '/ˈkəʊnɪfər/', meaning: 'n. 针叶树', category: 'GRE词汇' },
  { word: 'conjecture', phonetic: '/kənˈdʒektʃər/', meaning: 'n. 推测；v. 猜测', category: 'GRE词汇' },
  { word: 'conjoin', phonetic: '/kənˈdʒɔɪn/', meaning: 'v. 结合；连接', category: 'GRE词汇' },
  { word: 'conjure', phonetic: '/ˈkʌndʒər/', meaning: 'v. 变魔术；召唤', category: 'GRE词汇' },
  { word: 'connive', phonetic: '/kəˈnaɪv/', meaning: 'v. 共谋；纵容', category: 'GRE词汇' },
  { word: 'connoisseur', phonetic: '/ˌkɒnəˈsɜːr/', meaning: 'n. 鉴赏家；行家', category: 'GRE词汇' },
  { word: 'connotation', phonetic: '/ˌkɒnəˈteɪʃn/', meaning: 'n. 内涵；含意', category: '托福词汇' },
  { word: 'connubial', phonetic: '/kəˈnjuːbiəl/', meaning: 'adj. 婚姻的；夫妻的', category: 'GRE词汇' },
  { word: 'conquer', phonetic: '/ˈkɒŋkər/', meaning: 'v. 征服；克服', category: '托福词汇' },
  { word: 'conquest', phonetic: '/ˈkɒŋkwest/', meaning: 'n. 征服；战利品', category: '托福词汇' },
  { word: 'conscience', phonetic: '/ˈkɒnʃəns/', meaning: 'n. 良心；道德心', category: '托福词汇' },
  { word: 'conscientious', phonetic: '/ˌkɒnʃiˈenʃəs/', meaning: 'adj. 认真的；尽责的', category: 'GRE词汇' },
  { word: 'conscious', phonetic: '/ˈkɒnʃəs/', meaning: 'adj. 有意识的；清醒的', category: '托福词汇' },
  { word: 'conscript', phonetic: '/kənˈskrɪpt/', meaning: 'v. 征召；n. 被征召者', category: 'GRE词汇' },
  { word: 'consecrate', phonetic: '/ˈkɒnsɪkreɪt/', meaning: 'v. 奉献；使神圣', category: 'GRE词汇' },
  { word: 'consecutive', phonetic: '/kənˈsekjətɪv/', meaning: 'adj. 连续的；连贯的', category: '托福词汇' },
  { word: 'consensus', phonetic: '/kənˈsensəs/', meaning: 'n. 共识；一致意见', category: '托福词汇' },
  { word: 'consent', phonetic: '/kənˈsent/', meaning: 'n. 同意；v. 允许', category: '托福词汇' },
  { word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', meaning: 'n. 结果；后果', category: '托福词汇' },
  { word: 'consequent', phonetic: '/ˈkɒnsɪkwənt/', meaning: 'adj. 随之发生的', category: 'GRE词汇' },
  { word: 'conservation', phonetic: '/ˌkɒnsəˈveɪʃn/', meaning: 'n. 保护；保存', category: '托福词汇' },
  { word: 'conservative', phonetic: '/kənˈsɜːvətɪv/', meaning: 'adj. 保守的；n. 保守派', category: '托福词汇' },
  { word: 'conserve', phonetic: '/kənˈsɜːv/', meaning: 'v. 保存；节约', category: '托福词汇' },
  { word: 'considerable', phonetic: '/kənˈsɪdərəbl/', meaning: 'adj. 相当大的', category: '托福词汇' },
  { word: 'considerate', phonetic: '/kənˈsɪdərət/', meaning: 'adj. 体贴的；周到的', category: '托福词汇' },
  { word: 'consign', phonetic: '/kənˈsaɪn/', meaning: 'v. 托运；委托', category: '商务词汇' },
  { word: 'consist', phonetic: '/kənˈsɪst/', meaning: 'v. 组成；存在于', category: '托福词汇' },
  { word: 'consistent', phonetic: '/kənˈsɪstənt/', meaning: 'adj. 一致的；始终如一的', category: '托福词汇' },
  { word: 'console', phonetic: '/kənˈsəʊl/', meaning: 'v. 安慰；n. 控制台', category: '托福词汇' },
  { word: 'consolidate', phonetic: '/kənˈsɒlɪdeɪt/', meaning: 'v. 巩固；合并', category: '商务词汇' },
  { word: 'consonance', phonetic: '/ˈkɒnsənəns/', meaning: 'n. 一致；和谐', category: 'GRE词汇' },
  { word: 'consonant', phonetic: '/ˈkɒnsənənt/', meaning: 'n. 辅音；adj. 一致的', category: '托福词汇' },
  { word: 'consort', phonetic: '/ˈkɒnsɔːt/', meaning: 'n. 配偶；v. 结交', category: 'GRE词汇' },
  { word: 'consortium', phonetic: '/kənˈsɔːtiəm/', meaning: 'n. 联营企业；财团', category: '商务词汇' },
  { word: 'conspicuous', phonetic: '/kənˈspɪkjuəs/', meaning: 'adj. 显著的；引人注目的', category: 'GRE词汇' },
  { word: 'conspiracy', phonetic: '/kənˈspɪrəsi/', meaning: 'n. 阴谋；共谋', category: '托福词汇' },
  { word: 'conspire', phonetic: '/kənˈspaɪər/', meaning: 'v. 共谋；密谋', category: 'GRE词汇' },
  { word: 'constancy', phonetic: '/ˈkɒnstənsi/', meaning: 'n. 坚定；恒久', category: 'GRE词汇' },
  { word: 'constant', phonetic: '/ˈkɒnstənt/', meaning: 'adj. 恒定的；不断的', category: '托福词汇' },
  { word: 'constellation', phonetic: '/ˌkɒnstəˈleɪʃn/', meaning: 'n. 星座；群星', category: '托福词汇' },
  { word: 'consternation', phonetic: '/ˌkɒnstəˈneɪʃn/', meaning: 'n. 惊愕；恐慌', category: 'GRE词汇' },
  { word: 'constituent', phonetic: '/kənˈstɪtjuənt/', meaning: 'n. 成分；选民', category: '托福词汇' },
  { word: 'constitute', phonetic: '/ˈkɒnstɪtjuːt/', meaning: 'v. 组成；建立', category: '托福词汇' },
  { word: 'constitution', phonetic: '/ˌkɒnstɪˈtjuːʃn/', meaning: 'n. 宪法；体质', category: '托福词汇' },
  { word: 'constrain', phonetic: '/kənˈstreɪn/', meaning: 'v. 限制；约束', category: 'GRE词汇' },
  { word: 'constraint', phonetic: '/kənˈstreɪnt/', meaning: 'n. 约束；限制', category: '托福词汇' },
  { word: 'constrict', phonetic: '/kənˈstrɪkt/', meaning: 'v. 收缩；压缩', category: 'GRE词汇' },
  { word: 'construct', phonetic: '/kənˈstrʌkt/', meaning: 'v. 建造；构造', category: '托福词汇' },
  { word: 'construe', phonetic: '/kənˈstruː/', meaning: 'v. 解释；理解', category: 'GRE词汇' },
  { word: 'consult', phonetic: '/kənˈsʌlt/', meaning: 'v. 请教；咨询', category: '托福词汇' },
  { word: 'consume', phonetic: '/kənˈsjuːm/', meaning: 'v. 消耗；消费', category: '托福词汇' },
  { word: 'consumer', phonetic: '/kənˈsjuːmər/', meaning: 'n. 消费者', category: '商务词汇' },
  { word: 'consummate', phonetic: '/kənˈsʌmət/', meaning: 'adj. 完美的；v. 完成', category: 'GRE词汇' },
  { word: 'contact', phonetic: '/ˈkɒntækt/', meaning: 'n. 接触；联系', category: '托福词汇' },
  { word: 'contagion', phonetic: '/kənˈteɪdʒən/', meaning: 'n. 传染；蔓延', category: '医学词汇' },
  { word: 'contagious', phonetic: '/kənˈteɪdʒəs/', meaning: 'adj. 传染的；有感染力的', category: '医学词汇' },
  { word: 'contain', phonetic: '/kənˈteɪn/', meaning: 'v. 包含；控制', category: '托福词汇' },
  { word: 'contaminate', phonetic: '/kənˈtæmɪneɪt/', meaning: 'v. 污染；弄脏', category: '托福词汇' },
  { word: 'contemplate', phonetic: '/ˈkɒntəmpleɪt/', meaning: 'v. 沉思；打算', category: '托福词汇' },
  { word: 'contemporaneous', phonetic: '/kənˌtempəˈreɪniəs/', meaning: 'adj. 同时代的', category: 'GRE词汇' },
  { word: 'contemporary', phonetic: '/kənˈtempərəri/', meaning: 'adj. 当代的；n. 同时代人', category: '托福词汇' },
  { word: 'contempt', phonetic: '/kənˈtempt/', meaning: 'n. 轻视；藐视', category: 'GRE词汇' },
  { word: 'contend', phonetic: '/kənˈtend/', meaning: 'v. 竞争；主张', category: '托福词汇' },
  { word: 'content', phonetic: '/ˈkɒntent/', meaning: 'n. 内容；adj. 满足的', category: '托福词汇' },
  { word: 'contentious', phonetic: '/kənˈtenʃəs/', meaning: 'adj. 好争论的；有争议的', category: 'GRE词汇' },
  { word: 'contest', phonetic: '/ˈkɒntest/', meaning: 'n. 比赛；v. 竞争', category: '托福词汇' },
  { word: 'context', phonetic: '/ˈkɒntekst/', meaning: 'n. 上下文；背景', category: '托福词汇' },
  { word: 'contiguous', phonetic: '/kənˈtɪɡjuəs/', meaning: 'adj. 邻近的；接壤的', category: 'GRE词汇' },
  { word: 'continent', phonetic: '/ˈkɒntɪnənt/', meaning: 'n. 大陆；adj. 克制的', category: '托福词汇' },
  { word: 'contingent', phonetic: '/kənˈtɪndʒənt/', meaning: 'adj. 视…而定的；n. 代表团', category: 'GRE词汇' },
  { word: 'continua', phonetic: '/kənˈtɪnjuə/', meaning: 'n. 连续体', category: 'GRE词汇' },
  { word: 'continual', phonetic: '/kənˈtɪnjuəl/', meaning: 'adj. 连续的；频繁的', category: '托福词汇' },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: 'v. 继续；延续', category: '日常词汇' },
  { word: 'continuity', phonetic: '/ˌkɒntɪˈnjuːəti/', meaning: 'n. 连续性', category: '托福词汇' },
  { word: 'continuous', phonetic: '/kənˈtɪnjuəs/', meaning: 'adj. 连续不断的', category: '托福词汇' },
  { word: 'contort', phonetic: '/kənˈtɔːt/', meaning: 'v. 扭曲；弯曲', category: 'GRE词汇' },
  { word: 'contour', phonetic: '/ˈkɒntʊər/', meaning: 'n. 轮廓；外形', category: '托福词汇' },
  { word: 'contraband', phonetic: '/ˈkɒntrəbænd/', meaning: 'n. 走私品；违禁品', category: '法律词汇' },
  { word: 'contract', phonetic: '/ˈkɒntrækt/', meaning: 'n. 合同；v. 收缩', category: '托福词汇' },
  { word: 'contradict', phonetic: '/ˌkɒntrəˈdɪkt/', meaning: 'v. 反驳；与…矛盾', category: '托福词汇' },
  { word: 'contradiction', phonetic: '/ˌkɒntrəˈdɪkʃn/', meaning: 'n. 矛盾；否认', category: '托福词汇' },
  { word: 'contrary', phonetic: '/ˈkɒntrəri/', meaning: 'adj. 相反的；n. 相反', category: '托福词汇' },
  { word: 'contrast', phonetic: '/ˈkɒntrɑːst/', meaning: 'n. 对比；v. 对比', category: '托福词汇' },
  { word: 'contravene', phonetic: '/ˌkɒntrəˈviːn/', meaning: 'v. 违反；抵触', category: '法律词汇' },
  { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: 'v. 贡献；捐献', category: '托福词汇' },
  { word: 'contrite', phonetic: '/kənˈtraɪt/', meaning: 'adj. 悔悟的；痛悔的', category: 'GRE词汇' },
  { word: 'contrivance', phonetic: '/kənˈtraɪvəns/', meaning: 'n. 发明；计谋', category: 'GRE词汇' },
  { word: 'contrive', phonetic: '/kənˈtraɪv/', meaning: 'v. 设计；谋划', category: 'GRE词汇' },
  { word: 'control', phonetic: '/kənˈtrəʊl/', meaning: 'v. 控制；n. 控制', category: '托福词汇' },
  { word: 'controversial', phonetic: '/ˌkɒntrəˈvɜːʃl/', meaning: 'adj. 有争议的', category: '托福词汇' },
  { word: 'controversy', phonetic: '/ˈkɒntrəvɜːsi/', meaning: 'n. 争议；争论', category: '托福词汇' },
  { word: 'controvert', phonetic: '/ˈkɒntrəvɜːt/', meaning: 'v. 反驳；辩论', category: 'GRE词汇' },
  { word: 'convene', phonetic: '/kənˈviːn/', meaning: 'v. 召集；集合', category: 'GRE词汇' },
  { word: 'convenience', phonetic: '/kənˈviːniəns/', meaning: 'n. 方便；便利', category: '托福词汇' },
  { word: 'convenient', phonetic: '/kənˈviːniənt/', meaning: 'adj. 方便的；便利的', category: '托福词汇' },
  { word: 'convent', phonetic: '/ˈkɒnvent/', meaning: 'n. 女修道院', category: 'GRE词汇' },
  { word: 'convention', phonetic: '/kənˈvenʃn/', meaning: 'n. 大会；惯例', category: '托福词汇' },
  { word: 'conventional', phonetic: '/kənˈvenʃənl/', meaning: 'adj. 传统的；常规的', category: '托福词汇' },
  { word: 'converge', phonetic: '/kənˈvɜːdʒ/', meaning: 'v. 汇聚；集中', category: 'GRE词汇' },
  { word: 'converse', phonetic: '/kənˈvɜːs/', meaning: 'v. 交谈；adj. 相反的', category: '托福词汇' },
  { word: 'conversion', phonetic: '/kənˈvɜːʃn/', meaning: 'n. 转换；改变', category: '托福词汇' },
  { word: 'convert', phonetic: '/kənˈvɜːt/', meaning: 'v. 转换；改变信仰', category: '托福词汇' },
  { word: 'convex', phonetic: '/kənˈveks/', meaning: 'adj. 凸的', category: '科技词汇' },
  { word: 'convey', phonetic: '/kənˈveɪ/', meaning: 'v. 传达；运输', category: '托福词汇' },
  { word: 'conveyance', phonetic: '/kənˈveɪəns/', meaning: 'n. 运输；转让', category: '法律词汇' },
  { word: 'convict', phonetic: '/kənˈvɪkt/', meaning: 'v. 定罪；n. 囚犯', category: '法律词汇' },
  { word: 'conviction', phonetic: '/kənˈvɪkʃn/', meaning: 'n. 定罪；信念', category: '托福词汇' },
  { word: 'convince', phonetic: '/kənˈvɪns/', meaning: 'v. 说服；使确信', category: '托福词汇' },
  { word: 'convivial', phonetic: '/kənˈvɪviəl/', meaning: 'adj. 欢乐的；好交际的', category: 'GRE词汇' },
  { word: 'convoke', phonetic: '/kənˈvəʊk/', meaning: 'v. 召集', category: 'GRE词汇' },
  { word: 'convoluted', phonetic: '/ˈkɒnvəluːtɪd/', meaning: 'adj. 复杂的；费解的', category: 'GRE词汇' },
  { word: 'convoy', phonetic: '/ˈkɒnvɔɪ/', meaning: 'n. 护航队；v. 护送', category: 'GRE词汇' },
  { word: 'convulse', phonetic: '/kənˈvʌls/', meaning: 'v. 使震动；使抽搐', category: 'GRE词汇' },
  { word: 'coop', phonetic: '/kuːp/', meaning: 'n. 鸡笼；v. 拘禁', category: 'GRE词汇' },
  { word: 'cooperate', phonetic: '/kəʊˈɒpəreɪt/', meaning: 'v. 合作；配合', category: '托福词汇' },
  { word: 'cooperative', phonetic: '/kəʊˈɒpərətɪv/', meaning: 'adj. 合作的；n. 合作社', category: '托福词汇' },
  { word: 'coordinate', phonetic: '/kəʊˈɔːdɪnət/', meaning: 'v. 协调；n. 坐标', category: '托福词汇' },
  { word: 'coordination', phonetic: '/kəʊˌɔːdɪˈneɪʃn/', meaning: 'n. 协调；配合', category: '托福词汇' },
  { word: 'copious', phonetic: '/ˈkəʊpiəs/', meaning: 'adj. 大量的；丰富的', category: 'GRE词汇' },
  { word: 'coquette', phonetic: '/kɒˈket/', meaning: 'n. 卖弄风情的女子', category: 'GRE词汇' },
  { word: 'cordial', phonetic: '/ˈkɔːdiəl/', meaning: 'adj. 热情的；n. 兴奋剂', category: 'GRE词汇' },
  { word: 'cordon', phonetic: '/ˈkɔːdn/', meaning: 'n. 警戒线；饰带', category: 'GRE词汇' },
  { word: 'cornucopia', phonetic: '/ˌkɔːnjuˈkəʊpiə/', meaning: 'n. 丰饶之角；丰富', category: 'GRE词汇' },
  { word: 'corollary', phonetic: '/kəˈrɒləri/', meaning: 'n. 推论；必然结果', category: 'GRE词汇' },
  { word: 'corona', phonetic: '/kəˈrəʊnə/', meaning: 'n. 日冕；冠状物', category: '科技词汇' },
  { word: 'corporal', phonetic: '/ˈkɔːpərəl/', meaning: 'adj. 肉体的；n. 下士', category: 'GRE词汇' },
  { word: 'corporate', phonetic: '/ˈkɔːpərət/', meaning: 'adj. 公司的；共同的', category: '商务词汇' },
  { word: 'corporation', phonetic: '/ˌkɔːpəˈreɪʃn/', meaning: 'n. 公司；法人', category: '商务词汇' },
  { word: 'corporeal', phonetic: '/kɔːˈpɔːriəl/', meaning: 'adj. 肉体的；物质的', category: 'GRE词汇' },
  { word: 'corpulent', phonetic: '/ˈkɔːpjələnt/', meaning: 'adj. 肥胖的', category: 'GRE词汇' },
  { word: 'corral', phonetic: '/kəˈrɑːl/', meaning: 'n. 畜栏；v. 关入畜栏', category: 'GRE词汇' },
  { word: 'correct', phonetic: '/kəˈrekt/', meaning: 'adj. 正确的；v. 纠正', category: '托福词汇' },
  { word: 'correlate', phonetic: '/ˈkɒrəleɪt/', meaning: 'v. 相关；关联', category: '托福词汇' },
  { word: 'correlation', phonetic: '/ˌkɒrəˈleɪʃn/', meaning: 'n. 相关；关联', category: '托福词汇' },
  { word: 'corroborate', phonetic: '/kəˈrɒbəreɪt/', meaning: 'v. 证实；支持', category: 'GRE词汇' },
  { word: 'corrode', phonetic: '/kəˈrəʊd/', meaning: 'v. 腐蚀；侵蚀', category: '托福词汇' },
  { word: 'corrosion', phonetic: '/kəˈrəʊʒn/', meaning: 'n. 腐蚀；侵蚀', category: '科技词汇' },
  { word: 'corrosive', phonetic: '/kəˈrəʊsɪv/', meaning: 'adj. 腐蚀性的', category: '科技词汇' },
  { word: 'corrugate', phonetic: '/ˈkɒrʊɡeɪt/', meaning: 'v. 使起皱纹', category: 'GRE词汇' },
  { word: 'corrupt', phonetic: '/kəˈrʌpt/', meaning: 'adj. 腐败的；v. 腐蚀', category: '托福词汇' },
  { word: 'corruptible', phonetic: '/kəˈrʌptəbl/', meaning: 'adj. 易腐败的；易堕落的', category: 'GRE词汇' },
  { word: 'cosmic', phonetic: '/ˈkɒzmɪk/', meaning: 'adj. 宇宙的；巨大的', category: '科技词汇' },
  { word: 'cosmos', phonetic: '/ˈkɒzmɒs/', meaning: 'n. 宇宙；秩序', category: '科技词汇' },
  { word: 'cosmopolitan', phonetic: '/ˌkɒzməˈpɒlɪtən/', meaning: 'adj. 世界性的；国际的', category: 'GRE词汇' },
  { word: 'coterie', phonetic: '/ˈkəʊtəri/', meaning: 'n. 小圈子；志同道合的一群人', category: 'GRE词汇' },
  { word: 'coterminous', phonetic: '/kəʊˈtɜːmɪnəs/', meaning: 'adj. 相连的；毗连的', category: 'GRE词汇' },
  { word: 'cotillion', phonetic: '/kəʊˈtɪljən/', meaning: 'n. 正式舞会', category: 'GRE词汇' },
  { word: 'couch', phonetic: '/kaʊtʃ/', meaning: 'n. 长沙发；v. 表达', category: '托福词汇' },
  { word: 'cough', phonetic: '/kɒf/', meaning: 'v. 咳嗽；n. 咳嗽', category: '医学词汇' },
  { word: 'council', phonetic: '/ˈkaʊnsl/', meaning: 'n. 委员会；议会', category: '托福词汇' },
  { word: 'counsel', phonetic: '/ˈkaʊnsl/', meaning: 'n. 律师；忠告；v. 建议', category: '法律词汇' },
  { word: 'counselor', phonetic: '/ˈkaʊnsələr/', meaning: 'n. 顾问；律师', category: '商务词汇' },
  { word: 'countenance', phonetic: '/ˈkaʊntənəns/', meaning: 'n. 面容；v. 支持', category: 'GRE词汇' },
  { word: 'counteract', phonetic: '/ˌkaʊntərˈækt/', meaning: 'v. 抵消；对抗', category: '托福词汇' },
  { word: 'counterbalance', phonetic: '/ˈkaʊntəbæləns/', meaning: 'v. 抵消；平衡', category: 'GRE词汇' },
  { word: 'counterfeit', phonetic: '/ˈkaʊntəfɪt/', meaning: 'adj. 伪造的；v. 伪造', category: '法律词汇' },
  { word: 'counterpart', phonetic: '/ˈkaʊntəpɑːt/', meaning: 'n. 对应的人或物', category: '托福词汇' },
  { word: 'countless', phonetic: '/ˈkaʊntləs/', meaning: 'adj. 无数的', category: '托福词汇' },
  { word: 'coup', phonetic: '/kuː/', meaning: 'n. 政变；妙计', category: 'GRE词汇' },
  { word: 'couple', phonetic: '/ˈkʌpl/', meaning: 'n. 一对；v. 连接', category: '托福词汇' },
  { word: 'coupon', phonetic: '/ˈkuːpɒn/', meaning: 'n. 优惠券；息票', category: '商务词汇' },
  { word: 'courageous', phonetic: '/kəˈreɪdʒəs/', meaning: 'adj. 勇敢的', category: '托福词汇' },
  { word: 'courier', phonetic: '/ˈkʊriər/', meaning: 'n. 快递员；信使', category: '商务词汇' },
  { word: 'courteous', phonetic: '/ˈkɜːtiəs/', meaning: 'adj. 有礼貌的', category: '托福词汇' },
  { word: 'courtesy', phonetic: '/ˈkɜːtəsi/', meaning: 'n. 礼貌；好意', category: '托福词汇' },
  { word: 'courtship', phonetic: '/ˈkɔːtʃɪp/', meaning: 'n. 求爱；追求', category: 'GRE词汇' },
  { word: 'covenant', phonetic: '/ˈkʌvənənt/', meaning: 'n. 契约；盟约', category: '法律词汇' },
  { word: 'cover', phonetic: '/ˈkʌvər/', meaning: 'v. 覆盖；n. 封面', category: '日常词汇' },
  { word: 'covert', phonetic: '/ˈkʌvət/', meaning: 'adj. 秘密的；隐蔽的', category: 'GRE词汇' },
  { word: 'covet', phonetic: '/ˈkʌvɪt/', meaning: 'v. 贪图；觊觎', category: 'GRE词汇' },
  { word: 'covetous', phonetic: '/ˈkʌvɪtəs/', meaning: 'adj. 贪婪的', category: 'GRE词汇' },
  { word: 'cow', phonetic: '/kaʊ/', meaning: 'n. 母牛；v. 威吓', category: '日常词汇' },
  { word: 'cowardice', phonetic: '/ˈkaʊədɪs/', meaning: 'n. 胆怯；懦弱', category: 'GRE词汇' },
  { word: 'cowardly', phonetic: '/ˈkaʊədli/', meaning: 'adj. 胆怯的', category: 'GRE词汇' },
  { word: 'cower', phonetic: '/ˈkaʊər/', meaning: 'v. 畏缩；发抖', category: 'GRE词汇' },
  { word: 'coy', phonetic: '/kɔɪ/', meaning: 'adj. 害羞的；故作忸怩的', category: 'GRE词汇' },
  { word: 'cozen', phonetic: '/ˈkʌzn/', meaning: 'v. 欺骗；哄骗', category: 'GRE词汇' },
  { word: 'crabbed', phonetic: '/ˈkræbɪd/', meaning: 'adj. 脾气暴躁的；难懂的', category: 'GRE词汇' },
  { word: 'crack', phonetic: '/kræk/', meaning: 'v. 破裂；n. 裂缝', category: '日常词汇' },
  { word: 'crackdown', phonetic: '/ˈkrækdaʊn/', meaning: 'n. 镇压；制裁', category: '托福词汇' },
  { word: 'cradle', phonetic: '/ˈkreɪdl/', meaning: 'n. 摇篮；发源地', category: '托福词汇' },
  { word: 'craft', phonetic: '/krɑːft/', meaning: 'n. 工艺；v. 精心制作', category: '托福词汇' },
  { word: 'crafty', phonetic: '/ˈkrɑːfti/', meaning: 'adj. 狡猾的；诡计多端的', category: 'GRE词汇' },
  { word: 'crag', phonetic: '/kræɡ/', meaning: 'n. 悬崖；峭壁', category: 'GRE词汇' },
  { word: 'cram', phonetic: '/kræm/', meaning: 'v. 填满；死记硬背', category: '托福词汇' },
  { word: 'cramp', phonetic: '/kræmp/', meaning: 'n. 痉挛；v. 限制', category: '医学词汇' },
  { word: 'cranky', phonetic: '/ˈkræŋki/', meaning: 'adj. 脾气坏的', category: 'GRE词汇' },
  { word: 'crash', phonetic: '/kræʃ/', meaning: 'v. 撞击；n. 崩溃', category: '托福词汇' },
  { word: 'crass', phonetic: '/kræs/', meaning: 'adj. 愚钝的；粗鲁的', category: 'GRE词汇' },
  { word: 'crate', phonetic: '/kreɪt/', meaning: 'n. 板条箱', category: '商务词汇' },
  { word: 'crater', phonetic: '/ˈkreɪtər/', meaning: 'n. 火山口；弹坑', category: '科技词汇' },
  { word: 'crave', phonetic: '/kreɪv/', meaning: 'v. 渴望；恳求', category: 'GRE词汇' },
  { word: 'craven', phonetic: '/ˈkreɪvn/', meaning: 'adj. 怯懦的', category: 'GRE词汇' },
  { word: 'craving', phonetic: '/ˈkreɪvɪŋ/', meaning: 'n. 渴望', category: 'GRE词汇' },
  { word: 'crawl', phonetic: '/krɔːl/', meaning: 'v. 爬行；n. 爬行', category: '日常词汇' },
  { word: 'craze', phonetic: '/kreɪz/', meaning: 'n. 狂热；v. 使发狂', category: 'GRE词汇' },
  { word: 'creak', phonetic: '/kriːk/', meaning: 'v. 吱吱作响', category: 'GRE词汇' },
  { word: 'cream', phonetic: '/kriːm/', meaning: 'n. 奶油；精华', category: '日常词汇' },
  { word: 'crease', phonetic: '/kriːs/', meaning: 'n. 折痕；v. 起皱', category: '日常词汇' },
  { word: 'creative', phonetic: '/kriˈeɪtɪv/', meaning: 'adj. 创造性的', category: '托福词汇' },
  { word: 'creativity', phonetic: '/ˌkriːeɪˈtɪvəti/', meaning: 'n. 创造力', category: '托福词汇' },
  { word: 'creator', phonetic: '/kriˈeɪtər/', meaning: 'n. 创造者', category: '托福词汇' },
  { word: 'creature', phonetic: '/ˈkriːtʃər/', meaning: 'n. 生物；人', category: '托福词汇' },
  { word: 'credence', phonetic: '/ˈkriːdns/', meaning: 'n. 相信；信任', category: 'GRE词汇' },
  { word: 'credential', phonetic: '/krəˈdenʃl/', meaning: 'n. 凭证；资历', category: '商务词汇' },
  { word: 'credible', phonetic: '/ˈkredəbl/', meaning: 'adj. 可信的', category: '托福词汇' },
  { word: 'credit', phonetic: '/ˈkredɪt/', meaning: 'n. 信用；学分', category: '商务词汇' },
  { word: 'creditor', phonetic: '/ˈkredɪtər/', meaning: 'n. 债权人', category: '商务词汇' },
  { word: 'credulous', phonetic: '/ˈkredʒələs/', meaning: 'adj. 轻信的；易受骗的', category: 'GRE词汇' },
  { word: 'creed', phonetic: '/kriːd/', meaning: 'n. 信条；教义', category: 'GRE词汇' },
  { word: 'creek', phonetic: '/kriːk/', meaning: 'n. 小溪', category: '日常词汇' },
  { word: 'creep', phonetic: '/kriːp/', meaning: 'v. 爬行；悄悄移动', category: '托福词汇' },
  { word: 'cremate', phonetic: '/krɪˈmeɪt/', meaning: 'v. 火化；焚化', category: 'GRE词汇' },
  { word: 'crevice', phonetic: '/ˈkrevɪs/', meaning: 'n. 裂缝；缺口', category: 'GRE词汇' },
  { word: 'cringe', phonetic: '/krɪndʒ/', meaning: 'v. 畏缩；尴尬', category: 'GRE词汇' },
  { word: 'crinkle', phonetic: '/ˈkrɪŋkl/', meaning: 'v. 起皱；n. 皱纹', category: 'GRE词汇' },
  { word: 'cripple', phonetic: '/ˈkrɪpl/', meaning: 'n. 跛子；v. 削弱', category: '托福词汇' },
  { word: 'crisis', phonetic: '/ˈkraɪsɪs/', meaning: 'n. 危机；关键时刻', category: '托福词汇' },
  { word: 'crisp', phonetic: '/krɪsp/', meaning: 'adj. 脆的；清新的', category: '托福词汇' },
  { word: 'crisscross', phonetic: '/ˈkrɪskrɒs/', meaning: 'v. 交叉；n. 十字图案', category: 'GRE词汇' },
  { word: 'criteria', phonetic: '/kraɪˈtɪəriə/', meaning: 'n. 标准；准则', category: '托福词汇' },
  { word: 'criterion', phonetic: '/kraɪˈtɪəriən/', meaning: 'n. 标准；准则', category: '托福词汇' },
  { word: 'critic', phonetic: '/ˈkrɪtɪk/', meaning: 'n. 批评家；评论家', category: '托福词汇' },
  { word: 'critical', phonetic: '/ˈkrɪtɪkl/', meaning: 'adj. 批评的；关键的', category: '托福词汇' },
  { word: 'criticism', phonetic: '/ˈkrɪtɪsɪzəm/', meaning: 'n. 批评；评论', category: '托福词汇' },
  { word: 'criticize', phonetic: '/ˈkrɪtɪsaɪz/', meaning: 'v. 批评；评论', category: '托福词汇' },
  { word: 'critique', phonetic: '/krɪˈtiːk/', meaning: 'n. 评论；v. 评论', category: '托福词汇' },
  { word: 'croak', phonetic: '/krəʊk/', meaning: 'v. 发出低沉声；n. 蛙鸣', category: 'GRE词汇' },
  { word: 'crockery', phonetic: '/ˈkrɒkəri/', meaning: 'n. 陶器', category: 'GRE词汇' },
  { word: 'crooked', phonetic: '/ˈkrʊkɪd/', meaning: 'adj. 弯曲的；不诚实的', category: 'GRE词汇' },
  { word: 'crop', phonetic: '/krɒp/', meaning: 'n. 庄稼；收成', category: '托福词汇' },
  { word: 'cropper', phonetic: '/ˈkrɒpər/', meaning: 'n. 大失败', category: 'GRE词汇' },
  { word: 'cross', phonetic: '/krɒs/', meaning: 'v. 穿过；n. 十字架', category: '日常词汇' },
  { word: 'crotchety', phonetic: '/ˈkrɒtʃɪti/', meaning: 'adj. 脾气坏的', category: 'GRE词汇' },
  { word: 'crouch', phonetic: '/kraʊtʃ/', meaning: 'v. 蹲伏', category: 'GRE词汇' },
  { word: 'crow', phonetic: '/krəʊ/', meaning: 'n. 乌鸦；v. 啼叫', category: '日常词汇' },
  { word: 'crowd', phonetic: '/kraʊd/', meaning: 'n. 人群；v. 拥挤', category: '托福词汇' },
  { word: 'crown', phonetic: '/kraʊn/', meaning: 'n. 王冠；v. 加冕', category: '托福词汇' },
  { word: 'crucial', phonetic: '/ˈkruːʃl/', meaning: 'adj. 关键的；至关重要的', category: '托福词汇' },
  { word: 'crucible', phonetic: '/ˈkruːsɪbl/', meaning: 'n. 坩埚；严峻考验', category: 'GRE词汇' },
  { word: 'crucifix', phonetic: '/ˈkruːsɪfɪks/', meaning: 'n. 十字架', category: 'GRE词汇' },
  { word: 'crucify', phonetic: '/ˈkruːsɪfaɪ/', meaning: 'v. 钉在十字架上；折磨', category: 'GRE词汇' },
  { word: 'crude', phonetic: '/kruːd/', meaning: 'adj. 粗糙的；天然的', category: '托福词汇' },
  { word: 'cruel', phonetic: '/ˈkruːəl/', meaning: 'adj. 残忍的；残酷的', category: '托福词汇' },
  { word: 'cruelty', phonetic: '/ˈkruːəlti/', meaning: 'n. 残忍；残酷', category: '托福词汇' },
  { word: 'cruising', phonetic: '/ˈkruːzɪŋ/', meaning: 'n. 巡航；漫游', category: 'GRE词汇' },
  { word: 'rumple', phonetic: '/ˈrʌmpl/', meaning: 'v. 弄皱；弄乱', category: 'GRE词汇' },
  { word: 'crusade', phonetic: '/kruːˈseɪd/', meaning: 'n. 十字军东征；v. 投身运动', category: 'GRE词汇' },
  { word: 'crush', phonetic: '/krʌʃ/', meaning: 'v. 压碎；n. 迷恋', category: '托福词汇' },
  { word: 'crust', phonetic: '/krʌst/', meaning: 'n. 外壳；地壳', category: '托福词汇' },
  { word: 'crusty', phonetic: '/ˈkrʌsti/', meaning: 'adj. 有硬皮的；暴躁的', category: 'GRE词汇' },
  { word: 'crutch', phonetic: '/krʌtʃ/', meaning: 'n. 拐杖；支撑', category: '医学词汇' },
  { word: 'crux', phonetic: '/krʌks/', meaning: 'n. 关键；症结', category: 'GRE词汇' },
  { word: 'cryptic', phonetic: '/ˈkrɪptɪk/', meaning: 'adj. 神秘的；晦涩的', category: 'GRE词汇' },
  { word: 'crystal', phonetic: '/ˈkrɪstl/', meaning: 'n. 水晶；adj. 清晰的', category: '托福词汇' },
  { word: 'crystallize', phonetic: '/ˈkrɪstəlaɪz/', meaning: 'v. 结晶；使具体化', category: '托福词汇' },
];

export { wordsDataPart2 };
