// I字母开头的单词
import { getSupabaseClient } from '../src/storage/database/supabase-client';

const supabase = getSupabaseClient();
const WORDS_TABLE = 'words';

const wordsI = [
  { word: 'I', phonetic: '/aɪ/', meaning: 'pron. 我', category: '托福词汇' },
  { word: 'ice', phonetic: '/aɪs/', meaning: 'n. 冰', category: '托福词汇' },
  { word: 'iceberg', phonetic: '/ˈaɪsbɜːrɡ/', meaning: 'n. 冰山', category: '托福词汇' },
  { word: 'icicle', phonetic: '/ˈaɪsɪkl/', meaning: 'n. 冰柱', category: 'GRE词汇' },
  { word: 'icy', phonetic: '/ˈaɪsi/', meaning: 'adj. 冰冷的', category: '托福词汇' },
  { word: 'idea', phonetic: '/aɪˈdɪə/', meaning: 'n. 想法；主意', category: '托福词汇' },
  { word: 'ideal', phonetic: '/aɪˈdɪəl/', meaning: 'adj. 理想的；n. 理想', category: '托福词汇' },
  { word: 'idealism', phonetic: '/aɪˈdɪəlɪzəm/', meaning: 'n. 理想主义', category: 'GRE词汇' },
  { word: 'idealist', phonetic: '/aɪˈdɪəlɪst/', meaning: 'n. 理想主义者', category: 'GRE词汇' },
  { word: 'idealize', phonetic: '/aɪˈdɪəlaɪz/', meaning: 'v. 理想化', category: 'GRE词汇' },
  { word: 'ideally', phonetic: '/aɪˈdɪəli/', meaning: 'adv. 理想地', category: '托福词汇' },
  { word: 'identical', phonetic: '/aɪˈdentɪkl/', meaning: 'adj. 完全相同的', category: '托福词汇' },
  { word: 'identification', phonetic: '/aɪˌdentɪfɪˈkeɪʃn/', meaning: 'n. 识别；身份证明', category: '托福词汇' },
  { word: 'identify', phonetic: '/aɪˈdentɪfaɪ/', meaning: 'v. 识别；确认', category: '托福词汇' },
  { word: 'identity', phonetic: '/aɪˈdentəti/', meaning: 'n. 身份', category: '托福词汇' },
  { word: 'ideology', phonetic: '/ˌaɪdɪˈɒlədʒi/', meaning: 'n. 意识形态', category: 'GRE词汇' },
  { word: 'idiom', phonetic: '/ˈɪdɪəm/', meaning: 'n. 习语', category: '托福词汇' },
  { word: 'idiosyncrasy', phonetic: '/ˌɪdɪəˈsɪŋkrəsi/', meaning: 'n. 特质', category: 'GRE词汇' },
  { word: 'idiot', phonetic: '/ˈɪdɪət/', meaning: 'n. 白痴', category: '托福词汇' },
  { word: 'idle', phonetic: '/ˈaɪdl/', meaning: 'adj. 空闲的；v. 虚度', category: 'GRE词汇' },
  { word: 'idol', phonetic: '/ˈaɪdl/', meaning: 'n. 偶像', category: '托福词汇' },
  { word: 'idolize', phonetic: '/ˈaɪdəlaɪz/', meaning: 'v. 崇拜', category: 'GRE词汇' },
  { word: 'idyllic', phonetic: '/ɪˈdɪlɪk/', meaning: 'adj. 田园诗般的', category: 'GRE词汇' },
  { word: 'if', phonetic: '/ɪf/', meaning: 'conj. 如果', category: '托福词汇' },
  { word: 'ignite', phonetic: '/ɪɡˈnaɪt/', meaning: 'v. 点燃', category: 'GRE词汇' },
  { word: 'ignition', phonetic: '/ɪɡˈnɪʃn/', meaning: 'n. 点火', category: 'GRE词汇' },
  { word: 'ignoble', phonetic: '/ɪɡˈnəʊbl/', meaning: 'adj. 卑鄙的', category: 'GRE词汇' },
  { word: 'ignominious', phonetic: '/ˌɪɡnəˈmɪniəs/', meaning: 'adj. 可耻的', category: 'GRE词汇' },
  { word: 'ignominy', phonetic: '/ˈɪɡnəmɪni/', meaning: 'n. 耻辱', category: 'GRE词汇' },
  { word: 'ignorance', phonetic: '/ˈɪɡnərəns/', meaning: 'n. 无知', category: '托福词汇' },
  { word: 'ignorant', phonetic: '/ˈɪɡnərənt/', meaning: 'adj. 无知的', category: '托福词汇' },
  { word: 'ignore', phonetic: '/ɪɡˈnɔːr/', meaning: 'v. 忽视', category: '托福词汇' },
  { word: 'ill', phonetic: '/ɪl/', meaning: 'adj. 生病的；adv. 恶劣地', category: '托福词汇' },
  { word: 'illegal', phonetic: '/ɪˈliːɡl/', meaning: 'adj. 非法的', category: '托福词汇' },
  { word: 'illegible', phonetic: '/ɪˈledʒəbl/', meaning: 'adj. 难以辨认的', category: 'GRE词汇' },
  { word: 'illegitimate', phonetic: '/ˌɪlɪˈdʒɪtəmət/', meaning: 'adj. 非法的；私生的', category: 'GRE词汇' },
  { word: 'illiberal', phonetic: '/ɪˈlɪbərəl/', meaning: 'adj. 狭隘的', category: 'GRE词汇' },
  { word: 'illicit', phonetic: '/ɪˈlɪsɪt/', meaning: 'adj. 非法的', category: 'GRE词汇' },
  { word: 'illimitable', phonetic: '/ɪˈlɪmɪtəbl/', meaning: 'adj. 无限的', category: 'GRE词汇' },
  { word: 'illiterate', phonetic: '/ɪˈlɪtərət/', meaning: 'adj. 文盲的；n. 文盲', category: 'GRE词汇' },
  { word: 'illness', phonetic: '/ˈɪlnəs/', meaning: 'n. 疾病', category: '托福词汇' },
  { word: 'illogic', phonetic: '/ɪˈlɒdʒɪk/', meaning: 'n. 缺乏逻辑', category: 'GRE词汇' },
  { word: 'illogical', phonetic: '/ɪˈlɒdʒɪkl/', meaning: 'adj. 不合逻辑的', category: 'GRE词汇' },
  { word: 'illuminate', phonetic: '/ɪˈluːmɪneɪt/', meaning: 'v. 照亮；阐明', category: 'GRE词汇' },
  { word: 'illumination', phonetic: '/ɪˌluːmɪˈneɪʃn/', meaning: 'n. 照明', category: 'GRE词汇' },
  { word: 'illusion', phonetic: '/ɪˈluːʒn/', meaning: 'n. 幻觉', category: '托福词汇' },
  { word: 'illusory', phonetic: '/ɪˈluːsəri/', meaning: 'adj. 虚幻的', category: 'GRE词汇' },
  { word: 'illustrate', phonetic: '/ˈɪləstreɪt/', meaning: 'v. 说明；插图', category: '托福词汇' },
  { word: 'illustration', phonetic: '/ˌɪləˈstreɪʃn/', meaning: 'n. 说明；插图', category: '托福词汇' },
  { word: 'illustrious', phonetic: '/ɪˈlʌstriəs/', meaning: 'adj. 杰出的', category: 'GRE词汇' },
  { word: 'image', phonetic: '/ˈɪmɪdʒ/', meaning: 'n. 图像；形象', category: '托福词汇' },
  { word: 'imagery', phonetic: '/ˈɪmɪdʒəri/', meaning: 'n. 意象', category: 'GRE词汇' },
  { word: 'imaginary', phonetic: '/ɪˈmædʒɪnəri/', meaning: 'adj. 想象的', category: '托福词汇' },
  { word: 'imagination', phonetic: '/ɪˌmædʒɪˈneɪʃn/', meaning: 'n. 想象力', category: '托福词汇' },
  { word: 'imaginative', phonetic: '/ɪˈmædʒɪnətɪv/', meaning: 'adj. 富有想象力的', category: 'GRE词汇' },
  { word: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: 'v. 想象', category: '托福词汇' },
  { word: 'imbalance', phonetic: '/ɪmˈbæləns/', meaning: 'n. 不平衡', category: 'GRE词汇' },
  { word: 'imbecile', phonetic: '/ˈɪmbəsiːl/', meaning: 'n. 蠢人；adj. 愚蠢的', category: 'GRE词汇' },
  { word: 'imbezzle', phonetic: '/ɪmˈbezl/', meaning: 'v. 挪用', category: 'GRE词汇' },
  { word: 'imbibe', phonetic: '/ɪmˈbaɪb/', meaning: 'v. 喝；吸收', category: 'GRE词汇' },
  { word: 'imbroglio', phonetic: '/ɪmˈbrəʊliəʊ/', meaning: 'n. 纠纷', category: 'GRE词汇' },
  { word: 'imbue', phonetic: '/ɪmˈbjuː/', meaning: 'v. 灌输', category: 'GRE词汇' },
  { word: 'imitate', phonetic: '/ˈɪmɪteɪt/', meaning: 'v. 模仿', category: '托福词汇' },
  { word: 'imitation', phonetic: '/ˌɪmɪˈteɪʃn/', meaning: 'n. 模仿；仿制品', category: '托福词汇' },
  { word: 'imitative', phonetic: '/ˈɪmɪtətɪv/', meaning: 'adj. 模仿的', category: 'GRE词汇' },
  { word: 'immaculate', phonetic: '/ɪˈmækjələt/', meaning: 'adj. 完美的', category: 'GRE词汇' },
  { word: 'immanent', phonetic: '/ˈɪmənənt/', meaning: 'adj. 内在的', category: 'GRE词汇' },
  { word: 'immaterial', phonetic: '/ˌɪməˈtɪəriəl/', meaning: 'adj. 不重要的', category: 'GRE词汇' },
  { word: 'immature', phonetic: '/ˌɪməˈtjʊər/', meaning: 'adj. 不成熟的', category: '托福词汇' },
  { word: 'immeasurable', phonetic: '/ɪˈmeʒərəbl/', meaning: 'adj. 不可估量的', category: 'GRE词汇' },
  { word: 'immediate', phonetic: '/ɪˈmiːdiət/', meaning: 'adj. 立即的', category: '托福词汇' },
  { word: 'immediately', phonetic: '/ɪˈmiːdiətli/', meaning: 'adv. 立即', category: '托福词汇' },
  { word: 'immense', phonetic: '/ɪˈmens/', meaning: 'adj. 巨大的', category: '托福词汇' },
  { word: 'immensely', phonetic: '/ɪˈmensli/', meaning: 'adv. 极大地', category: '托福词汇' },
  { word: 'immersion', phonetic: '/ɪˈmɜːrʃn/', meaning: 'n. 沉浸', category: 'GRE词汇' },
  { word: 'immigrant', phonetic: '/ˈɪmɪɡrənt/', meaning: 'n. 移民', category: '托福词汇' },
  { word: 'immigrate', phonetic: '/ˈɪmɪɡreɪt/', meaning: 'v. 移民', category: '托福词汇' },
  { word: 'imminent', phonetic: '/ˈɪmɪnənt/', meaning: 'adj. 即将发生的', category: 'GRE词汇' },
  { word: 'immobile', phonetic: '/ɪˈməʊbaɪl/', meaning: 'adj. 不动的', category: 'GRE词汇' },
  { word: 'immobilize', phonetic: '/ɪˈməʊbəlaɪz/', meaning: 'v. 使不动', category: 'GRE词汇' },
  { word: 'immoral', phonetic: '/ɪˈmɒrəl/', meaning: 'adj. 不道德的', category: 'GRE词汇' },
  { word: 'immortal', phonetic: '/ɪˈmɔːrtl/', meaning: 'adj. 不朽的；n. 不朽者', category: 'GRE词汇' },
  { word: 'immortality', phonetic: '/ˌɪmɔːrˈtæləti/', meaning: 'n. 不朽', category: 'GRE词汇' },
  { word: 'immune', phonetic: '/ɪˈmjuːn/', meaning: 'adj. 免疫的', category: '托福词汇' },
  { word: 'immunity', phonetic: '/ɪˈmjuːnəti/', meaning: 'n. 免疫力', category: '托福词汇' },
  { word: 'immunize', phonetic: '/ˈɪmjunaɪz/', meaning: 'v. 使免疫', category: '医学词汇' },
  { word: 'immure', phonetic: '/ɪˈmjʊər/', meaning: 'v. 监禁', category: 'GRE词汇' },
  { word: 'immutable', phonetic: '/ɪˈmjuːtəbl/', meaning: 'adj. 不可改变的', category: 'GRE词汇' },
  { word: 'imp', phonetic: '/ɪmp/', meaning: 'n. 小鬼', category: 'GRE词汇' },
  { word: 'impact', phonetic: '/ˈɪmpækt/', meaning: 'n. 影响；v. 影响', category: '托福词汇' },
  { word: 'impair', phonetic: '/ɪmˈpeər/', meaning: 'v. 损害', category: 'GRE词汇' },
  { word: 'impalpable', phonetic: '/ɪmˈpælpəbl/', meaning: 'adj. 难以察觉的', category: 'GRE词汇' },
  { word: 'impartial', phonetic: '/ɪmˈpɑːrʃl/', meaning: 'adj. 公正的', category: 'GRE词汇' },
  { word: 'impassable', phonetic: '/ɪmˈpɑːsəbl/', meaning: 'adj. 不可通行的', category: 'GRE词汇' },
  { word: 'impassioned', phonetic: '/ɪmˈpæʃnd/', meaning: 'adj. 充满激情的', category: 'GRE词汇' },
  { word: 'impassive', phonetic: '/ɪmˈpæsɪv/', meaning: 'adj. 无动于衷的', category: 'GRE词汇' },
  { word: 'impatience', phonetic: '/ɪmˈpeɪʃns/', meaning: 'n. 不耐烦', category: 'GRE词汇' },
  { word: 'impatient', phonetic: '/ɪmˈpeɪʃnt/', meaning: 'adj. 不耐烦的', category: '托福词汇' },
  { word: 'impeach', phonetic: '/ɪmˈpiːtʃ/', meaning: 'v. 弹劾', category: 'GRE词汇' },
  { word: 'impeccable', phonetic: '/ɪmˈpekəbl/', meaning: 'adj. 无瑕疵的', category: 'GRE词汇' },
  { word: 'impecunious', phonetic: '/ˌɪmpɪˈkjuːniəs/', meaning: 'adj. 贫穷的', category: 'GRE词汇' },
  { word: 'impedance', phonetic: '/ɪmˈpiːdns/', meaning: 'n. 阻抗', category: '科技词汇' },
  { word: 'impede', phonetic: '/ɪmˈpiːd/', meaning: 'v. 阻碍', category: 'GRE词汇' },
  { word: 'impediment', phonetic: '/ɪmˈpedɪmənt/', meaning: 'n. 障碍', category: 'GRE词汇' },
  { word: 'impel', phonetic: '/ɪmˈpel/', meaning: 'v. 推动', category: 'GRE词汇' },
  { word: 'impending', phonetic: '/ɪmˈpendɪŋ/', meaning: 'adj. 即将发生的', category: 'GRE词汇' },
  { word: 'impenetrable', phonetic: '/ɪmˈpenɪtrəbl/', meaning: 'adj. 不能穿透的', category: 'GRE词汇' },
  { word: 'imperative', phonetic: '/ɪmˈperətɪv/', meaning: 'adj. 必要的；n. 命令', category: 'GRE词汇' },
  { word: 'imperceptible', phonetic: '/ˌɪmpərˈseptəbl/', meaning: 'adj. 察觉不到的', category: 'GRE词汇' },
  { word: 'imperfect', phonetic: '/ɪmˈpɜːrfɪkt/', meaning: 'adj. 不完美的', category: '托福词汇' },
  { word: 'imperial', phonetic: '/ɪmˈpɪəriəl/', meaning: 'adj. 帝国的', category: '托福词汇' },
  { word: 'imperialism', phonetic: '/ɪmˈpɪəriəlɪzəm/', meaning: 'n. 帝国主义', category: 'GRE词汇' },
  { word: 'imperialist', phonetic: '/ɪmˈpɪəriəlɪst/', meaning: 'n. 帝国主义者', category: 'GRE词汇' },
  { word: 'imperil', phonetic: '/ɪmˈperəl/', meaning: 'v. 危及', category: 'GRE词汇' },
  { word: 'imperious', phonetic: '/ɪmˈpɪəriəs/', meaning: 'adj. 专横的', category: 'GRE词汇' },
  { word: 'imperishable', phonetic: '/ɪmˈperɪʃəbl/', meaning: 'adj. 不朽的', category: 'GRE词汇' },
  { word: 'impersonal', phonetic: '/ɪmˈpɜːrsənl/', meaning: 'adj. 非个人的', category: 'GRE词汇' },
  { word: 'impersonate', phonetic: '/ɪmˈpɜːrsəneɪt/', meaning: 'v. 扮演', category: 'GRE词汇' },
  { word: 'impertinent', phonetic: '/ɪmˈpɜːrtɪnənt/', meaning: 'adj. 不恰当的', category: 'GRE词汇' },
  { word: 'impervious', phonetic: '/ɪmˈpɜːrviəs/', meaning: 'adj. 不受影响的', category: 'GRE词汇' },
  { word: 'impetuous', phonetic: '/ɪmˈpetʃuəs/', meaning: 'adj. 冲动的', category: 'GRE词汇' },
  { word: 'impetus', phonetic: '/ˈɪmpɪtəs/', meaning: 'n. 推动力', category: 'GRE词汇' },
  { word: 'impiety', phonetic: '/ɪmˈpaɪəti/', meaning: 'n. 不敬', category: 'GRE词汇' },
  { word: 'impinge', phonetic: '/ɪmˈpɪndʒ/', meaning: 'v. 影响', category: 'GRE词汇' },
  { word: 'impious', phonetic: '/ˈɪmpiəs/', meaning: 'adj. 不敬的', category: 'GRE词汇' },
  { word: 'implacable', phonetic: '/ɪmˈplækəbl/', meaning: 'adj. 难以平息的', category: 'GRE词汇' },
  { word: 'implant', phonetic: '/ɪmˈplɑːnt/', meaning: 'v. 植入；n. 植入物', category: '医学词汇' },
  { word: 'implement', phonetic: '/ˈɪmplɪmənt/', meaning: 'v. 实施；n. 工具', category: '托福词汇' },
  { word: 'implementation', phonetic: '/ˌɪmplɪmenˈteɪʃn/', meaning: 'n. 实施', category: '托福词汇' },
  { word: 'implicate', phonetic: '/ˈɪmplɪkeɪt/', meaning: 'v. 牵连', category: 'GRE词汇' },
  { word: 'implication', phonetic: '/ˌɪmplɪˈkeɪʃn/', meaning: 'n. 含义；牵连', category: '托福词汇' },
  { word: 'implicit', phonetic: '/ɪmˈplɪsɪt/', meaning: 'adj. 含蓄的', category: 'GRE词汇' },
  { word: 'implore', phonetic: '/ɪmˈplɔːr/', meaning: 'v. 恳求', category: 'GRE词汇' },
  { word: 'imply', phonetic: '/ɪmˈplaɪ/', meaning: 'v. 暗示', category: '托福词汇' },
  { word: 'impolite', phonetic: '/ˌɪmpəˈlaɪt/', meaning: 'adj. 不礼貌的', category: '托福词汇' },
  { word: 'impolitic', phonetic: '/ɪmˈpɒlətɪk/', meaning: 'adj. 不明智的', category: 'GRE词汇' },
  { word: 'important', phonetic: '/ɪmˈpɔːrtnt/', meaning: 'adj. 重要的', category: '托福词汇' },
  { word: 'import', phonetic: '/ɪmˈpɔːrt/', meaning: 'v. 进口；n. 进口', category: '托福词汇' },
  { word: 'importation', phonetic: '/ˌɪmpɔːrˈteɪʃn/', meaning: 'n. 进口', category: '托福词汇' },
  { word: 'importunate', phonetic: '/ɪmˈpɔːrtʃənət/', meaning: 'adj. 纠缠不休的', category: 'GRE词汇' },
  { word: 'importune', phonetic: '/ɪmˈpɔːrtjuːn/', meaning: 'v. 强求', category: 'GRE词汇' },
  { word: 'impose', phonetic: '/ɪmˈpəʊz/', meaning: 'v. 强加', category: '托福词汇' },
  { word: 'imposing', phonetic: '/ɪmˈpəʊzɪŋ/', meaning: 'adj. 壮观的', category: 'GRE词汇' },
  { word: 'imposition', phonetic: '/ˌɪmpəˈzɪʃn/', meaning: 'n. 强加', category: 'GRE词汇' },
  { word: 'impossible', phonetic: '/ɪmˈpɒsəbl/', meaning: 'adj. 不可能的', category: '托福词汇' },
  { word: 'impostor', phonetic: '/ɪmˈpɒstər/', meaning: 'n. 冒名顶替者', category: 'GRE词汇' },
  { word: 'impotent', phonetic: '/ˈɪmpətənt/', meaning: 'adj. 无力的', category: 'GRE词汇' },
  { word: 'impound', phonetic: '/ɪmˈpaʊnd/', meaning: 'v. 扣押', category: 'GRE词汇' },
  { word: 'impoverish', phonetic: '/ɪmˈpɒvərɪʃ/', meaning: 'v. 使贫困', category: 'GRE词汇' },
  { word: 'impractical', phonetic: '/ɪmˈpræktɪkl/', meaning: 'adj. 不切实际的', category: '托福词汇' },
  { word: 'imprecation', phonetic: '/ˌɪmprɪˈkeɪʃn/', meaning: 'n. 诅咒', category: 'GRE词汇' },
  { word: 'impregnable', phonetic: '/ɪmˈpreɡnəbl/', meaning: 'adj. 攻不破的', category: 'GRE词汇' },
  { word: 'impregnate', phonetic: '/ˈɪmpreɡneɪt/', meaning: 'v. 使怀孕；浸渍', category: 'GRE词汇' },
  { word: 'impresario', phonetic: '/ˌɪmpreˈsɑːriəʊ/', meaning: 'n. 演出者', category: 'GRE词汇' },
  { word: 'impress', phonetic: '/ɪmˈpres/', meaning: 'v. 给...留下印象', category: '托福词汇' },
  { word: 'impression', phonetic: '/ɪmˈpreʃn/', meaning: 'n. 印象', category: '托福词汇' },
  { word: 'impressionable', phonetic: '/ɪmˈpreʃənəbl/', meaning: 'adj. 易受影响的', category: 'GRE词汇' },
  { word: 'impressionism', phonetic: '/ɪmˈpreʃənɪzəm/', meaning: 'n. 印象派', category: 'GRE词汇' },
  { word: 'impressionist', phonetic: '/ɪmˈpreʃənɪst/', meaning: 'n. 印象派画家', category: 'GRE词汇' },
  { word: 'impressive', phonetic: '/ɪmˈpresɪv/', meaning: 'adj. 令人印象深刻的', category: '托福词汇' },
  { word: 'imprimatur', phonetic: '/ˌɪmprɪˈmeɪtər/', meaning: 'n. 出版许可', category: 'GRE词汇' },
  { word: 'imprison', phonetic: '/ɪmˈprɪzn/', meaning: 'v. 监禁', category: '托福词汇' },
  { word: 'imprisonment', phonetic: '/ɪmˈprɪznmənt/', meaning: 'n. 监禁', category: '托福词汇' },
  { word: 'improbability', phonetic: '/ɪmˌprɒbəˈbɪləti/', meaning: 'n. 不可能', category: 'GRE词汇' },
  { word: 'improbable', phonetic: '/ɪmˈprɒbəbl/', meaning: 'adj. 不可能的', category: '托福词汇' },
  { word: 'impromptu', phonetic: '/ɪmˈprɒmptjuː/', meaning: 'adj. 即兴的；adv. 即兴地', category: 'GRE词汇' },
  { word: 'improper', phonetic: '/ɪmˈprɒpər/', meaning: 'adj. 不适当的', category: '托福词汇' },
  { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: 'v. 改善', category: '托福词汇' },
  { word: 'improvement', phonetic: '/ɪmˈpruːvmənt/', meaning: 'n. 改善', category: '托福词汇' },
  { word: 'improvident', phonetic: '/ɪmˈprɒvɪdənt/', meaning: 'adj. 不节俭的', category: 'GRE词汇' },
  { word: 'improvise', phonetic: '/ˈɪmprəvaɪz/', meaning: 'v. 即兴创作', category: 'GRE词汇' },
  { word: 'imprudent', phonetic: '/ɪmˈpruːdnt/', meaning: 'adj. 轻率的', category: 'GRE词汇' },
  { word: 'impudence', phonetic: '/ˈɪmpjədəns/', meaning: 'n. 厚颜无耻', category: 'GRE词汇' },
  { word: 'impudent', phonetic: '/ˈɪmpjədənt/', meaning: 'adj. 厚颜无耻的', category: 'GRE词汇' },
  { word: 'impugn', phonetic: '/ɪmˈpjuːn/', meaning: 'v. 质疑', category: 'GRE词汇' },
  { word: 'impulse', phonetic: '/ˈɪmpʌls/', meaning: 'n. 冲动', category: '托福词汇' },
  { word: 'impulsive', phonetic: '/ɪmˈpʌlsɪv/', meaning: 'adj. 冲动的', category: 'GRE词汇' },
  { word: 'impunity', phonetic: '/ɪmˈpjuːnəti/', meaning: 'n. 免罚', category: 'GRE词汇' },
  { word: 'impure', phonetic: '/ɪmˈpjʊər/', meaning: 'adj. 不纯的', category: '托福词汇' },
  { word: 'impurity', phonetic: '/ɪmˈpjʊərəti/', meaning: 'n. 杂质', category: '托福词汇' },
  { word: 'imputation', phonetic: '/ˌɪmpjʊˈteɪʃn/', meaning: 'n. 归咎', category: 'GRE词汇' },
  { word: 'impute', phonetic: '/ɪmˈpjuːt/', meaning: 'v. 归咎于', category: 'GRE词汇' },
  { word: 'inability', phonetic: '/ˌɪnəˈbɪləti/', meaning: 'n. 无能力', category: '托福词汇' },
  { word: 'inaccessible', phonetic: '/ˌɪnækˈsesəbl/', meaning: 'adj. 难以接近的', category: 'GRE词汇' },
  { word: 'inaccurate', phonetic: '/ɪnˈækjərət/', meaning: 'adj. 不准确的', category: '托福词汇' },
  { word: 'inactive', phonetic: '/ɪnˈæktɪv/', meaning: 'adj. 不活跃的', category: '托福词汇' },
  { word: 'inadequacy', phonetic: '/ɪnˈædɪkwəsi/', meaning: 'n. 不足', category: 'GRE词汇' },
  { word: 'inadequate', phonetic: '/ɪnˈædɪkwət/', meaning: 'adj. 不足的', category: '托福词汇' },
  { word: 'inadmissible', phonetic: '/ˌɪnədˈmɪsəbl/', meaning: 'adj. 不可接受的', category: 'GRE词汇' },
  { word: 'inadvertent', phonetic: '/ˌɪnədˈvɜːrtnt/', meaning: 'adj. 疏忽的', category: 'GRE词汇' },
  { word: 'inadvisable', phonetic: '/ˌɪnədˈvaɪzəbl/', meaning: 'adj. 不明智的', category: 'GRE词汇' },
  { word: 'inalienable', phonetic: '/ɪnˈeɪliənəbl/', meaning: 'adj. 不可剥夺的', category: 'GRE词汇' },
  { word: 'inanimate', phonetic: '/ɪnˈænɪmət/', meaning: 'adj. 无生命的', category: 'GRE词汇' },
  { word: 'inanition', phonetic: '/ˌɪnəˈnɪʃn/', meaning: 'n. 空虚', category: 'GRE词汇' },
  { word: 'inanity', phonetic: '/ɪnˈænəti/', meaning: 'n. 愚蠢', category: 'GRE词汇' },
  { word: 'inapplicable', phonetic: '/ɪnəˈplɪkəbl/', meaning: 'adj. 不适用的', category: 'GRE词汇' },
  { word: 'inappropriate', phonetic: '/ˌɪnəˈprəʊpriət/', meaning: 'adj. 不适当的', category: '托福词汇' },
  { word: 'inarticulate', phonetic: '/ˌɪnɑːrˈtɪkjələt/', meaning: 'adj. 口齿不清的', category: 'GRE词汇' },
  { word: 'inattention', phonetic: '/ˌɪnəˈtenʃn/', meaning: 'n. 疏忽', category: 'GRE词汇' },
  { word: 'inaudible', phonetic: '/ɪnˈɔːdəbl/', meaning: 'adj. 听不见的', category: 'GRE词汇' },
  { word: 'inaugural', phonetic: '/ɪˈnɔːɡjərəl/', meaning: 'adj. 就职的', category: 'GRE词汇' },
  { word: 'inaugurate', phonetic: '/ɪˈnɔːɡjəreɪt/', meaning: 'v. 就职', category: 'GRE词汇' },
  { word: 'inauguration', phonetic: '/ɪˌnɔːɡjəˈreɪʃn/', meaning: 'n. 就职典礼', category: 'GRE词汇' },
  { word: 'incantation', phonetic: '/ˌɪnkænˈteɪʃn/', meaning: 'n. 咒语', category: 'GRE词汇' },
  { word: 'incapable', phonetic: '/ɪnˈkeɪpəbl/', meaning: 'adj. 无能力的', category: '托福词汇' },
  { word: 'incapacitate', phonetic: '/ˌɪnkəˈpæsɪteɪt/', meaning: 'v. 使无能力', category: 'GRE词汇' },
  { word: 'incapacity', phonetic: '/ˌɪnkəˈpæsəti/', meaning: 'n. 无能力', category: 'GRE词汇' },
  { word: 'incarcerate', phonetic: '/ɪnˈkɑːrsəreɪt/', meaning: 'v. 监禁', category: 'GRE词汇' },
  { word: 'incarceration', phonetic: '/ɪnˌkɑːrsəˈreɪʃn/', meaning: 'n. 监禁', category: 'GRE词汇' },
  { word: 'incarnate', phonetic: '/ɪnˈkɑːrnət/', meaning: 'v. 化身；adj. 化身的', category: 'GRE词汇' },
  { word: 'incarnation', phonetic: '/ˌɪnkɑːrˈneɪʃn/', meaning: 'n. 化身', category: 'GRE词汇' },
  { word: 'incautious', phonetic: '/ɪnˈkɔːʃəs/', meaning: 'adj. 不谨慎的', category: 'GRE词汇' },
  { word: 'incendiary', phonetic: '/ɪnˈsendiəri/', meaning: 'adj. 纵火的', category: 'GRE词汇' },
  { word: 'incense', phonetic: '/ɪnˈsens/', meaning: 'n. 香；v. 激怒', category: 'GRE词汇' },
  { word: 'incentive', phonetic: '/ɪnˈsentɪv/', meaning: 'n. 激励', category: '托福词汇' },
  { word: 'inception', phonetic: '/ɪnˈsepʃn/', meaning: 'n. 开始', category: 'GRE词汇' },
  { word: 'incest', phonetic: '/ˈɪnsest/', meaning: 'n. 乱伦', category: 'GRE词汇' },
  { word: 'inch', phonetic: '/ɪntʃ/', meaning: 'n. 英寸', category: '托福词汇' },
  { word: 'incidence', phonetic: '/ˈɪnsɪdəns/', meaning: 'n. 发生率', category: 'GRE词汇' },
  { word: 'incident', phonetic: '/ˈɪnsɪdənt/', meaning: 'n. 事件', category: '托福词汇' },
  { word: 'incidental', phonetic: '/ˌɪnsɪˈdentl/', meaning: 'adj. 附带的', category: 'GRE词汇' },
  { word: 'incidentally', phonetic: '/ˌɪnsɪˈdentli/', meaning: 'adv. 顺便地', category: '托福词汇' },
  { word: 'incipient', phonetic: '/ɪnˈsɪpiənt/', meaning: 'adj. 初期的', category: 'GRE词汇' },
  { word: 'incise', phonetic: '/ɪnˈsaɪz/', meaning: 'v. 切入', category: 'GRE词汇' },
  { word: 'incision', phonetic: '/ɪnˈsɪʒn/', meaning: 'n. 切口', category: '医学词汇' },
  { word: 'incisive', phonetic: '/ɪnˈsaɪsɪv/', meaning: 'adj. 敏锐的', category: 'GRE词汇' },
  { word: 'incite', phonetic: '/ɪnˈsaɪt/', meaning: 'v. 煽动', category: 'GRE词汇' },
  { word: 'incitement', phonetic: '/ɪnˈsaɪtmənt/', meaning: 'n. 煽动', category: 'GRE词汇' },
  { word: 'inclination', phonetic: '/ˌɪnklɪˈneɪʃn/', meaning: 'n. 倾向', category: '托福词汇' },
  { word: 'incline', phonetic: '/ɪnˈklaɪn/', meaning: 'v. 倾斜；n. 斜坡', category: '托福词汇' },
  { word: 'inclined', phonetic: '/ɪnˈklaɪnd/', meaning: 'adj. 倾向于...的', category: '托福词汇' },
  { word: 'include', phonetic: '/ɪnˈkluːd/', meaning: 'v. 包括', category: '托福词汇' },
  { word: 'inclusion', phonetic: '/ɪnˈkluːʒn/', meaning: 'n. 包括', category: '托福词汇' },
  { word: 'inclusive', phonetic: '/ɪnˈkluːsɪv/', meaning: 'adj. 包括的', category: '托福词汇' },
  { word: 'incoherent', phonetic: '/ˌɪnkəʊˈhɪərənt/', meaning: 'adj. 不连贯的', category: 'GRE词汇' },
  { word: 'incommunicado', phonetic: '/ˌɪnkəmjuːnɪˈkɑːdəʊ/', meaning: 'adj. 禁止与外界接触的', category: 'GRE词汇' },
  { word: 'incomparable', phonetic: '/ɪnˈkɒmpərəbl/', meaning: 'adj. 无比的', category: 'GRE词汇' },
  { word: 'incompatible', phonetic: '/ˌɪnkəmˈpætəbl/', meaning: 'adj. 不兼容的', category: '托福词汇' },
  { word: 'incompetence', phonetic: '/ɪnˈkɒmpɪtəns/', meaning: 'n. 无能力', category: 'GRE词汇' },
  { word: 'incompetent', phonetic: '/ɪnˈkɒmpɪtənt/', meaning: 'adj. 无能力的', category: '托福词汇' },
  { word: 'incomplete', phonetic: '/ˌɪnkəmˈpliːt/', meaning: 'adj. 不完整的', category: '托福词汇' },
  { word: 'incomprehensible', phonetic: '/ɪnˌkɒmprɪˈhensəbl/', meaning: 'adj. 难以理解的', category: 'GRE词汇' },
  { word: 'incompressible', phonetic: '/ˌɪnkəmˈpresəbl/', meaning: 'adj. 不可压缩的', category: '科技词汇' },
  { word: 'inconceivable', phonetic: '/ˌɪnkənˈsiːvəbl/', meaning: 'adj. 不可思议的', category: 'GRE词汇' },
  { word: 'inconclusive', phonetic: '/ɪnˈkɒnkluːsɪv/', meaning: 'adj. 非决定性的', category: 'GRE词汇' },
  { word: 'incongruity', phonetic: '/ˌɪnkɒŋˈɡruːəti/', meaning: 'n. 不协调', category: 'GRE词汇' },
  { word: 'incongruous', phonetic: '/ɪnˈkɒŋɡruəs/', meaning: 'adj. 不协调的', category: 'GRE词汇' },
  { word: 'inconsequential', phonetic: '/ɪnˌkɒnsɪˈkwenʃl/', meaning: 'adj. 不重要的', category: 'GRE词汇' },
  { word: 'inconsiderable', phonetic: '/ˌɪnkənˈsɪdərəbl/', meaning: 'adj. 不足取的', category: 'GRE词汇' },
  { word: 'inconsiderate', phonetic: '/ˌɪnkənˈsɪdərət/', meaning: 'adj. 不体贴的', category: '托福词汇' },
  { word: 'inconsistency', phonetic: '/ˌɪnkənˈsɪstənsi/', meaning: 'n. 不一致', category: 'GRE词汇' },
  { word: 'inconsistent', phonetic: '/ˌɪnkənˈsɪstənt/', meaning: 'adj. 不一致的', category: '托福词汇' },
  { word: 'inconspicuous', phonetic: '/ˌɪnkənˈspɪkjuəs/', meaning: 'adj. 不显眼的', category: 'GRE词汇' },
  { word: 'inconstant', phonetic: '/ɪnˈkɒnstənt/', meaning: 'adj. 多变的', category: 'GRE词汇' },
  { word: 'inconsumable', phonetic: '/ˌɪnkənˈsuːməbl/', meaning: 'adj. 不可消耗的', category: 'GRE词汇' },
  { word: 'incontrollable', phonetic: '/ˌɪnkənˈtrəʊləbl/', meaning: 'adj. 无法控制的', category: 'GRE词汇' },
  { word: 'incontrovertible', phonetic: '/ˌɪnkɒntrəˈvɜːrtəbl/', meaning: 'adj. 无可争辩的', category: 'GRE词汇' },
  { word: 'inconvenient', phonetic: '/ˌɪnkənˈviːniənt/', meaning: 'adj. 不方便的', category: '托福词汇' },
  { word: 'incorporate', phonetic: '/ɪnˈkɔːrpəreɪt/', meaning: 'v. 包含；合并', category: '托福词汇' },
  { word: 'incorporation', phonetic: '/ɪnˌkɔːrpəˈreɪʃn/', meaning: 'n. 合并', category: 'GRE词汇' },
  { word: 'incorrect', phonetic: '/ˌɪnkəˈrekt/', meaning: 'adj. 错误的', category: '托福词汇' },
  { word: 'incorrigible', phonetic: '/ɪnˈkɒrɪdʒəbl/', meaning: 'adj. 不可救药的', category: 'GRE词汇' },
  { word: 'incorruptible', phonetic: '/ˌɪnkəˈrʌptəbl/', meaning: 'adj. 廉洁的', category: 'GRE词汇' },
  { word: 'increase', phonetic: '/ɪnˈkriːs/', meaning: 'v. 增加；n. 增加', category: '托福词汇' },
  { word: 'increasingly', phonetic: '/ɪnˈkriːsɪŋli/', meaning: 'adv. 越来越', category: '托福词汇' },
  { word: 'incredible', phonetic: '/ɪnˈkredəbl/', meaning: 'adj. 难以置信的', category: '托福词汇' },
  { word: 'incredulous', phonetic: '/ɪnˈkredʒələs/', meaning: 'adj. 怀疑的', category: 'GRE词汇' },
  { word: 'increment', phonetic: '/ˈɪŋkrəmənt/', meaning: 'n. 增量', category: 'GRE词汇' },
  { word: 'incremental', phonetic: '/ˌɪŋkrəˈmentl/', meaning: 'adj. 增量的', category: 'GRE词汇' },
  { word: 'incriminate', phonetic: '/ɪnˈkrɪmɪneɪt/', meaning: 'v. 牵连', category: 'GRE词汇' },
  { word: 'incrustation', phonetic: '/ˌɪnkrʌˈsteɪʃn/', meaning: 'n. 结壳', category: 'GRE词汇' },
  { word: 'incubate', phonetic: '/ˈɪŋkjʊbeɪt/', meaning: 'v. 孵化', category: 'GRE词汇' },
  { word: 'incubation', phonetic: '/ˌɪŋkjʊˈbeɪʃn/', meaning: 'n. 孵化', category: 'GRE词汇' },
  { word: 'incubator', phonetic: '/ˈɪŋkjʊbeɪtər/', meaning: 'n. 孵化器', category: 'GRE词汇' },
  { word: 'inculpate', phonetic: '/ˈɪnkʌlpeɪt/', meaning: 'v. 牵连', category: 'GRE词汇' },
  { word: 'incumbent', phonetic: '/ɪnˈkʌmbənt/', meaning: 'adj. 现任的；n. 现任者', category: 'GRE词汇' },
  { word: 'incur', phonetic: '/ɪnˈkɜːr/', meaning: 'v. 招致', category: 'GRE词汇' },
  { word: 'incurable', phonetic: '/ɪnˈkjʊərəbl/', meaning: 'adj. 无法治愈的', category: '医学词汇' },
  { word: 'indebted', phonetic: '/ɪnˈdetɪd/', meaning: 'adj. 负债的', category: 'GRE词汇' },
  { word: 'indecent', phonetic: '/ɪnˈdiːsnt/', meaning: 'adj. 不体面的', category: 'GRE词汇' },
  { word: 'indecision', phonetic: '/ɪndɪˈsɪʒn/', meaning: 'n. 优柔寡断', category: 'GRE词汇' },
  { word: 'indecisive', phonetic: '/ˌɪndɪˈsaɪsɪv/', meaning: 'adj. 优柔寡断的', category: 'GRE词汇' },
  { word: 'indeed', phonetic: '/ɪnˈdiːd/', meaning: 'adv. 确实', category: '托福词汇' },
  { word: 'indefatigable', phonetic: '/ˌɪndɪˈfætɪɡəbl/', meaning: 'adj. 不知疲倦的', category: 'GRE词汇' },
  { word: 'indefensible', phonetic: '/ˌɪndɪˈfensəbl/', meaning: 'adj. 无法辩护的', category: 'GRE词汇' },
  { word: 'indefinite', phonetic: '/ɪnˈdefɪnət/', meaning: 'adj. 不确定的', category: '托福词汇' },
  { word: 'indefinitely', phonetic: '/ɪnˈdefɪnətli/', meaning: 'adv. 不确定地', category: '托福词汇' },
  { word: 'indelible', phonetic: '/ɪnˈdeləbl/', meaning: 'adj. 不可磨灭的', category: 'GRE词汇' },
  { word: 'indelicate', phonetic: '/ɪnˈdelɪkət/', meaning: 'adj. 不得体的', category: 'GRE词汇' },
  { word: 'independence', phonetic: '/ˌɪndɪˈpendəns/', meaning: 'n. 独立', category: '托福词汇' },
  { word: 'independent', phonetic: '/ˌɪndɪˈpendənt/', meaning: 'adj. 独立的', category: '托福词汇' },
  { word: 'indescribable', phonetic: '/ˌɪndɪˈskraɪbəbl/', meaning: 'adj. 难以描述的', category: 'GRE词汇' },
  { word: 'indestructible', phonetic: '/ˌɪndɪˈstrʌktəbl/', meaning: 'adj. 不可毁灭的', category: 'GRE词汇' },
  { word: 'indeterminate', phonetic: '/ˌɪndɪˈtɜːrmɪnət/', meaning: 'adj. 不确定的', category: 'GRE词汇' },
  { word: 'index', phonetic: '/ˈɪndeks/', meaning: 'n. 索引；v. 编索引', category: '托福词汇' },
  { word: 'indian', phonetic: '/ˈɪndiən/', meaning: 'n. 印度人；adj. 印度的', category: '托福词汇' },
  { word: 'indicate', phonetic: '/ˈɪndɪkeɪt/', meaning: 'v. 指出；表明', category: '托福词汇' },
  { word: 'indication', phonetic: '/ˌɪndɪˈkeɪʃn/', meaning: 'n. 指示', category: '托福词汇' },
  { word: 'indicative', phonetic: '/ɪnˈdɪkətɪv/', meaning: 'adj. 指示的', category: 'GRE词汇' },
  { word: 'indicator', phonetic: '/ˈɪndɪkeɪtər/', meaning: 'n. 指示器', category: '托福词汇' },
  { word: 'indict', phonetic: '/ɪnˈdaɪt/', meaning: 'v. 控告', category: 'GRE词汇' },
  { word: 'indictment', phonetic: '/ɪnˈdaɪtmənt/', meaning: 'n. 控告', category: 'GRE词汇' },
  { word: 'indifferent', phonetic: '/ɪnˈdɪfrənt/', meaning: 'adj. 冷漠的', category: '托福词汇' },
  { word: 'indigenous', phonetic: '/ɪnˈdɪdʒənəs/', meaning: 'adj. 本土的', category: 'GRE词汇' },
  { word: 'indigent', phonetic: '/ˈɪndɪdʒənt/', meaning: 'adj. 贫困的', category: 'GRE词汇' },
  { word: 'indignant', phonetic: '/ɪnˈdɪɡnənt/', meaning: 'adj. 愤慨的', category: 'GRE词汇' },
  { word: 'indignation', phonetic: '/ˌɪndɪɡˈneɪʃn/', meaning: 'n. 愤慨', category: 'GRE词汇' },
  { word: 'indignity', phonetic: '/ɪnˈdɪɡnəti/', meaning: 'n. 侮辱', category: 'GRE词汇' },
  { word: 'indirect', phonetic: '/ˌɪndəˈrekt/', meaning: 'adj. 间接的', category: '托福词汇' },
  { word: 'indiscernible', phonetic: '/ˌɪndɪˈsɜːrnəbl/', meaning: 'adj. 难识别的', category: 'GRE词汇' },
  { word: 'indiscreet', phonetic: '/ˌɪndɪˈskriːt/', meaning: 'adj. 不谨慎的', category: 'GRE词汇' },
  { word: 'indiscretion', phonetic: '/ˌɪndɪˈskreʃn/', meaning: 'n. 不谨慎', category: 'GRE词汇' },
  { word: 'indispensable', phonetic: '/ˌɪndɪˈspensəbl/', meaning: 'adj. 不可缺少的', category: '托福词汇' },
  { word: 'indisputable', phonetic: '/ˌɪndɪˈspjuːtəbl/', meaning: 'adj. 无可争辩的', category: 'GRE词汇' },
  { word: 'indissoluble', phonetic: '/ˌɪndɪˈsɒljəbl/', meaning: 'adj. 不可溶解的', category: 'GRE词汇' },
  { word: 'indistinct', phonetic: '/ˌɪndɪˈstɪŋkt/', meaning: 'adj. 模糊的', category: 'GRE词汇' },
  { word: 'indistinguishable', phonetic: '/ˌɪndɪˈstɪŋɡwɪʃəbl/', meaning: 'adj. 难区分的', category: 'GRE词汇' },
  { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning: 'n. 个人；adj. 个人的', category: '托福词汇' },
  { word: 'individualism', phonetic: '/ˌɪndɪˈvɪdʒuəlɪzəm/', meaning: 'n. 个人主义', category: 'GRE词汇' },
  { word: 'individuality', phonetic: '/ˌɪndɪvɪdʒuˈæləti/', meaning: 'n. 个性', category: 'GRE词汇' },
  { word: 'individualize', phonetic: '/ˌɪndɪˈvɪdʒuəlaɪz/', meaning: 'v. 个性化', category: 'GRE词汇' },
  { word: 'indivisible', phonetic: '/ˌɪndɪˈvɪzəbl/', meaning: 'adj. 不可分割的', category: 'GRE词汇' },
  { word: 'indocile', phonetic: '/ɪnˈdəʊsaɪl/', meaning: 'adj. 难驯服的', category: 'GRE词汇' },
  { word: 'indoctrinate', phonetic: '/ɪnˈdɒktrɪneɪt/', meaning: 'v. 灌输', category: 'GRE词汇' },
  { word: 'indolent', phonetic: '/ˈɪndələnt/', meaning: 'adj. 懒惰的', category: 'GRE词汇' },
  { word: 'indomitable', phonetic: '/ɪnˈdɒmɪtəbl/', meaning: 'adj. 不屈不挠的', category: 'GRE词汇' },
  { word: 'indoor', phonetic: '/ˈɪndɔːr/', meaning: 'adj. 室内的', category: '托福词汇' },
  { word: 'indoors', phonetic: '/ɪnˈdɔːrz/', meaning: 'adv. 在室内', category: '托福词汇' },
  { word: 'induce', phonetic: '/ɪnˈdjuːs/', meaning: 'v. 诱导', category: 'GRE词汇' },
  { word: 'inducement', phonetic: '/ɪnˈdjuːsmənt/', meaning: 'n. 诱因', category: 'GRE词汇' },
  { word: 'induct', phonetic: '/ɪnˈdʌkt/', meaning: 'v. 使就职', category: 'GRE词汇' },
  { word: 'induction', phonetic: '/ɪnˈdʌkʃn/', meaning: 'n. 就职；归纳', category: 'GRE词汇' },
  { word: 'indulge', phonetic: '/ɪnˈdʌldʒ/', meaning: 'v. 放纵', category: 'GRE词汇' },
  { word: 'indulgence', phonetic: '/ɪnˈdʌldʒəns/', meaning: 'n. 放纵', category: 'GRE词汇' },
  { word: 'indulgent', phonetic: '/ɪnˈdʌldʒənt/', meaning: 'adj. 放纵的', category: 'GRE词汇' },
  { word: 'industrial', phonetic: '/ɪnˈdʌstriəl/', meaning: 'adj. 工业的', category: '托福词汇' },
  { word: 'industrialize', phonetic: '/ɪnˈdʌstriəlaɪz/', meaning: 'v. 工业化', category: '托福词汇' },
  { word: 'industrious', phonetic: '/ɪnˈdʌstriəs/', meaning: 'adj. 勤奋的', category: 'GRE词汇' },
  { word: 'industry', phonetic: '/ˈɪndəstri/', meaning: 'n. 工业；勤奋', category: '托福词汇' },
  { word: 'ineffective', phonetic: '/ˌɪnɪˈfektɪv/', meaning: 'adj. 无效的', category: '托福词汇' },
  { word: 'inefficient', phonetic: '/ˌɪnɪˈfɪʃnt/', meaning: 'adj. 效率低的', category: '托福词汇' },
  { word: 'inelegance', phonetic: '/ɪnˈelɪɡəns/', meaning: 'n. 不优雅', category: 'GRE词汇' },
  { word: 'inelegant', phonetic: '/ɪnˈelɪɡənt/', meaning: 'adj. 不优雅的', category: 'GRE词汇' },
  { word: 'ineligible', phonetic: '/ɪnˈelɪdʒəbl/', meaning: 'adj. 无资格的', category: 'GRE词汇' },
  { word: 'ineluctable', phonetic: '/ˌɪnɪˈlʌktəbl/', meaning: 'adj. 不可避免的', category: 'GRE词汇' },
  { word: 'inept', phonetic: '/ɪˈnept/', meaning: 'adj. 无能的', category: 'GRE词汇' },
  { word: 'inequality', phonetic: '/ˌɪnɪˈkwɒləti/', meaning: 'n. 不平等', category: 'GRE词汇' },
  { word: 'inequity', phonetic: '/ɪnˈekwəti/', meaning: 'n. 不公平', category: 'GRE词汇' },
  { word: 'inescapable', phonetic: '/ˌɪnɪˈskeɪpəbl/', meaning: 'adj. 不可避免的', category: 'GRE词汇' },
  { word: 'inessential', phonetic: '/ˌɪnɪˈsenʃl/', meaning: 'adj. 非必要的', category: 'GRE词汇' },
  { word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', meaning: 'adj. 不可避免的', category: '托福词汇' },
  { word: 'inevitably', phonetic: '/ɪnˈevɪtəbli/', meaning: 'adv. 不可避免地', category: '托福词汇' },
  { word: 'inexorable', phonetic: '/ɪnˈeksərəbl/', meaning: 'adj. 不可阻挡的', category: 'GRE词汇' },
  { word: 'inexperience', phonetic: '/ˌɪnɪkˈspɪəriəns/', meaning: 'n. 缺乏经验', category: '托福词汇' },
  { word: 'inexperienced', phonetic: '/ˌɪnɪkˈspɪəriənst/', meaning: 'adj. 缺乏经验的', category: '托福词汇' },
  { word: 'inexpensive', phonetic: '/ˌɪnɪkˈspensɪv/', meaning: 'adj. 便宜的', category: '托福词汇' },
  { word: 'inexplicable', phonetic: '/ˌɪnɪkˈsplɪkəbl/', meaning: 'adj. 无法解释的', category: 'GRE词汇' },
  { word: 'inexplicable', phonetic: '/ɪnˈeksplɪkəbl/', meaning: 'adj. 费解的', category: 'GRE词汇' },
  { word: 'infallible', phonetic: '/ɪnˈfæləbl/', meaning: 'adj. 绝对可靠的', category: 'GRE词汇' },
  { word: 'infamous', phonetic: '/ˈɪnfəməs/', meaning: 'adj. 声名狼藉的', category: 'GRE词汇' },
  { word: 'infamy', phonetic: '/ˈɪnfəmi/', meaning: 'n. 声名狼藉', category: 'GRE词汇' },
  { word: 'infant', phonetic: '/ˈɪnfənt/', meaning: 'n. 婴儿', category: '托福词汇' },
  { word: 'infantile', phonetic: '/ˈɪnfəntaɪl/', meaning: 'adj. 婴儿的', category: 'GRE词汇' },
  { word: 'infantry', phonetic: '/ˈɪnfəntri/', meaning: 'n. 步兵', category: 'GRE词汇' },
  { word: 'infatuate', phonetic: '/ɪnˈfætʃueɪt/', meaning: 'v. 使迷恋', category: 'GRE词汇' },
  { word: 'infatuation', phonetic: '/ɪnˌfætʃuˈeɪʃn/', meaning: 'n. 迷恋', category: 'GRE词汇' },
  { word: 'infect', phonetic: '/ɪnˈfekt/', meaning: 'v. 感染', category: '托福词汇' },
  { word: 'infection', phonetic: '/ɪnˈfekʃn/', meaning: 'n. 感染', category: '托福词汇' },
  { word: 'infectious', phonetic: '/ɪnˈfekʃəs/', meaning: 'adj. 传染的', category: '托福词汇' },
  { word: 'infer', phonetic: '/ɪnˈfɜːr/', meaning: 'v. 推断', category: 'GRE词汇' },
  { word: 'inference', phonetic: '/ˈɪnfərəns/', meaning: 'n. 推断', category: 'GRE词汇' },
  { word: 'inferential', phonetic: '/ˌɪnfəˈrenʃl/', meaning: 'adj. 推论的', category: 'GRE词汇' },
  { word: 'inferior', phonetic: '/ɪnˈfɪəriər/', meaning: 'adj. 较差的；n. 下级', category: '托福词汇' },
  { word: 'inferiority', phonetic: '/ɪnˌfɪəriˈɒrəti/', meaning: 'n. 劣等', category: 'GRE词汇' },
  { word: 'infernal', phonetic: '/ɪnˈfɜːrnl/', meaning: 'adj. 地狱的', category: 'GRE词汇' },
  { word: 'infest', phonetic: '/ɪnˈfest/', meaning: 'v. 骚扰', category: 'GRE词汇' },
  { word: 'infidel', phonetic: '/ˈɪnfɪdəl/', meaning: 'n. 无信仰者', category: 'GRE词汇' },
  { word: 'infidelity', phonetic: '/ˌɪnfɪˈdeləti/', meaning: 'n. 不忠', category: 'GRE词汇' },
  { word: 'infield', phonetic: '/ˈɪnfiːld/', meaning: 'n. 内场', category: 'GRE词汇' },
  { word: 'infiltrate', phonetic: '/ˈɪnfɪltreɪt/', meaning: 'v. 渗透', category: 'GRE词汇' },
  { word: 'infiltration', phonetic: '/ˌɪnfɪlˈtreɪʃn/', meaning: 'n. 渗透', category: 'GRE词汇' },
  { word: 'infinite', phonetic: '/ˈɪnfɪnət/', meaning: 'adj. 无限的', category: '托福词汇' },
  { word: 'infinitely', phonetic: '/ˈɪnfɪnətli/', meaning: 'adv. 无限地', category: '托福词汇' },
  { word: 'infinity', phonetic: '/ɪnˈfɪnəti/', meaning: 'n. 无限', category: 'GRE词汇' },
  { word: 'infinitesimal', phonetic: '/ˌɪnfɪnɪˈtesɪml/', meaning: 'adj. 无限小的', category: 'GRE词汇' },
  { word: 'infinitive', phonetic: '/ɪnˈfɪnɪtɪv/', meaning: 'n. 不定式；adj. 不定式的', category: 'GRE词汇' },
  { word: 'infirm', phonetic: '/ɪnˈfɜːrm/', meaning: 'adj. 虚弱的', category: 'GRE词汇' },
  { word: 'infirmary', phonetic: '/ɪnˈfɜːrməri/', meaning: 'n. 医务室', category: 'GRE词汇' },
  { word: 'infirmity', phonetic: '/ɪnˈfɜːrməti/', meaning: 'n. 虚弱', category: 'GRE词汇' },
  { word: 'inflame', phonetic: '/ɪnˈfleɪm/', meaning: 'v. 使燃烧；激怒', category: 'GRE词汇' },
  { word: 'inflammable', phonetic: '/ɪnˈflæməbl/', meaning: 'adj. 易燃的', category: 'GRE词汇' },
  { word: 'inflammation', phonetic: '/ˌɪnfləˈmeɪʃn/', meaning: 'n. 炎症', category: '医学词汇' },
  { word: 'inflate', phonetic: '/ɪnˈfleɪt/', meaning: 'v. 充气；膨胀', category: '托福词汇' },
  { word: 'inflation', phonetic: '/ɪnˈfleɪʃn/', meaning: 'n. 通货膨胀', category: '托福词汇' },
  { word: 'inflect', phonetic: '/ɪnˈflekt/', meaning: 'v. 弯曲；变化', category: 'GRE词汇' },
  { word: 'inflection', phonetic: '/ɪnˈflekʃn/', meaning: 'n. 弯曲；变调', category: 'GRE词汇' },
  { word: 'inflict', phonetic: '/ɪnˈflɪkt/', meaning: 'v. 施加', category: 'GRE词汇' },
  { word: 'influence', phonetic: '/ˈɪnfluəns/', meaning: 'n. 影响；v. 影响', category: '托福词汇' },
  { word: 'influential', phonetic: '/ˌɪnfluˈenʃl/', meaning: 'adj. 有影响力的', category: '托福词汇' },
  { word: 'influx', phonetic: '/ˈɪnflʌks/', meaning: 'n. 流入', category: 'GRE词汇' },
  { word: 'inform', phonetic: '/ɪnˈfɔːrm/', meaning: 'v. 通知', category: '托福词汇' },
  { word: 'information', phonetic: '/ˌɪnfərˈmeɪʃn/', meaning: 'n. 信息', category: '托福词汇' },
  { word: 'informative', phonetic: '/ɪnˈfɔːrmətɪv/', meaning: 'adj. 信息丰富的', category: '托福词汇' },
  { word: 'informed', phonetic: '/ɪnˈfɔːrmd/', meaning: 'adj. 见多识广的', category: '托福词汇' },
  { word: 'informer', phonetic: '/ɪnˈfɔːrmər/', meaning: 'n. 告密者', category: 'GRE词汇' },
  { word: 'infra', phonetic: '/ˈɪnfrə/', meaning: 'pref. 在下面', category: 'GRE词汇' },
  { word: 'infraction', phonetic: '/ɪnˈfrækʃn/', meaning: 'n. 违反', category: 'GRE词汇' },
  { word: 'infrastructure', phonetic: '/ˈɪnfrəstrʌktʃər/', meaning: 'n. 基础设施', category: '托福词汇' },
  { word: 'infrequent', phonetic: '/ɪnˈfriːkwənt/', meaning: 'adj. 罕见的', category: 'GRE词汇' },
  { word: 'infringe', phonetic: '/ɪnˈfrɪndʒ/', meaning: 'v. 侵犯', category: 'GRE词汇' },
  { word: 'infringement', phonetic: '/ɪnˈfrɪndʒmənt/', meaning: 'n. 侵犯', category: 'GRE词汇' },
  { word: 'infuriate', phonetic: '/ɪnˈfjʊəriət/', meaning: 'v. 激怒', category: 'GRE词汇' },
  { word: 'infuse', phonetic: '/ɪnˈfjuːz/', meaning: 'v. 注入', category: 'GRE词汇' },
  { word: 'infusion', phonetic: '/ɪnˈfjuːʒn/', meaning: 'n. 注入', category: 'GRE词汇' },
  { word: 'ingenious', phonetic: '/ɪnˈdʒiːniəs/', meaning: 'adj. 足智多谋的', category: 'GRE词汇' },
  { word: 'ingenuity', phonetic: '/ˌɪndʒəˈnjuːəti/', meaning: 'n. 独创性', category: 'GRE词汇' },
  { word: 'ingenuous', phonetic: '/ɪnˈdʒenjuəs/', meaning: 'adj. 天真的', category: 'GRE词汇' },
  { word: 'inglorious', phonetic: '/ɪnˈɡlɔːriəs/', meaning: 'adj. 可耻的', category: 'GRE词汇' },
  { word: 'ingot', phonetic: '/ˈɪŋɡət/', meaning: 'n. 锭', category: 'GRE词汇' },
  { word: 'ingrained', phonetic: '/ɪnˈɡreɪnd/', meaning: 'adj. 根深蒂固的', category: 'GRE词汇' },
  { word: 'ingrate', phonetic: '/ˈɪŋɡreɪt/', meaning: 'n. 忘恩负义者', category: 'GRE词汇' },
  { word: 'ingratitude', phonetic: '/ɪnˈɡrætɪtjuːd/', meaning: 'n. 忘恩负义', category: 'GRE词汇' },
  { word: 'ingredient', phonetic: '/ɪnˈɡriːdiənt/', meaning: 'n. 原料', category: '托福词汇' },
  { word: 'inhabit', phonetic: '/ɪnˈhæbɪt/', meaning: 'v. 居住', category: '托福词汇' },
  { word: 'inhabitant', phonetic: '/ɪnˈhæbɪtənt/', meaning: 'n. 居民', category: '托福词汇' },
  { word: 'inhale', phonetic: '/ɪnˈheɪl/', meaning: 'v. 吸入', category: '托福词汇' },
  { word: 'inherent', phonetic: '/ɪnˈhɪərənt/', meaning: 'adj. 内在的', category: 'GRE词汇' },
  { word: 'inherence', phonetic: '/ɪnˈhɪərəns/', meaning: 'n. 内在', category: 'GRE词汇' },
  { word: 'inherit', phonetic: '/ɪnˈherɪt/', meaning: 'v. 继承', category: '托福词汇' },
  { word: 'inheritance', phonetic: '/ɪnˈherɪtəns/', meaning: 'n. 继承', category: '托福词汇' },
  { word: 'inhibit', phonetic: '/ɪnˈhɪbɪt/', meaning: 'v. 抑制', category: 'GRE词汇' },
  { word: 'inhibition', phonetic: '/ˌɪnɪˈbɪʃn/', meaning: 'n. 抑制', category: 'GRE词汇' },
  { word: 'inhospitable', phonetic: '/ˌɪnhɒˈspɪtəbl/', meaning: 'adj. 不好客的', category: 'GRE词汇' },
  { word: 'inhuman', phonetic: '/ɪnˈhjuːmən/', meaning: 'adj. 不人道的', category: 'GRE词汇' },
  { word: 'inhumane', phonetic: '/ˌɪnhjuːˈmeɪn/', meaning: 'adj. 不人道的', category: 'GRE词汇' },
  { word: 'inhumanity', phonetic: '/ˌɪnhjuːˈmænəti/', meaning: 'n. 不人道', category: 'GRE词汇' },
  { word: 'inhume', phonetic: '/ɪnˈhjuːm/', meaning: 'v. 埋葬', category: 'GRE词汇' },
  { word: 'initial', phonetic: '/ɪˈnɪʃl/', meaning: 'adj. 最初的；n. 首字母', category: '托福词汇' },
  { word: 'initially', phonetic: '/ɪˈnɪʃəli/', meaning: 'adv. 最初', category: '托福词汇' },
  { word: 'initiate', phonetic: '/ɪˈnɪʃieɪt/', meaning: 'v. 开始；n. 新加入者', category: 'GRE词汇' },
  { word: 'initiation', phonetic: '/ɪˌnɪʃiˈeɪʃn/', meaning: 'n. 开始', category: 'GRE词汇' },
  { word: 'initiative', phonetic: '/ɪˈnɪʃətɪv/', meaning: 'n. 主动性；adj. 主动的', category: '托福词汇' },
  { word: 'inject', phonetic: '/ɪnˈdʒekt/', meaning: 'v. 注射', category: '托福词汇' },
  { word: 'injection', phonetic: '/ɪnˈdʒekʃn/', meaning: 'n. 注射', category: '托福词汇' },
  { word: 'injudicious', phonetic: '/ˌɪndʒuˈdɪʃəs/', meaning: 'adj. 不明智的', category: 'GRE词汇' },
  { word: 'injure', phonetic: '/ˈɪndʒər/', meaning: 'v. 伤害', category: '托福词汇' },
  { word: 'injurious', phonetic: '/ɪnˈdʒʊəriəs/', meaning: 'adj. 有害的', category: 'GRE词汇' },
  { word: 'injury', phonetic: '/ˈɪndʒəri/', meaning: 'n. 伤害', category: '托福词汇' },
  { word: 'injustice', phonetic: '/ɪnˈdʒʌstɪs/', meaning: 'n. 不公正', category: 'GRE词汇' },
  { word: 'ink', phonetic: '/ɪŋk/', meaning: 'n. 墨水', category: '托福词汇' },
  { word: 'inkling', phonetic: '/ˈɪŋklɪŋ/', meaning: 'n. 暗示', category: 'GRE词汇' },
  { word: 'inland', phonetic: '/ˈɪnlənd/', meaning: 'adj. 内陆的；adv. 在内陆', category: '托福词汇' },
  { word: 'inlay', phonetic: '/ɪnˈleɪ/', meaning: 'v. 镶嵌；n. 镶嵌物', category: 'GRE词汇' },
  { word: 'inlet', phonetic: '/ˈɪnlet/', meaning: 'n. 入口', category: 'GRE词汇' },
  { word: 'inmate', phonetic: '/ˈɪnmeɪt/', meaning: 'n. 囚犯', category: 'GRE词汇' },
  { word: 'inn', phonetic: '/ɪn/', meaning: 'n. 客栈', category: '托福词汇' },
  { word: 'innate', phonetic: '/ɪˈneɪt/', meaning: 'adj. 天生的', category: 'GRE词汇' },
  { word: 'inner', phonetic: '/ˈɪnər/', meaning: 'adj. 内部的', category: '托福词汇' },
  { word: 'innermost', phonetic: '/ˈɪnərməʊst/', meaning: 'adj. 最里面的', category: 'GRE词汇' },
  { word: 'innocence', phonetic: '/ˈɪnəsns/', meaning: 'n. 无辜', category: '托福词汇' },
  { word: 'innocent', phonetic: '/ˈɪnəsnt/', meaning: 'adj. 无辜的', category: '托福词汇' },
  { word: 'innocuous', phonetic: '/ɪˈnɒkjuəs/', meaning: 'adj. 无害的', category: 'GRE词汇' },
  { word: 'innovation', phonetic: '/ˌɪnəˈveɪʃn/', meaning: 'n. 创新', category: '托福词汇' },
  { word: 'innovative', phonetic: '/ˈɪnəveɪtɪv/', meaning: 'adj. 创新的', category: '托福词汇' },
  { word: 'innovator', phonetic: '/ˈɪnəveɪtər/', meaning: 'n. 创新者', category: 'GRE词汇' },
  { word: 'innuendo', phonetic: '/ˌɪnjuˈendəʊ/', meaning: 'n. 暗示', category: 'GRE词汇' },
  { word: 'innumerable', phonetic: '/ɪˈnjuːmərəbl/', meaning: 'adj. 无数的', category: 'GRE词汇' },
  { word: 'inoculate', phonetic: '/ɪˈnɒkjʊleɪt/', meaning: 'v. 接种', category: '医学词汇' },
  { word: 'inoculation', phonetic: '/ɪˌnɒkjʊˈleɪʃn/', meaning: 'n. 接种', category: '医学词汇' },
  { word: 'inoffensive', phonetic: '/ˌɪnəˈfensɪv/', meaning: 'adj. 无害的', category: 'GRE词汇' },
  { word: 'inquest', phonetic: '/ˈɪŋkwest/', meaning: 'n. 调查', category: 'GRE词汇' },
  { word: 'inquire', phonetic: '/ɪnˈkwaɪər/', meaning: 'v. 询问', category: '托福词汇' },
  { word: 'inquiry', phonetic: '/ɪnˈkwaɪəri/', meaning: 'n. 询问', category: '托福词汇' },
  { word: 'inquisitive', phonetic: '/ɪnˈkwɪzətɪv/', meaning: 'adj. 好奇的', category: 'GRE词汇' },
  { word: 'inquisition', phonetic: '/ˌɪnkwɪˈzɪʃn/', meaning: 'n. 调查', category: 'GRE词汇' },
  { word: 'inquisitor', phonetic: '/ɪnˈkwɪzɪtər/', meaning: 'n. 审问者', category: 'GRE词汇' },
  { word: 'insane', phonetic: '/ɪnˈseɪn/', meaning: 'adj. 疯狂的', category: '托福词汇' },
  { word: 'insanity', phonetic: '/ɪnˈsænəti/', meaning: 'n. 精神错乱', category: 'GRE词汇' },
  { word: 'insatiable', phonetic: '/ɪnˈseɪʃəbl/', meaning: 'adj. 不知足的', category: 'GRE词汇' },
  { word: 'inscribe', phonetic: '/ɪnˈskraɪb/', meaning: 'v. 刻写', category: 'GRE词汇' },
  { word: 'inscription', phonetic: '/ɪnˈskrɪpʃn/', meaning: 'n. 铭文', category: 'GRE词汇' },
  { word: 'inscrutable', phonetic: '/ɪnˈskruːtəbl/', meaning: 'adj. 难以捉摸的', category: 'GRE词汇' },
  { word: 'insect', phonetic: '/ˈɪnsekt/', meaning: 'n. 昆虫', category: '托福词汇' },
  { word: 'insecticide', phonetic: '/ɪnˈsektɪsaɪd/', meaning: 'n. 杀虫剂', category: 'GRE词汇' },
  { word: 'insecure', phonetic: '/ˌɪnsɪˈkjʊər/', meaning: 'adj. 不安全的', category: '托福词汇' },
  { word: 'insecurity', phonetic: '/ˌɪnsɪˈkjʊərəti/', meaning: 'n. 不安全', category: 'GRE词汇' },
  { word: 'insensate', phonetic: '/ɪnˈsenseɪt/', meaning: 'adj. 无感觉的', category: 'GRE词汇' },
  { word: 'insensible', phonetic: '/ɪnˈsensəbl/', meaning: 'adj. 无感觉的', category: 'GRE词汇' },
  { word: 'insensitive', phonetic: '/ɪnˈsensətɪv/', meaning: 'adj. 不敏感的', category: '托福词汇' },
  { word: 'inseparable', phonetic: '/ɪnˈsepərəbl/', meaning: 'adj. 不可分离的', category: 'GRE词汇' },
  { word: 'insert', phonetic: '/ɪnˈsɜːrt/', meaning: 'v. 插入；n. 插入物', category: '托福词汇' },
  { word: 'insertion', phonetic: '/ɪnˈsɜːrʃn/', meaning: 'n. 插入', category: 'GRE词汇' },
  { word: 'inside', phonetic: '/ɪnˈsaɪd/', meaning: 'n. 内部；adj. 内部的', category: '托福词汇' },
  { word: 'insider', phonetic: '/ɪnˈsaɪdər/', meaning: 'n. 内部人士', category: '托福词汇' },
  { word: 'insidious', phonetic: '/ɪnˈsɪdiəs/', meaning: 'adj. 阴险的', category: 'GRE词汇' },
  { word: 'insight', phonetic: '/ˈɪnsaɪt/', meaning: 'n. 洞察力', category: '托福词汇' },
  { word: 'insightful', phonetic: '/ɪnˈsaɪtfl/', meaning: 'adj. 有洞察力的', category: '托福词汇' },
  { word: 'insignificance', phonetic: '/ɪnˌsɪɡˈnɪfɪkəns/', meaning: 'n. 无足轻重', category: 'GRE词汇' },
  { word: 'insignificant', phonetic: '/ˌɪnsɪɡˈnɪfɪkənt/', meaning: 'adj. 无足轻重的', category: '托福词汇' },
  { word: 'insincere', phonetic: '/ˌɪnsɪnˈsɪər/', meaning: 'adj. 不真诚的', category: 'GRE词汇' },
  { word: 'insincerity', phonetic: '/ˌɪnsɪnˈserəti/', meaning: 'n. 不真诚', category: 'GRE词汇' },
  { word: 'insinuate', phonetic: '/ɪnˈsɪnjueɪt/', meaning: 'v. 暗示', category: 'GRE词汇' },
  { word: 'insinuation', phonetic: '/ɪnˌsɪnjuˈeɪʃn/', meaning: 'n. 暗示', category: 'GRE词汇' },
  { word: 'insipid', phonetic: '/ɪnˈsɪpɪd/', meaning: 'adj. 无味的', category: 'GRE词汇' },
  { word: 'insist', phonetic: '/ɪnˈsɪst/', meaning: 'v. 坚持', category: '托福词汇' },
  { word: 'insistence', phonetic: '/ɪnˈsɪstəns/', meaning: 'n. 坚持', category: 'GRE词汇' },
  { word: 'insistent', phonetic: '/ɪnˈsɪstənt/', meaning: 'adj. 坚持的', category: 'GRE词汇' },
  { word: 'insole', phonetic: '/ˈɪnsəʊl/', meaning: 'n. 鞋垫', category: 'GRE词汇' },
  { word: 'insolent', phonetic: '/ˈɪnsələnt/', meaning: 'adj. 傲慢的', category: 'GRE词汇' },
  { word: 'insoluble', phonetic: '/ɪnˈsɒljəbl/', meaning: 'adj. 不能溶解的', category: 'GRE词汇' },
  { word: 'insolvable', phonetic: '/ɪnˈsɒlvəbl/', meaning: 'adj. 不能解决的', category: 'GRE词汇' },
  { word: 'insomnia', phonetic: '/ɪnˈsɒmniə/', meaning: 'n. 失眠', category: '医学词汇' },
  { word: 'insomniac', phonetic: '/ɪnˈsɒmniæk/', meaning: 'n. 失眠症患者', category: '医学词汇' },
  { word: 'inspect', phonetic: '/ɪnˈspekt/', meaning: 'v. 检查', category: '托福词汇' },
  { word: 'inspection', phonetic: '/ɪnˈspekʃn/', meaning: 'n. 检查', category: '托福词汇' },
  { word: 'inspector', phonetic: '/ɪnˈspektər/', meaning: 'n. 检查员', category: '托福词汇' },
  { word: 'inspiration', phonetic: '/ˌɪnspəˈreɪʃn/', meaning: 'n. 灵感', category: '托福词汇' },
  { word: 'inspire', phonetic: '/ɪnˈspaɪər/', meaning: 'v. 鼓舞；激发', category: '托福词汇' },
  { word: 'inspired', phonetic: '/ɪnˈspaɪərd/', meaning: 'adj. 有灵感的', category: '托福词汇' },
  { word: 'instability', phonetic: '/ˌɪnstəˈbɪləti/', meaning: 'n. 不稳定', category: 'GRE词汇' },
  { word: 'install', phonetic: '/ɪnˈstɔːl/', meaning: 'v. 安装', category: '托福词汇' },
  { word: 'installation', phonetic: '/ˌɪnstəˈleɪʃn/', meaning: 'n. 安装', category: '托福词汇' },
  { word: 'installment', phonetic: '/ɪnˈstɔːlmənt/', meaning: 'n. 分期付款', category: '商务词汇' },
  { word: 'instance', phonetic: '/ˈɪnstəns/', meaning: 'n. 例子', category: '托福词汇' },
  { word: 'instant', phonetic: '/ˈɪnstənt/', meaning: 'adj. 立即的；n. 瞬间', category: '托福词汇' },
  { word: 'instantaneous', phonetic: '/ˌɪnstənˈteɪniəs/', meaning: 'adj. 瞬间的', category: 'GRE词汇' },
  { word: 'instantly', phonetic: '/ˈɪnstəntli/', meaning: 'adv. 立即', category: '托福词汇' },
  { word: 'instead', phonetic: '/ɪnˈsted/', meaning: 'adv. 代替', category: '托福词汇' },
  { word: 'instigate', phonetic: '/ˈɪnstɪɡeɪt/', meaning: 'v. 煽动', category: 'GRE词汇' },
  { word: 'instigation', phonetic: '/ˌɪnstɪˈɡeɪʃn/', meaning: 'n. 煽动', category: 'GRE词汇' },
  { word: 'instill', phonetic: '/ɪnˈstɪl/', meaning: 'v. 滴注；灌输', category: 'GRE词汇' },
  { word: 'instinct', phonetic: '/ˈɪnstɪŋkt/', meaning: 'n. 本能', category: '托福词汇' },
  { word: 'instinctive', phonetic: '/ɪnˈstɪŋktɪv/', meaning: 'adj. 本能的', category: 'GRE词汇' },
  { word: 'institute', phonetic: '/ˈɪnstɪtjuːt/', meaning: 'n. 学院；v. 建立', category: '托福词汇' },
  { word: 'institution', phonetic: '/ˌɪnstɪˈtjuːʃn/', meaning: 'n. 机构', category: '托福词汇' },
  { word: 'institutional', phonetic: '/ˌɪnstɪˈtjuːʃənl/', meaning: 'adj. 制度的', category: 'GRE词汇' },
  { word: 'instruct', phonetic: '/ɪnˈstrʌkt/', meaning: 'v. 指导', category: '托福词汇' },
  { word: 'instruction', phonetic: '/ɪnˈstrʌkʃn/', meaning: 'n. 指导', category: '托福词汇' },
  { word: 'instructive', phonetic: '/ɪnˈstrʌktɪv/', meaning: 'adj. 有教育意义的', category: 'GRE词汇' },
  { word: 'instructor', phonetic: '/ɪnˈstrʌktər/', meaning: 'n. 教练', category: '托福词汇' },
  { word: 'instrument', phonetic: '/ˈɪnstrəmənt/', meaning: 'n. 仪器；乐器', category: '托福词汇' },
  { word: 'instrumental', phonetic: '/ˌɪnstrəˈmentl/', meaning: 'adj. 有帮助的', category: 'GRE词汇' },
  { word: 'insufficient', phonetic: '/ˌɪnsəˈfɪʃnt/', meaning: 'adj. 不足的', category: '托福词汇' },
  { word: 'insular', phonetic: '/ˈɪnsjələr/', meaning: 'adj. 岛屿的；狭隘的', category: 'GRE词汇' },
  { word: 'insulate', phonetic: '/ˈɪnsjʊleɪt/', meaning: 'v. 隔离；绝缘', category: 'GRE词汇' },
  { word: 'insulation', phonetic: '/ˌɪnsjʊˈleɪʃn/', meaning: 'n. 绝缘', category: 'GRE词汇' },
  { word: 'insulator', phonetic: '/ˈɪnsjʊleɪtər/', meaning: 'n. 绝缘体', category: '科技词汇' },
  { word: 'insult', phonetic: '/ɪnˈsʌlt/', meaning: 'v. 侮辱；n. 侮辱', category: '托福词汇' },
  { word: 'insurance', phonetic: '/ɪnˈʃʊərəns/', meaning: 'n. 保险', category: '托福词汇' },
  { word: 'insure', phonetic: '/ɪnˈʃʊər/', meaning: 'v. 保险', category: '托福词汇' },
  { word: 'insurgent', phonetic: '/ɪnˈsɜːrdʒənt/', meaning: 'adj. 叛乱的；n. 叛乱者', category: 'GRE词汇' },
  { word: 'insurmountable', phonetic: '/ˌɪnsərˈmaʊntəbl/', meaning: 'adj. 不可逾越的', category: 'GRE词汇' },
  { word: 'insurrection', phonetic: '/ˌɪnsəˈrekʃn/', meaning: 'n. 起义', category: 'GRE词汇' },
  { word: 'intact', phonetic: '/ɪnˈtækt/', meaning: 'adj. 完整的', category: 'GRE词汇' },
  { word: 'intake', phonetic: '/ˈɪnteɪk/', meaning: 'n. 摄入量', category: 'GRE词汇' },
  { word: 'intangible', phonetic: '/ɪnˈtændʒəbl/', meaning: 'adj. 无形的', category: 'GRE词汇' },
  { word: 'integral', phonetic: '/ˈɪntɪɡrəl/', meaning: 'adj. 完整的；n. 积分', category: 'GRE词汇' },
  { word: 'integrate', phonetic: '/ˈɪntɪɡreɪt/', meaning: 'v. 整合', category: '托福词汇' },
  { word: 'integration', phonetic: '/ˌɪntɪˈɡreɪʃn/', meaning: 'n. 整合', category: '托福词汇' },
  { word: 'integrity', phonetic: '/ɪnˈteɡrəti/', meaning: 'n. 完整；正直', category: 'GRE词汇' },
  { word: 'intellect', phonetic: '/ˈɪntəlekt/', meaning: 'n. 智力', category: 'GRE词汇' },
  { word: 'intellectual', phonetic: '/ˌɪntəˈlektʃuəl/', meaning: 'adj. 智力的；n. 知识分子', category: '托福词汇' },
  { word: 'intelligence', phonetic: '/ɪnˈtelɪdʒəns/', meaning: 'n. 智力；情报', category: '托福词汇' },
  { word: 'intelligent', phonetic: '/ɪnˈtelɪdʒənt/', meaning: 'adj. 聪明的', category: '托福词汇' },
  { word: 'intelligible', phonetic: '/ɪnˈtelɪdʒəbl/', meaning: 'adj. 可理解的', category: 'GRE词汇' },
  { word: 'intend', phonetic: '/ɪnˈtend/', meaning: 'v. 打算', category: '托福词汇' },
  { word: 'intense', phonetic: '/ɪnˈtens/', meaning: 'adj. 强烈的', category: '托福词汇' },
  { word: 'intensify', phonetic: '/ɪnˈtensɪfaɪ/', meaning: 'v. 加剧', category: 'GRE词汇' },
  { word: 'intensity', phonetic: '/ɪnˈtensəti/', meaning: 'n. 强度', category: '托福词汇' },
  { word: 'intensive', phonetic: '/ɪnˈtensɪv/', meaning: 'adj. 密集的', category: '托福词汇' },
  { word: 'intent', phonetic: '/ɪnˈtent/', meaning: 'n. 意图；adj. 专注的', category: 'GRE词汇' },
  { word: 'intention', phonetic: '/ɪnˈtenʃn/', meaning: 'n. 意图', category: '托福词汇' },
  { word: 'intentional', phonetic: '/ɪnˈtenʃənl/', meaning: 'adj. 故意的', category: '托福词汇' },
  { word: 'inter', phonetic: '/ɪnˈtɜːr/', meaning: 'v. 埋葬', category: 'GRE词汇' },
  { word: 'interact', phonetic: '/ˌɪntərˈækt/', meaning: 'v. 互动', category: '托福词汇' },
  { word: 'interaction', phonetic: '/ˌɪntərˈækʃn/', meaning: 'n. 互动', category: '托福词汇' },
  { word: 'interactive', phonetic: '/ˌɪntərˈæktɪv/', meaning: 'adj. 交互的', category: '托福词汇' },
  { word: 'intercede', phonetic: '/ˌɪntərˈsiːd/', meaning: 'v. 调解', category: 'GRE词汇' },
  { word: 'intercept', phonetic: '/ˌɪntərˈsept/', meaning: 'v. 拦截', category: 'GRE词汇' },
  { word: 'interchange', phonetic: '/ˈɪntərtʃeɪndʒ/', meaning: 'v. 交换；n. 交换', category: 'GRE词汇' },
  { word: 'interconnect', phonetic: '/ˌɪntərkəˈnekt/', meaning: 'v. 互相连接', category: 'GRE词汇' },
  { word: 'intercourse', phonetic: '/ˈɪntərkɔːrs/', meaning: 'n. 交往', category: 'GRE词汇' },
  { word: 'interest', phonetic: '/ˈɪntrəst/', meaning: 'n. 兴趣；利益；利息', category: '托福词汇' },
  { word: 'interested', phonetic: '/ˈɪntrəstɪd/', meaning: 'adj. 感兴趣的', category: '托福词汇' },
  { word: 'interesting', phonetic: '/ˈɪntrəstɪŋ/', meaning: 'adj. 有趣的', category: '托福词汇' },
  { word: 'interface', phonetic: '/ˈɪntərfeɪs/', meaning: 'n. 界面', category: '托福词汇' },
  { word: 'interfere', phonetic: '/ˌɪntərˈfɪər/', meaning: 'v. 干涉', category: '托福词汇' },
  { word: 'interference', phonetic: '/ˌɪntərˈfɪərəns/', meaning: 'n. 干涉', category: '托福词汇' },
  { word: 'interim', phonetic: '/ˈɪntərɪm/', meaning: 'adj. 暂时的；n. 过渡期', category: 'GRE词汇' },
  { word: 'interior', phonetic: '/ɪnˈtɪəriər/', meaning: 'n. 内部；adj. 内部的', category: '托福词汇' },
  { word: 'interject', phonetic: '/ˌɪntərˈdʒekt/', meaning: 'v. 插话', category: 'GRE词汇' },
  { word: 'interlace', phonetic: '/ˌɪntərˈleɪs/', meaning: 'v. 交织', category: 'GRE词汇' },
  { word: 'interlock', phonetic: '/ˌɪntərˈlɒk/', meaning: 'v. 连锁', category: 'GRE词汇' },
  { word: 'interloper', phonetic: '/ˈɪntərləʊpər/', meaning: 'n. 闯入者', category: 'GRE词汇' },
  { word: 'interlude', phonetic: '/ˈɪntərluːd/', meaning: 'n. 插曲', category: 'GRE词汇' },
  { word: 'intermediary', phonetic: '/ˌɪntərˈmiːdiəri/', meaning: 'n. 中间人', category: 'GRE词汇' },
  { word: 'intermediate', phonetic: '/ˌɪntərˈmiːdiət/', meaning: 'adj. 中间的', category: '托福词汇' },
  { word: 'interminable', phonetic: '/ɪnˈtɜːrmɪnəbl/', meaning: 'adj. 无止境的', category: 'GRE词汇' },
  { word: 'intermittent', phonetic: '/ˌɪntərˈmɪtənt/', meaning: 'adj. 间歇的', category: 'GRE词汇' },
  { word: 'internal', phonetic: '/ɪnˈtɜːrnl/', meaning: 'adj. 内部的', category: '托福词汇' },
  { word: 'internalize', phonetic: '/ɪnˈtɜːrnəlaɪz/', meaning: 'v. 内化', category: 'GRE词汇' },
  { word: 'international', phonetic: '/ˌɪntərˈnæʃnəl/', meaning: 'adj. 国际的', category: '托福词汇' },
  { word: 'interpersonal', phonetic: '/ˌɪntərˈpɜːrsənl/', meaning: 'adj. 人际的', category: 'GRE词汇' },
  { word: 'interplay', phonetic: '/ˈɪntərpleɪ/', meaning: 'n. 相互作用', category: 'GRE词汇' },
  { word: 'interpret', phonetic: '/ɪnˈtɜːrprɪt/', meaning: 'v. 解释；口译', category: '托福词汇' },
  { word: 'interpretation', phonetic: '/ɪnˌtɜːrprɪˈteɪʃn/', meaning: 'n. 解释', category: '托福词汇' },
  { word: 'interpreter', phonetic: '/ɪnˈtɜːrprɪtər/', meaning: 'n. 口译员', category: '托福词汇' },
  { word: 'interrogate', phonetic: '/ɪnˈterəɡeɪt/', meaning: 'v. 审问', category: 'GRE词汇' },
  { word: 'interrogation', phonetic: '/ɪnˌterəˈɡeɪʃn/', meaning: 'n. 审问', category: 'GRE词汇' },
  { word: 'interrogative', phonetic: '/ˌɪntəˈrɒɡətɪv/', meaning: 'adj. 疑问的', category: 'GRE词汇' },
  { word: 'interrupt', phonetic: '/ˌɪntəˈrʌpt/', meaning: 'v. 打断', category: '托福词汇' },
  { word: 'interruption', phonetic: '/ˌɪntəˈrʌpʃn/', meaning: 'n. 打断', category: '托福词汇' },
  { word: 'intersect', phonetic: '/ˌɪntərˈsekt/', meaning: 'v. 相交', category: 'GRE词汇' },
  { word: 'intersection', phonetic: '/ˌɪntərˈsekʃn/', meaning: 'n. 十字路口', category: '托福词汇' },
  { word: 'intersperse', phonetic: '/ˌɪntərˈspɜːrs/', meaning: 'v. 散布', category: 'GRE词汇' },
  { word: 'interstate', phonetic: '/ˈɪntərsteɪt/', meaning: 'adj. 州际的', category: 'GRE词汇' },
  { word: 'interstellar', phonetic: '/ˌɪntərˈstelər/', meaning: 'adj. 星际的', category: 'GRE词汇' },
  { word: 'intertwine', phonetic: '/ˌɪntərˈtwaɪn/', meaning: 'v. 纠缠', category: 'GRE词汇' },
  { word: 'interval', phonetic: '/ˈɪntərvl/', meaning: 'n. 间隔', category: '托福词汇' },
  { word: 'intervene', phonetic: '/ˌɪntərˈviːn/', meaning: 'v. 干涉', category: 'GRE词汇' },
  { word: 'intervention', phonetic: '/ˌɪntərˈvenʃn/', meaning: 'n. 干预', category: 'GRE词汇' },
  { word: 'interview', phonetic: '/ˈɪntərvjuː/', meaning: 'n. 面试；v. 面试', category: '托福词汇' },
  { word: 'interweave', phonetic: '/ˌɪntərˈwiːv/', meaning: 'v. 交织', category: 'GRE词汇' },
  { word: 'intestate', phonetic: '/ɪnˈtesteɪt/', meaning: 'adj. 未立遗嘱的', category: 'GRE词汇' },
  { word: 'intestine', phonetic: '/ɪnˈtestɪn/', meaning: 'n. 肠', category: '医学词汇' },
  { word: 'intimacy', phonetic: '/ˈɪntɪməsi/', meaning: 'n. 亲密', category: 'GRE词汇' },
  { word: 'intimate', phonetic: '/ˈɪntɪmət/', meaning: 'adj. 亲密的；v. 暗示', category: 'GRE词汇' },
  { word: 'intimidate', phonetic: '/ɪnˈtɪmɪdeɪt/', meaning: 'v. 恐吓', category: 'GRE词汇' },
  { word: 'intimidation', phonetic: '/ɪnˌtɪmɪˈdeɪʃn/', meaning: 'n. 恐吓', category: 'GRE词汇' },
  { word: 'into', phonetic: '/ˈɪntuː/', meaning: 'prep. 进入', category: '托福词汇' },
  { word: 'intolerable', phonetic: '/ɪnˈtɒlərəbl/', meaning: 'adj. 无法忍受的', category: 'GRE词汇' },
  { word: 'intolerance', phonetic: '/ɪnˈtɒlərəns/', meaning: 'n. 不宽容', category: 'GRE词汇' },
  { word: 'intolerant', phonetic: '/ɪnˈtɒlərənt/', meaning: 'adj. 不宽容的', category: 'GRE词汇' },
  { word: 'intonation', phonetic: '/ˌɪntəˈneɪʃn/', meaning: 'n. 语调', category: 'GRE词汇' },
  { word: 'intoxicate', phonetic: '/ɪnˈtɒksɪkeɪt/', meaning: 'v. 使中毒；使陶醉', category: 'GRE词汇' },
  { word: 'intoxication', phonetic: '/ɪnˌtɒksɪˈkeɪʃn/', meaning: 'n. 中毒；陶醉', category: 'GRE词汇' },
  { word: 'intractable', phonetic: '/ɪnˈtræktəbl/', meaning: 'adj. 难处理的', category: 'GRE词汇' },
  { word: 'intransigent', phonetic: '/ɪnˈtrænsɪdʒənt/', meaning: 'adj. 不妥协的', category: 'GRE词汇' },
  { word: 'intransitive', phonetic: '/ɪnˈtrænsətɪv/', meaning: 'adj. 不及物的', category: 'GRE词汇' },
  { word: 'intravenous', phonetic: '/ˌɪntrəˈviːnəs/', meaning: 'adj. 静脉内的', category: '医学词汇' },
  { word: 'intrepid', phonetic: '/ɪnˈtrepɪd/', meaning: 'adj. 无畏的', category: 'GRE词汇' },
  { word: 'intricacy', phonetic: '/ˈɪntrɪkəsi/', meaning: 'n. 错综复杂', category: 'GRE词汇' },
  { word: 'intricate', phonetic: '/ˈɪntrɪkət/', meaning: 'adj. 错综复杂的', category: 'GRE词汇' },
  { word: 'intrigue', phonetic: '/ɪnˈtriːɡ/', meaning: 'v. 激起兴趣；n. 阴谋', category: 'GRE词汇' },
  { word: 'intriguing', phonetic: '/ɪnˈtriːɡɪŋ/', meaning: 'adj. 有趣的', category: 'GRE词汇' },
  { word: 'intrinsic', phonetic: '/ɪnˈtrɪnsɪk/', meaning: 'adj. 内在的', category: 'GRE词汇' },
  { word: 'introduce', phonetic: '/ˌɪntrəˈdjuːs/', meaning: 'v. 介绍', category: '托福词汇' },
  { word: 'introduction', phonetic: '/ˌɪntrəˈdʌkʃn/', meaning: 'n. 介绍', category: '托福词汇' },
  { word: 'introductory', phonetic: '/ˌɪntrəˈdʌktəri/', meaning: 'adj. 介绍的', category: '托福词汇' },
  { word: 'intrude', phonetic: '/ɪnˈtruːd/', meaning: 'v. 侵入', category: 'GRE词汇' },
  { word: 'intrusion', phonetic: '/ɪnˈtruːʒn/', meaning: 'n. 侵入', category: 'GRE词汇' },
  { word: 'intrusive', phonetic: '/ɪnˈtruːsɪv/', meaning: 'adj. 侵入的', category: 'GRE词汇' },
  { word: 'intuition', phonetic: '/ˌɪntjuˈɪʃn/', meaning: 'n. 直觉', category: 'GRE词汇' },
  { word: 'intuitive', phonetic: '/ɪnˈtjuːɪtɪv/', meaning: 'adj. 直觉的', category: 'GRE词汇' },
  { word: 'inundate', phonetic: '/ˈɪnʌndeɪt/', meaning: 'v. 淹没', category: 'GRE词汇' },
  { word: 'inundation', phonetic: '/ˌɪnʌnˈdeɪʃn/', meaning: 'n. 洪水', category: 'GRE词汇' },
  { word: 'inure', phonetic: '/ɪnˈjʊər/', meaning: 'v. 使习惯', category: 'GRE词汇' },
  { word: 'invade', phonetic: '/ɪnˈveɪd/', meaning: 'v. 入侵', category: '托福词汇' },
  { word: 'invader', phonetic: '/ɪnˈveɪdər/', meaning: 'n. 入侵者', category: '托福词汇' },
  { word: 'invalid', phonetic: '/ɪnˈvælɪd/', meaning: 'adj. 无效的；n. 病人', category: '托福词汇' },
  { word: 'invalidate', phonetic: '/ɪnˈvælɪdeɪt/', meaning: 'v. 使无效', category: 'GRE词汇' },
  { word: 'invaluable', phonetic: '/ɪnˈvæljuəbl/', meaning: 'adj. 无价的', category: 'GRE词汇' },
  { word: 'invariable', phonetic: '/ɪnˈveəriəbl/', meaning: 'adj. 不变的', category: 'GRE词汇' },
  { word: 'invariably', phonetic: '/ɪnˈveəriəbli/', meaning: 'adv. 不变地', category: 'GRE词汇' },
  { word: 'invasion', phonetic: '/ɪnˈveɪʒn/', meaning: 'n. 入侵', category: '托福词汇' },
  { word: 'invective', phonetic: '/ɪnˈvektɪv/', meaning: 'n. 谩骂', category: 'GRE词汇' },
  { word: 'inveigh', phonetic: '/ɪnˈveɪ/', meaning: 'v. 猛烈抨击', category: 'GRE词汇' },
  { word: 'inveigle', phonetic: '/ɪnˈveɪɡl/', meaning: 'v. 诱骗', category: 'GRE词汇' },
  { word: 'invent', phonetic: '/ɪnˈvent/', meaning: 'v. 发明', category: '托福词汇' },
  { word: 'invention', phonetic: '/ɪnˈvenʃn/', meaning: 'n. 发明', category: '托福词汇' },
  { word: 'inventive', phonetic: '/ɪnˈventɪv/', meaning: 'adj. 有创造力的', category: 'GRE词汇' },
  { word: 'inventor', phonetic: '/ɪnˈventər/', meaning: 'n. 发明者', category: '托福词汇' },
  { word: 'inventory', phonetic: '/ˈɪnvəntɔːri/', meaning: 'n. 库存', category: '托福词汇' },
  { word: 'inverse', phonetic: '/ɪnˈvɜːrs/', meaning: 'adj. 相反的；n. 相反', category: 'GRE词汇' },
  { word: 'inversion', phonetic: '/ɪnˈvɜːrʃn/', meaning: 'n. 倒置', category: 'GRE词汇' },
  { word: 'invert', phonetic: '/ɪnˈvɜːrt/', meaning: 'v. 使倒置', category: 'GRE词汇' },
  { word: 'invest', phonetic: '/ɪnˈvest/', meaning: 'v. 投资', category: '托福词汇' },
  { word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', meaning: 'v. 调查', category: '托福词汇' },
  { word: 'investigation', phonetic: '/ɪnˌvestɪˈɡeɪʃn/', meaning: 'n. 调查', category: '托福词汇' },
  { word: 'investigator', phonetic: '/ɪnˈvestɪɡeɪtər/', meaning: 'n. 调查员', category: '托福词汇' },
  { word: 'investment', phonetic: '/ɪnˈvestmənt/', meaning: 'n. 投资', category: '托福词汇' },
  { word: 'investor', phonetic: '/ɪnˈvestər/', meaning: 'n. 投资者', category: '托福词汇' },
  { word: 'inveterate', phonetic: '/ɪnˈvetərət/', meaning: 'adj. 根深蒂固的', category: 'GRE词汇' },
  { word: 'invidious', phonetic: '/ɪnˈvɪdiəs/', meaning: 'adj. 惹人厌恶的', category: 'GRE词汇' },
  { word: 'invigilate', phonetic: '/ɪnˈvɪdʒɪleɪt/', meaning: 'v. 监考', category: 'GRE词汇' },
  { word: 'invigorate', phonetic: '/ɪnˈvɪɡəreɪt/', meaning: 'v. 使精力充沛', category: 'GRE词汇' },
  { word: 'invincible', phonetic: '/ɪnˈvɪnsəbl/', meaning: 'adj. 不可战胜的', category: 'GRE词汇' },
  { word: 'inviolable', phonetic: '/ɪnˈvaɪələbl/', meaning: 'adj. 不可侵犯的', category: 'GRE词汇' },
  { word: 'inviolate', phonetic: '/ɪnˈvaɪələt/', meaning: 'adj. 未受侵犯的', category: 'GRE词汇' },
  { word: 'invisible', phonetic: '/ɪnˈvɪzəbl/', meaning: 'adj. 看不见的', category: '托福词汇' },
  { word: 'invitation', phonetic: '/ˌɪnvɪˈteɪʃn/', meaning: 'n. 邀请', category: '托福词汇' },
  { word: 'invite', phonetic: '/ɪnˈvaɪt/', meaning: 'v. 邀请', category: '托福词汇' },
  { word: 'invoice', phonetic: '/ˈɪnvɔɪs/', meaning: 'n. 发票', category: '商务词汇' },
  { word: 'invoke', phonetic: '/ɪnˈvəʊk/', meaning: 'v. 援引', category: 'GRE词汇' },
  { word: 'involuntary', phonetic: '/ɪnˈvɒləntri/', meaning: 'adj. 非自愿的', category: 'GRE词汇' },
  { word: 'involve', phonetic: '/ɪnˈvɒlv/', meaning: 'v. 包括；卷入', category: '托福词汇' },
  { word: 'involved', phonetic: '/ɪnˈvɒlvd/', meaning: 'adj. 涉及的', category: '托福词汇' },
  { word: 'inward', phonetic: '/ˈɪnwərd/', meaning: 'adj. 向内的；adv. 向内', category: '托福词汇' },
  { word: 'iodine', phonetic: '/ˈaɪədiːn/', meaning: 'n. 碘', category: '科技词汇' },
  { word: 'ion', phonetic: '/ˈaɪən/', meaning: 'n. 离子', category: '科技词汇' },
  { word: 'irk', phonetic: '/ɜːrk/', meaning: 'v. 使厌烦', category: 'GRE词汇' },
  { word: 'iron', phonetic: '/ˈaɪərn/', meaning: 'n. 铁；v. 熨', category: '托福词汇' },
  { word: 'ironic', phonetic: '/aɪˈrɒnɪk/', meaning: 'adj. 讽刺的', category: '托福词汇' },
  { word: 'ironically', phonetic: '/aɪˈrɒnɪkli/', meaning: 'adv. 讽刺地', category: '托福词汇' },
  { word: 'irony', phonetic: '/ˈaɪrəni/', meaning: 'n. 讽刺', category: '托福词汇' },
  { word: 'irradiate', phonetic: '/ɪˈreɪdieɪt/', meaning: 'v. 照射', category: 'GRE词汇' },
  { word: 'irrational', phonetic: '/ɪˈræʃənl/', meaning: 'adj. 不合理的', category: 'GRE词汇' },
  { word: 'irreconcilable', phonetic: '/ɪˌrekənˈsaɪləbl/', meaning: 'adj. 不可调和的', category: 'GRE词汇' },
  { word: 'irrecoverable', phonetic: '/ˌɪrɪˈkʌvərəbl/', meaning: 'adj. 无法挽回的', category: 'GRE词汇' },
  { word: 'irredeemable', phonetic: '/ˌɪrɪˈdiːməbl/', meaning: 'adj. 不可挽回的', category: 'GRE词汇' },
  { word: 'irreformable', phonetic: '/ɪrɪˈfɔːrməbl/', meaning: 'adj. 不可改革的', category: 'GRE词汇' },
  { word: 'irregular', phonetic: '/ɪˈreɡjələr/', meaning: 'adj. 不规则的', category: '托福词汇' },
  { word: 'irregularity', phonetic: '/ɪˌreɡjəˈlærəti/', meaning: 'n. 不规则', category: 'GRE词汇' },
  { word: 'irrelevant', phonetic: '/ɪˈreləvənt/', meaning: 'adj. 不相关的', category: '托福词汇' },
  { word: 'irreligious', phonetic: '/ˌɪrɪˈlɪdʒəs/', meaning: 'adj. 不敬神的', category: 'GRE词汇' },
  { word: 'irremediable', phonetic: '/ˌɪrɪˈmiːdiəbl/', meaning: 'adj. 不可治愈的', category: 'GRE词汇' },
  { word: 'irremovable', phonetic: '/ˌɪrɪˈmuːvəbl/', meaning: 'adj. 无法移动的', category: 'GRE词汇' },
  { word: 'irreparable', phonetic: '/ɪˈrepərəbl/', meaning: 'adj. 无法弥补的', category: 'GRE词汇' },
  { word: 'irreplaceable', phonetic: '/ˌɪrɪˈpleɪsəbl/', meaning: 'adj. 不可替代的', category: 'GRE词汇' },
  { word: 'irrepressible', phonetic: '/ˌɪrɪˈpresəbl/', meaning: 'adj. 压抑不住的', category: 'GRE词汇' },
  { word: 'irreproachable', phonetic: '/ɪrɪˈprəʊtʃəbl/', meaning: 'adj. 无可指责的', category: 'GRE词汇' },
  { word: 'irresistible', phonetic: '/ˌɪrɪˈzɪstəbl/', meaning: 'adj. 无法抗拒的', category: 'GRE词汇' },
  { word: 'irresolute', phonetic: '/ɪˈrezəluːt/', meaning: 'adj. 优柔寡断的', category: 'GRE词汇' },
  { word: 'irrespective', phonetic: '/ˌɪrɪˈspektɪv/', meaning: 'adj. 不顾的', category: 'GRE词汇' },
  { word: 'irresponsible', phonetic: '/ˌɪrɪˈspɒnsəbl/', meaning: 'adj. 不负责任的', category: '托福词汇' },
  { word: 'irretrievable', phonetic: '/ˌɪrɪˈtriːvəbl/', meaning: 'adj. 无法挽回的', category: 'GRE词汇' },
  { word: 'irreverence', phonetic: '/ɪˈrevərəns/', meaning: 'n. 不敬', category: 'GRE词汇' },
  { word: 'irreverent', phonetic: '/ɪˈrevərənt/', meaning: 'adj. 不敬的', category: 'GRE词汇' },
  { word: 'irreversible', phonetic: '/ˌɪrɪˈvɜːrsəbl/', meaning: 'adj. 不可逆的', category: 'GRE词汇' },
  { word: 'irrigate', phonetic: '/ˈɪrɪɡeɪt/', meaning: 'v. 灌溉', category: 'GRE词汇' },
  { word: 'irrigation', phonetic: '/ˌɪrɪˈɡeɪʃn/', meaning: 'n. 灌溉', category: 'GRE词汇' },
  { word: 'irritable', phonetic: '/ˈɪrɪtəbl/', meaning: 'adj. 易怒的', category: 'GRE词汇' },
  { word: 'irritate', phonetic: '/ˈɪrɪteɪt/', meaning: 'v. 激怒', category: '托福词汇' },
  { word: 'irritation', phonetic: '/ˌɪrɪˈteɪʃn/', meaning: 'n. 激怒', category: '托福词汇' },
  { word: 'island', phonetic: '/ˈaɪlənd/', meaning: 'n. 岛', category: '托福词汇' },
  { word: 'islander', phonetic: '/ˈaɪləndər/', meaning: 'n. 岛民', category: '托福词汇' },
  { word: 'island', phonetic: '/ˈaɪlənd/', meaning: 'n. 岛屿', category: '托福词汇' },
  { word: 'isolate', phonetic: '/ˈaɪsəleɪt/', meaning: 'v. 隔离', category: '托福词汇' },
  { word: 'isolated', phonetic: '/ˈaɪsəleɪtɪd/', meaning: 'adj. 隔离的', category: '托福词汇' },
  { word: 'isolation', phonetic: '/ˌaɪsəˈleɪʃn/', meaning: 'n. 隔离', category: '托福词汇' },
  { word: 'isotope', phonetic: '/ˈaɪsətəʊp/', meaning: 'n. 同位素', category: '科技词汇' },
  { word: 'issue', phonetic: '/ˈɪʃuː/', meaning: 'n. 问题；v. 发行', category: '托福词汇' },
  { word: 'isthmus', phonetic: '/ˈɪsməs/', meaning: 'n. 地峡', category: 'GRE词汇' },
  { word: 'it', phonetic: '/ɪt/', meaning: 'pron. 它', category: '托福词汇' },
  { word: 'Italian', phonetic: '/ɪˈtæliən/', meaning: 'adj. 意大利的；n. 意大利人', category: '托福词汇' },
  { word: 'italic', phonetic: '/ɪˈtælɪk/', meaning: 'adj. 斜体的；n. 斜体字', category: '托福词汇' },
  { word: 'italicize', phonetic: '/ɪˈtælɪsaɪz/', meaning: 'v. 用斜体印刷', category: 'GRE词汇' },
  { word: 'itch', phonetic: '/ɪtʃ/', meaning: 'v. 痒；n. 痒', category: '托福词汇' },
  { word: 'item', phonetic: '/ˈaɪtəm/', meaning: 'n. 项目', category: '托福词汇' },
  { word: 'itemize', phonetic: '/ˈaɪtəmaɪz/', meaning: 'v. 列出', category: 'GRE词汇' },
  { word: 'itinerary', phonetic: '/aɪˈtɪnərəri/', meaning: 'n. 行程', category: 'GRE词汇' },
  { word: 'its', phonetic: '/ɪts/', meaning: 'pron. 它的', category: '托福词汇' },
  { word: 'itself', phonetic: '/ɪtˈself/', meaning: 'pron. 它自己', category: '托福词汇' },
  { word: 'ivory', phonetic: '/ˈaɪvəri/', meaning: 'n. 象牙', category: '托福词汇' },
  { word: 'ivy', phonetic: '/ˈaɪvi/', meaning: 'n. 常春藤', category: '托福词汇' },
];

async function getCategoryIds(): Promise<Map<string, number>> {
  const { data, error } = await supabase
    .from('vocabulary_categories')
    .select('id, name');
  
  if (error) return new Map();
  
  const map = new Map<string, number>();
  data?.forEach((cat: { id: number; name: string }) => map.set(cat.name, cat.id));
  return map;
}

async function getExistingWords(): Promise<Set<string>> {
  const { data, error } = await supabase
    .from(WORDS_TABLE)
    .select('word');
  
  if (error) return new Set();
  return new Set(data?.map((w: { word: string }) => w.word.toLowerCase()) || []);
}

async function insertWords(words: typeof wordsI, categoryIds: Map<string, number>, existingSet: Set<string>): Promise<number> {
  const defaultCategoryId = categoryIds.get('日常词汇') || 1;
  let inserted = 0;
  const records: Array<{
    word: string;
    phonetic: string;
    meaning: string;
    example_sentence: string;
    category_id: number;
  }> = [];
  
  for (const w of words) {
    const wordLower = w.word.toLowerCase();
    if (existingSet.has(wordLower)) continue;
    
    const categoryId = categoryIds.get(w.category) || defaultCategoryId;
    records.push({
      word: w.word,
      phonetic: w.phonetic,
      meaning: w.meaning,
      example_sentence: '',
      category_id: categoryId,
    });
    inserted++;
  }
  
  if (records.length > 0) {
    const { error } = await supabase.from(WORDS_TABLE).insert(records);
    if (error) {
      console.error('插入失败:', error.message);
      return 0;
    }
  }
  
  return inserted;
}

async function getCurrentCount(): Promise<number> {
  const { count, error } = await supabase
    .from(WORDS_TABLE)
    .select('*', { count: 'exact', head: true });
  return count || 0;
}

async function main() {
  console.log('=== 开始导入 I 字母开头的单词 ===');
  console.log(`预定义单词数量: ${wordsI.length}`);
  
  const categoryIds = await getCategoryIds();
  const existingSet = await getExistingWords();
  console.log(`已存在单词: ${existingSet.size} 个`);
  
  const inserted = await insertWords(wordsI, categoryIds, existingSet);
  
  console.log(`\n=== 导入完成 ===`);
  console.log(`本次导入: ${inserted} 个单词`);
  console.log(`总单词数: ${await getCurrentCount()} 个`);
}

main().catch(console.error);
