// Part 1/4 - 单词数据生成脚本
import { getSupabaseClient } from '../src/storage/database/supabase-client';

const supabase = getSupabaseClient();

// 预定义的单词列表 - Part 1
const wordsData = [
  // A
  { word: 'aberration', phonetic: '/ˌæbəˈreɪʃn/', meaning: 'n. 偏差；反常', category: 'GRE词汇' },
  { word: 'abhor', phonetic: '/əbˈhɔːr/', meaning: 'v. 憎恶；痛恨', category: 'GRE词汇' },
  { word: 'abolish', phonetic: '/əˈbɒlɪʃ/', meaning: 'v. 废除；废止', category: '雅思词汇' },
  { word: 'abrasive', phonetic: '/əˈbreɪsɪv/', meaning: 'adj. 粗糙的；有研磨作用的', category: 'GRE词汇' },
  { word: 'abreast', phonetic: '/əˈbrest/', meaning: 'adv. 并肩；并排', category: '托福词汇' },
  { word: 'abridge', phonetic: '/əˈbrɪdʒ/', meaning: 'v. 缩短；删节', category: 'GRE词汇' },
  { word: 'abstain', phonetic: '/əbˈsteɪn/', meaning: 'v. 戒除；弃权', category: 'GRE词汇' },
  { word: 'acclaim', phonetic: '/əˈkleɪm/', meaning: 'v. 称赞；喝彩', category: '托福词汇' },
  { word: 'accommodate', phonetic: '/əˈkɒmədeɪt/', meaning: 'v. 容纳；使适应', category: '雅思词汇' },
  { word: 'accomplice', phonetic: '/əˈkʌmplɪs/', meaning: 'n. 同谋；帮凶', category: 'GRE词汇' },
  { word: 'accountable', phonetic: '/əˈkaʊntəbl/', meaning: 'adj. 有责任的；可解释的', category: '商务词汇' },
  { word: 'accredit', phonetic: '/əˈkredɪt/', meaning: 'v. 授权；认可', category: '商务词汇' },
  { word: 'accrue', phonetic: '/əˈkruː/', meaning: 'v. 增加；积累', category: 'GRE词汇' },
  { word: 'adamant', phonetic: '/ˈædəmənt/', meaning: 'adj. 坚定不移的', category: 'GRE词汇' },
  { word: 'adept', phonetic: '/əˈdept/', meaning: 'adj. 熟练的；内行的', category: '托福词汇' },
  { word: 'adherent', phonetic: '/ədˈhɪərənt/', meaning: 'n. 拥护者；信徒', category: 'GRE词汇' },
  { word: 'adjacent', phonetic: '/əˈdʒeɪsnt/', meaning: 'adj. 邻近的；毗邻的', category: '雅思词汇' },
  { word: 'admonish', phonetic: '/ədˈmɒnɪʃ/', meaning: 'v. 告诫；警告', category: 'GRE词汇' },
  { word: 'adorn', phonetic: '/əˈdɔːn/', meaning: 'v. 装饰；修饰', category: '托福词汇' },
  { word: 'adversary', phonetic: '/ˈædvəsəri/', meaning: 'n. 对手；敌手', category: 'GRE词汇' },
  { word: 'aesthetic', phonetic: '/iːsˈθetɪk/', meaning: 'adj. 美学的；审美的', category: '雅思词汇' },
  { word: 'affable', phonetic: '/ˈæfəbl/', meaning: 'adj. 和蔼可亲的', category: 'GRE词汇' },
  { word: 'affiliate', phonetic: '/əˈfɪlieɪt/', meaning: 'v. 使附属；加入', category: '商务词汇' },
  { word: 'affinity', phonetic: '/əˈfɪnəti/', meaning: 'n. 密切关系；亲和力', category: 'GRE词汇' },
  { word: 'affluent', phonetic: '/ˈæfluənt/', meaning: 'adj. 富裕的；丰富的', category: '托福词汇' },
  { word: 'aggravate', phonetic: '/ˈæɡrəveɪt/', meaning: 'v. 加重；恶化', category: 'GRE词汇' },
  { word: 'aggregate', phonetic: '/ˈæɡrɪɡət/', meaning: 'n. 总数；合计', category: '商务词汇' },
  { word: 'aghast', phonetic: '/əˈɡɑːst/', meaning: 'adj. 惊骇的；吓呆的', category: 'GRE词汇' },
  { word: 'alacrity', phonetic: '/əˈlækrəti/', meaning: 'n. 敏捷；乐意', category: 'GRE词汇' },
  { word: 'allegiance', phonetic: '/əˈliːdʒəns/', meaning: 'n. 忠诚；效忠', category: 'GRE词汇' },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: 'v. 减轻；缓和', category: '托福词汇' },
  { word: 'allude', phonetic: '/əˈluːd/', meaning: 'v. 暗指；影射', category: 'GRE词汇' },
  { word: 'allure', phonetic: '/əˈljʊər/', meaning: 'n. 诱惑；吸引力', category: 'GRE词汇' },
  { word: 'amalgamate', phonetic: '/əˈmælɡəmeɪt/', meaning: 'v. 合并；混合', category: '商务词汇' },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: 'adj. 模棱两可的', category: '雅思词汇' },
  { word: 'ambivalent', phonetic: '/æmˈbɪvələnt/', meaning: 'adj. 矛盾的；摇摆不定的', category: 'GRE词汇' },
  { word: 'amicable', phonetic: '/ˈæmɪkəbl/', meaning: 'adj. 友好的；和睦的', category: '商务词汇' },
  { word: 'amnesty', phonetic: '/ˈæmnəsti/', meaning: 'n. 大赦；特赦', category: '法律词汇' },
  { word: 'amorous', phonetic: '/ˈæmərəs/', meaning: 'adj. 多情的；恋爱的', category: 'GRE词汇' },
  { word: 'analogous', phonetic: '/əˈnæləɡəs/', meaning: 'adj. 类似的；可比拟的', category: 'GRE词汇' },
  { word: 'anarchy', phonetic: '/ˈænəki/', meaning: 'n. 无政府状态；混乱', category: 'GRE词汇' },
  { word: 'anomaly', phonetic: '/əˈnɒməli/', meaning: 'n. 异常；反常事物', category: 'GRE词汇' },
  { word: 'antagonist', phonetic: '/ænˈtæɡənɪst/', meaning: 'n. 对手；敌手', category: 'GRE词汇' },
  { word: 'antipathy', phonetic: '/ænˈtɪpəθi/', meaning: 'n. 反感；憎恶', category: 'GRE词汇' },
  { word: 'antiquated', phonetic: '/ˈæntɪkweɪtɪd/', meaning: 'adj. 陈旧的；过时的', category: 'GRE词汇' },
  { word: 'apathetic', phonetic: '/ˌæpəˈθetɪk/', meaning: 'adj. 冷漠的；无动于衷的', category: 'GRE词汇' },
  { word: 'apex', phonetic: '/ˈeɪpeks/', meaning: 'n. 顶点；最高点', category: '托福词汇' },
  { word: 'apocalypse', phonetic: '/əˈpɒkəlɪps/', meaning: 'n. 大灾难；世界末日', category: 'GRE词汇' },
  { word: 'apologist', phonetic: '/əˈpɒlədʒɪst/', meaning: 'n. 辩护者', category: 'GRE词汇' },
  { word: 'apparatus', phonetic: '/ˌæpəˈreɪtəs/', meaning: 'n. 设备；机构', category: '托福词汇' },
  { word: 'apprehend', phonetic: '/ˌæprɪˈhend/', meaning: 'v. 逮捕；理解', category: '法律词汇' },
  { word: 'apprise', phonetic: '/əˈpraɪz/', meaning: 'v. 通知；告知', category: 'GRE词汇' },
  { word: 'aptitude', phonetic: '/ˈæptɪtjuːd/', meaning: 'n. 天资；资质', category: '托福词汇' },
  { word: 'arbitrary', phonetic: '/ˈɑːbɪtrəri/', meaning: 'adj. 任意的；武断的', category: '雅思词汇' },
  { word: 'arcane', phonetic: '/ɑːˈkeɪn/', meaning: 'adj. 神秘的；晦涩的', category: 'GRE词汇' },
  { word: 'arduous', phonetic: '/ˈɑːdjuəs/', meaning: 'adj. 艰巨的；费力的', category: 'GRE词汇' },
  { word: 'argot', phonetic: '/ˈɑːɡəʊ/', meaning: 'n. 行话；黑话', category: 'GRE词汇' },
  { word: 'arid', phonetic: '/ˈærɪd/', meaning: 'adj. 干旱的；贫瘠的', category: '托福词汇' },
  { word: 'aristocracy', phonetic: '/ˌærɪˈstɒkrəsi/', meaning: 'n. 贵族；贵族统治', category: 'GRE词汇' },
  { word: 'armament', phonetic: '/ˈɑːməmənt/', meaning: 'n. 军备；武器', category: '科技词汇' },
  { word: 'articulate', phonetic: '/ɑːˈtɪkjuleɪt/', meaning: 'v. 清楚表达； adj. 表达清晰的', category: '托福词汇' },
  { word: 'artifact', phonetic: '/ˈɑːtɪfækt/', meaning: 'n. 人工制品；手工艺品', category: '托福词汇' },
  { word: 'artisan', phonetic: '/ˌɑːtɪˈzæn/', meaning: 'n. 工匠；手艺人', category: '托福词汇' },
  { word: 'ascend', phonetic: '/əˈsend/', meaning: 'v. 攀登；上升', category: '托福词汇' },
  { word: 'ascertain', phonetic: '/ˌæsəˈteɪn/', meaning: 'v. 查明；确定', category: '法律词汇' },
  { word: 'ascetic', phonetic: '/əˈsetɪk/', meaning: 'adj. 苦行的；禁欲的', category: 'GRE词汇' },
  { word: 'asinine', phonetic: '/ˈæsɪnaɪn/', meaning: 'adj. 愚蠢的', category: 'GRE词汇' },
  { word: 'aspiration', phonetic: '/ˌæspəˈreɪʃn/', meaning: 'n. 抱负；渴望', category: '托福词汇' },
  { word: 'assail', phonetic: '/əˈseɪl/', meaning: 'v. 攻击；抨击', category: 'GRE词汇' },
  { word: 'assent', phonetic: '/əˈsent/', meaning: 'n. 同意；赞同', category: '商务词汇' },
  { word: 'assertive', phonetic: '/əˈsɜːtɪv/', meaning: 'adj. 自信的；坚定主张的', category: '商务词汇' },
  { word: 'assuage', phonetic: '/əˈsweɪdʒ/', meaning: 'v. 缓和；平息', category: 'GRE词汇' },
  { word: 'astute', phonetic: '/əˈstjuːt/', meaning: 'adj. 敏锐的；精明的', category: '商务词汇' },
  { word: 'atrocious', phonetic: '/əˈtrəʊʃəs/', meaning: 'adj. 凶恶的；残暴的', category: 'GRE词汇' },
  { word: 'attenuate', phonetic: '/əˈtenjueɪt/', meaning: 'v. 削弱；变细', category: 'GRE词汇' },
  { word: 'audacious', phonetic: '/ɔːˈdeɪʃəs/', meaning: 'adj. 大胆的；勇敢的', category: 'GRE词汇' },
  { word: 'augment', phonetic: '/ɔːɡˈment/', meaning: 'v. 增加；扩大', category: '托福词汇' },
  { word: 'austere', phonetic: '/ɒˈstɪər/', meaning: 'adj. 严峻的；朴素的', category: 'GRE词汇' },
  { word: 'authoritarian', phonetic: '/ɔːˌθɒrɪˈteəriən/', meaning: 'adj. 独裁的；威权的', category: 'GRE词汇' },
  { word: 'autonomous', phonetic: '/ɔːˈtɒnəməs/', meaning: 'adj. 自治的；自主的', category: '托福词汇' },
  { word: 'avarice', phonetic: '/ˈævərɪs/', meaning: 'n. 贪婪', category: 'GRE词汇' },
  { word: 'avenge', phonetic: '/əˈvendʒ/', meaning: 'v. 报复；报仇', category: 'GRE词汇' },
  { word: 'aversion', phonetic: '/əˈvɜːʃn/', meaning: 'n. 厌恶；反感', category: 'GRE词汇' },
  { word: 'avid', phonetic: '/ˈævɪd/', meaning: 'adj. 热切的；贪婪的', category: 'GRE词汇' },
  { word: 'avow', phonetic: '/əˈvaʊ/', meaning: 'v. 公开承认；宣称', category: 'GRE词汇' },
  
  // B
  { word: 'badger', phonetic: '/ˈbædʒər/', meaning: 'v. 纠缠；烦扰', category: 'GRE词汇' },
  { word: 'baffle', phonetic: '/ˈbæfl/', meaning: 'v. 使困惑；难住', category: '托福词汇' },
  { word: 'baleful', phonetic: '/ˈbeɪlfl/', meaning: 'adj. 有害的；邪恶的', category: 'GRE词汇' },
  { word: 'banal', phonetic: '/bəˈnɑːl/', meaning: 'adj. 平庸的；陈腐的', category: 'GRE词汇' },
  { word: 'baneful', phonetic: '/ˈbeɪnfl/', meaning: 'adj. 有毒的；有害的', category: 'GRE词汇' },
  { word: 'bankrupt', phonetic: '/ˈbæŋkrʌpt/', meaning: 'adj. 破产的；v. 使破产', category: '商务词汇' },
  { word: 'baroque', phonetic: '/bəˈrɒk/', meaning: 'adj. 巴洛克式的；复杂的', category: 'GRE词汇' },
  { word: 'barrage', phonetic: '/ˈbærɑːʒ/', meaning: 'n. 弹幕；大量', category: 'GRE词汇' },
  { word: 'barrister', phonetic: '/ˈbærɪstər/', meaning: 'n. 出庭律师', category: '法律词汇' },
  { word: 'bask', phonetic: '/bɑːsk/', meaning: 'v. 晒太阳；享受', category: '托福词汇' },
  { word: 'bastion', phonetic: '/ˈbæstiən/', meaning: 'n. 堡垒；据点', category: 'GRE词汇' },
  { word: 'befuddle', phonetic: '/bɪˈfʌdl/', meaning: 'v. 使迷惑；使糊涂', category: 'GRE词汇' },
  { word: 'begrudge', phonetic: '/bɪˈɡrʌdʒ/', meaning: 'v. 嫉妒；吝惜', category: 'GRE词汇' },
  { word: 'beguile', phonetic: '/bɪˈɡaɪl/', meaning: 'v. 欺骗；迷住', category: 'GRE词汇' },
  { word: 'behemoth', phonetic: '/bɪˈhiːmɒθ/', meaning: 'n. 巨兽；庞然大物', category: 'GRE词汇' },
  { word: 'behold', phonetic: '/bɪˈhəʊld/', meaning: 'v. 注视；观看', category: 'GRE词汇' },
  { word: 'belabor', phonetic: '/bɪˈleɪbər/', meaning: 'v. 过分阐述；痛打', category: 'GRE词汇' },
  { word: 'beleaguer', phonetic: '/bɪˈliːɡər/', meaning: 'v. 围攻；困扰', category: 'GRE词汇' },
  { word: 'belie', phonetic: '/bɪˈlaɪ/', meaning: 'v. 掩饰；证明…为假', category: 'GRE词汇' },
  { word: 'belittle', phonetic: '/bɪˈlɪtl/', meaning: 'v. 贬低；轻视', category: 'GRE词汇' },
  { word: 'belligerent', phonetic: '/bəˈlɪdʒərənt/', meaning: 'adj. 好战的；交战的', category: 'GRE词汇' },
  { word: 'bemoan', phonetic: '/bɪˈməʊn/', meaning: 'v. 悲叹；惋惜', category: 'GRE词汇' },
  { word: 'benevolent', phonetic: '/bəˈnevələnt/', meaning: 'adj. 仁慈的；慈善的', category: '托福词汇' },
  { word: 'benign', phonetic: '/bɪˈnaɪn/', meaning: 'adj. 良性的；温和的', category: '医学词汇' },
  { word: 'bequeath', phonetic: '/bɪˈkwiːð/', meaning: 'v. 遗赠；传下', category: '法律词汇' },
  { word: 'berate', phonetic: '/bɪˈreɪt/', meaning: 'v. 严厉斥责', category: 'GRE词汇' },
  { word: 'bereave', phonetic: '/bɪˈriːv/', meaning: 'v. 使丧失；剥夺', category: 'GRE词汇' },
  { word: 'berserk', phonetic: '/bəˈzɜːk/', meaning: 'adj. 狂暴的；疯狂的', category: 'GRE词汇' },
  { word: 'beseech', phonetic: '/bɪˈsiːtʃ/', meaning: 'v. 恳求；乞求', category: 'GRE词汇' },
  { word: 'beset', phonetic: '/bɪˈset/', meaning: 'v. 困扰；包围', category: 'GRE词汇' },
  { word: 'besiege', phonetic: '/bɪˈsiːdʒ/', meaning: 'v. 围攻；包围', category: 'GRE词汇' },
  { word: 'bestial', phonetic: '/ˈbestiəl/', meaning: 'adj. 野兽的；残忍的', category: 'GRE词汇' },
  { word: 'betroth', phonetic: '/bɪˈtrəʊð/', meaning: 'v. 订婚；许配', category: 'GRE词汇' },
  { word: 'bicameral', phonetic: '/baɪˈkæmərəl/', meaning: 'adj. 两院制的', category: '法律词汇' },
  { word: 'bicker', phonetic: '/ˈbɪkər/', meaning: 'v. 争吵；口角', category: '日常词汇' },
  { word: 'bidirectional', phonetic: '/ˌbaɪdɪˈrekʃənl/', meaning: 'adj. 双向的', category: '科技词汇' },
  { word: 'bigotry', phonetic: '/ˈbɪɡətri/', meaning: 'n. 偏执；盲从', category: 'GRE词汇' },
  { word: 'bilious', phonetic: '/ˈbɪliəs/', meaning: 'adj. 胆汁的；易怒的', category: '医学词汇' },
  { word: 'bizarre', phonetic: '/bɪˈzɑːr/', meaning: 'adj. 奇异的；古怪的', category: '托福词汇' },
  { word: 'blanch', phonetic: '/blɑːntʃ/', meaning: 'v. 使变白；使苍白', category: 'GRE词汇' },
  { word: 'blandishment', phonetic: '/ˈblændɪʃmənt/', meaning: 'n. 奉承；哄诱', category: 'GRE词汇' },
  { word: 'blasphemy', phonetic: '/ˈblæsfəmi/', meaning: 'n. 亵渎；渎神', category: 'GRE词汇' },
  { word: 'blatant', phonetic: '/ˈbleɪtnt/', meaning: 'adj. 明目张胆的', category: 'GRE词汇' },
  { word: 'bleak', phonetic: '/bliːk/', meaning: 'adj. 凄凉的；黯淡的', category: '托福词汇' },
  { word: 'blight', phonetic: '/blaɪt/', meaning: 'n. 枯萎病；v. 破坏', category: 'GRE词汇' },
  { word: 'blithe', phonetic: '/blaɪð/', meaning: 'adj. 快乐的；无忧无虑的', category: 'GRE词汇' },
  { word: 'bloated', phonetic: '/ˈbləʊtɪd/', meaning: 'adj. 肿胀的；傲慢的', category: '医学词汇' },
  { word: 'blunder', phonetic: '/ˈblʌndər/', meaning: 'n. 大错；v. 犯错', category: '托福词汇' },
  { word: 'blurt', phonetic: '/blɜːt/', meaning: 'v. 脱口而出', category: '日常词汇' },
  { word: 'bluster', phonetic: '/ˈblʌstər/', meaning: 'v. 咆哮；虚张声势', category: 'GRE词汇' },
  { word: 'bode', phonetic: '/bəʊd/', meaning: 'v. 预示；预示', category: 'GRE词汇' },
  { word: 'bogus', phonetic: '/ˈbəʊɡəs/', meaning: 'adj. 假冒的；伪造的', category: '日常词汇' },
  { word: 'boisterous', phonetic: '/ˈbɔɪstərəs/', meaning: 'adj. 喧闹的；活跃的', category: 'GRE词汇' },
  { word: 'bolster', phonetic: '/ˈbəʊlstər/', meaning: 'v. 支持；加强', category: '托福词汇' },
  { word: 'bombastic', phonetic: '/bɒmˈbæstɪk/', meaning: 'adj. 浮夸的；言过其实的', category: 'GRE词汇' },
  { word: 'boorish', phonetic: '/ˈbʊərɪʃ/', meaning: 'adj. 粗鲁的；笨拙的', category: 'GRE词汇' },
  { word: 'bootless', phonetic: '/ˈbuːtləs/', meaning: 'adj. 无用的；无益的', category: 'GRE词汇' },
  { word: 'borough', phonetic: '/ˈbʌrə/', meaning: 'n. 区；自治市', category: 'GRE词汇' },
  { word: 'bosom', phonetic: '/ˈbʊzəm/', meaning: 'n. 胸部；怀抱', category: 'GRE词汇' },
  { word: 'bountiful', phonetic: '/ˈbaʊntɪfl/', meaning: 'adj. 慷慨的；丰富的', category: 'GRE词汇' },
  { word: 'bourgeois', phonetic: '/ˈbʊəʒwɑː/', meaning: 'adj. 资产阶级的', category: 'GRE词汇' },
  { word: 'braggart', phonetic: '/ˈbræɡət/', meaning: 'n. 吹牛的人', category: 'GRE词汇' },
  { word: 'brandish', phonetic: '/ˈbrændɪʃ/', meaning: 'v. 挥舞；炫耀', category: 'GRE词汇' },
  { word: 'brash', phonetic: '/bræʃ/', meaning: 'adj. 傲慢的；鲁莽的', category: 'GRE词汇' },
  { word: 'bravado', phonetic: '/brəˈvɑːdəʊ/', meaning: 'n. 虚张声势', category: 'GRE词汇' },
  { word: 'brawn', phonetic: '/brɔːn/', meaning: 'n. 肌肉；体力', category: 'GRE词汇' },
  { word: 'brazen', phonetic: '/ˈbreɪzn/', meaning: 'adj. 厚颜无耻的', category: 'GRE词汇' },
  { word: 'breach', phonetic: '/briːtʃ/', meaning: 'n. 违背；缺口', category: '法律词汇' },
  { word: 'brethren', phonetic: '/ˈbreðrən/', meaning: 'n. 兄弟们；同胞', category: 'GRE词汇' },
  { word: 'brevity', phonetic: '/ˈbrevəti/', meaning: 'n. 简洁；简短', category: 'GRE词汇' },
  { word: 'bridle', phonetic: '/ˈbraɪdl/', meaning: 'v. 抑制；n. 马勒', category: 'GRE词汇' },
  { word: 'brigand', phonetic: '/ˈbrɪɡənd/', meaning: 'n. 土匪；强盗', category: 'GRE词汇' },
  { word: 'brisk', phonetic: '/brɪsk/', meaning: 'adj. 活泼的；轻快的', category: '托福词汇' },
  { word: 'brittle', phonetic: '/ˈbrɪtl/', meaning: 'adj. 易碎的；脆弱的', category: '托福词汇' },
  { word: 'broach', phonetic: '/brəʊtʃ/', meaning: 'v. 提出；开始讨论', category: 'GRE词汇' },
  { word: 'brocade', phonetic: '/brəˈkeɪd/', meaning: 'n. 锦缎', category: 'GRE词汇' },
  { word: 'brochure', phonetic: '/ˈbrəʊʃər/', meaning: 'n. 小册子', category: '商务词汇' },
  { word: 'broker', phonetic: '/ˈbrəʊkər/', meaning: 'n. 经纪人；中间人', category: '商务词汇' },
  { word: 'brood', phonetic: '/bruːd/', meaning: 'v. 沉思；n. 一窝', category: 'GRE词汇' },
  { word: 'brusque', phonetic: '/brʊsk/', meaning: 'adj. 唐突的；粗鲁的', category: 'GRE词汇' },
  { word: 'brutal', phonetic: '/ˈbruːtl/', meaning: 'adj. 残忍的；野蛮的', category: '托福词汇' },
  { word: 'bucolic', phonetic: '/bjuːˈkɒlɪk/', meaning: 'adj. 乡村的；田园的', category: 'GRE词汇' },
  { word: 'buffet', phonetic: '/ˈbʊfeɪ/', meaning: 'n. 自助餐；v. 打击', category: '日常词汇' },
  { word: 'buggy', phonetic: '/ˈbʌɡi/', meaning: 'n. 婴儿车；adj. 有虫的', category: '科技词汇' },
  { word: 'bulge', phonetic: '/bʌldʒ/', meaning: 'n. 膨胀；凸起', category: 'GRE词汇' },
  { word: 'bulwark', phonetic: '/ˈbʊlwək/', meaning: 'n. 堡垒；屏障', category: 'GRE词汇' },
  { word: 'bumptious', phonetic: '/ˈbʌmpʃəs/', meaning: 'adj. 傲慢的；自大的', category: 'GRE词汇' },
  { word: 'bungle', phonetic: '/ˈbʌŋɡl/', meaning: 'v. 搞砸；做坏', category: 'GRE词汇' },
  { word: 'buoyant', phonetic: '/ˈbɔɪənt/', meaning: 'adj. 有浮力的；快乐的', category: '托福词汇' },
  { word: 'burgeon', phonetic: '/ˈbɜːdʒən/', meaning: 'v. 迅速发展；萌芽', category: 'GRE词汇' },
  { word: 'burlesque', phonetic: '/bɜːˈlesk/', meaning: 'n. 讽刺作品；滑稽戏', category: 'GRE词汇' },
  { word: 'burnish', phonetic: '/ˈbɜːnɪʃ/', meaning: 'v. 擦亮；磨光', category: 'GRE词汇' },
  { word: 'burrow', phonetic: '/ˈbʌrəʊ/', meaning: 'v. 挖洞；n. 洞穴', category: '托福词汇' },
  { word: 'bustle', phonetic: '/ˈbʌsl/', meaning: 'v. 忙碌；n. 喧闹', category: '托福词汇' },
];

// 继续下一部分...
export { wordsData };
